[WIP] Append domain name setting follow-up
theforeman/foreman pull request #10014
Opened 2024-01-24 16:45 UTC by Dyrkon

Follow-up fixes.

2024-02-14 11:45 UTC, stejskalleos requested changes

2024-02-14 11:45 UTC, stejskalleos commented on app/models/host/base.rb
>        if Setting[:display_fqdn_for_hosts]
```suggestion
      return name if Setting[:display_fqdn_for_hosts]
```

2024-02-14 11:45 UTC, stejskalleos commented on app/models/host/base.rb
> +        if domain.nil?
```suggestion
return name unless domain
```

2024-03-05 09:09 UTC, stejskalleos commented
I see it's still in WIP, any blockers here?

2024-03-05 15:00 UTC, Dyrkon commented
> I see it's still in WIP, any blockers here?

Yes, there is some internal dispute regarding the way we are going to resolve this.

2024-03-27 09:32 UTC, stejskalleos approved these changes
:green_apple: **LGTM**

Works as expected

2024-03-27 09:32 UTC, merged

2024-03-27 09:32 UTC, stejskalleos commented
Thanks @Dyrkon