Fixes #37016 - don't reference CV / LCE name if nil
theforeman/foreman pull request #10023
Opened 2024-01-29 15:01 UTC by ianballou

The safe navigation doesn't work with older safemode.

To test, try this report with:

    No subs
    SCA mode and subs
    non-SCA mode and subs on hosts

Make sure to test on Foreman 3.9.

2024-01-29 15:05 UTC, ekohl requested changes
I think the PR title/commit message is misleading. It's not removing the safe navigator, but it is dealing with `nil` values.

Other than that, :+1:

2024-01-29 18:57 UTC, wbclark reviewed
Test results on Foreman 3.9.1 with Katello 4.11.0, using a single content host and checking various subscription states

SCA org w/o subscriptions: report contains no rows
SCA org w/ subscriptions: report contains no rows
non-SCA org w/ virtual guest subscription attached: report contains a row showing the host having the virtual subscription attached. LCE and CV are correctly populated
non-SCA org w/ physical subscription attached: report contains a row showing the host having the virtual subscription attached. LCE and CV are correctly populated
non-SCA org w/ no subscriptions attached: report contains no rows

2024-01-29 23:31 UTC, ekohl approved these changes

2024-01-29 23:31 UTC, ekohl commented
Is this still `Refs`? Shouldn't it be `Fixes` now?

2024-01-30 14:30 UTC, ianballou commented
> Is this still `Refs`? Shouldn't it be `Fixes` now?

Yeah, I'm all confused since this is like a cherry-pick but not really. Anyway fixed now.

2024-01-30 14:30 UTC, merged