Fixes #37179 - Clone hostgroup facets when cloning hostgroup
theforeman/foreman pull request #10055
Opened 2024-02-19 15:22 UTC by jeremylenz

When cloning a hostgroup, its facets were not being cloned. Because of this, the hostgroup form would be pre-filled with some attributes, but not all.

This change clones all registered facets when cloning a hostgroup, enabling improvements in plugins such as https://github.com/Katello/katello/pull/10894.

2024-02-19 22:23 UTC, ehelms commented
[test katello]

2024-02-28 17:11 UTC, jeremylenz commented
[test katello]

2024-02-28 17:14 UTC, jeremylenz commented
[test integration]

2024-02-28 20:32 UTC, jeremylenz commented
changed back to `@hostgroup.clone` per @parthaa

2024-02-28 20:49 UTC, parthaa approved these changes
Works well!

2024-02-28 21:44 UTC, parthaa commented
can you add this unit test
```patch
diff --git a/test/controllers/hostgroups_controller_test.rb b/test/controllers/hostgroups_controller_test.rb
index 697729e0e..2fd26b7da 100644
--- a/test/controllers/hostgroups_controller_test.rb
+++ b/test/controllers/hostgroups_controller_test.rb
@@ -38,6 +38,24 @@ class HostgroupsControllerTest < ActionController::TestCase
     assert_template 'new'
   end
 
+  def test_copies_facets
+    hg = hostgroups(:common)
+    hg.stubs(:facet_definitions).returns([OpenStruct.new(name: :mock_facet)])
+    stubbed_facet = OpenStruct.new(attribute_one:"one", two: "two")
+    hg.instance_eval {self.class.attr_accessor :mock_facet}
+    hg.mock_facet = stubbed_facet
+
+    @controller.stubs(:find_resource)
+    @controller.instance_variable_set(:@hostgroup, hg)
+    get :clone, params: { :id => hg.id }, session: set_session_user
+    assert_template 'new'
+    cloned_hg = @controller.instance_variable_get(:@hostgroup)
+    assert_nil cloned_hg.id
+    assert_nil cloned_hg.name
+    assert_equal stubbed_facet, cloned_hg.mock_facet
+    refute_equal stubbed_facet.object_id, cloned_hg.mock_facet.object_id
+  end
+
   def test_edit
     get :edit, params: { :id => hostgroups(:common) }, session: set_session_user
     assert_template 'edit
```

2024-02-28 22:07 UTC, jeremylenz commented
Added test :+1:

2024-02-29 10:29 UTC, ShimShtein requested changes

2024-02-29 10:29 UTC, ShimShtein commented on app/controllers/hostgroups_controller.rb
> +    @hostgroup.facet_definitions.map(&:name).each do |facet_name|
I think you don't need to do the legwork manually, you can use the `SelectiveClone` to do the work for you, similar to the host object: https://github.com/theforeman/foreman/blob/c31702337015ecdf76aaa3053924b57007b8867f/app/models/concerns/facets/managed_host_extensions.rb#L10

2024-03-01 15:50 UTC, parthaa commented on app/controllers/hostgroups_controller.rb
> +    @hostgroup.facet_definitions.map(&:name).each do |facet_name|
thank you @ShimShtein . Sounds like the entire PR can be replaced with
```patch
diff --git a/app/models/concerns/facets/hostgroup_extensions.rb b/app/models/concerns/facets/hostgroup_extensions.rb
index ba05649f2..4259504e0 100644
--- a/app/models/concerns/facets/hostgroup_extensions.rb
+++ b/app/models/concerns/facets/hostgroup_extensions.rb
@@ -6,7 +6,9 @@ module Facets
     include Facets::ModelExtensionsBase
 
     included do
-      configure_facet(:hostgroup, :hostgroup, :hostgroup_id)
+      configure_facet(:hostgroup, :hostgroup, :hostgroup_id) do |facet_config|
+        include_in_clone facet_config.name
+      end
     end
 
     def hostgroup_ancestry_cache

```

2024-03-05 19:00 UTC, jeremylenz commented
@ShimShtein updated :+1:

2024-03-05 19:04 UTC, ShimShtein commented on test/controllers/hostgroups_controller_test.rb
> +  def test_copies_facets
I think this test will belong with all facet behavior tests: https://github.com/theforeman/foreman/blob/a9b9b7d9a2caacb0062e7d4863f26b3ceaa87e22/test/unit/facet_test.rb#L237
This test file already has the proper setup.

2024-03-05 19:34 UTC, jeremylenz commented
@ShimShtein Moved and adjusted the test.

all this time I didn't realize we were running `Hostgroup#clone`, not Rails' `clone`. thanks!

2024-03-05 19:39 UTC, jeremylenz commented
Side note: this appears to still need https://github.com/Katello/katello/pull/10894 in order to work; otherwise I still don't see content view / LCE populated when I clone.

2024-03-10 11:53 UTC, ShimShtein approved these changes

2024-03-10 11:54 UTC, ShimShtein commented
Merging. Thanks @jeremylenz !

2024-03-10 11:55 UTC, merged

2024-03-11 06:39 UTC, evgeni commented
I'm afraid this broke `foreman_puppet`, which fails to boot now:

```
2024-03-10T22:18:19 [W|app|] ForemanPuppet: skipping engine hook (undefined method `include_in_clone' for Hostgroup (call 'Hostgroup.connection' to establish a connection):Class
 | Did you mean?  include_root_in_json)
 | /usr/share/gems/gems/activerecord-6.1.7.7/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
 | /usr/share/foreman/app/models/concerns/facets/hostgroup_extensions.rb:10:in `block (2 levels) in <module:HostgroupExtensions>'
 | /usr/share/foreman/app/models/concerns/facets/model_extensions_base.rb:57:in `register_facet_relation_for_type'
 | /usr/share/foreman/app/models/concerns/facets/model_extensions_base.rb:22:in `block in configure_facet'
 | /usr/share/foreman/app/models/concerns/facets/model_extensions_base.rb:21:in `each'
 | /usr/share/foreman/app/models/concerns/facets/model_extensions_base.rb:21:in `configure_facet'
 | /usr/share/foreman/app/models/concerns/facets/hostgroup_extensions.rb:9:in `block in <module:HostgroupExtensions>'
 | /usr/share/gems/gems/activesupport-6.1.7.7/lib/active_support/concern.rb:136:in `class_eval'
 | /usr/share/gems/gems/activesupport-6.1.7.7/lib/active_support/concern.rb:136:in `append_features'
 | /usr/share/foreman/app/models/hostgroup.rb:13:in `include'
 | /usr/share/foreman/app/models/hostgroup.rb:13:in `<class:Hostgroup>'
 | /usr/share/foreman/app/models/hostgroup.rb:1:in `<top (required)>'
```

2024-03-11 08:15 UTC, evgeni commented
https://github.com/theforeman/foreman/pull/10084