Fix Layout/ArgumentAlignment
theforeman/foreman pull request #10051
Opened 2024-02-16 07:36 UTC by archanaserver

2024-02-20 15:24 UTC, ekohl commented on test/unit/net/dhcp_test.rb
> +>>>>>>> 78b564104 (Fix Layout/ArgumentAlignment)
There's a merge conflict here.

2024-04-05 12:34 UTC, ekohl requested changes
theforeman-rubocop has the following style (https://github.com/theforeman/theforeman-rubocop/blob/a4e936fe00d4b839dc027b939f7d364b14faecd2/rules/style.yml#L4-L6):
```
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2
```

It would be good to copy this over to `.rubocop.yml` so no new violations are introduced before we upgrade. Then when we do upgrade, we can drop the config again.

Otherwise :+1: if you create a Redmine issue.

2024-05-15 09:29 UTC, archanaserver commented
@ekohl does the latest change looks good? then we can move to https://github.com/theforeman/foreman/pull/9982

2024-10-17 02:02 UTC, ehelms approved these changes

2024-10-17 02:03 UTC, merged