Fixes #37222 - Show error message if host fails to save
theforeman/foreman pull request #10077
Opened 2024-03-05 07:25 UTC by Manisha15

2024-03-21 14:14 UTC, ianballou commented
The error shown there might not make sense to users -- would it make sense to pick some errors that you encounter frequently, catch them, and return a warning with some instructions about how to fix the problem? "Content view environment content facets" is a bit of an internal thing.

2024-03-22 07:24 UTC, Manisha15 commented
> The error shown there might not make sense to users -- would it make sense to pick some errors that you encounter frequently, catch them, and return a warning with some instructions about how to fix the problem? "Content view environment content facets" is a bit of an internal thing.

I tried using `:messge` in Katello content_facet model as well but there I would have to provide the error message which is general enough for all errors. The error I encountered was due to selection of wrong lifecycle environment and there is possibility that the above error is thrown for other cases.

I agree that the error message is not very intuitive but that's the only error message which was caught in the host error messages.

2024-03-22 11:14 UTC, ekohl requested changes

2024-03-22 11:14 UTC, ekohl commented on app/controllers/hosts_controller.rb
> +      @host.errors.add(:base, errors.join(', '))
The controller should not change the errors. Shouldn't Katello try to explicitly flag the field that triggered the error so it's highlighted as wrong? And if anything, the view should read the base errors if they're there.

We already have some of that processing:
https://github.com/theforeman/foreman/blob/d309c1f37590fe4df1c7f3992d614e3319a4ed95/app/controllers/application_controller.rb#L311-L325

Another consideration: the API controller won't have the same validation this way.

2024-03-26 13:51 UTC, ianballou commented
Yeah, a second PR to improve the Katello error I think would round this out nicely.

2024-07-02 01:50 UTC, closed without merging