Fix some Style/* cop
theforeman/foreman pull request #10080
Opened 2024-03-06 11:33 UTC by archanaserver

Fixed Style/RedundantAssignment & Style/RedundantFileExtensionInRequire cop.

Check commits for more details

2024-03-21 16:49 UTC, ekohl requested changes

2024-03-21 16:49 UTC, ekohl commented on script/dynflowd
> +
RuboCop is unhappy about this line
```suggestion
```

2024-04-05 12:45 UTC, ekohl requested changes
I'm not sure if the test failures are related. Perhaps they're solved if you rebase.

Also, please open Redmine issues.

2024-06-24 10:21 UTC, ares commented
Needs also a rebase now.

2024-10-17 13:34 UTC, ehelms approved these changes

2024-10-17 13:35 UTC, merged