Fixes #37427 - refactor HostsIndex to map results directly
theforeman/foreman pull request #10093
Opened 2024-03-12 22:00 UTC by jeremylenz

2024-03-15 13:43 UTC, MariaAga requested changes
Nice clean up for the RowSelectTd and helpers!
Why is this adding mapping to the host index page if the mapping already works?

2024-03-15 13:43 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/PF4/TableIndexPage/Table/helpers.js
> +  const keysToColumnNames = columnNamesKeys ?? {};
Should `{}` be `[]` instead? ({} doesn't have forEach)

2024-03-15 13:43 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/PF4/TableIndexPage/Table/helpers.js
> +    keysToColumnNames[key] = columns[key].title;
Can this be a separate object instead of having an array+object mix?

2024-03-18 13:55 UTC, jeremylenz commented
> Why is this adding mapping to the host index page if the mapping already works?

This way you can see what is being rendered in the table in this single file, rather than having to look through 4 files. I think this way is much easier to read and maintain.

2024-03-18 14:06 UTC, jeremylenz commented on webpack/assets/javascripts/react_app/components/PF4/TableIndexPage/Table/helpers.js
> +    keysToColumnNames[key] = columns[key].title;
I realized what I actually meant above. see if this looks better :)

2024-03-18 14:06 UTC, jeremylenz commented
@MariaAga updated, see if that works better for you

2024-03-20 10:21 UTC, MariaAga commented
Yeah the helper makes more sense now
I agree that for the Host index page we can do specific in file mapping since its a special case

2024-03-26 19:37 UTC, parthaa approved these changes
Works well. Tested the basic ops. Like the architecture change.

2024-03-26 19:48 UTC, jeremylenz commented
[test katello]

2024-03-26 20:12 UTC, MariaAga approved these changes

2024-03-26 21:14 UTC, merged