Foreman modal magic
theforeman/foreman pull request #10128
Opened 2024-04-16 15:52 UTC by jeremylenz

2024-05-03 15:25 UTC, jeremylenz commented
Updated package.json with `"@theforeman/vendor": "^13.1.0"` to enable the use of `@patternfly/react-core/next`.

2024-05-03 15:27 UTC, evgeni commented
Packit will still fail, as 13.1.0 ain't packaged yet, but we'll get there

2024-05-06 16:24 UTC, ianballou commented
Testing this PR via https://github.com/Katello/katello/pull/10962 showed no technical issues.

2024-05-07 12:03 UTC, evgeni commented
@jeremylenz you dropped the use of `react/next` again?

2024-05-07 13:57 UTC, jeremylenz commented
@evgeni Nope, that use is in the Katello PR.

2024-05-15 19:45 UTC, parthaa approved these changes
Happy with the changes here. Tested it with Katello PR. Works well :+1:

2024-05-16 11:58 UTC, jeremylenz commented
Re: React on plugins katello/katello failures, see https://github.com/Katello/katello/pull/10962#discussion_r1603201718

2024-05-16 14:35 UTC, jeremylenz commented
I plan to wait til after stabilization week to merge this. Will need an ack from @theforeman/packaging then.

2024-05-22 14:52 UTC, jeremylenz commented
Foreman is now branched. @theforeman/packaging are we good here?

2024-05-22 15:27 UTC, evgeni approved these changes, later dismissed

2024-05-22 15:27 UTC, evgeni commented
(that ack is purely packaging, I did not look at the code)

2024-06-03 19:40 UTC, MariaAga commented
@jeremylenz I'm starting to look over the PR and it took me a while to find the actions buttons since there are 4 dropdowns in the page, not sure if its for this pr, but should we combine some dropdowns? 
![Screenshot from 2024-06-03 20-34-55(1)](https://github.com/theforeman/foreman/assets/30431079/b54de641-bcd1-41d4-80b8-deb90f31d995)

2024-06-04 13:42 UTC, jeremylenz commented
> but should we combine some dropdowns?

All those are in the mockups :shrug: 

They do each have their own purpose:
1) general actions you can do without selecting hosts
2) REX jobs (self-explanatory and not a kebab anyway)
3) actions you can do with multiple hosts selected
4) actions you can do only for the single host in the table row

2024-06-04 15:14 UTC, ekohl commented
> REX jobs (self-explanatory and not a kebab anyway)

Why is REX a special case? Aren't REX jobs just a regular bulk action you can use when you select hosts?

2024-06-04 15:20 UTC, jeremylenz commented
> Why is REX a special case? Aren't REX jobs just a regular bulk action you can use when you select hosts?

"Schedule a Job" is a split button with a dropdown. You can click the button itself without opening the dropdown, which takes you directly to a blank job wizard with the selected hosts pre-filled, or you can select an item from the dropdown, which runs a specific job on those hosts. AFAIK this is similar to the 'Schedule a Job' on the legacy page, so to me it would be inconsistent to remove it and move all the actions somewhere else. It also conforms to the designs we have, which we probably shouldn't alter too much without getting more UX input.

2024-06-04 15:26 UTC, ekohl commented
> "Schedule a Job" is a split button with a dropdown. You can click the button itself without opening the dropdown, which takes you directly to a blank job wizard with the selected hosts pre-filled, or you can select an item from the dropdown, which runs a specific job on those hosts. AFAIK this is similar to the 'Schedule a Job' on the legacy page, so to me it would be inconsistent to remove it and move all the actions somewhere else. It also conforms to the designs we have, which we probably shouldn't alter too much without getting more UX input.

In the existing UI scheduling a job is just a regular bulk host action. It only works if you have selected at least one host.

2024-06-05 18:22 UTC, MariaAga requested changes

2024-06-05 18:22 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/PF4/TableIndexPage/TableIndexPage.js
> +                perPage={Number(perPage) || 20}
since this is repeating 3 times in this file can it be in const in case we ever change it?

2024-06-05 18:28 UTC, MariaAga commented
Also the restrictedSearchQuery doesn't work well, I think the issue is in this pr and not the katello one, but when I search for `name ~ *` it adds more items to the list (in the package wizard host step)

2024-06-06 18:32 UTC, jeremylenz commented
> Also the restrictedSearchQuery doesn't work well, I think the issue is in this pr and not the katello one, but when I search for `name ~ *` it adds more items to the list (in the package wizard host step)

Fixed in Katello. I had somehow stopped passing in `initialSelectedHosts` to `HostReview`.

2024-06-06 18:33 UTC, jeremylenz commented on webpack/assets/javascripts/react_app/components/PF4/TableIndexPage/TableIndexPage.js
> +                perPage={Number(perPage) || 20}
Updated :+1:

2024-06-06 18:50 UTC, jeremylenz commented
rebased

2024-06-07 15:45 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/PF4/TableIndexPage/TableIndexPage.js
> +                perPage={Number(perPage) || 20}
Meant also the page || 1.
Also actually why is this needed? the default value for page is 1 and perPage uses the settings perPage if not defined

2024-06-07 16:21 UTC, MariaAga commented
> Fixed in Katello. I had somehow stopped passing in initialSelectedHosts to HostReview.

I updated both prs and can still select more hosts than the initial selection with `name ~ *` if its by design then please change the wording of `Review and optionally exclude hosts from your selection.`  since hosts can be excluded and also *added*

2024-06-07 16:34 UTC, jeremylenz commented
Sorry, I had committed locally but forgot to push in the Katello PR :flushed:  try again now?

2024-06-07 17:14 UTC, jeremylenz commented
Removed the `Number()` uses. (could have sworn I needed them but it seems to work okay without them?) Also fixed a bug where the selectedCount would be incorrect in select all mode if there are no search results.

2024-06-07 20:20 UTC, MariaAga approved these changes
Looks good to me, but I would like to see that it doesn't break the remidiation wizard with the initialQuery change, and dont have openScap working yet. 
@ofedoren (or @jeremylenz if you have the plugin) Could you just open the openscap table to see that its fine?

2024-06-07 21:00 UTC, jeremylenz commented
Looks like this also will need another @theforeman/packaging ack for some reason.

2024-06-11 14:31 UTC, ofedoren commented
> I would like to see that it doesn't break the remidiation wizard with the initialQuery change

I don't think we use that much in the wizard, we also disabled searchbox there.

> Could you just open the openscap table to see that its fine?

I've checked the wizard and everything seems working just fine without any changes.

2024-06-11 14:47 UTC, evgeni approved these changes
:package:

2024-06-11 14:50 UTC, merged