Fixes #37439 - API 'build_pxe_default' with taxonomies
theforeman/foreman pull request #10160
Opened 2024-05-13 07:48 UTC by stejskalleos

The `hammer template build-pxe-default` command works only when no organization or location is passed.

The fix is to skip `:find_optional_nested_object` for the `build_pxe_default` action, as it does not make sense here.

**How to test**
* Proxy 1 in Default Organization & Default location
* Proxy 2 in Second Organization & Second location
* Run
```
hammer template build-pxe-default --organization-title "Default Organization" --location-title "Default Location"
hammer template build-pxe-default --organization-title "Second Organization" --location-title "Second Location"
```
Check that it works fine

2024-05-16 09:08 UTC, ShimShtein requested changes
Can we also add a test to make sure we are able to build default menu without taxonomies specified explicitly?

Besides that, looks good.

2024-05-17 07:14 UTC, stejskalleos commented
> Can we also add a test to make sure we are able to build default menu without taxonomies specified explicitly?
I kept the original one (without taxonomies) and added new one with them.

2024-05-22 11:48 UTC, stejskalleos commented
@ShimShtein can we merge?

2024-05-22 12:43 UTC, ShimShtein approved these changes

2024-05-22 12:44 UTC, merged