Fixes #37575 - Foreman Table columns sort is inconsistent
theforeman/foreman pull request #10213
Opened 2024-06-19 13:45 UTC by MariaAga

To test you can open the models table in firefox and chrome and see that the order is different before the pr.
Firefox and Chrome implement the sort function differently

2024-06-19 15:30 UTC, ekohl commented
What if both weights are undefined? Should it sort on a secondary parameter like name or id?

2024-06-19 15:57 UTC, MariaAga commented
then it sorts it in the order the columns are in the object provided to the table

2024-06-19 16:21 UTC, ekohl commented
Shouldn't it still return `0` if both are undefined? Because then you can consider them equal.

2024-06-19 17:01 UTC, MariaAga commented
It will return 0 if both undefined since then the first if would be true `columnBWeight === undefined`

2024-06-20 11:08 UTC, ekohl requested changes
What I meant was that it needs to be:
```javascript
if (columnAWeight === undefined && columnBWeight === undefined) {
        return 0;
}
if (columnBWeight === undefined) {
        return -1;
}
if (columnAWeight === undefined) {
        return 1;
}
return columnAWeight - columnBWeight;
```

Because the sort interface says that when it's `0` they should be considered equal. Your current change implies that if `columnBWeight` they're always equal, even if `columnAWeight` isn't undefined.

Another way to look at it is that the function should be its inverse with a swapped order, or `sort(a, b) == -sort(b, a)`.

2024-06-20 12:44 UTC, MariaAga commented
Yeah changed to this logic instead, the weights are sorted in this way, from the doc:
* `weight` - the weight of the column, which determines the order in which columns are displayed. Lower weights are displayed first.

2024-06-20 16:41 UTC, ekohl approved these changes

2024-06-20 16:41 UTC, ekohl commented
@jeremylenz since I proposed the current version, would you mind reviewing?

2024-06-20 20:03 UTC, jeremylenz approved these changes
Tested and LGTM :+1:

2024-06-20 20:03 UTC, merged