Fixes #37636 - remove "@theforeman/test" imports
theforeman/foreman pull request #10239
Opened 2024-07-09 12:56 UTC by MariaAga

Working towards removing theforeman/test, context: https://community.theforeman.org/t/do-we-want-to-keep-foreman-js/37644

2024-09-12 11:41 UTC, MariaAga commented on script/npm_test_plugin.js
> +  }
add comment: if the argument is `--debug` and not a plugin name

2024-09-12 11:48 UTC, MariaAga commented on script/plugin_webpack_directories.js
> +// Get plugin paths with the plugin name, dont assume the plugin path will have the pluin name
typo pluin

2024-09-12 11:50 UTC, MariaAga commented on webpack/jest.config.js
> +// const { modules: foremanJsModules } = require('@theforeman/vendor-core');
remove

2024-09-12 11:57 UTC, MariaAga commented on webpack/theforeman-test.js
> +// replaces @theforeman/test.js
Is a duplicate?

2024-09-12 12:02 UTC, MariaAga commented on script/lint/link-eslint-plugin.js
> +        console.error('Error creating symlink:', err);
Add eslint ignore

2024-09-12 12:05 UTC, MariaAga commented on script/lint/plugin-lint.js
> +//     "lint": "node script/lint/plugin-lint.js"
`"lint": "node script/lint/plugin-lint.js"` -> `"lint": "node ../foreman/script/lint/plugin-lint.js"`

2024-10-09 10:52 UTC, MariaAga commented on script/lint/link-eslint-plugin.js
> +function linkEslintPlugin(runPath = process.cwd()) {
Check npm link

2024-10-21 16:49 UTC, MariaAga commented on script/lint/link-eslint-plugin.js
> +function linkEslintPlugin(runPath = process.cwd()) {
npm link too complicated (need package.json with specific naming, deletes files sometimes) while creating a symlink is simple.

2024-10-30 19:13 UTC, MariaAga commented on package.json
> +    "react-redux-test-utils": "^0.2.0",
remove

2025-03-10 12:03 UTC, MariaAga commented
Check if github actions need to be updated 
EDIT: https://github.com/theforeman/actions/pull/66

2025-03-26 11:26 UTC, MariaAga commented on .github/workflows/plugins_react_tests.yml
> +        working-directory: ${{ github.workspace }}/projects/foreman
Check if needed

2025-03-28 13:21 UTC, MariaAga commented on package-exclude.json
>      "EXCLUDE_NPM_PACKAGES": [
Add all test packages

2025-03-28 13:30 UTC, MariaAga commented on .github/workflows/plugins_react_tests.yml
>          working-directory: ${{ github.workspace }}/projects/plugin
Check if need to run on foreman as well

2025-03-28 15:19 UTC, MariaAga commented on .github/workflows/plugins_react_tests.yml
> +      #   working-directory: ${{ github.workspace }}/projects/foreman
delete

2025-04-02 10:25 UTC, MariaAga commented on .eslintrc
> +    "import/no-extraneous-dependencies": "off",
removed in the next commit

2025-04-02 10:26 UTC, MariaAga commented on script/lint/lint_core_config.js
> +    'import/no-extraneous-dependencies': 'off',
Check if needed

2025-04-02 10:37 UTC, MariaAga commented on script/lint/link-eslint-plugin.js
> +function linkEslintPlugin(runPath = process.cwd()) {
Check rulesdir

2025-04-02 10:40 UTC, MariaAga commented on script/lint/lint_generic_config.js
> +    // '@foreman/custom/require-ouiaid': 'error', TODO: uncomment when the plugins are ready
Check

2025-04-02 10:45 UTC, MariaAga commented on package.json
> +    "lint": "eslint ./webpack ./script",
test if shows errors

2025-04-02 10:49 UTC, MariaAga commented on package.json
> +    "lint": "eslint ./webpack ./script",
they do

2025-04-10 14:13 UTC, MariaAga commented
to do, update `developer_docs/plugins.asciidoc`

2025-04-15 09:07 UTC, ShimShtein commented on webpack/assets/javascripts/react_app/components/ExternalLogout/__tests__/ExternalLogout.test.js
> +import { testComponentSnapshotsWithFixtures } from 'foremanReact/common/testHelpers';
Why are we using `foremanReact/common/testHelpers` here and in other places we use relative path (`../../../../common/testHelpers`)?

2025-04-15 09:07 UTC, ShimShtein commented on script/npm_test_plugin.js
> +    let stderrBuffer = `${pluginPath}: \n`;
Why do we prefix the stderr buffer with the plugin path, but we don't do the same for stdout?

2025-04-15 09:07 UTC, ShimShtein commented on script/npm_test_plugin.js
> +      lines.forEach(line => console.error(line));
Why do we write the errors twice: the moment they appear and on close?
I don't see the same is done for stdout

2025-04-15 09:07 UTC, ShimShtein commented on script/npm_lint_plugins.js
> +  if (pluginLintScript?.includes('tfm-lint')) {
Does it mean that if the plugin does not define lint at all, this branch will be used?

2025-04-15 09:07 UTC, ShimShtein commented on .github/workflows/plugins_react_tests.yml
> +      #   working-directory: ${{ github.workspace }}/projects/foreman
I suppose it's time to delete it :)

2025-04-15 10:25 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/ExternalLogout/__tests__/ExternalLogout.test.js
> +import { testComponentSnapshotsWithFixtures } from 'foremanReact/common/testHelpers';
Honsetly, since doing find and replace `@theforeman/test'` to `foremanReact/common/testHelpers` was easier to do than manually doing a relative path

2025-04-15 11:15 UTC, MariaAga commented on script/npm_lint_plugins.js
> +  if (pluginLintScript?.includes('tfm-lint')) {
If a plugin does not have a lint script in package.json nothing will run 
```
package.json:
...
"scripts": {
    "lint":  SOMETHING
```
The branch options are either: `"lint": "tfm-lint"` or something like `"lint": "npx eslint webpack/",`

2025-04-15 15:49 UTC, MariaAga commented on script/npm_test_plugin.js
> +      lines.forEach(line => console.error(line));
no reason, removed

2025-04-15 15:50 UTC, MariaAga commented on script/npm_test_plugin.js
> +    let stderrBuffer = `${pluginPath}: \n`;
added in stdout

2025-04-15 17:28 UTC, ShimShtein commented on webpack/assets/javascripts/react_app/components/ExternalLogout/__tests__/ExternalLogout.test.js
> +import { testComponentSnapshotsWithFixtures } from 'foremanReact/common/testHelpers';
What do you think, should we standardize to `foremanReact/common/testHelpers` all over the place?

2025-04-15 17:28 UTC, ShimShtein commented on script/lint/link-eslint-plugin.js
> +function linkEslintPlugin(runPath = process.cwd()) {
Please add this as a comment to the code. I feel we will be wondering who and why added this file.
Also, @ekohl, do you think it will be OK given our long-term plans for containers e.t.c.?

2025-04-15 17:28 UTC, ShimShtein commented on script/npm_lint_plugins.js
> +  if (pluginLintScript?.includes('tfm-lint')) {
I think we should also use our default configuration if lint was not specified at all in the plugin.
I am thinking about a plugin that is created after we merge this feature: it will not need to do anything to get the default lint, so why they will define it in the first place?

2025-04-16 06:56 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/ExternalLogout/__tests__/ExternalLogout.test.js
> +import { testComponentSnapshotsWithFixtures } from 'foremanReact/common/testHelpers';
I dont think we should standardize it, as both ways are right, and if we ever regret it it will be harder to move `foremanReact` back into relative. But if we find that we need it in the future it will be easy to move relative import into `foremanReact`

2025-04-16 08:23 UTC, ShimShtein reviewed
We still need to address https://github.com/theforeman/foreman/pull/10239/commits/cc50ed1455d0912c91b3aa25253c896ca9f511ad#r2045132395

2025-04-16 08:23 UTC, ShimShtein commented on .eslintrc.js
> +module.exports = combinedConfig;
nit: empty line at the end of the file

2025-04-16 09:37 UTC, MariaAga commented
> We still need to address https://github.com/theforeman/foreman/commit/cc50ed1455d0912c91b3aa25253c896ca9f511ad#r2045132395

@ShimShtein Not sure where this is suppose to link to? as it just shows me the top of  the commit "Fixes #37639 - Use own lint instead of https://github.com/theforeman"

2025-04-17 12:23 UTC, ofedoren reviewed
> @ShimShtein Not sure where this is suppose to link to? as it just shows me the top of the commit "Fixes #37639 - Use own lint instead of https://github.com/theforeman"

I think Shim meant 

> I think we should also use our default configuration if lint was not specified at all in the plugin.
I am thinking about a plugin that is created after we merge this feature: it will not need to do anything to get the default lint, so why they will define it in the first place?

2025-04-17 12:23 UTC, ofedoren commented on script/npm_lint_plugins.js
> +  // if the argument is --dix and not a plugin name npm lint:plugins katello --fix
nit:
```suggestion
  // if the argument is --fix and not a plugin name npm lint:plugins katello --fix
```

2025-04-27 09:41 UTC, ShimShtein reviewed
Just one small additional comment

2025-04-27 09:41 UTC, ShimShtein commented on script/npm_lint_plugins.js
> +if (passedArgs[0] && passedArgs[0][0] !== '-') {
Please add an empty line after the method declaration and before the actual script

2025-05-08 11:16 UTC, MariaAga commented on script/npm_test_plugin.js
> +      lines.forEach(line => console.error(line));
yes reason, will simplify this function instead on push

2025-05-08 11:16 UTC, MariaAga commented on script/npm_lint_plugins.js
> +  if (pluginLintScript?.includes('tfm-lint')) {
Changed to check if webpack folder exists as a condition for running tests and lint

2025-05-14 19:42 UTC, ShimShtein requested changes

2025-05-14 19:42 UTC, ShimShtein commented on script/npm_lint_plugins.js
> +  const pluginLintScript = pluginDefinesLint(pluginPath);
Shouldn't we do the same thing as we do with lint?
If a plugin defines a `test` script - run it, otherwise use this one?

2025-05-15 11:04 UTC, MariaAga commented on webpack/jest.config.js
> +  testPathIgnorePatterns: [
add .vendor

2025-05-15 11:25 UTC, MariaAga commented on webpack/jest.config.js
> +  testPathIgnorePatterns: [
Also to lint

2025-05-16 11:56 UTC, MariaAga commented
Updated webpack/jest.config.js and script/npm_test_plugin.js to ignore fixtures and gems 
change spawn to exec
and added a message for errors so when users test all plugins they will see a list at the end of which of the runs failed

2025-05-16 15:49 UTC, MariaAga commented on script/npm_lint_plugins.js
> +  const pluginLintScript = pluginDefinesLint(pluginPath);
For tests, we search for a config file and merge it with ours

2025-05-21 16:51 UTC, MariaAga commented
Updated to skip gems in the plugins list, and notify user about it

2025-05-28 09:43 UTC, ShimShtein reviewed
I am getting
```
<--- Last few GCs --->

[483922:0x555dff6ad250]   484320 ms: Scavenge (reduce) 1965.9 (2083.8) -> 1965.5 (2084.1) MB, 17.4 / 0.0 ms  (average mu = 0.150, current mu = 0.030) allocation failure; 
[483922:0x555dff6ad250]   484359 ms: Scavenge (reduce) 1966.2 (2084.1) -> 1965.8 (2084.3) MB, 18.6 / 0.0 ms  (average mu = 0.150, current mu = 0.030) allocation failure; 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x555dfbe02954 node::Abort() [/usr/bin/node]
 2: 0x555dfbc95666 node::OOMErrorHandler(char const*, bool) [/usr/bin/node]
 3: 0x555dfc009fa4 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 4: 0x555dfc00a266 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 5: 0x555dfc1cf299  [/usr/bin/node]
 6: 0x555dfc1d664a  [/usr/bin/node]
 7: 0x555dfc1e6702 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*, v8::GCCallbackFlags) [/usr/bin/node]
 8: 0x555dfc1e6f89 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
```
when running npm test:plugins
Is it something that we expect to happen? Specifically it happens on katello tests

Also there is
```
> katello@1.0.0 lint /home/vagrant/katello
> npx eslint webpack/

Cannot read config file: /home/vagrant/katello/webpack/.eslintrc.js
Error: Could not find ./node_modules/@theforeman/vendor-dev/eslint.extends.js in /home/vagrant/foreman
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! katello@1.0.0 lint: `npx eslint webpack/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the katello@1.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2025-05-28T09_27_08_093Z-debug.log
```
when I run lint:plugins. Is it considered a normal thing?

2025-05-28 09:43 UTC, ShimShtein commented on script/npm_lint_plugins.js
> +Object.keys(dirs).forEach(k => {
Can we move it to `plugin_webpack_directories`? 
something like:
``` js
const skipGems = true;
var dirs = packageJsonDirsObject(skipGems);
```
or
``` js
var dirs = developmentPackageJsonDirs();
```
We will have a single place where we identify that the plugin is a gem. If we would change this logic later, it would be much easier.

2025-05-29 14:32 UTC, MariaAga commented on script/npm_lint_plugins.js
> +Object.keys(dirs).forEach(k => {
Added filterPluginDirectories to plugin_webpack_directories.js

2025-05-29 14:33 UTC, MariaAga commented
For katello error: 
https://github.com/Katello/katello/pull/11395
for " JavaScript heap out of memory" I added process.env.NODE_OPTIONS =
  process.env.NODE_OPTIONS || '--max-old-space-size=8096';

2025-06-06 15:20 UTC, MariaAga commented
rebase

2025-06-08 13:40 UTC, ShimShtein submitted a review, later dismissed

2025-06-08 14:09 UTC, ShimShtein commented
LGTM, @theforeman/packaging , can you give it a final ack?

2025-06-10 10:18 UTC, MariaAga commented
added NODE_OPTIONS to the docs

2025-06-10 10:36 UTC, evgeni commented on .github/workflows/plugins_react_tests.yml
> +          bundler-cache: true
Curious, why did you add this? At this point, neither Foreman nor a Plugin is checked out yet, so bundler won't do anything, as there is no Gemfile.

2025-06-10 10:42 UTC, evgeni commented on .github/workflows/plugins_react_tests.yml
> +        run: npm run test:plugins $(echo ${{ matrix.plugin }} | awk -F'/' '{print $NF}')
```suggestion
        run: npm run test:plugins $PLUGIN_NAME
```

that's the same, right?

2025-06-10 10:44 UTC, evgeni commented on .github/workflows/plugins_react_tests.yml
> +        run: echo "PLUGIN_NAME=$(echo ${{ matrix.plugin }} | awk -F'/' '{print $NF}')" >> "${GITHUB_ENV}"
https://github.com/theforeman/actions/blob/v0/.github/workflows/foreman_plugin_js.yml already expects the plugin name and repository to be separate inputs. would it be beneficial if we declare the matrix above as:
```
plugin:
  - name: foreman-tasks
    repo: theforeman/foreman-tasks
  - name: katello
    repo: Katello/katello
```
and use the more structured data instead of this awk line? (I am not sure using hashes like that works in GitHub actions, and would be OK if you say "Evgeni, go do your own experimental PR" ;) )

2025-06-10 10:46 UTC, evgeni commented on package.json
> +    "victory-legend": "~36.8.6",
does this need to be added to the package exclude list?

2025-06-10 10:46 UTC, evgeni commented on package.json
> +    "react-test-renderer": "^17.0.1",
does this need to be added to the package exclude list?

2025-06-10 10:46 UTC, evgeni commented on package.json
> +    "axios-mock-adapter": "^1.1.7",
does this need to be added to the package exclude list?

2025-06-10 11:01 UTC, MariaAga commented on package.json
> +    "victory-legend": "~36.8.6",
We actually never got an answer in https://github.com/theforeman/foreman/pull/10043/files#r1489694681
So I can copy from the pr and add it? but also not sure if thats the right thing?
Its what Patternfly uses for charts, and in a later pr we're going to use npm overrides to pin them https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

2025-06-10 11:05 UTC, evgeni commented on package.json
> +    "victory-legend": "~36.8.6",
So far, we've been consuming victory via `@theforeman/vendor-core` and thus the pinning here was only for development. Does this change now?

2025-06-10 11:08 UTC, MariaAga commented on package.json
> +    "victory-legend": "~36.8.6",
This was added for the tests, so I'll add it to the exclude list
Once we remove `@theforeman/vendor-core`, should I open a packaging pr to remove vendor and add all its packages?

2025-06-10 11:10 UTC, evgeni commented on package.json
> +    "victory-legend": "~36.8.6",
Depends :)
Once we drop vendor-core, we'll have to package all *direct* dependencies, but I'd assume all indirect ones get vendored (into the direct ones). So we'll probably package pf and pf brings victory?

2025-06-10 11:30 UTC, MariaAga commented on .github/workflows/plugins_react_tests.yml
> +          bundler-cache: true
Took i from here: https://github.com/theforeman/foreman/blob/62b3353e6b557c70f4e1e51f6d2b0de48001c119/.github/workflows/foreman.yml#L82-L86

2025-06-10 13:06 UTC, MariaAga commented on package.json
> +    "victory-legend": "~36.8.6",
added to exclude

2025-06-10 13:06 UTC, MariaAga commented on .github/workflows/plugins_react_tests.yml
> +        run: echo "PLUGIN_NAME=$(echo ${{ matrix.plugin }} | awk -F'/' '{print $NF}')" >> "${GITHUB_ENV}"
It worked :partying_face:

2025-06-10 13:11 UTC, evgeni commented on .github/workflows/plugins_react_tests.yml
> +          bundler-cache: true
Ah yes, but there it happens after Foreman and was checked out, so there is a Gemfile
You can try doing
```yaml
      - name: "Set up Ruby ${{ matrix.ruby }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ github.workspace }}/projects/foreman
```
*after* the "Set up plugin in Foreman" step.

2025-06-10 13:12 UTC, evgeni commented on .github/workflows/plugins_react_tests.yml
> +    name: ${{ matrix.plugin.repo }} with Ruby ${{ matrix.ruby }} and Node ${{ matrix.node }}
```suggestion
    name: ${{ matrix.plugin.name }} with Ruby ${{ matrix.ruby }} and Node ${{ matrix.node }}
```

Given we have the name now, I think this is nicer

2025-06-10 13:12 UTC, evgeni commented on .github/workflows/plugins_react_tests.yml
> +      - name: Install ${{ matrix.plugin.repo }} npm dependencies
```suggestion
      - name: Install ${{ matrix.plugin.name }} npm dependencies
```
same, nicer output :)

2025-06-10 13:12 UTC, evgeni commented on .github/workflows/plugins_react_tests.yml
> +      - name: Run ${{ matrix.plugin.repo }} tests
```suggestion
      - name: Run ${{ matrix.plugin.name }} tests
```

2025-06-10 13:14 UTC, evgeni submitted a review, later dismissed
:package: : ACK

I left a few comments on the workflow, but nothing that can't be done later

2025-06-10 13:17 UTC, MariaAga commented on .github/workflows/plugins_react_tests.yml
> +          bundler-cache: true
If I removed it and the tests worked, does it mean it can stay removed?  or is it a cache thing to help efficiency?

2025-06-10 13:19 UTC, evgeni commented on .github/workflows/plugins_react_tests.yml
> +          bundler-cache: true
If we can cache, it's preferred, as it saves a bit time/bandwidth, but not massively (NPM is slow, Ruby… usually not so)

The cool part is that if you say `bundler-cache: true`, it does two things: it calls `bundle install` *and* it caches, so you save a step (`run: bundle install`) *and* benefit from caching (a bit)

2025-06-10 13:36 UTC, evgeni commented on .github/workflows/plugins_react_tests.yml
> +        working-directory: ${{ github.workspace }}/projects/foreman
this is taken care of by the `bundler-cache: true` above, so can be dropped

2025-06-10 13:38 UTC, evgeni commented on .github/workflows/plugins_react_tests.yml
> +      - run: sudo apt-get -qq -y install build-essential libcurl4-openssl-dev zlib1g-dev libpq-dev libvirt-dev
given `setup-ruby` with `bundler-cache: true` succeeds above, these *seem* not to be necessary.

so you can either drop them, or move before the `setup-ruby` and see what you can drop from the `BUNDLE_WITHOUT` list (realistically tho, I don't expect plugins to need libvirt integration… so… drop?)

2025-06-10 13:43 UTC, evgeni commented on .github/workflows/plugins_react_tests.yml
> +          bundler-cache: true
do the JS tests even boot rails? (if they don't, there is no need for the libvirt gems etc to be present)

2025-06-10 14:12 UTC, MariaAga commented on .github/workflows/plugins_react_tests.yml
> +      - run: sudo apt-get -qq -y install build-essential libcurl4-openssl-dev zlib1g-dev libpq-dev libvirt-dev
Dropped and it seem to work so yay

2025-06-10 14:13 UTC, evgeni approved these changes

2025-06-11 08:30 UTC, merged