Fixes #37696 - Add convert2rhel fact to host reported data facet
theforeman/foreman pull request #10256
Opened 2024-07-29 21:10 UTC by chris1984

Convert2rhel creates a custom fact with an env variable if it got converted through Satellite or through the customer portal. It looks like this:

```bash
[root@toledo8 ~]# cat /etc/rhsm/facts/convert2rhel.facts {
"conversions.version": "1",
"conversions.activity": "conversion",
"conversions.packages.0.nevra": "convert2rhel-0:2.0.0-1.el8.noarch",
"conversions.packages.0.signature": "RSA/SHA256, Thu May 30 13:31:33 2024, Key ID 199e2f91fd431d51",
"conversions.executed": "/usr/bin/convert2rhel",
"conversions.success": true,
"conversions.activity_started": "2024-07-11T17:28:54.281664Z",
"conversions.activity_ended": "2024-07-11T17:48:47.026664Z",
"conversions.source_os.id": "Cerulean Leopard",
"conversions.source_os.name": "AlmaLinux",
"conversions.source_os.version": "8.10",
"conversions.target_os.id": "Ootpa",
"conversions.target_os.name": "Red Hat Enterprise Linux",
"conversions.target_os.version": "8.10",
"conversions.env.CONVERT2RHEL_THROUGH_FOREMAN": "1",
"conversions.run_id": "null"
}
```

We can see that the fact with this PR is not present on the system when looking with pry:

```bash
[12] pry(main)> foo.reported_data
=> #<HostFacets::ReportedDataFacet:0x00007f6a30b9fb30
 id: 19,
 host_id: 18,
 boot_time: Thu, 11 Jul 2024 17:49:26.000000000 UTC +00:00,
 created_at: Mon, 29 Jul 2024 18:36:51.167876000 UTC +00:00,
 updated_at: Mon, 29 Jul 2024 19:30:23.632255000 UTC +00:00,
 virtual: true,
 sockets: 1,
 cores: 1,
 ram: 7953,
 disks_total: nil,
 kernel_version: "4.18.0-553.8.1.el8_10.x86_64",
 bios_vendor: nil,
 bios_release_date: nil,
 bios_version: nil,
 convert2rhel: 1>
```

The convert2rhel team wants that fact reported through RH cloud so they know if they should keep working on enhancing this process and to see how many people are using it.

Once this is in, I will make a PR to RH Cloud to add that into the report we send off.

2024-07-30 13:43 UTC, chris1984 commented
@ekohl here is the pr I made about the facts we talked about yesterday

2024-07-30 13:58 UTC, ekohl requested changes
Please add a test for this in `test/unit/katello/rhsm_fact_parser_test.rb`.

2024-07-30 13:58 UTC, ekohl commented on app/services/katello/rhsm_fact_parser.rb
> +      facts['conversions.env.CONVERT2RHEL_THROUGH_FOREMAN'].to_i
I don't know this fact that well, but what does this actually mean? The fact itself implies it's more like a boolean.

I can see it's set here:

https://github.com/theforeman/foreman_ansible/blob/afd7faa412259f339605e5d419a039a72fb30e3b/app/views/foreman_ansible/job_templates/convert_to_rhel.erb#L30-L31

Then in convert2rhel this gets picked up:
https://github.com/oamg/convert2rhel/blob/d738c1dae0a50e0d0c5a7aad60316505fbf70e36/convert2rhel/breadcrumbs.py#L70-L71
https://github.com/oamg/convert2rhel/blob/d738c1dae0a50e0d0c5a7aad60316505fbf70e36/convert2rhel/breadcrumbs.py#L140-L150

So isn't this better?
```suggestion
    def convert2rhel_though_foreman?
      facts['conversions.env.CONVERT2RHEL_THROUGH_FOREMAN'] == "1"
```

2024-08-05 13:56 UTC, chris1984 commented
After talking with @ShimShtein we decided it was best to go into Katello. Closing this one in favor of the Katello one I made.

2024-08-05 13:56 UTC, closed without merging

2024-08-05 15:36 UTC, chris1984 commented
https://github.com/Katello/katello/pull/11096