PF5
theforeman/foreman pull request #10272
Opened 2024-08-13 13:14 UTC by MariaAga

Needs https://github.com/theforeman/foreman-js/pull/481 & to remove pf5 from package.json

2024-08-19 14:21 UTC, MariaAga commented on webpack/assets/javascripts/react_app/common/colors.scss
> +$pf-v5-color-white: #fff;
Bring back to pf-color-white (was cought automatically by `pf-c` -> `pf-v5-c` replace)

2024-08-20 15:41 UTC, MariaAga commented on package.json
> +    "@patternfly/react-tokens": "^5.1.1",
need to update tabbable to "tabbable": "^6.2.0", as well

2024-11-22 19:01 UTC, kmalyjur requested changes
Except for a few small things I made comments about, everything looks fine, thank you! :partying_face:

2024-11-22 19:01 UTC, kmalyjur commented on app/assets/stylesheets/base-pf4.scss
Maybe the first comment could be updated?

2024-11-22 19:01 UTC, kmalyjur commented on app/assets/stylesheets/patternfly_colors_overrides.scss
> +    }
The icon and "Search and go" text are too light (the text is not well readable)

2024-11-22 19:01 UTC, kmalyjur commented on webpack/assets/javascripts/react_app/components/HostDetails/Audits/index.js
> +  Table /* data-codemods */,
forgotten comment

2024-11-22 19:01 UTC, kmalyjur commented on webpack/assets/javascripts/react_app/components/HostDetails/DetailsCard/index.js
> +          className: undefined,
- hasNoOffset is false by default
- is the className necessary?

2024-11-22 19:01 UTC, kmalyjur commented on webpack/assets/javascripts/react_app/components/HostDetails/Tabs/Details/Cards/TemplatesCard/index.js
> +  Table /* data-codemods */,
forgotten comment

2024-11-22 19:01 UTC, kmalyjur commented on webpack/assets/javascripts/react_app/components/HostDetails/Tabs/Parameters/EditTableRow.js
The pencil icon is not clickable when the table is too small, but that issue was already there before, so it's not in the scope of this PR

2024-11-22 19:01 UTC, kmalyjur commented on webpack/assets/javascripts/react_app/components/HostDetails/Tabs/Parameters/ParametersTable.js
> +  Table /* data-codemods */,
forgotten comment

2024-11-22 19:01 UTC, kmalyjur commented on webpack/assets/javascripts/react_app/components/HostDetails/Tabs/Parameters/ParametersTable.js
> +            <Th aria-label='actions'/>
Should be `"actions"`

2024-11-22 19:01 UTC, kmalyjur commented on webpack/assets/javascripts/react_app/components/HostDetails/Tabs/ReportsTab/ReportsTable.js
> +  Table /* data-codemods */,
forgotten comment

2024-11-22 19:01 UTC, kmalyjur commented on webpack/assets/javascripts/react_app/components/HostDetails/Templates/CardItem/CardTemplate/index.js
> +              className: undefined,
Is this necessary?

2024-11-22 19:01 UTC, kmalyjur commented on webpack/assets/javascripts/react_app/components/Layout/components/TaxonomySwitcher/TaxonomyDropdown.js
>      setSearchValue(event.target.value);
I get `Uncaught TypeError: Cannot read properties of undefined (reading 'value')` when trying to type into the search bar, but idk if it's this PR's fault

2024-11-22 19:01 UTC, kmalyjur commented on webpack/assets/javascripts/react_app/components/PF4/TableIndexPage/Table/Table.js
> +  Table as PFTable /* data-codemods */,
forgotten comment

2024-11-22 19:01 UTC, kmalyjur commented on webpack/assets/javascripts/react_app/components/SearchBar/SearchAutocomplete.js
There is unnecessary `<h1 class="pf-v5-c-menu__group-title"></h1>` which creates a blank space:
![image](https://github.com/user-attachments/assets/0f23759d-761d-4288-9344-c104d2c29b1c)

2024-11-22 19:01 UTC, kmalyjur commented on webpack/assets/javascripts/react_app/components/PF4/TableIndexPage/Table/Table.js
> +  };
The functionality is fine, however, when opening the table kebab, the "Edit" button looks like it's selected and the mouse on the "Change content..." looks like it's clickable:
![image](https://github.com/user-attachments/assets/5e7b5741-5f37-48f7-a48a-6cda42932566)

2024-11-25 15:44 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/HostDetails/Tabs/Parameters/EditTableRow.js
That would be for a different PR as its not a small fix :+1:

2024-11-25 16:09 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/Layout/components/TaxonomySwitcher/TaxonomyDropdown.js
>      setSearchValue(event.target.value);
it was, fixed it

2024-11-26 13:53 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/PF4/TableIndexPage/Table/Table.js
> +  };
Fixed  both, thanks

2024-11-26 13:54 UTC, MariaAga commented
Thanks @kmalyjur for the review, all should be fixed now. I'll open a seperate PR for host page 
> The pencil icon is not clickable when the table is too small, but that issue was already there before, so it's not in the scope of this PR

2024-11-27 11:24 UTC, kmalyjur approved these changes
Thank you! I'm just not sure about some of the not-passing checks, but I'm certain you'll figure it out :)

2024-11-27 14:07 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/HostsIndex/index.js
> +      autoFocus: true,
Need to remove

2024-11-27 17:42 UTC, MariaAga commented
The checks are mostly failing due to this PR not having the correct foreman-js version, which will only be available once the foreman-js PR is merged. and also will need to do a packaging PR

2025-01-07 18:41 UTC, sjha4 commented
Functionally this has been working well on foreman and katello pages..Ack on this outside of dependency related CI issues..

2025-01-08 15:39 UTC, sjha4 approved these changes
The pages are loading correctly and all the pages look good from everything I tested..Changes make sense for the upgrade..Ack.. 👍🏼

2025-01-10 15:02 UTC, MariaAga commented
Updated PR to include new components that were added in the last 5 months

2025-01-15 12:58 UTC, evgeni commented on package.json
> +    "tabbable": "^6.2.0",
Note to self: this doesn't need packaging.

2025-01-15 12:59 UTC, evgeni commented on package.json
> +    "@patternfly/react-tokens": "^5.1.1",
@MariaAga do you need help packaging those?

2025-01-15 12:59 UTC, ogajduse commented
@theforeman/packaging

2025-01-15 13:10 UTC, evgeni commented on package.json
> +    "@patternfly/react-tokens": "^5.1.1",
or will it be vendored inside `foreman-js` and we won't need packaging these separately?

2025-01-15 13:14 UTC, MariaAga commented on package.json
> +    "@patternfly/react-tokens": "^5.1.1",
It will be inside foreman-js

2025-01-15 13:17 UTC, evgeni commented on package.json
> +    "@patternfly/react-tokens": "^5.1.1",
okay, so the change here is just temporarily until there is a foreman-js release out with those changes? and we don't package `tabbable`, so you *technically* don't need any packaging ACK ;-)
(GH will still want it, so, once there is a foreman-js release out, and the version requirement was bumped here, you get it)

2025-01-15 13:18 UTC, MariaAga commented on package.json
> +    "@patternfly/react-tokens": "^5.1.1",
Yes, thanks

2025-01-15 14:04 UTC, ekohl commented
Do I get it right that this adds patternfly 5, but doesn't remove any older version? So now we have yet another front end framework in place?

2025-01-15 15:28 UTC, MariaAga commented
@ekohl 

> Do I get it right that this adds patternfly 5, but doesn't remove any older version? So now we have yet another front end framework in place?

Nope, it removes it in foreman-js "Needs https://github.com/theforeman/foreman-js/pull/481 & to remove pf5 from package.json"

2025-03-06 13:12 UTC, evgeni approved these changes
:package: ack

2025-03-06 14:05 UTC, evgeni commented
and just to keep a log, the packaging is at https://github.com/theforeman/foreman-packaging/pull/11837 so whenever this gets merged, we're ready

2025-03-06 14:10 UTC, ofedoren approved these changes

2025-03-06 14:10 UTC, ofedoren commented on app/assets/stylesheets/base-pf4.scss
> +  font-family: var(--pf-v5-global--FontFamily--text);
~Since there are explicit versioning tags in class names, should we drop `pf4` from the file name?.. Or since there is already `base.scss`, maybe this file should be `base-pf-latest` or something. Just a suggestion, not a requirement at all.~

At the top of this file it says `This file exists to make pf3 compatible with pf4.`. Since we're migrating to PF5, should this file exist at all?

2025-03-06 14:49 UTC, merged