Fixes #37738 - explicitly stringify major/minor for Ubuntu
theforeman/foreman pull request #10279
Opened 2024-08-16 10:15 UTC by evgeni

We stringify these anyway on save, but here it's also used for
searching, and that fails to find the existing OS when searching with
minor=nil.

When the existing OS is not found, a new one is created, but that fails
to save as the name/major/minor combination already exists and that
breaks fact uploads.

Fixes: d690fa772475adc612ca11f6bd3a0209a8133126

2024-08-16 10:17 UTC, evgeni commented
cc @sbernhard @goarsna

2024-08-16 10:20 UTC, sbernhard approved these changes
Make sense. Thank you!

2024-08-16 10:21 UTC, evgeni commented on app/services/puppet_fact_parser.rb
> +        minor = os_minor_version.to_s
obviously the `.to_s` can also directly in those functions, I have no preference.

2024-08-16 10:36 UTC, ekohl requested changes
:+1: but please make it `Refs #36547` since that hasn't been released yet.

2024-08-16 11:44 UTC, ekohl approved these changes
This is an interesting failure that looks unrelated:
```
 [MinitestRetry] retry 'test_0002_Apipie DSL docs URL should be successful' count: 1,  msg: FrozenError: can't modify frozen String: ""
    lib/foreman/middleware/libvirt_connection_cleaner.rb:9:in `call'
    lib/foreman/middleware/telemetry.rb:10:in `call'
    lib/foreman/middleware/logging_context_session.rb:22:in `call'
    lib/foreman/middleware/logging_context_request.rb:11:in `call'
    test/integration/apipie_test.rb:10:in `block in <class:ApipieIntegrationTest>'
```

Sadly it happens somewhere and middleware is not providing a useful traceback.

@ofedoren have you seen this before?

2024-08-16 12:00 UTC, merged

2024-08-20 05:52 UTC, goarsna commented
Thanks for fixing this, @evgeni

2024-08-20 08:57 UTC, ofedoren commented
> This is an interesting failure that looks unrelated:
> 
> ```
>  [MinitestRetry] retry 'test_0002_Apipie DSL docs URL should be successful' count: 1,  msg: FrozenError: can't modify frozen String: ""
>     lib/foreman/middleware/libvirt_connection_cleaner.rb:9:in `call'
>     lib/foreman/middleware/telemetry.rb:10:in `call'
>     lib/foreman/middleware/logging_context_session.rb:22:in `call'
>     lib/foreman/middleware/logging_context_request.rb:11:in `call'
>     test/integration/apipie_test.rb:10:in `block in <class:ApipieIntegrationTest>'
> ```
> 
> Sadly it happens somewhere and middleware is not providing a useful traceback.
> 
> @ofedoren have you seen this before?

I'm afraid I have not :/