Fixes #37731 - Display correct network at the host/edit page after importing the host
theforeman/foreman pull request #10274
Opened 2024-08-14 09:18 UTC by girijaasoni

…porting a host

2024-08-19 09:23 UTC, girijaasoni commented
@ShimShtein @ekohl @stejskalleos @MariaAga @nofaralfasi 
This PR is ready for review

2024-08-19 10:25 UTC, nofaralfasi requested changes
This code isn’t working for me. During the VM import, the correct values appear on the host edit page in the interface tab. However, once the import is complete, if I return to the edit form, the values are incorrect.

2024-08-21 13:24 UTC, girijaasoni commented
> This code isn’t working for me. During the VM import, the correct values appear on the host edit page in the interface tab. However, once the import is complete, if I return to the edit form, the values are incorrect.

As discussed in our meetup, this is a separate issue and I will create a new bug for the same.

2024-08-28 10:46 UTC, nofaralfasi reviewed
The commit message for this PR is unclear. This fix also affects the values displayed after the host import. Could you please update the message to better reflect this?

2024-08-29 11:39 UTC, girijaasoni commented
> The commit message for this PR is unclear. This fix also affects the values displayed after the host import. Could you please update the message to better reflect this?

updated

2024-08-29 12:13 UTC, nofaralfasi commented
> > The commit message for this PR is unclear. This fix also affects the values displayed after the host import. Could you please update the message to better reflect this?
> 
> updated

I don't think you fully understand my point. This PR also affects existing VMware hosts in Foreman.

2024-09-03 11:50 UTC, nofaralfasi commented
After discussing it with @ShimShtein, it seems that removing `var providerSpecificNICInfo = null;` from `app/assets/javascripts/host_edit_interfaces.js` resolves an issue that only occurs in the development environment, but not in production. We suspect this is related to the order in which the JavaScript is rendered, which differs between these environments.

2024-09-03 11:52 UTC, nofaralfasi approved these changes

2024-09-03 11:53 UTC, merged