Revert "Fixes #37433 - Set indentation when calling subscription_manager_setup"
theforeman/foreman pull request #10289
Opened 2024-08-27 10:04 UTC by stejskalleos

This reverts commit aa8f66f2f442602f48980fb037c003d13addc9ce.

The change is breaking the provisioning of RHEL 8.y machines.

2024-08-27 10:35 UTC, stejskalleos commented
@ShimShtein @ekohl Since the original change is breaking multiple critical features, I think we should revert it and find a different fix.

2024-08-27 21:05 UTC, ekohl approved these changes
Agreed, and we should cherry pick this to 3.12. While doing so, we shouldn't forget to update the Redmine issue to reflect it was reverted.

2024-08-28 08:45 UTC, stejskalleos commented
@ekohl I created a [new Redmine](https://projects.theforeman.org/issues/37766) ticket since the original one was already released in 3.12.
After merge I'll cherry-pick it to 3.12 and update the original ticket

2024-08-28 09:47 UTC, ekohl requested changes
> @ekohl I created a [new Redmine](https://projects.theforeman.org/issues/37766) ticket since the original one was already released in 3.12.

3.12 is not GA yet. Please use the original Redmine issue.

2024-08-28 09:51 UTC, stejskalleos commented
> 3.12 is not GA yet. 

Oh yeah, the branching was just a few weeks ago. 
The commit message has been updated; I will close the new issue.

2024-08-28 09:57 UTC, ekohl approved these changes
Thanks!

2024-08-28 10:26 UTC, merged