WIP Fixes #TODO - Don't apply the compute profile when updating host
theforeman/foreman pull request #10291
Opened 2024-08-28 09:09 UTC by stejskalleos

**HEAVILY WIP**

2024-08-28 12:23 UTC, sbernhard commented
Thanks, I think this makes totally sense!

2024-08-29 13:33 UTC, ekohl commented
Further discussion in https://community.theforeman.org/t/rfc-dont-apply-the-compute-profile-when-updating-the-host/39278.

2024-09-11 11:58 UTC, nofaralfasi requested changes
Failing tests seem related.

2024-09-11 13:21 UTC, stejskalleos commented
For the tracking of upcoming changes, I created a [new tracker issue](https://projects.theforeman.org/issues/37800)

2024-09-11 15:41 UTC, nofaralfasi commented
> For the tracking of upcoming changes, I created a [new tracker issue](https://projects.theforeman.org/issues/37800)

I think you meant to use this link: https://projects.theforeman.org/issues/37806.

2024-09-12 06:49 UTC, stejskalleos commented
Failed tests for Katello are unrelated; they are failing due to Zeitwerk changes (IMO).
@nofaralfasi, feel free to merge if you are okay with it; I'll leave the final decision up to you.

2024-09-12 08:00 UTC, nofaralfasi commented
I'm considering whether we should add a test for this change. @stejskalleos WDYT?

2024-09-12 09:56 UTC, stejskalleos commented
> I'm considering whether we should add a test for this change. @stejskalleos WDYT?

Yeah make sense. I will add it.

2024-09-12 11:19 UTC, stejskalleos commented
And it's all green!

2024-09-19 06:04 UTC, stejskalleos commented
@nofaralfasi can we merge?

2024-09-19 09:42 UTC, nofaralfasi approved these changes

2024-09-19 09:42 UTC, merged