Fixes #37823 - Add Secure Boot and Virtual TPM support for VMware
theforeman/foreman pull request #10324
Opened 2024-09-17 17:34 UTC by nofaralfasi

Dependent on:
* https://github.com/theforeman/foreman/pull/10321

2024-09-18 09:17 UTC, nofaralfasi commented
While testing this PR, I discovered a pre-existing bug on the `compute_attributes` form where the Automatic firmware option is not functioning correctly. I’ve created a new issue to track and address this problem: [Issue #37834](https://projects.theforeman.org/issues/37834).

2024-12-05 09:46 UTC, stejskalleos requested changes
The combination `BIOS+PXELinux BIOS` works fine, but `UEFI + Grub2 UEFI` or `Secure Boot` always fails with:
```
2024-12-05T04:43:11 [W|app|41503fe0] Failed to create a compute vmware (VMware) instance molly-haugland.rhos-01.prod.psi.rdu2.redhat.com: RuntimeFault: RuntimeFault.summary
 41503fe0 |  
2024-12-05T04:43:11 [I|app|41503fe0] Backtrace for 'Failed to create a compute vmware (VMware) instance molly-haugland.rhos-01.prod.psi.rdu2.redhat.com: RuntimeFault: RuntimeFault.summary
 41503fe0 |  ' error (RbVmomi::Fault): RuntimeFault: RuntimeFault.summary
 41503fe0 | /usr/share/gems/gems/rbvmomi2-3.7.1/lib/rbvmomi/vim/Task.rb:15:in `wait_for_completion'
 41503fe0 | /usr/share/gems/gems/fog-vsphere-3.7.0/lib/fog/vsphere/requests/compute/create_vm.rb:71:in `create_vm_on_storage_pod'
 41503fe0 | /usr/share/gems/gems/fog-vsphere-3.7.0/lib/fog/vsphere/requests/compute/create_vm.rb:39:in `create_vm'
 41503fe0 | /usr/share/gems/gems/fog-vsphere-3.7.0/lib/fog/vsphere/models/compute/server.rb:314:in `save'
 41503fe0 | /usr/share/foreman/app/models/compute_resources/foreman/model/vmware.rb:518:in `create_vm'
```

Tested on the latest stream, changes deployed with packit. I'll share instance details in PM.

2024-12-05 09:46 UTC, stejskalleos commented on test/models/compute_resources/vmware_test.rb
> +      assert_empty @cr.errors.full_messages
```suggestion
      assert_empty @cr.errors
```

Nit: Isn't this enough to check?

2024-12-09 14:01 UTC, stejskalleos approved these changes
The previous error was caused by a lack of configuration on the Vcenter side.

:green_apple: Now it works as expected.

2024-12-09 14:01 UTC, merged

2024-12-09 14:01 UTC, stejskalleos commented
Thanks @nofaralfasi and everyone involved!