Fixes #13873 - Add UI extension point to show facets.
theforeman/foreman pull request #3229
Opened 2016-02-24 13:55 UTC by ShimShtein

This commit adds following extension points to the UI:
**in `hosts/_form.html.erb`**: For each facet that is connected to a host, it will create a tab for it. The framework will try to render facet object itself, so it expects the proper partial template to exist. For example in puppet_facet, it will try to find `app/views/puppet_facets/_puppet_facet.html.erb`. Additionally it will show any tab that was specified during facet's registration by invoking the `tabs` method.

**in `hosts/_list.html.erb`**: There are two extension points there, one to add additional column headers, and one to add additional column data. In both cases the framework looks for a specific paths: `<plural_facet_name>/host/_list_headers.html.erb` for the headers and `<plural_facet_name>/host/_list.html.erb` for the values.

2016-02-28 09:10 UTC, ShimShtein commented
Fixed test and added another one to check skipping facets with missing template.

2016-06-30 10:12 UTC, iNecas commented
What's state of this PR, is this a prerequisite for Puppet optional work?

2016-06-30 11:58 UTC, ShimShtein commented
It will be at a much later state, since it involves changes to the current UI. Currently I am trying to avoid such changes.

2017-05-11 06:53 UTC, ares commented
@ShimShtein what is the plan here? from the last comment, I'm not sure whether you will need this later or we should get this in. In any case, it needs rebasing.

2017-11-01 22:57 UTC, timogoebel commented
@ShimShtein: What is the status of this PR? Are you going to pick this up again? Just asking, because I could need the added functionality.

2017-11-06 08:47 UTC, ShimShtein commented
@timogoebel If you need this, I can rebase it (the rebase does not look too awful).

However, I think we should open this to mailing list discussion, since we already intend to do host form redesign. I wouldn't want to add even more features that will cause even deeper feature gap for the design. I will open the thread on dev list and link it here a bit later today.

2017-11-06 08:51 UTC, timogoebel commented
@ShimShtein: Thanks. I can also work with https://github.com/theforeman/foreman/pull/4979. I'll take whatever goes in first.

2017-11-07 09:47 UTC, ShimShtein commented
@timogoebel, as promised [here](https://groups.google.com/forum/#!topic/foreman-dev/oqbkuOAkISc) is the thread about the topic.

On a personal note, for your needs, I would prefer the second approach. As a side effect it will make more extension points for facets framework, that I will be able to use later on, no matter what course the thread will take.

2017-11-13 11:41 UTC, ShimShtein commented
Rebased for the discussion.

2017-11-15 14:02 UTC, timogoebel requested changes
@ShimShtein: I went through the code and left some comments. Thanks for doing this.

2017-11-15 14:02 UTC, timogoebel commented on app/assets/javascripts/host_edit.js
> +function disableFacet(name) {
We should move this to webpack. Maybe `tfm.facets.` ?

2017-11-15 14:02 UTC, timogoebel commented on app/views/hosts/_list.html.erb
> +      <%= render "#{config.name.to_s.pluralize}/host/list_headers" if lookup_context.find_all("list_headers", "#{config.name.to_s.pluralize}/host/", true).any? %>
We should add a helper for this. Or better two.
Something like:

`render_if_template_exists "#{config.name.to_s.pluralize}/host/list_headers"`

and
```ruby
def render_if_template_exists(template)
  render template if template_exists?(templete)
end

def template_exists?(templete)
  lookup_context.find_all("list_headers", "#{config.name.to_s.pluralize}/host/", true).any?
end
```

2017-11-15 14:02 UTC, timogoebel commented on app/helpers/hosts_helper.rb
> +      disable_tab(group) +
We should talk about this. Is it safe to assume that every developer wants to use this functionality?

2017-11-15 14:02 UTC, timogoebel commented on app/helpers/hosts_helper.rb
> +      "Manage"
This needs i18n. `_('Manage')`

2017-11-16 12:38 UTC, ShimShtein commented
On the second pass - I probably should use pagelets here, instead of explicit registry. I'll change the PR.

2017-12-31 13:36 UTC, ohadlevy commented
whats the status of this pr? @ares this issue was marked as 1.17? should this PR be done for 1.17 as well?

2018-01-17 11:14 UTC, xprazak2 commented
I set the redmine release to 1.18 as this will not go into 1.17.

2018-01-18 08:26 UTC, ares commented
> whats the status of this pr? @ares this issue was marked as 1.17? should this PR be done for 1.17 as well?

honestly, I'm not sure why you set the redmine issue to 1.17, it's nice addition but at this point, it does not qualify for cherrypick into stable branch I think

I think the current assignment 1.18 is also not ideal, PR is WoC - @ShimShtein any progress?

2018-04-03 08:18 UTC, xprazak2 commented
@ShimShtein, any progress on this? I am just curious whether to remove it from 1.18...

2018-10-04 01:23 UTC, closed without merging