Fixes #14652 - Allow local boot templates to be reviewed from host page
theforeman/foreman pull request #3432
Opened 2016-04-14 18:54 UTC by treydock

2016-04-15 07:53 UTC, timogoebel commented on app/models/provisioning_template.rb
> +
Please remote this line for rubocop style tests to be green. :-)

2016-04-18 18:16 UTC, dLobatog commented on app/controllers/unattended_controller.rb
> +    if type == 'local_boot'
Please extract to a separate private method, `find_config_template(type)` or similar

2016-04-18 18:18 UTC, dLobatog commented on test/unit/provisioning_template_test.rb
> +    host = FactoryGirl.create(:host, :with_operatingsystem)
`.build_stubbed` instead of create, to save the db call, same thing below

2016-04-18 18:28 UTC, dLobatog commented on app/models/provisioning_template.rb
> +    return unless host.operatingsystem.present?
Sorry, I'm confused as to why can you not leave this to `host.provisioning_template`? It's the way the rest of the code retrieves it, you could add something like:

```ruby
return local_boot_template if opts[:kind] == 'local_boot'
``` 

over here https://github.com/theforeman/foreman/blob/develop/app/models/host/managed.rb#L327

2016-04-18 18:31 UTC, dLobatog commented
@treydock Thanks for the contribution! I guess I'm a little confused as to why this is needed. Reviewing these templates serves no purpose, as PXEGrub local boot and PXELinux local boot don't use any variables, and will always look the same. Can you provide a bit more context?

2016-04-18 18:44 UTC, treydock commented
@dLobatog I'm going to make the various tweaks per comments.  The need for this is a case where PXELinux is dynamic.  My use case is managing hosts in Foreman (DHCP, DNS, etc) but using PXE to do stateless provisioning of bare-metal systems.  The only way I could think to do this is by adding a host, taking out of build mode, and letting the "PXELinux default local boot" have a condition that would set the first boot option to a stateless image instead of local disk, for select systems.

2016-04-25 13:20 UTC, treydock commented on app/models/provisioning_template.rb
> +    return unless host.operatingsystem.present?
@dLobatog Do you mean putting an instance method for Host::Managed named `local_boot_template` and then referencing that inside `host.provisioning_template`?

2016-04-28 07:09 UTC, dLobatog commented on app/models/provisioning_template.rb
> +    return unless host.operatingsystem.present?
Yup!

2017-05-20 13:20 UTC, mmoll commented
this needs a serious rebase :)

2017-06-19 17:36 UTC, ohadlevy commented
@treydock would you mind explaining a bit more the usage case here? (sorry for looking it after so much time)...?

2017-08-15 18:08 UTC, treydock commented
@ohadlevy Our environment uses NFS root for cluster nodes, so systems that mount their root filesystem over a read-only NFS export.  These systems are PXE booted on every boot to load the appropriate filesystem and kernel version.  We overload the "PXELinux default local boot" template to support dynamically generating these host's PXE boot file.  These NFS root systems never go into a "Build" state, since their PXE config never changes.  Let me know if this helps explain this use case for this pull requests original idea.

2017-10-31 12:54 UTC, dLobatog requested changes
@treydock Could you rebase & ping me? Sorry for keeping this open for so long.

2018-06-27 14:13 UTC, closed without merging