Fixes #14583 - reworded orphan taxonomy validation error
theforeman/foreman pull request #3528
Opened 2016-05-16 09:41 UTC by lzap

This error can appear when new Lifecycle Environment or a Hostgroup is being
created. Therefore I suggest to reword it a bit to something more
appropriate. Currently it reads:

		hammer organization add-hostgroup --hostgroup-id="6" --id="144"
		Locations you cannot remove locations that are used by hosts or inherited.

In this patch, I suggest wording that fits both for UI and API/CLI.

2016-05-17 07:13 UTC, dLobatog commented
@lzap Thanks :smile: - I can see how the message is confusing, but 'check mismatches' isn't very user-friendly either IMO both for API and UI. Where does the user see the mismatches list / what exactly is mismatching? 

Lastly, can you write a test that triggers this?

2016-05-17 14:41 UTC, lzap commented
> @lzap Thanks :smile: - I can see how the message is confusing, but 'check mismatches' isn't very user-friendly either IMO both for API and UI. Where does the user see the mismatches list / what exactly is mismatching? 

What do you recommend then, I was thinking about "taxonomy mismatch" but
we don't use "taxonomy" in the UI...

-- 
Later,
 Lukas #lzap Zapletal

2016-05-18 06:53 UTC, tbrisker commented on app/services/tax_host.rb
> +        taxonomy.errors.add(taxable_type.tableize, _("expecting %s used by hosts or inherited (check mismatches).") % taxable_type.tableize.humanize.downcase)
This won't get the taxonomy name translated.

2016-05-18 09:36 UTC, lzap commented on app/services/tax_host.rb
> +        taxonomy.errors.add(taxable_type.tableize, _("expecting %s used by hosts or inherited (check mismatches).") % taxable_type.tableize.humanize.downcase)
Fixed. How about this @dLobatog ? Mismatches report is only available in the UI if you go to Organizations -> Mismatches button.

2016-05-19 14:31 UTC, lzap commented
Just couple of JS failures.

2017-06-19 17:39 UTC, ohadlevy commented
@lzap @dLobatog bump?

2017-10-31 13:10 UTC, dLobatog requested changes
@lzap This just needs a rebase & changing a minor thing in a string, let me know when it's rebased and I'll check it out - ping me on IRC if I don't as this is pretty old

2017-10-31 13:10 UTC, dLobatog commented on app/services/tax_host.rb
> +        taxonomy.errors.add(taxable_type.tableize, _("expecting %s used by hosts or inherited (check mismatches report).") % _(taxable_type.tableize.humanize.downcase))
`Check %s mismatches report` maybe? I'm trying to point the user to the mismatches report directly (if possible a link would be the best).

2017-11-03 13:55 UTC, lzap commented
Yep a string change with a test.

2017-11-21 09:59 UTC, dLobatog requested changes
@lzap Please change `FactoryGirl` to `FactoryBot` and I think we're ready to go. Thanks @lzap

2017-11-29 13:56 UTC, lzap commented
Rebased.

2017-11-30 06:38 UTC, dLobatog approved these changes

2017-11-30 06:38 UTC, merged

2017-11-30 12:32 UTC, ares commented
thanks, setting the release to 1.17 in redmine