Fixes #15402 - Moved puppet to separate api controller
theforeman/foreman pull request #3663
Opened 2016-07-20 13:50 UTC by ShimShtein

2016-07-21 05:40 UTC, ShimShtein commented
The tests hit `Execution expired` error, retrying.
[test]

2016-07-21 17:55 UTC, dLobatog commented
@ShimShtein Thanks, most of it is good :smile:  Just two comments that I think would improve this:

1. Can you add a test for `permissions_check`? Just to check we call it properly on the puppetrun action.
2. There's an additional route created 'api/v2/puppet_hosts/puppetrun', can you make this patch not add any additional routes? I don't think it's used for anything.

2016-07-24 11:08 UTC, ShimShtein commented
Added test for `permissions_check`.

>There's an additional route created 'api/v2/puppet_hosts/puppetrun', can you make this patch not add any additional routes? I don't think it's used for anything.

@dLobatog , are you sure? I don't see it when running `rake routes`:
```
$ rake routes | grep puppetrun
                                                   puppetrun_host GET    /hosts/:id/puppetrun(.:format)                                                                                                                         hosts#puppetrun {:id=>/[^\/]+/}
                                         multiple_puppetrun_hosts GET    /hosts/multiple_puppetrun(.:format)                                                                                                                    hosts#multiple_puppetrun
                                  update_multiple_puppetrun_hosts POST   /hosts/update_multiple_puppetrun(.:format)                                                                                                             hosts#update_multiple_puppetrun
                                               puppetrun_api_host PUT    /api(/:apiv)/hosts/:id/puppetrun(.:format)                                                                                                             api/v2/puppet_hosts#puppetrun {:format=>"json", :apiv=>/v1|v2/, :id=>/[^\/]+/}
```

in the last line I can see the new method, but the path is set to `/api/v2/hosts/:id/puppetrun`.

2016-07-24 12:27 UTC, ShimShtein commented
Test results are inconsistent, retesting.
[test]

2016-07-31 15:17 UTC, ShimShtein commented
Rebased.

2016-08-02 05:55 UTC, ShimShtein commented
[test]

2016-08-24 11:27 UTC, orrabin commented on test/lib/foreman/access_permissions_test.rb
> +  SPECIAL_PATH = ['api/v2/puppet_hosts/puppetrun']
maybe change to PUPPET_RUN_PATH or HOSTS_PUPPET_RUN_PATH?

2016-08-24 17:50 UTC, ShimShtein commented on test/lib/foreman/access_permissions_test.rb
> +  SPECIAL_PATH = ['api/v2/puppet_hosts/puppetrun']
It's a global constant that holds all actions that have special paths - these actions cannot be tested by this test. [This line](https://github.com/ShimShtein/foreman/blob/73fe3dc47c3faee6d44ced1f059bf9cd5dce176d/test/lib/foreman/access_permissions_test.rb#L51) generates paths from controller names, and in this case it's not going to work.

2016-09-28 16:31 UTC, ShimShtein commented
Rebased

2017-01-04 13:00 UTC, ShimShtein commented
Rebased
@dLobatog, Can you please re-review this?

2017-09-21 00:27 UTC, mmoll commented
this needs a rebase :)

2017-09-24 13:04 UTC, ShimShtein commented
Rebased

2017-09-25 21:36 UTC, iNecas commented
Tests are green. Looks good to me. @dLobatog anything else to add before we merge?

2017-11-02 08:58 UTC, dLobatog requested changes
@ShimShtein @iNecas This looks (and looked) basically ready to merge to me, it slipped off my radar. Are you able to rebase so we can see tests pass & we move forward?

Sorry for the long wait to get back to you

2017-11-07 07:59 UTC, ShimShtein commented
Rebased, tests are green. @dLobatog want to take last round?

2017-11-07 11:13 UTC, dLobatog approved these changes

2017-11-07 11:14 UTC, merged

2017-11-07 11:14 UTC, dLobatog commented
Thanks @ShimShtein !