Fixes #15543 - External method to search fact's hostgroup
theforeman/foreman pull request #3837
Opened 2016-09-13 09:33 UTC by shlomizadok

2016-09-13 09:35 UTC, ohadlevy commented on app/models/fact_value.rb
> +    { :conditions => "fact_values.id IN(#{search.join(',')})" }
why not use an inner query? if search is a scope, it will be done automatically.

2016-09-13 13:27 UTC, tbrisker commented on app/models/fact_value.rb
> +    { :conditions => "fact_values.id IN(#{search.join(',')})" }
Even better, I think this should work just as well and get rid of the extra query completely:
```ruby
search_term = value =~ /\A\d+\Z/ ? 'id' : 'name'
conditions = sanitize_sql_for_conditions(["hostgroups.#{search_term} #{operator} ?", value_to_sql(operator, value)])
{ :joins => :hostgroup, :conditions => conditions }
```

2016-09-14 08:57 UTC, shlomizadok commented on app/models/fact_value.rb
> +    { :conditions => "fact_values.id IN(#{search.join(',')})" }
@tbrisker - this works perfect. Thanks !

2016-09-14 09:06 UTC, tbrisker commented
@shlomizadok Could you apply the same refactoring to the host search above while at it?

2016-09-14 10:50 UTC, shlomizadok commented
@tbrisker - yeah, tried to DRY them as well.

2016-09-18 12:44 UTC, tbrisker commented on app/models/fact_value.rb
> +  def self.search_by(host_or_hg, key, operator, value)
you can even DRY this more- key is either `host` or `host.hostgroup`, so you can use the same method for both and just check the key to decide which table to use.

2016-09-18 12:45 UTC, tbrisker requested changes

2016-09-18 13:08 UTC, shlomizadok commented
@tbrisker - got it as DRY as I can...

2016-09-18 13:11 UTC, shlomizadok commented on app/models/fact_value.rb
> +
@houndci-bot woof!

2016-09-18 13:15 UTC, tbrisker approved these changes

2016-09-18 13:15 UTC, shlomizadok commented on app/models/fact_value.rb
> +  def self.search_by(host_or_hg, key, operator, value)
Excellent idea. Changed :+1:

2016-09-18 13:58 UTC, shlomizadok commented
Foreman [test] failure seem unrelated

2016-09-19 09:12 UTC, shlomizadok commented
@theforeman/core - Any clue why this is failing?

2016-09-19 09:13 UTC, tbrisker commented
@shlomizadok this is the cause of the failures: http://projects.theforeman.org/issues/16599

2016-09-21 15:04 UTC, dLobatog commented
[test foreman]

2016-09-22 07:29 UTC, shlomizadok commented
[test foreman]

2016-09-22 08:19 UTC, tbrisker commented
Merged as 5ce4c4c51917fdcf377fb168157a099108e5557f, thanks @shlomizadok!

2016-09-22 08:19 UTC, closed without merging