Fixes #16565 - Correct host search by parameters
theforeman/foreman pull request #3847
Opened 2016-09-15 09:13 UTC by tbrisker

Overrides for parameters values caused incorrect results for when
searching by parameter value. This commit fixes those results, and
improves the handling of parameter priorities in general. A new rake
task, `parameters:reset_priorities` is introduced that should be invoked
every time priorities are changed to update to the correct values.

2016-09-16 13:36 UTC, domcleal commented on db/migrate/20110327123639_add_priority_to_parameter.rb
> -    Parameter.reset_column_information
Might this still be required? The column information may be cached, and the rake task still relies on it. (As may later migrations.)

2016-09-16 13:37 UTC, domcleal requested changes

2016-09-18 09:46 UTC, tbrisker commented on db/migrate/20110327123639_add_priority_to_parameter.rb
> -    Parameter.reset_column_information
I'm not sure but I will leave that line there just in case.

2016-09-19 08:30 UTC, domcleal approved these changes

2016-09-19 08:30 UTC, domcleal commented
Merged as a29f3e3, thanks @tbrisker.

2016-09-19 08:30 UTC, closed without merging