fixes #16578 - make keep_param idempotent, remove duplicate call
theforeman/foreman pull request #3853
Opened 2016-09-16 11:02 UTC by domcleal

Using host_params (and keep_param) twice was causing compute_attributes
to be deleted permanently out of `params`. keep_param now restores
elements it deletes, and the controller now only calls host_params once
for efficiency.

2016-09-19 18:55 UTC, dLobatog commented on app/controllers/concerns/foreman/controller/parameters/keep_param.rb
> +    params[top_level_hash].update old_params
Please leave a comment here explaining this restores deleted `params` , I don't think it's very clear at first glance

2016-09-19 18:55 UTC, dLobatog requested changes
Just a small comment to explain what keep_params is doing and why - otherwise :+1: , thanks for fixing this @domcleal

2016-09-20 07:25 UTC, domcleal commented
@dLobatog comments added for both restoration lines, hopefully it's clearer now.

2016-09-20 07:28 UTC, dLobatog approved these changes

2016-09-20 07:28 UTC, dLobatog commented
Ready to merge if Jenkins tests pass

2016-09-21 15:04 UTC, dLobatog commented
[test foreman]

2016-09-21 19:15 UTC, domcleal commented
[test foreman] as develop changed.

2016-09-22 07:32 UTC, merged

2016-09-22 07:32 UTC, dLobatog commented
Thanks @domcleal !