Fixes #16577 - enhance unit detection
theforeman/foreman pull request #3854
Opened 2016-09-16 11:23 UTC by ares

2016-09-16 11:24 UTC, ares commented on lib/core_extensions.rb
> -    value, _, unit=self.match(/(\d+(\.\d+)?) ?(([KMGT]i?B?|B))$/i)[1..3]
this used to fail, #match return nil if there's no match and we called `[1..3]` on it

2016-09-16 18:39 UTC, brandonweeks approved these changes

2016-09-18 09:53 UTC, tbrisker commented on lib/core_extensions.rb
> +    match_data = self.match(/(\d+(\.\d+)?) ?(([KMGT]i?B?|B|Bytes))$/i)
Shouldn't the match start at the start of the string?

2016-09-18 09:54 UTC, tbrisker commented on lib/core_extensions.rb
>      case unit.to_sym
we use case insensitive matching, so for example "10gb" will be caught, but there is no `:gb` symbol - perhaps `.lower.to_sym`?

2016-09-18 10:00 UTC, tbrisker requested changes

2016-09-19 14:12 UTC, ares commented on lib/core_extensions.rb
> +    match_data = self.match(/(\d+(\.\d+)?) ?(([KMGT]i?B?|B|Bytes))$/i)
I didn't want to mix refactorings with fix since I thought this should be merged into 1.13 but since it was rejected I can fix existing code.

2016-09-19 14:14 UTC, ares commented on lib/core_extensions.rb
>      case unit.to_sym
alright, even though gB is not gb

2016-09-19 14:16 UTC, ares commented
thanks @tbrisker, I made changes you requested, could you take another look?

2016-09-20 11:58 UTC, ares commented
[test foreman]

2016-09-21 11:56 UTC, tbrisker approved these changes

2016-09-22 07:33 UTC, dLobatog commented
[test foreman]

2016-09-22 08:43 UTC, tbrisker commented on lib/core_extensions.rb
>      case unit.to_sym
technically GiB isn't the same as GB either, but we ignore that as well :)

2016-09-22 08:44 UTC, tbrisker commented
Merged as 0771cec2351c75514abaf1c7040cdd5b74e8ef1d, thanks @ares!

2016-09-22 08:44 UTC, closed without merging

2016-09-22 10:53 UTC, ares commented on lib/core_extensions.rb
>      case unit.to_sym
right :-)