Fixes #14837 - Reword import buttons
theforeman/foreman pull request #3858
Opened 2016-09-18 11:46 UTC by shlomizadok

Import buttons now say where they import from.

In /environments it looks like:
![image](https://cloud.githubusercontent.com/assets/433583/18615386/5b2c274c-7dae-11e6-92bf-12f6952a9598.png)

In /puppetclasses, it would state "Import environments from..." as it is what it is doing
and would look like:

![image](https://cloud.githubusercontent.com/assets/433583/18615395/9f545da4-7dae-11e6-92e1-becfae5076dc.png)

2016-09-19 08:44 UTC, domcleal commented on app/helpers/puppetclasses_and_environments_helper.rb
> +    import_from_text = import_env_text ? "Import environments from %s" : "Import classes from %s"
These strings must be extracted, move the `_()` from line 21.

2016-09-19 08:44 UTC, domcleal requested changes

2016-09-19 08:58 UTC, shlomizadok commented
@domcleal - changed. Thanks

2016-09-19 09:52 UTC, domcleal approved these changes

2016-09-19 09:53 UTC, domcleal commented
Thanks, that's all fine subject to develop being fixed in #16599 and tests passing.

2016-09-21 14:19 UTC, domcleal commented
[test foreman]

2016-09-22 07:21 UTC, domcleal commented
Merged as 2272591, thanks @shlomizadok.

2016-09-22 07:22 UTC, closed without merging