Fixes #16603 - Add translations to the new org process
theforeman/foreman pull request #3860
Opened 2016-09-19 20:16 UTC by bkearney

2016-09-20 10:12 UTC, dLobatog commented
@bkearney We have this in most models and it works (try subnet or architectures) - why does it fail to show the translation here?

2016-09-20 12:00 UTC, bkearney commented
@dLobatog I am not sure. I do not see the label or the description field int the model attributes for taxonomies. So, perhaps something to do with model inheritance?

2016-09-21 12:16 UTC, bkearney commented
@dLobatog I can not reomve the waiting on contributor label :(

2016-09-21 12:25 UTC, domcleal commented on app/views/taxonomies/_form.html.erb
> +        <%= text_f f, :name, :label => _('Name') %>
Why extract the name? `Taxonomy|Name` is extracted via model_attributes.rb.

2016-09-21 12:25 UTC, domcleal commented on app/views/taxonomies/_form.html.erb
> +        <%= textarea_f f, :description, :rows => 5, :label => _('Description') %>
Use model_attributes.rb.

2016-09-21 12:25 UTC, domcleal requested changes
> @dLobatog I am not sure. I do not see the label or the description field int the model attributes for taxonomies.

Label isn't an attribute of Taxonomy, it may not come from Foreman. Description can be added to the model_attributes.rb file rather than being extracted in the UI.

2016-09-21 12:27 UTC, domcleal commented
Your bug report says "Organization" isn't translated, but where exactly is that? I don't see it changed in the PR.

2016-09-23 20:52 UTC, bkearney commented
@domcleal do I edit the model file directly to add the new column, or is it extracted?

2016-09-26 06:49 UTC, domcleal commented
It's generated, see locale:find_model.

2017-03-30 07:00 UTC, closed without merging