Fixes #16649 - PXE helper pxe_kernel_options fixed
theforeman/foreman pull request #3877
Opened 2016-09-22 10:55 UTC by lzap

In PXE templates there should be pxe_kernel_options appended on each line, but
it renders as "[]" instead empty string (or "['element=xyz']") instead of
element=xyz.

2016-09-22 15:33 UTC, dLobatog commented on test/lib/foreman/renderer_test.rb
> +  test "pxe_kernel_options are not set when no OS is set" do
nitpick, `.build`

2016-09-22 15:33 UTC, dLobatog commented on test/lib/foreman/renderer_test.rb
> +    @host = FactoryGirl.create(:host, :operatingsystem => Operatingsystem.find_by_name('Redhat'))
nitpick, `.build`

2016-09-22 15:35 UTC, dLobatog requested changes
@lzap Aside from a nit on the tests, :+1: . Thanks!

2016-09-23 06:59 UTC, domcleal commented on test/lib/foreman/renderer_test.rb
> +    assert_empty pxe_kernel_options
`[]` is also empty, I'd suggest using `assert_equal '', pxe_kernel_options` instead to properly test the return value for this issue.

2016-09-30 10:58 UTC, lzap commented
Nice catches, thanks! Rebased.

2016-09-30 11:10 UTC, dLobatog approved these changes

2016-09-30 11:10 UTC, dLobatog commented
Ready to merge if Jenkins tests pass

2016-09-30 11:50 UTC, dLobatog commented
Unrelated failure - merging

2016-09-30 11:50 UTC, merged

2016-09-30 11:50 UTC, dLobatog commented
Thanks @lzap !