Fixes #10930 : Make widget names and titles consistent
theforeman/foreman pull request #3880
Opened 2016-09-23 21:36 UTC by bkearney

2016-09-26 07:40 UTC, domcleal commented on app/services/dashboard/loader.rb
> +                        {:template=>'distribution_widget', :sizex=>6,:sizey=>1,:name=> N_('Distribution Chart')}]
Missing "Run" from the name, should be "Run Distribution" to match.

2016-09-26 07:40 UTC, domcleal requested changes
There are conflicts, please rebase the PR onto develop.

2016-09-26 13:04 UTC, bkearney commented
@domcleal changed the title of the Distribution chart, rebased, and pushed a new verison.

2016-09-28 10:39 UTC, domcleal commented
The integration tests appear to be failing, please check and update if necessary.

2016-09-28 16:06 UTC, bkearney commented
@domcleal can you kick off the test again? My first push did not have a migration, and I am not sure if this teting caught it.

2016-09-29 07:04 UTC, domcleal commented
Tests are recorded against commits, and the page shows it tested fef2dd0.  Still, if you insist: [test foreman]

2016-09-29 19:02 UTC, bkearney commented
@domcleal pushed new version which fixes the test and incorporates your suggestion to make the tltle "Run Distribution Chart"

2016-09-30 07:13 UTC, domcleal approved these changes

2016-09-30 07:14 UTC, merged

2016-09-30 07:14 UTC, domcleal commented
Merged, thanks @bkearney.