Fixes #16646 - Add ability to plugins to modify index scope
theforeman/foreman pull request #3887
Opened 2016-09-25 18:22 UTC by ShimShtein

Added the ability for plugins to modify the scope used to get hosts for `#index` action. This is needed if a plugin wants to add more `includes` or `eager_load` statements, so Active Record won't try to lazy load additional relations and create N+1 queries.

2016-09-26 06:02 UTC, timogoebel commented on app/controllers/concerns/scopes_per_action.rb
> +# This module will hold a regstry of scope directives that should be
nitpick: `regstry´should be `registry´

2016-09-26 06:25 UTC, ShimShtein commented on app/controllers/concerns/scopes_per_action.rb
> +# This module will hold a regstry of scope directives that should be
Done

2016-09-26 06:42 UTC, ohadlevy commented on app/controllers/concerns/scopes_per_action.rb
> +      scope = scope_func.call(scope) || scope
instead of looping them all, you can return the first match? or do you rather want to match the last one? the code is a bit hard to read.

2016-09-26 06:43 UTC, ohadlevy commented on app/services/foreman/plugin.rb
> +      HostsController.add_scope_for(action, block)
does it make sense to always assume you want to extend them both?

2016-09-26 07:01 UTC, ShimShtein commented on app/controllers/concerns/scopes_per_action.rb
> +      scope = scope_func.call(scope) || scope
I am chaining the scopes, here is an example:
In puppet plugin:
``` ruby
HostsController.add_scope_for(:index) { |base_scope| base_scope.eager_load(:environment) }
```
In provisioning plugin:

``` ruby
HostsController.add_scope_for(:index) { |base_scope| base_scope.eager_load(:operatingsystem) }
```

I want to create a scope that will contain both operations:

``` ruby
base_scope = Hosts.authorized
actual_scope = base_scope.eager_load(environment).eager_load(operatingsystem)
```

I achieve this by calling each block, and passing it the result of the previous block.

2016-09-26 07:04 UTC, ShimShtein commented on app/services/foreman/plugin.rb
> +      HostsController.add_scope_for(action, block)
It sounds reasonable to me that the info that is returned is similar between the API and UI. In the original bug in Katello I saw that the problem exists in both UI and API.
I won't fight over it though. If you think it's unlikely, I can separate it to different methods.

2016-09-27 13:51 UTC, timogoebel requested changes
Looks good to me all in all. I like the DSL and this feature is long past due. The Plugin method needs test coverage (and fixing), though.

2016-09-27 13:51 UTC, timogoebel commented on app/services/foreman/plugin.rb
> +    def hosts_controller_action_scope(action, &block)
Could you please add a test for this? Extra points for inline usage example.

2016-09-27 13:51 UTC, timogoebel commented on app/services/foreman/plugin.rb
> +      HostsController.add_scope_for(action, block)
I think, you need to pass the block like so (note the extra ampersand):

```ruby
HostsController.add_scope_for(action, &block)
```

Same below.

2016-10-06 15:16 UTC, ShimShtein commented
Rebased, fixed plugin registration and added tests.

@timogoebel did I get the extra points?
Is it clear how to use it?

2016-10-09 06:12 UTC, ShimShtein commented
Rebased again

2016-10-09 13:42 UTC, timogoebel requested changes
The code looks good, thanks for the tests. It is also clear how to use this.
My only concern is, that this won't work in develop mode when classes can be reloaded. My suggestion is to store the scope codeblocks in the plugin model and when the concern is included have it get the scopes from the plugin model. You can check c6760930cf08a4b584b75df8a621092dd787da01 for an example.

2016-10-09 18:02 UTC, ShimShtein commented
> My only concern is, that this won't work in develop mode when classes can be reloaded. 

In the past we had `config.to_prepare` block that was run after reload. I can see that in Rails 5, this block [has moved](https://github.com/activeadmin/activeadmin/issues/4438) to `ActiveSupport::Reloader.to_prepare` just put those definitions in the to_prepare block and the callback will be registered again after reload.

2016-10-10 06:53 UTC, timogoebel commented
@ShimShtein : That would be possible, however it's not the Straight-A student's solution. The code in "to_prepare" runs on every development request. I think, it's better to implement a solution that just runs when a class is actually reloaded.

2016-10-13 12:31 UTC, ShimShtein commented
Now the list is global - no reloads should affect it.

2016-10-25 09:48 UTC, lzap commented
FYI there are conflicting files.

2016-10-27 13:00 UTC, ShimShtein commented
Rebased

2016-10-27 13:35 UTC, timogoebel requested changes
@ShimShtein : Thanks for the latest updates. Class reloading still beaks the scopes from Plugins.

Open hosts index page -> everyting is fine.

To reproduce:

``` bash
touch app/controllers/concerns/scopes_per_action.rb
```

Open host index page again -> it detects a n+1 query.

2016-10-27 13:35 UTC, timogoebel commented on test/unit/plugin_test.rb
> +    Foreman::Plugin.register :test_parameter_filter do
should be `test_controller_action_scope`

2016-10-27 14:09 UTC, ShimShtein commented
> touch app/controllers/concerns/scopes_per_action.rb

Indeed, reloading of this class will break the scopes. But that class'es sole responsibility is to maintain the registry, so if it changes - the old registry is probably not valid.
If I store this registry in the plugin class and it will get reloaded, it will be lost too.

2016-10-27 14:13 UTC, timogoebel commented
@ShimShtein : True. But if you store the data in

1. the host controller class
2. the plugin class

When these classes get reloaded, the code is parsed as well and the information is restored.

When you access the data, you can get it from both classes (and merge it) and you shouldn't have a problem. What do you think?

2016-10-27 14:43 UTC, timogoebel commented
@domcleal: May @ShimShtein and I ask for your opinion regarding where to store the data so that it survives a class reload in development? Is the current implementation fine, where the data from plugins gets lost when the `ScopesPerAction` concern is reloaded?

2016-10-27 14:48 UTC, domcleal commented
> @domcleal: May @ShimShtein and I ask for your opinion regarding where to store the data so that it survives a class reload in development?

It really should be stored in Foreman::Plugin (which is immune from reloads) when the API is called. Either access it from there when called, or something akin to c676093 where it's retrieved when the concern is included.

I'd also suggest not adding an API specifically for hosts, else it'd spawn a new API for every single model/controller collection, it ought to be more generic.

> Is the current implementation fine, where the data from plugins gets lost when the ScopesPerAction concern is reloaded?

Not really, IMHO. This is normally treated as a bug, and it ought to be fixed.

2016-10-30 10:06 UTC, ShimShtein commented
@domcleal First, thanks for the review. My only question is what to do with scopes that are not part of a particular plugin. For example `API::V2::HostsController` adds a default scope for index [here](https://github.com/theforeman/foreman/pull/3887/files#diff-6e62e9d287766aaa9c3d35e6dc3470a1R21). Of course I can add this scope manually in the method, but it sounds like I should really use the same framework here too.

2016-10-30 14:22 UTC, ShimShtein commented
@domcleal, Sorry, ignore my previous comment, I did not read the code thoroughly enough.

I have change the implementation to store scopes in both the plugin and in the controller (locally). The local storage is there for cases like the `API::V2::HostsController`.
I didn't cache the result of querying the plugins intentionally. It is done to avoid issues with construction of the controller class before all the plugins are loaded.

2016-10-31 15:57 UTC, ShimShtein commented
test failure is not related.

2016-11-03 13:53 UTC, timogoebel approved these changes

2016-11-03 13:54 UTC, merged

2016-11-03 13:56 UTC, timogoebel commented
Merged, thanks @ShimShtein. Please add a usage example to http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin.

2016-11-03 14:29 UTC, ShimShtein commented
@timogoebel Done: http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Modifying-controllers-query