Fixes #13968 - Fail to save proxy if feature is missing
theforeman/foreman pull request #3895
Opened 2016-09-28 09:51 UTC by shlomizadok

2016-09-28 10:24 UTC, shlomizadok commented on app/models/smart_proxy.rb
> +    features.map{|f| Feature.name_map[f]} == nil
I feel like a Tuna fish for sending this code :sob:

2016-09-28 10:30 UTC, shlomizadok commented
Maybe commit message should be something like:
"Skip feature if not in Feature model"

2016-09-28 10:55 UTC, domcleal commented
> Maybe commit message should be something like: "Skip feature if not in Feature model"

I think it already did this. This now correctly logs an error when no _known_ features are found. Perhaps "add error when no known proxy features found", if you wanted to change it.

Could you add a test for this bug and validation? It contains a skip when Rails.env is test, but I think that could probably be removed and ProxyAPI::Features be stubbed instead when necessary (e.g. in the factory).

2016-09-28 10:55 UTC, domcleal requested changes

2016-09-28 10:55 UTC, domcleal commented on app/models/smart_proxy.rb
> -      if reply.is_a?(Array) && reply.any?
I think the Array check here on `reply` is important - it's moved below to `valid_features.is_a?(Array)`, but you know that's an array as you're constructing it with .map. Check the `reply` is an array before trying to use map on it.

2016-09-28 10:59 UTC, shlomizadok commented on app/models/smart_proxy.rb
> -      if reply.is_a?(Array) && reply.any?
You are right. I'll change that.

2016-09-28 11:01 UTC, shlomizadok commented
Thanks for the review and comments @domcleal. Will add tests to validate this issue.

2016-09-28 12:12 UTC, shlomizadok commented
@domcleal  - Added tests, reworded commit message.
Let me know what you think.

2016-09-29 08:24 UTC, domcleal requested changes

2016-09-29 08:24 UTC, domcleal commented on app/models/smart_proxy.rb
> -    return true if Rails.env == 'test'
It looks like removing this is affecting a very large number of tests - sorry, the check might have to remain.

I do have one more suggestion if you'd like to continue with it - separate the feature association from the validation. So this method with the ProxyAPI::Features call becomes a `before_validation` and is skipped when Rails.env.test?, but the validation that the smart proxy has at least one feature is a normal validator which can be tested in isolation from the feature assignment.

2016-09-29 08:24 UTC, domcleal commented on app/models/smart_proxy.rb
> +      return errors.add(:base, _('Invalid features format')) unless reply.is_a?(Array)
Please expand this message a little, it'll be unclear to users - perhaps "An invalid response was received while requesting available features from this proxy" (similar to the message below)?

2016-09-29 08:38 UTC, shlomizadok commented on app/models/smart_proxy.rb
> +      return errors.add(:base, _('Invalid features format')) unless reply.is_a?(Array)
:+1:  Again your English is better than mine :smile: 
Will change.

2016-09-29 08:40 UTC, shlomizadok commented on app/models/smart_proxy.rb
> -    return true if Rails.env == 'test'
I have been pulling my hair with how to fix the tests... Your idea is better. Will refactor

2016-10-05 08:54 UTC, shlomizadok commented on app/models/smart_proxy.rb
> -    return true if Rails.env == 'test'
Refactored. Hope this is what you had in mind

2016-10-05 09:36 UTC, shlomizadok commented
@domcleal - first approach didn't work well for me (I may have done something wrong).
I have moved to stubbing the Proxy API calls: 
`ProxyAPI::Features.any_instance.stubs(:features => Feature.name_map.keys)`

Let me know if that's acceptable

2016-10-05 11:36 UTC, shlomizadok commented on test/models/nic_test.rb
> +      assert_includes SmartProxy.with_features('BMC').map { |sp| sp.url + '/bmc' }, @interface.proxy.url
We are not sure there is always only one proxy

2016-10-05 11:37 UTC, shlomizadok commented on test/controllers/smart_proxies_controller_test.rb
> +    ProxyAPI::Features.any_instance.stubs(:features =>["dns", "dhcp"])
Not needed anymore. Will remove

2016-10-05 12:44 UTC, shlomizadok commented
OK, I think that besides https://github.com/theforeman/foreman/pull/3895#discussion_r81953386 I'm good :bowtie:

2016-10-05 14:42 UTC, domcleal commented on test/active_support_test_case_helper.rb
> +    ProxyAPI::Features.any_instance.stubs(:features => Feature.name_map.keys)
This adds a new SQL query to every single test, as it's called regardless of whether the stubbing's needed or not. What's it used for? Can the stubbing be added to the tests that need it?

2016-10-05 15:40 UTC, shlomizadok commented on test/active_support_test_case_helper.rb
> +    ProxyAPI::Features.any_instance.stubs(:features => Feature.name_map.keys)
Yeah, it was a precaution for Katello tests. I will open a PR on the failing tests there (to use factories)

2016-10-06 05:02 UTC, shlomizadok commented
https://github.com/Katello/katello/pull/6377 should solve the failures in Katello

2016-10-07 06:34 UTC, dLobatog commented on app/models/smart_proxy.rb
> +      return errors.add(:base, _('An invalid response was received while requesting available features from this proxy')) unless reply.is_a?(Array)
How about printing the response too? That can be helpful while debugging

2016-10-07 06:40 UTC, dLobatog commented on app/models/smart_proxy.rb
> +        errors.add :base, _('No matching features found on this proxy, please make sure you enable at least one feature')
Not sure what 'matching' means in this context for a user that doesn't know about the bug. Also it tells the user to 'enable at least one feature' but control flow allows Foreman to get here when there was certainly one feature enabled (albeit not known by Foreman)

How about 'Features #{invalid_features} in this proxy are not recognized by Foreman. If these features come from a Smart Proxy plugin, make sure Foreman has the plugin installed too.' when there are invalid features, and leaving the old message "No features found..." for the case where there are no features found?

2016-10-07 06:42 UTC, dLobatog commented
@shlomizadok I left a few comments concerning the 'not features found' case vs 'only unknown features found' - thanks for fixing this

2016-10-07 14:27 UTC, shlomizadok commented on app/models/smart_proxy.rb
> +      return errors.add(:base, _('An invalid response was received while requesting available features from this proxy')) unless reply.is_a?(Array)
@dLobatog - Shall I print it in a logger message or just add it to the errors ?

2016-10-08 20:17 UTC, shlomizadok commented
[test katello]

2016-10-09 12:55 UTC, shlomizadok commented on app/models/smart_proxy.rb
> +        errors.add :base, _('No matching features found on this proxy, please make sure you enable at least one feature')
Changed. Let me know if this is what you had in mind.

2016-10-09 12:55 UTC, shlomizadok commented on app/models/smart_proxy.rb
> +      return errors.add(:base, _('An invalid response was received while requesting available features from this proxy')) unless reply.is_a?(Array)
Added a logger message.

2016-10-10 11:17 UTC, domcleal requested changes

2016-10-10 11:17 UTC, domcleal commented on test/test_helper.rb
> +    ProxyAPI::Features.any_instance.stubs(:features => Feature.name_map.keys)
Wasn't this going to be removed now? (https://github.com/theforeman/foreman/pull/3895#discussion_r81988688)

2016-10-10 13:18 UTC, shlomizadok commented on test/test_helper.rb
> +    ProxyAPI::Features.any_instance.stubs(:features => Feature.name_map.keys)
The previous one was for unit (/models) tests. This one is for functional (/controllers) tests. I guess I can remove it too and add per each test.

2016-10-10 15:33 UTC, shlomizadok commented on test/test_helper.rb
> +    ProxyAPI::Features.any_instance.stubs(:features => Feature.name_map.keys)
@domcleal - removed ^, added per test

2016-10-13 09:21 UTC, domcleal approved these changes

2016-10-13 09:21 UTC, merged

2016-10-13 09:22 UTC, domcleal commented
Merged, thanks @shlomizadok.