Fixes #16704 - Allow filtering on dashboard
theforeman/foreman pull request #3900
Opened 2016-09-28 15:13 UTC by tbrisker

Some filters on the dashboard caused the reports widget to break,
specifically searching using free text or on attributes that are not
part of the hosts table (such as environment name).
This is caused by an issue with Rails that digregards outer joins when a
query is used as an inner query for a where clause using hash syntax.

2016-09-29 07:33 UTC, domcleal commented
Could you add tests for this please? I'd suggest at a couple of layers, e.g. a unit test for Dashboard::Data and a general integration test for the dashboard with filtering. Both should catch this class of errors, and the unit test will be easy and cheap to extend for more precise tests.

2016-09-29 10:49 UTC, tbrisker commented
@domcleal I've added several unit tests.
I did not manage to get a properly working integration test due to issues with the ajax loading of the widgets.
I'm leaving on an extended leave soon, if you or any other maintainer wishes to add integration tests while I'm away, my branch allows edits from maintainers.

2016-09-29 11:41 UTC, domcleal commented
There are some test failures - the dashboard tests are failing on SQLite3, and PuppetClassImporter tests are failing on multiple DBs.

It looks like the latter is expecting certain ordering of environments in queries - possibly the creation of new environments in the tests (pushing the count over 100) is affecting the sorting ("99" vs "100") so the comparisons in the test may need `.sort` adding.

2016-11-01 12:17 UTC, tbrisker commented
@domcleal Thanks, updated the tests to use `@env` instead of `env` for the created environment which seems to clear it correctly from the db, and moved it to the setup block since nearly all the tests use it. Also changed the column quoting so it should hopefully now pass on all dbs.

2016-11-01 14:07 UTC, domcleal requested changes

2016-11-01 14:07 UTC, domcleal commented on test/unit/dashboard_test.rb
> +    @host.update_attribute(:environment_id, @env.id)
Pass `:environment => @env` to the host creation in `setup` to avoid these additional updates in many of the tests.

2016-11-01 14:26 UTC, tbrisker commented
@domcleal fixed, also fixed some minor spacing inconsistencies.

2016-11-01 15:12 UTC, domcleal approved these changes

2016-11-01 15:13 UTC, merged

2016-11-01 15:13 UTC, domcleal commented
Merged, thanks @tbrisker.