Fixes #5673 - Allow deletion of role with users
theforeman/foreman pull request #3922
Opened 2016-10-05 15:26 UTC by shlomizadok

2016-10-06 07:38 UTC, domcleal requested changes

2016-10-06 07:38 UTC, domcleal commented on app/helpers/roles_helper.rb
> +      _("Warning! This will remove %{name} from %{number} users. are you sure?") % {name: role.name, number: role.users.size}
Use `n_()` here for the pluralised form, i.e. "from %{number} user" (1) and "from %{number} users".

2016-10-06 07:38 UTC, domcleal commented on test/controllers/roles_controller_test.rb
> +  test 'roles in use can be destroyed' do
Might as well delete this I think, or perhaps change it to a test to check you can't delete built in roles. Your unit test coverage of deletion of roles with users is better I think, and cheaper.

2016-10-06 09:34 UTC, shlomizadok commented on test/controllers/roles_controller_test.rb
> +  test 'roles in use can be destroyed' do
Changed to testing built-in role

2016-10-06 09:34 UTC, shlomizadok commented on app/helpers/roles_helper.rb
> +      _("Warning! This will remove %{name} from %{number} users. are you sure?") % {name: role.name, number: role.users.size}
Changed to pluralized form

2016-10-07 06:31 UTC, dLobatog commented on test/models/role_test.rb
> +  it "Should delete role who has users" do
nitpick - lowercase should. can be fixed on merge. Also `FactoryGirl.build` is preferable for creating the User here, it'll prove the point just the same (and the relationship need not to be in db)

2016-10-07 11:24 UTC, domcleal approved these changes

2016-10-07 11:25 UTC, domcleal commented on test/models/role_test.rb
> +  it "Should delete role who has users" do
Fixed the case on merge, but I'd prefer in this case to keep the objects persisted in the DB to ensure we test the whole destroy mechanism (there are a few dependent destroys with cached user roles etc).

2016-10-07 11:26 UTC, domcleal commented
Merged as a2c1e8d, thanks @shlomizadok.

2016-10-07 11:26 UTC, closed without merging