Fixes #16828 role.builtin = 0(integer) value instead of 'false'
theforeman/foreman pull request #3925
Opened 2016-10-07 09:03 UTC by swapnilabnave

Though `roles.builtin` has [`:default => 0`](https://github.com/theforeman/foreman/blob/12612809c5deb885b13ceaf36b6a147c21688eb5/db/migrate/20160715131352_set_role_builtin_default.rb). This is to ensure cloned roles always have `builtin == 0`

2016-10-07 11:45 UTC, domcleal requested changes
The test passes on current develop, so it's of limited value. I'd suggest just adding the assertion into the existing clone test, keeps everything simple.

2016-10-07 11:45 UTC, domcleal commented on test/controllers/roles_controller_test.rb
> +    test "cloned roles should have builtin value 0 instead of `false`" do
The comment about `false` isn't helpful after this patch is merged, it should simply state that it should have the value 0.

2016-10-07 11:45 UTC, domcleal commented on test/controllers/roles_controller_test.rb
> +      assert_equal cloned_role.builtin, 0
Might as well put this assertion into the existing cloning test above? It'll save execution time.

2016-10-07 11:46 UTC, domcleal commented
@theforeman-bot ok to test

2016-10-08 04:30 UTC, swapnilabnave commented on test/controllers/roles_controller_test.rb
> +      assert_equal cloned_role.builtin, 0
@domcleal 
Believe me it was like that at some-point in time. But I was in 2 minds whether to add more asserts to one test or not. I totally agree on _saving execution time_.
Thanks for reviewing.

2016-10-08 04:35 UTC, swapnilabnave commented
@domcleal 
I wanted to discuss this with someone.
In `app/models/role.rb` - [`BUILTIN_DEFAULT_ROLE = 2`](https://github.com/theforeman/foreman/blob/develop/app/models/role.rb#L26) is for **default role**. Likewise shouldn't there be constants for 0 and 1 (w.r.t Roles) ?

2016-10-08 06:19 UTC, ranjan commented
@swapnilabnave  There is a ongoing [PR#3630](https://github.com/theforeman/foreman/pull/3630) for the same issue. I think that discussion thread will be helpful for you.

2016-10-08 15:38 UTC, swapab commented on test/controllers/roles_controller_test.rb
> +    test "cloned roles should have builtin value 0 instead of `false`" do
Removed the redundant test.

2016-10-08 15:41 UTC, swapnilabnave commented
@ranjan Thanks for the direction. I think #3630 would be make it more meaningful.

2016-10-10 11:30 UTC, domcleal approved these changes

2016-10-10 11:30 UTC, merged

2016-10-10 11:30 UTC, domcleal commented
Merged, thanks @swapnilabnave.

2017-01-31 14:19 UTC, lzap commented
I think this patch is missing migration that will fix incorrect record:

```
Role.where(:builtin => nil).update_all(:builtin => 0)
```

Shell we create one?