Fixes #6492 - ipmi_boot permission renamed to ipmi_boot_hosts
theforeman/foreman pull request #3926
Opened 2016-10-07 12:04 UTC by dLobatog

Authorizer expects permission names to follow a convention
'action'_'controller'. However this permission was not following it, and
this prevented the permission from being applied properly.

Before this fix, only admins could call ipmi_boot. I've also added a
small fix to the controller to check whether the BMC interface is
available before making the IPMI call - otherwise the error that Foreman
threw did not make much sense for the end user (NoMethodError on
bmc_proxy).

2016-10-10 12:26 UTC, domcleal requested changes

2016-10-10 12:26 UTC, domcleal commented on test/controllers/hosts_controller_test.rb
> +    test 'responds gracefully if BMC is not available' do
This test name should be changed, perhaps to say it responds correctly for a non-admin user or similar.

2016-10-10 12:26 UTC, domcleal commented on test/fixtures/permissions.yml
>    ipmi_boot:
Nitpick, update the name here too, please.

2016-10-10 12:26 UTC, domcleal commented on db/migrate/20161007115719_rename_ipmi_boot_permission.rb
> +      update_all(:name => 'ipmi_boot_hosts')
This change isn't reversible, it'll need separate up/down methods.

2016-10-10 12:26 UTC, domcleal commented on app/controllers/hosts_controller.rb
> +    raise Foreman::Exception.new(
This might need to be in the API v2 hosts controller (or the model) too? it calls ipmi_boot without any checking.

2016-10-11 10:09 UTC, dLobatog commented
Thanks for taking a look @domcleal - I've updated it, the changes include:

* bmc_available check and exception moved to Host::Managed
* tests for controller and v2 controller handling that exception 
* fix for permissions check in API v2 
* migration is reversible

2016-10-11 10:10 UTC, dLobatog commented on app/controllers/api/v2/hosts_controller.rb
> +        permission = "#{action_permission}_hosts".to_sym
Without this, we call for permissions that might not even exist in the next line. E.g: 'rebuild_config_hosts', 'boot_hosts', etc... I think this fixes permission problems with a bunch of other methods, not just 'ipmi_boot_hosts'

2016-10-13 09:43 UTC, domcleal approved these changes

2016-10-13 09:44 UTC, merged

2016-10-13 09:44 UTC, domcleal commented
Merged, thanks @dLobatog.