fixes #16592 - keep consistent for headline capitalization
theforeman/foreman pull request #3928
Opened 2016-10-09 11:07 UTC by junezhang

Based on PatternFly Outlines Headline Style Capitalization, http://www.patternfly.org/styles/terminology-and-wording/#capitalization
We suggested to keep consistent in headline capitalization, capitalize the first letter of every word in headline.

As last PR #3841, I fixed the menu case, @ohadlevy suggested me to fix all the labels in one PR.
So I re-created one PR for updating all labels capitalization in Foreman.

Please have a review.
Thanks.

2016-10-11 09:02 UTC, junezhang commented
@ohadlevy, @bbuckingham, @dLobatog, @tbrisker,  thanks for your comments on my last PR.
May I have your attention for reviewing my new PR, please, thanks!

2016-10-11 09:07 UTC, junezhang commented on app/views/subnets/index.html.erb
>        <th class="col-md-3"><%= _("Domains") %></th>
When reviewing the page, it is "Network address",  but in the coding it is "Network". and I added "Address" after Network.
If it is wrong, please correct me. Thanks.

2016-11-02 15:09 UTC, tbrisker commented
@theforeman-bot ok to test

2016-11-02 15:12 UTC, tbrisker commented on app/views/subnets/index.html.erb
>        <th class="col-md-3"><%= _("Domains") %></th>
For some reason this was changed to network address by the English translation file.

2016-11-02 15:16 UTC, tbrisker commented
Sorry for the slow response, I was on a long vacation. OK to merge if all tests pass.

2016-11-02 15:21 UTC, domcleal commented on app/views/subnets/index.html.erb
>        <th class="col-md-3"><%= _("Domains") %></th>
Don't create a second string (`Subnet|Network Address`) without removing the first (`Subnet|Network`), either change the existing translation or remove the original. (Not that attrs should be removed from the generated model attrs file.)

2016-11-02 15:34 UTC, tbrisker commented on app/views/subnets/index.html.erb
>        <th class="col-md-3"><%= _("Domains") %></th>
@domcleal I'm not quite sure what you mean, aren't the translation files automatically generated? what is the model attrs file?

2016-11-02 15:36 UTC, domcleal commented on app/views/subnets/index.html.erb
>        <th class="col-md-3"><%= _("Domains") %></th>
Non-English translations are in Transifex, English translations are in this repo, and model attrs is locale/model_attributes.rb.

2016-11-03 18:30 UTC, junezhang commented on app/views/subnets/index.html.erb
>        <th class="col-md-3"><%= _("Domains") %></th>
@domcleal what you meaning is if want to update the strings, fixing the capitalization problem, I need to update the English translation file: locale/en/foreman.po, Is that right?

2016-11-11 08:54 UTC, junezhang commented
@domcleal I've updated the English translation PO file. Please help to review? 
When updating the PO file, I haven't found how to update these two items (Provisioning templates, Smart class parameters) in the navigation, so update them in the menu/loader.rb file.
Thanks.

2016-11-11 12:40 UTC, junezhang commented on app/views/subnets/index.html.erb
>        <th class="col-md-3"><%= _("Domains") %></th>
@domcleal Update the English translation PO file, and re-submit a patch, please help to review. Thanks.

2016-12-21 13:32 UTC, ohadlevy commented
@junezhang can you please rebase?
@tbrisker anything else this PR needs? thanks!

2016-12-22 07:01 UTC, junezhang commented
test

2016-12-22 09:17 UTC, junezhang commented
Rebase my commit, @tbrisker @domcleal Please have a review. Thanks.

2017-02-15 12:16 UTC, junezhang commented
It's a long time for seeking feedback about my English translation PO file. so I think maybe it's not a right way. then I turn back to update the menu/loader.rb file and other .erb files. Please help to review it. Thanks.

2017-05-30 12:08 UTC, sean797 commented
Thanks a ton for doing this @junezhang 🥇 Looks good overall. If you have a chance to look at the test failures, can you? When they pass, it should be good to merge. If not I will raise a PR based off this one.

2017-06-02 14:17 UTC, junezhang commented
Hi, @sean797, sorry for replying late. I've checked the test result, but have no idea about the test failure. Could you help on the test error, please? Thank you!

2017-06-02 15:05 UTC, sean797 commented
Sure, try this @junezhang 

```
$ git diff
diff --git a/test/integration_test_helper.rb b/test/integration_test_helper.rb
index 0c0e109..e1f7b3a 100644
--- a/test/integration_test_helper.rb
+++ b/test/integration_test_helper.rb
@@ -37,14 +37,14 @@ class ActionDispatch::IntegrationTest
   def assert_index_page(index_path,title_text,new_link_text = nil,has_search = true,has_pagination = true)
     visit index_path
     assert page.has_selector?('h1', :text => title_text), "#{title_text} was expected in the <h1> tag, but was not found"
-    (assert find_link(new_link_text).visible?, "#{new_link_text} is not visible") if new_link_text
+    (assert first(:link, new_link_text).visible?, "#{new_link_text} is not visible") if new_link_text
     (assert find_button('Search').visible?, "Search button is not visible") if has_search
     (assert has_content?("Displaying"), "Pagination 'Display ...' does not appear") if has_pagination
   end
 
   def assert_new_button(index_path,new_link_text,new_path)
     visit index_path
-    click_link new_link_text
+    first(:link, new_link_text).click
     assert_current_path new_path
   end

2017-06-05 10:15 UTC, dLobatog requested changes
Set to Waiting on contributor due to the failing test, thanks for the help @junezhang @sean797

2017-06-05 20:12 UTC, junezhang commented
@sean797  Thanks for providing suggestion to fix the test failure. Currently I'm traveling in US. I will fix it next week. Sorry for any inconvenience.

2017-06-12 09:42 UTC, junezhang commented
@sean797 I've submitted a commit, but it is still failed. So could you help to raise a PR based off this one, please?

2017-06-12 09:56 UTC, sean797 commented
@junezhang it works when I run them locally. Lets [test foreman] again, looks like it could be an intermittent failure

2017-06-12 10:48 UTC, sean797 approved these changes
\o/ tests passed, thanks @junezhang 👍

2017-06-12 12:25 UTC, junezhang commented
@sean797 Thanks for your supporting. 
@dLobatog please have a review for the capitalization updating.

2017-06-19 17:47 UTC, ohadlevy commented
@dLobatog bump?

2017-07-26 12:21 UTC, dLobatog approved these changes

2017-07-26 12:22 UTC, merged

2017-07-26 12:22 UTC, dLobatog commented
Thank you @junezhang & @sean797

2017-07-26 12:24 UTC, dLobatog commented on app/views/media/index.html.erb
> +      <th class="col-md-1"><%= sort :family, :as => s_("Medium|Os Family") %></th>
I think I may have missed this, should be `OS Family`.

2017-07-26 12:25 UTC, dLobatog commented on app/views/ptables/index.html.erb
> +      <th class="col-md-1"><%= sort :family, :as => s_("Ptable|Os Family") %></th>
Another one, OS family.

2017-07-26 12:38 UTC, sean797 commented
ah nice spot @dLobatog ! Created https://github.com/theforeman/foreman/pull/4700

2017-07-27 08:12 UTC, ares commented
I set 1.16 in redmine issue and marked the linked PR to be included in 1.16 too.