fixes #16819 - rebuild tftp with template kinds
theforeman/foreman pull request #3929
Opened 2016-10-09 14:50 UTC by timogoebel

2016-10-10 12:30 UTC, domcleal requested changes

2016-10-10 12:30 UTC, domcleal commented on app/models/concerns/orchestration/tftp.rb
>        rescue => e
Can you move this _inside_ the template_kinds loop? Have a look at Orchestration::DNS for a similar example, where the rebuild method always tries to rebuild as much as possible, even if one fails, but then returns `false` on failure.

2016-10-10 15:01 UTC, lzap commented
Ah, sorry about this one. This is when tests won't help much, compiler would do it.

2016-10-10 15:41 UTC, timogoebel commented
@lzap: No worries. ;-)

@domcleal : Pushed the latest changes that should address your comment.

2016-10-13 09:09 UTC, domcleal approved these changes

2016-10-13 09:10 UTC, merged

2016-10-13 09:10 UTC, domcleal commented
Merged, thanks @timogoebel.