fixes #16951 - ipv6 compute orchestration
theforeman/foreman pull request #3943
Opened 2016-10-16 14:32 UTC by timogoebel

2016-10-16 14:34 UTC, timogoebel commented
This can be tested with https://github.com/theforeman/foreman-digitalocean/pull/16

2016-10-24 10:05 UTC, domcleal requested changes
find_address causes problems when IPv6 is not active on a v6-capable provider.

2016-10-24 10:05 UTC, domcleal commented on app/models/concerns/orchestration/compute.rb
>            value = vm.send(fog_attr) || find_address
`find_address` isn't IPv6 aware here, it'll call `vm.ip_addresses` which can return v4 addresses if the compute claims to provide v6 but `vm.send(fog_attr)` returns nil. You can reproduce this by _not_ ticking the IPv6 box when using fog-digitalocean.

It probably needs to be changed to filter addresses from `vm.ip_addresses` depending on their type?

2016-11-01 13:33 UTC, timogoebel commented
@domcleal : The code is more reliable now. `find_address` filters the ip addresses by type and returns early if any other ip address is already set. I also removed the `delCompute` calls from `validate_forman_attr` as they would eventually try to delete the vm twice.

[test foreman]
[test katello]
[test upgrade]

2016-11-01 14:08 UTC, domcleal commented
[test foreman]

2016-11-01 14:44 UTC, domcleal requested changes

2016-11-01 14:44 UTC, domcleal commented on app/models/concerns/orchestration/compute.rb
> +        return failure(_("failed to acquire ip addresses from compute resource for %s") % name)
Capitalise "Failed" and "IP", important in translated (and therefore user-visible) strings.

2016-11-01 14:44 UTC, domcleal commented on app/models/concerns/orchestration/compute.rb
> +    addresses.map {|ip| IPAddr.new(ip) rescue nil}.compact.select { |ip| ip.send(check_method) }.map(&:to_s)
`select { |ip| ip.send(check_method) }` can be written as `select(&check_method)`

2016-11-01 14:44 UTC, domcleal commented on app/models/concerns/orchestration/compute.rb
>            return false unless validate_foreman_attr(value, ::Nic::Base, foreman_attr)
If the provider claims to provide :ip6 but it doesn't (e.g. foreman_digitalocean, don't tick IPv6), then this still throws an error if `value.blank?` and there's another blank value in the database. Don't call it if the value's blank?

    2016-11-01T14:36:30 c50b235a [sql] [W] ip6  is already used by

2016-11-01 14:44 UTC, domcleal commented on test/models/orchestration/compute_test.rb
> +      @host.vm.expects(:ip6).returns(an_ip6)
A test that returns a blank value for :ip6 while claiming to provide ip4 + ip6 would be a good idea.

2016-11-01 14:57 UTC, timogoebel commented on app/models/concerns/orchestration/compute.rb
>            return false unless validate_foreman_attr(value, ::Nic::Base, foreman_attr)
Oh, sorry. I have tested this with a fresh install and an empty database and it worked fine. I will make the necessary adjustments and add a test case for this.

2016-11-01 15:56 UTC, timogoebel commented
@domcleal : Thanks for giving this another spin. I have fixed the issue and tested with more hosts. It should work fine now. Also improved the test coverage of this.

2016-11-02 10:18 UTC, domcleal approved these changes

2016-11-02 10:18 UTC, merged

2016-11-02 10:18 UTC, domcleal commented
Merged, thanks @timogoebel.