Fixes #17005 - more strict debug password filter
theforeman/foreman pull request #3952
Opened 2016-10-19 07:18 UTC by lzap

We have reports on missed password entries in logs and config files, see the
ticket for the complete list. This patch covers answer files (default files)
and also certificate key files.

2016-10-24 13:31 UTC, domcleal requested changes
There are also foreman-proxy related bits of the bug report, please file a new ticket against the Smart Proxy and fix them in its foreman-debug script too.

2016-10-24 13:31 UTC, domcleal commented on script/foreman-debug
> +key
This causes paths in installer answer files or Foreman's own settings.yaml (e.g. ssl_priv_key) to be filtered out, e.g. `client_ssl_key`, is that intentional?

2016-10-24 13:31 UTC, domcleal commented on script/foreman-debug
> +FILTER="s/($FILTER_WORDS_STR)(\"?\s*[:= ]\s*)\S+/\1\2+FILTERED+/g"
No need for the extra space here? \s* is either side of it.

2016-10-24 13:31 UTC, domcleal commented on script/foreman-debug
> +add_files /etc/foreman/*.{yml,yaml,conf} /etc/foreman/*{cert,ca}.pem /etc/foreman/plugins/
1. No need for *{cert,ca}.pem here I think, that depends on the user's configuration? If it's from Katello, please add it to their debug scripts.
1. /etc/foreman/plugins/ is missing a filename, so it's not picking up any files. *.yaml might be most precise (that's all that's loaded anyway).

2016-11-08 07:40 UTC, lzap commented on script/foreman-debug
> +key
Yes, the problem with current approach mentioning only specific strings was not working apparently, this patch tighten the filtering causing a lot more false alerts which should be safer. If you don't like, I can simply name them.

2016-11-08 07:40 UTC, lzap commented on script/foreman-debug
> +FILTER="s/($FILTER_WORDS_STR)(\"?\s*[:= ]\s*)\S+/\1\2+FILTERED+/g"
Yeah thanks.

2016-11-08 07:42 UTC, lzap commented on script/foreman-debug
> +add_files /etc/foreman/*.{yml,yaml,conf} /etc/foreman/*{cert,ca}.pem /etc/foreman/plugins/
Removed katello related certs, added `yaml` extension.

2016-11-08 07:51 UTC, lzap commented
Resolved conflicts.

2016-11-08 07:55 UTC, lzap commented
Here is an example session, Foreman 1.13:

```
/tmp/debug/var/log/foreman/production.log:2016-10-25 02:41:08 e16b3a18 [app] [I]   Parameters: {"utf8"=>"✓", "authenticity_token"=+FILTERED+ "login"=>{"login"=>"admin", "password"=+FILTERED+ "commit"=>"Login"}
/tmp/debug/var/log/foreman/production.log:2016-10-25 02:41:16 45c825f8 [app] [I]   Parameters: {"utf8"=>"✓", "authenticity_token"=+FILTERED+ "host"=>{"name"=>"gwen-navappo", "hostgroup_id"=>"1", "managed"=>"true", "progress_report_id"=>"[FILTERED]", "type"=>"Host::Managed", "interfaces_attributes"=>{"0"=>{"_destroy"=>"0", "type"=>"Nic::Managed", "mac"=>"", "identifier"=>"", "name"=>"gwen-navappo", "domain_id"=>"", "subnet_id"=>"", "ip"=>"", "ip6"=>"", "managed"=>"1", "primary"=>"1", "provision"=>"1", "virtual"=>"0", "tag"=>"", "attached_to"=>""}}, "architecture_id"=>"", "provision_method"=>"build", "build"=>"1", "disk"=>"", "root_pass"=>"[FILTERED]", "is_owned_by"=>"3-Users", "enabled"=>"1", "model_id"=>"", "comment"=>"", "overwrite"=>"false"}, "fakepassword"=+FILTERED+ "bare_metal_capabilities"=>"build"}
/tmp/debug/var/log/foreman/production.log:2016-10-25 02:41:17 45c825f8 [app] [I]   Parameters: {"utf8"=>"✓", "authenticity_token"=+FILTERED+ "host"=>{"name"=>"gwen-navappo", "hostgroup_id"=>"1", "compute_resource_id"=>"", "puppetclass_ids"=>[""], "managed"=>"true", "progress_report_id"=>"[FILTERED]", "type"=>"Host::Managed", "interfaces_attributes"=>{"0"=>{"_destroy"=>"0", "type"=>"Nic::Managed", "mac"=>"", "identifier"=>"", "name"=>"gwen-navappo", "domain_id"=>"2", "subnet_id"=>"1", "ip"=>"", "ip6"=>"", "managed"=>"1", "primary"=>"1", "provision"=>"1", "virtual"=>"0", "tag"=>"", "attached_to"=>""}}, "architecture_id"=>"1", "operatingsystem_id"=>"1", "provision_method"=>"build", "build"=>"1", "medium_id"=>"1", "ptable_id"=>"80", "pxe_loader"=>"Grub2 UEFI", "disk"=>"", "root_pass"=>"[FILTERED]", "is_owned_by"=>"3-Users", "enabled"=>"1", "model_id"=>"", "comment"=>"", "overwrite"=>"false"}, "fakepassword"=+FILTERED+ "bare_metal_capabilities"=>"build"}
/tmp/debug/var/log/foreman/production.log:2016-10-25 02:41:51 45c825f8 [app] [I]   Parameters: {"utf8"=>"✓", "authenticity_token"=+FILTERED+ "host"=>{"name"=>"gwen-navappo", "hostgroup_id"=>"1", "compute_resource_id"=>"", "puppetclass_ids"=>[""], "managed"=>"true", "progress_report_id"=>"[FILTERED]", "type"=>"Host::Managed", "interfaces_attributes"=>{"0"=>{"_destroy"=>"0", "type"=>"Nic::Managed", "mac"=>"52:54:00:60:d0:fe", "identifier"=>"", "name"=>"gwen-navappo", "domain_id"=>"2", "subnet_id"=>"1", "ip"=>"192.168.222.100", "ip6"=>"", "managed"=>"1", "primary"=>"1", "provision"=>"1", "virtual"=>"0", "tag"=>"", "attached_to"=>""}, "1477377700813"=>{"_destroy"=>"0", "type"=>"Nic::Managed", "mac"=>"52:54:00:60:d0:fe", "identifier"=>"", "name"=>"", "domain_id"=>"", "subnet_id"=>"1", "ip"=>"192.168.222.101", "ip6"=>"", "managed"=>"1", "primary"=>"0", "provision"=>"0", "virtual"=>"0", "tag"=>"", "attached_to"=>""}}, "architecture_id"=>"1", "operatingsystem_id"=>"1", "provision_method"=>"build", "build"=>"1", "medium_id"=>"1", "ptable_id"=>"80", "pxe_loader"=>"Grub2 UEFI", "disk"=>"", "root_pass"=>"[FILTERED]", "is_owned_by"=>"3-Users", "enabled"=>"1", "model_id"=>"", "comment"=>"", "overwrite"=>"false"}, "bare_metal_capabilities"=>"build"}
/tmp/debug/var/log/foreman/production.log:2016-10-25 09:30:42 9130b1f7 [app] [I]   Parameters: {"utf8"=>"✓", "authenticity_token"=+FILTERED+ "login"=>{"login"=>"admin", "password"=+FILTERED+ "commit"=>"Login"}
/tmp/debug/var/log/foreman/production.log:2016-10-25 10:07:11 95be5624 [app] [I]   Parameters: {"utf8"=>"✓", "authenticity_token"=+FILTERED+ "host"=>{"name"=>"joni-weller", "hostgroup_id"=>"", "compute_resource_id"=>"", "environment_id"=>"", "puppet_ca_proxy_id"=>"", "puppet_proxy_id"=>"", "managed"=>"true", "progress_report_id"=>"[FILTERED]", "type"=>"Host::Managed", "interfaces_attributes"=>{"0"=>{"_destroy"=>"0", "type"=>"Nic::Managed", "mac"=>"", "identifier"=>"", "name"=>"joni-weller", "domain_id"=>"", "subnet_id"=>"", "ip"=>"", "ip6"=>"", "managed"=>"1", "primary"=>"1", "provision"=>"1", "virtual"=>"0", "tag"=>"", "attached_to"=>""}}, "architecture_id"=>"", "provision_method"=>"build", "build"=>"1", "disk"=>"", "root_pass"=>"[FILTERED]", "is_owned_by"=>"3-Users", "enabled"=>"1", "model_id"=>"", "comment"=>"", "overwrite"=>"false"}, "bare_metal_capabilities"=>"build"}
/tmp/debug/var/log/foreman/production.log:2016-10-25 10:07:25 95be5624 [app] [I]   Parameters: {"utf8"=>"✓", "authenticity_token"=+FILTERED+ "host"=>{"name"=>"joni-weller", "hostgroup_id"=>"1", "managed"=>"true", "progress_report_id"=>"[FILTERED]", "type"=>"Host::Managed", "interfaces_attributes"=>{"0"=>{"_destroy"=>"0", "type"=>"Nic::Managed", "mac"=>"52:54:00:c6:a9:df", "identifier"=>"", "name"=>"joni-weller", "domain_id"=>"", "subnet_id"=>"", "ip"=>"", "ip6"=>"", "managed"=>"1", "primary"=>"1", "provision"=>"1", "virtual"=>"0", "tag"=>"", "attached_to"=>""}}, "architecture_id"=>"", "provision_method"=>"build", "build"=>"1", "disk"=>"", "root_pass"=>"[FILTERED]", "is_owned_by"=>"3-Users", "enabled"=>"1", "model_id"=>"", "comment"=>"", "overwrite"=>"false"}, "fakepassword"=+FILTERED+ "bare_metal_capabilities"=>"build"}
/tmp/debug/var/log/foreman/production.log:2016-10-25 10:07:25 95be5624 [app] [I]   Parameters: {"utf8"=>"✓", "authenticity_token"=+FILTERED+ "host"=>{"name"=>"joni-weller", "hostgroup_id"=>"1", "compute_resource_id"=>"", "puppetclass_ids"=>[""], "managed"=>"true", "progress_report_id"=>"[FILTERED]", "type"=>"Host::Managed", "interfaces_attributes"=>{"0"=>{"_destroy"=>"0", "type"=>"Nic::Managed", "mac"=>"52:54:00:c6:a9:df", "identifier"=>"", "name"=>"joni-weller", "domain_id"=>"2", "subnet_id"=>"1", "ip"=>"", "ip6"=>"", "managed"=>"1", "primary"=>"1", "provision"=>"1", "virtual"=>"0", "tag"=>"", "attached_to"=>""}}, "architecture_id"=>"1", "operatingsystem_id"=>"1", "provision_method"=>"build", "build"=>"1", "medium_id"=>"1", "ptable_id"=>"80", "pxe_loader"=>"Grub2 UEFI", "disk"=>"", "root_pass"=>"[FILTERED]", "is_owned_by"=>"3-Users", "enabled"=>"1", "model_id"=>"", "comment"=>"", "overwrite"=>"false"}, "fakepassword"=+FILTERED+ "bare_metal_capabilities"=>"build"}
/tmp/debug/var/log/foreman/production.log:2016-10-25 10:07:26 95be5624 [app] [I]   Parameters: {"utf8"=>"✓", "authenticity_token"=+FILTERED+ "host"=>{"name"=>"joni-weller", "hostgroup_id"=>"1", "compute_resource_id"=>"", "puppetclass_ids"=>[""], "managed"=>"true", "progress_report_id"=>"[FILTERED]", "type"=>"Host::Managed", "interfaces_attributes"=>{"0"=>{"_destroy"=>"0", "type"=>"Nic::Managed", "mac"=>"52:54:00:c6:a9:df", "identifier"=>"", "name"=>"joni-weller", "domain_id"=>"2", "subnet_id"=>"1", "ip6"=>"", "managed"=>"1", "primary"=>"1", "provision"=>"1", "virtual"=>"0", "tag"=>"", "attached_to"=>""}}, "architecture_id"=>"1", "operatingsystem_id"=>"1", "provision_method"=>"build", "build"=>"1", "medium_id"=>"1", "ptable_id"=>"80", "pxe_loader"=>"Grub2 UEFI", "disk"=>"", "root_pass"=>"[FILTERED]", "is_owned_by"=>"3-Users", "enabled"=>"1", "model_id"=>"", "comment"=>"", "overwrite"=>"false"}, "bare_metal_capabilities"=>"build"}
/tmp/debug/var/log/foreman/production.log:2016-10-25 10:07:38 95be5624 [app] [I]   Parameters: {"authenticity_token"=+FILTERED+ "id"=>"joni-weller.nested.lan"}
/tmp/debug/var/log/foreman/production.log:2016-11-01 10:50:07 702e8084 [app] [I]   Parameters: {"utf8"=>"✓", "authenticity_token"=+FILTERED+ "login"=>{"login"=>"admin", "password"=+FILTERED+ "commit"=>"Login"}
/tmp/debug/var/log/foreman/production.log:2016-11-02 08:28:53 ba442256 [app] [I]   Parameters: {"utf8"=>"✓", "authenticity_token"=+FILTERED+ "login"=>{"login"=>"admin", "password"=+FILTERED+ "commit"=>"Login"}
/tmp/debug/var/log/foreman/production.log:2016-11-02 09:08:26 1fae37c2 [app] [I]   Parameters: {"utf8"=>"✓", "authenticity_token"=+FILTERED+ "changed"=>{"new"=>{"production"=>"{\"stdlib::stages\":{\"new\":{}},\"stdlib\":{\"new\":{}},\"ntp::service\":{\"new\":{}},\"ntp::config\ [...]

2016-11-08 11:32 UTC, domcleal commented on script/foreman-debug
> +key
What strings are you talking about specifically? The ticket mentions "oauth_consumer_key" - if that's the only one (and I'm unsure it's a secret, as there is a separate secret), then it's probably worth naming.

2016-12-22 08:17 UTC, lzap commented
Note to myself: Additional string in installer log:

```
> [ INFO 2015-07-20 10:19:51 main] +    "proxy_username": "my_username",
> [ INFO 2015-07-20 10:19:51 main] +    "proxy_password": "SomeSecretPassword"
```

2017-02-01 17:35 UTC, lzap commented
Ok added the full `oauth_consumer_key`. Summary, this should be filtered out:

```
  "capsule::params::pulp_admin_password": XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  "::foreman::params::db_password": XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  "::foreman::params::oauth_consumer_key": XXXXXXXXXXXXXXXXXXXXXXXXXXX
  "::foreman::params::oauth_consumer_secret": XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  "::foreman::params::admin_password": XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  "foreman_proxy::params::oauth_consumer_key": XXXXXXXXXXXXXXXXXXXXXXXXXX
  "foreman_proxy::params::oauth_consumer_secret": XXXXXXXXXXXXXXXXXXXXXXXXXX
  "katello::params::oauth_secret": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX" 
  "katello::params::post_sync_token": XXXXXXXXXXXXXXXXXXXXXXXXXXX
 [ INFO 2015-07-20 10:19:51 main] +    "proxy_password": "SomeSecretPassword"
```

2017-02-02 09:58 UTC, domcleal approved these changes

2017-02-02 09:58 UTC, merged

2017-02-02 09:58 UTC, domcleal commented
Merged, thanks @lzap. Please complete the security process.