Fixes 17084 - add webpack on welcome packages
theforeman/foreman pull request #3975
Opened 2016-10-27 11:59 UTC by bastilian

On pages where the welcome action in the app controller was triggered
the webpack server was not added due to welcome rendering before

2016-10-27 12:18 UTC, ares commented
@theforeman-bot ok to test

2016-10-27 12:21 UTC, ares commented
@bastilian please change the commit message so it follows the pattern, e.g. "Fixes #17084 - add webpack on welcome packages" and `git push -f`. I tested the patch and it fixes the issue for me. If tests passes it's good to merge after the commit message change.

2016-10-27 12:25 UTC, bastilian commented
Commit message fixed and pushed.

2016-10-27 13:05 UTC, domcleal requested changes
Also the commit message states "welcome packages" - should it say "welcome pages"?

2016-10-27 13:05 UTC, domcleal commented on app/controllers/application_controller.rb
>    before_action :authorize
The same applies to `authorize`, the CSP headers must be in place for the 403 page.

2016-10-27 13:26 UTC, bastilian commented
@domcleal packages is now corrected to pages. and it now uses `prepend_before_action` and includes a test to verify it is also set on unauthorised page requests.

2016-10-27 13:35 UTC, domcleal requested changes

2016-10-27 13:35 UTC, domcleal commented on test/integration/middleware_test.rb
> +      Environment.stubs(:first).returns(nil)
Both new tests are missing any verification that these stubs have triggered the filters you expect. Probably at a minimum they should be expectations, but some kind of verification of the page content may also help.

2016-10-27 13:35 UTC, domcleal commented on test/integration/middleware_test.rb
> +  test "webpack dev server adds the dev server to Content-Security-Policy on unauthirized page requests" do
spelling, "unauthorized"

2016-10-27 13:35 UTC, domcleal commented on test/integration/middleware_test.rb
> +      User.stubs(:current).returns(nil)
Prefer overriding `login_admin` (see user_test.rb), same comment as above applies - no verification that this tests the `authorize` filter behaviour.

2016-10-27 20:23 UTC, bastilian commented
@domcleal thanks for taking a closer look at it!

I've added assertions to verify the behaviour of what the stubs should trigger as well, override the `login_admin` for the unauthorised test and wrap the three tests in a context to clean it up.

2016-10-28 08:00 UTC, domcleal approved these changes

2016-10-28 09:43 UTC, domcleal requested changes

2016-10-28 09:43 UTC, domcleal commented on test/integration/middleware_test.rb
> +        assert page.status_code, '403'
`assert_equal '403', page.status_code` - this currently asserts that page.status_code is trueish

2016-10-31 06:50 UTC, bastilian commented
@domcleal I've cleaned it up now and added `logout_admin`, which simple removes the cookie, since overriding `login_admin` did not trigger an unauthorised request in this case.

2016-10-31 08:29 UTC, domcleal approved these changes

2016-10-31 08:30 UTC, merged

2016-10-31 08:30 UTC, domcleal commented
Merged, thanks @bastilian.

2016-10-31 08:54 UTC, bastilian commented
Thanks for merging @domcleal! 🎉  :)