Fixes #17151 - sort PXE labels by hostname title
theforeman/foreman pull request #3982
Opened 2016-11-01 13:06 UTC by amirfefer

The title includes the whole path, sorting by hostname's name may result with unsorted nested hostgroups.

2016-11-01 15:15 UTC, domcleal commented
There are some test failures, so setting WoC. If this is caused by the new fixture, it would be preferable to use factories for tests that need the additional host group rather than modifying fixtures.

Please also check the commit message, I don't think you mean hostnames, I think this refers to host group names.

2016-11-01 15:23 UTC, domcleal requested changes

2016-11-01 15:23 UTC, domcleal commented on test/controllers/provisioning_templates_controller_test.rb
> +      t1.save
Use `TemplateCombination.create` to avoid all of this editing and saving, or preferably just use the :template_combination factory.

2016-11-01 15:23 UTC, domcleal commented on test/controllers/provisioning_templates_controller_test.rb
> +    test "pxe menu's labels should be sorted by full hostname title" do
hostgroup

2016-11-01 15:23 UTC, domcleal commented on test/controllers/provisioning_templates_controller_test.rb
> +      ProxyAPI::TFTP.any_instance.expects(:create_default).with(regexp_matches(/^PXE.*/), has_entry(:menu, regexp_matches(/#{hostgroups(:nested).name}.*#{hostgroups(:inherited).name}/m))).returns(tru
If you really intend to test the ordering, explicitly create host groups with names above that will exercise it - it's not clear from the fixtures that the names are meant to be sorted this way.

2016-11-03 10:12 UTC, amirfefer commented
@domcleal  Thanks for your review, I've changed the test by using factory.

2016-11-03 11:18 UTC, domcleal approved these changes

2016-11-03 11:19 UTC, merged

2016-11-03 11:19 UTC, domcleal commented
Merged, thanks @amirfefer.

2016-11-08 10:18 UTC, lzap commented
Nice one, this was driving me crazy :-)