[Performance] Menu item url_hash optimized
theforeman/foreman pull request #3986
Opened 2016-11-02 13:07 UTC by lzap

My foreman-tracer utility reveled that we allocate about 800 arrays each
request here. I think we can optimize this, not creating ticket until confirmed
by someone else.

2016-11-02 14:51 UTC, lzap commented
The katello failure is irrelevant, I believe. The patch looks correct to me, I will go ahead and create an issue number for this one.

2016-11-03 14:14 UTC, domcleal requested changes
Ticket's still missing.

2016-11-03 14:14 UTC, domcleal commented on app/services/menu/item.rb
>          h[key] = (value.respond_to?(:call) ? value.call : value)
Returning early prevents this entire block of code from ever running - so procs aren't executed here.

2016-11-03 14:18 UTC, ohadlevy commented
@lzap please note, the entire top level menu is cached in production. did you run your tracer in production or development environment?

2016-11-07 20:14 UTC, lzap commented
It was production, looks like you are right, the top menu is only generated once.

2016-11-07 20:14 UTC, closed without merging