Fixes #17238 - Validates lookup value match exists in key path
theforeman/foreman pull request #3997
Opened 2016-11-06 16:48 UTC by orrabin

2016-11-08 13:13 UTC, domcleal requested changes
I think the tests need re-checking after fixing `path.include?` to check the array of path elements instead of the path string, there will probably be more failures.

2016-11-08 13:13 UTC, domcleal commented on app/models/lookup_value.rb
> +        return false
No need to return here or at the end, adding the error's enough and lets the user see _all_ errors.

2016-11-08 13:13 UTC, domcleal commented on test/integration/hostgroup_test.rb
> +    lookup_key = FactoryGirl.create(:puppetclass_lookup_key, :as_smart_class_param, :with_override, :path => "hostgroup/ncomment",
`\n`

2016-11-08 13:13 UTC, domcleal commented on test/models/hostgroup_test.rb
> +      FactoryGirl.create(:puppetclass_lookup_key, :as_smart_class_param, :with_override, :path => "hostgroup/ncomment", :puppetclass => group.puppetclasses.first, :overrides => {group.lookup_value_ma
`\n`

2016-11-08 13:13 UTC, domcleal commented on test/models/lookup_value_test.rb
> +    key.path += '\nfoo'
1. `\nfoo` with single quotes wouldn't actually create a new line, is this really doing anything?
1. Would it be better to change the `foo` in the lookup_value below to `comment` or whatever's in the key path?

2016-11-08 13:13 UTC, domcleal commented on test/models/lookup_value_test.rb
> +                                :with_override, :with_omit, :path => 'hostgroup\ncomment',
ditto, \n in a single quoted string?

2016-11-08 13:13 UTC, domcleal commented on test/models/lookup_value_test.rb
> +                             :with_override, :path => 'hostgroup\ncomment',
ditto

2016-11-08 13:13 UTC, domcleal commented on app/models/lookup_value.rb
> +      unless lookup_key.path.include?(key_element)
I think `path` needs to be split here to more precisely check whether the attribute is in the _array_ of path items, not just the path _string_ as a whole. The path array should be accessible through `path_elements`.

I think this is why some tests that used single quotes for `path` are passing when they shouldn't (see comments further down).

2016-11-10 14:07 UTC, orrabin commented on app/models/lookup_value.rb
> +      unless lookup_key.path.include?(key_element)
You're right. that's better. The fact that I missed a few or the single quoted strings proves this is still permitting unknown matchers, I'll change it.

2016-11-10 14:11 UTC, orrabin commented on test/models/lookup_value_test.rb
> +    key.path += '\nfoo'
2. I'll change it, it doesn't really matter for this test.

2016-11-13 13:34 UTC, orrabin commented
@domcleal thanks for the review. `ensure_matcher_exists` now handles multiple matchers correctly and the tests are also fixed.

2016-11-14 12:38 UTC, domcleal approved these changes

2016-11-14 12:38 UTC, merged

2016-11-14 12:38 UTC, domcleal commented
Merged, thanks @orrabin.