Fixes #5176 - Adding vSphere as an OS type
theforeman/foreman pull request #3998
Opened 2016-11-06 18:30 UTC by LiamLeane

This was originally theforeman/foreman#3351, github isn't opening the pull back up after clearing commits and submitting a new one so new PR.

Adds vSphere as an OS type for VCSA, ESXi etc.

2016-11-07 08:21 UTC, timogoebel commented
@theforeman-bot ok to test

2016-11-07 16:24 UTC, timogoebel commented
@LiamLeane : First of all, thanks for this PR. I think, every new os is a great addition to Foreman.

I didn't have time to take a closer look, but you definitely need to fix the test in `test/models/operatingsystem_test.rb:162`.

2016-11-08 12:27 UTC, dLobatog commented
Seems OK, thanks @LiamLeane ! What templates are you using to deploy this? The ones in the Foreman wiki? http://projects.theforeman.org/projects/foreman/wiki/VMware_ESXi ? 

If so - would you mind to share the ones you're using? I'd like to deploy ESXi using this and merge. Thanks!

2016-11-08 12:55 UTC, timogoebel commented
@dLobatog : There is a PR that adds the templates: https://github.com/theforeman/community-templates/pull/249

2016-11-08 17:16 UTC, dLobatog requested changes

2016-11-08 17:16 UTC, dLobatog commented on app/models/operatingsystems/vsphere.rb
> +  def pxe_type
This needs also 

```ruby
def pxedir
  "EFI/BOOT"
end
```

Not sure 100% about whether that path suits all versions but for 6.0 that seems OK

2016-11-08 17:16 UTC, dLobatog commented on app/models/operatingsystems/vsphere.rb
> +
This needs an `available_loaders` method too to list all of the possible PXE loaders

2017-05-18 08:04 UTC, closed without merging