[DNF] fixes #14178 - introduce patternfly toast notifications
theforeman/foreman pull request #4007
Opened 2016-11-08 15:37 UTC by ohadlevy

this PR replaces the jnotify implementation.

TODO:
- add missing tests.
- consider better ways to push data as props vs using the notify function.

Don't merge, since I've started this work a while, i realize its better
open as PR for comments.

2016-11-09 12:16 UTC, gailsteiger commented on webpack/assets/javascripts/react_app/components/toasts/Toast.js
> +    );
Why not use html button tag here as in patternfly reference markup. What do we gain from using the react-bootstrap component?

2016-11-09 12:31 UTC, ohadlevy commented on webpack/assets/javascripts/react_app/components/toasts/Toast.js
> +    );
most likely in this usage case its not that important.. i can go either way.

2016-11-09 12:31 UTC, ohadlevy commented on webpack/assets/javascripts/react_app/components/toasts/Toast.js
> +    );
but i dont think it implies we don't need react-bootstrap?

2016-11-09 12:38 UTC, gailsteiger commented on webpack/assets/javascripts/react_app/components/toasts/Toast.js
> +    );
It doesn't imply that we don't need react-bootstrap, just that we don't need it here.

2016-11-09 12:40 UTC, ohadlevy commented
now using plain buttons instead of a react-bootstrap component.

2016-11-09 12:50 UTC, ohadlevy commented
I've just noticed https://github.com/bentatum/react-fade, maybe we can remove the Expire component and replace it with <Fade>

2017-01-31 10:53 UTC, ohadlevy commented
@gailsteiger @tbrisker I've rebased this and updated, can you have a look please and comment on the approach? thanks.

2017-02-01 13:46 UTC, tbrisker requested changes
:1st_place_medal: for getting rid of one of one of our unmaintained dependencies, see inline comments.

2017-02-01 13:46 UTC, tbrisker commented on webpack/assets/javascripts/foreman_notifications.js
> +export function importFlashMessagesFromRails() {
Does this actually need exporting? if it is only used internally in this module, don't export it.

2017-02-01 13:46 UTC, tbrisker commented on webpack/assets/javascripts/foreman_notifications.js
> +    notify({type: type, message: message, sticky: (type === 'error')});
I think `notify({type, message, sticky: (type === 'error')});` will also work

2017-02-01 13:46 UTC, tbrisker commented on app/assets/javascripts/application.js
> +  console.log("DEPRECATION WARNING: you are using deprecated notify() function, \
`console.warn` maybe?

2017-02-01 13:46 UTC, tbrisker commented on app/assets/javascripts/application.js
> +  console.log("DEPRECATION WARNING: you are using deprecated notify() function, \
Also, how about making this into `tfm.tools.deprecate('notify','1.17')`?

2017-02-01 13:46 UTC, tbrisker commented on app/assets/javascripts/dashboard.js
> +                notify(__("Widget removed from dashboard."), 'success');
why not use  `tfm.notifications.notify` directly?

2017-02-01 13:46 UTC, tbrisker commented on webpack/assets/javascripts/bundle.js
> +    notifications: require('./foreman_notifications'),
this might cause confusion with the notification drawer, maybe name it toast instead?

2017-02-01 13:46 UTC, tbrisker commented on webpack/assets/javascripts/foreman_notifications.js
> +  notifications.forEach(notification => {
you can use destructuring directly in the function definition, like so:
`notifications.forEach(([type, message]) => {...`

2017-02-01 13:46 UTC, tbrisker commented on webpack/assets/javascripts/foreman_notifications.js
> +    notify({type: type, message: message, sticky: (type === 'error')});
also, previously warning was also sticky (the condition checked for `type!='success'`)

2017-02-01 13:46 UTC, tbrisker commented on webpack/assets/javascripts/react_app/components/notifications/toast/Toast.js
> +const Toast = (props) => {
Not crucial but how about destructuring the props here so that it's clear which props we expect?

2017-02-01 13:46 UTC, tbrisker commented on webpack/assets/javascripts/react_app/common/MountingService.js
> +    FlashNotifications: {
Shouldn't this also be called ToastNotifications?

2017-02-01 13:46 UTC, tbrisker commented on webpack/assets/javascripts/react_app/components/common/Fade.js
> +export default class Fade extends React.Component {
Correct me if i'm wrong but this doesn't actually fade, just removes the content when time is out?

2017-02-01 13:46 UTC, tbrisker commented on webpack/assets/javascripts/react_app/stores/ToastNotificationsStore.js
> +    case ACTIONS.FADED_NOTIFICATION: {
If this action isn't used remove it?

2017-02-01 13:46 UTC, tbrisker commented on webpack/stories/index.js
> +// from '../assets/javascripts/react_app/components/notifications/toast/FlashNotifications';
leftovers?

2017-02-01 14:38 UTC, ohadlevy commented on webpack/assets/javascripts/react_app/components/notifications/toast/Toast.js
> +const Toast = (props) => {
I tried, but it was more than 4, that was both lint error and pretty long, there is probably a react way to describe the props - @gailsteiger ?

2017-02-01 14:39 UTC, ohadlevy commented on webpack/assets/javascripts/react_app/components/common/Fade.js
> +export default class Fade extends React.Component {
Yeah, would Expire be a better name?

2017-02-01 14:40 UTC, ohadlevy commented
@tbrisker I've addressed your comments, I did not handle the deprecation as I wasn't sure whats the best way to call a function from string, I think it deserve its own PR too.

2017-02-01 15:31 UTC, tbrisker requested changes
Some more comments inline, opened https://github.com/theforeman/foreman/pull/4246 for the deprecation message.

2017-02-01 15:31 UTC, tbrisker commented on LICENSE
> -* vendor/assets/javascripts/jquery.jnotify.js is (c) 2010 Giva, Inc. under ASL 2.0 license.
This was the only one using ASL, we can remove it below.

2017-02-01 15:31 UTC, tbrisker commented on app/assets/javascripts/application.js
>  function notify(item, type) {
you can change the parameter name to `message`, then below call
```js
tfm.toastNotifications.notify({message, type});
```

2017-02-01 15:31 UTC, tbrisker commented on vendor/assets/stylesheets/vendor.scss
> -@import "/**/*";
Why not remove the folder entirely?

2017-02-01 15:31 UTC, tbrisker commented on webpack/assets/javascripts/react_app/components/common/Fade.js
> +export default class Fade extends React.Component {
Maybe, or maybe use the fade component you found that actually does fade?

2017-02-01 15:31 UTC, tbrisker commented on webpack/assets/javascripts/react_app/components/notifications/toast/Toast.js
> +          {props.link}
What happens if there is no link? Also, shouldn't the link also have a target that isn't `#`?

2017-02-02 08:59 UTC, ohadlevy commented on vendor/assets/stylesheets/vendor.scss
> -@import "/**/*";
We no longer use it, and I hope we would not need to as we moved assets to npm/yarn packages

2017-02-02 09:00 UTC, ohadlevy commented on webpack/assets/javascripts/react_app/components/common/Fade.js
> +export default class Fade extends React.Component {
I did that initially, but it ended up pulling a lot of unneeded dependencies.

2017-02-02 10:39 UTC, gailsteiger commented on webpack/assets/javascripts/react_app/components/common/Alert.js
> +      <Icon type="close" />
We shouldn't use the bootstrap js. It manipulates the DOM. Need to be careful about inconsistencies between the DOM, the virtual DOM and the data.

2017-02-02 10:42 UTC, gailsteiger commented on webpack/assets/javascripts/react_app/components/notifications/toast/Toast.js
> +const Toast = (props) => {
You can always break the statement into 2 or more lines. The question is whether or not destructuring the props in this case adds clarity or causes confusion.

2017-02-02 10:43 UTC, gailsteiger commented on webpack/assets/javascripts/react_app/components/common/Fade.js
> +export default class Fade extends React.Component {
Is the content being removing via React or through DOM manipulation?

2017-02-02 10:45 UTC, gailsteiger commented on webpack/assets/javascripts/react_app/components/notifications/toast/Toast.js
> +          {props.link}
building the JSX such that the <a> is only include when there actually is a link. pointer cursor not desirable when there is nothing to click.

2017-02-02 10:52 UTC, gailsteiger commented
I think the terminology could be confusing between toast and notification. Worth considering

2017-02-05 08:50 UTC, matanwerbner commented on webpack/assets/javascripts/foreman_toast_notifications.js
> +$(window).bind('beforeunload', function () {
Shouldn't this action be fired on the "componentWillUnmount" lifecycle event of the notification component?

2017-02-07 07:45 UTC, gailsteiger commented on webpack/assets/javascripts/foreman_toast_notifications.js
> +$(window).bind('beforeunload', function () {
The implementation is WIP. It is not pure react and contains carryover aspects which directly manipulate the DOM. This will be cleaned up.

2017-02-19 11:34 UTC, ohadlevy commented
closed in favor of #4300

2017-02-19 11:34 UTC, closed without merging