add a new hosts dashboard widget
theforeman/foreman pull request #4034
Opened 2016-11-21 08:16 UTC by timogoebel

This commit adds a small dashboard that shows a list of the latest eight hosts that were created. Nothing too fancy.

2016-11-21 09:26 UTC, timogoebel commented
Tests failures look unrelated.

2016-11-21 10:47 UTC, ohadlevy commented on app/views/dashboard/_new_hosts_widget.html.erb
> +<% hosts = Host.authorized(:view_hosts).includes(:owner, :operatingsystem).order(:created_at => :desc).limit(8) %>
does it also make sense to do something based on installed_at attribute as well?

2016-11-21 10:47 UTC, ohadlevy commented on app/views/dashboard/_new_hosts_widget_host_list.html.erb
> +        <td><%= link_to trunc_with_tooltip(h(host.name)), host_path(host) %></td>
nitpick: h is not longer needed.

2016-11-21 11:53 UTC, tbrisker commented on app/views/dashboard/_new_hosts_widget.html.erb
> +<% hosts = Host.authorized(:view_hosts).includes(:owner, :operatingsystem).order(:created_at => :desc).limit(8) %>
the dashboard data service already loads hosts respecting authorization and filters, you can use `@data.hosts.includes...`  instead and get the widget to respect the filter.

2016-11-21 11:53 UTC, tbrisker commented on app/views/dashboard/_new_hosts_widget_host_list.html.erb
> +<table class="table table-striped ellipsis">
`ellipsis` class should be on the `<td>`, not the table. the table should have `table-fixed` and the `th` elements should set their width.

2016-11-21 11:53 UTC, tbrisker commented on app/views/dashboard/_new_hosts_widget_host_list.html.erb
> +        <td><%= link_to trunc_with_tooltip(h(host.name)), host_path(host) %></td>
`trunc_with_tooltip` is not needed if using `ellipsis` on the `td`.

2016-11-21 14:21 UTC, timogoebel commented
@ohadlevy, @tbrisker : Thanks for your comments. I added a "installed_at" column and fixed the ellipsis code.

2016-11-25 16:18 UTC, dLobatog commented
@timogoebel 👍 by me, however I'll wait until @tbrisker takes a final look since he's been the one reviewing this. Thank you 😄

2016-11-28 13:09 UTC, tbrisker requested changes
Mostly looks good, just a couple of inline comments.

2016-11-28 13:09 UTC, tbrisker commented on app/views/dashboard/_new_hosts_widget.html.erb
> +<% hosts = @data.hosts.includes(:operatingsystem).preload(:owner).order(:created_at => :desc).limit(8) %>
any reason not to use `.joins(:operatingsystem, :owner)` and getting the data in one call? also seems like there is room for 9 rows in the widget.

2016-11-28 13:09 UTC, tbrisker commented on app/views/dashboard/_new_hosts_widget_host_list.html.erb
> +        <td class="ellipsis"><%= link_to host.name, host_path(host) %></td>
Ellipsis on the dashboard seems broken but it is unrelated to this. Opened http://projects.theforeman.org/issues/17501 to handle that.

2016-11-28 13:17 UTC, timogoebel commented on app/views/dashboard/_new_hosts_widget.html.erb
> +<% hosts = @data.hosts.includes(:operatingsystem).preload(:owner).order(:created_at => :desc).limit(8) %>
Yes, rails joins seem to be broken for polymorphic associations. You can try that yourself, just use `includes(:operatingsystem, :owner)` and add a filter that doesn't match any host.

2016-11-28 13:18 UTC, timogoebel commented on app/views/dashboard/_new_hosts_widget_host_list.html.erb
> +        <td class="ellipsis"><%= link_to host.name, host_path(host) %></td>
Thanks.

2016-11-28 18:32 UTC, timogoebel commented on app/views/dashboard/_new_hosts_widget.html.erb
> +<% hosts = @data.hosts.includes(:operatingsystem).preload(:owner).order(:created_at => :desc).limit(8) %>
For the record, rails throws a `ActiveRecord::EagerLoadPolymorphicError: Cannot eagerly load the polymorphic association :owner` error.

2016-11-28 18:35 UTC, timogoebel commented
@tbrisker : Added one more row to the dashboard.

2016-11-28 19:10 UTC, tbrisker approved these changes

2016-11-28 19:11 UTC, tbrisker commented
good to merge once :green_apple:

2016-11-28 19:57 UTC, merged