Stop mention-bot from pinging inactive past contributers
theforeman/foreman pull request #4037
Opened 2016-11-22 10:41 UTC by tbrisker

2016-11-28 18:23 UTC, timogoebel requested changes
@tbrisker : Thanks. In addition to my inline comments, please file a redmine ticket for this.

2016-11-28 18:23 UTC, timogoebel commented on .mention-bot
> +  "requiredOrgs": ["theforeman"]
I think, this is missing a trailing comma to be valid json.

2016-11-28 18:23 UTC, timogoebel commented on .mention-bot
> +  "userBlackList": ["abenari", "unorthodoxgeek", "alongoldboim", "bgupta", "logicminds"]
Shouldn't we "remove" this guys from the organization if they're definitely inactive?

2016-12-07 15:17 UTC, tbrisker commented on .mention-bot
> +  "userBlackList": ["abenari", "unorthodoxgeek", "alongoldboim", "bgupta", "logicminds"]
I think we should, at least from the committer group, but only @domcleal and @ohadlevy have the permissions to do that.

2016-12-07 15:17 UTC, tbrisker commented
@timogoebel added ticket and fixed comment.

2016-12-08 14:15 UTC, dLobatog commented
There's https://github.com/mention-bot/how-to-unsubscribe too..

2016-12-08 14:58 UTC, tbrisker commented
@dLobatog thanks, that is useful for users not seeing notifications they don't care about but it will still ping them instead of relevant contributes, plus this is not useful for users that may be using mentionbot in other projects.

2016-12-19 16:41 UTC, timogoebel approved these changes
@tbrisker : Sorry for the delay, I was off. Looks good to me, will merge in a sec.

2016-12-19 16:42 UTC, merged