Fixes #17457 - multiple_checkboxes doesn't work with orgs/locs
theforeman/foreman pull request #4039
Opened 2016-11-23 09:34 UTC by dLobatog

multiple_checkboxes calls ActiveModel::Naming on associations that could
be simply "Taxonomy". This results on a 500 error 'undefined method
`taxonomies' for #<Filter:0x005593624bdd18>' (or whatever other class
has the problem). Simply trying to edit a filter will throw this 500
error.

We've always had this problem , but since #16971 removed the check for
only using that method for '> 5' associations, you'd only see the error
if you had at least 6 organizations or locations (unlikely). Now it
became more apparent and it shows up every time.

The fix I've used is just to take advantage of the options hash to send
the association name directly, and if it's not set, then use
ActiveModel::Naming to get it (as usual).

2016-11-24 12:21 UTC, tbrisker commented
Does this mean the workaround in https://github.com/theforeman/foreman/pull/3779 is no longer needed?

2016-11-24 14:45 UTC, dLobatog commented
@tbrisker It's still needed, that's a different issue

2016-11-28 12:29 UTC, tbrisker requested changes
I could not reproduce the condition which causes this error, however if you manage to reproduce it there is much simpler way to fix this w/o requiring change to the funtion caller - see inline comments

2016-11-28 12:29 UTC, tbrisker commented on app/helpers/form_helper.rb
> +    association_name = options[:association_name] ||
We already sent this as `attr`, no reason to send again in the options.

2016-11-28 12:29 UTC, tbrisker commented on app/helpers/form_helper.rb
> +                       ActiveModel::Naming.plural(associations.new)
`.new` here is not needed.

2016-11-28 12:29 UTC, tbrisker commented on app/helpers/form_helper.rb
>      selected_ids = associated_obj.select("#{associations.new.class.table_name}.id").map(&:id)
`associations.new.class.table_name == associations.table_name` AFAICT

2016-11-28 12:30 UTC, tbrisker commented
Also, if this is reproducible please add a test reproducing it so we don't break again.

2016-12-10 09:02 UTC, ares commented
I haven't done the review but it fixes the issue for me. I just went to role -> filters -> new filter and got the exception, after applying the patch, it works as expected.

2016-12-15 09:14 UTC, dLobatog commented on app/helpers/form_helper.rb
> -    associated_obj = klass.send(ActiveModel::Naming.plural(associations.new))
The bug is basically `klass.send(ActiveModel::Naming.plural(associations.new))` when associations is `User.current.organizations` produces 'taxonomies'

2016-12-15 09:15 UTC, dLobatog commented on app/helpers/form_helper.rb
> -    associated_obj = klass.send(ActiveModel::Naming.plural(associations.new))
Which doesn't work as `filter.taxonomies` is not a valid method

2016-12-15 09:25 UTC, dLobatog commented
Updated with tests @tbrisker , to reproduce I think just visiting the Filter page with an user with one Organization or Location will break it, as `klass.send(ActiveModel::Naming.plural(User.current.organizations))` becomes `klass.send(:taxonomies)`. Hopefully the test is clear enough. 

cc @ares thanks for taking a look too.

2016-12-15 12:44 UTC, tbrisker commented
This prevents the exception, however when going to edit a filter as a non-admin user the taxonomy selection fields are empty.

2016-12-19 20:29 UTC, dLobatog commented on app/services/association_authorizer.rb
> +      associations.authorized(permission, klass_name) if permission
This is what was causing the issue where non admin users wouldn't see their locs/orgs. @tbrisker notice `klass_name` is passed from the patch #3779 but it wasn't being used (only for creating the permission name)

2016-12-19 20:29 UTC, dLobatog commented on app/views/filters/_form.html.erb
> +        <% collection = User.current.locations.empty? ? Location : User.current.my_locations %>
switched to `my_locations` which includes truly all user locations including children

2016-12-19 20:30 UTC, dLobatog commented on app/views/filters/_form.html.erb
> +        <% collection = User.current.organizations.empty? ? Organization : User.current.my_organizations %>
switched to my_organizations too. this was another bug...

2016-12-20 07:48 UTC, dLobatog commented
Set to WoC as I broke something

2016-12-20 09:24 UTC, dLobatog commented
Tests back green again, and I am able to see my organizations as a non-admin user, can you check back @tbrisker ?

2016-12-20 11:24 UTC, tbrisker requested changes
Mostly works, just a minor comment about a certain use case.

2016-12-20 11:24 UTC, tbrisker commented on app/views/filters/_form.html.erb
> +        <% collection = User.current.locations.empty? ? Location : User.current.my_locations %>
This allows a non-admin user with no locations assigned to see all locations. This should just be `User.current.my_locations` always.

2016-12-20 11:24 UTC, tbrisker commented on app/views/filters/_form.html.erb
> +        <% collection = User.current.organizations.empty? ? Organization : User.current.my_organizations %>
ditto

2016-12-20 11:24 UTC, tbrisker commented on app/views/roles/_form.html.erb
>          <% collection = User.current.locations.empty? ? Location : Location.my_locations %>
same comment applied to this form.

2016-12-22 08:06 UTC, dLobatog commented
Moved everything to `User.current.my_xxxxx` , thanks for the catch @tbrisker

2017-01-03 11:54 UTC, dLobatog commented
@tbrisker anything else I should change here?

2017-01-03 13:45 UTC, tbrisker approved these changes

2017-01-03 13:47 UTC, merged

2017-01-03 13:47 UTC, tbrisker commented
Thanks @dLobatog !