Fixes #8016 - support sessions for api calls
theforeman/foreman pull request #4045
Opened 2016-11-24 12:24 UTC by tstrachota

- authenticated api calls save user to session and set flag api_authenticated_session
- sessions with such flag allow posting requests without CSRF token
- api sessions exipre the same way as UI sessions
- api sessions don't store any additional data to keep the requests stateless

This way the standard UI requests as well as API requests authenticated with session created from UI remain protected against CSRF. At the same time applications using API (such as hammer) can benefit from using session authentication and avoid the need of storing two tokens (CSRF and _session_id).

2016-11-25 14:55 UTC, domcleal requested changes
Thanks, that works nicely when retaining the session ID cookie. Could you please rebase to ensure the test suite is passing?

2016-11-25 16:12 UTC, tstrachota commented
Rebased

2016-11-29 11:55 UTC, domcleal commented
Sorry, please rebase again to ensure ee7d140 is included - the test suite isn't fully running currently.

2016-11-29 12:21 UTC, tstrachota commented
Rebased

2016-11-30 10:42 UTC, domcleal approved these changes

2016-11-30 10:43 UTC, merged

2016-11-30 10:43 UTC, domcleal commented
Merged, thank you for the nice addition @tstrachota.