Fixes #3551 - Show unavailable Puppet Classe in Host Group edit
theforeman/foreman pull request #4048
Opened 2016-11-24 15:12 UTC by bastilian

Puppet Classes can be assigned to a Host Group even if they are
not in the set environment. They will persist through out changes
of the environment, but were previously hidden from the UI.

Unavailable Puppet Classes are now shown in the UI as unavailable
and a warning is triggered to inform the user about them.

**Host Group edit form / Puppet Classes with changed environment:**
![screen shot 2016-11-24 at 16 08 21](https://cloud.githubusercontent.com/assets/7757/20603126/66e1e54a-b260-11e6-9618-122f1d9f6c45.png)

**Warning:**
![screen shot 2016-11-24 at 16 08 10](https://cloud.githubusercontent.com/assets/7757/20603125/66e18280-b260-11e6-8c15-d1239eb8e0d5.png)

2016-11-25 07:53 UTC, dLobatog commented
@theforeman-bot ok to test

2016-11-25 07:56 UTC, dLobatog commented
@domcleal @ohadlevy Could you add @bastilian to @theforeman org please?

2016-11-25 08:17 UTC, dLobatog requested changes
@bastilian Thank you, this works pretty well from what I've seen. 

Once you save the host group, when you edit it again, the Puppet classes are colored in red, but it doesn't tell you why. You only see the 'unavailable' warning message when you change the environment, after that it's hard to know.

Can you add an `alert(:class => 'alert-warning'` to display this information? (or any equivalent way to show the classes are indeed unavailable) The rest of the PR is pretty much ready!

2016-11-25 08:17 UTC, dLobatog commented on app/models/concerns/host_common.rb
> +  def individual_puppetclasses(with_environments: false, in_environment: true)
I'm not sure I understand why this method has arguments if it's only called once (in the view), where 'with_environments' is true and 'in_environment' is false. I'd suggest to either:

* remove the arguments completely (adds complexity to the method that I don't think we're using anywhere)
* make the arguments default to what we're using

2016-11-25 08:17 UTC, dLobatog commented on test/controllers/hostgroups_controller_test.rb
> +      assert_equal(1, (assigns(:hostgroup).puppetclasses.length))
Nitpick, you probably want to check `assert_include @puppetclass, assigns(:hostgroup).puppetclasses` to ensure it's the right class

2016-11-25 08:19 UTC, dLobatog commented on app/assets/javascripts/application.js
> +    notify('<span>' + __('Some Puppet Classes are unavailable in the selected environment') + '</span>', 'warning')
I think it's 'Puppet class' (lowercase class) - we're certainly not being very consistent about this around the app but a quick search revealed it's only 'Puppet Class' on a couple of titles, not texts

2016-11-25 08:25 UTC, bastilian commented on app/models/concerns/host_common.rb
> +  def individual_puppetclasses(with_environments: false, in_environment: true)
Ah, you are right! I overlooked that it is just used once in the whole app.

I'll rewrite it to not need arguments.

2016-11-25 08:27 UTC, bastilian commented on app/assets/javascripts/application.js
> +    notify('<span>' + __('Some Puppet Classes are unavailable in the selected environment') + '</span>', 'warning')
I've taken the tab title, that capitalises both, considering that is what the user need to look for when the alert pops up.

2016-11-25 08:31 UTC, bastilian commented on app/assets/javascripts/application.js
> +    notify('<span>' + __('Some Puppet Classes are unavailable in the selected environment') + '</span>', 'warning')
BUT. I do think that "Puppet class" would be the correct way to write it, as "Puppet" is a "brand" and "class" is just another word.

2016-11-27 08:41 UTC, ohadlevy commented
@bastilian why do you show the error as a toast notification? shouldn't it be within (or next) to the puppet class section on the form?
also, does red (in your image) means you can't remove it, or disabled? I was unsure what it means from looking at your screenshot. if its unavialavble, shouldn't it be disabled? /cc @rohoover

2016-11-28 15:16 UTC, Rohoover commented
@ohadlevy 
I interpreted the red text as being part of the form error. Perhaps I'm mistaken.

2016-11-30 11:30 UTC, bastilian commented
@ohadlevy  & @Rohoover yeah, it is not obvious why they are red, @dLobatog pointed that out as well.

I'm gonna add a note on the Puppet classes tab elaborating on why they are red and that they are going to be wiped if submitted.

2016-11-30 11:55 UTC, ohadlevy commented
can you explain it here as well? maybe @Rohoover could suggest an
alternative approach? thanks!

2016-11-30 13:41 UTC, bastilian commented
The case here is that the user has changed the environment of the host group. The environment that has been selected environment does not include the puppet classes, that have been previously configured for the host group with an environment that had these classes.

Marking these red may not be appropriate, now that I think about it, as the are actually not wiped, but are just "ineffective" in the set environment not including them. 

In case the environment changes to one that includes them they will be considered again.

Let me know if you have more questions to find a good way to communicate this in the UI, @Rohoover.

2016-12-05 16:14 UTC, Rohoover commented
@bastilian 

A few thoughts:

Placing an inline notification at the top (yellow) would help give the user more insight.
After you explanation - I agree, red may not be accurate. Perhaps grey them out?
Lastly, in your example no included classes were applicable. What remedies does the user have other than to switch environments?

2016-12-06 10:19 UTC, bastilian commented
@Rohoover Switching the environment is the only way to have them active again.

Another action the user could take is to remove the unavailable classes to avoid mistakenly activate them by updating the environment, later on. A link offering that in the message explaining the state would make sense I think.

2016-12-06 15:21 UTC, dLobatog commented on test/controllers/hostgroups_controller_test.rb
> +      assert_equal(1, (assigns(:hostgroup).puppetclasses.length))
fixed

2016-12-06 15:22 UTC, dLobatog commented on app/assets/stylesheets/puppetclasses.scss
> +  color: #cc0000
http://www.patternfly.org/styles/color-palette/#_ I believe you can use one of these

2016-12-06 15:23 UTC, dLobatog commented
Set to WoC @bastilian if you can find an way to show the 'resolution' (maybe just link to the primary tab and highlight the Environment field) with js is good - @Rohoover is that what you're looking for?

2016-12-06 15:24 UTC, dLobatog approved these changes

2016-12-06 15:38 UTC, Rohoover commented
@bastilian @dLobatog 

I think offering the user the feedback in the notification will go a long way. If it's possible to link to the tab within that notification then that could also be helpful.

2016-12-14 10:05 UTC, ohadlevy commented on app/assets/javascripts/application.js
> +  var unavailable_classes = $('#puppet_klasses #selected_classes .unavailable');
tbh: I think this needs to be rewritten in webpack, this way you can add tests to the function...

2016-12-14 10:06 UTC, ohadlevy commented on app/assets/stylesheets/puppetclasses.scss
> +  color: #d1d1d1;
is this a patternfly color? maybe add its name / reference to color pallet.

2016-12-14 10:10 UTC, ohadlevy commented on app/models/puppetclass.rb
> +           LEFT OUTER JOIN environments ON environment_classes.environment_id = environments.id')
why left outer join? wont you get duplicates this way? maybe I'm missing something

2016-12-14 10:22 UTC, dLobatog commented on app/assets/stylesheets/puppetclasses.scss
> +  color: #d1d1d1;
https://github.com/theforeman/foreman/pull/4048#discussion_r91099151 - should be a patternfly color

2016-12-14 13:27 UTC, Rohoover commented on app/assets/stylesheets/puppetclasses.scss
> +  color: #d1d1d1;
pf-black-300 =  #d1d1d1

2016-12-14 13:32 UTC, ohadlevy commented on app/assets/stylesheets/puppetclasses.scss
> +  color: #d1d1d1;
can't we simply access it via js/css directly? would make it both readable and if pf colors change we will have less of an headache :)

2016-12-19 10:52 UTC, bastilian commented on app/assets/javascripts/application.js
> +  var unavailable_classes = $('#puppet_klasses #selected_classes .unavailable');
Yes, I am also in favour of rewriting it under webpack, but wouldn't it be better to to have a component for the edit form in general first and then move over components like in this case for editing Puppet classes?

To have this tested now we can use an integration test, which can be removed (or not) once it is rewritten with tests under webpack.

2016-12-22 10:01 UTC, bastilian commented
@Rohoover I've changed this to have the warning now next to the environment select and is updated when it changes:

![screen shot 2016-12-22 at 10 53 52](https://cloud.githubusercontent.com/assets/7757/21421795/06c09cde-c835-11e6-9930-efa6a8acd283.png)

It didn't feel right to have a notification every time this state is detected, I think warning this way is much more effective.

In the Puppet Classes tab the unavailable ones are now only grey out (using the patternfly `$grey-lighter` color):

![screen shot 2016-12-22 at 10 20 34](https://cloud.githubusercontent.com/assets/7757/21420873/53c687a0-c830-11e6-8020-a13329a20ffd.png)

If we have more cases like this, where things are unavailable/inactive, it might be a good idea to have this in `colors.scss` (or `status-colors.scss`).

@ohadlevy you were right, the outer join was not the right thing to use here. The `individual_puppetclasses` method now uses Rails' includes, as it should have in the first place and the scope with join is removed.

2016-12-23 07:39 UTC, dLobatog requested changes
@bastilian This looks basically ready except for the JS function missing unit tests. I haven't tested it much yet, but please move the function to `webpack/`, write a couple of tests (for unavailable_classes.size greater than 0 and equal to 0) and ping me so we can get this merged soon.

Thanks!

2016-12-23 07:39 UTC, dLobatog commented on app/assets/javascripts/application.js
> +  var unavailable_classes = $('#puppet_klasses #selected_classes .unavailable');
I have to agree with @ohadlevy here, the function is relatively complicated so if we can get unit tests for them that's great. It doesn't have to be a React component, just moving the function there would make sense IMO so you can use Jest to test it. Like this one: https://github.com/theforeman/foreman/blob/develop/webpack/assets/javascripts/foreman_users.js

2016-12-23 09:29 UTC, bastilian commented
@dLobatog & @ohadlevy I was reluctant before, because I thought it would be beyond the scope of the PR, if moved to webpack and written as a component. I'm gonna move the function and from now on only add JS under `webpack`. :)

2016-12-23 17:22 UTC, Rohoover commented
@bastilian My only concern is that the two pieces of messaging below it for Puppet Master and Puppet CA are persistent. The warning for environment may be less identifiable because of the persistent messaging. A possible solution would be to place the persistent messaging in inline help:
http://www.patternfly.org/pattern-library/forms-and-controls/field-level-help/#_

As a note: I'm gong to be addressing with the patternfly team if that icon is correct... there are currently two info icons, I'd like to consolidate them.

2016-12-30 11:23 UTC, bastilian commented
@Rohoover To be consistent with other forms, where it is next to the label as an (i)-icon tooltip, it does make sense to use the field help for Puppet Master and Puppet CA.

Let me know once you heard back from the patternfly team.

2017-01-02 10:36 UTC, dLobatog requested changes
@bastilian I've been looking at it and the functionality is good, it detects the envs just fine (after fixing the typo in application.js). My only comments are:

* The color is barely distinguishable from white, it might be my background, but I think using some color from the patternfly pallette would make it more visible, see the comment inline.
* The warning isn't really noticeable on the "Host" tab, plus as @Rohoover it's confusing to have both persistent and ephemeral information there. Personally I didn't even notice the information when I was testing it, and it wasn't until I came back to the PR that I saw it. What I meant by adding `pf-warning` is that you can put it in the "Puppet classes" tab, on top of everything as @ohadlevy mentioned. That way it's immediately obvious why these are grey, while the current way forces you to go back. 
* It doesn't seem to work in the Host form, which is the same.
* The warning doesn't look good when Katello is installed, see the screenshot.

Long comment, but the fixes needed are quite minimal, thanks @bastilian

2017-01-02 10:36 UTC, dLobatog commented on app/assets/javascripts/application.js
> +      tfm.hostgroups.check_for_unavailable_puppetclasses();
`checkForUnavailablePuppetclasses` typo

2017-01-02 10:36 UTC, dLobatog commented on app/assets/stylesheets/puppetclasses.scss
> +  color: $gray-lighter;
Use something from http://www.patternfly.org/styles/color-palette/#_ , the current one is barely visible

`pf-black-400 #bbbbbb` looks nice IMO for disabled elements

2017-01-02 10:37 UTC, dLobatog commented
The warning with Katello installed:
![screenshot from 2017-01-02 11-29-26](https://cloud.githubusercontent.com/assets/598891/21587744/d9345a68-d0df-11e6-8596-cb4d77bb93c2.png)

2017-01-02 12:25 UTC, bastilian commented
@dLobatog I've addressed the minor changes and move the warning to the Puppet Classes tab now:

![screen shot 2017-01-02 at 13 11 05](https://cloud.githubusercontent.com/assets/7757/21589100/9c3459c4-d0ee-11e6-8813-0653588f3cc2.png)

One thing that would be good though is to somehow let the user know that "something happened" in the Puppet Classes tab when the environment was changed or do you think it is enough for them to see it only in the tab?

2017-01-03 16:05 UTC, Rohoover commented
@bastilian 

The correct icon should be pficon_info, not the blue info icon. 

Also - I think currently the tab turns red when there is an error, not sure if the same holds true for a warning. That said, being that the content has changed in the tab, it should be made known to the user. Though this is not currently defined, it may be good to have something more or other than just a color change - as I have talked to a user who is color-blind, and color only indicators were useless for him.

2017-01-04 07:05 UTC, bastilian commented
@Rohoover How about adding a warning sign to the tab, instead of it turning red? Like this:

![screen shot 2017-01-04 at 08 03 32](https://cloud.githubusercontent.com/assets/7757/21634045/7fb39730-d254-11e6-8b44-1230af6679ae.png)

2017-01-04 12:33 UTC, Rohoover commented
@bastilian +1

2017-01-04 19:33 UTC, bastilian commented
@Rohoover It's now implemented and the screens look as follows when an environment is selected with classes unavailable:

![screen shot 2017-01-04 at 19 48 36](https://cloud.githubusercontent.com/assets/7757/21656119/09a5f5b0-d2bd-11e6-9b07-2b01e6df8b4e.png)
![screen shot 2017-01-04 at 19 48 43](https://cloud.githubusercontent.com/assets/7757/21656120/09aa7338-d2bd-11e6-8b03-bc089f67be5a.png)

2017-01-11 12:13 UTC, dLobatog approved these changes

2017-01-11 12:18 UTC, dLobatog commented
@bastilian Awesome - if tests pass, I'll merge (and rebase first, as I solved a small conflict to let tests run).

Great job at figuring out how to show warnings like this with @Rohoover , to be fair we basically relied on making the fields red any time anything wrong happens. As you said that's not going to work for color-blind users. Also, a warning when changing something in the form doesn't have to look the same as an error when you submit it. 

Is there any recommendation on the Patternfly guidelines for forms, or can we make this (warning icon on the tab) a Patternfly recommendation?

2017-01-11 12:38 UTC, dLobatog requested changes
@bastilian Found a problem when switching back to the original environment (where the classes are available), it added another warning icon. Every time I change environments now it adds a new icon basically. I'll try to figure out what's going on

2017-01-11 12:38 UTC, dLobatog commented on webpack/assets/javascripts/foreman_hostgroups.js
> +    puppetKlassesTab.find('#puppetclasses_unavaliable_warning').remove();
typo (here and above), `unavailable`

2017-01-11 12:38 UTC, dLobatog commented on webpack/assets/javascripts/foreman_hostgroups.js
> +  if (unavailableClasses.size() > 0) {
Seems like `unavailableClasses.size() > 0` is true even after you change back from the environment that has the classes, so every time I change environments, a new pficon warning is added

2017-01-11 12:54 UTC, dLobatog requested changes
See https://github.com/theforeman/foreman/pull/4048/files#r95572403 for the change needed for this to work again

2017-01-11 12:54 UTC, dLobatog commented on app/views/puppetclasses/_selectedClasses.html.erb
> +<%= content_tag_for :li, klass, :selected, :class => [cycle('even', 'odd'), ('unavailable' unless klass.environments.include?(@environment))] do %>
Found the issue. `@environment` is only available on the *first* load of the page. On subsequent loads, it doesn't exist as the host controller didn't set it.

I fixed it locally by adding two lines to `hostgroup_or_environment_selected`, so it's the following:

```ruby

  def hostgroup_or_environment_selected
    Taxonomy.as_taxonomy @organization, @location do
      if params['host']['environment_id'].present? || params['host']['hostgroup_id'].present?
        @environment = Environment.find(params['host']['environment_id'])
        @hostgroup = Hostgroup.find(params['host']['hostgroup_id'])
        render :partial => 'puppetclasses/class_selection', :locals => {:obj => (refresh_host)}
      else
        logger.info "environment_id or hostgroup_id is required to render puppetclasses"
      end
    end
  end
```

I think that's all that's required for it to work.

2017-01-11 15:25 UTC, dLobatog approved these changes

2017-01-11 16:29 UTC, merged

2017-01-11 16:29 UTC, dLobatog commented
Thanks @bastilian & @Rohoover !