Fixes #17482 - make strings translatable
theforeman/foreman pull request #4054
Opened 2016-11-25 12:37 UTC by ares

I can't combine the string into one as asked in the issue because the environments part is generated dynamically, the result can be following

```
Update environment one (5 classes), environment two (3 classes)
```

I added it as translation parameter at least in case order needs to be changed, hopefully that helps. I also updated button labels and plural form.

2016-11-25 14:38 UTC, domcleal requested changes

2016-11-25 14:38 UTC, domcleal commented on app/services/actions/foreman/puppet_class/import.rb
>            end.join(', ')
use `.to_sentence`

2016-11-25 14:38 UTC, domcleal commented on app/services/actions/foreman/puppet_class/import.rb
> +          humanized_output << _('Add %s') % format_env_and_classes_input(input[:changed][:new]) if input[:changed][:new].present?
The verb should still be part of the string _inside_ the method as it's part of the same sentence - it isn't a separate sentence or fragment, i.e. inside `format_env_and_classes_input`:

    _("Add environment %s")

and append versions without the verb:

    _("environment %s")

unless you rewrite it entirely into separate fragments or sentences, which it isn't right now.

2017-02-23 18:59 UTC, ares commented
Closing, the PR adding these files was reverted.

2017-02-23 18:59 UTC, closed without merging