Fixes #17611 - Localize smart variables strings
theforeman/foreman pull request #4097
Opened 2016-12-08 14:14 UTC by dLobatog

This commit rename removes the prefixes of LookupKey from model
attributes so that we can reuse the same strings across smart class
params and smart variables. In addition to that it uses the label
attribute to ensure those are used

2016-12-08 14:17 UTC, domcleal requested changes

2016-12-08 14:17 UTC, domcleal commented on app/views/lookup_keys/_fields.html.erb
> +    <%= text_f f, :key, :disabled => is_param, :size => "col-md-8", :label => _('Key') %>
No need to extract the strings again here, or even translate them, the form helpers do it automatically. They're likely to get out of sync.

2016-12-08 14:17 UTC, domcleal commented on locale/model_attributes.rb
> +_('Avoid duplicates')
These should be `Table name|Colum name` per the comment, i.e. `LookupKey|Avoid duplicates` or they won't match the automatic string lookups.

2016-12-08 14:30 UTC, dLobatog commented
I've updated it according to your comments @domcleal  - but I'm probably missing something. If I do *not* use `:label` on the view, I don't see any translations. That's because PuppetclassLookupKey and VariableLookupKey are used still on the .po files. Should I change those too?

2016-12-08 14:31 UTC, domcleal commented
If you want to test it you could change them temporarily, but they shouldn't be changed directly - they would be updated when the POT is updated and synced from Transifex.

You appear to have squashed your changes into an unrelated commit.

2016-12-08 14:38 UTC, dLobatog commented
Fair enough - thanks @domcleal !

2016-12-12 09:20 UTC, domcleal approved these changes

2016-12-12 09:20 UTC, merged

2016-12-12 09:20 UTC, domcleal commented
Merged, thanks @dLobatog.