Fixes #17632 - Reports widget will not fail on ambiguous filter
theforeman/foreman pull request #4102
Opened 2016-12-12 14:00 UTC by tbrisker

A user with a filter on a joined table that has a host_id column (such
as nics for example) will cause the report widget to break due to an
ambiguous column name. This fix makes sure the columns use the table
name and are correctly quoted.

2016-12-13 14:55 UTC, domcleal requested changes

2016-12-13 14:55 UTC, domcleal commented on test/unit/dashboard_test.rb
> +      ConfigReport.stubs(:authorized).with(:view_config_reports).returns(ConfigReport.joins(:host => :interfaces))
Nitpick, please use `expects` instead of `stubs` to prevent the test incorrectly succeeding if the implementation changes for any reason.

2016-12-13 15:19 UTC, tbrisker commented on test/unit/dashboard_test.rb
> +      ConfigReport.stubs(:authorized).with(:view_config_reports).returns(ConfigReport.joins(:host => :interfaces))
fixed.

2016-12-14 08:54 UTC, domcleal approved these changes

2016-12-14 08:54 UTC, merged

2016-12-14 08:54 UTC, domcleal commented
Merged, thanks @tbrisker.