Fixes #6952 - Set hostgroup after provisioning from pxe
theforeman/foreman pull request #4112
Opened 2016-12-15 00:04 UTC by amirfefer

After hostgroup provisioning, when the machine has registered
with foreman, it should be in the same hostgroup.
to achieve this behavier, the [referenced](https://github.com/theforeman/community-templates/pull/327) snippet should be added
to hostgroup provisioning template.

2016-12-22 19:10 UTC, dLobatog requested changes
It's nearly done. Just call `set_hostgroup_defaults` and please add something to theforeman.org documenting what this does, as `foreman_hostgroup` isn't provided by Ansible, Puppet etc... 

Thanks @amirfefer

2016-12-22 19:10 UTC, dLobatog commented on app/models/host/base.rb
> +      hostgroup_title = facts.delete(:foreman_hostgroup)
This fact isn't standard, from what I read on the issue description it's a custom fact. I think the functionality is neat, but please add docs to this after it's merged

2016-12-22 19:10 UTC, dLobatog commented on app/models/host/base.rb
> +      self.hostgroup = Hostgroup.find_by_title(title)
Call `set_hostgroup_defaults` after, so that the attributes from the host group are applied

2017-01-06 01:21 UTC, amirfefer commented
Thanks for your review @dLobatog, I've added `set_hostgroup_defaults` call, and a related test.

2017-01-11 08:48 UTC, dLobatog approved these changes

2017-01-11 11:10 UTC, dLobatog commented
@amirfefer I'll fix the HoundCI qualms on merge, remember to write some docs for this on https://github.com/theforeman/theforeman.org/ please. Thanks!

2017-01-11 11:43 UTC, dLobatog commented
Merged as 9883149acbb88bd59695b92207933c074a72c427 , thanks @amirfefer !

2017-01-11 11:43 UTC, closed without merging

2017-01-11 11:47 UTC, domcleal commented
9883149 looks significantly different to the reviewed commit 604a651, adding `hostgroup` to `attributes_to_import_from_facts` and removing the `set_hostgroup` method + calls. Why isn't it the same?