Fixes #17841 - Expose compute resource SSH keys via API
theforeman/foreman pull request #4130
Opened 2016-12-25 13:05 UTC by shlomizadok

2016-12-25 13:11 UTC, ohadlevy commented on app/views/api/v2/key_pairs/main.json.rabl
> +attributes :name, :active, :used_elsewhere
maybe in_used vs used_elsewhere?
is there a way via the API / UI to figure out where its being used?

2016-12-25 13:12 UTC, ohadlevy commented on app/controllers/api/v2/key_pairs_controller.rb
> +        return not_found unless key_to_delete
shouldnt this be recreate vs delete? I mean we should allow to delete unused keys, but the current active key should not be deleted only recreated?

2016-12-25 13:18 UTC, shlomizadok commented on app/views/api/v2/key_pairs/main.json.rabl
> +attributes :name, :active, :used_elsewhere
I'll reword. Currently no way to know where it is used

2016-12-25 13:21 UTC, shlomizadok commented on app/controllers/api/v2/key_pairs_controller.rb
> +        return not_found unless key_to_delete
Yes. This should be checked at the model. will refactor.

2016-12-29 08:55 UTC, shlomizadok commented
[test]

2017-01-05 10:05 UTC, tbrisker commented
[test foreman]
[test katello]
[test upgrade]

2017-01-25 09:48 UTC, dLobatog requested changes
@shlomizadok Overall it works nicely , found a few things in the controller that I think it could reuse from the API ApplicationController - mind to check it out. Thanks!

2017-01-25 09:48 UTC, dLobatog commented on app/controllers/api/v2/key_pairs_controller.rb
> +      api :GET, '/compute_resources/:compute_resource_id/key_pairs', N_("List all SSH key for compute resource")
typo, 'SSH key pairs` (can be fixed on merge)

2017-01-25 09:48 UTC, dLobatog commented on app/controllers/api/v2/key_pairs_controller.rb
> +      def find_resource
No need to override this method?

2017-01-25 09:48 UTC, dLobatog commented on app/controllers/api/v2/key_pairs_controller.rb
> +      def get_resource
Dead code?

2017-01-25 09:48 UTC, dLobatog commented on app/controllers/api/v2/key_pairs_controller.rb
> +      def find_compute_resource
This looks like it should rely on `find_required_nested_object`, then check whether @compute_resource.capabilities include keypair?

2017-01-25 09:48 UTC, dLobatog commented on app/controllers/api/v2/key_pairs_controller.rb
> +        return not_found unless key_to_delete
I see the refactor allows to destroy "unused keys" defining "unused" as "not used by Foreman". I'd say that looks a bit dangerous.

2017-02-02 10:26 UTC, shlomizadok commented on app/controllers/api/v2/key_pairs_controller.rb
> +      def find_compute_resource
It fails when relying on `find_required_nested_object`

2017-02-02 11:42 UTC, shlomizadok commented on app/controllers/api/v2/key_pairs_controller.rb
> +      def get_resource
nope

2017-03-28 09:13 UTC, shlomizadok commented
@dLobatog - how shall I proceed here? :)

2017-06-19 18:44 UTC, ohadlevy commented
@dLobatog recommendations on how to continue?

2018-06-27 13:13 UTC, closed without merging