Fixes #17939 - Refactored classification to reduce complexity
theforeman/foreman pull request #4163
Opened 2017-01-08 21:06 UTC by ShimShtein

1. Created a query object class to encapsulate the complex query for finding values that are relevant for a key
2. Made this query accessible via scope on `LookupKey` class
3. Encapsulated results rendering into a results class that behaves a bit like hash
4. Encapsulated matches generation logic into `MatchesGenerator` class.

For transition purposes, I have left the old classification classes but stripped down the logic and made them only adapters to the new system.

2017-01-10 14:12 UTC, orrabin requested changes

2017-01-10 14:12 UTC, orrabin commented on app/services/classification/base.rb
> +      raise NotImplementedError
why return keys in `class_parameters` and have this and not just implement `class_parameters`?

2017-01-10 14:12 UTC, orrabin commented on app/services/classification/matches_generator.rb
> +    def is_method?(element)
Why extract this? it was easier to understand when it was part of the line. It's also not a method, it's associations to the host.

2017-01-10 14:12 UTC, orrabin commented on app/services/classification/class_param.rb
> +      key_hash = hashed_class_keys(keys)
Why send the keys when you can call it from `hashed_class_keys`?

2017-01-10 14:12 UTC, orrabin commented on app/services/classification/matches_generator.rb
> +        hostgroup_matches.each do |hostgroup_match|
This whole part can move into `add_hostgroup_matches?` if you change the name to `add_hostgroup_matches`.

2017-01-10 14:12 UTC, orrabin commented on app/services/classification/matches_generator.rb
> +    def is_parameter?(element)
I don't think it's worth extracting.

2017-01-10 14:12 UTC, orrabin commented on app/services/classification/matches_generator.rb
> +        match = generate_match(rule)
:+1: for breaking this up

2017-01-10 14:12 UTC, orrabin commented on app/services/classification/matches_generator.rb
> +      if (fn = fact_name(element))
Instead of extracting one liners into 2 methods why not extract this if into one method?

2017-01-10 14:12 UTC, orrabin commented on app/services/classification/class_param.rb
> +        klasses[klass.name] = smart_class_params_for(klass, key_hash, values)
The name is confusing, this is the way the hash will look and not smart class parameters.

2017-01-10 14:12 UTC, orrabin commented on app/services/classification/classification_result.rb
> +      raw[key.id][key.to_s] if raw[key.id]
Why extract this?

2017-01-10 14:12 UTC, orrabin commented on app/services/classification/values_hash_query.rb
> +      def values_hash(host, keys, options = {})
:+1: for breaking this up, it was huge and unreadable.

2017-01-10 14:12 UTC, orrabin commented on app/services/classification/values_hash_query.rb
> +        value = nil
Since this is now a method why not return instead of keeping the value and returning it at the end?

2017-01-10 14:12 UTC, orrabin commented on test/unit/classification_test.rb
> +    host.expects(:comment).returns('override')
Why is this on the host?

2017-01-10 14:12 UTC, orrabin commented on test/unit/classification_test.rb
> +    classparam = Classification::ClassParam.new(:host => host)
Isn't this what `get_classparam` does? (with the env and puppetclass)

2017-01-10 14:12 UTC, orrabin commented on test/unit/classification_test.rb
> +    classparam = Classification::ClassificationResult.new(host, {})
looks like the host should be the second parameter

2018-04-01 20:19 UTC, mmoll commented
what's the status here? :)

2018-10-03 01:23 UTC, closed without merging

2018-10-03 17:44 UTC, ShimShtein commented
It's good that this commit is closed. It's obsolete, everything from it is already in core's code base!