Fixes #18040 - URL escape PuppetCA CN on proxy view
theforeman/foreman pull request #4185
Opened 2017-01-12 10:03 UTC by dLobatog

If the CN contains characters that cannot be displayed in an URL, like
'mcollective/OL=mcollective', the puppetca list will not be able to
render.

The reason is that Rails cannot generate an URL for such CNs, so we need
to convert it into URL-friendly style.

2017-01-30 13:48 UTC, domcleal requested changes
Could you add a controller test please, covering the index action?

2017-01-30 16:41 UTC, dLobatog commented
@domcleal Updated with a test now for the index action. If you remove the `url_encode`, you'll see the action will throw 'ActionView::Template::Error: No route matches {:action=>"update", :controller=>"puppetca", :id=>"mcollective/OL=mcollective", :smart_proxy_id=>"182953976-Puppetmaster Proxy"} missing required keys: [:id]' which is the current behavior without the patch.

2017-01-31 08:09 UTC, domcleal approved these changes

2017-01-31 08:10 UTC, merged

2017-01-31 08:10 UTC, domcleal commented
Merged, thanks @dLobatog.