Fixes #18260 - Display proper organizations count on table
theforeman/foreman pull request #4234
Opened 2017-01-26 15:33 UTC by dLobatog

If the user is scoped to taxonomy "A", "Host.count" will only return
hosts in that taxonomy. That is correct. However there is a usecase
where we want to display the hosts count regardless of the current
taxonomy.

The table for locations and organizations was showing the "Host.count"
scoped to the current taxonomy, so it would show 0 everywhere but in the
current taxonomy.

The fix is to make the helper aware of this issue, and show the unscoped
Host.count when displaying the organizations/locations table

"Spot the difference"

![screenshot from 2017-01-26 16-23-36](https://cloud.githubusercontent.com/assets/598891/22337413/2d8ad444-e3e5-11e6-8443-fe03a6894e08.png)
![screenshot from 2017-01-26 16-24-04](https://cloud.githubusercontent.com/assets/598891/22337415/2dbf0908-e3e5-11e6-9163-f32d0ee6a771.png)

2017-01-26 15:53 UTC, tbrisker requested changes
See inline

2017-01-26 15:53 UTC, tbrisker commented on app/helpers/application_helper.rb
> +      hosts_scope = Host::Managed.reorder('').unscoped
This would mean the user may know about hosts he is not authorized to see.

2017-01-26 16:25 UTC, dLobatog commented on app/helpers/application_helper.rb
> +      hosts_scope = Host::Managed.reorder('').unscoped
No? This would only display the count, once you click on the number to be directed to the search, it will not display you anything you cannot see.

2017-01-26 16:26 UTC, dLobatog commented
@tbrisker Replied inline, I don't think this opens up anything for users - just the host count. I'm OK with hiding the number if that's preferred, but showing the count doesn't mean the user will see any of these hosts.

2017-01-29 09:25 UTC, tbrisker requested changes

2017-01-29 09:25 UTC, tbrisker commented on app/helpers/application_helper.rb
> +      hosts_scope = Host::Managed.reorder('').unscoped
Oh, actually I was wrong, there is another `.authorized` below. However there is some repetition here, how about 
```ruby
hosts_scope = Host::Managed.reorder('')
hosts_scope = hosts_scope.unscoped if ['organization', 'location'].include? resource_name
@hosts_count ||= hosts_scope.authorized.group("#{resource_name}_id").count
```

2017-01-30 09:41 UTC, dLobatog commented
@tbrisker Updated according to your changes 😄

2017-01-30 14:59 UTC, tbrisker approved these changes

2017-01-30 15:02 UTC, merged