fixes #13618 - cache expensive vmware api calls
theforeman/foreman pull request #4238
Opened 2017-01-27 14:20 UTC by timogoebel

In my dev environment the `compute_resource_selected` call got approx. 10 times faster. I'm really thrilled!

The caching can be enabled for every compute resource. The code is reusable to plugins or oder compute resources can reuse the caching mechanism.
Cache invalidation was not straight forward to implement because I wanted to support memcached so I had to use a "scope" when creating the cache keys. The scope is changed when the cache is invalidated.

Some "benchmarks":

Before:
Completed 200 OK in 16121ms (Views: 15963.0ms | ActiveRecord: 6.4ms)

After:
Completed 200 OK in 1710ms (Views: 1583.8ms | ActiveRecord: 5.1ms)

2017-01-29 09:05 UTC, tbrisker requested changes
Looks very good in general, a few comments inline about the code. Couldn't test as I don't have a vmware resource.

2017-01-29 09:05 UTC, tbrisker commented on app/services/compute_resource_cache.rb
> +    self.cache_duration = opts.fetch(:cache_duration, 180.minutes)
You can use a kwarg here

2017-01-29 09:05 UTC, tbrisker commented on app/controllers/api/v2/compute_resources_controller.rb
> +            :edit
I think it makes sense to allow viewers to also invalidate the cache (for example if they notice the data seems outdated), this doesn't actually do anything to the compute resource other then reload the data.

2017-01-29 09:05 UTC, tbrisker commented on app/controllers/compute_resources_controller.rb
> +      when 'associate', 'invalidate_cache'
ditto

2017-01-29 09:05 UTC, tbrisker commented on app/models/concerns/compute_resource_caching.rb
> +    @cache || ComputeResourceCache.new(self)
I think this needs to be `||=` for the new cache to be saved

2017-01-29 09:05 UTC, tbrisker commented on app/views/compute_resources/form/_vmware.html.erb
> +<%= checkbox_f f, :caching_enabled, :label => _("Enable caching"),
This parameter should also be added to the api

2017-01-29 09:05 UTC, tbrisker commented on db/migrate/20170127094357_add_caching_enabled_to_compute_resource.rb
> +    add_column :compute_resources, :caching_enabled, :boolean
This should have a default false I believe

2017-01-29 09:32 UTC, ohadlevy commented on app/services/compute_resource_cache.rb
> +    self.cache_duration = opts.fetch(:cache_duration, 180.minutes)
would it make sense to include some sort of a hourly task that keeps refreshing the cache offline?

2017-01-29 09:35 UTC, ohadlevy commented on app/views/compute_resources/show.html.erb
> +(display_link_if_authorized(_('Clear Cache'), hash_for_invalidate_cache_compute_resource_path(@compute_resource).merge(:auth_object => @compute_resource), :method => :put, :class => "btn btn-default"
nitpick: I would call it reload vs clear cache.

2017-01-29 09:37 UTC, ohadlevy commented on app/views/compute_resources/show/_vmware.html.erb
> +  <td><%= @compute_resource.caching_enabled ? _("Enabled") : _("Disabled") %></td>
consider using an icon ? from http://www.patternfly.org/styles/icons/#_ maybe  pficon-ok and  pficon-warning-triangle-o?

2017-01-29 09:37 UTC, ohadlevy commented on config/routes.rb
> +          put 'invalidate_cache'
nitpick: i would prefer reload vs invalidate (sounds scary as we all know cache invalidation is a hard problem ;))

2017-01-29 09:38 UTC, ohadlevy commented on db/migrate/20170127094357_add_caching_enabled_to_compute_resource.rb
> +    add_column :compute_resources, :caching_enabled, :boolean
do you see a need to default to false? I would rather opt in by default, no one wants the slower option unless they have a problem?

2017-01-29 09:39 UTC, ohadlevy commented
I would like to see a refresh / reload button on the host edit page, i think this is where you would really need  up to date / latest info as you dont have the option (dc, cluster etc).

2017-01-29 17:04 UTC, timogoebel commented on app/services/compute_resource_cache.rb
> +    self.cache_duration = opts.fetch(:cache_duration, 180.minutes)
Yes, I do want to add a hourly rake task for this that can be called by cron. I'd prefer to do this in a separate PR, though.

2017-01-29 17:08 UTC, timogoebel commented on app/views/compute_resources/show.html.erb
> +(display_link_if_authorized(_('Clear Cache'), hash_for_invalidate_cache_compute_resource_path(@compute_resource).merge(:auth_object => @compute_resource), :method => :put, :class => "btn btn-default"
How about "refresh cache"?

2017-01-29 17:11 UTC, timogoebel commented on app/views/compute_resources/show/_vmware.html.erb
> +  <td><%= @compute_resource.caching_enabled ? _("Enabled") : _("Disabled") %></td>
I actually do prefer the text vs. the icons to be consistent in the UI. We can change this to icons in a separate PR. ´pficon-warning-triangle-o´ is too much warning. If a user disables the caching, it won't break anything.

2017-01-29 17:12 UTC, timogoebel commented
> I would like to see a refresh / reload button on the host edit page, i think this is where you would really need up to date / latest info as you dont have the option (dc, cluster etc).

@ohadlevy : Would it be ok for you to add this in a separate PR? I think, this will make coding and reviewing easier.

2017-01-30 12:05 UTC, tbrisker reviewed
A couple more comments inline. As for the naming of the action, "reload" seems to be a bit misleading, as it isn't actually reloaded, rather "cleared" or "flushed" IIUC.

2017-01-30 12:05 UTC, tbrisker commented on app/services/compute_resource_cache.rb
> +  def initialize(compute_resource:, cache_duration: nil)
I'm afraid required kwargs is supported only in ruby 2.1, so we can't use that yet. I'd suggest making the first parameter a regular argument and just the cache duration a kwarg. Then you can set the default to 180.minutes in the kwarg rather then below, like so:
```ruby
def initialize(compute_resource, cache_duration: 180.minutes)
```

2017-01-30 12:05 UTC, tbrisker commented on db/migrate/20170127094357_add_caching_enabled_to_compute_resource.rb
> +    add_column :compute_resources, :caching_enabled, :boolean, default: true
Won't this make compute resources that don't support caching appear to have caching enabled?

2017-01-30 12:23 UTC, timogoebel commented on db/migrate/20170127094357_add_caching_enabled_to_compute_resource.rb
> +    add_column :compute_resources, :caching_enabled, :boolean, default: true
@tbrisker : Yes, it will. But it's not shown in the UI or API. So it figured, it doesn't really matter.   Do you see that differently?

2017-01-30 13:04 UTC, tbrisker commented on db/migrate/20170127094357_add_caching_enabled_to_compute_resource.rb
> +    add_column :compute_resources, :caching_enabled, :boolean, default: true
ok, makes sense.

2017-01-30 13:05 UTC, tbrisker commented on app/services/compute_resource_cache.rb
> +    self.cache_duration = cache_duration || 180.minutes
Instead of defaulting the kwarg to nil then defaulting here to 180.minutes, you can do that in the kwarg itself

2017-01-30 13:07 UTC, timogoebel commented
@tbrisker , @ohadlevy : Addressed all of your comments. Thanks a lot for these.

> As for the naming of the action, "reload" seems to be a bit misleading, as it isn't actually reloaded, rather "cleared" or "flushed" IIUC.

@tbrisker : Would `refresh cache` be fine for your? I had `clear cache` before, but @ohadlevy suggested to use something different.

I currently see these follow up tasks:

- [ ] Add a rake task to refresh the cache.
- [ ] Add a cache refresh button to the select boxed in the host form that flushes the cache and reloads the data.

2017-01-30 14:06 UTC, tbrisker commented
@timogoebel I guess refresh is better, @ohadlevy what do you think? Still one minor comment on the kwargs, other than that LGTM but I would like someone with access to VMWare to test it as well before merging.

2017-01-30 14:10 UTC, timogoebel commented
@shlomizadok : Would you mind testing this for me? I think a VM show and create should suffice.

2017-01-30 15:18 UTC, timogoebel commented
Caching is now disabled if the compute resource has not been saved yet, fixed the kwarg default and removed caching from `dc` method as method is quite fast.

2017-01-30 16:27 UTC, timogoebel commented
Rebased and renamed `reload_cache` to `refresh_cache`.

2017-01-31 08:04 UTC, timogoebel commented
Fixed an issue with caching of `dc.clusters`.

@TheKangaroo: Would you mind testing this PR and let us know if you see any issues? Thanks.

2017-01-31 08:35 UTC, tbrisker commented on app/models/compute_resources/foreman/model/vmware.rb
> +          name_sort(dc.datastores.get(opts[:storage_domain]))
not directly required, but this could benefit from a kwarg for storage domain

2017-01-31 08:39 UTC, tbrisker approved these changes

2017-01-31 08:40 UTC, tbrisker commented
Looks good to me pending testing, test failure is unrelated.

2017-01-31 08:45 UTC, TheKangaroo commented
Hi @tbrisker, I tested it in our environment.
I couldn't find any issues and the runtime improvements in creating hosts is huge :)
I really like your PR @timogoebel

2017-01-31 08:46 UTC, shlomizadok commented
@tbrisker - testing this now. give me 2 minutes to ack :)

2017-01-31 09:01 UTC, shlomizadok commented
ACK :+1:

2017-01-31 09:04 UTC, merged

2017-01-31 09:05 UTC, tbrisker commented
Thanks @timogoebel !

2017-01-31 09:27 UTC, timogoebel commented
Created two follow-up tickets:

Cache-Warming rake task:
http://projects.theforeman.org/issues/18314

Refresh from host page:
http://projects.theforeman.org/issues/18315