Fixes #18289 - fix IP based proxy authentication
theforeman/foreman pull request #4239
Opened 2017-01-27 19:16 UTC by ares

2017-01-30 12:36 UTC, dLobatog commented
@ares Thanks - would it be OK to check `request.env['REMOTE_ADDR']` against the list of possible proxy addresses `(Regexp.new(Setting[:remote_addr])` like we do in app/controllers/unattended_controller.rb ?

2017-02-01 13:59 UTC, ares commented
I'm not sure I understand the question. Which part exactly you have in mind? If you mean the initializer (which would probably make sense) then I'm not sure how to reliably parse the regexp to specific IP addresses that would be trusted proxies.

2017-02-23 19:02 UTC, ares commented
ping

2017-12-28 14:54 UTC, dLobatog requested changes
@ares Looks good, what I meant to check is just that in the concern, when we use a remote IP, like (`request.remote_ip`) as far as I understand, the regular IP (`request.ip`) should match `Setting[:remote_addr]`

2017-12-28 14:54 UTC, dLobatog commented on config/initializers/trusted_proxies.rb
> +Foreman::Application.config.action_dispatch.trusted_proxies = %w(::1 127.0.0.1). map { |proxy| IPAddr.new(proxy) }
Looks like the fix was merged already?

2018-05-25 13:40 UTC, xprazak2 commented
What is the status here?

2018-05-28 14:28 UTC, ares commented
closing as I know longer need the fix, though I think it's still valid issue

2018-05-28 14:28 UTC, closed without merging