Update README screenshots and links
theforeman/foreman pull request #4258
Opened 2017-02-07 15:38 UTC by dLobatog

Some of the README links were pointing to old versions of our
documentation. Also the pictures are from Foreman 1.8 (I think), the UI
does not look similar at all anymore.

2017-02-07 17:34 UTC, timogoebel requested changes
@dLobatog : Thanks for taking the time to update this. Some small comments inline.

2017-02-07 17:34 UTC, timogoebel commented on README.md
> +An up-to-date plugin list is kept in [here](http://theforeman.org/plugins/)
Can we avoid naming the link "here". How about "The [plugins page] lists all available plugins and has more information."

2017-02-07 17:34 UTC, timogoebel commented on README.md
> +We document our API using [apipie](https://github.com/Apipie/apipie-rails).The [API chapter](http://theforeman.org/manuals/latest/index.html#5.1API) has more information about accessing the API and t
https?

2017-02-07 17:34 UTC, timogoebel commented on README.md
> +Plugins are tools to extend and modify the functionality of Foreman. They are implemented as Rails engines that are packaged as gems and thus easily installed into Foreman. Read the [plugins page](ht
https?

2017-02-07 17:34 UTC, timogoebel commented on README.md
> +* We have a [development handbook](http://theforeman.org/handbook.html) to help developers understand how Foreman developers code.
https?

2017-02-07 17:34 UTC, timogoebel commented on README.md
>  Generally, follow the [Foreman guidelines](http://theforeman.org/contribute.html). For code-related contributions, fork this project and send a pull request with all changes. Some things to keep in m
https?

2017-02-07 17:34 UTC, timogoebel commented on README.md
>  * [Follow the rules](http://theforeman.org/contribute.html#SubmitPatches) about commit message style and create a Redmine issue. Doing this right will help reviewers to get your contribution merged f
https?

2017-02-08 11:06 UTC, dLobatog commented
@timogoebel Updated!

2017-02-08 11:14 UTC, timogoebel commented
@dLobatog : Thanks, this still needs a Redmine ticket, though. ;-)

2017-02-08 15:58 UTC, dLobatog commented
@timogoebel Updated with a ticket - I thought it would not be needed in this case (tickets are used to see what goes in each release)

2017-02-09 13:30 UTC, timogoebel requested changes
@dLobatog : Thanks for adding the ticket. As the README is also part of a release, a ticket can't hurt. Left two more comments inline.

2017-02-09 13:30 UTC, timogoebel commented on README.md
>  * Wiki: [Foreman wiki](http://projects.theforeman.org/projects/foreman/wiki/About)
The freenode link (line below) below doesn't work. I know you didn't break it, but while we're at it...

2017-02-09 13:30 UTC, timogoebel commented on README.md
> +Using Puppet, [Ansible](https://theforeman.org/plugins/foreman_ansible/), [Chef](https://theforeman.org/plugins/foreman_chef/), [Salt](https://theforeman.org/plugins/foreman_salt/) and Foreman's [sma
We should either link to all of the Github pages of Puppet, Ansible, Salt and Smart-Proxy or all links should point to the manual. I'd prefer the former, but don't have a strong preference.

2017-02-09 14:59 UTC, dLobatog commented on README.md
> +Using Puppet, [Ansible](https://theforeman.org/plugins/foreman_ansible/), [Chef](https://theforeman.org/plugins/foreman_chef/), [Salt](https://theforeman.org/plugins/foreman_salt/) and Foreman's [sma
You're right, I thought I did that - will do in a moment

2017-02-09 15:03 UTC, dLobatog commented
@timogoebel Updated - now all links in the introduction point to the manual (including Puppet and Smart Proxy which did not do that before) and freenode points to freenode.net

2017-02-10 08:22 UTC, timogoebel approved these changes

2017-02-10 08:22 UTC, merged

2017-02-10 08:22 UTC, timogoebel commented
Merged, thanks @dLobatog!