Fixes #18381 - PXE loader attr load in host/hostgroup form
theforeman/foreman pull request #4260
Opened 2017-02-08 13:11 UTC by swapab

Override pxe_loader attribute to fail safe find nested pxe_loader from parent hostgroup. Host#pxe_loader needed override as similar behavior was observed in new host form.

- [ ] Test-cases WIP

2017-03-01 12:32 UTC, lzap commented
Thanks, it fixes the issue but when I create hg A with some loader setting and then I click on Nest button, it does explicitly set it instead of Inherited value (The value), is this expected behavior?

2017-03-01 12:49 UTC, swapab commented
@lzap Yes, it is showing the PXE Loader value explicitly now. Is it mandatory to show it like `Inherited value(the value)`?
If yes, I'll revisit this and try to bring back the previous behavior(along with the fix).

2017-03-01 14:26 UTC, lzap commented
I don't mind this behavior, it's just different. Is there a reason for that? @ares ?

2017-03-06 13:08 UTC, ares commented
I'd prefer to have the inheritance as for other fields unless there's some technical limitation.

2017-03-16 10:50 UTC, swapab commented
@lzap @ares PR has been updated to the original behavior of showing `Inherit parent (<pxe-loader>)`

2017-03-23 11:43 UTC, lzap commented
Looks good but this does not work:

Create hostgroup A, select Grub2 UEFI for example, save.
Create nested hg B, select Grub1, save.
Now edit B again, select Inherit parent (Grub1) - but this should be Inherit parent (Grub2 UEFI).

Perhaps add a test for that? The one there is there did not catch this.

2017-03-23 15:53 UTC, swapab commented
@lzap Thanks for catching this :+1: 

Q: What should be the behavior in the following case:
1. Create Hostgroup-A, select Grub2 UEFI save
2. Create _independent_ Hostgroup-B, select Grub1 save
3. Edit Hostgroup-B, set parent Hostgroup-A, goto Operating systems -> PXE Loader shows 'Grub1'.
4. Dropdown has value 'Inherited parent (Grub2 UEFI)'

step#3 PXE Loader should be auto selected to step#4?
On edit, this appears to be a bug but looks like `FormHelper#blank_or_inherit_f` is not supposed to handle this, dropdown had already got its value. I think we need to reset the dropdown so that, include_blank plays it's role.

2017-03-23 16:01 UTC, swapab commented
A point to mention, after saving on step#3 the functionality might be working as expected, as the parent hostgroup relation is achieved. This is the UI part that should show what actually is.

One fix could be, let's not reset the drop-down instead reset `pxe_loader` on the server side while updating(since parent hostgroup is there).

2017-03-27 12:06 UTC, lzap commented
There are test failures.

2017-03-30 14:15 UTC, swapab commented
@lzap Tests are green.

Q: https://github.com/theforeman/foreman/pull/4260#issuecomment-288764905 do you think this is a valid use-case/scenario?

To summarize, shall we reset hostgroup.pxe_loader value if parent_id is present? Does an explicitly set pxe_loader has any effect even if hostgroup has a parent(with a valid parent_hg.pxe_loader)?

2017-03-30 15:03 UTC, lzap approved these changes
This is expected behavior, thanks.

2017-03-30 15:04 UTC, lzap commented
I'd like to have extra look by @ares as I would like to propose this into 1.15, looks good, works as expected. Any concerns?

2017-04-03 15:30 UTC, ares commented
It does not seem to work for me when I have multiple levels of inheritance. E.g. host groups A -> B -> C, B correctly inherits from A but C displays `Inherit parent ()`. Other values, such as architecture, seems to work fine.

2017-04-05 11:13 UTC, lzap commented
Can you add a test for three levels of inheritance please? Good catch thanks.

2017-04-10 11:48 UTC, swapab commented
@ares Thanks for catching this. I have used attribute `selected` to fix multi-level inheritance issue.

2017-04-11 13:01 UTC, lzap requested changes
Unfortunately, on Hostgroup edit, I am not able to save nested hostgroup with explicitly set flag. It always falls back to Inherited parent no matter what I set. If possible, make a test for this.

2017-04-17 12:11 UTC, swapab commented
@lzap Fixed the explicit use case https://github.com/theforeman/foreman/pull/4260#issuecomment-292926741 and added a js test https://github.com/theforeman/foreman/pull/4260/files#diff-5a2960f2e24206bf7cca4c8b3b029e40

2017-04-20 11:53 UTC, lzap approved these changes

2017-04-20 11:56 UTC, merged

2017-04-20 11:58 UTC, lzap commented
Thanks it works fine, althought there is one wish I have - when you create new host without any hostgroup set, currently PXE loader is blank, I wish it was set to PXELinux (BIOS) which was the default behavior before I introduced PXE loader. In the original patch this was never implemented, but I wish we had this. If you happen to find some time to work on this as well, that would be great. Anyway good patch, thanks a lot!

2017-04-20 12:11 UTC, swapab commented
@lzap Thanks for merging the patch :smiley: 
I'll take a note of the wish. It does make a lot of sense to have default `pxe_loader`. I am yet to understand 'behind the scene' part of `pxe_loader` but I have created a new ticket to address it : http://projects.theforeman.org/issues/19327