Fixes #3541,#13769 - make sure the ssh orchestration methods return true on success
theforeman/foreman pull request #4262
Opened 2017-02-08 22:02 UTC by iNecas

Strange things start happening otherwise.

Less controversal version after https://github.com/theforeman/foreman/pull/3269
not making it in.

2017-02-09 13:26 UTC, ares approved these changes
Fixes the problem and refactors the condition in delSSHCert, :+1:

2017-02-09 13:48 UTC, ares requested changes
actually a I'm afraid I found another combination where some step fails if log level is set to error, investigating

2017-02-09 13:53 UTC, ares requested changes

2017-02-09 13:53 UTC, ares commented on app/models/concerns/orchestration/ssh_provision.rb
> +      if puppetca? && respond_to?(:initialize_puppetca, true)
when I deploy host without puppet ca, this fails since this is the last expression and it's missing

```ruby
else
  true
end
```

2017-02-09 17:21 UTC, iNecas commented on app/models/concerns/orchestration/ssh_provision.rb
> +      if puppetca? && respond_to?(:initialize_puppetca, true)
Ah, I assumed we ignore when returning nil (and only false is significant), but you're right, updated

2017-02-10 12:21 UTC, ares approved these changes

2017-02-10 12:22 UTC, ares commented
Foreman tests failure unrelated, thanks @iNecas, merged as a4e1e08ceb388e9749fceee8ae4487ab3c76c105

2017-02-10 12:22 UTC, closed without merging

2017-02-14 08:44 UTC, lzap commented
I was wondering, how about to insist on a return value of some type in the orchestration code. We'd need to refactor all orchestration return values, but that is easy change. I see this kind of bug for second time now, it had to be difficult to track. Any comments? Shall I make a refactor ticket for that?

2017-02-14 09:12 UTC, iNecas commented
@lzap I think it would make sense: the biggest obstacle I see is you need a buy-in from multiple people here, and especially as it's compatibility breaking change, it might be a challenged. But you initial :+1 from me at least.