fixes #18512 - support sprockets-rails 3.x
theforeman/foreman pull request #4288
Opened 2017-02-15 13:47 UTC by domcleal

The app.assets environment is no longer always configured, and instead
is only configured when the regular Rails environment is loaded. Loading
only the 'assets' group initializers isn't sufficient.

Because the asset group initializers are no longer run, the plugin API
has been extended with `precompile_assets` and `automatic_assets` to
store and optionally generate a list of assets for that plugin. It
deprecates using an assets initializer, modifying SETTINGS and
`config.assets.precompile` to configure the plugin asset list.

2017-03-20 20:27 UTC, ohadlevy commented
[test katello]

2017-05-29 13:50 UTC, dLobatog requested changes
@domcleal I think the deprecation message showed up fine but it didn't fall back to the previous behavior. One of the failed tests in Katello precisely has to do with including assets this way (https://github.com/Katello/katello/blob/master/test/controllers/foreman/containers/steps_controller_test.rb#L25)  

http://ci.theforeman.org/job/test_develop_pr_katello/2816/database=postgresql,ruby=2.2,slave=fast/consoleFull contains the messages. I'll investigate what happened when loading foreman_docker + Katello.

2017-05-30 11:05 UTC, domcleal commented
> I think the deprecation message showed up fine but it didn't fall back to the previous behavior. One of the failed tests in Katello precisely has to do with including assets this way

The deprecation warning is when SETTINGS is populated, which is only used in the `plugin:assets:precompile` rake task. The development or test mode asset pipeline should continue to work fine.

The assertion in that test is probably too tight, it assumes that digests are disabled, which is not the case by default in 3.x.

2017-06-19 06:17 UTC, ohadlevy commented
@dLobatog ping?

2017-06-27 16:04 UTC, dLobatog commented
Sorry for the long turnaround, @domcleal you're right on https://github.com/theforeman/foreman/pull/4288#issuecomment-304845600. I changed the test on https://github.com/Katello/katello/pull/6841, as soon as it's merged I will trigger the test katello job again and hopefully merge.

2017-06-27 16:04 UTC, dLobatog approved these changes

2017-06-30 14:05 UTC, mmoll commented
[test katello]

2017-06-30 20:32 UTC, jlsherrill commented
[test katello]

2017-06-30 23:09 UTC, dLobatog commented
[test katello]

2017-07-01 14:22 UTC, mmoll commented
[test katello]

2017-07-01 14:28 UTC, mmoll commented
I have not the slightest idea, what's happening here, maybe one of the deprecations warnings is treated as an error at some point, leading to an incomplete DB...

2017-07-04 05:38 UTC, dLobatog commented
@mmoll I think I've seen the katello job failing like random on other PRs here in a similar way [test katello]

2017-07-04 09:01 UTC, mmoll commented
[test katello] again

2017-07-04 09:29 UTC, mmoll commented
I think this one is failing consistently...

2017-07-04 09:30 UTC, mmoll commented
https://github.com/Katello/bastion/pull/198 is related, BTW, but no idea if that fixes anything

2017-07-06 15:28 UTC, mmoll commented
[test katello]

2017-07-06 17:28 UTC, jlsherrill commented
[test katello]

2017-07-06 18:14 UTC, jlsherrill commented
[test katello]

2017-07-07 13:04 UTC, jlsherrill commented
[test katello]

2017-07-07 13:39 UTC, dLobatog approved these changes
This branch does not have host_info from https://github.com/theforeman/foreman/pull/3701/files which is needed to pass Katello tests. However the commit is included in https://github.com/theforeman/foreman/pull/4646 including authorship so I think it's safe to close this if tests pass on that one.

2017-07-07 14:24 UTC, closed without merging

2017-07-07 14:25 UTC, dLobatog commented
Closed as it was merged with #4646