Fixes #18587 - fix 'multipart form data' IE bug for domains and subnets
theforeman/foreman pull request #4313
Opened 2017-02-21 12:08 UTC by evgeni

According to this bug (https://connect.microsoft.com/IE/Feedback/Details/868498),
multipart form data is malformed if there are fields without names.
It been solved within Edge browser, however no solution is expected for IE10/IE11

It cause a failure with Rack - EOFError: bad content body, therefore pages like
domains and subnet create/edit cannot be submitted (and all other forms which are
submitted via ajax with multipart form data, and an unnamed field within).

This is identical to https://github.com/theforeman/foreman/pull/4125
but on the domains and subnets pages.

2017-02-21 12:09 UTC, sean797 commented
ok to test

2017-02-21 12:12 UTC, tbrisker commented
@evgeni - could you please extract that snippet to a helper and use that in both places as well as the previous one (in the templates)? I've also seen this occur on the smart variable form, care to add it there as well?

2017-02-21 13:07 UTC, evgeni commented
Created a snippet as @tbrisker asked and also fixed https://bugzilla.redhat.com/show_bug.cgi?id=1422188

2017-02-21 13:38 UTC, tbrisker requested changes
Just a minor comment, looks good in general. 
I'll try to test if there are other forms that have the same issue so we can solve it once and for all.

2017-02-21 13:38 UTC, tbrisker commented on app/helpers/form_helper.rb
> +  def internetexplorer_multipart_form_data_fix(f)
No need to pass the form object (`f`) in here. Also name is a bit long, how about `ie_multipart_fix` or something like that?

2017-02-21 13:46 UTC, tbrisker approved these changes

2017-02-21 13:50 UTC, tbrisker commented
Code looks good, pending testing on IE and checking for other places hitting the same bug.

2017-02-23 10:02 UTC, amirfefer commented
@evgeni, @tbrisker domains and subnets pages work well on IE11, however I've found few more forms with the same issue: Global parameters, Architectures, Installation media and Operating systems.

2017-02-23 10:18 UTC, evgeni commented
@amirfefer cool, thanks for checking. I must admit I was too lazy to click though *all* the dialogs in my IE11 VM.

Will see that I fix the other dialogs too.

I wonder if there is a nicer way to inject that snipet into all Ajax dialogs.

2017-02-23 16:04 UTC, dLobatog commented
Setting to WoC based on @amirfefer 's  comment

2017-03-01 10:27 UTC, tbrisker commented
@evgeni - There is a way to automatically add this on all two pane forms. In the `submit_or_cancel` method in `app/helper/form_helper.rb`, check if `request.env['HTTP_X_FOREMAN_LAYOUT'] == 'two-pane'`. If it is true, add this fix after the buttons. 
We can even further only apply it on IE browsers by checking if `request.env['HTTP_USER_AGENT'].include?('MSIE')`.

2017-03-01 19:23 UTC, evgeni commented
@tbrisker there we go :)

* I used `request.headers` not `.env` as I think that's cleaner
* I did not add the `MSIE` filter, as I think this is ugly and only makes debugging harder

2017-03-01 19:29 UTC, tbrisker requested changes
Thanks @evgeni , this looks much cleaner. one concern though - the fake field has to be the last field in the form, we need to make sure that is the case for all relevant forms. One case noted inline.

2017-03-01 19:29 UTC, tbrisker commented on app/views/templates/_form.html.erb
>    <input type="hidden" id="new" value="<%= @template.template %>" />
I think these also need to be reordered with the submit_or_cancel so the fix is the last input

2017-03-01 21:09 UTC, evgeni commented
Right. That is what you get when you commit at 8000m :)
Fixed.

2017-03-06 12:47 UTC, timogoebel commented
I just tested `develop` without this patch with:
![image](https://cloud.githubusercontent.com/assets/4107560/23610572/47477f34-0273-11e7-8c93-e04925387dc4.png)

The menu didn't work at all but I had no issues submitting the subnet form. :-(

2017-03-08 09:45 UTC, timogoebel commented
@evgeni : I was finally able to verify this works. Good job.

@tbrisker +1 from me

2017-03-08 09:46 UTC, timogoebel approved these changes

2017-03-08 09:53 UTC, tbrisker approved these changes

2017-03-08 09:53 UTC, merged

2017-03-08 09:54 UTC, tbrisker commented
Thanks @evgeni  and @timogoebel !