Adding VMware vSphere Disk Mode support (Dependent, Independent - P…
theforeman/foreman pull request #4314
Opened 2017-02-21 12:49 UTC by BernhardAtix

Adding VMware vSphere Disk Mode support (Dependent, Independent - Persistent, Independent - Nonpersistent)

2017-02-21 13:03 UTC, ohadlevy commented
@BernhardAtix thanks! FYI - please note that #3979 potentially rewrite this part of the form

2017-02-21 13:05 UTC, ohadlevy commented
ok to test

2017-02-21 14:26 UTC, timogoebel requested changes
@BernhardAtix : Thanks for your PR. I left some comments inline. Could you also please provide a Redmine issue for this?

2017-02-21 14:26 UTC, timogoebel commented on app/views/compute_resources_vms/form/vmware/_volume.html.erb
> +# regarding to the following documentation:
Could you please remove these comments? They don't belong in Foreman's source.

2017-02-21 14:26 UTC, timogoebel commented on app/views/compute_resources_vms/form/vmware/_volume.html.erb
> +<% disk_mode_values = [['Dependent', :persistent],
Please move these options to vmware's compute resource model.

`firmware_types` is one example for this.
https://github.com/theforeman/foreman/blob/develop/app/models/compute_resources/foreman/model/vmware.rb#L170

Please note, that you need to mark the names as translatable, e.g. `_('Dependent')`.

2017-02-21 14:26 UTC, timogoebel commented on app/views/compute_resources_vms/form/vmware/_volume.html.erb
> +
Nitpick: Please remote the empty line.

2017-03-06 21:47 UTC, BernhardAtix commented
fixes #18815 
=> added redmine issue for it

2017-03-07 17:12 UTC, timogoebel requested changes
@BernhardAtix : Thanks for the updates. I left one small comment inline.

2017-03-07 17:12 UTC, timogoebel commented on app/models/compute_resources/foreman/model/vmware.rb
> +        "persistent" => N_("Persistent"),
This isn't translated correctly.
`N_()` just marks a string for translation but doesn't actually translate it.
Please use either `_()` or translate it in the view.
```ruby
<%= select_f f, :mode, compute_resource.disk_mode_types, :first, ->(d) { _(d.last) }, { }, :class => "span5", :label => _("Disk mode"), :label_size => "col-md-2", :disabled => !new_host %>
```

2017-03-08 09:14 UTC, timogoebel approved these changes
Thanks @BernhardAtix. Works well.

2017-03-08 09:16 UTC, merged