fixes #18676 - don't ignore notification expiry
theforeman/foreman pull request #4337
Opened 2017-02-26 15:18 UTC by ohadlevy

This also adds the ability to mass refresh expiry dates.

2017-02-27 21:05 UTC, dLobatog requested changes
@ohadlevy Left a few minor comments, particularly it took me a bit of time to understand why `expired_at` was not using delegation. Overall I agree it's a good change, thanks!

2017-02-27 21:05 UTC, dLobatog commented on app/models/notification.rb
> +  def set_expiry
A comment explaining that you want this value to be saved only once, when the Notification is created, would be useful. Otherwise I think it's going to lead people unfamiliar with the code to wonder why it's not `delegate :expired_at, :to => :notification_blueprint` instead.

Since it has the potential of override an existing attribute, I think it would be good to warn by naming it `set_expiry!`

2017-02-27 21:05 UTC, dLobatog commented on app/controllers/notification_recipients_controller.rb
> +      joins(:notification).merge(Notification.active).
I think this can do without the `join`, by adding it to the `where`

`where(:user_id => User.current.id, :notification_id => Notification.active)`

2017-02-27 21:05 UTC, dLobatog commented on app/models/notification_blueprint.rb
> +  def mass_update_expiry
I'd rather not add unused code if we can avoid it, is it used anywhere?

```
blueprint.notifications.map(&:set_expiry!) // is clear enough IMO to not need a method
```

2017-02-28 07:25 UTC, ohadlevy commented on app/models/notification_blueprint.rb
> +  def mass_update_expiry
its used in the discovery notification pr - see https://github.com/theforeman/foreman_discovery/issues/328

2017-02-28 07:26 UTC, ohadlevy commented on app/models/notification_blueprint.rb
> +  def mass_update_expiry
also, map will create a rails ar object, the approach is mass update on the db level.

2017-02-28 07:29 UTC, ohadlevy commented
@dLobatog:
1. removed the join to inner select
2. added a comment.
thanks for the review!

2017-02-28 15:46 UTC, dLobatog approved these changes

2017-02-28 15:46 UTC, merged

2017-02-28 15:46 UTC, dLobatog commented
Thanks @ohadlevy !