Fixes #16043 - add 'select all hosts' option into hosts page
theforeman/foreman pull request #4338
Opened 2017-02-26 15:50 UTC by amirfefer

`Select all items` checkbox in hosts page selects only the hosts within the page.  when the user wish to select all hosts for a bulk action, he has to select all hosts page after page.

![multiple_selection1](https://cloud.githubusercontent.com/assets/11807069/23341140/b0703818-fc4a-11e6-88d1-6e0266493bd5.png)

![multiple_selection](https://cloud.githubusercontent.com/assets/11807069/23341141/b07082a0-fc4a-11e6-8bc3-7749326729a9.png)

![ezgif com-resize](https://cloud.githubusercontent.com/assets/11807069/23341085/01ee8600-fc4a-11e6-8074-4b9c3ff52582.gif)

2017-02-26 15:56 UTC, ohadlevy commented on app/views/hosts/_selected_hosts.html.erb
> +  <%= alert(:class => 'alert-info hide', :close => true, :header => '',
maybe this should be warning? @rohoover ?

2017-02-27 14:24 UTC, Rohoover commented on app/views/hosts/_selected_hosts.html.erb
> +  <%= alert(:class => 'alert-info hide', :close => true, :header => '',
@ohadlevy For which part? The selection of all items or that all items are changing owners?

2017-02-27 14:42 UTC, ohadlevy commented on app/views/hosts/_selected_hosts.html.erb
> +  <%= alert(:class => 'alert-info hide', :close => true, :header => '',
I'm looking for a way to say that you are seeing only the first 20 but you actually selected all of them, so if you take an action against them its the entire list not just he one you see (same workflow if you select all of your emails on gmail).

2017-02-27 16:08 UTC, tbrisker requested changes
Added a few comments inline. Seeing the amount of changes to host_checkbox.js.erb, I wonder if it makes sense to just rewrite it in ES6? afaict the only reason for it to be an .erb is for the path to the spinner, which I think can be done with just a class anyways.

2017-02-27 16:08 UTC, tbrisker commented on app/helpers/layout_helper.rb
> +    content_tag(:div, :id => "pagination", :class => "row", 'data-meta-count' => collection.count) do
Use `collection.total_entries` which caches to total count

2017-02-27 16:08 UTC, tbrisker commented on app/controllers/hosts_controller.rb
> +    if params[:host_names].present? || params[:host_ids].present? || params.key?(:search)
mind turning all of these to `.key?`?

2017-02-27 16:08 UTC, tbrisker commented on app/assets/javascripts/host_checkbox.js.erb
> +    var query = $("<input>")
why do you need to create an input here if the value is encoded directly to the query?

2017-02-27 16:08 UTC, tbrisker commented on app/assets/javascripts/host_checkbox.js.erb
> +    $("#confirmation-modal form").append($(query));
no need to wrap `query` here, it is already a jquery object

2017-02-27 16:08 UTC, tbrisker commented on app/assets/javascripts/host_checkbox.js.erb
> +    if ($(".alert").length){
might this be a different alert?

2017-02-27 18:21 UTC, Rohoover commented on app/views/hosts/_selected_hosts.html.erb
> +  <%= alert(:class => 'alert-info hide', :close => true, :header => '',
@ohadlevy 

I actually like the way it's address in the gif. I don't think it should be a warning as nothing "wrong" happened.

2017-03-01 12:13 UTC, amirfefer commented
thanks @tbrisker for your review, I've followed your comments.

2017-03-02 11:43 UTC, ohadlevy commented
@tbrisker I would favor to move this to ES6 in a separate commit, as that most likely will invlove the entire file vs just this particular feature?

also the js.erb file has been fixed in #4349

2017-03-08 09:55 UTC, tbrisker commented
In general this works well, however there is an issue when selecting a very large amount of hosts - loading the modal with the host list can take several minutes as it isn't paginated. 
The table in the modal should be paginated or only display the matching search when "select all" is chosen. Also it seems to join tables that aren't needed for the fields it displays and can be removed to speed it up.

2017-03-09 16:12 UTC, amirfefer commented
@Rohoover: What do you think is more suitable for the modal dialog alert?

**Info alert:**
![info_alert](https://cloud.githubusercontent.com/assets/11807069/23758185/98b6c8b8-04f1-11e7-8aa4-da49d7fac3c4.png)
**Warning alert:**
![warning_alert](https://cloud.githubusercontent.com/assets/11807069/23758186/98d47cb4-04f1-11e7-878c-9e063a768b3b.png)

@tbrisker: Thanks, I think it better to display just the alert with hosts quantity and filter query, as you can see at the screenshots above. I've fixed the join issue.

2017-03-09 16:25 UTC, Rohoover commented
Use the grey box if the action isn't particular serious.

If it has strong consequences use the warning (orange) box.

Remove the chevrons in both. It would be nice to have (but not required) if the messaging would read" Reminder: **All 10 hosts are selected** for query filter architecture=..." because the important part is not what query they searched but that they have them all selected.

2017-03-09 23:48 UTC, amirfefer commented
@Rohoover Thanks :+1: . I've kept the grey box. otherwise the user would think he made something wrong.   The chevron mark notes that the string is translatable.

2017-03-12 14:20 UTC, tbrisker requested changes
Getting there, a few mostly minor inline comments.

2017-03-12 14:20 UTC, tbrisker commented on app/views/hosts/_selected_hosts.html.erb
> +            :text => _("Reminder: <strong> All #{hosts.count.to_s} hosts are selected </strong> for query filter #{multiple_filter}").html_safe) %>
I think it makes sense to only show the "for query filter..." part if there is a filter, otherwise it looks odd:
![image](https://cloud.githubusercontent.com/assets/1540531/23832009/60a3158a-0735-11e7-8ed9-a614b17eef7a.png)

2017-03-12 14:20 UTC, tbrisker commented on app/helpers/layout_helper.rb
> +    content_tag(:div, :id => "pagination", :class => "row", 'data-meta-count' => collection.total_entries) do
We also have a meta tag on the host list for number per page, it makes sense to me to use the same here as well using a `<meta name="totalResults" content="#{collection.total_entries}"/>` tag.

2017-03-12 14:20 UTC, tbrisker commented on app/views/hosts/index.html.erb
> +          :text => _("All #{Setting[:entries_per_page]} hosts on this page are selected. ").html_safe + link_to_function((_("Select all <b> #{@hosts.count.to_s} </b> hosts")).html_safe, "multiple_sel
This should also use the cached `@hosts.total_entries` instead of `@hosts.count`.

2017-03-12 14:20 UTC, tbrisker commented on app/views/hosts/_selected_hosts.html.erb
> +            :text => _("Reminder: <strong> All #{hosts.count.to_s} hosts are selected </strong> for query filter #{multiple_filter}").html_safe) %>
The filter should also be escaped to prevent XSS :
![image](https://cloud.githubusercontent.com/assets/1540531/23832435/a2a1cd44-073c-11e7-943f-a6c20de6ec77.png)

2017-03-12 14:20 UTC, tbrisker commented on app/views/hosts/_selected_hosts.html.erb
> +    <%= _('Keep selected hosts for a future action') %><br/><br/>
shouldn't this be possible also when selecting all? (i.e. outside the if block)

2017-03-12 14:20 UTC, tbrisker commented on app/controllers/hosts_controller.rb
> +    if params.key?(:host_names) || params.key?(:host_ids) || multiple_with_filter?
I wonder - do we actually ever call this method with a `host_names` parameter?

2017-03-12 14:20 UTC, tbrisker commented on app/controllers/hosts_controller.rb
> +  end
I think this should go in the helper instead of the controller.

2017-03-12 14:20 UTC, tbrisker commented on test/controllers/hosts_controller_test.rb
> +  end
Please add a test that has an actual search query and make sure only the matching hosts are selected.

2017-03-12 14:20 UTC, tbrisker commented on app/assets/javascripts/host_checkbox.js
> +  var select_text = Jed.sprintf(__("Select all") + "<b> %s </b>" + __("hosts"), count);
This won't translate correctly in all languages as the strings `Select all` and `hosts` will be translated separately and not as one sentence. Also above on line 96.

2017-03-12 22:40 UTC, amirfefer commented on test/controllers/hosts_controller_test.rb
> +  end
I've added two additional tests

2017-03-12 22:41 UTC, amirfefer commented on app/controllers/hosts_controller.rb
> +    if params.key?(:host_names) || params.key?(:host_ids) || multiple_with_filter?
I haven't found anything using `host names` in params...

2017-03-12 22:42 UTC, amirfefer commented on app/controllers/hosts_controller.rb
> +  end
`host_helper` is too large, hence I've extract this logic into `hosts_and_hostgroup_helper`

2017-03-12 22:42 UTC, amirfefer commented on app/helpers/layout_helper.rb
> +    content_tag(:div, :id => "pagination", :class => "row", 'data-meta-count' => collection.total_entries) do
I've added this particularly  to pagination div, so the total collection size would be collectable from any pagination page.

As you can see at the following screenshot, the total size is visable though hardly collectable. 
![total](https://cloud.githubusercontent.com/assets/11807069/23836664/6dffb8d8-0784-11e7-924f-806e385fbb1b.png)
 The meta name `per page` exists only in hosts page.

2017-03-12 22:46 UTC, amirfefer commented on app/views/hosts/_selected_hosts.html.erb
> +    <%= _('Keep selected hosts for a future action') %><br/><br/>
I've thought at the beginning that it useless due to cookie implementation , but I've managed not to expand this cookie :smile:

2017-03-12 22:50 UTC, amirfefer commented
@tbrisker I've fixed most of your inline comments, I've left some inline comments.

2017-03-12 23:08 UTC, amirfefer commented on app/helpers/hosts_and_hostgroups_helper.rb
> +      with_filter = _("Reminder: <strong> All #{hosts.size} hosts are selected </strong> for query filter").html_safe + h(params[:search])
In the helper file, I've couldn't use `total_entries` (no method exception),  instead I've used `size`.

2017-03-13 07:41 UTC, ohadlevy commented on app/helpers/layout_helper.rb
> +    content_tag(:div, :id => "pagination", :class => "row", 'data-meta-count' => collection.total_entries) do
@tbrisker @amirfefer meta attribute was remove at https://github.com/theforeman/foreman/commit/ee7002f8f2bffb3a589c28ea1b35460b6bdbf3c0#diff-7eb571b855131f643240b7b93ddfd44dL4

2017-03-13 13:41 UTC, amirfefer commented on app/helpers/layout_helper.rb
> +    content_tag(:div, :id => "pagination", :class => "row", 'data-meta-count' => collection.total_entries) do
I've removed the use of meta attribute, instead I've expand  `will_paginate_with_info` with `include_data_tag` flag.

2017-03-16 08:48 UTC, ohadlevy commented
@amirfefer please rebase.
@tbrisker what is left here? thanks

2017-03-20 13:22 UTC, tbrisker requested changes
Works well in general, a few minor inline comments. 
One thing I also noticed when testing this - when selecting all hosts on a page, then searching for something else, the "select all" isn't cleared leading to a confusing header- e.g. "All 20 hosts on this page are selected. Select all 4 hosts" when non of the hosts on the page are actually selected. This also appears to be present on develop, but is less obvious because there is no big header telling you how many hosts are selected (it's only listed at the bottom of the page).

2017-03-20 13:22 UTC, tbrisker commented on app/helpers/hosts_and_hostgroups_helper.rb
> +    with_filter = _("Reminder: <strong> All #{hosts.size} hosts are selected </strong> for query filter").html_safe + h(params[:search])
nitpick: missing either a `: ` in the end of the sentence or placing the search inside the translated string (since if it's part of the sentence it might not be the end of it in all languages).

2017-03-20 13:22 UTC, tbrisker commented on app/helpers/layout_helper.rb
> +                :data => ({'count' => collection.total_entries, 'per-page' => Setting[:entries_per_page]} if options[:include_data_tag])) do
Is there any reason not to have these always available for anything that needs them rather then add yet another option?

2017-03-20 13:22 UTC, tbrisker commented on app/assets/javascripts/host_checkbox.js
> +  $(".text").html('<span id="multiple-chosen">' + alert_text + '<a href="#" onclick="undo_multiple_selection();">' + undo_text + '</a></span>');
nitpick: missing a space here.

2017-03-23 00:14 UTC, amirfefer commented on app/helpers/layout_helper.rb
> +                :data => ({'count' => collection.total_entries, 'per-page' => Setting[:entries_per_page]} if options[:include_data_tag])) do
No special reason..

2017-03-23 00:22 UTC, amirfefer commented
@tbrisker Thanks, I've rebased and fixed above issues, including the search bug.

2017-03-23 13:04 UTC, ohadlevy commented
test failure unrelated.

2017-03-23 13:36 UTC, tbrisker commented
I'm afraid the resetting of selection on filter change still does not work as expected:
![image](https://cloud.githubusercontent.com/assets/1540531/24249991/fd6728ba-0fdd-11e7-936c-7f5de052c1d4.png)
This is after I selected all 89 hosts in a different search, then searched for something else. Clicking on a multiple action from the action select button leads to loading the modal with the first 20 from the previous search. If the new search return a subset of the previous this is even more confusing - you expect only some hosts to be affected but then the modal contains all.
@Rohoover - correct me if I'm wrong, but to me it makes sense that a new search should clear any previously selected hosts, right?

2017-03-23 14:15 UTC, Rohoover commented
@tbrisker 

Yes, that would be my assumption as well.

2017-03-23 14:21 UTC, tbrisker commented
@amirfefer Also, if I select all hosts, then in the modal choose "keep hosts selected", then it reverts to only the first 20 instead of all matching the filter.

2017-03-23 16:37 UTC, amirfefer commented
@tbrisker IMO the cookie is the problem here.
I think it better to keep the cookie behavior as it was, which means only for save specific hosts selection.
I don't see any benefit to save the user's choice in a cookie when he select a whole collection by search filter. Therefore I've removed the `keep hosts selected` checkbox when a user select all hosts by query filter.

2017-03-27 08:54 UTC, tbrisker requested changes
Here is a screenshot explaining the problem with not clearing the cookie on a new search:
![screenshot from 2017-03-27 11-45-07](https://cloud.githubusercontent.com/assets/1540531/24348312/eb15eb2a-12e3-11e7-9d1e-1d67decfae2d.png)
Note that the top shown "20 selected", but the bottom says "40 selected" which is the correct number. (to get to this situation, search for something, mark some hosts, search a different search and select all)

2017-03-27 08:54 UTC, tbrisker commented on app/helpers/hosts_and_hostgroups_helper.rb
> +     collection.total_entries > Setting[:entries_per_page] ? Setting[:entries_per_page] : collection.total_entries
Shouldn't this be in layout helper?
also, how about `[Setting[:entries_per_page], collection.total_entries].min`?

2017-03-27 08:54 UTC, tbrisker commented on app/assets/javascripts/host_checkbox.js
> +  var per_page = $("#pagination").data("per-page");
Please cache `$("#pagination")` to save dom lookups

2017-03-27 08:54 UTC, tbrisker commented on app/assets/javascripts/host_checkbox.js
> +  $(".text").html('<span id="multiple-chosen">' + alert_text + '<a href="#" onclick="multiple_selection();">' + select_text + '</a></span>');
Isn't `.text` a bit of a generic selector?

2017-03-27 08:54 UTC, tbrisker commented on app/assets/javascripts/host_checkbox.js
> +  var total_host = $("#pagination").data("count");
ditto

2017-03-27 21:49 UTC, amirfefer commented
@tbrisker :  From your screenshot It looks like the top number is presented correctly  while the bottom does not. 
This issue occurs due to a counter bug which exists in develop, as you can see in the following screenshot.
![selected_counter](https://cloud.githubusercontent.com/assets/11807069/24379262/fd7ea534-134e-11e7-9dd2-701e3044896d.png)

I've fixed the rest.

2017-03-28 14:31 UTC, tbrisker requested changes
a few more comments, please also note related tests seem to be failing intermittently.

2017-03-28 14:31 UTC, tbrisker commented on app/assets/javascripts/host_checkbox.js
> +  $.per_page = $("#pagination").data("per-page");
Why are you adding these to the jQuery object?

2017-03-28 14:31 UTC, tbrisker commented on app/assets/javascripts/host_checkbox.js
> +      $("#multiple-alert").data('multiple', false)
`$("#multiple-alert")` should be cached to reduce lookups

2017-03-28 14:31 UTC, tbrisker commented on app/assets/javascripts/host_checkbox.js
> +  $.per_page = $("#pagination").data("per-page");
also please cache `$("#pagination")`

2017-03-28 14:31 UTC, tbrisker commented on app/assets/javascripts/host_checkbox.js
> +    $("#multiple-alert").data('multiple', false);
please cache these too

2017-03-30 12:40 UTC, amirfefer commented
@tbrisker , thanks, I've added caching to reduce lookups.

2017-04-02 12:40 UTC, tbrisker commented
@amirfefer Following our talk, looks like you didn't push an updated version with correct caching for jquery objects?

2017-04-03 01:40 UTC, amirfefer commented
@tbrisker , You're right, now you can see caching for jquery objects

2017-04-03 10:52 UTC, merged

2017-04-03 10:53 UTC, tbrisker commented
Thanks @amirfefer ! I'd be happy to see all of this code rewritten in es6 or react, could you please open a refactor issue for that?