Fixes #18764 - Hammer-cli current user password update
theforeman/foreman pull request #4359
Opened 2017-03-06 17:37 UTC by dhlavac

2017-03-07 09:26 UTC, tstrachota requested changes
Works fine in general. Added some comments about name and description of the new params.

2017-03-07 09:26 UTC, tstrachota commented on app/controllers/api/v2/users_controller.rb
> +      def_param_group :current_user_update do
Since the endpoint can be used for updating any user, not just the current one, would you mind to rename to just `user_update`?

2017-03-07 09:26 UTC, tstrachota commented on app/controllers/api/v2/users_controller.rb
> +          param :current_password, String, :required => true
I think that `current_password` is required only when you perform the request from non-admin account so `:required => true` should go away.

2017-03-07 09:26 UTC, tstrachota commented on app/controllers/api/v2/users_controller.rb
> +          param :current_password, String, :required => true
Also a description when this field is required would be handy. Could you add it, please?

2017-03-09 11:05 UTC, dhlavac commented
@tstrachota solved comments please look at PR

2017-03-09 11:31 UTC, tstrachota commented
LGTM :+1: @dhlavac

2017-03-10 18:59 UTC, merged

2017-03-10 18:59 UTC, dLobatog commented
Thanks @dhlavac @tstrachota !