fixes #18940 - adds caching to notofication api calls.
theforeman/foreman pull request #4383
Opened 2017-03-16 16:14 UTC by ohadlevy

this also removes pagination from the implementation, as that was not
implemented in the UI at all.

this implementation reduce the notification fetching time on
my production system from avg response times of 80ms to 20ms.

2017-03-20 14:47 UTC, tbrisker reviewed
:+1: in general, a few inline comments.

2017-03-20 14:47 UTC, tbrisker commented on app/controllers/notification_recipients_controller.rb
> +      includes(:notification, :notification_blueprint).
You can use `.preload` or `.joins` to prevent a potentially large double left-outer-join

2017-03-20 14:47 UTC, tbrisker commented on app/controllers/notification_recipients_controller.rb
> +      where(:user_id => User.current.id, :notification_id => Notification.active).
Doesn't this cause an extra inner query on a table you (could be) joining in any case?

2017-03-20 14:47 UTC, tbrisker commented on app/models/notification_recipient.rb
> +  after_save :delete_user_cache
Is this the only condition that invalidates the cache?

2017-03-20 14:52 UTC, ohadlevy commented on app/controllers/notification_recipients_controller.rb
> +      where(:user_id => User.current.id, :notification_id => Notification.active).
not sure i understand?

notification_id => Notification.scope adds conditions ? (expiry)

2017-03-20 14:52 UTC, ohadlevy commented on app/models/notification_recipient.rb
> +  after_save :delete_user_cache
thanks - you are correct, I need to invalidate the cache before the notification itself should expire - will fix.

2017-03-20 15:10 UTC, tbrisker commented on app/controllers/notification_recipients_controller.rb
> +      where(:user_id => User.current.id, :notification_id => Notification.active).
I mean this is the current query:
```sql
SELECT "notification_recipients".* 
FROM "notification_recipients" 
WHERE "notification_recipients"."user_id" = $1 
AND "notification_recipients"."notification_id" IN (
    SELECT "notifications"."id" 
    FROM "notifications" 
    WHERE (notifications.expired_at >= '2017-03-20 14:57:26.205932'))  
ORDER BY "notification_recipients"."created_at" ASC
```
but if you anyways load the notifications, it makes sense to do a join and just add another condition and reduce the nested query.

2017-03-27 10:33 UTC, ohadlevy commented
@tbrisker I've refactored the PR, Could you please re-review? thanks!

2017-03-27 11:06 UTC, tbrisker requested changes
Looks better, a few inline comments.

2017-03-27 11:06 UTC, tbrisker commented on app/services/ui_notifications/cache_handler.rb
> +    def initialize(user_id = User.current)
`User.current.id`?

2017-03-27 11:06 UTC, tbrisker commented on app/controllers/notification_recipients_controller.rb
> +    payload = UINotifications::CacheHandler.new(User.current).payload
Shouldn't this be `User.current.id`?

2017-03-27 11:06 UTC, tbrisker commented on app/services/ui_notifications/cache_handler.rb
> +        minimum(:expired_at)
would it make sense to just expire the cache at the next expiring notification, regardless of the user, to simplify this lookup?

2017-03-27 11:06 UTC, tbrisker commented on test/unit/ui_notifications/cache_handler_test.rb
> +    FactoryGirl.create(:notification_recipient, :notification =>  notification, user_id: user.id)
NP: I'm not opposed to new-style hashes, but at least be consistent with one style per line :smile:

2017-03-27 11:06 UTC, tbrisker commented on test/unit/ui_notifications/cache_handler_test.rb
> +    user = FactoryGirl.create(:user)
Any reason to create a new user here rather then just using an existing one?

2017-03-27 11:06 UTC, tbrisker commented on test/unit/ui_notifications/cache_handler_test.rb
> +  end
So does it use cache if it exists?

2017-03-27 12:04 UTC, ohadlevy commented on app/services/ui_notifications/cache_handler.rb
> +        minimum(:expired_at)
IMHO no, why are you concerned about this query?

2017-03-27 12:04 UTC, ohadlevy commented
@tbrisker I think I've addressed all of your comments..
![bart-simpson-chalkboard-wallpaper-generator](https://cloud.githubusercontent.com/assets/20167/24355468/af86fc00-12fe-11e7-82b6-7c7a949fcf0c.png)

2017-03-27 12:09 UTC, tbrisker commented on app/services/ui_notifications/cache_handler.rb
> +    def initialize(user_id = User.current)
missed this one

2017-03-27 12:37 UTC, tbrisker commented on app/services/ui_notifications/cache_handler.rb
> +        minimum(:expired_at)
Might be premature optimization, but if the tables grow significantly this might become a painful join for every cache miss.

2017-03-27 12:46 UTC, ohadlevy commented
@tbrisker updated again, also added .freeze on cache key and try in case User.current is nil.

2017-03-27 13:10 UTC, ohadlevy commented on app/services/ui_notifications/cache_handler.rb
> +        where(:user_id => user_id, :notification_id => Notification.active).
I'll update the hash rocket syntax after tests will pass/fail.

2017-03-27 18:33 UTC, ohadlevy commented
@tbrisker test failures seems unrelated.

2017-03-28 08:22 UTC, merged

2017-03-28 08:23 UTC, tbrisker commented
Thanks @ohadlevy !