Fixes #14160 - Allow boot order to be changed
theforeman/foreman pull request #4400
Opened 2017-03-22 14:14 UTC by chris1984

2017-03-22 14:17 UTC, ekohl commented on app/views/compute_resources_vms/form/vmware/_base.html.erb
> +<%= checkbox_f f, :boot_order, { :help_inline => _("Use default Foreman behaivor to lock boot order on creation"), :label => _('Hardcode boot order'), :label_size => "col-md-2", :disabled => !new_hos
behaivor is most likely a typo.

2017-03-23 16:30 UTC, timogoebel commented
@chris1984 : Thanks. I got it working in https://github.com/timogoebel/foreman/commit/3fe7014de4f76921b2f2ec36606146fcfe57084d.

I'd suggest that instead of the checkbox we add a sortable multiselect, where a user can actually change the boot order. I think, that makes more sense. There are probably users who want to first boot off cdrom, then network and then disk. Or any other combination.

Something like this:
http://select2.github.io/select2/#programmatic  -> "Select2 Drag and Drop Sorting"

Should not be hard to do. What do you think, @chris1984 ?

2017-05-19 13:52 UTC, chris1984 commented
@timogoebel planning to revisit this, how hard is the jquery to add the webui select box? I have never did anything with the webui before.

2017-05-19 13:57 UTC, timogoebel commented
> how hard is the jquery to add the webui select box?

I shouldn't be too difficult I think. We don't want any magic, just a rather default widget. I'd have to do some research to actually know what needs to be done.

2017-05-22 13:53 UTC, chris1984 commented
@timogoebel can we do a paired programming session then or something, or when you get time can you send me an example. I really am not familiar with jquery at all. I can try to work with one of the guys here using your existing code for the other 2 areas if you want?

2017-05-22 15:19 UTC, timogoebel commented
@chris1984 : Some wip code: https://github.com/timogoebel/foreman/commit/94c097e8fe42a37601ee22c1e9a3a04ca1119c65

Issues I have found so far:
- Data gets lost when saving the form with errors
- default values don't work
- jQuery is always messy
- no drag & drop sorting
- I have no idea if the data is passed correctly to vmware. Haven't tried provisioning a vm, yet.

2017-05-30 17:35 UTC, chris1984 commented
@timogoebel the form looks to be working better but when we use the default foreman style we get an error with boot order being "" invalid and when we use the boot options it does not reflect, but at least the checkbox is staying checked now.

2017-06-01 14:54 UTC, timogoebel commented on app/models/compute_resources/foreman/model/vmware.rb
> +         :network => 'Network'
for the sake of completeness we might want to add:
```
:floppy => 'Floppy'
```

2017-06-01 14:54 UTC, timogoebel commented on app/views/compute_resources_vms/form/vmware/_base.html.erb
> +<%= checkbox_f f, :manage_boot_order, { :help_inline => _("Use default Foreman behavior to lock boot order on creation"), :label => _('Hardcode boot order'), :label_size => "col-md-2", :disabled => !
Is this really needed? If the Boot Order select is empty, it will not enforce any boot order and use VMWare's defaults.

2017-06-01 15:09 UTC, timogoebel commented
> when we use the default foreman style we get an error with boot order being "" invalid

@chris1984: I guess, you mean this one:
` RuntimeError: failed to create boot device because "" is unknown` 

This is because the request that is sent to the server is `"boot_order"=>["", "cdrom"],`, when querying select2's value via js console i get the following:

```
$("#host_compute_attributes_boot_order").val();
["cdrom"]
```
I don't have the time to trace this right now. 
Maybe it's this hidden input field:
![image](https://cloud.githubusercontent.com/assets/4107560/26685929/c2ed93d2-46eb-11e7-97f1-30f638fa518b.png)
Where does that come from? It stays there even if I deactivate select2: `$('select').select2("destroy");`

2017-06-05 10:22 UTC, dLobatog requested changes
Moving to WoC because of the questions by @timogoebel

2017-06-13 15:15 UTC, chris1984 commented
@timogoebel after talking with @Klaas- it seems there is an issue with sending the correct boot order where VMware will honor it. Are you fine with going back to the checkbox idea of checked do default Foreman behavior right now and if unchecked just don't send anything so the user can edit the bios boot order in the VM console?

2017-06-13 15:44 UTC, timogoebel commented
> Are you fine with going back to the checkbox idea of checked do default Foreman behavior right now and if unchecked just don't send anything so the user can edit the bios boot order in the VM console?

I don't like this at all and I'm not aware of such an issue with VMWare. It's definitely not a clean solution imho. @Klaas-: Mind to explain where you think that there is a bug in VMWare? I don't get it. Is there a VMWare KB for this?

2017-06-13 17:04 UTC, Klaas- commented
@timogoebel  the (suspected) bug is within vmware when you force boot order via the vmx file. This is basically what we do at the moment through api. It seems once you force the bootorder you can't do things like deleting a disk (via web client, fat client seems to ignore this problem) or using those vms as templates (what the original issue is about if I understood it correctly). I've reported this issue to vmware but support is not really sure if this is supported by my licenses ... :) In any case I've also involved the fog-vsphere maintainer. He seems to agree to my assessment that this is a bug. Of cause this has nothing to do with what this PR has evolved to - making the boot order configurable is a nice new feature but not setting the bootorder is not really solving the issue that is at the hearth of this.

2017-06-13 17:07 UTC, Klaas- commented
plus if we don't set boot order certain things will stop working - like rebuilding a host. so if we work around the issue and make setting the boot order configurable we should warn about not putting network first there or explicitly set boot order while provisioning only (not sure if that is actually supported by vmware though)

2017-06-14 06:33 UTC, timogoebel commented
@Klaas-: Thanks for the explanation. I still don't really believe in a checkbox to just disable "bootorder hardcoding". From a user's experience, this still seems like the wrong approach.

2017-06-14 13:25 UTC, chris1984 commented
@timogoebel I am happy to do w/e will get the PR Merged :) since it will close 3 downstream bugs I have assigned to me. Do you still want to go with the drag and drop or something different?

2017-06-14 14:25 UTC, timogoebel commented
@chris1984: I had a talk with @Klaas- earlier today. I still don't fully get the suspected bug to he honest. What is the expected behavior and the actual behavior happening here?

One known restriction with this approach is:
When you set the boot order via foreman, you can't change it in the VM's bios anymore.

@Klaas- said that you cannot delete a hard disk anymore.
That is true. I can confirm this.

Is there anything else?

2017-06-14 14:35 UTC, chris1984 commented
@timogoebel ok thanks, I will keep trying with what you proposed and send in an updated commit for your review and possible help to debug further.

2017-07-10 20:39 UTC, bkearney commented
@chris1984 whats the next step?

2017-07-17 06:45 UTC, chris1984 commented
@timogoebel do you have some more time to help me with this?

2017-08-07 15:30 UTC, timogoebel commented
@chris1984: If you want to continue working on this, please use a different Redmine issue.

2017-08-07 15:33 UTC, chris1984 commented
@timogoebel I noticed you delete this PR from the upstream issue, since you are working on this should I close this one out?

2017-08-07 15:34 UTC, chris1984 commented
@timogoebel ignore i just posted that right after you sent that and the page didnt refresh.... ack will do

2017-08-08 07:01 UTC, Klaas- commented
@chris1984 the upstream bug is not about changing the bootorder, its about not being able to clone images with the bootorder set. The workaround in fog-vsphere doesn't enable changing of bootorder.

2017-08-24 14:19 UTC, closed without merging

2019-03-11 08:41 UTC, Emil-G commented
@chris1984 Was this prematurely closed? https://bugzilla.redhat.com/show_bug.cgi?id=1398317

2019-03-11 11:16 UTC, Klaas- commented
@Emil-G it depends on what you want to achieve; the this PR was abandoned if I recall correctly because the fix for #14160 was achieved differently. Recently there was a restart of the afford to make bootselection possible with vmware #26010 (https://projects.theforeman.org/issues/26010)