Fixes #17588 - Remove 1.16 deprecations
theforeman/foreman pull request #4425
Opened 2017-03-31 15:38 UTC by dLobatog

2017-04-03 07:34 UTC, domcleal requested changes
Please ensure the tests pass.

2017-04-03 07:34 UTC, domcleal commented on app/models/setting.rb
>    rescue NoMethodError
No need to keep this empty method.

2017-04-05 09:21 UTC, dLobatog commented
Tests passing again

2017-04-05 09:23 UTC, domcleal requested changes
There are some more `email.yaml` leftovers - please remove the template file, and entries in `.gitignore` and `config/spring.rb`.

2017-04-05 09:23 UTC, domcleal commented on test/models/settings/email_setting_test.rb
> +    Setting::Email.stubs(:mailconfig).returns({})
This method's being removed, no need to stub it now.

2017-04-05 09:23 UTC, domcleal commented on test/models/settings/email_setting_test.rb
> +  test 'email settings should be editable if email.yaml not exist' do
No need to mention email.yaml here, it's obsolete. (Suggest renaming this test to simply say it tests the output of `delivery_settings` when settings are modified.)

2017-04-18 10:55 UTC, dLobatog commented
Updated- thanks for the review @domcleal

2017-04-18 12:09 UTC, domcleal approved these changes

2017-04-18 12:10 UTC, merged

2017-04-18 12:10 UTC, domcleal commented
Merged, thanks @dLobatog.