Fixes #19151 - progress_report_id fix for host edit
theforeman/foreman pull request #4433
Opened 2017-04-04 10:23 UTC by lzap

The whole orchestration skipping when unattended setting is false is weird. This patch fixes this hot problem, we need to backport this into 1.14 and 1.15.

2017-04-04 10:26 UTC, lzap commented
I think this part needs more refactoring, some our code requires `progress_report` to be always present, this is worth separate refactor ticket.

2017-04-04 10:27 UTC, domcleal submitted a review, later dismissed
There don't appear to be any tests.

2017-04-04 10:27 UTC, domcleal commented on app/models/host/managed.rb
> +    include Orchestration::ProgressReport
There shouldn't be any orchestration modules present in Host::Managed when not using unmanaged mode. The need for these methods should be removed, or it should be in Host::Managed proper, or Host::Base if applicable.

2017-04-04 11:18 UTC, lzap commented
I am not writing any test until we come to agreement. This should do it, it looks like the only appearance is in the edit form, other three are in API but that's not the issue.

2017-09-13 08:29 UTC, dLobatog requested changes
@lzap Is this still happening? I can't recall seeing the error, you just have to create a host with `:unattended => false` to reproduce, or what is it?

2017-09-13 08:29 UTC, dLobatog commented on app/models/host/base.rb
> +    def orchestraded?
typo, orchestrated

2017-10-30 16:05 UTC, lzap commented
@mhulan why have you mentioned this patch? it is still a valid bug, but should not be blocker unless you have turned off unattended...

2017-10-30 16:51 UTC, ares commented
@lzap the release of the redmine issus is set to 1.16 which equals to blocker for 1.16

2017-11-13 06:11 UTC, dLobatog requested changes
@lzap This is basically ready, could you check out the typo and re-submit? Ping me and I'll merge for 1.16 RC3

2017-11-13 13:34 UTC, lzap commented
Done

2017-11-14 07:44 UTC, dLobatog approved these changes

2017-11-14 07:45 UTC, merged

2017-11-14 07:47 UTC, dLobatog commented
Cherry-picked to 1.16-stable as 50b6d64325eaf91e36b393ae6822f7414a57e329