Fixes #19148 - Add description field to subnets
theforeman/foreman pull request #4436
Opened 2017-04-04 13:56 UTC by tbrisker

2017-04-04 14:22 UTC, timogoebel approved these changes
@tbrisker : Thanks. Code looks fine and feature works well! Ready to merge when tests are 💚 .

2017-04-04 14:30 UTC, ohadlevy commented on app/views/subnets/_fields.html.erb
> +<%= text_f f, :description %>
Text area or field?

2017-04-04 14:38 UTC, tbrisker commented on app/views/subnets/_fields.html.erb
> +<%= text_f f, :description %>
right, fixed.

2017-04-04 14:44 UTC, timogoebel commented on app/views/subnets/_fields.html.erb
> +<%= text_f f, :description %>
Oh, I thought that was on purpose. :-)

2017-04-04 15:31 UTC, ares commented
would you mind also opening hammer-cli-foreman PR? Should be similar to https://github.com/theforeman/hammer-cli-foreman/pull/260

2017-04-04 15:34 UTC, ares commented
and last idea - would it make sense to make this available in [ENC output](https://github.com/theforeman/foreman/blob/develop/app/models/subnet.rb#L18)? fair to say no :-)

2017-04-04 15:44 UTC, timogoebel requested changes
@tbrisker : I think, @ares has a point here. Could you please allow safe mode and add this to enc output while you're at it. Can't hurt.

2017-04-05 07:20 UTC, tbrisker commented
@ares @timogoebel Thanks, added to enc and safemode (though not sure there will be much use for it) and created pr for hammer as well

2017-04-05 08:32 UTC, timogoebel commented
@tbrisker : One thing I found:

![image](https://cloud.githubusercontent.com/assets/4107560/24696638/671d215e-19ea-11e7-95c1-b3a92d2f7a6c.png)

But I think, this is unrelated to this PR.

2017-04-05 08:32 UTC, timogoebel approved these changes
@tbrisker : Thanks, looks good.

2017-04-05 08:47 UTC, tbrisker commented
@timogoebel is that after you stretched it or is that how it loaded for you?

2017-04-05 08:50 UTC, timogoebel commented
@tbrisker: It's after I changed the size. It looks good when the page loads.

2017-04-05 10:06 UTC, ares approved these changes
Thanks, I have no more comments :+1:

2017-04-05 10:39 UTC, merged