Fixes #16839 - sort by origin is possible
theforeman/foreman pull request #4445
Opened 2017-04-09 12:29 UTC by lizagilman

2017-04-09 12:35 UTC, tbrisker commented
add to PR whitelist

2017-04-09 18:34 UTC, ohadlevy commented on test/factories/facts_related.rb
> +    type 'PuppetFactName'
@lizagilman I would suggest to try without this line, as it turns out break many other tests.

2017-04-17 09:49 UTC, dLobatog requested changes
Works fairly well, thanks @lizagilman - I left a couple of comments about the scoped_search options.

2017-04-17 09:49 UTC, dLobatog commented on app/controllers/fact_values_controller.rb
> -    rescue => e
In my opinion this error handling removal is OK - it's from 2011 and I'd prefer not to hide potential exceptions

2017-04-17 09:49 UTC, dLobatog commented on app/models/fact_value.rb
> +  scoped_search :relation => :fact_name, :on => :type, :complete_value => false, :only_explicit => true, :aliases => ["origin"]
Why `complete_value` is false? There are only 3 or 4 options in a typical installation, which makes it a good candidate for autocompletion IMO. Same for `only_explicit`, why?

2017-04-17 10:22 UTC, ohadlevy commented on app/models/fact_value.rb
> +  scoped_search :relation => :fact_name, :on => :type, :complete_value => false, :only_explicit => true, :aliases => ["origin"]
The type field value is not user friendly, the initial bug was with sort, fixing the search imho is out of scope for this pr?

2017-04-17 10:58 UTC, dLobatog commented on app/models/fact_value.rb
> +  scoped_search :relation => :fact_name, :on => :type, :complete_value => false, :only_explicit => true, :aliases => ["origin"]
Oh I see it now - "type = ForemanAnsible::FactName" is definitely bad... this is a good candidate for `ext_method` though.

2017-04-17 10:58 UTC, dLobatog approved these changes

2017-04-17 10:59 UTC, dLobatog commented
Merging after seeing the type values are things like "ForemanAnsible::FactName" - which shouldn't be displayed to the user. This should use `ext_method` or something similar to avoid this problem.

2017-04-17 10:59 UTC, merged

2017-04-17 10:59 UTC, dLobatog commented
Thanks @lizagilman @ohadlevy