Fixes #17568 - create compute-resource VMware - URL optional
theforeman/foreman pull request #4461
Opened 2017-04-18 09:05 UTC by swapab

Server-side validation for https://github.com/theforeman/hammer-cli-foreman/pull/272

2017-04-19 11:56 UTC, timogoebel commented
@swapab : Please create a Foreman issue for this and link to it in the commit message. Thanks.

2017-04-19 11:58 UTC, timogoebel requested changes

2017-04-19 11:58 UTC, timogoebel commented on app/models/compute_resource.rb
> +    %w(libvirt ovirt openstack rackspace)
Can we make this an option of the Model-class, e.g. `Foreman::Model::Ovirt`? It would be easier for plugins to change this.

2017-04-20 12:25 UTC, lzap commented on app/models/compute_resource.rb
> +    %w(libvirt ovirt openstack rackspace)
Frankly I'd squash this with `is_eligible_for_url?` method, unless you have specific reason to have it like that.

2017-04-20 12:29 UTC, timogoebel commented on app/models/compute_resource.rb
> +    %w(libvirt ovirt openstack rackspace)
Yeah, or that if we want to keep it simple.
How about adding `validates :url, :presence => true` to each Foreman::Model class that needs the validation? I think, that's even better than to filter in the superclass?

2017-04-21 06:48 UTC, swapab commented on app/models/compute_resource.rb
> +    %w(libvirt ovirt openstack rackspace)
@lzap I originally introduced `providers_url_mandatory` to be able to override it in other plugins(example: https://github.com/theforeman/foreman-docker/pull/190)
I had thought of doing it the way @timogoebel suggested https://github.com/theforeman/foreman/pull/4461#discussion_r112439805.

But right now I am trying to find an answer for @domcleal's question: http://projects.theforeman.org/issues/19326#note-2
Do you guys see any reason for making `url` as required attribute for VMware?

---
I prefer to keep url validation per model, will do the change.

2017-07-27 12:12 UTC, swapab commented
@timogoebel I have updated the PR to validate `url` in respective compute-resources.
Parallel docker PR: https://github.com/theforeman/foreman-docker/pull/198

Not able to understand why the **upgrade** build is failing.
The console output is not of much help: http://ci.theforeman.org/job/test_develop_pr_upgrade/3433/console

2017-07-31 13:46 UTC, timogoebel requested changes
@swapab: Thanks. I left some inline comments.

2017-07-31 13:46 UTC, timogoebel commented on bundler.d/foreman_docker.rb
> +gemspec :path => '../foreman-docker'
Please remove this.

2017-07-31 13:46 UTC, timogoebel commented on test/factories/compute_resources.rb
> -      sequence(:url) { |n| "#{n}.example.com" } # alias for server
Why is this necessary? It looks like a good default to me. You cannot use `sequence(:server)` as FactoryGirl doesn't allow you to use an aliased method.

2017-07-31 13:46 UTC, timogoebel commented on test/models/compute_resources/libvirt_test.rb
> +      assert libvirt_cr.valid?, 'LibVirt compute resource expected to be valid'
You can use `assert_valid`.

2017-07-31 13:46 UTC, timogoebel commented on test/models/compute_resource_test.rb
> +    cr = FactoryGirl.build(:vmware_cr)
Could you check that instead the `server` attribute is required and a error message is added for `server`. Maybe `shoulda-matchers` help to reduce the boilerplate.

2017-08-01 11:00 UTC, swapab commented on test/factories/compute_resources.rb
> -      sequence(:url) { |n| "#{n}.example.com" } # alias for server
Done. Restored sequence.

2017-08-01 11:00 UTC, swapab commented on test/models/compute_resources/libvirt_test.rb
> +      assert libvirt_cr.valid?, 'LibVirt compute resource expected to be valid'
Done. Thanks.

2017-08-01 11:01 UTC, swapab commented on test/models/compute_resource_test.rb
> +    cr = FactoryGirl.build(:vmware_cr)
Yes makes sense. Moved the test cases to model tests `vmware_test.rb`

2017-08-01 13:28 UTC, timogoebel requested changes

2017-08-01 13:28 UTC, timogoebel commented on test/factories/compute_resources.rb
> -      sequence(:url) { |n| "#{n}.example.com" } # alias for server
As written above, you cannot use `sequence(:server)` here as FactoryGirl doesn't allow you to use an aliased method. Please use `sequence(:url)` and restore the comment.

2017-08-01 17:12 UTC, swapab commented on test/factories/compute_resources.rb
> -      sequence(:url) { |n| "#{n}.example.com" } # alias for server
Oops. I misread it. Fixed.

2017-08-02 07:16 UTC, timogoebel requested changes
@swapab: Thanks. I left some more comments inline. Could you please take another look? Then we're ready to 🚢 .

2017-08-02 07:16 UTC, timogoebel commented on test/factories/compute_resources.rb
> -      sequence(:url) { |n| "#{n}.example.com" } # alias for server
Could you please also restore the comment?
```
sequence(:url) { |n| "#{n}.example.com" } # alias for server
```

2017-08-02 07:16 UTC, timogoebel commented on test/models/compute_resources/ovirt_test.rb
> +    test 'valid if url is present' do
Can we use shoulda matchers to check this to reduce boilerplate?
Please also add a test for the URL regex. Shoulda matchers should be fine.

```ruby
should allow_values('http://foo.com', 'http://bar.com/baz').
    for(:url)

should_not allow_values('http://foo.com', 'buz').
    for(:url)
```

In addition, i think it's safe to add `https://github.com/theforeman/foreman/blob/develop/app/validators/url_schema_validator.rb` and limit the allowed schemes to http and https.

```
validates :url, :url_schema => ['http', 'https']
```

Please add tests (shoulda matchers) for this, too. Positive and Negative should be fine.

2017-08-02 10:22 UTC, swapab commented on test/models/compute_resources/ovirt_test.rb
> +    test 'valid if url is present' do
`:url_schema => ['http', 'https']` should be only applicable for ovirt? Or should be applied for rackspace, openstack as well?

2017-08-02 11:47 UTC, timogoebel commented on test/models/compute_resources/ovirt_test.rb
> +    test 'valid if url is present' do
i definitely know, that vmware is either http or http. I don't know for the others for sure.

2017-08-02 14:02 UTC, swapab commented on test/models/compute_resources/ovirt_test.rb
> +    test 'valid if url is present' do
Okay, I have added `url_schema` for VMware as well. And have asked on IRC for some help to know about other CRs.

2017-08-03 07:29 UTC, timogoebel requested changes

2017-08-03 07:29 UTC, timogoebel commented on test/models/compute_resources/ec2_test.rb
> +      describe 'validate' do
I beleive, this can also be replaces by
```ruby
should validate_presence_of(:url)
```

Ditto for libvirt & rackspace.

2017-08-03 13:11 UTC, swapab commented on test/models/compute_resources/ec2_test.rb
> +      describe 'validate' do
Thanks. Done.

2017-08-14 08:54 UTC, timogoebel requested changes
@swapab: Sorry, I asked you to add a wrong validation to VMWare. If you could remove that, I think we're ready to 🚢 .

2017-08-14 08:54 UTC, timogoebel commented on app/models/compute_resources/foreman/model/vmware.rb
> +              :url_schema => ['http', 'https']
Sorry for misleading you here, VMWare should /not/ have the `url_schema` validated. My mistake. Could you remove that please?

2017-08-14 08:54 UTC, timogoebel commented on test/models/compute_resources/vmware_test.rb
> +  should_not allow_values('ftp://foo.com', 'buz').for(:server)
Please also remove these tests. Sorry again.

2017-08-14 09:27 UTC, swapab commented on app/models/compute_resources/foreman/model/vmware.rb
> +              :url_schema => ['http', 'https']
No problem :smile: 
I have updated the PR accordingly

2017-08-14 09:28 UTC, swapab commented on app/models/compute_resources/foreman/model/vmware.rb
> +              :url_schema => ['http', 'https']
Q. Should I also remove the `format` ?

2017-08-14 09:40 UTC, timogoebel commented on app/models/compute_resources/foreman/model/vmware.rb
> +              :url_schema => ['http', 'https']
@swapab : Yes, please. Basically we want to support simple hostnames. "vcenter.example.com". Extra points for adding a test for that.

```
should allow_values('vcenter.example.com', 'vcenter').for(:server)
```

2017-08-14 09:51 UTC, swapab commented on app/models/compute_resources/foreman/model/vmware.rb
> +              :url_schema => ['http', 'https']
Thanks. Done.

2017-08-14 10:23 UTC, timogoebel commented
[test katello]

2017-08-14 11:30 UTC, timogoebel commented
@swapab : Could you please rebase the PR? This might fix the failing tests. Thanks.

2017-08-15 14:22 UTC, timogoebel approved these changes

2017-08-15 14:28 UTC, merged

2017-08-15 14:28 UTC, timogoebel commented
Merged, thanks @swapab.