Fixes #19295 - use new DHCP API
theforeman/foreman pull request #4462
Opened 2017-04-18 12:30 UTC by ares

2017-04-18 12:54 UTC, timogoebel approved these changes
Code looks good to me, thanks @ares!

2017-04-18 15:31 UTC, dLobatog requested changes
@ares 👍 to me - can you double check the 404 thing? Thanks for fixing this

2017-04-18 15:31 UTC, dLobatog commented on lib/proxy_api/dhcp.rb
>      rescue RestClient::ResourceNotFound
Seems like this rescue would never be reached under normal conditions, 404s are ignored and treated like "OK, it's deleted anyway" 

https://github.com/theforeman/smart-proxy/blob/develop/modules/dhcp/dhcp_api.rb#L139

2017-04-19 07:37 UTC, timogoebel commented on lib/proxy_api/dhcp.rb
>      rescue RestClient::ResourceNotFound
Yes. Good catch, that did change between the old and new API.

2017-04-19 07:45 UTC, ares commented on lib/proxy_api/dhcp.rb
>      rescue RestClient::ResourceNotFound
right, I removed the rescue

2017-04-19 14:18 UTC, dLobatog approved these changes

2017-04-19 14:19 UTC, merged

2017-04-19 14:19 UTC, dLobatog commented
Thanks @ares , @timogoebel !