Refs #19309 - Test for 'select all hosts' for 1 page
theforeman/foreman pull request #4473
Opened 2017-04-20 13:11 UTC by dLobatog

2017-04-20 14:44 UTC, domcleal requested changes
I think the (integration) test stops short of full coverage, it's more of a unit test by only checking internal state and may be invalidated by internal refactoring - which shouldn't be the case for an integration test.

It probably needs to perform an action and ensure all of the hosts are modified.

2017-04-20 14:44 UTC, domcleal commented on test/integration/host_js_test.rb
> +  #extend Minitest::OptionalRetry
Why's this commented?

2017-04-20 14:44 UTC, domcleal commented on test/integration/host_js_test.rb
> +      #page.find('#check_all').trigger('click')
ditto, and why is this changed?

2017-04-20 14:44 UTC, domcleal commented on test/integration/host_js_test.rb
> -
Unrelated?

2017-04-20 14:44 UTC, domcleal commented on test/integration/host_js_test.rb
> +      Setting[:entries_per_page] = 20
Superfluous, the database should be reset after each test.

2017-04-20 14:44 UTC, domcleal commented on test/integration/host_js_test.rb
> +      # Multiple is false when we have not clicked "select all"
True or false? The assertion below checks whether it's true, and later it seems to be false.

2018-04-01 20:23 UTC, mmoll commented
what's the status here?

2018-10-02 01:23 UTC, closed without merging