Fixes #19305 - fixing spacing issue on facts page
theforeman/foreman pull request #4479
Opened 2017-04-23 11:43 UTC by lizagilman

fixing design issues that came up from #4463

2017-04-23 12:11 UTC, lizagilman commented
[test upgrade]

2017-04-23 13:53 UTC, tbrisker commented
Foreman test failures (`ChildFactValueIntegrationTest.test_0001_parent name links to child list`) seems related, please take a look.

2017-04-24 11:42 UTC, lizagilman commented
updated

2017-04-24 13:50 UTC, lizagilman commented
[test foreman]

2017-04-27 06:45 UTC, lizagilman commented
[test katello]

2017-05-15 11:12 UTC, tbrisker commented
Looks like when going into one of the child facts the breadcrumbs disappear?
![image](https://cloud.githubusercontent.com/assets/1540531/26055197/5db1b802-3978-11e7-9a08-cf51a5fef67d.png)

2017-07-30 07:42 UTC, lizagilman commented
updated, @tbrisker can you re-review?

2017-07-31 09:48 UTC, timogoebel requested changes
@lizagilman: Thanks. I left some small comments inline.

Looks good with #4495.
![image](https://user-images.githubusercontent.com/4107560/28772306-139b2f8c-75e6-11e7-98c6-620fc53f474f.png)

2017-07-31 09:48 UTC, timogoebel commented on app/helpers/fact_values_helper.rb
> +    if parent.present? && h(parent.name) == memo
This can be simplified with a guard clause as `return current_name if parent.present? && h(parent.name) == memo`. The else can be removed then.

2017-07-31 09:48 UTC, timogoebel commented on app/views/fact_values/_fact.html.erb
> +        <%= content_tag(:ol, fact_name(fact, parent), :class => "breadcrumb") %>
Indentation is off.

2017-07-31 11:48 UTC, lizagilman commented
@timogoebel thanks, updated

2017-07-31 13:14 UTC, timogoebel approved these changes

2017-07-31 13:16 UTC, merged

2017-07-31 13:16 UTC, timogoebel commented
Merged, thanks @lizagilman.