Fixes #19417 - Safely check params for nested keys
theforeman/foreman pull request #4491
Opened 2017-04-27 17:26 UTC by tbrisker

2017-04-28 08:24 UTC, domcleal requested changes
Thanks, could you please add a test to `test/unit/concerns/parameters/keep_param_test.rb`?

2017-04-28 08:24 UTC, domcleal commented on app/controllers/concerns/foreman/controller/parameters/keep_param.rb
> +      if params[top_level_hash].try(:has_key?, key)
Nitpick, prefer `try!`.

2017-04-30 15:37 UTC, tbrisker commented
@domcleal - Fixed and added test.

2017-05-02 07:30 UTC, domcleal approved these changes

2017-05-02 07:30 UTC, merged

2017-05-02 07:30 UTC, domcleal commented
Merged, thanks @tbrisker.