Fixes #19372 - replace children fact values icon
theforeman/foreman pull request #4495
Opened 2017-04-30 06:48 UTC by lizagilman

before: 
![plus_icon](https://cloud.githubusercontent.com/assets/15361156/25562273/cab26398-2d89-11e7-9b31-1cdf4f5c7aaa.png)

after:
![zoom_in](https://cloud.githubusercontent.com/assets/15361156/25562276/d86269f2-2d89-11e7-9523-b7c5c1607b8e.png)

@Rohoover what do you think?

2017-04-30 07:39 UTC, ohadlevy commented
thanks @lizagilman - @rohoover is that the icon you had in mind?

2017-05-02 09:32 UTC, timogoebel commented
Just for the record: I think the plus sign is more suitable for an expand action then a zoom-in icon. I associate the zoom-in icon with a zoom-in action, e.g. in an image.
How about `fa-angle-down` in Patternfly's [TreeGrid Table](http://www.patternfly.org/pattern-library/widgets/#treegrid-table) or [Fixed Height Accordion](http://www.patternfly.org/pattern-library/widgets/#fixed-height-accordion)?

2017-05-03 08:45 UTC, lizagilman commented
I think TreeGrid Table may be the right thing here

2017-05-08 14:12 UTC, Rohoover commented
@timogoebel is correct. Zoom should be used to zoom in, either a chevron icon or the tree grid table /accordion would be better for expansion.

2017-05-21 09:51 UTC, ohadlevy commented
@lizagilman ping?

2017-07-26 12:38 UTC, dLobatog submitted a review, later dismissed
Setting to WoC as per @Rohoover & @timogoebel comment - most likely no change is needed

2017-07-27 07:30 UTC, lizagilman commented
[test foreman]

2017-07-28 08:28 UTC, timogoebel requested changes
@lizagilman : I found a small typo. If this is fixed, we can get this in. Thanks.

2017-07-28 08:28 UTC, timogoebel commented on app/helpers/fact_values_helper.rb
> +      link_to(icon_text('angle-down','', :kind => 'fa',:title => _('Expand nested items')), url) + ' ' + content_tag(:span, name)   else
The `else` should be on a separate line.

2017-07-28 10:02 UTC, lizagilman commented
@timogoebel updated, thanks

2017-07-31 09:25 UTC, timogoebel requested changes
@lizagilman : Sorry for yet another comment, but there is a line break after the icon. I think, we should get rid of it.
![image](https://user-images.githubusercontent.com/4107560/28771395-f0c0a6de-75e2-11e7-86bb-49fc1002717b.png)

2017-07-31 09:37 UTC, lizagilman commented
@timogoebel I think this is related to #4479 
Once both of this PRs be merged the page should look ok

2017-07-31 09:51 UTC, timogoebel commented
@lizagilman : Yep. You are right. I tested this with the other patch applied, too. Works great.
Let's merge the other patch first and then rebase this on top.

2017-07-31 09:51 UTC, timogoebel approved these changes

2017-07-31 13:17 UTC, timogoebel commented
@lizagilman : Would you mind rebasing this?

2017-07-31 14:28 UTC, lizagilman commented
@timogoebel : rebased

2017-08-01 07:19 UTC, timogoebel requested changes
@lizagilman: Thanks. Looks good. One more nitpick and this is ready.

2017-08-01 07:19 UTC, timogoebel commented on app/helpers/fact_values_helper.rb
> +      link_to(icon_text('angle-down','', :kind => 'fa',:title => _('Expand nested items')), url) + ' ' + content_tag(:span, name)
Nitpick: Could you please add some spaces between commas?

```
link_to(icon_text('angle-down', '', :kind => 'fa', :title => _('Expand nested items')), url) + ' ' + content_tag(:span, name)
```

2017-08-01 09:54 UTC, lizagilman commented
@timogoebel updated

2017-08-01 09:56 UTC, timogoebel approved these changes

2017-08-01 09:56 UTC, timogoebel commented
Thanks. 👍  if tests pass.

2017-08-01 11:22 UTC, merged

2017-08-01 11:23 UTC, timogoebel commented
Merged, thanks @lizagilman. Good job.