Fixes #19436 - Better controller selection on host dropdown
theforeman/foreman pull request #4498
Opened 2017-05-03 10:23 UTC by tbrisker

Always setting to `host` unless the controller is `hostgroup` broke
discovery's usage of the form as it uses the `discoverd_host`
controller.

2017-05-03 11:27 UTC, timogoebel commented
@tbrisker : Somehow I don't like the approach either. I'm curious if we can find a way that generates the correct url based on the same criteria for
a) the form action
b) the ajax data

2017-05-03 12:14 UTC, tbrisker commented
Since some of the dropdowns were using `method_path` while others had `host_or_hostgroup_path`, I reverted the change to `host_or_hostgroup_path` from 637da2f and moved the controller correction to the `method_path` method. Another option would be to override this method only in the compute_resource_vms controller.
While I agree this is a bit of a hack and would be happy to clean up the host form, this bug is a regression introduced in 1.15 which breaks discovery.

2017-05-03 12:42 UTC, timogoebel commented
@tbrisker: 👍  for 1.15 and 👍 for agreeing, that this isn't great and needs more work for 1.16.

2017-05-05 11:37 UTC, dLobatog commented
Thanks @tbrisker , setting back to WoC as it's failing tests. [test katello] (I'm not so sure katello failures happened after this)

2017-05-05 11:39 UTC, dLobatog requested changes
Looks like architecture_selected_hosts_path isn't working

2017-05-05 12:50 UTC, lzap commented
@dLobatog does 1.15 mean RCx or 1.15.1?

2017-05-07 12:50 UTC, tbrisker commented
@dLobatog - thanks, I had a typo. fixed now.
@lzap - I believe this is a 1.15.0 blocker.

2017-05-08 08:28 UTC, dLobatog approved these changes

2017-05-08 08:29 UTC, dLobatog commented
[test upgrade]  - @tbrisker MySQL upgrade job failed, I will retry and merge if green

2017-05-08 08:50 UTC, merged

2017-05-08 08:50 UTC, dLobatog commented
Thanks @tbrisker !