Require fog subprojects instead of fog
theforeman/foreman pull request #4501
Opened 2017-05-03 19:51 UTC by icco

In response to https://github.com/fog/fog-google/issues/158, update your fog dependency to include modern versions of fog.

2017-05-04 08:23 UTC, domcleal requested changes
The `fog` dependency is required for oVirt, Docker, and possibly OpenNebula support, which aren't available in a separate fog-* gem, so I don't think this dependency can simply be removed currently.

2017-05-04 08:23 UTC, domcleal commented on bundler.d/fog.rb
> +  gem 'fog-aws', '1.3.0', :require => false
This is already in `bundler.d/ec2.rb`.

2017-05-04 08:23 UTC, domcleal commented on bundler.d/fog.rb
> +  gem 'fog-google', '0.5.2', :require => false
Already in `gce.rb`, would be changed there.

2017-05-14 11:36 UTC, mmoll commented
I guess the first step for now would be to only update the fog gem(s) used in Foreman core. Regarding the single providers, I would hope that some @theforeman and @manageiq people could maintain a split-out fog-ovirt, while somebody from @netways could take over a split-out fog-one...

2017-05-14 20:24 UTC, icco commented
@mmoll The discussion on that work is at https://github.com/fog/fog/issues/3942 if you'd like to speed that along. Until that work is done, I'll close this PR.

2017-05-14 20:24 UTC, closed without merging