Fixes #19459 - move vm ready to compute_resource for easy override
theforeman/foreman pull request #4502
Opened 2017-05-04 11:02 UTC by martin-ducar-gd

To be able to override the wait for vm ready we need to move
it to compute resource definition. Also improve Openstack one

2017-05-04 11:54 UTC, timogoebel commented
@theforeman-bot ok to test

2017-05-04 14:57 UTC, martin-ducar-gd commented
The failure looks unrelated to change if I'm not mistaken

2017-05-11 07:04 UTC, timogoebel requested changes
@martin-ducar-gd : Thanks for your PR and sorry for the delay. This definitely helps a lot with debugging deployment issues.

2017-05-11 07:04 UTC, timogoebel commented on app/models/compute_resources/foreman/model/openstack.rb
> +      raise "Failed to deploy vm %{name}, fault: %{e}" % { :name => vm.name, :e => vm.fault } if vm.failed?
Please use 

```
raise Foreman::Exception.new(N_("Failed to deploy vm %{name}, fault: %{e}"), { :name => vm.name, :e => vm.fault })
```

This generates an [ERF-Code](http://projects.theforeman.org/projects/foreman/wiki/ErrorCodes) that helps with troubleshooting.

2017-05-11 07:04 UTC, timogoebel commented on app/models/compute_resources/foreman/model/openstack.rb
> +      raise "Failed to deploy vm %{name}, fault: %{e}" % { :name => vm.name, :e => vm.fault } if vm.failed?
In addition, why not use vm.fault['message'] to display only the error message and not the http status code and timestamp?

2017-05-18 12:31 UTC, martin-ducar-gd commented
@timogoebel sorry for the delay I was on vacation, I implemented hopefully all your comments

2017-05-18 12:48 UTC, martin-ducar-gd commented
@timogoebel sorry for the delay I was on vacation, I implemented hopefully all your comments

2017-05-18 21:26 UTC, chris1984 commented
@theforeman-bot ok to test

2017-05-18 21:27 UTC, chris1984 approved these changes

2017-05-18 21:27 UTC, chris1984 commented
@timogoebel kicked off tests again since katello-pipeline is green. croberts on irc

2017-05-19 04:00 UTC, martin-ducar-gd commented
@chris1984 should i rebase again?  Because the failures again look unrelated.

2017-05-22 12:41 UTC, tbrisker commented
I confirm, test failures are unrelated. @timogoebel any further comments or can we merge?

2017-05-22 12:43 UTC, timogoebel commented
@tbrisker: I haven't manually tested the new version. It looks ok to me, though and I don't have any additional comments.

2017-05-22 13:20 UTC, tbrisker commented
LGTM, pending testing by @timogoebel

2017-05-28 17:23 UTC, timogoebel commented
Works nicely, thanks @martin-ducar-gd.

![image](https://cloud.githubusercontent.com/assets/4107560/26530728/cd12e574-43da-11e7-84b6-cb0ccd42c154.png)

2017-05-28 17:35 UTC, merged

2017-05-28 17:35 UTC, timogoebel commented
Merged, thanks @martin-ducar-gd and @tbrisker.

2017-05-28 17:38 UTC, martin-ducar-gd commented
Thank you too @timogoebel @tbrisker