Fixes #17771 - Test if rsync successfully uploaded tarball
theforeman/foreman pull request #4505
Opened 2017-05-05 01:51 UTC by gnurag

This PR checks if rsync executed successfully and only then it prints a success message, along with http url for the uploaded foreman-debug archive.

Upon failure, I've also added a suggestion to upload to an alternate location. Let me know if this suggestion is reasonable, or else I'll remove it.

2017-05-05 08:11 UTC, domcleal requested changes
The exit code appears to be `0` on error, please change this so it's non-zero when the upload fails.

2017-05-05 14:13 UTC, gnurag commented
Thanks, what would be an appropriate exit code? 1, 2 seem reserved. Perhaps 69?

`#define EX_USAGE        64      /* command line usage error */`

2017-05-05 14:34 UTC, domcleal commented
I don't see how you get from 1, 2 to 69. The next logical choice would probably be 3. Either way, please make a choice (with justification if necessary) and update the PR for review.

2017-05-08 11:58 UTC, timogoebel commented
@domcleal : PR has been updated.

2017-05-08 11:58 UTC, gnurag commented
@domcleal Added `exit 3`; please re-review.

2017-05-08 13:21 UTC, domcleal approved these changes

2017-05-08 13:22 UTC, domcleal commented
@theforeman-bot ok to test

2017-05-08 14:26 UTC, merged

2017-05-08 14:26 UTC, domcleal commented
Merged, thanks @gnurag.