Fixes #19173 - build notification succeeds with expired token.
theforeman/foreman pull request #4508
Opened 2017-05-05 11:35 UTC by witlessbird

2017-05-05 13:57 UTC, witlessbird commented
Test failure is a js test timing out on a connection to /organizations.

2017-05-08 13:42 UTC, timogoebel commented
@witlessbird : Thanks. Is this really a good idea? If a token is expired, it should be expired, invalid and useless. Is there any real-world scenario, where this is necessary if everything else is set up correctly?

2017-05-08 14:00 UTC, witlessbird commented
@timogoebel: This is an attempt to fix an issue someone experienced irl (token expired after provisioning started, leading to it being forever stuck in build mode). I couldn't think of a better way to fix this; fwiw the change only allows the host to call "/build" and nothing else.

2017-05-09 07:09 UTC, timogoebel commented on app/controllers/unattended_controller.rb
> +    unless a_host
How about extracting this to something like

```ruby
def host_value_present?(a_host, value, N_("%{controller}: unable to find a host that matches the request from %{addr}"))
  unless value
     [...]
  end
end

2017-05-09 07:11 UTC, timogoebel commented
@witlessbird : Thanks. Fair enough. I did experience something like this myself. However usually when something else was wrong. The host then stays in an install loop. Fun experience. From a user's perspective, this is probably a valid RFE.

2017-05-09 09:28 UTC, witlessbird commented
- extracted value presence check into a separate method.

2017-05-11 06:44 UTC, timogoebel requested changes
@witlessbird : Thanks. I tested this manually. Works great. There is just one nitpick that needs fixing before merge.

2017-05-11 06:44 UTC, timogoebel commented on app/controllers/unattended_controller.rb
> +    return token
superfluous return

2017-05-11 09:04 UTC, witlessbird commented
* removed a redundant "return" keyword in UnattendedController#token_from_params method.

2017-05-11 11:29 UTC, timogoebel approved these changes
Test failure is unrelated (JS test).

2017-05-11 11:29 UTC, merged

2017-05-11 11:30 UTC, timogoebel commented
Merged, thanks @witlessbird.