fixes #19479, #10587 notifications now works with two-pane again
theforeman/foreman pull request #4513
Opened 2017-05-09 08:33 UTC by ohadlevy

- notification is now inside the content div, allowing two-pane server
responses to include it.
- refactored all notifications to use notification helpers (notice,
warning and error) instead of direct flash manipulation
- also added the usage of flash now via the helpers, and fixed
it in a couple of places it was used incorrectly (mostly clone rendering
which does not redirect at all).
- fixed consisteny to remove trailing dots from toast messages (as it
seems most strings are without dot suffix).

2017-05-09 13:05 UTC, tbrisker approved these changes
Looks good, lets see that tests pass.

2017-05-09 13:18 UTC, tbrisker commented
@ohadlevy looks like one test is failing, could you take a look?

2017-05-09 13:36 UTC, ohadlevy commented
@tbrisker fixed failing test, I actually changed a notice alert to warning, hence the failure. thanks

2017-05-09 13:37 UTC, ohadlevy commented on app/controllers/users_controller.rb
> +      warning _("You cannot delete this user while logged in as this user")
this was changed from notice to warning level.

2017-05-09 16:56 UTC, tbrisker requested changes
Integration tests are still failing.

2017-05-09 16:56 UTC, tbrisker commented on webpack/assets/javascripts/foreman_toast_notifications.js
> +  notifications.data().flash.forEach(([type, message]) => {
This seems to fail when there is no flash data, which occurs in some of the tests.

2017-05-09 19:38 UTC, johnpmitsch commented
This fixes http://projects.theforeman.org/issues/19500 for me

2017-05-09 19:41 UTC, ohadlevy commented
@tbrisker updated.

2017-05-09 20:50 UTC, ohadlevy commented
@tbrisker test failure unrelated.

2017-05-09 21:01 UTC, tbrisker commented on webpack/assets/javascripts/foreman_toast_notifications.js
> +    !notifications.data().flash) {return;}
you can safely combine these two checks to `!notifications.data('flash')` (also works for looping below)

2017-05-09 21:22 UTC, ohadlevy commented
If I read the error on http://projects.theforeman.org/issues/19500#change-86746 correctly, it seems that .data was undefined?

2017-05-09 21:23 UTC, ohadlevy commented
Oh I see, tomorrow than :)

2017-05-10 05:41 UTC, ohadlevy commented
@tbrisker updated.

2017-05-10 07:26 UTC, ohadlevy commented
tests failures seem unrelated?

2017-05-10 08:25 UTC, tbrisker approved these changes

2017-05-10 08:25 UTC, merged

2017-05-10 08:25 UTC, tbrisker commented
Thanks @ohadlevy !