Fixes #17749 - Remove confusing .gz.txt extension from logs
theforeman/foreman pull request #4515
Opened 2017-05-09 11:34 UTC by gnurag

Currently .txt extension is appended to log files that are processed
by foreman-debug and added to the debug archive. This is confusing to
the user.

This PR gets rid of the .txt extension, and also removes .gz/.bz2/xz
extension from log files that have been uncompressed.

2017-05-11 10:01 UTC, lzap requested changes
Nice thanks for taking care of these small annoying things. I'd suggest to use shell builtin.

2017-05-11 10:01 UTC, lzap commented on script/foreman-debug
> +          OUTFILE=$(echo "$FILE" | sed s/.gz$//)
Bash allows you to replace strings in variables, it's built in feature. Why not to use that.

http://stackoverflow.com/questions/13210880/replace-one-substring-for-another-string-in-shell-script

2017-05-11 10:01 UTC, lzap commented on script/foreman-debug
> +          touch -c -r "$FILE" "$DIR$OUTFILE"
I think you can merge $DIR and $OUTFILE into single variable, can you?

2017-05-15 12:57 UTC, gnurag commented on script/foreman-debug
> +          OUTFILE=$(echo "$FILE" | sed s/.gz$//)
@lzap Thanks, tried % flag to match .gz at the end of the line and it worked great. Updating the PR.

2017-05-15 12:58 UTC, gnurag commented on script/foreman-debug
> +          touch -c -r "$FILE" "$DIR$OUTFILE"
@lzap Tried to merge `$DIR$FILE` into a single var, please see if it looks okay.

2017-05-15 13:02 UTC, gnurag commented
@lzap tried the builtin bash variable substitution syntax. please re-review.

2017-05-17 14:59 UTC, lzap approved these changes

2017-05-17 14:59 UTC, lzap commented
Well done, works great.

2017-05-17 14:59 UTC, merged