Fixes #19582 - Alert when puppetclass is not saved due to error
theforeman/foreman pull request #4534
Opened 2017-05-18 07:08 UTC by orrabin

Getting an error from a smart class parameter or smart variable that was not edited and prevents saving is confusing.
This alert is to make sure it's clear the puppet class will not be saved if there are any errors in any of it's parameters/variables.

2017-05-18 07:08 UTC, orrabin commented on app/views/puppetclasses/_form.html.erb
> +  <% unless @puppetclass.errors.empty? %>
should this be only for errors on parameters/variables?

2017-05-18 07:13 UTC, orrabin commented
@Rohoover is this the correct place and wording of the inline notification?

![image](https://cloud.githubusercontent.com/assets/7894647/26190414/168f798c-3bb2-11e7-8404-adc580f7696f.png)

2017-05-18 16:26 UTC, Rohoover commented
@orrabin 
Can the error occur on any of the tabs? Or is it specifically in the Smart Variable Tab?

2017-05-21 07:46 UTC, orrabin commented
> Can the error occur on any of the tabs? Or is it specifically in the Smart Variable Tab?

@Rohoover any of the tabs

2017-05-22 11:53 UTC, Rohoover commented
@orrabin 

So I think the position is correct because the error affects the whole page.

2017-05-24 18:04 UTC, ShimShtein reviewed
@ohadlevy, you did some work with error notifications, should it affect this message in some way?

2017-05-24 18:04 UTC, ShimShtein commented on app/views/puppetclasses/_form.html.erb
> +    <%= alert :class => 'alert-danger', :header => '', :text => _("The puppet class has not been saved because of an existing error in the class or one of it's parameters.") %>
nitpick: IMHO, it should be either `"Puppet class has not..."` or `"The class has not..."`.

2017-05-29 07:25 UTC, orrabin commented
@ShimShtein thanks, I fixed the wording.

2017-05-29 07:29 UTC, tbrisker commented on app/views/puppetclasses/_form.html.erb
> +    <%= alert :class => 'alert-danger', :header => '', :text => _("The class has not been saved because of an existing error in the class or one of it's parameters.") %>
nitpick: its not it's, also I would drop the word "existing"

2017-05-29 13:51 UTC, dLobatog requested changes
Set to WOC as per @tbrisker 's comment about the typo, I haven't tried it but it looks fine

2017-06-05 08:09 UTC, orrabin commented
@tbrisker thanks, I fixed the typo.

2017-06-05 08:24 UTC, tbrisker commented on app/views/puppetclasses/_form.html.erb
> +  <% unless @puppetclass.errors.empty? %>
I don't think there can be any error in the class itself, so if there is any error it has to be in the parameters/variables.

2017-06-05 08:24 UTC, tbrisker commented on app/views/puppetclasses/_form.html.erb
> +    <%= alert :class => 'alert-danger', :header => '', :text => _("The class has not been saved because of an error in the class or one of its parameters.") %>
could you reword this to `The class could not be saved because of an error in one of the class parameters.`?

2017-06-05 12:51 UTC, tbrisker approved these changes

2017-06-05 12:52 UTC, merged

2017-06-05 12:52 UTC, tbrisker commented
Thanks @orrabin !