Fixes #19315 - redirect to login  when session expired
theforeman/foreman pull request #4547
Opened 2017-05-22 08:19 UTC by amirfefer

When a session expired, the page remains on browser, and sensitive data may be leaked.
To deal with it, we can use notifications pull mechanism. When a notification pulled, if session expired, it'll return with http respond with status 401.

2017-05-22 08:30 UTC, ares commented
this needs to be rebased, also there are some hound issues

2017-05-24 13:27 UTC, amirfefer commented
@ares Thanks for your review, could you please re-review? 
btw, it seems failures not related..

2017-06-01 11:08 UTC, amirfefer commented
@tbrisker , could you have a look ?

2017-06-01 11:08 UTC, ohadlevy commented
/cc @matanwerbner

2017-06-01 11:09 UTC, ohadlevy commented on webpack/assets/javascripts/react_app/redux/actions/notifications/index.js
> +            window.location.replace('/users/login');
@matanwerbner how would you go about testing this?

2017-06-01 11:43 UTC, matanwerbner commented on webpack/assets/javascripts/react_app/redux/actions/notifications/index.js
> +        .success(response => {
The jqXHR.success(), jqXHR.error(), and jqXHR.complete() callbacks are removed as of jQuery 3.0 (http://api.jquery.com/jQuery.ajax/), so we'd better not use them.

2017-06-01 11:47 UTC, matanwerbner commented on webpack/assets/javascripts/react_app/redux/actions/notifications/index.js
> +            window.location.replace('/users/login');
in notifications.test.js , we already have mock server response in the beforeEach part, we need to mock a failure response, and then set up a mock for window.location.replace function with a spy, and make sure that it is called.

2017-06-01 11:50 UTC, dLobatog requested changes
Changing to WoC after @matanwerbner comments

2017-06-07 07:49 UTC, ohadlevy commented
@amirfefer ping?

2017-06-07 12:28 UTC, amirfefer commented
@matanwerbner could you re-review please?

2017-06-07 12:30 UTC, matanwerbner commented on webpack/assets/javascripts/react_app/redux/actions/notifications/index.js
> +        (error) => {
i think we should structure it a bit nicer - make an error function, a success function, and a finally function to make it cleaner.

2017-06-07 13:38 UTC, dLobatog approved these changes

2017-06-07 13:40 UTC, dLobatog commented
@matanwerbner thanks for the review - please remember to set the `Waiting on Contributor` label after requesting changes, to allow other reviewers to skip this PR. You can do so either manually, if you have permissions, or by submitting a review and marking Request Changes (the bot does it for you in this case)

![screenshot from 2017-06-07 15-40-00](https://user-images.githubusercontent.com/598891/26881430-a2ca0ddc-4b97-11e7-90bf-3e84c3d57200.png)

2017-06-07 14:25 UTC, ohadlevy commented
@amirfefer can you rebase and run rubocop, I think this will ensure hound concerns are addressed.

2017-06-07 18:40 UTC, matanwerbner commented
Looks good @amirfefer!

2017-06-08 00:23 UTC, amirfefer commented
@ohadlevy :+1:  - I've rebased.

2017-06-14 07:48 UTC, merged