Fixes #19700 - update rubocop rules
theforeman/foreman pull request #4559
Opened 2017-05-29 14:11 UTC by ohadlevy

The following changes have been made:

- Performance/RedundantMerge:
changes lines such as:
```not_found_message.merge! :message => options```
to:
```not_found_message[:message] = options```

- converts str.match() to str =~ ()
- remove extra whitespaces etc.

2017-05-29 17:32 UTC, dLobatog requested changes
Thanks @ohadlevy ! Take a look at the seeds changes, it looks like tests are failing because of some problem there (including some Katello tests, only 11 of those failures are "supposed to be"  there)

2017-05-30 11:59 UTC, lzap submitted a review, later dismissed
Test failures, also I'd suggest setting `MaxKeyValuePairs` to just `1` - I think two lines of code is worth merging into one `merge` call. Defaults to 2.

2017-05-30 11:59 UTC, lzap commented on db/seeds.d/08-data.rb
> +SEEDED_PARTITION_TABLES ||= [
Reason for this?

2017-05-30 11:59 UTC, lzap commented on lib/proxy_api/dhcp.rb
> +      end
This might be reasonable case when to use `merge` tho, but I can live with that enforcing.

2017-05-30 11:59 UTC, lzap commented on lib/proxy_api/dhcp.rb
> +      end
Also see my review comment, I'd change MaxKeyValuePairs.

2017-05-30 14:36 UTC, ohadlevy commented on db/seeds.d/08-data.rb
> +SEEDED_PARTITION_TABLES ||= [
I was trying to address ```foreman/db/seeds.d/08-data.rb:1: warning: already initialized constant SEEDED_PARTITION_TABLES``` I'll revert as its not really related to this PR.

2017-05-30 16:35 UTC, ohadlevy commented
Tests are passing.

2017-05-31 11:56 UTC, lzap commented on db/seeds.d/08-data.rb
> +SEEDED_PARTITION_TABLES ||= [
Hmm looks we load this twice.

2017-06-01 08:01 UTC, ohadlevy commented
@dLobatog can you re-review please? thanks.

2017-06-01 11:45 UTC, dLobatog approved these changes

2017-06-01 11:45 UTC, merged

2017-06-01 11:45 UTC, dLobatog commented
Thanks @ohadlevy & @lzap !