Fixes #17204 - Sort setting UI category tabs consistently
theforeman/foreman pull request #4590
Opened 2017-06-14 12:29 UTC by swapab

2017-06-14 17:03 UTC, sean797 commented
Thanks @swapab, just want to get someone else recommendation on ordering. @Rohoover can you comment please? This sets "General" first, then the remainder alphabetically.

Here's a screenshot for reference:
![screenshot from 2017-06-14 17-56-41](https://user-images.githubusercontent.com/13135483/27144785-1cba1f54-512b-11e7-97ba-de4f2f480faf.png)

2017-06-14 17:08 UTC, Rohoover commented
@sean797 
I can't really comment on the order unless there was data showing most used options from the user. I think the approach you took is reasonable without said information.

2017-06-15 07:19 UTC, swapab commented
@sean797 @Rohoover Thanks for the review.
The order was set to give an ideal sense to it as opposed to random one.
Given the fact that in future we would have analytics of _most used options_ it would be easier to shuffle around accordingly.

2017-06-15 08:45 UTC, sean797 requested changes
Thanks @Rohoover for taking a look 🥇 @swapab, I made 2 small comments, I agree the ordering seems sane, Thanks! 👍

Edit: Also tests are broken, can you take a look?

2017-06-15 08:45 UTC, sean797 commented on app/models/setting.rb
> +  def self.sticky_setting
Can you move this to a private method?

2017-06-15 08:45 UTC, sean797 commented on app/models/setting.rb
> +  def self.stick_general_to_first
Nitpick, can this be `self.stick_general_first` ?

2017-06-15 13:39 UTC, swapab commented
Requested changes were done.
All tests passing.

2017-06-15 13:41 UTC, swapab commented on app/models/setting.rb
> +  def self.sticky_setting
I am not a fan of private class methods. Moved it to a variable in `stick_general_first`.

2017-06-15 14:35 UTC, dLobatog requested changes
Thanks @swapab - I see the results are alphabetically ordered but i'm not sure where is that coming, could you please address the 2 questions inline?

2017-06-15 14:35 UTC, dLobatog commented on app/models/setting.rb
> +  scope :order_by, ->(attr) { except(:order).order(attr) }
What is the `except(:order)` for?

2017-06-15 14:35 UTC, dLobatog commented on app/models/setting.rb
> +    where(:category => sticky_setting).concat(where.not(:category => sticky_setting)).group_by(&:category)
The issue mentions the rest of the settings should be ordered alphabetically, where is that?

2017-07-05 08:50 UTC, swapab commented on app/models/setting.rb
> +  scope :order_by, ->(attr) { except(:order).order(attr) }
The `except(:order)` is to remove `default_scope` https://github.com/swapab/foreman/blob/develop/app/models/setting.rb#L57
I feel the `default_scope` is not required and should be replaced with explicit sorting wherever required.

2017-07-05 08:52 UTC, swapab commented on app/models/setting.rb
> +    where(:category => sticky_setting).concat(where.not(:category => sticky_setting)).group_by(&:category)
The sort query has been added in `Setting::live_descendants`
https://github.com/swapab/foreman/blob/e55c6e4b8a486a34e81bef048853031c890f5bb7/app/models/setting.rb#L75

2017-07-19 19:53 UTC, ohadlevy commented
whats the status of this pr? thanks

2017-07-20 09:25 UTC, swapab commented
@ohadlevy It needs a re-review.
I have answered @dLobatog's queries https://github.com/theforeman/foreman/pull/4590#pullrequestreview-44315495

2017-07-26 12:35 UTC, dLobatog approved these changes

2017-07-26 12:35 UTC, merged

2017-07-26 12:36 UTC, dLobatog commented
Sorry for the delay, merged! Thanks @swapab!

2017-07-27 03:51 UTC, swapab commented
@dLobatog No problem.Thanks! :smiley:

2017-07-27 07:33 UTC, ares commented
Thanks @dLobatog for merging, I set the redmine release to 1.16