Fixes #20035 - Adds API link to About page
theforeman/foreman pull request #4599
Opened 2017-06-16 14:13 UTC by ares

2017-06-16 19:20 UTC, ohadlevy commented on app/views/about/index.html.erb
> +        <li><%= link_to _('API'), apipie_apipie_path %></li>
nitpick: should this be API docs or something more clear?

2017-06-16 19:35 UTC, ares commented on app/views/about/index.html.erb
> +        <li><%= link_to _('API'), apipie_apipie_path %></li>
Yeah... I was not sure about the label, "API documentation" seems too much for just a list of endpoints. How about "Available API calls" or "API provided by the server"?

2017-06-18 11:00 UTC, ohadlevy commented on app/views/about/index.html.erb
> +        <li><%= link_to _('API'), apipie_apipie_path %></li>
I would add it maybe via an hover or an icon? something like
```Automate Foreman via a simple and powerful API```

2017-06-19 09:29 UTC, dLobatog requested changes
Setting to WoC as per @ohadlevy 's comment. @ares  Personally I think "API documentation" or "API resources"  is accurate to describe what Apipie provides.

2017-06-19 10:47 UTC, ares commented
I liked "API Resources" the most, I also added the hover message as @ohadlevy suggested

2017-06-20 09:28 UTC, dLobatog commented
Failure http://ci.theforeman.org/job/test_develop_pr_core/13327/database=postgresql,ruby=2.4,slave=fast/testReport/junit/(root)/ComputeResourceJSIntegrationTest/test_0003_compute_resource_password_isn_t_deleted_when_testing_connection/ should be fixed by https://github.com/theforeman/foreman/pull/4604

2017-06-20 09:29 UTC, dLobatog approved these changes

2017-06-20 09:29 UTC, merged

2017-06-20 09:30 UTC, dLobatog commented
Thanks @ares !