Fixes #19623 - add comparison to portkey for vmware networks
theforeman/foreman pull request #4611
Opened 2017-06-22 10:01 UTC by wiad

Details in http://projects.theforeman.org/issues/19623

2017-06-22 13:24 UTC, dLobatog commented
[test upgrade]
[test katello]
[test foreman]

(this triggers our CI test)

2017-06-22 13:25 UTC, dLobatog requested changes

2017-06-22 13:25 UTC, dLobatog commented on app/models/concerns/fog_extensions/vsphere/server.rb
> +        vm_network ||= all_networks.detect { |network| network.key == nic_attrs['network'] }
Nitpick, you may as well put everything on the same line:

```ruby
          vm_network ||= all_networks.detect { |network| [network.name, network.key].include? nic_attrs['network'] } 
```

2017-06-23 09:15 UTC, timogoebel commented
@dLobatog: I can't test the issue described in the ticket, but I'll be happy to test this for regressions & merge this next week.

2017-06-27 16:06 UTC, dLobatog approved these changes

2017-06-27 16:09 UTC, dLobatog reviewed
@timogoebel Don't worry, I tested just the basic case. The proper fix has to come through fog-vmware though. If tests pass I'll merge.

@wiad Remember to make the commits compliant with @theforeman-bot 's message tips 😉 https://github.com/theforeman/foreman/pull/4611#issuecomment-310384125 It helps with our automation. Don't worry now though, I will just rebase your two commits into one with the right title.

2017-06-27 16:34 UTC, wiad commented
@dLobatog  yeah, I forgot the commit message style convention in the last commit but hoped it would be ok anyway - thanks! I'll remember it next time.

2017-06-27 16:36 UTC, dLobatog commented
[test upgrade]
[test katello]
[test foreman]

2017-06-27 18:56 UTC, merged

2017-06-27 18:56 UTC, dLobatog commented
Thanks @wiad !