Fixes #19844 - fix Security/Eval cop
theforeman/foreman pull request #4620
Opened 2017-06-25 14:31 UTC by tbrisker

2017-06-25 14:35 UTC, ohadlevy commented
:+1: pending fixes to hound comments and tests :)

2017-06-26 08:12 UTC, dLobatog requested changes
@tbrisker It looks like the family prefixes to PXEFILES are missing on a couple of files, could you check that's correct? Thanks!

2017-06-26 08:12 UTC, dLobatog commented on app/models/operatingsystems/windows.rb
> +    pxe_prefix(arch) + PXEFILES[type.to_sym]
Isn't this missing `self.family.constantize::` before PXEFILES?

2017-06-26 08:12 UTC, dLobatog commented on app/models/operatingsystems/xenserver.rb
> +    pxe_prefix(arch) + "-" + PXEFILES[type.to_sym].split("/")[-1]
`self.family.constantize::` ditto

2017-06-26 08:12 UTC, dLobatog commented on app/models/operatingsystems/xenserver.rb
> +    PXEFILES.values.push(MBOOT).map do |img|
`self.family.constantize::` ditto, Xenserver has a family according to operatingsystem.rb

2017-06-26 08:14 UTC, tbrisker commented on app/models/operatingsystems/windows.rb
> +    pxe_prefix(arch) + PXEFILES[type.to_sym]
No, because in this case the family is always `Windows` - Operatingsystem.family just reads the type attribute.

2017-06-26 11:23 UTC, tbrisker commented
@dLobatog the `self.family` part was just copy paste from the general operating system code AFACIT. for windows/xenserver the `family` (which is basically an alias for `type`) would be `Windows` or `Xenserver` accordingly and the relevant constant would be just `PXEFILES` without having to fully qualify it.

2017-06-26 14:35 UTC, dLobatog approved these changes

2017-06-26 14:36 UTC, merged

2017-06-26 14:36 UTC, dLobatog commented
Thanks @tbrisker !

2017-06-27 06:05 UTC, ares commented
Thanks for merging, please don't forget to set the release in redmine issue after merging.