[Do not merge] Foreman plugin support for webpack/react
theforeman/foreman pull request #4625
Opened 2017-06-26 15:15 UTC by ohadlevy

How to use:

in a plugin, create a directory called webpack
then inside a file called index.js put something like:

```js
import React from 'react';
import ReactDOM from 'react-dom';
import Icon from 'foremanReact/common/Icon';

const reactNode = document.querySelector('#content');

if (reactNode) {
  ReactDOM.render(
    <Icon type='ok' />,
    reactNode);
};

```
TODOS:
- [ ] support JEST / eslint
- [ ] extend the react mounter, so plugins can add more mounting points and use
them.
- [ ] update storybook to support plugins too
- [ ] make equivalent of rake test

2017-06-26 15:17 UTC, ohadlevy commented
this replaces #4619

2017-06-28 21:01 UTC, dLobatog requested changes
@ohadlevy Thanks for improving #4619! 

I have been trying it, and it compiles fine.  My problem is that even if I see ../foreman_ansible/index.js on the webpack compile output, however I can't find it neither on myforklifturl:3808, nor on the Firefox/Chromium inspector... I tried to do something stupid like putting `console.log` or `alerts` in there and they don't seem to be loaded either. What could I be missing?

2017-06-28 21:01 UTC, dLobatog commented on app/views/layouts/base.html.erb
> +    <%= javascript_include_tag *webpack_asset_paths('vendor', :extension => 'js'), "data-turbolinks-track" => true %>
I see it's mostly React (the library itself), however it doesn't seem to get my `../foreman_ansible/webpack/index.js` content in it.. https://gist.github.com/dLobatog/96f33a68be7fdd92ba79e8d5d6219496 is what I see

2017-06-28 21:01 UTC, dLobatog commented on config/webpack.config.js
> +    plugins.entries
Out of curiosity, where is the part that adds '-core.js' to the name of the config entries? I see `ansiblecore.js` here for example, https://gist.github.com/7b39b650c625aba5d7f4216fa7a0c61d (on foreman_ansible I just have `webpack/index.js`)

2017-06-28 21:01 UTC, dLobatog commented on script/plugin_webpack_directories.rb
> +# Only works for local dependencies
Do you mean it only works for gems that have the source path set by `:path=>` in the Gemfile?

2017-06-29 06:02 UTC, ohadlevy commented on app/views/layouts/base.html.erb
> +    <%= javascript_include_tag *webpack_asset_paths('vendor', :extension => 'js'), "data-turbolinks-track" => true %>
it wont, you need to include it in your plugin.
e.g, in a page somewhere (either in the layout or a specific page) add:
```erb
+<%= javascript_include_tag *webpack_asset_paths('name of chunk'', :extension => 'js'), "data-turbolinks-track" => true %>
```

2017-06-29 06:04 UTC, ohadlevy commented on config/webpack.config.js
> +    plugins.entries
I think "core" comes from plugins that have it in their names, e.g. foreman-tasks-core, rex-core etc.

have a look at the ruby script output, it defines the chunk name. I'm uncertain why you have the extra word core in there either.

2017-06-29 06:04 UTC, ohadlevy commented on script/plugin_webpack_directories.rb
> +# Only works for local dependencies
actually, you can remove it, it was a copy paste from your original script.

2017-06-29 07:01 UTC, dLobatog commented on config/webpack.config.js
> +    plugins.entries
It makes sense now, it reads foreman_ansible_core first apparently 😄

2017-06-29 07:06 UTC, ohadlevy commented on config/webpack.config.js
> +    plugins.entries
just wondering - why do you have a core spec in there to begin with?

2017-07-03 12:07 UTC, ohadlevy commented
@dLobatog @waldenraines do you think it makes sense to merge as is? this should unblock basic usage and allow experimenting with packaging efforts?

2017-07-03 18:37 UTC, dLobatog commented on config/webpack.config.js
> +    plugins.entries
@ohadlevy The agent that executes the roles can run on the proxy or on Foreman itself. In fact it's the first plugin that introduced this "_core" gem dependency concept to allow reusing the code to run actions in the proxy or in Foreman.

2017-07-03 20:25 UTC, dLobatog approved these changes

2017-07-03 20:28 UTC, dLobatog requested changes
@ohadlevy Yeah, I agree - I was able to successfully do basic things like importing `'foremanReact/common/Alert` and using it from a plugin. 

Can you rebase, squash and use the proper commit title to reference the Redmine issue? It should be ready after that I think.

2017-07-04 07:18 UTC, ohadlevy commented
@dLobatog updated.

2017-07-04 09:30 UTC, dLobatog approved these changes

2017-07-04 09:32 UTC, merged

2017-07-04 09:32 UTC, dLobatog commented
Thanks @ohadlevy !

2017-07-05 14:37 UTC, waldenraines commented
> @dLobatog @waldenraines do you think it makes sense to merge as is? this should unblock basic usage and allow experimenting with packaging efforts?

I'm a little late to the party but yes 😄  and thanks @ohadlevy!