Fixes #20134 - Compute Profile for Ovirt loads template data
theforeman/foreman pull request #4626
Opened 2017-06-28 12:51 UTC by orrabin

2017-06-28 18:39 UTC, dLobatog requested changes
@orrabin Marking this one as 1.15.2, is there any way to write a small test for this that verifies the value is changed? Thanks!

2017-07-02 10:04 UTC, orrabin commented
@dLobatog I can add an integration test for the value change but that would only test the use of this js on the host form and this pr is fixing a bug when using the same js from compute profiles. In my case the value shouldn't change because `templateSelector[0]` is undefined.

2017-07-03 17:22 UTC, dLobatog approved these changes

2017-07-03 17:22 UTC, dLobatog commented
@orrabin Oh I see it now.. OK - I'm not really sure it makes much sense to test just the selector. Hopefully we can move this to be tested with Jest at some point. Merging...

2017-07-03 17:23 UTC, merged