Fixes #20137 - hide ssh keys for new users
theforeman/foreman pull request #4627
Opened 2017-06-28 15:20 UTC by ares

This might be a candidate for 1.15.z

2017-06-28 18:37 UTC, dLobatog requested changes
Thanks @ares , I agree this is 1.15.2, double check the warning message please.

2017-06-28 18:37 UTC, dLobatog commented on app/views/ssh_keys/_ssh_keys_tab.html.erb
> +                 <%= _("In order to create the SSH key, the user must be saved first. A 'create_ssh_keys' is required too.") %>
I think the message got cut by mistake, you meant "A `create_ssh_keys` permission is required"?

2017-06-28 18:37 UTC, dLobatog commented on app/views/ssh_keys/_ssh_keys_tab.html.erb
> +                 <%= _("In order to create the SSH key, the user must be saved first. A 'create_ssh_keys' is required too.") %>
Also this immediately reminded me of the same thing in Roles `https://github.com/theforeman/foreman/blob/develop/app/views/roles/_form.html.erb#L46`, mind to also use `alert :header => '', :class => 'alert-warning'` for coherence?

2017-06-29 06:25 UTC, ares commented
Both good catches, I updated the message and styled a warning. Please take another look.

2017-06-29 07:26 UTC, tbrisker approved these changes

2017-06-29 10:58 UTC, dLobatog approved these changes

2017-06-29 10:59 UTC, merged

2017-06-29 10:59 UTC, dLobatog commented
Thanks @ares  & @tbrisker !