fixes #20193 - upgrade storybook to 3.1
theforeman/foreman pull request #4639
Opened 2017-07-03 18:50 UTC by ohadlevy

2017-07-04 13:14 UTC, tbrisker requested changes

2017-07-04 13:14 UTC, tbrisker commented on webpack/stories/index.js
>  /* eslint-disable no-unused-vars */
is this comment needed? I don't see any unused vars (I think linkTo was the unused one?)

2017-07-04 13:14 UTC, tbrisker commented on package.json
> -    "storybook": "start-storybook --dont-track -p 6006",
does this mean that tracking is enabled now or did the default change?

2017-07-04 13:14 UTC, tbrisker commented on .storybook/webpack.config.js
> +        loaders: ['style-loader', 'css-loader', 'sass-loader']
I think `sass-loader` shouldn't run on `.css` files, only on `.scss`

2017-07-04 13:14 UTC, tbrisker commented on package.json
> +    "@storybook/addon-knobs": "3.1.2",
Is there a reason this one is locked to a specific version and the other addons are not? 
Also, do we actually use any of the addons other then actions anywhere?

2017-07-05 09:04 UTC, ohadlevy commented on package.json
> -    "storybook": "start-storybook --dont-track -p 6006",
sadly that option has been removed, I was unable to find if it actually tracks or not, based on my browser connections it seems like it does not.

2017-07-05 09:04 UTC, ohadlevy commented
@tbrisker updated.

2017-07-05 09:14 UTC, tbrisker approved these changes

2017-07-05 09:17 UTC, tbrisker commented
not sure why, but looks like tests broke completely?

2017-07-05 09:31 UTC, tbrisker commented
Ok, looks like tests broke due to #4625, not related to this, opened #4644 to make sure js tests run when webpack config changes. Merging.

2017-07-05 09:31 UTC, merged

2017-07-05 09:31 UTC, tbrisker commented
Thanks @ohadlevy !