Fixes #19947 - Fix creating bookmarks for global params
theforeman/foreman pull request #4661
Opened 2017-07-12 07:19 UTC by xprazak2

2017-07-12 09:47 UTC, dLobatog requested changes
Thanks, this looks good @xprazak2 - could you add a functional test that creates a bookmark for global params using this controller? I plan to include this fix on 1.15.3 and patch release changes should come with tests

2017-07-17 07:11 UTC, xprazak2 commented
I added a test

2017-07-17 14:44 UTC, dLobatog approved these changes

2017-07-17 14:44 UTC, merged

2017-07-17 14:45 UTC, dLobatog commented
Thanks @xprazak2 !