Fixes #19113 - use fog-ovirt method for rebooting
theforeman/foreman pull request #4672
Opened 2017-07-14 13:02 UTC by iNecas

While fixing the waiting for stopped vm in reboot there.

Waiting for https://github.com/fog/fog/pull/3954 to get in.

2017-07-16 09:19 UTC, tbrisker approved these changes
Looks good, will merge once fog change is merged and released.

2017-07-16 09:19 UTC, tbrisker commented on app/models/concerns/fog_extensions/ovirt/server.rb
> +        reboot
:+1: to pushing this into fog.

2017-07-18 15:53 UTC, dLobatog requested changes
@iNecas 👍 - I would say 1.16, as I'm not too keen on updating the fog version for a patch version... Setting to WoC so you can let us know when the release has been done.

2017-08-03 11:45 UTC, iNecas commented
@dLobatog @tbrisker new fog, that includes required change got just merged. The required version is bumped and ready for final re-review

2017-08-04 10:36 UTC, dLobatog approved these changes

2017-08-04 10:37 UTC, dLobatog requested changes
@iNecas I think you also need to update the fog-core dep, after that I'm 👍  if tests pass.

```
Bundler could not find compatible versions for gem "fog-core":
  In Gemfile:
    fog-core (= 1.44.2)

    fog (= 1.41.0) was resolved to 1.41.0, which depends on
      fog-core (~> 1.45)
```

2017-08-04 11:20 UTC, iNecas commented
Updated the deps, waiting for the tests

2017-08-04 14:49 UTC, iNecas commented
[test foreman]

2017-08-04 15:33 UTC, iNecas commented
[test foreman]

2017-08-07 09:08 UTC, dLobatog requested changes
@iNecas Seems that tests fail?

2017-08-07 12:17 UTC, iNecas commented
[test foreman]

Couldn't reproduce locally still :( Hoping it is something with Jenkins :)

2017-08-23 20:30 UTC, iNecas commented
Tests are 🍏 now

2017-08-24 08:51 UTC, dLobatog approved these changes

2017-08-24 08:52 UTC, merged

2017-08-24 08:52 UTC, dLobatog commented
Thanks @iNecas !