Fixes #20312: Use bundler_ext in production to load webpack plugin
theforeman/foreman pull request #4675
Opened 2017-07-16 15:18 UTC by ehelms

2017-07-16 19:01 UTC, ohadlevy commented
@ehelms thanks, does it make sense to add a test to see this file return json correctly?

2017-07-17 13:33 UTC, ehelms commented
@ohadlevy I added one, lets see what Jenkins does. Testing the bundler_ext route is not really possible since it requires installing a gem that also changes multiple other paths.

2017-07-17 13:44 UTC, ohadlevy commented on test/unit/script/plugin_webpack_directories_test.rb
> +    @root_dir = File.expand_path('../../../..', __FILE__)
consider using File.join instead (if we ever run on non unix platform).

2017-07-17 13:46 UTC, dLobatog requested changes
Setting to WoC based on Hound, `File.join` comment, commit summary length > 65

2017-07-17 14:46 UTC, dLobatog approved these changes

2017-07-17 14:46 UTC, dLobatog approved these changes
Ready to merge if tests pass

2017-07-17 15:49 UTC, dLobatog requested changes
@ehelms Please check out the test, thanks !

2017-07-17 15:49 UTC, dLobatog commented on test/unit/script/plugin_webpack_directories_test.rb
> +    plugin_webpack = `#{@script}`
Seems that this is not producing any output in Jenkins, as it's nil in the test that is failing

2017-07-19 11:14 UTC, dLobatog requested changes
@ehelms Please rebase now that the commit by @ohadlevy was merged, thanks!

2017-07-19 14:05 UTC, ehelms commented
Rebased and should pass tests this time around

2017-07-19 19:11 UTC, dLobatog requested changes
@ehelms Still failing :/

2017-07-19 19:37 UTC, ohadlevy commented on test/unit/script/plugin_webpack_directories_test.rb
> +    @root_dir = File.join('../../../..', __FILE__)
nitpicking, but the whole value of using file.join was to not include / or \ so ['..','..','..'....]
also, shouldnt it be 3 times vs 4 ?

if you want to be sure you can probably assert that @root_dir exists is rails root too

2017-07-24 13:47 UTC, ehelms commented
@ohadlevy @dLobatog This is now passing tests. Please double check all your requests.

2017-07-24 13:52 UTC, ohadlevy commented
overall :+1: but if we add more logic I would prefer to start extracting methods and / or classes etc ...

2017-07-25 16:03 UTC, dLobatog approved these changes

2017-07-25 16:04 UTC, merged

2017-07-25 16:04 UTC, dLobatog commented
Thanks @ehelms & @ohadlevy !

2017-07-25 17:24 UTC, ares commented
I set 1.16 in redmine