Refs #17525 - verify domain dns id also on update
theforeman/foreman pull request #4677
Opened 2017-07-17 13:56 UTC by ares

While still not systematic solution to all possible relations in Foreman, this tries to close the gap from https://github.com/theforeman/foreman/pull/4120, except for relying on `dns_id` being the only foreign key, we proactively check for the value. The patch is still small so I think could be cherry-picked to 1.15.3 since the original fix was introduced in 1.15 branch.

2017-07-17 13:56 UTC, ares commented
if it's not accepted to 1.15, please let me know so I can create separate issue to track it against different version

2017-07-18 11:04 UTC, lzap approved these changes
Looks good, but I will let the 1.15 decision on @dLobatog

2017-07-18 15:50 UTC, dLobatog requested changes
👍 , ack this for 1.15 , no problem. 

@ares Please add one or two tests for the new function demonstrating it's behavior to make sure it doesn't break, to keep patch versions as stable as possible I'm following http://projects.theforeman.org/projects/foreman/wiki/Release_Management#Issue-tracking and requiring tests for any change meant to be cherry-picked (this PR fails number 7 in that list)

2017-07-18 15:50 UTC, dLobatog commented on app/controllers/api/v2/domains_controller.rb
> +        id.nil? || SmartProxy.authorized(:view_smart_proxies).find_by_id(id).present?
`id.blank?` checks against empty strings too

2017-07-19 07:54 UTC, ares commented
Fair enough, I added the tests (similar to existing for creation). Btw other tests revealed some issues with my initial implementation, so the code path is decently covered.

2017-07-20 08:42 UTC, ares commented on app/controllers/api/v2/domains_controller.rb
> +        id.nil? || SmartProxy.authorized(:view_smart_proxies).find_by_id(id).present?
But we want only `nil` here, we don't want to verify dns_id if it was not passed as attribute (`domain_parameters[:dns_id]` is `nil`), if user sent empty string we want to trigger the verification and try load the proxy so it fails and tells user that empty string is invalid value.

2017-07-20 09:21 UTC, lzap commented
There are failures.

2017-07-20 09:24 UTC, dLobatog approved these changes
@ares Could you rebase to bring in the changes from https://github.com/theforeman/foreman/pull/4678  ? I think that's why tests are failing now.

2017-07-20 09:32 UTC, ares commented
rebased

2017-07-20 10:41 UTC, lzap commented
Capybara::Poltergeist::StatusFailError: Request to 'http://127.0.0.1:37703/variable_lookup_keys' failed to reach server, check DNS and/or server status seems unrelated.

2017-07-20 12:24 UTC, merged

2017-07-20 12:24 UTC, dLobatog commented
Thanks @ares !

2017-07-20 12:25 UTC, dLobatog commented
Cherry picked to 1.15-stable as d2eece634bf9040e4d9b32a36886b097980e1cae