Fixes #20386 - Allow to identify smart proxy by ip only
theforeman/foreman pull request #4692
Opened 2017-07-23 15:04 UTC by agx

This allows setting trusted_puppet_master_hosts to an IP in the
non-https case. This can e.g. be useful when testing ansible fact
importing from another machine.

2017-07-24 17:35 UTC, dLobatog requested changes
Thanks @agx, makes sense

2017-07-24 17:35 UTC, dLobatog commented on app/controllers/concerns/foreman/controller/smart_proxy_auth.rb
> +      request_hosts = [request.ip] if request_host == []
`request_hosts` - mind to write a test to demonstrate the behavior?

2017-07-25 06:36 UTC, agx commented
@dLobatog added a test now as well

2017-07-25 07:48 UTC, dLobatog approved these changes

2017-07-25 07:49 UTC, dLobatog approved these changes

2017-07-25 07:49 UTC, merged

2017-07-25 07:49 UTC, dLobatog commented
Thanks @agx!