Fixes #20403 - Only show authorized compute profiles in forms
theforeman/foreman pull request #4695
Opened 2017-07-25 12:32 UTC by tbrisker

2017-07-25 12:34 UTC, tbrisker commented on app/helpers/application_helper.rb
> -    where = opts.fetch(:where, nil)
not directly related to this but just noticed while i was working on this and cleaned up along the way.

2017-07-25 12:34 UTC, tbrisker commented on app/models/compute_profile.rb
> +  scope :visibles, -> { joins(:compute_attributes) }
we don't actually use the eager loaded attributes anywhere, this looks like some weird way to turn a left outer join into an inner join.

2017-07-27 08:41 UTC, dLobatog requested changes
@tbrisker Looks good, can you add a test to ensure this behavior remains? Just ensuring `visible_compute_profiles` does not return ComputeProfiles a user is unauthorized to see should be enough. Thanks!

2017-07-27 08:41 UTC, dLobatog commented on app/helpers/application_helper.rb
> -    where = opts.fetch(:where, nil)
Should be safe to do this https://github.com/search?q=accessible_related_resource&type=Code&utf8=%E2%9C%93

2017-07-27 11:03 UTC, tbrisker commented on app/helpers/application_helper.rb
> -    where = opts.fetch(:where, nil)
not sure I understand your comment here, the behaviour doesn't change at all, just replace the ops hash into kwargs.

2017-07-27 11:04 UTC, tbrisker commented
@dLobatog thanks, with the test i realized i had the wrong permission name there and that we don't have fixtures for compute profile permissions at all.

2017-07-27 14:47 UTC, tbrisker commented
test failures seem to be unrelated.

2017-07-29 21:38 UTC, boaz0 approved these changes
LGTM

2017-07-31 11:15 UTC, dLobatog approved these changes

2017-07-31 11:15 UTC, merged

2017-07-31 11:15 UTC, dLobatog commented
Thanks @tbrisker !