"Fixes #20446 - reset page param after search"
theforeman/foreman pull request #4706
Opened 2017-07-31 14:09 UTC by lizagilman

2017-07-31 17:54 UTC, ohadlevy commented on webpack/assets/javascripts/foreman_tools.js
> +  }
won't this always set the page to 1 regardless? afaiu this function is called both from the per_page and the search submit?.

can you write a test to demonstrate the various options?

2017-08-03 07:34 UTC, ohadlevy commented on webpack/assets/javascripts/foreman_tools.js
> +      if (getQueryStringValue(uri, 'page') > 1) {
I dont think thats correct, if i have a search term and then I'll do pagination, wont this always keep me on the first page?

IMHO only when the search has been submitted (not if it has a value) then you reset the page number to 1. (or remove the page attribute from the url)

2017-08-03 09:27 UTC, ohadlevy commented
btw: I think we need to reset the page number when changing the per page value as well.

I just changed from 20 to 5, and then moved 10 pages or so, and then i change it back to 15 where page 10 didn't exists anymore.

2017-08-10 13:04 UTC, lizagilman commented
updated

2017-08-13 07:27 UTC, lizagilman commented
[test foreman]

2017-08-14 10:47 UTC, ohadlevy commented
@lizagilman tests are failing.

2017-08-14 11:01 UTC, lizagilman commented
@ohadlevy minor change.. updated

2017-08-30 10:24 UTC, lizagilman commented
@ohadlevy ping ?

2017-09-12 09:44 UTC, tbrisker requested changes
See comments inline, looks like the code can be simplified a bit.

2017-09-12 09:44 UTC, tbrisker commented on webpack/assets/javascripts/foreman_tools.js
> +      searchTerm = $(element).find('.autocomplete-input').val() || $('#search-form').find('.autocomplete-input').val();
`isSearchForm` means that `element` has id of `search-form`, so that the two conditions are actually checking for the same thing.

2017-09-12 09:44 UTC, tbrisker commented on webpack/assets/javascripts/foreman_tools.js
> +      if (searchTerm) {
If there isn't a value shouldn't we still set the search to an empty value?

2017-09-12 09:44 UTC, tbrisker commented on webpack/assets/javascripts/foreman_tools.js
> +      if (element.id !== 'search-form' && !(uri.hasSearch('search'))) {
the first clause here is the same as `!isSearchForm`, and the second I think is redundant - if the uri doesn't have search, there is nothing to remove.

2017-09-12 09:44 UTC, tbrisker commented on webpack/assets/javascripts/foreman_tools.js
> +    if ((isSearchForm || element.id === 'per_page') && getQueryStringValue(uri, 'page') > 1) {
why do we need to check if page > 1? if it is 1 setting it to 1 is a noop, and it makes the `getQueryStringValue` function redundant.

2017-10-15 09:27 UTC, lizagilman commented
waiting for review

2017-10-19 15:26 UTC, waldenraines commented
@tbrisker @ohadlevy anything else to be done here before merging?

2017-10-23 10:02 UTC, tbrisker commented on webpack/assets/javascripts/foreman_tools.js
> +    if ((isSearchForm || element.id === 'per_page') && getQueryStringValue(uri, 'page') > 1) {
I think you missed this comment.

2017-10-25 08:53 UTC, lizagilman commented
updated

2017-10-30 14:03 UTC, waldenraines approved these changes
Tested this out and it worked for me, thanks @lizagilman!

2017-11-07 11:43 UTC, tbrisker approved these changes
Works well, thanks @lizagilman !

2017-11-07 11:44 UTC, merged