Refs #19305 - fixing spacing issues on facts page
theforeman/foreman pull request #4711
Opened 2017-08-02 13:10 UTC by lizagilman

![image](https://user-images.githubusercontent.com/15361156/28874725-bb1a7fcc-779b-11e7-91d3-77b419c9cb3c.png)

2017-08-03 08:16 UTC, timogoebel requested changes

2017-08-03 08:16 UTC, timogoebel commented on app/helpers/fact_values_helper.rb
> +        if value.compose and current_name == name.split(FactName::SEPARATOR).last
Please use `&&` instead of `and`.

2017-08-03 08:17 UTC, timogoebel commented
Looks good now:
![image](https://user-images.githubusercontent.com/4107560/28912513-ddb99a6a-7834-11e7-98df-3643849a7ac8.png)

2017-08-04 14:09 UTC, lizagilman commented
@timogoebel updated

2017-08-06 06:59 UTC, lizagilman commented
[test katello]

2017-08-07 09:04 UTC, dLobatog approved these changes
![screenshot from 2017-08-07 11-03-13](https://user-images.githubusercontent.com/598891/29019787-08137c94-7b60-11e7-81ec-5c3b6f0124c7.png)

![screenshot from 2017-08-07 11-04-07](https://user-images.githubusercontent.com/598891/29019824-27ca8abe-7b60-11e7-8dfa-58aec43f8a15.png)


I think I'm going to merge @timogoebel , hopefully I'm not missing anything else. Thanks @lizagilman & @timogoebel

2017-08-07 09:05 UTC, merged