Fixes #20454 - change page by typing page number
theforeman/foreman pull request #4713
Opened 2017-08-03 04:37 UTC by lizagilman

2017-08-03 07:33 UTC, ohadlevy commented on webpack/assets/javascripts/foreman_tools.js
> +  pageNum = $('#pagination1-page').val();
i might be missing something, but where does the pagination1-page comes from? why is it called "1"?

2017-08-13 12:53 UTC, lizagilman commented
@updated

2017-08-30 10:26 UTC, lizagilman commented
can anyone review? @tbrisker / @timogoebel  maybe ?

2017-09-11 13:39 UTC, tbrisker requested changes
Just a small typo, see inline

2017-09-11 13:39 UTC, tbrisker commented on config/initializers/will_paginate.rb
> +        current_page_input = tag(:input, '', class: 'pagination-pf-page', type: 'text', value: current_page, id: 'cur-page-num')
The id here is `cur-page-num` but below you look for `#cur_page_num` so it fails to find the right element. The tests also use `cur_page_num` which is why they pass.

2017-09-12 08:38 UTC, tbrisker commented
Pushed the typo correction to your branch, will merge if all green.

2017-09-12 11:25 UTC, tbrisker commented
Tests passed, merging. Thanks @lizagilman !

2017-09-12 11:25 UTC, tbrisker approved these changes

2017-09-12 11:25 UTC, merged