Fixes #20500 - Allow GET /api/hostgroups to include parameters in results
theforeman/foreman pull request #4718
Opened 2017-08-03 16:49 UTC by treydock

2017-08-11 09:55 UTC, dLobatog requested changes
Great work here @treydock , I don't have any major comments. Could you just add `@parameters = true` to the `update` and `create` methods? Those ones return a Hostgroup object too, which should contain parameters. Also this way both Host and Host groups API are more consistent.

Thanks!

2017-08-15 18:00 UTC, treydock commented
@dLobatog Changes made

2017-09-04 19:19 UTC, dLobatog approved these changes

2017-09-04 19:19 UTC, dLobatog commented
Thank you @treydock !

2017-09-04 19:19 UTC, merged