Fixes #15286 - New API for auth sources
theforeman/foreman pull request #4727
Opened 2017-08-08 13:34 UTC by dhlavac

Basic concept of new auth sources API

2017-08-14 13:21 UTC, tstrachota requested changes
Thanks for the PR @dhlavac 

I added some comments into the code. Routes definition seem to be missing completely so it's not possible to use the new controllers.

Could you please add some tests for the controllers?

2017-08-14 13:21 UTC, tstrachota commented on app/controllers/api/v2/auth_source_controller.rb
> +      api :GET, "/auth_source/:id/", N_("Show all authentication sources")
"Show an authentication source"

2017-08-14 13:21 UTC, tstrachota commented on app/controllers/api/v2/auth_source_external_controller.rb
> +      api :GET, "/auth_source_external/", N_("List external audits")
"List external authentication sources"

2017-08-14 13:21 UTC, tstrachota commented on app/controllers/api/v2/auth_source_internal_controller.rb
> +      api :GET, "/auth_source_internal/", N_("List internal audits")
"List internal authentication sources"

2017-08-14 13:21 UTC, tstrachota commented on app/controllers/api/v2/auth_source_external_controller.rb
> +        @auth_source_internal = resource_scope_for_index
Shouldn't this be `@auth_source_external`?

2017-08-14 13:21 UTC, tstrachota commented on app/views/api/v2/auth_source/base.jsno.rabl
> +object @auth_source
There's a typo in the file name: `base.jsno.rabl` vs base.json.rabl

2017-08-14 13:21 UTC, tstrachota commented on app/views/api/v2/auth_source/base.jsno.rabl
> +attributes :id, :type, :name
No newline at the end of file.

2017-08-14 13:21 UTC, tstrachota commented on app/views/api/v2/auth_source_external/base.jsno.rabl
> +object @auth_sources_external
Ditto file name

2017-08-14 13:21 UTC, tstrachota commented on app/views/api/v2/auth_source_external/test.json.rabl
> +end
Where is this `test.json.rabl` used?

2017-08-14 13:21 UTC, tstrachota commented on app/views/api/v2/auth_source_external/create.json.rabl
> +extends "api/v2/auth_source_external/show"
There's no `create` action defined in the auth source external controller.

2017-08-14 13:21 UTC, tstrachota commented on app/views/api/v2/auth_source_external/base.jsno.rabl
> +attributes :id, :type, :name
It would be good to map `type` onto some human readable type name to avoid leaking the internal class names out of the api.

2017-08-14 13:21 UTC, tstrachota commented on app/views/api/v2/auth_source/main.json.rabl
> +attributes :onthefly_register, :usergroup_sync, :tls, :server_type, :created_at, :updated_at
I don't think it makes sense to display the fields above (apart from the timestamps) for a generic auth source. They're all LDAP related.

2017-08-14 13:21 UTC, tstrachota commented on app/controllers/api/v2/auth_source_controller.rb
> +      param_group :search_and_pagination, ::Api::V2::BaseController
At the moment I don't think there's scoped search defined for auth sources. It would imho make sense to add it at least on name attr.

2017-08-15 07:42 UTC, ares commented on app/views/api/v2/auth_source_internal/base.jsno.rabl
> +attributes :id, :name
missing new line at the end of the file

2017-08-18 10:59 UTC, dhlavac commented on app/views/api/v2/auth_source/main.json.rabl
> +attributes :onthefly_register, :usergroup_sync, :tls, :server_type, :created_at, :updated_at
I have found records of this attributes in database due to I think it make senes to show that. Which is related for all authsorces ? - :created_at, :updated_at ? Some else ?

2017-08-18 12:00 UTC, tstrachota commented on app/views/api/v2/auth_source/main.json.rabl
> +attributes :onthefly_register, :usergroup_sync, :tls, :server_type, :created_at, :updated_at
Yeah, it's caused by STI. It can be confusing.
From the list above I think it's only the timestamps.

2017-09-12 21:28 UTC, closed without merging