Fixes #20416 - fix UI under email preferences
theforeman/foreman pull request #4732
Opened 2017-08-09 13:39 UTC by amirfefer

Before:
![before_notif](https://user-images.githubusercontent.com/11807069/29124127-aeacb61c-7d20-11e7-882d-598f21f3179f.png)
After:
![notification](https://user-images.githubusercontent.com/11807069/29124152-bffd1d44-7d20-11e7-8e72-d21defb5baee.png)

I've removed the label, and added placeholder text instead. IMO it looks better, less messy.

2017-08-10 09:00 UTC, tstrachota commented
The code looks good to me and it fixes the problem. 

@rohoover whe we're touching the code, would you mind checking if this is correct way of displaying such information?

If @rohoover approves this layout in general, I have additional proposals on the top of the current change:
- make the filter input narrower and align the right border with the rest of the inputs
- ensure the spacing after input filter is consistent with the rest of the form

Something like this:
![screenshot from 2017-08-10 10-59-30](https://user-images.githubusercontent.com/1186631/29162922-158feae4-7dbb-11e7-8d6d-27067247641a.png)

2017-08-10 14:10 UTC, Rohoover commented
Looks good. Anyway we can add the inline help text into the help icon with tooltip?

2017-08-11 09:22 UTC, dLobatog requested changes
@amirfefer Setting to WoC if you could please move the `help_inline` to `label_help`? There are multiple examples of `label_help` use, the end result should be like https://www.patternfly.org/pattern-library/forms-and-controls/field-level-help/ 

Thanks!

2017-08-15 20:55 UTC, amirfefer commented
@Rohoover Is that what you've meant?
![email_notification_v2](https://user-images.githubusercontent.com/11807069/29335805-8df3239a-8214-11e7-9235-b25c6b86c7df.png)

2017-08-18 17:03 UTC, Rohoover commented
Yes! Thank you! 

![bitmoji](https://render.bitstrips.com/v2/cpanel/9188364-131321122_2-s4-v1.png?transparent=1&palette=1&width=246)

2017-08-20 07:29 UTC, boaz0 approved these changes
LGTM 👍

2017-08-20 07:29 UTC, ripcurld0 commented
@dLobatog PTAL

2017-08-20 13:59 UTC, tbrisker approved these changes

2017-08-20 13:59 UTC, merged

2017-08-20 13:59 UTC, tbrisker commented
Thanks @amirfefer !