Fixes #19554 - Provide warning for unsupported PXE loader combinations
theforeman/foreman pull request #4792
Opened 2017-08-28 15:55 UTC by tstrachota

2017-08-28 17:27 UTC, tstrachota commented
@lzap would you mind doing the review?

2017-08-29 08:06 UTC, lzap requested changes
LGTM few nitpicks. I wonder if this works when PXE Loader is set via hostgroup. I will tests after rebase, if any.

2017-08-29 08:06 UTC, lzap commented on webpack/assets/javascripts/foreman_hosts.js
> +    /(?:red[ ]*hat|rhel|cent[ ]*os)[^\d]*(\d+)(?:[.]\d+)?/,
It is worth including "scientific" and "oracle".

2017-08-29 08:06 UTC, lzap commented on webpack/assets/javascripts/foreman_hosts.js
> +      } else if (os[1] === '7') {
I'd use `>= 7` here prehaps for the future.

2017-08-29 08:06 UTC, lzap commented on webpack/assets/javascripts/foreman_hosts.test.js
> +    assertUndefinedCompatibility('Debian', 'Grub2 UEFI SecureBoot');
Do similar tests for RHEL make sense?

2017-08-29 10:37 UTC, tstrachota commented on webpack/assets/javascripts/foreman_hosts.test.js
> +    assertUndefinedCompatibility('Debian', 'Grub2 UEFI SecureBoot');
I added such tests for RHEL too.

2017-08-29 10:40 UTC, tstrachota commented
@lzap updated. The warning now works also after hostgroup change.

At the moment it works only in the host form. Do you think we should add it at the hostgroup form too?

2017-08-30 09:23 UTC, lzap approved these changes

2017-08-30 09:24 UTC, lzap commented
All postgresql tests failed, do you think these are relevant @tstrachota ?

2017-08-30 09:33 UTC, lzap commented
I have two small things.

Can you please reword the text to: _This combination of loader and OS might not be able to boot._ This is shorter and no irrelevant "testing" word is used. I would drop the Warning prefix as well.

Can you add PXELoader UEFI to show warning in all cases. There is no stable build of this, we should show the warning in all cases really.

2017-08-30 11:45 UTC, tstrachota commented
Updated, @lzap

2017-09-04 11:31 UTC, merged

2017-09-04 11:31 UTC, lzap commented
Thank you, merged.

2017-09-05 06:23 UTC, ohadlevy commented
@lzap this PR had a failing tests for foreman, why was it merged? develop is currently broken...

2017-09-07 09:41 UTC, lzap commented
Sorry, it way my mistake, I was under impression this is some kind of JS random bug. I can clearly see the errors now. Thanks for fixing this @bastilian and @dLobatog and I apologize.