Fixes #20705 - display paginations section on audits page correctly
theforeman/foreman pull request #4799
Opened 2017-08-30 15:38 UTC by lizagilman

2017-08-31 12:16 UTC, iNecas commented
@lizagilman please provide the screenshots of before and after changes for the UI updates, it helps with review a lot. Doing this for now from the testing:

Before:
![audits-before](https://user-images.githubusercontent.com/190443/29922658-d43b749e-8e56-11e7-97db-b1223a9f47d7.png)

After:
![audits-after](https://user-images.githubusercontent.com/190443/29922666-d95619a2-8e56-11e7-9d9b-427705c03e73.png)

The positioning still doesn't feel right to me. Curious  about @Rohoover ideas

2017-09-01 08:19 UTC, ares commented
@iNecas note that the audit page should change so this pagination might be in right direction. I think we agreed with @Rohoover that audit list should be regular table.

2017-09-01 11:39 UTC, iNecas commented
Shouldn't we do it right away then?

2017-09-01 18:38 UTC, ares commented
I guess it's up to @lizagilman, I can imagine it as a separate PR as this fixes pagination, which should be brought to 1.16. Converting to table will be followed by discussion about what the table should contain, how it should look like etc

2017-09-02 05:59 UTC, iNecas commented
My only concern is we will merge this while putting converting the table to a backlog which could lead to have the page in half done state for unknown amount of time. Therefore I would like to see either the pagination fitting better (with the least amont of effort) in the page or finishng the whole table.

2017-09-06 14:26 UTC, lizagilman commented
How about this until we"ll switch to table -
![image](https://user-images.githubusercontent.com/15361156/30117272-63cb8eca-9328-11e7-954d-e4b9bd66e153.png)

2017-09-06 16:44 UTC, iNecas reviewed
That works much better visualy. Let's find the best way to achieve it

2017-09-06 16:44 UTC, iNecas commented on app/views/common/_pagination.html.erb
> +  class='col-md-12 <%= "audits-pagination" if @page_header == "Audits" %> content-view-pf-pagination table-view-pf-pagination paginate' id='pagination'
The page header might change based on localization. Could we override the color in css using dome css selector rather than doing if here?

2017-09-07 09:26 UTC, dLobatog requested changes
Setting to WoC based on @iNecas 's comment

2017-09-10 13:22 UTC, lizagilman commented
updated
@iNecas not exactly what you suggested but at least got rid of the `if ` ...

2017-09-11 07:39 UTC, iNecas commented
Works for me. Deferring to @amirfefer to have a final word on this or whether he has other ideas to do it differently.

2017-09-11 14:41 UTC, tbrisker approved these changes
WFM. Getting the pagination to display properly with the current layout is a separate issue to changing the layout completely which will be done in the future. @rohoover - can you please ACK the layout in the latest screen shot for an intermediate stage until the entire page layout is modified?

2017-09-14 15:42 UTC, Rohoover commented
I think it's fine as an intermediate solution. Thanks!

2017-09-14 15:48 UTC, iNecas commented
There are conflicts on the branch: I'm ok with merging afterwards, unless anyone opposes it before this happens

2017-09-14 15:48 UTC, iNecas approved these changes

2017-09-20 12:32 UTC, dLobatog approved these changes

2017-09-20 12:33 UTC, dLobatog commented
Thanks @lizagilman !

2017-09-20 12:33 UTC, merged