Fixes #20905 - Add a message in audit in case there are no changes to…
theforeman/foreman pull request #4832
Opened 2017-09-14 10:43 UTC by shiramax

Added the following message in audit : 
![image](https://user-images.githubusercontent.com/5609929/30425260-47ed71c6-9951-11e7-8a9f-0e71d9021ec5.png)

@Rohoover , what do you think about the design? thanks.

2017-09-14 10:45 UTC, shiramax commented
Added the following message in audit : 
![image](https://user-images.githubusercontent.com/5609929/30425260-47ed71c6-9951-11e7-8a9f-0e71d9021ec5.png)

@Rohoover , what do you think about the design? thanks.

2017-09-14 10:58 UTC, ares commented
There was a recent improvement no template history tab too, see #4773 I think it would be good to display it the same way. 
![template](https://user-images.githubusercontent.com/109773/30426439-59c23706-994c-11e7-9e46-b7b1439f45d8.png)

2017-09-14 11:44 UTC, shiramax commented
@ares , 
Is this better? 
![image](https://user-images.githubusercontent.com/5609929/30428125-235e759e-995b-11e7-9003-a46c526755b4.png)

2017-09-14 13:26 UTC, Rohoover commented
![bitmoji](https://render.bitstrips.com/v2/cpanel/8363918-131321122_2-s4-v1.png?transparent=1&palette=1&width=246)

2017-09-15 20:07 UTC, ares requested changes
It's much better but now I think it does not behave correctly. See the screenshot for new template and update of existing one when I changed name and template content at the same time

![tmp1](https://user-images.githubusercontent.com/109773/30501288-2eecf2fc-9a62-11e7-890e-9fb0819ee8b0.png)
![tmp2](https://user-images.githubusercontent.com/109773/30501289-2ef52cf6-9a62-11e7-9e78-211daa07c053.png)

2017-09-17 18:51 UTC, shiramax commented
@ares, yes I think I fixed it now, please let me know what you think.

2017-09-19 12:47 UTC, tbrisker reviewed
minor nitpick - looks like a large part of the diff is an indentation change making it more difficult to see what changed. Could you please make sure you stay with the indentation level we use everywhere (2 spaces per level)?

2017-09-20 13:34 UTC, ares requested changes
it now works great, one comment in the code and then good to go

2017-09-20 13:34 UTC, ares commented on app/views/audits/show.html.erb
> +        <%if @audit.audited_changes.key?("template") && @audit.audited_changes.length==1 %>
please add a space after `<%` and around `==`, also I think `@audit.audited_changes.size` is prefered

2017-09-20 21:18 UTC, shiramax commented
@ares, Done :)

2017-09-21 21:02 UTC, ares approved these changes

2017-09-21 21:04 UTC, ares commented
Works just great, the indentation now looks correct. Thanks @shiramax, merged as d79cc18d1c5bd5d71d4b2a22370c5254635cae27

2017-09-21 21:04 UTC, closed without merging