Fixes #20890 - changes SSH key validation messages
theforeman/foreman pull request #4834
Opened 2017-09-14 15:17 UTC by shiramax

2017-09-18 18:17 UTC, tstrachota commented
:+1: Tested on hammer and it works well:
```
> hammer user ssh-keys add --user john --name Key --key "wrong format" 
Could not add SSH Key:
  Key is not a valid public ssh key
  Key must be in OpenSSH public key format.
  Fingerprint could not be generated
  Length could not be calculated
```

2017-09-19 02:38 UTC, boaz0 approved these changes
:+1 SGTM

2017-09-19 07:01 UTC, ares requested changes
in UI, the message is composed with other validation messages, so it does not work well with sentences

![key](https://user-images.githubusercontent.com/109773/30579470-1da36148-9d19-11e7-83c7-b5d0b900a281.png)

2017-09-19 07:01 UTC, ares commented on app/models/ssh_key.rb
> +    :format => { with: /\A(ssh|ecdsa)-.*\Z/, message: N_('must be in OpenSSH public key format.') }
the dot should not be part of the message, see the screen below

2017-09-19 12:38 UTC, shiramax commented
@ares , Thanks , I removed the dot.

2017-09-20 10:13 UTC, ares approved these changes

2017-09-20 10:15 UTC, ares commented
Thanks @shiramax, merged as 4a96211d33c261655c887bbb6c787e38d883200a

2017-09-20 10:15 UTC, closed without merging