Fixes #20940 - Interfaces shows extra fields in API /api/hosts/id
theforeman/foreman pull request #4853
Opened 2017-09-18 10:07 UTC by snagoor

This fix is to have a consistency between REST API `/api/hosts/:id` and `/api/hosts/:id/interfaces` where many important flags such as `managed`, `virtual`  are hidden in the former call and shows additional details in interfaces API call.

2017-09-18 10:12 UTC, snagoor commented
After the fix 
~~~
    "interfaces": [
        {
            "id": 5,
            "name": "client.example.com",
            "ip": "192.168.121.65",
            "ip6": null,
            "mac": "52:54:00:a5:d6:b7",
            "fqdn": "client.example.com",
            "identifier": "ens3",
            "managed": true,
            "primary": true,
            "provision": true,
            "virtual": false,
            "created_at": "2017-08-07 05:39:33 UTC",
            "updated_at": "2017-08-07 05:39:37 UTC",
            "domain_id": null,
            "domain_name": null,
            "subnet_id": null,
            "subnet_name": null,
            "type": "interface"
        }
~~~

2017-09-18 14:12 UTC, dLobatog requested changes
Thanks @snagoor , how about introducing a test that checks that the response for api/v2/hosts/interfaces and api/v2/hosts have the same attributes in the interfaces array? That way we ensure the inconsistency will not happen anymore.

2018-04-27 16:31 UTC, tstrachota commented
@snagoor would you mind to rebase?

I think that we should fix this one by including `interfaces/main.json.rabl` from `hosts/show.json.rabl` rather than by moving attributes from `base` to `main`. Since it's a detail info request for just one host it should be ok to provide full details. Interfaces are important aspect.

2018-07-02 08:54 UTC, amitkarsale commented
@snagoor any blocker you are facing over the PR?

2018-08-23 10:37 UTC, amitkarsale commented
On 1-0-1 conversation with @snagoor will take over this PR. Closing this PR and creating a new one.

2018-08-23 10:39 UTC, amitkarsale commented
Oops, I just realized I dont have close PR permissions. ;)
 @tstrachota or @dLobatog can you close this PR.

2018-08-23 11:10 UTC, closed without merging