Fixes #21015 - sync host and hostgroup rabl to show all_classes
theforeman/foreman pull request #4858
Opened 2017-09-19 17:35 UTC by ShimShtein

2017-09-20 11:06 UTC, dLobatog requested changes
Thanks @ShimShtein , could you add a test to ensure this remains fixed? http://projects.theforeman.org/issues/5631 fixed it originally then it got broken again

2017-09-24 09:29 UTC, ShimShtein commented
Test added

2017-09-24 14:55 UTC, tbrisker approved these changes

2017-09-24 14:55 UTC, merged

2017-09-24 14:56 UTC, tbrisker commented
Thanks @ShimShtein !