Fixes #21037 - use Host::Base as auditable_type
theforeman/foreman pull request #4864
Opened 2017-09-20 19:42 UTC by iNecas

Otherwise, we are hitting "Invalid single-table inheritance type:
Host::Discovered is not a subclass of Host::Managed" when converting the
host from discovered to managed.

2017-09-20 19:55 UTC, iNecas commented
Discovery tests running here http://ci.theforeman.org/job/test_plugin_matrix/3768/

2017-09-21 05:26 UTC, iNecas commented
@lzap this should help you with the "Invalid single-table inheritance type: Host::Discovered is not a subclass of Host::Managed" issue. The other test failures should be just regular rails5 deprecation warnings.

2017-09-21 12:36 UTC, iNecas commented on app/controllers/api/base_controller.rb
> +        association = resource_class.reflect_on_all_associations.find {|assoc| assoc.class_name == 'Host::Base'}
whatever

2017-09-21 14:50 UTC, iNecas commented
In case anyone interested: all green :)

2017-09-21 16:02 UTC, lzap commented
@iNecas dude you kick ass! Lemme take a look, may I ask for double review @mhulan or anyone

2017-09-21 16:07 UTC, lzap approved these changes
Cool, WFM. The find vs detect was not related, wasn't it?

2017-09-21 16:25 UTC, iNecas commented
No, it was hound barking

2017-09-21 18:07 UTC, ares commented on app/models/concerns/audit_extensions.rb
> +    self.associated_type = "Host::Base"         if associated_type =~ /Host::/
this is exactly the reason why we shouldn't align code with whitespaces :-) could you please remove them?

2017-09-21 18:25 UTC, ares requested changes
The problem now is that any host audit is logged as change to Host/Base (see the screenshot). If for some reason we need this, we should make sure, it's presented as a Host. It should be also listed here https://github.com/theforeman/foreman/blob/develop/app/helpers/audits_helper.rb#L2, https://github.com/theforeman/foreman/blob/develop/app/helpers/audits_helper.rb#L118 and some other places in audits helper.

There are other places that would need to be updated, https://github.com/theforeman/foreman/blob/develop/app/views/audits/show.html.erb#L6

Would it be better to take the same approach as we did for templates STI? See https://github.com/theforeman/foreman/pull/4778 for what I mean.

![host](https://user-images.githubusercontent.com/109773/30739940-67132f0c-9f8f-11e7-86a6-d8331e7a8ab0.png)

2017-09-22 08:39 UTC, iNecas commented
Screenshot missing

2017-09-22 08:42 UTC, iNecas commented
I don't think https://github.com/theforeman/foreman/pull/4778 is the same, as in host case we actually change the type of the class as we go (from Discovered to Managed), while in templates, this is immutable. I will try to update the missed places.

2017-09-22 09:30 UTC, iNecas commented
Nm for the screenshots: I've seen it by myself: updated + addressed other comments.

2017-09-22 15:46 UTC, lzap commented
LGTM @ares ?

2017-09-22 17:16 UTC, ares commented
Sorry to keep asking... how does this happen in the first place? I don't see `audited` definition in Host::Discovered nor Host::Base, it's in Host::Managed only. AFAIK there's no Managed -> Discovered transition. I don't want to block it, just want to understand, what we're trying to solve here. This basically means any subclass of Host will be audited as generic Host. No way to search audits based on host type. I know we have only managed and discovered hosts so far, but before we commit to this, I'd like to know why :-)

2017-09-25 07:03 UTC, iNecas commented
That's definitely valid reason to ask.

The problem is, when saving the audit records for the host, the audit record is being created first, and as part of the process, the auditable record (the host) is being loaded again from the database: and this is where the issue comes, as the auditable_type was marked as `Host` which translates to `Host::Managed` and the `Host::Discovered` was set in the database, which lead to the error `"Invalid single-table inheritance type: Host::Discovered is not a subclass of Host::Managed`.

Since we allow transitions of types for host record, I think it makes sense to keep the auditable_type as `Host::Base`. Honestly, the Host should not be an STI in first place and discovered host should be just a record on it's own: but that's outside of scope for this PR

2017-09-25 12:05 UTC, lzap commented
@ares hey are we good to go?

2017-09-26 16:30 UTC, ares requested changes
Just one tiny thing re icons, otherwise seems to work fine, good to merge afterwards

2017-09-26 16:30 UTC, ares commented on app/helpers/audits_helper.rb
> +               when "Host::Base"
this is `'Host'` actually, since audited_type converts it

2017-09-26 17:00 UTC, ares approved these changes

2017-09-26 17:00 UTC, ares commented
Ready for merge pending tests

2017-09-26 19:52 UTC, iNecas commented
Tests are green

2017-09-27 06:39 UTC, merged

2017-09-27 06:39 UTC, lzap commented
Thanks a bunch folks, really appreciated for unblocking discovery tests.

2017-09-27 07:06 UTC, ares commented
I set the release to 1.17, @lzap if you want this to be cherry-picked to 1.16, please updated the redmine issue. If it's accepted, then you should also do the cherry-pick to 1.16-stable.

2018-06-15 05:20 UTC, kotyara85 commented
Facing the same issue on 1.17. Can't provision hosts unless I'm an admin. https://projects.theforeman.org/issues/23869