Fixes #21105 - hostgroup provisioning without media
theforeman/foreman pull request #4874
Opened 2017-09-26 08:43 UTC by lzap

There is no medium associated when Katello plugin is installed and Synced Content is selected. This breaks hostgroup provisioning.

Workaround described in:
https://www.youtube.com/watch?v=Dc5DN_Xov40

It is essentially about "do not use Synced Media".

When testing this patch, make sure Katello is installed.

2017-11-15 06:47 UTC, dLobatog requested changes
@lzap I'm seeing a similar problem just doing regular provisioning. After submitting the Host form, it change from Synced Content to All Media - since there's no Installation Media, Host creation fails

Do you think these 2 are related and if so any idea what's going on?

2017-11-15 06:54 UTC, dLobatog commented
Basically after submitting, the form bounces from:

![screenshot from 2017-11-15 07-54-22](https://user-images.githubusercontent.com/598891/32822726-350c4c76-c9da-11e7-99a6-d386a255b8c8.png)


to:

![screenshot from 2017-11-15 07-50-28](https://user-images.githubusercontent.com/598891/32822705-1ad5fd8e-c9da-11e7-86fd-d8006ca71000.png)

2017-11-15 07:01 UTC, dLobatog commented
Actually that one comes from a problem in Katello I just found - nevermind. Can you write any tests for this PR?

2017-11-23 14:36 UTC, lzap commented
I will take a look thanks, another patch was proposed in https://bugzilla.redhat.com/show_bug.cgi?id=1449290#c10

2018-01-16 16:41 UTC, lzap commented
Added one extra check for pxe_files method.

2018-06-26 09:14 UTC, lzap commented
Rebased, test present, @dLobatog

2018-08-07 14:08 UTC, dLobatog submitted a review, later dismissed

2018-08-07 14:09 UTC, dLobatog commented
Thanks @lzap , this completely slipped off my radar - could you rebase & I'll merge if :green_apple:

2018-08-09 07:11 UTC, lzap commented
The new media framework fixed the issue, this shrink down to just an extra test.

2018-09-01 14:48 UTC, mmoll approved these changes

2018-09-01 15:22 UTC, merged

2018-09-01 15:23 UTC, mmoll commented
merged, díky @lzap!