Fixes #21420 - Add the name of the file in Edit file
theforeman/foreman pull request #4936
Opened 2017-10-23 12:22 UTC by shiramax

2017-10-24 13:07 UTC, shiramax commented
[test foreman]

2017-10-24 13:08 UTC, shiramax commented
[test katello]

2017-10-25 15:05 UTC, amirfefer requested changes

2017-10-25 15:05 UTC, amirfefer commented on app/helpers/form_helper.rb
> +        html += content_tag(:span) {"Current file os '#{options.delete(:file_name)}', upload a new file to change it" + ' ' || '' }
1. you don't have to use block for span's content
2. string should be extracted for translation.
3.  typo? (os = is?)

2017-10-25 15:05 UTC, amirfefer commented on app/helpers/form_helper.rb
> +      html = ''
I found this unnecessary a bit.
consider  using nesting fields or inline if statement?

2017-10-31 10:26 UTC, dLobatog approved these changes
Thanks  @shiramax  @amirfefer

2017-10-31 10:26 UTC, merged