Fixes #21135 - Add tooltip for overridden flag icon
theforeman/foreman pull request #4938
Opened 2017-10-23 15:32 UTC by shiramax

![image](https://user-images.githubusercontent.com/5609929/31897954-86c5b88e-b820-11e7-9fb7-2e19973d8bfa.png)

2017-10-23 15:41 UTC, ohadlevy commented on app/views/puppetclasses/_form.html.erb
> +                  <div class="clip"><%= icon_text((key.override ? "flag": ""), key.to_s.tr('_',' '), :kind => 'fa', :title=>"Overridden") %></div>
please make sure you extract the string, thanks :)

2017-10-24 11:19 UTC, shiramax commented
@ohadlevy , 
Done, thanks.

2017-10-24 11:46 UTC, ohadlevy commented
@orrabin can you review please?

2017-10-31 09:32 UTC, orrabin commented
lgtm. I think we should change the tooltip on the key to only appear for long keys, that would make it easier to find the flag tooltip but that could be addressed in a separate pr.

2017-11-01 11:54 UTC, ohadlevy commented
in that case, can you add a test please?

2017-11-01 12:35 UTC, shiramax commented
@orrabin, 
I created the issue: http://projects.theforeman.org/issues/21543 thanks.
@ohadlevy ,
Which test do you want to add?

2017-11-02 14:36 UTC, ohadlevy commented
@shiramax something like the fact that the string is getting shorter if its longer than...?

2017-11-02 15:37 UTC, shiramax commented
@ohadlevy , 
Thanks, I think it should be addressed in a different PR, 
I already created this PR: https://github.com/theforeman/foreman/pull/4971 .

2017-11-03 13:17 UTC, dLobatog requested changes
Thanks @shiramax , I think @ohadlevy 's comment is already addressed in https://github.com/theforeman/foreman/pull/4971 , but the test isn't there. 

Can you update this PR to include a test for that? It doesn't have to be an integration test, you can simply extract the `key.size > 43` to a method in `app/helpers` and unit test the method.

2017-11-08 14:18 UTC, shiramax commented
@dLobatog , @ohadlevy ,
I added the tests, Thanks.

2017-11-10 09:09 UTC, dLobatog approved these changes

2017-11-10 09:09 UTC, dLobatog commented
Thanks @shiramax !

2017-11-10 09:09 UTC, merged