Fixes #21502 - Disable editing users in group with EUG
theforeman/foreman pull request #4962
Opened 2017-10-30 12:59 UTC by dLobatog

Adding Users to User Groups with External User Groups does not
work. Currently the only feedback the user gets is that Users get
automatically removed after the form is submitted - no warning or
mention.

In order not to confuse the user or make the user waste their time
adding users, we should display a warning when there are External User
Groups linked to a User Group.

------------------------------------

This should contain tests and should not be merged as is, just opening it to keep track of it and maybe get early feedback

2017-10-30 16:09 UTC, ares reviewed
Can't we just skip users that has auth source set to INTERNAL? That way you could combine both internal and ldap users in a single user group.

2017-10-31 06:49 UTC, dLobatog reviewed
@ares I've made it skip internal users, and it works well in the UI case, there is a warning and the user know about this behavior. The original bug mentions how this behavior is disconcerting in hammer too - should we add a warning in hammer for this command or can you think of any other option? Returning extra data in the API response doesn't seem quite right to me.

2017-10-31 12:28 UTC, dLobatog commented
Updated to include a warning in the API description and allow to add/remove internal users freely.

2017-11-13 15:33 UTC, ares requested changes
The functionality works great. To be consistent with other pages, the warning should not be created using alert. We replaced it with simple `<h5>` separated with `<hr>`, see https://github.com/theforeman/foreman/blob/develop/app/views/roles/_form.html.erb#L13-L23 for an example.

Otherwise ready to merge.

2017-11-14 06:29 UTC, dLobatog reviewed
@ares Updated to use h5 instead of alert, check out the screenshot

2017-11-14 06:30 UTC, dLobatog commented
![screenshot from 2017-11-14 07-27-09](https://user-images.githubusercontent.com/598891/32766091-a18df58e-c90d-11e7-9923-fefa7433dfe6.png)

2017-11-14 06:30 UTC, dLobatog commented on app/views/usergroups/_form.html.erb
> +          <br>
I've split this into 2 strings so that it's easier to translate.

2017-11-14 08:23 UTC, ares commented
@dLobatog it seems something went wrong and there FactoryGirl again in usergroup_test :-) 

http://ci.theforeman.org/job/test_develop_pr_core/15077/database=sqlite3,ruby=2.2,slave=fast/testReport/junit/(root)/UsergroupTest__external%20usergroups/test_0006_internal_auth_source_users_remain_after_refresh/

2017-11-14 08:28 UTC, ares commented
One more tiny thing, in role there's spacing between two warning. I'm not sure if here we can consider it as two separate warnings but I think it would be more readable if both are separate `<h5>` and it would look more consistent with role form.

![0label](https://user-images.githubusercontent.com/109773/32769952-23373306-c91e-11e7-9251-a063619ca715.png)
![1label](https://user-images.githubusercontent.com/109773/32769953-233a1918-c91e-11e7-872e-d46fc8363f59.png)

2017-11-14 08:39 UTC, dLobatog commented
@ares Updated to use FactoryBot & use 2 h5, it looks like this now:

![screenshot from 2017-11-14 09-38-01](https://user-images.githubusercontent.com/598891/32770375-a7ef0ef6-c91f-11e7-84df-6f60d2dd1f9c.png)

2017-11-14 08:44 UTC, ares commented
Ack pending jenkins

2017-11-14 08:44 UTC, ares approved these changes

2017-11-14 11:14 UTC, merged

2017-11-14 11:14 UTC, ares commented
Thanks @dLobatog, merging!