fixes #21592 - uses headless chrome instead of phantomjs
theforeman/foreman pull request #4987
Opened 2017-11-07 12:20 UTC by ohadlevy

it seems that we can also cut down the default waiting time
which hopefully will speed up our tests.

2017-11-07 15:05 UTC, waldenraines submitted a review, later dismissed
Nice change, approved pending green tests.

2017-11-08 08:45 UTC, ohadlevy commented
@mmoll @ekohl any idea why the test fail? I'm installing chromedriver via npm (search from chromedriver in  http://ci.theforeman.org/job/test_develop_pr_core/14979/database=postgresql,ruby=2.2,slave=fast/consoleFull) and I'm using the relative path at https://github.com/theforeman/foreman/pull/4987/files#diff-7a6aaeae51145fd37e71db58212fd18bR15) which of course works locally. how can I debug / troubleshoot this?

2017-11-08 09:03 UTC, ekohl commented
According to https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver it expects chrome to be in ```/usr/bin/google-chrome```. You're just installing the driver and I think we need to look at a package installation of chrome. A quick search for RPMs doesn't show me any for centos7 so I'll need to dive into it. Since it's selenium it should also support firefox which may work better on centos7 slaves. Need to dive into it a bit to figure out our options.

2017-11-08 09:04 UTC, ohadlevy commented
I was under the assumption that I was override it - (its possible via
https://sites.google.com/a/chromium.org/chromedriver/capabilities#TOC-Using-a-Chrome-executable-in-a-non-standard-location
)

also, we could consider setting up a symlink?

On Wed, Nov 8, 2017 at 11:03 AM, Ewoud Kohl van Wijngaarden <
notifications@github.com> wrote:

> According to https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver it
> expects chrome to be in /usr/bin/google-chrome. You're just installing
> the driver and I think we need to look at a package installation of chrome.
> A quick search for RPMs doesn't show me any for centos7 so I'll need to
> dive into it. Since it's selenium it should also support firefox which may
> work better on centos7 slaves. Need to dive into it a bit to figure out our
> options.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/theforeman/foreman/pull/4987#issuecomment-342753799>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AABOx1g61pQOp2iOo0XfK45gy3n8OHBIks5s0W5JgaJpZM4QUtDX>
> .
>

2017-11-08 09:08 UTC, ekohl commented
But the entire chrome browser isn't on NPM, only the chrome driver for selenium. One reason I can think of why chrome isn't packaged for EL7 is that it uses some kernel features for sandboxing that the EL7 kernel doesn't support, but this is speculation from my side. It may be that the Fedora packages do work. One path we can choose is to get Fedora slaves for the UI tests but I'd prefer to try a more generic solution first with Firefox.

2017-11-08 09:10 UTC, ohadlevy commented
On Wed, Nov 8, 2017 at 11:08 AM, Ewoud Kohl van Wijngaarden <
notifications@github.com> wrote:

> But the entire chrome browser isn't on NPM, only the chrome driver for
> selenium. One reason I can think of why chrome isn't packaged for EL7 is
> that it uses some kernel features for sandboxing that the EL7 kernel
> doesn't support, but this is speculation from my side. It may be that the
> Fedora packages do work. One path we can choose is to get Fedora slaves for
> the UI tests but I'd prefer to try a more generic solution first with
> Firefox.
>
>
>
Are you suggesting we will drop this pr in favor of firefox based
approach?

2017-11-08 09:14 UTC, ekohl commented
That would be my suggestion to start with. I have experience with using Firefox + Selenium on CentOS7 and generally that works well. If the setup code is generic enough we can support chrome via an env var for users who prefer that on their desktops.

Note that Firefox and xvfb are already installed on our slaves but the job config may need to be modified. Looks like the 1.11-stable job uses it.

2017-11-08 09:18 UTC, ohadlevy commented
On Wed, Nov 8, 2017 at 11:14 AM, Ewoud Kohl van Wijngaarden <
notifications@github.com> wrote:

> That would be my suggestion to start with. I have experience with using
> Firefox + Selenium on CentOS7 and generally that works well. If the setup
> code is generic enough we can support chrome via an env var for users who
> prefer that on their desktops.
>
> Note that Firefox and xvfb are already installed on our slaves but the job
> config may need to be modified. Looks like the 1.11-stable job uses it.
>

the fact is that currently the tests are: a. slow b. inaccurate as they
represent an old browser env (which imho is no longer relevant to our users
- e.g. IE). I would like to unblock / improve our test infrastructure.
whats the timeline you had in mind to implement this? thanks.

2017-11-08 09:25 UTC, ekohl commented
That makes total sense, but I haven't thought about it. We have a few priorities to balance no. I think that Rails 5.1 SCL + Updated Ruby is also a high priority blocker for developers but the fixing the Dynflow service for the 1.16 release is my top priority. Perhaps this is small enough to do it before the Rails 5.1 effort but I'll get back to you on that.

2017-11-08 09:29 UTC, ohadlevy commented
another option is to run it on travis - as its already configured to support chrome.
the main problem is that currently travis works on one language at a time (e.g. ruby or node) and not both.

2017-11-08 09:33 UTC, ekohl commented
Travis has matrix builds. See https://github.com/theforeman/puppet-foreman/blob/master/.travis.yml for how we use separate RVMs. Pretty sure you can choose a different language in the ```include```.

2017-11-08 09:34 UTC, ohadlevy commented
I failed to make this work (tried at
https://github.com/ManageIQ/manageiq-ui-classic/pull/2540) without success.

On Wed, Nov 8, 2017 at 11:33 AM, Ewoud Kohl van Wijngaarden <
notifications@github.com> wrote:

> Travis has matrix builds. See https://github.com/theforeman/
> puppet-foreman/blob/master/.travis.yml for how we use separate RVMs.
> Pretty sure you can choose a different language in the include.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/theforeman/foreman/pull/4987#issuecomment-342761267>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AABOx7RcA5atzFRv5HiQOkPqEqilqbZMks5s0XVRgaJpZM4QUtDX>
> .
>

2017-11-08 09:36 UTC, ekohl commented
It appears you're right: https://github.com/travis-ci/travis-ci/issues/4090

2017-11-08 12:43 UTC, ehelms commented
The Travis configuration is already running node based tests. Where does the Ruby part come into play?

2017-11-08 12:49 UTC, ohadlevy commented
@ehelms chrome integration tests run against the rails server.... you need to be able to execute ```rake jenkins:integration```

2017-11-08 12:53 UTC, ehelms commented
One broader issue I will point out is that our current standard devel environment via Forklift is based on using CentOS 7 given that is the production RPM distro we support. This change would imply that developers could no longer run these tests within the local environment.

Has anyone tried installing the 'Fedora' only Chrome on EL7? From what I read, when they dropped it they dropped it intending to drop for EL6 but dropped it for all. Should be a fairly easy test on a Forklift environment to configure:

```
[google-chrome]
name=google-chrome - \$basearch
baseurl=http://dl.google.com/linux/chrome/rpm/stable/\$basearch
enabled=1
gpgcheck=1
gpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub
```

Install chrome and try this PR out. If that works, then we can add this to our slaves no?

2017-11-08 12:54 UTC, ehelms commented
@ohadlevy ahh so these are for the older JS tests not the new ones coming with the React changes? Or even those requires a running Rails server?

2017-11-08 12:59 UTC, ohadlevy commented
> ahh so these are for the older JS tests not the new ones coming with the React changes? Or even those requires a running Rails server?

this PR aim is to replace phantomjs with headless chrome- the motivation is to:
1. reduce integeration test time
2. use a more modern infrastructure - phantomjs seems like a less of an ideal tool today, we need polyfills etc as its emulated fairly older browsers.
(I must admit I don't know if we have an official minimum browser defined anywhere).

regarding the tests itself:
1. phatomjs and chrome are both doing full end to end tests using an automated browser - you require a 
full rails server.
2. webpack based code tests (using jest) do not require a browser - they run purely in travis today using jsdom.

2017-11-09 14:12 UTC, ehelms commented
So testing this out, I was able to install Chrome on EL7 without issues (running the tests now) using that repository. From what I read, they "pulled" Chrome from EL6 due to incompatibility and in the process pulled it from all all EL despite it still working just fine.

Assuming tests pass, I'd opt for adding this repository to our slaves and allowing the use of Chrome here.

2017-11-09 14:28 UTC, ekohl commented
@ehelms I think that's fine.

2017-11-11 18:04 UTC, ohadlevy commented
@ehelms whats the next step ?

2017-11-13 09:42 UTC, dLobatog reviewed
@ohadlevy @ehelms @ekohl I think a good strategy to move forward is:

* Installing chrome alongside firefox/phantomjs in our slaves
* Making sure tests pass on Jenkins in this PR 
* Remove phantomjs/firefox

I've submitted https://github.com/theforeman/foreman-infra/pull/381, as soon as that is merged please trigger the tests here again to see if they pass. I'd be thrilled to see a `default_max_wait_time=5` working 😄

2017-11-20 21:31 UTC, dLobatog commented
[test foreman]

2017-11-20 21:32 UTC, dLobatog reviewed
PR from foreman-infra got merged, hopefully chrome is available on the slaves that will run the tests

2017-11-21 08:31 UTC, ohadlevy commented
[test foreman]

2017-11-24 06:32 UTC, dLobatog reviewed
From the tests, `chromedriver` would also be needed on Jenkins.

```
Selenium::WebDriver::Error::WebDriverError:  Unable to find chromedriver. Please download the server from http://chromedriver.storage.googleapis.com/index.html and place it somewhere on your PATH. More info at https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver....
```

2017-12-20 14:53 UTC, dLobatog commented
[test foreman]

2017-12-20 16:10 UTC, dLobatog requested changes
@ohadlevy Looks like a few tests are failing

2017-12-20 16:18 UTC, ohadlevy commented
@dLobatog rebased.

2018-01-05 02:32 UTC, mmoll commented
[test foreman]

2018-01-05 02:43 UTC, mmoll commented
@ohadlevy please rebase

2018-01-05 20:34 UTC, mmoll commented
@ohadlevy a log of tests fail and I have the feeling a lot of tests are run with this new configuration the first time after a long while... how can that be?

2018-02-14 08:49 UTC, dLobatog commented
[test foreman]

2018-02-14 09:32 UTC, dLobatog requested changes
@ohadlevy I think this needs rebasing so tests pass, could you try that? Thanks!

2018-02-17 17:08 UTC, mmoll commented
rebased, no change.

2018-03-12 10:42 UTC, ohadlevy commented
@dLobatog @mmoll - can we upgrade the chrome version?

2018-03-12 11:58 UTC, mmoll commented
Currently not, as it was agreed to use the chromium version coming in EPEL.

2018-05-04 01:40 UTC, mmoll commented on test/integration_test_helper.rb
> +    visit '/'
while this fixes some tests, some are also failing because of this (e.g. `TEST=test/integration/fact_value_test.rb`)

2018-05-04 01:56 UTC, mmoll commented
I think the changes itself are OK, somebody:tm: would need to have a look into the problem with the cookies vs. visting a page first and then fix a few remaining problems.

2018-07-04 13:20 UTC, ohadlevy commented
closing in favor of #5770

2018-07-04 13:20 UTC, closed without merging