Fixes #21602 - Add scoped_search on host.id for reports
theforeman/foreman pull request #4989
Opened 2017-11-08 12:17 UTC by xprazak2

2017-11-08 15:48 UTC, tbrisker requested changes

2017-11-08 15:48 UTC, tbrisker commented on app/models/report.rb
> +      scoped_search :relation => :host,        :on => :id,    :complete_value => true, :rename => :host_id
Why not search on the `host_id` column? it would save a potentially painful join with the host table. Also, please make this only explicit.

2017-11-09 08:24 UTC, xprazak2 commented
I changed to search on `reports.host_id` column.

2017-11-09 09:37 UTC, tbrisker requested changes

2017-11-09 09:37 UTC, tbrisker commented on app/models/report.rb
> +      scoped_search :on => :host_id,     :complete_value => true, :only_explicit => true
@ares made a good comment on the similar GH-4993 - please make complete_value false so it doesn't auto-suggest all host ids.

2017-11-09 15:27 UTC, xprazak2 commented
I changed it to `:complete_value => false`

2017-11-09 15:35 UTC, tbrisker approved these changes

2017-11-09 20:47 UTC, merged

2017-11-09 20:48 UTC, tbrisker commented
Thanks @xprazak2

2017-11-10 07:11 UTC, ares commented
Setting release to 1.17