fixes #21657 - remove facets when host is removed
theforeman/foreman pull request #5004
Opened 2017-11-14 13:35 UTC by timogoebel

Without this, you have to manually delete the facets from the database. There is no automatic cleanup.

cc: @ShimShtein

2017-11-15 08:36 UTC, timogoebel commented
I see a lot of test failures like
```
PG::UndefinedTable: ERROR:  relation "test_classes" does not exist...
```

I believe, the tests aren't properly isolated. Will take a look.

2017-11-15 09:31 UTC, ShimShtein commented
@jlsherrill , @thomasmckay Any objections? Could it cause issues to Katello?

2017-11-15 21:51 UTC, jlsherrill commented
In katello we preferred this route, as deleting facets without deleting backend (candlepin or pulp) entities can lead to issues.  The idea being that deletion is directed through our foreman-task orchestration which properly removes those objects from the backend services before removing the facets and finally the host. 

One question though, how are you able to delete the host without deleting the facet first?  Are you missing a foreign key constraint on the host_id column on your facet?  It should prevent that.  

This change won't completely break katello (as i said the user ends up going through dynflow tasks when deleting a host), but may make it harder to detect if this breaks in the future.  Some sort of more official facet delete api may be nice, as i could see it useful for other things such as a puppet facet (where you may want to cleanup the puppet ca).

2017-11-20 11:37 UTC, sean797 commented
Do you think we should clear up any fact belonging to hosts that no long exist?

2017-11-21 11:14 UTC, ShimShtein commented
> Do you think we should clear up any fact belonging to hosts that no long exist?

We already [do this](https://github.com/theforeman/foreman/blob/develop/app/models/host/base.rb#L17)

2017-11-21 11:37 UTC, sean797 commented
Sorry I mean facets. This will stop it happening anymore, but should there be a migration to clear any stale facets already in the database?

2017-11-21 12:17 UTC, ShimShtein commented
@timogoebel, I think we should make it configurable - we can add another configuration option to `services/facets/entry.rb` and add `:dependent => destroy` accordingly.

2017-11-21 12:47 UTC, timogoebel commented
@ShimShtein: Sounds like a good idea. Do you (as the "facet guy") by any chance want to take this over? :-)

2017-12-27 13:19 UTC, timogoebel commented
@ShimShtein: Added a configuration parameter & tests.

2017-12-28 10:47 UTC, ShimShtein commented
[test foreman]

2017-12-28 10:54 UTC, timogoebel commented
Rebased to (hopefully) fix the tests.

2017-12-28 13:40 UTC, boaz0 approved these changes
LGTM 👍

2018-01-03 06:54 UTC, ShimShtein commented
[test foreman]

2018-01-03 08:31 UTC, timogoebel commented
Rebased.

2018-01-03 11:26 UTC, ShimShtein commented
@timogoebel Tests are still red

2018-01-03 14:18 UTC, timogoebel commented
*sights* pushes another attempt. I have a feeling, the configuration tests weren't isolated enough. I stubbed `Facets::ManagedHostExtensions.register_facet_relation` now. Hope, that helps.

2018-01-03 19:59 UTC, iNecas commented
It probably didn't

2018-01-10 08:52 UTC, timogoebel commented
Another attempt to fix the tests by reloading the host class following the suggestion by @ShimShtein.

2018-01-10 17:07 UTC, mmoll commented
please rebase :)

2018-01-11 08:02 UTC, timogoebel commented
Rebased.

2018-01-11 13:31 UTC, timogoebel commented
[test foreman]

2018-01-14 12:02 UTC, ShimShtein commented
[test foreman]

2018-01-14 12:22 UTC, boaz0 approved these changes
LGTM 💯

2018-01-14 13:39 UTC, tbrisker commented
[test foreman]

2018-01-23 09:32 UTC, ShimShtein commented
[test]

2018-01-23 09:48 UTC, timogoebel commented
I actually have a feeling, the test failure could be related to the reloading of the host object. But I haven't had time to investigate.

2018-02-01 14:21 UTC, timogoebel commented
I changed my opinion about the test failures being related. Rebased. Hopefully, tests are 🍏 now.

2018-03-21 19:36 UTC, mmoll commented
@timogoebel please rebase :)

2018-03-22 09:03 UTC, timogoebel commented
Rebased.

2018-03-25 14:01 UTC, tbrisker requested changes
I managed to reliably reproduce the test failures. They seem to be caused by the reloading of `host/managed.rb` in the facet test - commenting out those lines, or even just the one in `teardown` makes audit tests pass. Are you sure they are needed?
To reproduce locally: 
`SEED=30219 ruby -I.:test -e "ARGV.each{|f| require f}" test/unit/facet_test.rb test/models/concerns/audit_extensions_test.rb`

2018-03-25 14:01 UTC, tbrisker commented on app/services/facets/entry.rb
> +      @dependent = value if value.present?
This method looks like a combination of getter and setter, why not just use `attr_accessor`? Or name it in a way that has clear meaning, like `set_dependent_action`?

2018-03-26 08:18 UTC, timogoebel commented
@tbrisker: Thanks for taking a look. :-)

> Are you sure they are needed?

I just pushed a version with these lines commented out. Let's see what that breaks.

2018-03-26 09:32 UTC, ShimShtein commented
@tbrisker facets pollute the `Host::Managed` class with new relations. Those relations cannot be undone, so if you are adding a facet for test only, you end up with unwanted relation methods for all other tests. This is what started this whole mess.

2018-03-26 13:41 UTC, timogoebel commented
Tests passed without the reload code. I just pushed a version that renames the DSL to use `set_dependent_action`. I hope, we're good to go now. *sights*

2018-03-27 09:31 UTC, timogoebel commented
@tbrisker, @ShimShtein: Tests are green now. 🌲

2018-03-27 10:34 UTC, tbrisker submitted a review, later dismissed
Works for me, any more comments @ShimShtein ?

2018-03-28 18:36 UTC, ShimShtein commented on test/unit/facet_test.rb
> -  teardown do
Without those lines, cloning `Host::Managed` will try to clone `test_facet`. I don't think it's desirable.

After this test Host::Managed will contain all properties related to `test_facet` and `namespaced_facet`

2018-03-29 13:05 UTC, timogoebel commented
I re-added the teardown lines for the tests.

2018-04-01 09:54 UTC, tbrisker commented
@timogoebel I think you forgot to push, and I think it will still fail (it did when i was testing on the older version). Perhaps we need to find some other way to remove the association that doesn't include reloading the model.

2018-04-03 07:25 UTC, timogoebel commented
> Perhaps we need to find some other way to remove the association that doesn't include reloading the model.

To be honest, I'm out of ideas. I could try to not add the association in the first place by stubbing it, but otherwise: I have no idea how to proceed here. Suggestions are very welcome.

I'll push the change anyway, maybe it does pass tests.

2018-04-03 07:33 UTC, ShimShtein commented
I am not sure it's a good one, but maybe we can use an inherited throwaway class here?
Something along the lines:

``` ruby
class FacetTest < ActiveSupport::TestCase
  class TestHost < Host::Managed
  end
end
```
I am not sure it will work, and what ActiveRecord trickery we will need to invoke, but at least it will not pollute the original `Host::Managed` class.

2018-04-24 08:41 UTC, leewaa commented
Nothing else is missing here ? Looks ok to me and tests are green.

No other objections to this one ?

2018-04-24 08:52 UTC, timogoebel commented
Rebased.

Can we get this in? I don't think rewriting the way we test facets is actually within the scope of this issue. We should probably do it at some time, but we can do that later I believe.

2018-04-24 10:52 UTC, mmoll approved these changes

2018-04-24 15:33 UTC, tbrisker approved these changes
LGTM, Thanks @timogoebel and everyone involved in reviewing :)

2018-04-24 15:34 UTC, merged

2018-04-25 11:01 UTC, timogoebel commented
Thanks, guys.

I updated the documentation to include this: http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#section-26