Fixes #21849 -Check if the user is new before disabling login
theforeman/foreman pull request #5052
Opened 2017-12-04 14:20 UTC by shiramax

2017-12-04 15:40 UTC, tbrisker requested changes
Can you please add an integration test for creating a new user so that we don't break it again?

2017-12-04 16:18 UTC, shiramax commented
@tbrisker Done.

2017-12-04 18:13 UTC, iNecas requested changes

2017-12-04 18:13 UTC, iNecas commented on app/views/users/_form.html.erb
> +      <% if !(@user.internal?) && !(@user.new_record? ) %>
The parenthesis are not needed here (or at least the spacing should be consistent

2017-12-06 10:04 UTC, tbrisker approved these changes

2017-12-06 10:04 UTC, tbrisker commented
[test foreman]

2017-12-06 10:55 UTC, iNecas approved these changes

2017-12-06 11:21 UTC, tbrisker commented
Test failures are intermittent connection issues: 
```
Capybara::Poltergeist::StatusFailError: Request to 'http://127.0.0.1:37596/hosts/host26/edit' failed to reach server, check DNS and/or server status
    test/integration/host_js_test.rb:586:in `block (3 levels) in <class:HostJSTest>'
    test/test_helper.rb:35:in `before_setup' (Capybara::Poltergeist::StatusFailError)
```
merging despite test failure.
Thanks @shiramax !

2017-12-06 11:21 UTC, merged