Fixes #21868 - Refactored "troubleshooting" to docs link
theforeman/foreman pull request #5057
Opened 2017-12-06 08:08 UTC by ShimShtein

For both VNC and SPICE console templates.

2017-12-06 09:51 UTC, timogoebel approved these changes

2017-12-06 09:58 UTC, iNecas commented on app/views/hosts/console/spice.html.erb
> -                     link_to(_("Troubleshooting"), "http://theforeman.org/manuals/#{SETTINGS[:version].short}/index.html#7.1NoVNC",
the issue also suggests to rename "troubleshooting" to"documentation", which would be consistent with other places

2017-12-06 10:57 UTC, tbrisker reviewed
shouldn't this use `documentation_button` helper to be consistent with other documentation links?

2017-12-06 19:08 UTC, ShimShtein commented
@tbrisker, it's either keeping all three items in a single button group, or ungrouping them. 
Here is an example on ungrouped buttons:
![image](https://user-images.githubusercontent.com/10046168/33680192-7c930eb8-dac9-11e7-8741-c47c61bf2550.png)
Personally, I think ungrouping is better, but I don't have strong opinion to either option.

2017-12-07 11:22 UTC, ShimShtein commented
@Rohoover, Any thoughts? Originally it was a single buttongroup:

![image](https://user-images.githubusercontent.com/10046168/33712849-96f7f02e-db51-11e7-8b6c-a6f1653558ae.png)

2017-12-11 19:53 UTC, Rohoover commented
Ungroup, they're not related.

2017-12-12 18:17 UTC, ShimShtein commented
Ungrouped for both VNC and spice.

2017-12-17 13:44 UTC, tbrisker requested changes

2017-12-17 13:44 UTC, tbrisker commented on app/views/hosts/console/spice.html.erb
> +                     {:id => "troubleshootingButton", :class => "btn btn-default"})
Nitpick - I think the indentation here is a bit off, the documentation_button should be on the same level as the button group iiuc

2017-12-21 15:03 UTC, ShimShtein commented
Fixed spacing

2017-12-27 11:08 UTC, ShimShtein commented
@tbrisker Wanna give it a quick run?

2017-12-27 11:42 UTC, tbrisker approved these changes
LGTM, Thanks @ShimShtein !

2017-12-27 11:42 UTC, merged