Fixes #21748 - Removed gravatar images
theforeman/foreman pull request #5066
Opened 2017-12-07 20:23 UTC by witlessbird

Removed gravatar images as gravatar urls use MD5 hashes

2017-12-08 16:38 UTC, timogoebel commented
@witlessbird: Thanks. I don't really care for the gravatar feature, but why isn't disabling this setting enough to comply with FIPS? Can we add a feature toggle "FIPS enabled yes/no" that just disabled this code?

https://github.com/theforeman/foreman/blob/8195b2557b5db1b9a6489e6da6b394e0cec56630/app/models/setting/general.rb#L17

Anyway, if we remove this completely, the setting has to be removed as well. I think, this needs to be done with a db a migration.

2017-12-08 19:58 UTC, witlessbird commented
- Removed 'use_gravatar' setting from the db.

> why isn't disabling this setting enough to comply with FIPS? Can we add a feature toggle "FIPS enabled yes/no" that just disabled this code?

My thinking is that re-enabling gravatar images on a system with fips enabled will lead to a crash (with minimal logging). Adding a check for fips mode isn't worth the trouble in my opinion.

2017-12-11 19:19 UTC, witlessbird commented
Anyone?

2017-12-12 15:20 UTC, iNecas commented on app/views/users/index.html.erb
> +        <td class="display-two-pane ellipsis"><%= user.mail %> <%=link_to_if_authorized user.login, hash_for_edit_user_path(:id => user).merge(:auth_object => user, :authorizer => authorizer) %></td>
The email here looks weird + it's a duplicate info, as we already have the email column.

![Uploading avatar-4.png…]()

2017-12-12 15:30 UTC, iNecas commented on app/helpers/application_helper.rb
> -      image_tag("avatars/#{user.avatar_hash}.jpg", html_options)
The avatar_hash is actually coming from `ldap` and there is probably no reason removing this path.

2017-12-12 15:32 UTC, iNecas commented on app/views/users/index.html.erb
> +        <td class="display-two-pane ellipsis"><%= user.mail %> <%=link_to_if_authorized user.login, hash_for_edit_user_path(:id => user).merge(:auth_object => user, :authorizer => authorizer) %></td>
And since the ldap avatar support should IMO stay, I think we can leave this untouched for now.

2017-12-12 23:17 UTC, witlessbird commented
* restored avatar_image_tag helper

2018-01-03 14:28 UTC, iNecas requested changes
Tested and works well. The only request is to rebase and update the syntax for migration definition

2018-01-03 14:28 UTC, iNecas commented on db/migrate/20171208113210_remove_use_gravatar_setting.rb
> +class RemoveUseGravatarSetting < ActiveRecord::Migration
Since Foreman moved to rails 5.1 in the meantime, this needs to be:

```ruby
class RemoveUseGravatarSetting < ActiveRecord::Migration[4.2]
```

2018-01-03 19:56 UTC, witlessbird commented
* rebased
* updated migration for Rails 5.1

2018-01-05 08:27 UTC, iNecas approved these changes

2018-01-05 08:28 UTC, iNecas commented
Thanks @witlessbird

2018-01-05 08:28 UTC, merged