fixes #22055 - update bookmark loading status.
theforeman/foreman pull request #5106
Opened 2017-12-21 13:30 UTC by ohadlevy

This PR both fixes the issue reported by not showing spinner if
there is an empty set of saved bookmarks (it shows None found)

It also adds missing tests cases for spinner, error and empty result sets.

2017-12-21 14:49 UTC, sharvit approved these changes
Looks great!

2017-12-21 15:23 UTC, timogoebel requested changes
@ohadlevy: Thanks. I found one small issue, otherwise: 👍

2017-12-21 15:23 UTC, timogoebel commented on webpack/assets/javascripts/react_app/components/bookmarks/index.js
> +              ))) || <MenuItem> __('None found')</MenuItem>)}
This needs to be interpolated, i.e. `<MenuItem>{__('None found')}</MenuItem>`.

![image](https://user-images.githubusercontent.com/4107560/34261668-3637231c-e66a-11e7-87c7-3a72810b3d52.png)

In addition, I think this text should not be clickable. Maybe it's worth marking it as [disabled](https://getbootstrap.com/docs/3.3/components/#dropdowns-disabled).

2017-12-21 15:34 UTC, ohadlevy commented
Good find! I've updated both (both disabled and extracted strings).

2017-12-21 17:02 UTC, ohadlevy commented
@timogoebel green again

2017-12-22 08:45 UTC, timogoebel requested changes
@ohadlevy: Thanks. Looks good. I just have one remark regarding the spinner. I also found, that the error action is not working correctly. Could you take another look, please? Thanks.

2017-12-22 08:45 UTC, timogoebel commented on webpack/assets/javascripts/react_app/components/bookmarks/index.js
> +            <MenuItem className='loader-root'>
I think we should add the spinner as a direct child element to the `<li>` in the DOM and drop the `<a>` around it.

2017-12-22 08:45 UTC, timogoebel commented on webpack/assets/javascripts/react_app/redux/reducers/bookmarks/index.js
> +        .setIn([payload.controller, 'errors'], payload.error)
This does not work as well, as `payload.controller` is not defined.

2017-12-22 12:55 UTC, ohadlevy commented
@timogoebel fixed both issues - thanks!

2017-12-22 13:28 UTC, timogoebel approved these changes
👍 if tests are 🍏 .

2017-12-22 16:56 UTC, ohadlevy commented
It's green :)

2017-12-23 09:25 UTC, merged

2017-12-23 09:25 UTC, timogoebel commented
Merged, thanks @ohadlevy.