Fixes 22072 - adds scrolling in bookmarks dropdown
theforeman/foreman pull request #5114
Opened 2017-12-26 12:20 UTC by amirfefer

before:
![hosts 1](https://user-images.githubusercontent.com/11807069/34356605-df89a102-ea47-11e7-87e4-63715f4a007e.gif)

after:
![hosts](https://user-images.githubusercontent.com/11807069/34356609-e76d9018-ea47-11e7-870c-78b97ce3c133.gif)

2017-12-26 12:24 UTC, ohadlevy commented
/cc @rohoover

2017-12-26 20:44 UTC, timogoebel commented
Just a suggestion: Why not limit the scrollable area to the actual bookmark list and always show the "Bookmark this search" and "Documentation" links?

2018-01-01 10:06 UTC, sharvit requested changes

2018-01-01 10:06 UTC, sharvit commented on app/assets/stylesheets/base.scss
> +  overflow-y: auto;
@amirfefer can you add an empty line at the end of the file? :smiley:

2018-01-01 10:06 UTC, sharvit commented on webpack/assets/javascripts/react_app/components/bookmarks/index.js
> +            <MenuItem key="newBookmark" id="newBookmark" onClick={this.onClick.bind(this)}>
`onClick` should be bind at the constructor with the help of the helpers.

I prefer naming those event as well:
```js
onClick={this.handleNewBookmarkClick}
```

2018-01-01 10:06 UTC, sharvit commented on webpack/assets/javascripts/react_app/components/bookmarks/index.js
> +          <DocumentationUrl id="bookmarkDocumentation" href={this.props.documentationUrl} />
`documentationUrl` can be extracted from props at the beginning of this function.

2018-01-02 12:11 UTC, amirfefer commented
@sharvit Thanks, would you have another look?

2018-01-02 12:47 UTC, sharvit requested changes
@amirfefer thanks, it looks good!

Can you just add an empty line at the end of `base.scss`?

hound says: `Unexpected missing end-of-source newline no-missing-end-of-source-newline`

2018-01-02 13:42 UTC, sharvit commented
@timogoebel I think it can be nice to try, but i afraid it may feel unnatural becuase the scrollbar will be shorter and under the top controllers.

@Rohoover?

2018-01-02 15:14 UTC, Rohoover commented
I think adding the scroll is an improvement.

I also think if there is time and it's not too much effort @timogoebel suggestion would be nice as well. I don't think having a floating header/footer is particularly unnatural.

2018-01-02 15:30 UTC, Rohoover commented
Hey also wanted to post some concept work I've done with the filter/bookmark bar for thought:

![search_v2](https://user-images.githubusercontent.com/18266453/34488835-f7dfa3e0-efa7-11e7-9541-29b211687a43.jpg)

2018-01-02 15:31 UTC, ohadlevy commented
thanks! what does the "x" next to the bookmark name mean? does it delete it?

On Tue, Jan 2, 2018 at 5:30 PM, Roxanne Hoover <notifications@github.com>
wrote:

> Hey also wanted to post some concept work I've done with the
> filter/bookmark bar for thought:
>
> [image: search_v2]
> <https://user-images.githubusercontent.com/18266453/34488835-f7dfa3e0-efa7-11e7-9541-29b211687a43.jpg>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/theforeman/foreman/pull/5114#issuecomment-354792028>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AABOx-kHGWTO2WUsS7f695fQ5N5kczbRks5tGkufgaJpZM4RMu6R>
> .
>

2018-01-02 15:39 UTC, Rohoover commented
@ohadlevy 

Yes, I was looking at ways to better remove bookmarks.

2018-01-02 18:03 UTC, amirfefer commented on app/assets/stylesheets/base.scss
> +  overflow-y: auto;
I already added, as you can see hound has passed.

2018-01-03 15:17 UTC, amirfefer commented
I've tried to add floating dropdown items, however bootstrap's dropdown  makes it harder to implement, and I don't think it worth the time.
I've added a `bookmark` icon though.  

The item's delete action is not related to scrolling,  it looks great though.  I prefer to add it on different PR

![hosts 2](https://user-images.githubusercontent.com/11807069/34526085-f9c06f7a-f0a9-11e7-8e80-7d1407b6310b.gif)

2018-01-03 15:57 UTC, timogoebel commented
Looks good to me.

I also like the "inline removal" of the bookmarks.

@Rohoover: Can you please create a Remine issue for that and describe in more details how it should behave (e.g. does it need a "Confirm?" dialog etc.) and attach the concept work?

@sharvit: Do you have more comments? If you approve as well, I'll be happy to merge.

2018-01-03 16:23 UTC, sharvit commented
@timogoebel Looks good to me but travis is faling.

I will re-review once the tests will pass.

2018-01-03 18:09 UTC, Rohoover commented
@timogoebel Will do, thanks!

2018-01-05 17:02 UTC, waldenraines commented
@amirfefer this needs a rebase please.

2018-01-07 14:27 UTC, amirfefer commented
@sharvit , @waldenraines 
I've rebased, could you have another look?

2018-01-08 15:33 UTC, waldenraines approved these changes
Tested this out and it works well.  Code looks fine to me.  A definite improvement on the current behavior.

2018-01-08 16:17 UTC, sharvit approved these changes
Thanks @amirfefer!
I have tested it and it works great.

@amirfefer can you donate the class to `patternfly`?

2018-01-08 17:00 UTC, timogoebel approved these changes

2018-01-08 17:02 UTC, merged

2018-01-08 17:27 UTC, timogoebel commented
Merged, thanks @amirfefer. And thanks for the help in reviewing this @waldenraines and @sharvit.

I'm putting this on 1.17, cherry-picked as 9c06ba937d808e29c86047190776fdb38da274b1.