Fixes #12829 -add identifier for smart variables/parameters
theforeman/foreman pull request #5125
Opened 2017-12-28 10:06 UTC by shiramax

2017-12-28 13:21 UTC, tbrisker requested changes
See comments inline. thanks!

2017-12-28 13:21 UTC, tbrisker commented on app/views/puppetclasses/_class_parameters.html.erb
> +      <%= lookup_key.type == "PuppetclassLookupKey" ? "Smart Parameters":"Smart Variables"%>
Please extract the strings for translation (https://theforeman.org/handbook.html#Stringsandtranslations).
You can also check the key type using `lookup_key.is_a? PuppetclassLookupKey` (reducing one string allocation per key)

2017-12-28 13:21 UTC, tbrisker commented on app/views/puppetclasses/_class_parameters.html.erb
> +    <td class="ellipsis param_name">
I think `param_name` class isn't needed here and might actually lead to issues (iirc, it is used by the js to lookup the param name)

2017-12-28 13:21 UTC, tbrisker commented on app/views/puppetclasses/_classes_parameters.html.erb
> +      <th class='col-md-2'><%= _('Type') %></th>
This width causes the total column to go over 12 which is the default grid size used in bootstrap. Perhaps the width of other columns should be adjusted to fit this in.

2017-12-31 14:24 UTC, tbrisker requested changes

2017-12-31 14:24 UTC, tbrisker commented on app/views/puppetclasses/_class_parameters.html.erb
>      <td class="ellipsis param_name">
`param_name` class should be on the other column that contains the param name (lookup_key.key). Both columns should have the `ellipsis` class so they get a tooltip if they overflow (e.g. on a small display). I think the order should be the other way around, first name then type.

2017-12-31 14:24 UTC, tbrisker commented on app/views/puppetclasses/_class_parameters.html.erb
> +      <%= (lookup_key.is_a? PuppetclassLookupKey) ? _("Smart Parameters"):_("Smart Variables")%>
I think these should be singular. also, please add a space around the `:`

2017-12-31 14:41 UTC, shiramax commented
@tbrisker Done.

2017-12-31 15:00 UTC, tbrisker requested changes

2017-12-31 15:00 UTC, tbrisker commented on app/views/puppetclasses/_class_parameters.html.erb
> +    <td>
This should be `</td>`

2017-12-31 15:06 UTC, shiramax commented
@tbrisker  Done.

2017-12-31 15:07 UTC, tbrisker approved these changes

2017-12-31 17:24 UTC, merged

2017-12-31 17:24 UTC, tbrisker commented
Thanks @shiramax !