refs #22107 - subnet host count: permissions and n+1
theforeman/foreman pull request #5151
Opened 2018-01-05 13:06 UTC by timogoebel

Only displays the link to the host count if a user has the "view_hosts" permission and counts the number of hosts without a "n+1" query as we do on similar pages.
I'm still not sure if the query counts correct, but could you (@dLobatog + @tbrisker) please take a look? Thanks.

2018-01-15 12:25 UTC, tbrisker reviewed
This seems to work correctly, but I wonder if perhaps we should put the logic inside the host_count method instead of passing it from the view, similar to how we handle unscoping for taxonomies? 
Another question I'm not sure about - should we include only primary nic subnet or all nics? the search seems to lead to only primary subnet.

2018-01-15 12:50 UTC, timogoebel commented
> I wonder if perhaps we should put the logic inside the host_count method instead of passing it from the view, similar to how we handle unscoping for taxonomies?

Could you give me an example what you have in mind? I can't follow.

> should we include only primary nic subnet or all nics?

I stumbled upon that as well. It might be best to be consistent with the search results, but I don't have a strong opinion for or against the other.

2018-01-15 13:15 UTC, tbrisker commented
@timogoebel I was thinking something like:
```ruby
  def hosts_count(resource_name = controller.resource_name)
    hosts_scope = Host::Managed.reorder('')
    case resource_name
    when 'organization', 'location'
      # If we are on /organizations or /locations, this allows to display the
      # count for hosts not in the current organization & location.
      hosts_scope = hosts_scope.unscoped
    when 'subnet'
      hosts_scope = hosts_scope.joins(:primary_interface)
    end
    @hosts_count ||= hosts_scope.authorized.group(:"#{resource_name}_id").count
  end
```
We could also perhaps refactor some of the other pages similarly, such as domains.

2018-01-15 13:21 UTC, timogoebel commented
@tbrisker: Thanks. I quite like that.

2018-01-16 09:22 UTC, dLobatog submitted a review, later dismissed
Moving back to WoC based on @tbrisker 's comment, I also think it makes sense

2018-01-16 15:36 UTC, timogoebel commented
@tbrisker and @dLobatog: Thanks for your comments. Addressed your feedback.

2018-01-16 16:01 UTC, tbrisker requested changes
just one minor comment, other than that looks good.

2018-01-16 16:01 UTC, tbrisker commented on app/views/subnets/index.html.erb
> +        <td><%= link_to_if_authorized(hosts_count(controller.resource_name).fetch(subnet.id, 0), hash_for_hosts_path(:search => "subnet.name=\"#{subnet}\"")) %>
no need to pass the parameter here, it's the default value

2018-01-16 16:06 UTC, timogoebel commented
@tbrisker: Thanks, done. 🌲

2018-01-16 16:07 UTC, tbrisker approved these changes

2018-01-29 14:34 UTC, tbrisker commented
[test foreman]

2018-02-01 14:14 UTC, timogoebel commented
@tbrisker: Tests are 🍏 📗 💚 🥗

2018-02-01 14:18 UTC, merged

2018-02-01 14:18 UTC, tbrisker commented
Thanks @timogoebel !