[WIP] Fixes #22381 - adds react-redux integration helper
theforeman/foreman pull request #5205
Opened 2018-01-23 14:00 UTC by amirfefer

2018-01-23 14:01 UTC, amirfefer commented
@sharvit , @ohadlevy 
What do you think about this approach ?

2018-01-23 16:27 UTC, sharvit requested changes
I like this approach.
I think it would even make more sense after we will migrate the folder structure to a domain level approach.

2018-01-23 16:27 UTC, sharvit commented on webpack/assets/javascripts/react_app/components/bookmarks/form/form.test.js
> +describe('bookmark form - unit tests', () => {
I believe it would be better to use separate file for unit-testing

2018-01-23 16:27 UTC, sharvit commented on webpack/assets/javascripts/react_app/IntergrationHelper.js
> +  return new Promise(resolve => setTimeout(() => resolve(), 100));
Why don't you use the `setImmediate` like the post propose to?

`setImmediate` should get called when the javascript callstack is getting empty.
It is till risky, but somehow make sense when waiting for all the async actions to get resolved.

2018-01-23 16:27 UTC, sharvit commented on webpack/assets/javascripts/react_app/IntergrationHelper.js
> +export function flushAllPromises() {
Can you rename this function to `waitForAsyncActions()`?

2018-01-23 16:27 UTC, sharvit commented on webpack/assets/javascripts/react_app/components/bookmarks/form/form.test.js
> +      payload: { item: 'Bookmark', body: { ok: true, id: 70 } },
You can use snapshot here.
https://gist.github.com/sharvit/cf658a8494758be8062a63121b925fdc#file-bookmarksactions-test-js-L16

2018-01-23 16:27 UTC, sharvit commented on webpack/assets/javascripts/react_app/components/bookmarks/form/form.test.js
> +      payload: { item: 'Bookmark', body: { ok: true, id: 70 } },
What about a test against the store?
```js
expect(store.getState()).toMatchSnapshot();
```

2018-01-28 12:26 UTC, sharvit commented on webpack/assets/javascripts/react_app/IntergrationHelper.js
> +export function flushAllPromises() {
and use es6 syntax for functions :)

2018-03-06 17:13 UTC, amirfefer commented
This PR is implemented here:  https://github.com/theforeman/foreman/pull/5240

2018-03-06 17:13 UTC, closed without merging