Fixes #22403 - every API endpoint can set current context
theforeman/foreman pull request #5208
Opened 2018-01-24 11:54 UTC by ares

@iNecas @mbacovsky this is what we discussed yesterday, this seems as most straightforward way to add this to every request definition. It also adds it to resources which are not taxable, e.g. architectures API, but that is consistent with context switcher on architectures page in UI.

2018-01-24 11:55 UTC, ares commented
We could perhaps improve the texts to let users know that nil mean any context. I'm open to suggestions

2018-01-24 12:23 UTC, dLobatog requested changes
I assume this is related to the mails where there's a discussion to remove the scoping by taxonomies by default on the API (all taxonomies selected by default) - should that be included here?

2018-01-24 14:23 UTC, ares commented
It's not really related, the API already works even without this definition, but it's not documented and hammer does not render these arguments. With this PR all hammer commands would have --organization-id and --location-ld to specify current context.

2018-02-22 11:40 UTC, ares commented
removing WoC, this is unrelated change as mentioned a month ago, could someone please take a look? the default scope for API was removed separately already

2018-02-22 20:13 UTC, iNecas approved these changes

2018-02-22 20:15 UTC, iNecas commented
Ack from me. @dLobatog any other objections?

2018-02-23 08:46 UTC, dLobatog approved these changes

2018-02-23 08:46 UTC, dLobatog commented
@iNecas none, merging - thanks @ares

2018-02-23 08:46 UTC, merged