Fixes #22389 - Current taxonomies in API response header
theforeman/foreman pull request #5209
Opened 2018-01-24 13:42 UTC by mbacovsky

2018-01-24 14:52 UTC, iNecas reviewed
mind adding some tests?

2018-01-24 19:39 UTC, ehelms commented
I think this is a solid change. I do think most people don't tend to look at header sense you have to go looking for them specifically.

How hard or crazy do you think it would be to add this same context into the actual API responses?

2018-01-24 22:45 UTC, ares commented
In such case, it should be called "current organization" but imho it does not belong to the api output. It's not resource attribute. Headers make sense to me.

2018-01-25 07:19 UTC, iNecas commented
+1 for headers over output

2018-01-26 21:37 UTC, mbacovsky commented
@ehelms, I'm not sure how difficult it would be to add the context to our json responses. We probably would have to patch our rabl library.
In the list requests it could be easy, we already have some metadata in the response. The rest may need some data format changes.

I prefer to keep the context in the headers as the change is uniform and unobtrusive for all the request types. I also don't think we need to be explicit about the context in API calls which are used mostly for automation. Having the information in the headers doesn't prevent us to be explicit in hammer if we need to.

2018-04-27 14:07 UTC, tstrachota requested changes
It makes sense to use headers instead of output for me.

@mbacovsky can you please add tests for the new headers? The base controller subclass test is probably the right place for them:
https://github.com/theforeman/foreman/blob/develop/test/controllers/api/base_controller_subclass_test.rb#L59

Also please add a redmine issue for the Foreman. The current one is for hammer.

2018-04-27 14:07 UTC, tstrachota commented on app/controllers/api/base_controller.rb
> +        response.headers["Current_organization"] = current_org || '; ANY'
How about `Foreman_current_organization`? The name clash is fairly minimal here, but I'd prefer to keep the `Foreman_` prefix here for the sake of consistency.

2018-04-27 14:08 UTC, tstrachota commented
[test katello]

2018-10-28 01:23 UTC, closed without merging