Fixes #22505 - CoreOS does not work
theforeman/foreman pull request #5234
Opened 2018-02-03 01:25 UTC by dLobatog

The image is called 'CoreOS.png', however the view is trying to fetch
'Coreos.png'.

To test, just create a Operating System with family "CoreOS", and you will see that the list of OSs does not show the little OS logo.

2018-02-04 12:08 UTC, tbrisker submitted a review, later dismissed
Can you please rephrase the commit message in the imperative stating what this fixes? (e.g. "use correct name for coreos logo")

2018-02-05 10:21 UTC, lzap commented
Added this to our PR github template: https://github.com/theforeman/foreman/pull/5099

2018-02-06 16:09 UTC, timogoebel commented
[test foreman]

2018-02-06 16:15 UTC, timogoebel commented
> To test, just create a Operating System with family "CoreOS", and you will see that the list of OSs does not show the little OS logo.

https://github.com/theforeman/foreman/blob/12ca07b6bca5dd0c27657d2f47a87adfcd7cfb75/app/helpers/operatingsystems_helper.rb#L35-L36

Works for me without the patch and the [code suggests](https://github.com/theforeman/foreman/blob/12ca07b6bca5dd0c27657d2f47a87adfcd7cfb75/app/helpers/operatingsystems_helper.rb#L35-L36) the file should be named `CoreOS`.

2018-02-07 11:38 UTC, lzap approved these changes
No need to stress our jenkins, I am merging manually with corrected commit message.

2018-02-07 11:40 UTC, lzap commented
Hmmm no luck, apparently a bug at github.com...

```
Counting objects: 5, done.
Delta compression using up to 7 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 602 bytes | 602.00 KiB/s, done.
Total 5 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/develop.
remote: error: At least one approved review is required by reviewers with write access.
To github.com:theforeman/foreman.git
 ! [remote rejected]     develop -> develop (protected branch hook declined)
error: failed to push some refs to 'git@github.com:theforeman/foreman.git'
```

2018-02-07 11:42 UTC, lzap commented
Sorry about the mess, @dLobatog: Can you please rephrase the commit message in the imperative stating what this fixes? (e.g. "use correct name for coreos logo")

2018-02-07 12:37 UTC, timogoebel requested changes
@lzap: Please test this first, I don't think this works correctly.

2018-02-08 11:23 UTC, lzap commented
I think the problem roots in fact that @dLobatog likely configured OS with random name therefore family is used for the icon which is `Coreos` but @timogoebel properly named the OS as `CoreOS` thus this icon is fetched.

I suggest a definitive solution to this - all icons in lowercase and converting family to lowercase as well.

2018-02-08 13:41 UTC, timogoebel commented
> I suggest a definitive solution to this - all icons in lowercase and converting family to lowercase as well.

Sorry, if I'm being a smartass here, but as the regex in the code I posted in my previous comment is case insensitive, the spelling of the family should not matter. It will always map to `CoreOS`. As long as the image is also named `CoreOS` everything should be fine. Am I missing something? 😕 ❓

2018-02-09 12:21 UTC, lzap commented
I believe @dLobatog named hist OS like "Something Completely Different CoreOS" and that will not match and falls back to family. Let's wait if he confirms :-)

2018-02-09 12:33 UTC, dLobatog reviewed
@lzap is right. CoreOS changed it's name to 'Container Linux' in 2016, so I called my OSs in Foreman 'Container Linux', family 'CoreOS'.

In order to make it work with both, I will change the regex

2018-02-09 12:33 UTC, dLobatog commented
![screenshot from 2018-02-09 13-30-40](https://user-images.githubusercontent.com/598891/36028020-c8d614f8-0d9d-11e8-8b34-46e2e8dbf08a.png)

2018-02-09 12:38 UTC, dLobatog commented
![screenshot from 2018-02-09 13-37-40](https://user-images.githubusercontent.com/598891/36028215-73c65bfc-0d9e-11e8-9cf2-d426b3d0e7a7.png)
Updated - @timogoebel @lzap I think it should work for both cases now, thanks for the review

2018-02-09 13:00 UTC, lzap approved these changes
Works for me but I will wait for @timogoebel 's opinion.

2018-02-12 14:47 UTC, timogoebel approved these changes

2018-02-12 14:48 UTC, timogoebel commented
👍

2018-02-12 14:49 UTC, merged

2018-02-12 14:49 UTC, timogoebel commented
Thanks, @dLobatog and @lzap.