Amend PR template - format links as markdown
theforeman/foreman pull request #5245
Opened 2018-02-09 12:50 UTC by dLobatog

Updated the links as markdown.

2018-02-09 13:01 UTC, lzap commented
Can you make the text to break at 80th column, I write my PR texts in terminal window.

2018-02-09 13:02 UTC, lzap commented on .github/PULL_REQUEST_TEMPLATE.md
> +* Create an issue in [Redmine](https://projects.theforeman.org/projects/foreman/issues)
This could be:

    [Create an issue](https://projects.theforeman.org/projects/foreman/issues)

2018-02-09 13:02 UTC, lzap commented on .github/PULL_REQUEST_TEMPLATE.md
> +- in short:
Wrap nicely please. Thanks!

2018-02-09 13:03 UTC, lzap commented
Why did you create new PR? I could do the changes myself. Whatever, fine for me.

2018-02-12 14:40 UTC, dLobatog reviewed
@lzap I opened a new PR because I thought I could push your PR with changes, but the develop branch is now protected and can only be updated through PRs. 

Thanks for the comments - I've updated according to each of them. The "Translating" link I've kept it as-is, the URL is already very long, do you want me to wrap it in some way?

2018-02-13 08:54 UTC, lzap requested changes
Missing line break.

2018-02-13 08:54 UTC, lzap commented on .github/PULL_REQUEST_TEMPLATE.md
> +* Extract all strings for i18n, see [Translating section in the guide](https://projects.theforeman.org/projects/foreman/wiki/Translating)
This needs a line break. Other than that - ok, thanks.

2018-02-13 11:09 UTC, dLobatog reviewed
@lzap Line break added to `Translating`

2018-02-13 17:04 UTC, lzap approved these changes

2018-02-13 17:05 UTC, merged