Fixex #9868 - adding test for organization controller
theforeman/foreman pull request #5251
Opened 2018-02-14 13:18 UTC by lizagilman

2018-02-14 13:33 UTC, lzap requested changes
Thanks one comment.

2018-02-14 13:33 UTC, lzap commented on test/controllers/api/v2/organizations_controller_test.rb
> +    put :update, params: { :id => Organization.first.to_param, :organization => { :name => "" } }
Hey, the `to_param` method returns `/organiazation/1` while here you want to put just number instead. Try `Organization.first.id` instead.

2018-02-14 13:57 UTC, lizagilman commented
@lzap thank you, updated

2018-02-14 16:32 UTC, lizagilman commented
[test foreman]
[test katello]

2018-02-19 09:43 UTC, lzap approved these changes
Thank you!

2018-02-19 09:43 UTC, merged