Fixes #22888 - remove code around dynflow db_pool_size
theforeman/foreman pull request #5320
Opened 2018-03-13 20:49 UTC by iNecas

Remove the code in favor of the Dynfow, where we can handle all the
logic at one place.

Requires https://github.com/Dynflow/dynflow/pull/277

2018-03-13 20:49 UTC, iNecas commented
Setting to WOC until the new Dynflow is released

2018-03-14 12:34 UTC, adamruzicka requested changes
Works as expected, pending dynflow dependency version bump

2018-03-27 20:17 UTC, iNecas commented
Version dependency dumped, waiting for dynflow to be released

2018-03-29 14:35 UTC, iNecas commented
New dynflow released: ready for final review

2018-03-29 14:36 UTC, iNecas commented
@ares searching for core committer for merging this one.

2018-03-29 17:51 UTC, ares commented
[test foreman] [test katello] [test upgrade]

2018-03-29 18:14 UTC, mmoll commented on Gemfile
> +gem 'dynflow', '>= l.0.0', '< 2.0.0'
1 instead of l, I presume? ;)

2018-03-29 19:33 UTC, iNecas commented on Gemfile
> +gem 'dynflow', '>= l.0.0', '< 2.0.0'
LOL, close enough :) Sry, I guess I need to take some rest, updated

2018-03-29 20:49 UTC, mmoll approved these changes

2018-03-29 20:53 UTC, merged

2018-03-29 20:53 UTC, mmoll commented
merged, díky @iNecas!