Fixes #22049 - Add metadata to Audit view
theforeman/foreman pull request #5359
Opened 2018-03-26 08:13 UTC by tbrisker

This could use some love on the UI side I think, but at least a first step. @rohoover would love your feedback as to how to make this prettier :smile: 

![image](https://user-images.githubusercontent.com/1540531/37894366-af56f13e-30e6-11e8-9531-8d0cb822de1e.png)

2018-03-27 13:40 UTC, Rohoover reviewed
I would do the following:
1) Make label names bold & Title case
2) Bring labels and text a little closer together
3) Add a bit more space between the meta-data and "Changes"

I think those would be the simplest thing without undertaking a larger redesign.

2018-03-27 14:40 UTC, tbrisker commented
@Rohoover only problem I have is with #2 - I can either bring the labels and text together and lose the alignment of the text, or leave it as is. If I use a smaller space for the label, the longest one ("affected organizations") gets broken into two lines. There may also be similar issues in languages that have longer labels. Please advise how to proceed.

2018-03-27 14:50 UTC, Rohoover reviewed
Makes sense, thanks for clarifying! Leave as-is.

2018-03-27 14:53 UTC, tbrisker commented
@Rohoover thanks, updated:
![image](https://user-images.githubusercontent.com/1540531/37975300-aa45b1f6-31e7-11e8-858e-6de34098da6c.png)

Please confirm.

2018-03-27 14:57 UTC, Rohoover approved these changes
LGTM

2018-03-28 14:36 UTC, ares requested changes
All looks good and is a great improvement already.

I'm thinking about audits for non-taxable resources, e.g. architecture. Seeing `Affected Organizations: ` might be a misleading as it in fact affects all orgs. Could we either say "all" in case the resource is not taxable, or `N/A` if it's not? Given the fact such audit won't be listed in audits page on specific organization, 'N/A' might be more applicable.

And perhaps for audits that are auditing taxable resource, but tracks no change, it would be good to say 'None' instead of empty line. Or with additional characters, so it's not confusing if someone creates org with name None :-)

2018-03-28 14:37 UTC, ares commented
sorry and one more thought, would you mind making User name, orgs and locs clickable leading to $resource show/edit page?

2018-03-29 13:22 UTC, ares approved these changes
I decided to go ahead and merge as this is already a great improvement. I'll send separate PR with additions I had in mind.

Thanks @tbrisker, merging!

2018-03-29 13:22 UTC, merged