Fixes #23039 - Remove deleted LDAP users
theforeman/foreman pull request #5392
Opened 2018-04-03 11:29 UTC by juliantodt

Adds a rake task ldap:remove_deleted_users which checks all users
that authenticate via LDAP whether their users are valid and
deletes invalid ones.

2018-04-03 11:35 UTC, timogoebel commented
ok to test

2018-04-03 13:59 UTC, timogoebel requested changes
@juliantodt: Thanks. I found one small issue while testing this. Please take a look. :-)

2018-04-03 13:59 UTC, timogoebel commented on lib/tasks/ldap.rake
> +    User.joins(:auth_source).where(:'auth_sources.type' => 'AuthSourceLdap').each do |user|
I think you need to wrap this in `User.as_anonymous_admin do [...] end` as no user is set when the rake tasks run.

2018-04-04 08:41 UTC, juliantodt commented
@timogoebel Thanks for the review. Had no problems while testing myself but added your suggestion nevertheless.

2018-04-04 08:51 UTC, timogoebel approved these changes
Looks good, thanks.

2018-04-04 11:51 UTC, tbrisker approved these changes
Thanks @juliantodt !

2018-04-04 11:51 UTC, merged