Fixes #23113 - Allow disabling of out of sync status
theforeman/foreman pull request #5401
Opened 2018-04-04 10:39 UTC by bastilian

This allows plugins that make use of an origin to add a setting to disable out of sync status for their origin. This is useful for environments that do not regulraly run configurations, as it is with most Ansible environments.
The changes are to widgets and the out of sync status of a host itself.

Here is a screenshot of the Ansible dashboard Widgets out of sync still enabled:

![screenshot_2018-04-04_12-27-26](https://user-images.githubusercontent.com/7757/38302965-db3234c4-3804-11e8-9953-42eb3807c106.png)

With the `ansible_out_of_sync_disabled` enabled out of sync hosts become ok hosts:

![screenshot_2018-04-04_12-35-10](https://user-images.githubusercontent.com/7757/38303010-01dfaaca-3805-11e8-8a01-b2e0c00de65a.png)

Settings for Puppet are implemented as well and the PR introducing the Ansible setting can be found here: https://github.com/theforeman/foreman_ansible/pull/158

2018-04-04 10:43 UTC, bastilian commented
Tests are WIP but would appreciate a first review. :)

2018-04-05 09:07 UTC, ares requested changes
It works great, only one suggestion regarding settings description.

2018-04-05 09:07 UTC, ares commented on app/models/setting/puppet.rb
> +      self.set('puppet_out_of_sync_disabled', N_("Disable out of sync for %s") % 'Puppet', false, N_('%s out of sync disabled') % 'Puppet'),
I'd enhance the description a bit, e.g. "Disable host configuration status turning to out of sync for %s after report does not arrive within configured interval", current version is hard to understand if you don't have the context.

2018-04-05 10:08 UTC, bastilian commented
@ares Tests for `ConfigurationStatus#out_of_sync?` respecting origins out of sync settings via `out_of_sync_disabled?` are added and the description for the settings here and in https://github.com/theforeman/foreman_ansible/pull/158 are enhanced.

2018-04-05 10:46 UTC, ares approved these changes
:+1: let's wait for Mr. Jenkins to confirm

2018-04-05 13:14 UTC, dLobatog approved these changes
Jenkins approves, and the feature works, thanks @bastilian !

2018-04-05 13:14 UTC, merged