Fixes #23183 - Remove HashWithIndifferentAccess workaround
theforeman/foreman pull request #5422
Opened 2018-04-09 14:20 UTC by mmoll

See GH-2148, this should have been removed with Rails 4.x.

2018-04-09 15:02 UTC, tbrisker commented
@mmoll please open a new issue in redmine, this issue has been closed for a long time

2018-04-09 15:49 UTC, mmoll commented
opened a new issue

2018-04-10 07:26 UTC, tbrisker commented
This is still used in https://github.com/theforeman/foreman/blob/develop/app/models/lookup_value.rb#L37 and despite the comment, these methods aren't present in newer rails versions. It might be that they are no longer needed, but i'm not sure.

2018-04-16 21:45 UTC, mmoll commented
@orrabin could you have a look there?

2018-04-30 11:04 UTC, henry-spanka commented
After upgrading to 1.17 I get the same bug as described in https://projects.theforeman.org/issues/9240.
Is this related to this pull request?

2018-04-30 11:44 UTC, mmoll commented
@henry-spanka it shouldn't be connected in a user visible way.

2018-04-30 12:01 UTC, orrabin commented
@mmoll I tried to create a nested HashWithIndifferentAccess to see if it get's converted with `to_hash` and it looked to me like it did. It was a very simple hash but it looks like if you change the like that @tbrisker send to `val.to_hash` it should work .

2018-04-30 16:04 UTC, henry-spanka commented
@mmoll Well, at least after upgrade from 1.16 to 1.17 I can not render the external YML from a node.

The output is now like:
```yaml
--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
testvg: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  physical_volumes:
  - /dev/sdb
  - /dev/sdc
  logical_volumes: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    test1: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      size: 128M
      mountpath: /opt/test1
    test2: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      size: 128M
      mountpath: /opt/test2
    test3: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      size: 128M
      mountpath: /opt/test3
    test4: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      size: 128M
      mountpath: /opt/test4
    test5: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      size: 128M
      mountpath: /opt/test5
```

2018-04-30 16:06 UTC, mmoll commented
@henry-spanka please open an issue over at https://projects.theforeman.org/

2018-04-30 16:15 UTC, henry-spanka commented
@mmoll Thanks. I have opened a new issue (23463)

2018-07-05 12:56 UTC, tbrisker requested changes

2018-07-05 12:56 UTC, tbrisker commented on app/models/lookup_value.rb
> +      super(val.to_hash)
This should use `deep_stringify_keys`, and perhaps do it for all hashes, not just HWIA's (in case there is a HWIA nested inside a regular hash)

2019-01-06 01:23 UTC, closed without merging