Fixes #23336 - env variables for test retry and logs
theforeman/foreman pull request #5467
Opened 2018-04-19 14:02 UTC by lzap

* SKIP_MINITEST_RETRY - skips Minitest::Retry
* PRINT_ACTIVERECORD_TEST_LOGS - print ActiveRecord (SQL) logs
* PRINT_TEST_LOGS_ON_FAILURE - print Rails logs on failure
* PRINT_TEST_LOGS_ON_ERROR - print Rails logs on test error

Allows opt-out for Minitest::Retry, allows opt-in for error/failure logs
on STDOUT. Previously it was alwas on.

2018-04-19 15:50 UTC, lzap commented
Puzzled by this error: unexpected invocation: statuses() (Minitest::Assertion)
/var/lib/workspace/workspace/test_develop_pr_core@2/database/postgresql/ruby/2.5/slave/fast/app/controllers/api/v2/smart_proxies_controller.rb:70

2018-04-19 16:44 UTC, lzap commented
I see the very same failure randomly during discovery hosts, looks like it can be reproduced in core tests as well. Unable to see this locally. Amending one change where `statuses` call is *expected* in test setup which is wrong - setup should only have `stubs` calls, expectations should be all part of tests.

2018-04-20 07:12 UTC, lzap commented
Ok I think the problem with `expects` is more deep, I am pulling this out of this PR.

2018-06-26 09:04 UTC, lzap commented
Rebased can we have this @tbrisker it's disturbing.

2018-06-27 13:11 UTC, tbrisker requested changes
Looks like test failures related:
```
Failure:
UtilTest#test_0005_secure_encryption_key should match AS default key length [/var/lib/workspace/workspace/test_develop_pr_core/database/mysql/ruby/2.4/slave/fast/test/test_helper.rb:71]:
unexpected invocation: [](PRINT_TEST_LOGS_ON_ERROR)
```
Also for some reason jenkins now doesn't recognize the failed tests

2018-06-28 12:11 UTC, lzap commented
Where do you see that error? Does not make any sense to me. Locally green.

2018-06-28 12:38 UTC, tbrisker commented
@lzap that's on jenkins, if you look at the console log for the tests

2018-07-02 10:12 UTC, lzap commented
Rebased.

2018-07-02 10:12 UTC, lzap commented
Rebased.

2018-08-07 07:51 UTC, lzap commented
Test failures unrelated [test] please merge this is killing me. Very useful on Jenkins, not much useful for everyday work. And it was me who added this :-)

2018-08-07 09:17 UTC, tbrisker requested changes
Sorry, but looks like failures are related, they are failing in the about page integration test: https://ci.theforeman.org/job/test_develop_pr_core/18726/database=postgresql,ruby=2.3,slave=fast/

2018-08-09 07:18 UTC, lzap commented
Oh thanks, I missed this. I wanted to replace `expects` with `stubs`.

2018-08-13 12:00 UTC, lzap commented
Foreman is green

2018-09-25 09:02 UTC, lzap commented
Rebased, this is now ready for merge.

2018-10-04 15:28 UTC, tbrisker commented
[test katello]

2018-10-05 08:57 UTC, lzap commented
That should not be releated:

```
An HTTP request has been made that VCR does not know how to handle:
  POST https://localhost:8443/candlepin/environments/119c4753ff6d3b7bd0b76de6d5a5f94a/content

VCR is currently using the following cassette:
  - /var/lib/workspace/workspace/test_develop_pr_katello/database/postgresql/ruby/2.5/slave/fast/plugin/test/fixtures/vcr_cassettes/scenarios/repo_create.yml
    - :record => :none
    - :match_requests_on => [:method, :path, :params, :body_json]
```

2018-10-05 09:28 UTC, tbrisker approved these changes

2018-10-05 09:28 UTC, merged