Fixes #23391 - remove next/prev captions in breadcrumbs switcher
theforeman/foreman pull request #5493
Opened 2018-04-25 12:31 UTC by amirfefer

before:
![pager_2](https://user-images.githubusercontent.com/11807069/39245896-abeedda8-489d-11e8-90f5-938c8bf3ea85.png)

after:
![pager_1](https://user-images.githubusercontent.com/11807069/39245902-b0bd6700-489d-11e8-805f-49f9d0cdea72.png)

2018-04-25 12:42 UTC, ohadlevy commented
does it make sense to fix all issues at http://projects.theforeman.org/issues/23251 as well?

2018-04-27 15:26 UTC, tstrachota commented
+1 to fix it together with 23251. These issues are highly coupled.

@amirfefer do you plan to work on the other issue too? Could you fix them together?

2018-05-06 12:46 UTC, amirfefer commented
I use fixed per_page value (10 resouces), and therefore the max-height is 360px with no scroll-bar.
 
![fixed_switcher](https://user-images.githubusercontent.com/11807069/39673404-45777d00-5144-11e8-9114-be7c3d50f66f.png)

2018-05-06 13:00 UTC, ohadlevy commented
does it make sense (here on another pr) to add it to storybook? so its easily to test out it looks ?

2018-05-06 15:58 UTC, amirfefer commented
I've added `BreadcrumbsBar` to the storybook:
https://rawgit.com/amirfefer/foreman/breadcrumbs/index.html

2018-05-07 08:28 UTC, amirfefer commented
[test foreman]

2018-05-09 05:42 UTC, ohadlevy commented
@rohoover can you review the storybook please?

2018-05-13 15:30 UTC, sharvit requested changes
Great addition @amirfefer :+1:

2018-05-13 15:30 UTC, sharvit commented on webpack/assets/javascripts/react_app/components/BreadcrumbBar/BreadcrumbBar.js
> +      handleOpen,
Need to add `prop-types` and `default-props` as well

2018-05-13 15:30 UTC, sharvit commented on webpack/assets/javascripts/react_app/components/BreadcrumbBar/BreadcrumbBar.js
> +              onOpen={() => handleOpen || this.handleOpen()}
1. You don't actually run the `handleOpen` method!
    When clicking the toggle button in the storybook, I don't see an action-logger about it.

2. Do we actually need the extra prop `handleOpen`?
    `handleOpen` should be called after we already decieded to open the switcher but need the data inside it.
    Maybe it is better to use the `toggleSwitcher`, `closeSwitcher` and `loadSwitcherResourcesByResource` to demo this component?

2018-05-14 09:49 UTC, amirfefer commented
@sharvit - I removed `handleOpen` prop

2018-05-14 11:31 UTC, sharvit commented
@amirfefer would it make it easier to understand if you add actions to `toggleSwitcher` and `closeSwitcher`?

2018-05-14 11:57 UTC, Rohoover reviewed
Can we use the a more square button size, as found here for Default Size?

https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/pagination.html

2018-05-14 15:10 UTC, amirfefer commented
@Rohoover Thanks, I'll add a caption-less (no `next`/`previous` text) prop to the Pager component, with more square buttons.

2018-05-22 09:56 UTC, ohadlevy commented
@amirfefer can you rebase please?

2018-06-10 12:25 UTC, ohadlevy commented
@amirfefer whats the status of this PR? IMHO it should be included in #5662 as well.

2018-06-12 08:20 UTC, ohadlevy commented
@amirfefer ping? lets try finishing all breadcrumbs remaining issues?

2018-06-12 13:14 UTC, amirfefer commented
@ohadlevy  - i'm on it :)

2018-06-13 12:44 UTC, amirfefer commented
@Rohoover 
The pagination buttons look more squarish:
![swticher-desgin](https://user-images.githubusercontent.com/11807069/41351899-7ac3d068-6f20-11e8-97a4-3d32c0fa053a.png)

2018-06-17 10:09 UTC, amirfefer commented
[test foreman]

2018-06-18 13:35 UTC, waldenraines commented
@Rohoover any other thoughts on the current implementation?  This PR is blocked on UX approval.

2018-06-18 14:46 UTC, amirfefer commented
@ohadlevy could we merge this?
test failure seems unrelated

2018-06-18 14:50 UTC, ohadlevy commented
@amirfefer once we get a UX ack from @theforeman/ui-ux

2018-06-18 14:53 UTC, ekohl commented
I'd also appreciate if both typos in the commit message were fixed.

2018-06-18 15:12 UTC, amirfefer commented
We've got :+1: from @Rohoover 
looks like an ACK for me :)

2018-06-19 08:16 UTC, sharvit approved these changes
LGTM! Thanks @amirfefer

2018-06-19 08:28 UTC, ohadlevy commented on package.json
> +    "@storybook/addon-knobs": "^3.4.3",
just noticed there is package dep, @ekohl ack?

2018-06-19 12:32 UTC, Rohoover reviewed
Sorry I was on PTO. 

@amirfefer is correct, I gave a thumbs up!

LGTM

2018-06-19 12:43 UTC, ekohl approved these changes

2018-06-19 12:44 UTC, ohadlevy commented
test failure not relevant, thanks @amirfefer

2018-06-19 12:44 UTC, merged

2018-06-19 13:27 UTC, ares commented
Setting redmine release to 1.19, please don't forget to set the desired version after merging, thanks.

2018-06-19 21:14 UTC, amirfefer commented
@ares Do we want to CP this into 1.18? as @ohadlevy mentioned before
basically it's a bug fix.

2018-06-21 07:40 UTC, ares commented
Looks good and safe, but seems pretty minor given we're building RC2 already. @xprazak2 what's your take on this?

2018-06-21 08:12 UTC, ohadlevy commented
IMHO it should be cherrypicked into 1.8-stable, I care a bit less if the
version is 1.18.0 or .1, having said all of that, this seems like a very
low risk pr to merge regardless.

On Thu, Jun 21, 2018 at 10:41 AM Marek Hulán <notifications@github.com>
wrote:

> Looks good and safe, but seems pretty minor given we're building RC2
> already. @xprazak2 <https://github.com/xprazak2> what's your take on this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/theforeman/foreman/pull/5493#issuecomment-399006954>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AABOx3n79GZOr51-nUoddIKZi9veCY4Kks5t-04NgaJpZM4TjVZu>
> .
>