Fixes #17292 - take otp for freeipa before save @host object in db
theforeman/foreman pull request #5542
Opened 2018-05-09 17:43 UTC by pronix

https://bugzilla.redhat.com/show_bug.cgi?id=1392620

For render user data with otp for freeipa registrytion, host object should have otp before created job for render userdata.

2018-05-09 18:38 UTC, mmoll commented
ok to test

2018-05-11 09:24 UTC, timogoebel requested changes
@pronix: Thanks. I left some comments. Do you mind adding a test for this as well? Thanks.

2018-05-11 09:24 UTC, timogoebel commented on app/models/concerns/orchestration/realm.rb
> +    return self.otp if self.otp.present? && !options[:update]
Why is this needed? Just as a gard, because the realm would be set twice otherwise (once from `handle_realm_without_save` and once from `queue_realm_create`)?

2018-05-11 09:24 UTC, timogoebel commented on app/models/concerns/orchestration/compute.rb
> +    self.handle_realm_without_save
Isn't it enough to change the priority in `queue_realm_create` so that this runs earlier than the user data template rendering?

2018-05-11 09:46 UTC, pronix commented on app/models/concerns/orchestration/realm.rb
> +    return self.otp if self.otp.present? && !options[:update]
it is also big difference when you have record in ipa and trying to update it, and when you trying to recreate token for existed record.

2018-05-11 09:48 UTC, pronix commented on app/models/concerns/orchestration/compute.rb
> +    self.handle_realm_without_save
you suggest set priority for ```queue_realm_create``` less then 1 ? because ```setUserData``` has priority 1

2018-05-11 11:27 UTC, timogoebel commented on app/models/concerns/orchestration/compute.rb
> +    self.handle_realm_without_save
Well, I'd set the priority for the realm update to something lower then `setUserdata` but try to avoid negative numbers.

2018-05-11 11:38 UTC, pronix commented on app/models/concerns/orchestration/compute.rb
> +    self.handle_realm_without_save
so i should shift all tasks priority to +1 and insert on first place ```queue_realm_create```.
correct ?

2018-05-11 11:41 UTC, timogoebel commented on app/models/concerns/orchestration/compute.rb
> +    self.handle_realm_without_save
I think it should be enough to just increase the compute relates tasks, but in general: Yes.

2018-05-11 11:42 UTC, pronix commented on app/models/concerns/orchestration/compute.rb
> +    self.handle_realm_without_save
ok. thanks. today will update.

2018-05-28 06:58 UTC, timogoebel submitted a review, later dismissed
Looks good to me, but I haven't tested this.

2018-05-28 06:58 UTC, timogoebel commented
[test foreman]
[test katello]

2018-05-29 10:32 UTC, pronix commented
@timogoebel looks like jenkins error. can you please retrigger it.

2018-05-29 10:43 UTC, mmoll commented
test failure unrelated :green_heart:

2018-05-29 11:25 UTC, timogoebel commented
Code looks good to me, could somebody please jump in and help with testing this?

2018-05-29 12:15 UTC, jewgeni-prokhorenko commented
@timogoebel help with testing meaning writing tests? I want to participate.

2018-05-29 12:16 UTC, timogoebel commented
@jewgeni-prokhorenko: More like taking this patch and verifying it does not break provisioning and fixes the issue by manually testing this.

2018-06-14 12:44 UTC, pronix commented
can i help with tests ?

2018-06-14 12:45 UTC, timogoebel commented
> can i help with tests ?

Sure!

2018-08-08 14:22 UTC, acortina-git commented
Hi @timogoebel  and @pronix, 
I just tested with foreman 1.19.0-rc1 katello 3.8 and it fails with the following message:

```
Render user data template for donna-rosch.minet.net task failed with the following error: undefined method `handle_ca' for # Did you mean? handle_realm
```

2018-08-08 15:01 UTC, pronix commented
hello
i not checked yet with 1.19
during weekend i will recheck it

2018-08-09 08:15 UTC, alejojo commented
Hi @pronix,
I've removed the line 99:
```ruby
 self.handle_ca
```
 in compute.rb and it's working fine :D

2018-09-07 17:45 UTC, mmoll commented
@pronix What's the status here? Could you please rebase onto current develop?

2018-09-07 17:51 UTC, pronix commented
hello @mmoll 
it is in my plan during vacation after 2 weeks :)

2018-11-22 16:21 UTC, schlitzered commented
i just tried the patch with my foreman 1.20 installation and it worked, would be great if this could be merged to foreman 1.20.1

2018-11-22 16:40 UTC, mmoll commented
a rebase and added tests are still needed.

2019-03-06 17:38 UTC, tinsjourney commented
any update on this PR ?

2019-03-07 09:28 UTC, timogoebel commented
@theforeman/core: Could somebody review this? I would do it, but I don't have a testing environment for realm things.

2019-03-07 10:46 UTC, lzap commented
Sorry it took so long. Now, I don't have realm setup as well, but I don't think it's super important to test if the patch fixes the realm issue. What's more important IMHO is test for regressions in compute resource, as you can see this patch changes priority numbers of these and this can have huge impact. I can do that.

Here is an idea - how about to clear priorities for once but forever? The problem is that we have them spread over the codebase and most of them are 1, 2, 3 numbers which makes everything pretty much "random". If you grep `queue.create | grep priority` you get most of these.

I suggest to create a new file `app/services/orchestration/priority.rb` with an explicit list of priority numbers as constants:

```ruby
module Priority
  PRIORITY_DHCP_CREATE = 10
  PRIORITY_DHCP_DELETE = 9
  # etc for all orchestration "queue.create" calls
```

This could be mixed in everywhere needed and then we would benefit from a single place with all priorities. We could do a breaking change and setup all orchestration order for once and forever so at least in core we have it in expected order and with some reasonable numbers like 100, 200, 300, 310, 320 so plugins could take advantage of that. I would file such a patch if folks are interested - @timogoebel and @tbrisker

2019-03-07 13:08 UTC, lzap commented
A simple example with libvirt VM works just fine:

```
[app|D|dc6|fe5] Scheduling new DHCP reservations for leigh-canupp.home.lan
[app|D|dc6|fe5] Enqueued task 'dhcp_create_192.168.99.194' to 'Host::Managed Main' queue
[app|D|dc6|fe5] Current organization set to MyOrg
[app|D|dc6|fe5] Current location set to MyLoc
[app|D|dc6|fe5] Current location set to none
[app|D|dc6|fe5] Current organization set to none
[app|D|dc6|fe5] Enqueued task 'Deploy TFTP PXELinux config for leigh-canupp.home.lan' to 'Host::Managed Main' queue
[app|D|dc6|fe5] Enqueued task 'Deploy TFTP PXEGrub2 config for leigh-canupp.home.lan' to 'Host::Managed Main' queue
[app|D|dc6|fe5] Enqueued task 'Deploy TFTP PXEGrub config for leigh-canupp.home.lan' to 'Host::Managed Main' queue
[app|D|dc6|fe5] Enqueued task 'Deploy TFTP iPXE config for leigh-canupp.home.lan' to 'Host::Managed Main' queue
[app|D|dc6|fe5] Enqueued task 'Fetch TFTP boot files for leigh-canupp.home.lan' to 'Host::Managed Main' queue
[app|D|dc6|fe5] Enqueued task 'Set up compute instance leigh-canupp.home.lan' to 'Host::Managed Main' queue
[app|D|dc6|fe5] Enqueued task 'Query instance details for leigh-canupp.home.lan' to 'Host::Managed Main' queue
[app|D|dc6|fe5] Observed create hook on leigh-canupp.home.lan
[app|D|dc6|fe5] Observed postcreate hook on leigh-canupp.home.lan
[app|D|dc6|fe5] Queuing 1 hooks for Host::Managed#postcreate
```

I am giving this a go, we are unlikely able to test all the plugins.

2019-03-07 13:08 UTC, lzap approved these changes
Thanks.

2019-03-07 13:09 UTC, merged

2019-03-07 13:32 UTC, lzap commented
https://community.theforeman.org/t/idea-one-place-for-orchestration-priorities/13168