Fixes #23377 - audit external group membership changes
theforeman/foreman pull request #5555
Opened 2018-05-14 13:33 UTC by kgaikwad

2018-05-15 08:08 UTC, ares requested changes
tests are being worked on by @kgaikwad

2018-05-30 07:30 UTC, ares requested changes
Works well, I have only one suggestion for keeping some test logic. If that's kept and tests are green, it's ready for merge.

2018-05-30 07:30 UTC, ares commented on app/models/user.rb
> +    User.where(:lower_login => userlist.map(&:downcase)).pluck(:id)
could you please add a test for this method that would ensure it's case insensitive? basically to replace tests for add_users/remote_users this PR is dropping, it should verify that even if we pass OnE, TWO it affects users one, two

2018-06-01 13:01 UTC, kgaikwad commented
@ares,
Updated PR with a test case.

2018-06-04 11:16 UTC, ares requested changes
two small comments to the test, good to be merged afterwards

2018-06-04 11:16 UTC, ares commented on test/models/user_test.rb
> +    assert (!login_values.include? 'tHREE')
better written as [refute_includes](https://apidock.com/ruby/v1_9_3_125/MiniTest/Assertions/refute_includes)

2018-06-04 11:16 UTC, ares commented on test/models/user_test.rb
> +    assert_not_empty user_ids
I think this is covered by the line below

2018-06-05 04:32 UTC, kgaikwad commented
@ares, 
Updated PR as per review comments.
Some tests are failing but those are I guess irrelevant to my changes.

2018-06-08 10:30 UTC, ares approved these changes

2018-06-08 10:31 UTC, ares commented
Test failures are caused by develop branch, it was already fixed so your PR would have to be rebased. But I see no other tests are failing, so let's merge this. Thanks @kgaikwad!

2018-06-08 10:31 UTC, merged