Fixes #21987 - New UI for auth sources
theforeman/foreman pull request #5560
Opened 2018-05-15 11:44 UTC by dhlavac

# Pull request not ready yet!!! We need to add more tests.

This PR changes Administration for Authentication sources

**Administer page for Authentication sources**
![auth_sources](https://user-images.githubusercontent.com/11925360/40054611-bfed9e72-5845-11e8-9454-49e6a1119b40.png)

**Administer page for Authentication sources with no LDAPs**
![auth_sources_empty](https://user-images.githubusercontent.com/11925360/40054627-d9eef0e6-5845-11e8-858b-b95db4a02438.png)

**Drop-downs for External and LDAP authentication sources**
![auth_sources_with_external](https://user-images.githubusercontent.com/11925360/40054658-f4cf3862-5845-11e8-8e1a-b079284e5da9.png)

2018-05-15 13:14 UTC, amirfefer reviewed
Thanks @dhlavac, looks great!
I'd like to see this card view as a react component.
there are patternfly-react [card](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?knob-Warning%20threshold%20value=40&knob-Header=Great%20job%21&knob-is%20Drawer%20Expandable=true&knob-Loading=true&knob-Description=Description&knob-animate=true&knob-Action=true&knob-Error%20threshold%20value=80&knob-Maximal%20value=100&knob-Message=This%20is%20really%20working%20out.&knob-Type=success&knob-Actual%20value=70&knob-Menu=true&knob-Size=md&knob-Match%20Height=true&knob-On%20Color=primary&knob-Off%20Color=default&knob-Minimal%20value=0&knob-Label=Label&selectedKind=patternfly-react%2FCards&selectedStory=Base%20Card&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel) and [kebab](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?knob-Warning%20threshold%20value=40&knob-Header=Great%20job%21&knob-is%20Drawer%20Expandable=true&knob-Loading=true&knob-Description=Description&knob-animate=true&knob-Action=true&knob-Error%20threshold%20value=80&knob-Maximal%20value=100&knob-Message=This%20is%20really%20working%20out.&knob-Type=success&knob-Actual%20value=70&knob-Menu=true&knob-Size=md&knob-Match%20Height=true&knob-On%20Color=primary&knob-Off%20Color=default&knob-Minimal%20value=0&knob-Label=Label&selectedKind=patternfly-react%2FDropdownKebab&selectedStory=DropdownKebab&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel) components already.

When a pull request is still in progress, you can add [WIP] on the PR title.

2018-05-15 14:56 UTC, ohadlevy commented
I too would love to see it in react, but maybe prior to that we should review the UX with @rohoover as well? I could imagine different views (besides tables) that might be useful here?

2018-05-16 05:59 UTC, ares commented
This is the outcome of discussion with @rohoover, it's a midterm solution, until we have org/loc association per external hostgroup, until them we need table for ldap auth sources, as users need to create many of them in multiorg scenario. After that's done, auth sources should be cards only.

2018-05-16 08:12 UTC, ohadlevy commented
On Wed, May 16, 2018 at 8:59 AM, Marek Hulán <notifications@github.com>
wrote:

> This is the outcome of discussion with @Rohoover
> <https://github.com/Rohoover>, it's a midterm solution, until we have
> org/loc association per external hostgroup, until them we need table for
> ldap auth sources, as users need to create many of them in multiorg
> scenario. After that's done, auth sources should be cards only.
>
>
> Where can I find more information about your end goal?  I find it hard to
understand what you are trying to achieve in the long term? (sorry, but
just missing the user stories and dont understand how auth source, external
hostgroups and multiorg comes together)

2018-05-18 11:19 UTC, ares commented
I don't recall if the meeting back then was recorded. Here's the motivation, today we can setup mapping between external auth sources and user groups, user groups can have roles assigned. With external user groups mapping, administrators can manage permissions externally to Foreman, only by assigning user groups in their LDAP. This works fine for permissions but not for ogranizations and locations, which is our secondary authorization system. For that we added orgs/locs associations to ldap auth sources. When user account is created, it gets associated to orgs/locs the LDAP is assigned to.

The problem is that if I want to have single LDAP for multiple organizations, each use belonging to different one, the model does not fit. People workaround that by having multiple LDAP definitions for the same LDAP server but with different filter and organization assigned. That means easily >10  LDAP authsources in env with multiple orgs.

We started adding the same model to external auth source (using just REMOTE_USER) but in order to do it, we had to add API and UI for manipulating it's org/loc association. As part of that, @dhlavac adds UI for it. This is a temporary solution, where we'll still have table for ldap authsources (as there can be a lot of them because of ^) and cards for internal and external (both have single instance). Later we want to add org/loc association also to external user group which should dramatically decrease the number of LDAP auth sources defined here and at that point we'd like to convert the table to cards. So at the end, all auth source instances should be represented by card.

Hope that puts more light on the change. When @dhlavac started working on this, there were no cards implemented and patternfly roadmap was unclear about this. Since it was few months ago, I think we can revisit the decision. Though I'm not sure I'd block this PR because of that single card partial. It's not the crucial part of it. But I'd definitely support the effort that would follow right after this gets in, so that we'll get card implemented as a react component if @dhlavac agrees.

2018-10-22 15:24 UTC, dhlavac commented
@ares PR is ready I hope. @ohadlevy @amirfefer If it isn't problem, for now I will let card component in erb. It's a midterm solution, until we have org/loc association per external hostgroup and then implement react component for cards.

2018-11-13 07:14 UTC, ares commented
There seems to be several hound/rubocop issues, mind to rebase and fix them?

2018-11-13 07:15 UTC, ares requested changes
rubocop failures, rebase would also be good (no conflicts)

2018-11-13 07:16 UTC, ares commented on config/environments/development.rb
> +  # config.active_record.migration_error = :page_load
is this related?

2018-11-15 15:30 UTC, dhlavac commented on config/environments/development.rb
> +  # config.active_record.migration_error = :page_load
Ou thanks ... leftover from debugging

2018-11-23 16:22 UTC, dhlavac commented
@ares rebased and removed debug leftovers and hound violations

2018-11-30 10:43 UTC, ares commented
this needs to be rebased

2018-11-30 11:01 UTC, ares requested changes
couple of new findings, please take a look

2018-11-30 11:01 UTC, ares commented on app/models/auth_source.rb
> +  scope :only_ldap, -> { where("auth_sources.type NOT IN (?)", ['AuthSourceInternal', 'AuthSourceHidden', 'AuthSourceExternal']) }
would it be better to explicitly mention LDAP auth source class? if we add additional auth source in future, it will be also included in this only_ldap scope (in fact there's at least one plugin that adds it)

2018-11-30 11:01 UTC, ares commented on app/views/auth_source_ldaps/_form.html.erb
> +  <%= submit_or_cancel f, false, :cancel_path => auth_sources_path%>
missing space before %

2018-11-30 11:01 UTC, ares commented on db/migrate/20180720143228_set_default_authsource_external_setting.rb
> +    N_('Name of the external auth source where unknown externally authentication users (see authorize_login_delegation) should be created (If you want to prevent the autocreation, keep unset)'),
no need to extract strings here using N_(), they are already extracted in setting file, please remove from the whole migration

2018-11-30 11:01 UTC, ares commented on app/views/auth_sources/_card.html.erb
> +      <% if auth_source.type != 'AuthSourceInternal' %>
it would be better to restructure this partial as it seems it's combining too many things, I'd suggest

1) make a generic card partial that contains the first three wrapper divs, it would accept variable body, it should also live in some more generic dir as it wouldn't be specific for auth sources
2) define auth_source_ldap_card and auth_source_external_card that would use the generic partial specifying their content as body, to avoid big if conditions in view layer
3) to share the common part I'd add one extra partial, auth_source_card that would lines 24-32 to the generic one and in fact partials from 2) would be using this auth_source_card instead of generic one directly

I hope that makes sense

2018-11-30 11:01 UTC, ares commented on app/views/auth_sources/index.html.erb
> +    <% if auth_source = ldap_present(@auth_sources) %>
could you please explain this a bit more? the ldap_present method searches for first ldap auth source in `@auth_sources` if there's none it builds new one if my understanding is correct

also you already have ldap auth sources in `@auth_source_ldaps`, why filtering `@auth_sources`?

2018-11-30 11:01 UTC, ares commented on app/views/auth_sources/index.html.erb
> +      <% if auth_source.type != 'AuthSourceLdap' %>
you added scopes to AuthSource class, why not using them here?

2018-12-12 14:38 UTC, dhlavac commented on app/views/auth_sources/_card.html.erb
> +      <% if auth_source.type != 'AuthSourceInternal' %>
Thanks, good idea. What do you think where can I place this generic card ?

2018-12-12 14:38 UTC, dhlavac commented on app/views/auth_sources/index.html.erb
> +      <% if auth_source.type != 'AuthSourceLdap' %>
We have scopes for only_ldaps but not for everything except ldaps(and hidden)

2018-12-12 14:38 UTC, dhlavac commented on app/views/auth_sources/index.html.erb
> +    <% if auth_source = ldap_present(@auth_sources) %>
Unless we have added taxonomies to external usergroups there can be a lot of ldap auth sources and we want to show ldap card only one and not for all ldap authsources . If there is many ldap auth sources card will be created from first occurance (that prevents creating more ldap cards). If there is no ldap auth source temporary will be created because we need authsource object for card element. If it is confusing, I can add one more scope without ldaps and use that(for internal and external card)

2018-12-17 15:36 UTC, ares commented on app/views/auth_sources/_card.html.erb
> +      <% if auth_source.type != 'AuthSourceInternal' %>
I'd put it under app/views/common

2018-12-19 13:10 UTC, dhlavac commented
@ares Changes done

2019-01-16 15:08 UTC, dhlavac commented
@ares Anything else what can i do on this PR ?

2019-05-04 01:58 UTC, mmoll commented
@dhlavac please rebase :)
@ares any more comments?

2019-05-15 11:07 UTC, dhlavac commented
@mmoll @ares rebased

2019-11-11 00:21 UTC, mmoll commented
@dhlavac This needs a rebase :)

2019-11-11 15:09 UTC, dhlavac commented
@mmoll I don't know if it is still planned to use this feature. @ares should I rebase that or close PR ?

2019-11-11 16:40 UTC, ezr-ondrej commented
@dhlavac if you're not plannig to continue I was planning to take over. I do not know when I will get to it though.

2019-11-25 18:32 UTC, tbrisker commented
closing in favor of #7206

2019-11-25 18:32 UTC, closed without merging

2019-11-25 18:32 UTC, tbrisker commented
Thanks for the effort here @dhlavac !