Fixes #23598 - move report metrics chart to c3
theforeman/foreman pull request #5563
Opened 2018-05-15 14:09 UTC by lizagilman

Using pf-react donut chart instead of flot

![image](https://user-images.githubusercontent.com/15361156/40061034-abe97250-5860-11e8-9187-8a6099e9113d.png)

2018-05-15 14:27 UTC, amirfefer requested changes
Thanks @lizagilman 
I left some inline comments.

We have a component for a chart box with this design:
![chart-box](https://user-images.githubusercontent.com/11807069/40063285-a749dd3e-5865-11e8-8113-db00d383c682.png)
 although I know that this page uses chart bar which still using flot.

2018-05-15 14:27 UTC, amirfefer commented on app/views/config_reports/_metrics.html.erb
> +      <div id="metrics_chart" class='metrics-chart' style="margin-top:50px;padding-bottom: 40px;"></div>
why not add the inline style to the `metrics-chart` class?

2018-05-15 14:27 UTC, amirfefer commented on app/views/config_reports/_metrics.html.erb
> +      <% metrics.sort.each do |title, value|%>
indentation should be 2 space

2018-05-15 14:27 UTC, amirfefer commented on app/views/config_reports/_metrics.html.erb
> +      <tr>
ditto

2018-05-15 14:27 UTC, amirfefer commented on app/views/config_reports/_metrics.html.erb
> +      <%= mount_react_component('DonutChart', '#metrics_chart', metrics.to_a) %>
data should be in json format (`to_json`)

2018-05-15 14:56 UTC, lizagilman commented
@amirfefer thanks for the quick review, updated.
should we move only one chart to a box? once @ripcurld is finished with the bar chart we can move both to chartbox

2018-05-16 12:57 UTC, amirfefer requested changes
Thanks @lizagilman , just one minor issue with the css.

Generally speaking, We do test the component behavior, 
but we don't test if a component actually is rendered in a page (end to end test).
do we want this kind of test?

2018-05-16 12:57 UTC, amirfefer commented on app/assets/stylesheets/charts.scss
> +  margin-top: 50px;
duplicate `margin-top` with 12px and 50px values.
maybe use margin with 4 values?

2018-05-16 15:21 UTC, lizagilman commented
@amirfefer thanks, css updated
I tried to test for the chart rendering both on integration test and controller test but it seems the container div is empty (the component is not mounted to `#metrics_chart`). Is this a normal behavior?

2018-05-17 08:59 UTC, amirfefer commented
@lizagilman, in order to run js in integration test you should use js driver, tests with js end with `_js_test`, and inherit `IntegrationTestWithJavascript`.

2018-05-17 10:27 UTC, lizagilman commented
@amirfefer ok, I added a test
Is this what you had in mind?

2018-05-17 13:23 UTC, ohadlevy commented
@lizagilman mind adding an updated screenshot? thanks.

2018-05-17 16:59 UTC, amirfefer requested changes

2018-05-17 16:59 UTC, amirfefer commented on test/integration/config_report_js_test.rb
> +    @report = ConfigReport.import(read_json_fixture('reports/applied.json'))
I think `@` is redundant here

2018-05-21 08:09 UTC, lizagilman commented
before: 

![metrics_flot](https://user-images.githubusercontent.com/15361156/40296846-945c24ae-5ce6-11e8-8089-1d39b4e57920.png)

aftre:

![metrics_c3](https://user-images.githubusercontent.com/15361156/40296864-a4a9184e-5ce6-11e8-87a7-eae8a4daba92.png)

2018-05-21 08:10 UTC, lizagilman commented on test/integration/config_report_js_test.rb
> +    @report = ConfigReport.import(read_json_fixture('reports/applied.json'))
fixed

2018-05-21 11:43 UTC, amirfefer commented
Overall looks good :+1: 
The chart boxes are not at the same size: 
![report_charts](https://user-images.githubusercontent.com/11807069/40305870-17293d90-5d05-11e8-9860-ef3db677d825.png)

I wonder if the right table with the metric values is needed,  or we can use donuts chart  legend:
![report_metrics](https://user-images.githubusercontent.com/11807069/40305915-4224f246-5d05-11e8-8a10-f907b1f8c421.png)

2018-05-21 11:44 UTC, amirfefer requested changes
Overall looks good :+1: 
just a minor adjustment is needed, see other comment for details

2018-05-21 12:06 UTC, lizagilman commented
updated - 

![image](https://user-images.githubusercontent.com/15361156/40306382-27bc77ce-5d07-11e8-995d-daf8a3b76ed1.png)
![image](https://user-images.githubusercontent.com/15361156/40306735-771ed8c4-5d08-11e8-9b93-c53aa7bef173.png)

2018-05-22 08:56 UTC, amirfefer submitted a review, later dismissed
LGTM :+1:

2018-05-22 09:44 UTC, ohadlevy commented
this looks like a solid change, the only thing I'm a bit uncomfortable with is the red (and to some degree green) color inside the chart, in your screenshots it looks like something requires attention, when i looked at it on some other sample data it didnt look as bad, but it still feels wrong to me, @rohoover any thoughts?
![image](https://user-images.githubusercontent.com/20167/40354862-978e2e1a-5dbd-11e8-9e9a-e9398ff9d370.png)
![image](https://user-images.githubusercontent.com/20167/40354888-a58fa2f0-5dbd-11e8-9052-ea2a1f3c2de6.png)
![image](https://user-images.githubusercontent.com/20167/40354923-bcbc4d5c-5dbd-11e8-90d2-0d0d00bb4a89.png)

2018-05-22 10:24 UTC, amirfefer commented
@ohadlevy: these colors are suggested by pf color-palette and mentioned [here](https://github.com/theforeman/foreman/pull/5137#issuecomment-356959608)
But I tend to agree when it's about two distinct colors, the red color has some negative impact.
We can change the color pattern order, and move the red color from the [second place](https://github.com/theforeman/foreman/blob/develop/webpack/assets/javascripts/services/ChartService.consts.js#L21).

2018-05-22 11:53 UTC, Rohoover commented
@amirfefer Is correct. There is some flexibility as the donut doesn't specify which colors and only gives guidance to use the recommended [PF Color palette](http://www.patternfly.org/styles/color-palette/). We can technically choose from any of those colors.

2018-05-22 12:06 UTC, ohadlevy commented
so in this case would you recommend changing the colors or its just me?

On Tue, May 22, 2018 at 2:53 PM, Roxanne Hoover <notifications@github.com>
wrote:

> @amirfefer <https://github.com/amirfefer> Is correct. There is some
> flexibility as the donut doesn't specify which colors and only gives
> guidance to use the recommended PF Color palette
> <http://www.patternfly.org/styles/color-palette/>. We can technically
> choose from any of those colors.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/theforeman/foreman/pull/5563#issuecomment-390962785>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AABOx0zXmL4VInsl4WwmtDwwMWRDFPxnks5t0_wygaJpZM4T_n3V>
> .
>

2018-05-22 12:29 UTC, Rohoover commented
@ohadlevy 

It's you. ;)

In all seriousness, I am not married to any particular color choice at this point. I think PF does use the red, orange, green colors as both color and status in the donuts, which can be a bit confusing.

2018-05-23 06:16 UTC, ares commented
I'd also prefer to avoid red if that's easy to do. But I can live with it :-)

2018-05-23 09:30 UTC, lizagilman commented
How about now? 

1. red is last

![image](https://user-images.githubusercontent.com/15361156/40414580-4c032698-5e81-11e8-8fbd-15373a6bda6a.png)

![image](https://user-images.githubusercontent.com/15361156/40414939-52ae571e-5e82-11e8-8ec7-813c78e24f15.png)

2. or we can replace it with a different color -

![image](https://user-images.githubusercontent.com/15361156/40415443-8ac8752a-5e83-11e8-9d38-a1454bb306e0.png)


for now, pr updated with option 1 (red at last place)

2018-05-23 19:01 UTC, ares commented
I prefer option 2, but not strong opinion. If red helps color-blind people, I'm fine with keeping it.

2018-06-03 19:48 UTC, lizagilman commented
@tstrachota any preferences? or can we merge?

2018-06-05 12:14 UTC, amirfefer requested changes
I prefer option 2 as well,
Please pick another color from [this](https://github.com/theforeman/foreman/pull/5137#issuecomment-356959608) list.

2018-06-05 13:15 UTC, lizagilman commented
ok, changed - 

![image](https://user-images.githubusercontent.com/15361156/40978156-884bdce4-68db-11e8-88ff-a2501c8292c1.png)

2018-06-05 16:44 UTC, ripcurld commented
LGTM :+1: 

test failures not related.
[test foreman]
[test katello]

2018-06-06 06:56 UTC, lizagilman commented
[test foreman]

2018-06-06 08:46 UTC, amirfefer approved these changes

2018-06-10 08:07 UTC, tbrisker approved these changes
Tested, works well. Thanks @lizagilman !

2018-06-10 08:07 UTC, merged