Fixes #23635 - Centralize use of facter
theforeman/foreman pull request #5589
Opened 2018-05-18 10:46 UTC by ekohl

We have a bundler group for facter. That implies it's optional but
before this change it wasn't With this change it's only required if no
domain and fqdn are set. This is still the default so in most cases it's
no difference, but at least we have centralized all use of facter to one
place.

2018-05-18 10:55 UTC, sean797 requested changes
Mind also removing https://github.com/theforeman/foreman/blob/d73ddd4fa6068f846dae2486d2e5611b201ce49d/app/models/setting/email.rb#L1

2018-05-18 11:08 UTC, ekohl commented
You're right, I missed a few.

2018-05-18 11:12 UTC, ekohl commented
Updated to remove more `require 'facter'` statements.

2018-05-18 12:30 UTC, sean797 approved these changes
ACK pending tests. Thanks @ekohl  :+1:

2018-05-18 14:44 UTC, ekohl commented
Looks like Katello has some assumptions that Facter is present. Will send a PR.

2018-05-18 14:56 UTC, ekohl commented
https://github.com/Katello/katello/pull/7384

2018-05-22 10:16 UTC, timogoebel approved these changes
This can be merged once the Katello PR is merged.

2018-05-22 13:39 UTC, timogoebel commented
[test katello]

2018-05-22 15:18 UTC, merged

2018-05-22 15:18 UTC, mmoll commented
merged, bedankt @ekohl!