Fixes #23951 - fix searching by config group
theforeman/foreman pull request #5698
Opened 2018-06-15 09:12 UTC by ares

the problem is that when you under non-admin user search for hosts using config_group = x, the search_by_config_group ext method uses Host.authorized which again calls search_by_config_group. The authorization of host in this case is redundant, as this is a search method of host and we don't know, whether the query should be authorized or nor (e.g. system call like this). Authorized can be safely removed since host_ids are joined with the rest of conditions so if this was authorized query already, result will be authorized anyway.

2018-06-15 13:40 UTC, dLobatog requested changes
Thanks @ares , fixes the issue for me, can you add a test for the query?

2018-06-19 13:57 UTC, ares commented
added the test

2018-06-19 14:42 UTC, dLobatog submitted a review, later dismissed
@ares Did you forget to push your local changes :smile: ?

2018-06-19 21:43 UTC, ares commented
I guess I put laptop to sleep mode too early ;-) pushed now

2018-06-24 13:02 UTC, tbrisker commented
[test foreman]

2018-06-24 14:07 UTC, tbrisker approved these changes
Thanks @ares and @dLobatog !

2018-06-24 14:07 UTC, merged

2018-06-24 14:09 UTC, tbrisker commented
Set release to 1.19 for now, unless @xprazak2 considers this important enough to cp to 1.18