Fixes #23994 - Do not update templates out of scope
theforeman/foreman pull request #5725
Opened 2018-06-21 08:36 UTC by xprazak2

`JobTemplate` should import `TemplateTax` as well.

2018-06-22 08:45 UTC, lzap requested changes
Nasty.

2018-06-22 08:45 UTC, lzap commented on app/models/concerns/template_tax.rb
> +end
This is bad name for this concern, it should not mention template but rather name and also "Tax" is misleading, perhaps something like TaxonomyCollisionFinder. You can extract `:name` as parameter so it's generic and reusable across our app.

2018-06-22 08:45 UTC, lzap commented on test/models/template_test.rb
> +      end
Don't do this, we have `teardown :clear_current_taxonomies` on each test from ActiveSupport::TestCase already.

2018-06-25 08:04 UTC, xprazak2 commented
I renamed the concern and made it more generic, made changes in tests

2018-06-26 10:16 UTC, lzap commented
Test failures seem relevant.

2018-06-27 06:16 UTC, xprazak2 commented
[test]

2018-06-28 12:14 UTC, lzap approved these changes
TY

2018-06-28 12:15 UTC, merged

2018-06-28 12:15 UTC, lzap commented
Thank you very much for your contribution, this is now merged.