Fixes #23210 - Handle PuppetCA tokens
theforeman/foreman pull request #5730
Opened 2018-06-21 13:42 UTC by juliantodt

In a new SmartProxy PuppetCA autosigning variant tokens get returned that need to be provisioned on the host.
This adds a Token::PuppetCa model; moves the PuppetCa-orchestration form queue to post-queue (we need the host's id to save the token); and handles the response from the SmartProxy correctly (save the token if we get one, don't do anything if we don't).
This is completely backwards-compatible - old SmartProxy versions and the basic autosigning variant will also work with this.

2018-06-27 08:52 UTC, timogoebel reviewed
@juliantodt: Thanks, some comments inline.

2018-06-27 08:52 UTC, timogoebel commented on app/models/concerns/orchestration/puppetca.rb
> +    self.puppetca_token.delete if self.puppetca_token.present?
Please use `.destroy` so that callbacks run.

2018-06-27 08:52 UTC, timogoebel commented on app/models/concerns/orchestration/puppetca.rb
> +    post_queue.create(:name => _("Reset PuppetCA certname for %s") % self, :priority => 49,
Why do we need to take a look at the `post_queue`?

2018-06-28 10:39 UTC, juliantodt commented on app/models/concerns/orchestration/puppetca.rb
> +    post_queue.create(:name => _("Reset PuppetCA certname for %s") % self, :priority => 49,
To save tokens, we need the host's id which is only available after the host is saved, therefore we need these actions to happen in the `post_queue`

2018-06-28 12:19 UTC, juliantodt commented
Updated, thanks @timogoebel. Tests are now green as well.

2018-07-09 10:51 UTC, timogoebel requested changes
@juliantodt: Thanks. Looks good in general.
Could you please add `puppetca_token` to `Host::Managed::Jail` so it's allowed in safe mode template rendering? Thanks.

2018-07-09 19:43 UTC, juliantodt commented
@timogoebel Thanks for the review, is done.

2018-08-24 08:41 UTC, timogoebel approved these changes
Looks good to me. Ready to merge pending these PRs:

SmartProxy:
https://github.com/theforeman/smart-proxy/pull/592

Puppet Foreman Proxy:
https://github.com/theforeman/puppet-foreman_proxy/pull/433
https://github.com/theforeman/puppet-foreman_proxy/pull/425

2018-09-14 09:21 UTC, timogoebel requested changes

2018-09-14 09:21 UTC, timogoebel commented on app/models/token.rb
>      allow :host, :value, :expires, :nil?
This also needs `present?` for the community templates PR to work.

2018-09-19 07:43 UTC, juliantodt commented on app/models/token.rb
>      allow :host, :value, :expires, :nil?
Good catch. Fixed.

2018-09-19 10:16 UTC, timogoebel approved these changes

2018-09-19 10:17 UTC, merged

2018-09-19 10:17 UTC, timogoebel commented
Thanks, @juliantodt.