fixes #24046 - return id as str for name as last resort
theforeman/foreman pull request #5732
Opened 2018-06-22 14:14 UTC by stbenjam

Foreman HasManyCommon concern uses 'id' as a value of last resort for
the name of an attribute. But Rails expects this value to a return a
string. This causes a problem for Katello. Take a look at the output
here in Katello:

```
irb(main):001:0> Host.first
Hirb Error: undefined method `gsub' for 2:Integer
```

Where's that coming from?

```
<pre>
irb(main):006:0> Host.first.content_facet_attributes.to_s
=> 2
irb(main):007:0> Host.first.content_facet_attributes.to_s.is_a?(String)
=> false
</pre>
```

Foreman should use a method that returns string as a last resort.  Open to other ideas, and I'm not sure if changing this to a string is going to break something that was relying on this behavior...

2018-06-22 14:38 UTC, beav commented
This patch worked for me. I had to kill spring first to make the change get picked up.

2018-06-25 09:17 UTC, tbrisker commented on app/models/concerns/has_many_common.rb
>      send(self.class.attribute_name)
would it make sense to just add `.to_s` here? or is the `attribute_name` called not via `name_method`?

2018-06-25 09:23 UTC, tbrisker commented on app/models/concerns/has_many_common.rb
> +        :id_str
I think this may cause issues in the meta-programmed methods below, e.g. `"find_by_#{assoc_klass(association).attribute_name}"` will no longer work

2018-06-25 09:25 UTC, tbrisker requested changes
see inline comments, sorry for not doing them all in one review, just had additional thoughts after submitting the comments :)

2018-06-25 13:33 UTC, stbenjam commented
Ah yea you're right, just changing name_method to do to_s works.

2018-06-25 13:50 UTC, tbrisker approved these changes
LGTM, waiting on the butler.

2018-06-25 15:08 UTC, merged

2018-06-25 15:08 UTC, tbrisker commented
Thanks @stbenjam !