Fixes #23979 - add option to search location & organization
theforeman/foreman pull request #5740
Opened 2018-06-26 06:48 UTC by shiramax

2018-06-26 07:32 UTC, ohadlevy commented on app/controllers/api/v2/fact_values_controller.rb
> +        params[:search] = " host = " + params[:host_id] if params[:host_id]
can you please add a test for this? thanks

2018-06-26 07:46 UTC, tbrisker requested changes

2018-06-26 07:46 UTC, tbrisker commented on app/controllers/api/v2/fact_values_controller.rb
> +        params[:search] = " host = " + params[:host_id] if params[:host_id]
this should be added to the search param, not override it. also keep in mind the param might not be there.

2018-07-04 14:00 UTC, shiramax commented
thanks @tbrisker @ohadlevy , please review again :)

2018-07-10 09:09 UTC, adamruzicka commented on app/controllers/api/v2/fact_values_controller.rb
> +        params[:search] += " host = " + params[:host_id] if params[:host_id]
Doesn't the original `Api::BaseController#setup_search_options` do exactly this, but in a slightly more generic way?

2018-07-16 13:42 UTC, shiramax commented on app/controllers/api/v2/fact_values_controller.rb
> +        params[:search] += " host = " + params[:host_id] if params[:host_id]
yes, the problem is that the original  setup_search_options functions apply also to the location and organization search too, which preventing the api/cli to search by location or organization.

2018-07-16 14:03 UTC, adamruzicka commented on app/controllers/api/v2/fact_values_controller.rb
> +        params[:search] += " host = " + params[:host_id] if params[:host_id]
Ah, I see

2018-07-31 08:41 UTC, adamruzicka commented
Looks good to me, @tbrisker, @ohadlevy anything to change here?

2018-08-22 08:37 UTC, tbrisker approved these changes
Thanks @shiramax !

2018-08-22 08:37 UTC, merged