Fixes #24125 - Show error when libvirt not reachable
theforeman/foreman pull request #5762
Opened 2018-07-02 12:53 UTC by xprazak2

2018-07-02 14:20 UTC, lzap submitted a review, later dismissed
Lots of broken tests, I think they are relevant.

2018-07-02 14:20 UTC, lzap commented on app/models/compute_resources/foreman/model/libvirt.rb
> +      raise Foreman::Exception.new(msg)
The interpolation must go into exception as a parameter. Also use just one string:

```ruby
msg = N_("Full message)
raise Foreman::Exception.new(msg, errors.full_messages.join(', '))
```

2018-07-04 10:05 UTC, xprazak2 commented
Updated and fixed tests.

2018-07-05 14:35 UTC, dLobatog requested changes
Thanks, this works pretty well. I see that long error messages are clipped on the UI though (I know this is for the UI but still it'll be visible in the UI). Can you fix that? Should be ready to merge after that.

You may reproduce this easily by raising an exception with a long text on `app/models/compute_resources/foreman/model/libvirt.rb#test_connection`, for example: `raise StandardError.new("ohnoes. this libvirt is broken")` 

![screenshot from 2018-07-05 16-33-32](https://user-images.githubusercontent.com/598891/42329665-88bc1024-8071-11e8-919d-ec6d4ca7d7bb.png)


Thank you @xprazak2

2018-07-09 12:57 UTC, xprazak2 commented
Updated, truncating messages for alerts makes not sense since there is no tooltip.

![](https://i.imgur.com/X7xKJkU.png)

2018-07-10 06:23 UTC, ares commented
tests are still failing, @xprazak2 please take a look, thanks

```
--- expected
+++ actual
@@ -1,2 +1,2 @@
-"<div class=\"alert alert-danger \"><span class=\"pficon pficon-error-circle-o \"></span> <span class=\"text\"><span data-original-title=\"Failure: ActiveRecord::RecordNotFound\" rel=\"twipsy\">Failure: ActiveRecord::RecordNotFound</span></span></div>
+"<div class=\"alert alert-danger \"><span class=\"pficon pficon-error-circle-o \"></span> <span class=\"text\"><span>Failure: ActiveRecord::RecordNotFound</span></span></div>
 "
 (Minitest::Assertion)
/var/lib/workspace/workspace/test_develop_pr_core@3/database/postgresql/ruby/2.4/slave/fast/test/controllers/hosts_controller_test.rb:257    
```

2018-07-10 10:11 UTC, xprazak2 commented
[test katello]

2018-07-10 11:23 UTC, xprazak2 commented
[test katello]

Docker Meta Tags test is known to fail sometimes and this probably does not have effect on activation key audits either.

2018-07-10 12:02 UTC, dLobatog approved these changes

2018-07-10 12:03 UTC, merged

2018-07-10 13:56 UTC, tbrisker commented on app/models/compute_resources/foreman/model/libvirt.rb
> +      raise Foreman::Exception.new(msg, errors.full_messages.join(', '))
I'm not sure how this passed PR tests, but it is now failing on jenkins - https://ci.theforeman.org/job/test_develop/3603/database=postgresql,ruby=2.3,slave=fast/testReport/junit/(root)/HostJSTest__create%20new%20host%20page/test_0003_choosing_a_hostgroup_with_compute_resource_works/