Fixes #23918 - Find correct scope when updating taxonomy
theforeman/foreman pull request #5768
Opened 2018-07-04 08:41 UTC by xprazak2

[resource_scope](https://github.com/theforeman/foreman/blob/develop/app/controllers/concerns/find_common.rb#L36) caches the scope, on update the `@resource_scope` is `[]` (no idea how that happens), but `scope_for` fetches the correct scope.

2018-07-05 14:26 UTC, dLobatog requested changes
@xprazak2 It looks like it fixes the issue with hammer but could you add a test? It is unclear to me how this broke and I'm afraid we will break it again.

Thank you!

2018-07-05 14:26 UTC, dLobatog commented on app/controllers/concerns/api/v2/taxonomies_controller.rb
> +    @resource_scope = scope_for(resource_class, args).send("my_#{taxonomies_plural}")
Shouldn't this be `||=` too?

2018-07-09 06:04 UTC, xprazak2 commented on app/controllers/concerns/api/v2/taxonomies_controller.rb
> +    @resource_scope = scope_for(resource_class, args).send("my_#{taxonomies_plural}")
I do not see a reason why there is a `||=` in the first place, what if the cached data is stale?

2018-07-09 10:14 UTC, xprazak2 commented on app/controllers/concerns/api/v2/taxonomies_controller.rb
> +    @resource_scope = scope_for(resource_class, args).send("my_#{taxonomies_plural}")
`||=` seems to work here as well, so I made the change.

2018-07-09 10:15 UTC, xprazak2 commented
I added test and changed `=` to `||=`.

2018-07-10 14:53 UTC, dLobatog approved these changes

2018-07-10 14:54 UTC, dLobatog commented
```
hammer -u dlobatog -p changeme  organization add-location --id=15 --location-id=16
The location has been associated
```

Looks like it works perfectly. Thanks for the test!

cc  @jhutar @sghai

2018-07-10 14:54 UTC, merged

2018-07-11 02:35 UTC, sghai commented
@dLobatog @xprazak2 : thank you