Fixes #23703 - Remove "Create Puppet Environment" buttons
theforeman/foreman pull request #5777
Opened 2018-07-05 10:16 UTC by dLobatog

It should probably be OK to remove the "Delete" buttons from the list of
actions too. There should only be one way to get new environments/puppet
classes, and that's by clicking on the import button and selecting them.
It's less error-prone as that way we have only one path, and we can
ensure it's well tested.

2018-07-05 10:59 UTC, tbrisker requested changes
If we're removing this (which makes sense to me), then we should remove the controller action and api endpoint as well.

2018-07-05 12:00 UTC, timogoebel requested changes
Please do not remove these, we use them heavily (because importing is too slow). They are important.

2018-07-05 14:08 UTC, dLobatog commented
@timogoebel Sounds like the root of the problem is not really the button.. :smile:

2018-07-05 14:39 UTC, timogoebel commented
> @timogoebel Sounds like the root of the problem is not really the button.. 😄

True, but please don't break our existing workflow.

> If importing the environment is slow, how do you deal with importing the classes for the environment? Because that takes even longer (3 API calls, the 1st one is /environments)

If you create a new environment manually and then only import that particular environment, all is well.

2018-07-26 14:40 UTC, ekohl commented
Would splitting the process in 2 steps be better? First show a list of all the environments (without what would be changed), let the user select them and then offer 2 actions: preview and submit. Preview shows what we currently show for just the selected environments. It also allows the user to skip the preview and just do the right thing.

I think it allows to removal of the create button, but does speed up the workflow.

2018-07-26 14:44 UTC, timogoebel commented
I like the idea.

> I think it allows to removal of the create button

I don't follow. How would one create a new environment then?

2018-07-26 14:46 UTC, ekohl commented
> I don't follow. How would one create a new environment then?

By creating it on the proxy. Then you import envs from that proxy and just select the newly added one.

2018-07-26 14:49 UTC, ekohl commented
I also believe we should make [environment filters](https://theforeman.org/manuals/1.18/index.html#4.2.2Classes) more visible and easier to configure. Most envs have a lot of classes you never want to include at the ENC level.

2018-07-26 14:58 UTC, timogoebel commented
> By creating it on the proxy.

What if I want to create it first in Foreman and only then on the proxy?

2018-07-26 16:23 UTC, ekohl commented
Perhaps we should discuss the Puppet class workflow in discourse? @orrabin was also looking into other improvements like using Puppet types as hints.

2018-07-29 08:12 UTC, orrabin commented
@ekohl please link to the discussion here as I think this PR will be stuck until we get to some conclusions about the workflow. I mentioned types and @tbrisker added looking into optional/required and there is still this: https://projects.theforeman.org/issues/18564.

2018-07-29 08:34 UTC, timogoebel commented
Maybe it would help for now to add a description that the environment will be created in Foreman only and the user has to make sure it actually exists?

2018-09-16 01:23 UTC, closed without merging