[WIP] Fixes #24193 - ensures better multipexception handling in core.
theforeman/foreman pull request #5785
Opened 2018-07-09 06:05 UTC by rahulbajaj0509

2018-09-11 07:43 UTC, lzap requested changes
Looks good, this will be useful class.

2018-09-11 07:43 UTC, lzap commented on lib/foreman/exception.rb
> +    end
Please override `to_s` from Exception class instead new method name.

2018-09-11 07:43 UTC, lzap commented on lib/foreman/exception.rb
> +    end
Please create `as_json` method in Exception base class and override here (call it and merge `errors` key into the hash).

Also I suggest to do something like: `e.respond_to?(:message) ? e.message : e.to_s`

2018-10-23 09:08 UTC, lzap commented
What is the status here?

2018-12-04 11:20 UTC, rahulbajaj0509 commented
@lzap looks good?

2018-12-14 12:56 UTC, lzap approved these changes
Ok I will rewrite the message on push.

2018-12-14 12:57 UTC, merged