Fixes #24185 - logging env override config fixed
theforeman/foreman pull request #5792
Opened 2018-07-09 11:44 UTC by lzap

This does not work due to bad implementation in https://github.com/theforeman/foreman/pull/3755/files

```
:logging:
  :level: debug
  :production:
    :type: file
    :layout: pattern
```

Environment-level sub-hash overrides the root values, so level is unset
(set to default = info). This works:

```
:logging:
  :production:
    :level: debug
    :type: file
    :layout: pattern
```

And this works too:

```
:logging:
  :level: debug
  :type: file
  :layout: pattern
```

This patch fixes the very first case so it works for everyone.

2018-07-10 10:28 UTC, ares requested changes
Works well and fixes overriding in settings.yaml per environment. Given what you implemented in https://github.com/theforeman/foreman/pull/3755 could you please remove overriding per environment from config/logging.yaml example file? I'm not sure why we have this file, but at least the level can be set on both places according to the example but settings.yaml always win.

Also I don't think this is 1.18 regression, the linked PR was merged in 1.14.0. Therefore I don't think we need to merge it to 1.18-stable. Just my opinion.

2018-07-11 07:36 UTC, lzap commented
I want to keep per-env override, this patch keeps the possibility. You can't change logging.yaml file since it is in git, so the only place is settings.yaml and I want different logging settings for development and test environments (test is too verbose by default leaving gigabytes of logs).

2018-07-11 08:54 UTC, lzap commented
I vote for 1.18 here @ares @xprazak2 the fix is trivial yet being unable to set debug can be quite bad experience when troubleshooting. Since YAML is under puppet control, the comment which assumes this works is there and we can't remove it easily by changing our example file in git (puppet change would be necessary). It's much more flexible to simple fix this - which this patch really does.

2018-07-11 08:55 UTC, lzap commented
Tests are green, we are good to go.

2018-07-12 06:41 UTC, xprazak2 commented
Setting target version to 1.18.1.

2018-07-12 08:46 UTC, ares approved these changes
Ok, I understand your motivation for the patch now. I see it's benefit. I still do not understand why you ask for inclusion to 1.18, for production setups, it can be set out of :production key. There's no need for other (dev and test) envs configurations. But it's small thing and if release owner is fine with that, I'm fine too.

Merging to develop, please open a CP against 1.18-stable if you want to have it in 1.18.1

2018-07-12 08:47 UTC, merged

2018-07-26 09:51 UTC, lzap commented
Let's have it in 1.19 it's fine. We have an example in example yaml, nevermind.