Fixes #24200 - Fix ChartBox storybook
theforeman/foreman pull request #5796
Opened 2018-07-09 13:20 UTC by ripcurld

ChartBox storybook failed to load:
 * Without Data
 * With Data + Modal

The error message was:
> Element type is invalid: expected a string (for built-in components)
> or a class/function (for composite components) but got: undefined

Because the `type` prop was missing, the [`Chart`](https://github.com/theforeman/foreman/compare/develop...ripcurld:fixes_24200?expand=1#diff-c613cc11b2f0c91f5121a347d19b7be7R42) component was `undefined` showing this error message.

To fix this, I set the default value of `type` to `donut` as this is the only type right now.

2018-07-22 14:08 UTC, amirfefer requested changes
Thanks @ripcurld , I left one inline comment.

2018-07-22 14:08 UTC, amirfefer commented on webpack/assets/javascripts/react_app/components/statistics/ChartBox.js
> +  type: 'donut',
Why donut is the default type when we have also [bar chart](https://github.com/theforeman/foreman/pull/5718/files#diff-c613cc11b2f0c91f5121a347d19b7be7R88)?
Could we keep the type as required prop:
```javascript
 <ChartBox type='donut' ...>
```

2018-07-22 19:16 UTC, ripcurld commented
@amirfefer I changed the PR according as you requested.
Can you please review it again? Thanks a lot :keyboard:

2018-07-23 01:41 UTC, ripcurld commented
[test katello]

2018-07-23 10:27 UTC, amirfefer submitted a review, later dismissed
Works well,
Thanks @ripcurld !

2018-07-23 12:16 UTC, ripcurld commented
[test katello]

2018-08-07 08:33 UTC, sharvit approved these changes
LGTM! Thanks @ripcurld :+1:

2018-08-07 08:38 UTC, ohadlevy approved these changes

2018-08-07 08:38 UTC, merged

2018-08-07 08:38 UTC, ohadlevy commented
thanks @ripcurld