Remove deprecated methods for 1.20
theforeman/foreman pull request #5855
Opened 2018-07-19 09:03 UTC by tbrisker

2018-07-19 09:11 UTC, ohadlevy requested changes
I see alot more code related to two-pane - have a look at https://github.com/theforeman/foreman/search?q=two-pane&unscoped_q=two-pane

2018-07-19 14:03 UTC, tbrisker commented
Updated to remove all two-pane leftovers (hopefully)

2018-07-23 07:48 UTC, ohadlevy requested changes
tested and looks good, minor nitpick inside, could you also update the commit message? thanks

2018-07-23 07:48 UTC, ohadlevy commented on app/controllers/application_controller.rb
> +  layout "application"
That's the default, you can omit the layout call.

2018-07-23 08:12 UTC, tbrisker commented on app/controllers/application_controller.rb
> +  layout "application"
thanks, updated

2018-07-23 08:19 UTC, ohadlevy approved these changes

2018-07-23 12:23 UTC, tbrisker commented
Test failure unrelated, care to pull the trigger @ohadlevy ?

2018-07-23 12:26 UTC, merged

2018-07-23 12:26 UTC, ohadlevy commented
thanks @tbrisker