Fixes #24303 - New hostgroup after submit path
theforeman/foreman pull request #5861
Opened 2018-07-19 13:50 UTC by sharvit

Change the url to hostgroups_path
after creating a new hostgroup

2018-07-19 13:51 UTC, sharvit commented
`data-history-url` getting used here:
https://github.com/theforeman/foreman/blob/develop/app/assets/javascripts/host_edit.js#L153-L155

2018-07-19 15:25 UTC, dLobatog requested changes
@sharvit How about a unit test for this :smile: ? Thank you!

2018-07-22 14:01 UTC, sharvit commented
Thanks for the review @dLobatog, test added

2018-07-23 12:33 UTC, ripcurld commented on test/integration/hostgroup_js_test.rb
> +    assert page.has_current_path? hostgroups_path
shouldn't it be `have_current_path`?
I think `has_current_path?` returns `true` or `false` while `have_current_path` returns the current URL (after waiting).

2018-07-23 18:10 UTC, dLobatog approved these changes
I manually confirmed it fixes the issue too. This looks like an issue where it must have been difficult to find why is it happening, thanks @sharvit

2018-07-23 18:10 UTC, dLobatog commented on test/integration/hostgroup_js_test.rb
> +    assert page.has_current_path? hostgroups_path
@ripcurld https://www.rubydoc.info/github/jnicklas/capybara/Capybara/SessionMatchers#has_current_path%3F-instance_method

I think this is fine, the assert is just verifying `has_current_path?` returns true. If I'm not wrong, you are mistaking `assert` by `assert_equal` (we're not comparing hostgroups_path to the result of `page.current_path` in the assertion)

2018-07-23 18:10 UTC, merged