Fixes #24386 - Update foreman-debug to include proxy certs generate.
theforeman/foreman pull request #5873
Opened 2018-07-25 15:31 UTC by chris1984

2018-07-25 15:39 UTC, chris1984 commented
@lzap can I get a review please?

2018-07-26 10:01 UTC, lzap requested changes
There is slightly different naming convention as you'd expect:

```
[root@sat-r220-07 ~]# ll /var/log/foreman-proxy-certs-generate.*log
-rw-r--r--. 1 root root 117278 Apr 30 11:37 /var/log/foreman-proxy-certs-generate.10.log
-rw-r--r--. 1 root root 131204 Apr 30 11:23 /var/log/foreman-proxy-certs-generate.11.log
-rw-r--r--. 1 root root 130025 Apr 30 11:02 /var/log/foreman-proxy-certs-generate.12.log
-rw-r--r--. 1 root root      0 Mar 17 15:26 /var/log/foreman-proxy-certs-generate.13.log
-rw-r--r--. 1 root root  21157 Mar 17 15:18 /var/log/foreman-proxy-certs-generate.14.log
-rw-r--r--. 1 root root  21150 Dec  4  2017 /var/log/foreman-proxy-certs-generate.15.log
-rw-r--r--. 1 root root      0 Dec  4  2017 /var/log/foreman-proxy-certs-generate.16.log
-rw-r--r--. 1 root root      0 Dec  4  2017 /var/log/foreman-proxy-certs-generate.17.log
-rw-r--r--. 1 root root      0 Dec  4  2017 /var/log/foreman-proxy-certs-generate.18.log
-rw-r--r--. 1 root root 129104 May  9 11:06 /var/log/foreman-proxy-certs-generate.1.log
-rw-r--r--. 1 root root 131227 May  9 10:43 /var/log/foreman-proxy-certs-generate.2.log
-rw-r--r--. 1 root root 129455 Apr 30 16:39 /var/log/foreman-proxy-certs-generate.3.log
-rw-r--r--. 1 root root      0 Apr 30 15:23 /var/log/foreman-proxy-certs-generate.4.log
-rw-r--r--. 1 root root 117279 Apr 30 15:22 /var/log/foreman-proxy-certs-generate.5.log
-rw-r--r--. 1 root root 116673 Apr 30 13:42 /var/log/foreman-proxy-certs-generate.6.log
-rw-r--r--. 1 root root      0 Apr 30 12:47 /var/log/foreman-proxy-certs-generate.7.log
-rw-r--r--. 1 root root  89711 Apr 30 12:33 /var/log/foreman-proxy-certs-generate.8.log
-rw-r--r--. 1 root root 117279 Apr 30 12:33 /var/log/foreman-proxy-certs-generate.9.log
-rw-r--r--. 1 root root 128777 May  9 11:06 /var/log/foreman-proxy-certs-generate.log
```

2018-07-26 10:01 UTC, lzap commented on script/foreman-debug
> +add_files /var/log/foreman-proxy-certs-generate.log*
It should be actually this: `/var/log/foreman-proxy-certs-generate.*log`

2018-07-26 16:12 UTC, chris1984 commented
@lzap Updated, good catch!

2018-07-26 20:35 UTC, chris1984 commented
[test foreman]

2018-07-26 21:29 UTC, chris1984 commented
[test katello]

2018-07-27 08:00 UTC, lzap approved these changes
TY

2018-07-27 08:00 UTC, merged