Fixes #24476: add SR-IOV virtual functions to the ignored NIC list
theforeman/foreman pull request #5887
Opened 2018-07-30 12:15 UTC by evgeni

this new naming was introduced in udev v239
(https://github.com/systemd/systemd/commit/609948c7043a40008b8299529c978ed8e11de8f6)

2018-07-31 06:53 UTC, ares commented
I don't know if we did it in past, but this does not solve the issue for existing users right? Should we have a migration that adds this record if it's missing? Or should we only document in upgrade notes? Otherwise, :+1: for the patch.

2018-07-31 06:58 UTC, evgeni commented
I could not find a migration for the last change of that list. But I also must admit I only quickly `git grep`ed for it.

2018-08-07 12:47 UTC, ShimShtein approved these changes
If the user didn't change the default value, it will be updated automatically on seed (runs by the RPM).

In case the user changed the value, we need to publish upgrade notes.

2018-08-07 12:50 UTC, ShimShtein requested changes
Sorry for taking this PR back and forth, but for completeness sake we also need to update [`:ignored_interface_identifiers`](https://github.com/theforeman/foreman/blob/706b4aecc9b98e739420077f40473daacf1d5046/test/fixtures/settings.yml#L268) fixture.

2018-08-07 13:54 UTC, ShimShtein commented
@lzap, anything to add?

2018-08-08 07:49 UTC, ShimShtein commented
[test foreman]

2018-08-08 12:50 UTC, ShimShtein approved these changes

2018-08-08 13:33 UTC, lzap approved these changes
Nothing to add other than the systemd PR mentions that before the patch the name was `enp101s0f0` and after `eno1v0`. Shall we also ignore the "old" naming pattern?

2018-08-08 13:34 UTC, evgeni commented
@lzap the old naming *also* included real NICs with multiple functions, which I did not dare to exclude :/

2018-08-08 13:38 UTC, lzap commented
Oh right, this is of course a valid NIC name, how nice :-) It's GO from me, thanks!

2018-08-08 13:39 UTC, merged

2020-06-25 09:44 UTC, lzap commented
Hey, we have a report that this patch created a regression - it filters some facts named `_env` which is pretty common fact name. Was there a reason to filter out `en*v*` instead of `eno*v*`? The systemd patch mentioned specifically that these names are onboard, thus `eno`.

https://projects.theforeman.org/issues/30209

2020-06-25 10:32 UTC, evgeni commented
I don't really remember. Probably because I've seen "en1v1" somewhere. Or thought I have seen...