Fixes #24261 - pagination CSS is wrong on assign hosts for taxonomy
theforeman/foreman pull request #5899
Opened 2018-07-31 21:27 UTC by ripcurld

The reason why this happens is because there is a nested form:
the host pagination nested under hosts assign.

Because of that the form tag in pagination is not rendered.
To fix this, the form tag in pagination was replaced by div.

Why?:
It seems like the pagination does not have to be a form. It
can be a div element that its select handles the onchange event
which calls `turbolinks.visit`.

/cc @ohadlevy @lizagilman

2018-08-01 01:32 UTC, ripcurld commented
[test katello]

2018-08-01 01:32 UTC, ripcurld commented
[test foreman]

2018-08-01 07:09 UTC, ripcurld commented
[test foreman]

2018-08-08 12:25 UTC, lizagilman commented
LGTM :+1:

2018-08-16 10:44 UTC, tbrisker requested changes
This breaks the ability to type a page number in the pagination. Also small comment inline.

2018-08-16 10:44 UTC, tbrisker commented on test/integration/organization_js_test.rb
> +    (1..10).map{ Host.create }
you can use `FactoryBot.create_list(:host, 10, organization: nil)` instead

2018-08-25 18:46 UTC, ripcurld commented
[test foreman]

2018-08-26 00:02 UTC, ripcurld commented
[test foreman]

2018-08-26 10:55 UTC, ripcurld commented
[test foreman]

2018-09-13 07:01 UTC, ohadlevy commented
@boaz1337 whats the status of this PR? thanks.

2018-09-13 08:13 UTC, boaz1337 commented
@tbrisker - can you review this change, please? :pray:

2018-10-04 09:45 UTC, boaz1337 commented
https://github.com/theforeman/foreman/commit/d4e81e9610de1d1802d2747d47c4badd60e5150d fixes this.

2018-10-04 09:45 UTC, closed without merging