fixes #24503 - remove snippets macro
theforeman/foreman pull request #5901
Opened 2018-08-01 09:09 UTC by timogoebel

2018-08-01 10:20 UTC, boaz0 reviewed
Code LGTM :+1:

2018-08-08 13:46 UTC, ares commented
test failures unrelated, @timogoebel  by not being used you mean they are not used on community templates right? I think we should solve it the same way that we decide at https://github.com/theforeman/foreman/pull/5900/files/85170114b8d1a572ca568c644d554eb462751ae2#diff-f3f86650376a3e2c3698174c127d2608

otherwise +1 for removal with hope users didn't use it in their custom templates

2018-08-09 12:53 UTC, lzap submitted a review, later dismissed
I like deleting lines!

2018-08-16 08:56 UTC, tbrisker requested changes

2018-08-16 08:56 UTC, tbrisker commented on lib/foreman/renderer/scope/macros/snippet_rendering.rb
> -              snippet(file.gsub(/^_/, ""), options)
If i understand correctly, this branch is not broken, so it would be best to deprecate it before removing

2018-08-16 08:56 UTC, tbrisker commented on lib/foreman/renderer/scope/macros/snippet_rendering.rb
> -              render :partial => "unattended/snippets/#{file}"
This branch has not been working since 1.15 when the template folder structure was changed so it can be safely removed.

2018-08-21 15:03 UTC, timogoebel commented
@tbrisker: added the deprecation warning and removed the broken code.

2018-08-22 08:06 UTC, tbrisker approved these changes
Thanks @timogoebel!

2018-08-22 08:07 UTC, merged

2018-08-22 08:08 UTC, tbrisker commented
Please update the [nightly manual](https://github.com/theforeman/theforeman.org/blob/gh-pages/_includes/manuals/nightly/1.2_release_notes.md#deprecations) with the deprecation of this function.