Fixes #24551 - Change all matcher attributes to lowercase
theforeman/foreman pull request #5951
Opened 2018-08-15 12:35 UTC by orrabin

This was a result of `sorted_values` getting the path before sanitizing + the fact that we didn't change the matcher to lowercase even though the path is changed to lowercase.

2018-08-15 12:35 UTC, orrabin commented
@tbrisker please take a look, there might be a change to `sorted_values` that could change instead.

2018-09-02 12:42 UTC, tbrisker requested changes
It makes sense to normalize both in the same way when saving, although there might be some unexpected result for fact name matchers since they can be uppercase (e.g. `LANG`). They won't work today anyways since we lowercase the path, so I won't block on this.
However for data in the DB that causes breakage i think this needs the `sorted_values` to change as well so the loading doesn't fail - I don't think this is worth a migration since the function is only used in the UI and adding `downcase` there should be enough to allow opening any existing values that aren't normalized.
Also, i think a rebase should fix tests.

2018-12-25 13:12 UTC, tbrisker commented on app/models/lookup_value.rb
> +    self.match = match.split(LookupKey::KEY_DELM).map do |m|
this is still remaining, you can just `return true unless match.present?` before

2018-12-25 14:07 UTC, orrabin commented
@tbrisker I rebased and fixed the failing cop. Can we open a bug about the uppercase facts separately since it's not working today either?

2018-12-25 14:23 UTC, tbrisker approved these changes
LGTM, lets wait for tests to finish. feel free to create an issue though i doubt fixing it would be easy or worth the effort considering it never worked and noone reported it is broken yet.

2018-12-25 15:27 UTC, tbrisker commented
failures unrelated. Thanks @orrabin !

2018-12-25 15:27 UTC, merged