Fixes #24652 - subnet_for returns highest CIDR prefix
theforeman/foreman pull request #5960
Opened 2018-08-17 17:06 UTC by lzap

It returns randomly sorted by VLANID which can be used as a workaround.
This patch sorts them by CIDR prefix, which we unfortunately don'ŧ store
in the database so we need to sort in-memory.

Proper solution would be to store both probably, with a database index.
Let's do this in another path tho.

2018-08-17 17:13 UTC, ekohl commented on app/models/subnet.rb
> +      Subnet.unscoped.all.select {|s| s.family == ip.family && s.contains?(ip)}.sort {|a,b| b.cidr <=> a.cidr}.first
Isn't https://ruby-doc.org/core-2.5.1/Enumerable.html#method-i-max_by better than (reverse) sorting and taking the first?

2018-08-21 14:26 UTC, lzap commented on app/models/subnet.rb
> +      Subnet.unscoped.all.select {|s| s.family == ip.family && s.contains?(ip)}.sort {|a,b| b.cidr <=> a.cidr}.first
This is indeed good idea, thanks! Rebased.

2018-08-22 16:02 UTC, lzap commented
Rebased for tests to pass due to FactoryGirl5 issue.

2018-08-23 10:24 UTC, ekohl submitted a review, later dismissed

2018-08-26 12:03 UTC, tbrisker requested changes
Can you please also add a test for ipv6? 
I'm not too concerned about finding max in memory, in most cases there will only be 1-2 matching subnets. I think that's better than storing cidr in db and having to make sure it is in sync with the mask all the time.

2018-08-26 12:03 UTC, tbrisker commented on app/models/subnet.rb
> +      Subnet.unscoped.all.select {|s| s.family == ip.family && s.contains?(ip)}.max_by {|x| x.cidr}
you can also use `.max_by(&:cidr)`, but it's not crucial.

2018-08-28 11:18 UTC, lzap commented
I agree on the other hand I am pretty sure there is somebody with Foreman having 10,000 subnets. Anyway, rebased the shorter syntax and added IPv6 test, good idea.

2018-08-28 11:25 UTC, ekohl approved these changes
If needed you could fall back to DB native checks like https://github.com/theforeman/foreman/pull/5623 but the existing code also operates in memory so this isn't regressing.

2018-08-28 11:27 UTC, tbrisker commented
@lzap there may be users with that many subnets but the max is only done for the matching subnets, the select would be done anyways in memory since I don't think we have a good way of checking if an ip is in a subnet at the db level.

2018-08-29 10:27 UTC, lzap commented
Katello::Api::Rhsm::CandlepinDynflowProxyControllerIntegrationTest.test_0001_params are not parsed in the controller failure not related it appears.

2018-09-25 09:20 UTC, lzap commented
What is the status @tbrisker or @ekohl please?

2018-10-04 15:33 UTC, tbrisker approved these changes
Thanks @lzap !

2018-10-04 15:34 UTC, merged