Fixes #24740: document --watch-poll for NFS
theforeman/foreman pull request #6007
Opened 2018-08-29 13:17 UTC by akofink

From https://community.theforeman.org/t/webpack-watch-over-nfs/10922/2

2018-08-29 18:31 UTC, ekohl submitted a review, later dismissed

2018-08-30 07:17 UTC, lizagilman commented
Failing tests unrelated? 
They seem to fails in some other pr's as well

2018-08-30 12:01 UTC, akofink commented
I'd hope a readme change wouldn't cause tests to fail. ;)

2018-08-30 12:20 UTC, lizagilman commented
@akofink oops didn't notice :rofl:

2018-09-01 12:59 UTC, mmoll requested changes

2018-09-01 12:59 UTC, mmoll commented on webpack/stories/docs/gettingStarted.md
> +      --cacert /etc/pki/katello/certs/katello-default-ca.crt\
please add a space before the backslash

2018-09-04 12:00 UTC, akofink commented
Updated

2018-09-04 12:10 UTC, mmoll approved these changes

2018-09-04 12:10 UTC, merged

2018-09-04 12:10 UTC, mmoll commented
merged, thanks @akofink!