Fixes #24745 - new variables kernel/initrd_uri
theforeman/foreman pull request #6010
Opened 2018-08-29 14:52 UTC by lzap

In our rendering there are two variables kernel_uri and initrd_uri, but these are relative. It is useful to have absolute URI addresses for various kinds of provisioning, including Discovery kexec. Previously discovery was monkey patching this, if these variables are present in default foreman core renderer context this would make discovery code cleaner. It can be useful also for other provisioning types like iPXE.

Although this is reachable via `medium_provider.medium_uri + @kernel` or
`@initrd` this is convinient to have it in variables.

2018-08-29 16:10 UTC, timogoebel approved these changes
The code looks good to me, but I haven't tested this.

2018-08-30 07:44 UTC, timogoebel requested changes
@lzap: Looks good and works great. Do you mind addind a small test for this, something like https://github.com/theforeman/foreman/blob/e65038056d56257b32d20b61e2c683fe4b8f3c3a/test/unit/foreman/renderer/scope/variables/base_test.rb#L64-L65?

2018-08-30 13:42 UTC, lzap commented
Will do, I think @ShimShtein raised concern what other scenarios these variables can be used except discovery. I believe this can be useful in iPXE templates.

2018-08-30 13:54 UTC, lzap commented
I have amended the last commit, thank you for review.

2018-08-30 13:57 UTC, timogoebel approved these changes
Good enough, thanks.

2018-08-31 07:43 UTC, merged

2018-08-31 07:43 UTC, timogoebel commented
Test failures were unrelated.