Fixes #24348 - Validate compute resources is within taxonomy
theforeman/foreman pull request #6027
Opened 2018-09-03 06:42 UTC by bastilian

2018-09-03 15:25 UTC, tbrisker requested changes
A couple of small comments inline. otherwise looks good!

2018-09-03 15:25 UTC, tbrisker commented on app/models/host/managed.rb
> +  validate :compute_resource_in_taxonomy, :if => Proc.new { |host| SETTINGS[:locations_enabled] && host.managed? && host.compute_resource_id.present? }
I think the test should be for `Taxonomy.enabled_taxonomies.any?`, since there may be just one or the other enabled.

2018-09-03 15:25 UTC, tbrisker commented on test/controllers/hosts_controller_test.rb
> +      Foreman::Model::Libvirt.unstub(:max_cpu_count)
don't stubs get removed automatically in teardown?

2018-09-04 09:45 UTC, tbrisker approved these changes
Thanks @bastilian !

2018-09-04 09:45 UTC, tbrisker requested changes
actually looks like a whole bunch of tests just broke...

2018-09-04 11:00 UTC, bastilian commented
Could it be that the factory for `:libvirt_cr` in `:with_dns_orchestration` is not passing down the location and org?

I tried this, but it throws a factorybot attribute error with "location already defined".
```ruby
    # host_releated.rb:317
    trait :with_dns_orchestration do
      managed
      taxonomies = {}
      # add taxonomy overrides in case it's set in the host object
      taxonomies[:locations] = [location] unless location.nil?
      taxonomies[:organizations] = [organization] unless organization.nil?
      compute_resource do
        FactoryBot.create(:libvirt_cr, taxonomies)
      end
      subnet do
        FactoryBot.create(:subnet_ipv4, taxonomies.merge({:dns => FactoryBot.create(:dns_smart_proxy)}))
      end
      domain do
        FactoryBot.create(:domain,
          :dns => FactoryBot.create(:smart_proxy,
                    :features => [FactoryBot.create(:feature, :dns)])
        )
      end
      interfaces do
        [FactoryBot.build(:nic_managed, :primary => true,
                                         :provision => true,
                                         :domain => FactoryBot.build(:domain),
                                         :ip => subnet.network.sub(/0\Z/, '1'))]
      end
    end
```

Weirdly taxonomies are in some cases disabled, but the validation still seems to execute.

2018-09-06 07:57 UTC, bastilian commented
@tbrisker the trait definitions are now fixed (thanks to @ares :)) and test should turn green(ish).

2018-09-06 11:01 UTC, mmoll commented
[test foreman]
[test upgrade]
[test katello]

2018-09-06 13:49 UTC, tbrisker approved these changes
Test failures unrelated. Thanks @bastilian !

2018-09-06 13:49 UTC, merged