Fixes #24850 - Do not add usergroup to itself
theforeman/foreman pull request #6054
Opened 2018-09-10 14:07 UTC by xprazak2

2018-09-10 14:34 UTC, ares commented
If I understand correctly, we display the same hostgroup in edit form? Could we also hide it? The check is still important for API, but we should prevent users doing wrong assignment before they hit the error.

2018-09-11 07:24 UTC, xprazak2 commented on app/views/usergroups/_form.html.erb
> +      <%= multiple_checkboxes f, :usergroups, @usergroup, Usergroup.except_current(@usergroup),
We hide it.

2018-10-03 05:58 UTC, ares requested changes
Usergroup test failure seems related

2019-02-06 11:53 UTC, xprazak2 commented
[test katello]

2019-02-11 07:23 UTC, xprazak2 commented
[test katello]

2019-02-21 08:16 UTC, xprazak2 commented
Rebased and updated tests, lets see what Jenkins will say.

2019-02-21 11:52 UTC, xprazak2 commented
I do not expect content view and audit test are affected by the changes.

2019-03-21 15:23 UTC, ares approved these changes
Thanks @xprazak2, fixes the issue, merging!

2019-03-21 15:23 UTC, merged