Refs #23113 - Allow disabling out of sync in widget for All
theforeman/foreman pull request #6092
Opened 2018-09-26 07:04 UTC by bastilian

When all origins have out of sync disabled the widget for
all hosts will now discard the link too.

2018-11-21 07:29 UTC, bastilian commented
[test foreman]

2018-11-22 18:39 UTC, ares commented
Please don't use refs, open a separate issue for this. The original issue was resolved in 1.18.0, if we don't plan to backport to 1.18 (there's no 1.18.z planned AFAIK), we need a new issue to set the fixed version correctly. Just link the new issue with the original one in redmine for reference.

2018-12-11 08:54 UTC, bastilian commented
[test foreman]

2018-12-11 08:58 UTC, tbrisker commented on app/services/dashboard/data.rb
> +      hosts.distinct.includes(:reports).pluck('reports.origin').compact
```suggestion
      Report.where(host: hosts).distinct.pluck('origin').compact
```

2018-12-11 09:26 UTC, tbrisker reviewed
Adding the comments we talked about (and one extra we didn't :))

2018-12-11 09:26 UTC, tbrisker commented on app/services/dashboard/data.rb
> +      settings[:origin] && settings[:origin] == 'All'
this should remain `!= 'All` and function should be renamed accordingly (maybe also make it private?)

2018-12-11 09:26 UTC, tbrisker commented on app/services/dashboard/data.rb
> +      @hosts = @hosts.with_last_report_origin(settings[:origin]) unless for_all_origin?
should remain `if`

2018-12-11 09:26 UTC, tbrisker commented on app/services/dashboard/data.rb
> +        hosts.out_of_sync_setting_for(settings[:origin])
i think this should be `hosts.out_of_sync_for(out_of_sync_setting_for(settings[:origin]))` or something similar?

2018-12-11 09:26 UTC, tbrisker commented on app/services/dashboard/data.rb
> +        host_origins.map { |origin| out_of_sync_setting_for(origin) }.any?
you can pass the block directly to `any?` (https://ruby-doc.org/core-2.5.3/Enumerable.html#method-i-any-3F): 
```suggestion
        host_origins.any? { |origin| out_of_sync_setting_for(origin) }
```

2018-12-12 07:53 UTC, tbrisker commented on app/services/dashboard/data.rb
> +      hosts.distinct.includes(:reports).pluck('reports.origin').compact
Looks like this was reverted in the rebase?

2019-01-22 13:55 UTC, ares requested changes
one comment, otherwise looks sane

2019-01-22 13:55 UTC, ares commented on app/services/dashboard/data.rb
> +      @hosts = @hosts.with_last_report_origin(settings[:origin]) unless for_all_origin?
you switched if to unless but the definition of `for_all_origin?` does not seem to be negation of the original condition. what if there's no `settings[:origin]`? is that intentional?

2019-01-22 13:55 UTC, ares commented on app/services/dashboard/data.rb
> +        host_origins.any? { |origin| out_of_sync_setting_for(origin) }
this condition looks switched, `is_not_all_origin?` returns true if origin is specific one, so the else branch should apply

2019-07-23 01:23 UTC, closed without merging