WIP - template requirements and import for seeding templates
theforeman/foreman pull request #6104
Opened 2018-10-03 14:18 UTC by tstrachota

- Changes seeding mechanism for provisioning and report templates. It
  uses template importing now.
- Template import allows checking for presence of templates in certain
  versions. Metadata can contain section `require:` with list of
  requirements.

  For example:
```yaml
  require:
    - plugin: katello  # checks whether Katello is installed in any version
    - plugin: katello
      version: 3.9.0   # checks whether Katello >- 3.9.0 is installed
```

TODO:

- [ ] add tests for `import_raw_template`
- [ ] create a PR into community templates that adds operating systems and kinds into metadata of all templates

2018-10-03 14:19 UTC, tstrachota commented
@ares, @mbacovsky please take a look.

2018-10-04 11:11 UTC, mbacovsky commented
@tstrachota are there any plans to dispose templates during upgrades? If there is e.g. required Katello version < 3.8.0 can we remove/replace the template during upgrade?

2018-10-04 11:22 UTC, tstrachota commented
> are there any plans to dispose templates during upgrades?

@mbacovsky No. If a template has the same name, an upgrade will just change the contents (i.e. it works the same way as before).

2018-10-04 13:17 UTC, ares requested changes
Looks good, few minor suggestions. I'll continue with testing.

2018-10-04 13:17 UTC, ares commented on lib/seed_helper.rb
> +        raise "Unable to create template #{t.name}: #{format_errors t}" unless t.valid?
this could be added blow the block to deduplicate, e.g.
```
 if !t.persisted?
  t.organizations = Organization.unscoped.all if SETTINGS[:organizations_enabled]
  t.locations = Location.unscoped.all if SETTINGS[:locations_enabled]
end
raise "Unable to create template #{t.name}: #{format_errors t}" if !t.persisted && !t.valid?
```

2018-10-04 13:17 UTC, ares commented on lib/seed_helper.rb
> +          Foreman::Logging.logger('app').debug("Template #{template_name} requires plugin #{r['plugin']}")
if this happens only during seeding, we should increase the log level to info and perhaps also say "skipping this template" or something like that

2018-10-04 13:17 UTC, ares commented on lib/seed_helper.rb
> +          Foreman::Logging.logger('app').debug("Template #{template_name} requires plugin #{r['plugin']} >= #{r['version']}")
again, saying skipping could help understand what's going on from reading the logs

2018-10-04 14:07 UTC, tstrachota commented on lib/seed_helper.rb
> +        raise "Unable to create template #{t.name}: #{format_errors t}" unless t.valid?
There's difference in words "create" vs. "update". I didn't want to combine it into one message.

2018-10-04 14:11 UTC, tstrachota commented
@ares updated, my changes are in a separate commit.

2018-10-04 14:52 UTC, ares requested changes
The tests fail now because we used the templates lists in migrations too. We'll need to use `Dir["#{Rails.root}/app/views/unattended/provisioning_templates/**/*.erb"]` and parse names out of them there. Perhaps we could have that as methods in SeedHelper method to avoid repetition?

Otherwise it works great on my local setup, we need to fix the clean db setups. Once there's PR for community-templates I'll retest but looks as it's really close.

2018-10-05 08:09 UTC, tstrachota commented
@ares updated, let's see what the tests say now.

2018-10-05 08:33 UTC, tstrachota commented
The related PR into community templates is here: https://github.com/theforeman/community-templates/pull/521

2018-10-05 12:02 UTC, tstrachota commented
@ares updated and squashed. Thanks for your patch!

2018-10-05 13:04 UTC, ares approved these changes
looks good codewise, also tested all I could think of and work well now, waiting on jenkins to confirm the last failure was resovled

2018-10-05 14:51 UTC, ares commented
2 known failures and one that I see the first time but only on sqlite and passes locally on sqlite so I believe it's unrelated.

Thanks @tstrachota, merging! I'm keeping two commits separate so it's clear templates were synced too.

2018-10-05 14:51 UTC, merged