Fixes #25197- onChange debounce too slow
theforeman/foreman pull request #6137
Opened 2018-10-14 13:31 UTC by Laviro

While typing something very quickly and pressing 'Enter' to search,
the onChange function is not fast enough to update the current `searchQuery`.
Removing the debounce on the onChange  fix this problem.

2018-10-14 15:46 UTC, Laviro commented
[test foreman katello]

2018-10-14 15:46 UTC, Laviro commented
[test foreman]

2018-10-14 15:47 UTC, Laviro commented
[test katello]

2018-10-15 08:51 UTC, tbrisker requested changes
Removing the debounce completely makes the search send every single letter i type when typing quickly, which is the original reason the debounce was introduced,

2018-10-15 09:04 UTC, Laviro commented
the `onChange` updates the store with the current `searchQuery`,
if it won't update before a fast `Enter` press, the last char/s won't be searched.
I tried to bring the `debounce` to the minimum but it wasn't fast enough if I very(!!) quickly pressed `Enter`.

removing the `debounce` allowed the `onChange` to update the `store` quickly enough to be searched if hitting `Enter` in this speeds.

2018-10-15 09:11 UTC, boaz1337 commented
I agree with @tbrisker. It sounds like the API and onChange are coupled, we need to separate those two mechanisms into different functions.
onChange needs to change the Redux state and not to call on API.
The API calls will be done in a different part.

2018-10-15 12:13 UTC, Laviro commented
thanks @boaz1337 @tbrisker,
the original `handleSearch` prop was receiving the `searchQuery` from the store, and if you triggered the `handleSearch` in the same second that you changed the input, there was a chance that the `handleSearch` didn't receive the updated `searchQuery`.

I added a debounce to the `handleSearch` and it looks good now.

2018-10-15 12:56 UTC, Laviro commented
[test katello]

2018-10-17 10:48 UTC, Laviro commented
After discussing this with @boaz1337 & @tbrisker offline,
I added the `debounce` to the API call in `AutoCompleteActions`,
and removed all of the unnecessary `debounce` methods in `index`

2018-10-24 13:18 UTC, Laviro commented
coverage is reduced only because I am not using `helpers/debounceMethods` anymore.

2018-10-25 11:10 UTC, tbrisker approved these changes
Works well, thanks @Laviro !

2018-10-25 11:10 UTC, merged

2018-10-25 11:17 UTC, tbrisker commented
:cherries: to 1.20 as fac3d5444