Fixes #25203 - set hosts count to 0 if null
theforeman/foreman pull request #6140
Opened 2018-10-15 11:15 UTC by boaz1337

`ngettext` expects the last argument to be a number while `factCharts.hostsCount` is initialized to null in Redux.

When rendering the `factChart` modal the number of hosts is translated using `ngettext`.

However, if `factChart` is rendered before the data arrives the component will fail printing the error below in the console:

> The number that was passed in is not a number

To fix this if `factCharts.hostsCount` is null pass to `ngettext` 0 in the last argument instead of `factCharts.hostsCount`.

2018-10-15 11:45 UTC, tbrisker submitted a review, later dismissed
Thanks @boaz1337 !

2018-10-15 12:41 UTC, amirfefer requested changes

2018-10-15 12:41 UTC, amirfefer commented on webpack/assets/javascripts/react_app/components/factCharts/index.js
> +    const hostsCount = factChart.hostsCount || 0;
The counter still shows on the modal title (just an odd `( hosts)`) while loading or no data exists:
![counting](https://user-images.githubusercontent.com/11807069/46951341-5b464500-d090-11e8-960b-4fb0ffddcb47.png)

IMHO this is better:
![notitle](https://user-images.githubusercontent.com/11807069/46951437-a3656780-d090-11e8-9b6e-f153ddeaf215.png)

2018-10-15 12:43 UTC, amirfefer commented
BTW, I've pushed few minutes after you a [fix](https://github.com/theforeman/foreman/pull/6141) :)

2018-10-15 13:07 UTC, boaz1337 commented
I am closing this in favor of #6141

2018-10-16 12:40 UTC, amirfefer approved these changes
Thanks @boaz1337 
Works well :+1:

2018-10-16 12:41 UTC, tbrisker approved these changes
Thanks @boaz1337 and @amirfefer !

2018-10-16 12:42 UTC, tbrisker commented
[test foreman]

2018-10-16 14:45 UTC, merged