Fixes #22898 - Preview fails on /clone_template
theforeman/foreman pull request #6190
Opened 2018-11-01 02:47 UTC by apuntamb

Since we are using `dup` method to get a cloned template, but `dup` typically uses the class of the existing template object to create the new instance and since it is a new instance, id that it gets is nil. So, I have tried here, to store the id of the template before cloning it and later, using it when the template is cloned.

2018-11-01 06:11 UTC, apuntamb commented
I could see a test failure in `audit_mailer_test` for [Audit template change should not crash](https://ci.theforeman.org/job/test_develop_pr_core/20104/database=postgresql,ruby=2.4,slave=fast/testReport/junit/(root)/AuditMailerTest/test_0006_Audit_template_change_should_not_crash/) . 

Is this test failure related ?

2018-11-04 16:36 UTC, tbrisker commented
[test foreman] - let's see if that failure is consistent. But I'm not sure that retaining the same ID as the original template is the right way to go - the cloned template should get a new ID of it's own, not the same as the old one (but I may be missing something here).

2018-11-12 07:34 UTC, apuntamb commented
@tbrisker sure.
If that is the case, then may be even I'm missing something. @lzap any views ?

2018-11-12 15:56 UTC, lzap commented
Aditi, hey. This is a hack, you can do this in a nicer way I think. Our controller works fine if the id is missing completely: `http://localhost:3000/templates/provisioning_templates//preview`

You can modify this code in `_toolbar.html.erb`:

```erb
    <% if show_preview %>
      <span id="preview_host_selector" style="display:none">
        <%= text_field_tag :preview_host_id, nil,
            :'data-url' => preview_host_collection_hosts_path,
            :'data-scope' => controller.send(:model_of_controller),
            :name => '',
            :onchange => 'tfm.editor.getRenderedTemplate()' %>
      </span>
    <% end %>
```

You can call `preview_host_collection_hosts_path` only if you have both ID and NAME, otherwise just render it as `//` (empty element) and it will work both for new and clone requests.

If you want to make this clean, then you can create the `preview` action to be collection scope, so then this `http://localhost:3000/templates/provisioning_templates//preview` can be this `http://localhost:3000/templates/provisioning_templates/preview`. You will need to update few other places probably to get both new and clone working but this is probably the cleanest approach.

2018-11-12 15:57 UTC, lzap requested changes
Therefore I am giving this thumbs down for now.

2018-11-19 09:19 UTC, lzap commented
Ok I was pointing to a wrong code. Anyway, preview action already is both resource and collection level:

```ruby
  scope 'templates' do
    resources :report_templates, :except => [:show] do
      member do
        get 'clone_template'
        get 'lock'
        get 'unlock'
        get 'export'
        get 'generate'
        post 'schedule_report'
        post 'preview'
      end
      collection do
        post 'preview'
        get 'revision'
        get 'auto_complete_search'
      end
    end
  end
```

That's good, just make sure the code does not generate the double `//` and it will be passed correctly. Looks like the collection-level route is not in use, code might need to be fixed in order to return useful response.

2018-11-29 17:32 UTC, lzap commented
That's much shorter and elegant, good work. What is the status? Ready for testing?

2018-11-30 07:23 UTC, apuntamb commented
@lzap Thank you.
I'll just work on these nit picks. I guess then it would be ready for testing.

2018-11-30 09:15 UTC, apuntamb commented
Foreman tests are red with these [failures](https://ci.theforeman.org/job/test_develop_pr_core/20653/). Are these related in some way ?

2018-11-30 13:29 UTC, ares commented
@apuntamb no these seems unrelated

2018-12-03 06:25 UTC, apuntamb commented
@ares @lzap Great, then it seems ready for testing.

2018-12-05 13:56 UTC, lzap approved these changes
LGTM I will test next week unless someone wants to test it!

2018-12-10 14:47 UTC, merged

2018-12-10 14:48 UTC, lzap commented
Nice and small patch. I like those! :-)