Fixes #25483 - keep false facts
theforeman/foreman pull request #6253
Opened 2018-11-16 14:15 UTC by ares

2018-11-16 14:15 UTC, ares commented
we ignore all incoming facts with value false, becase there was a check for `value.present?`. `false` value is never present :-)

2018-11-16 15:03 UTC, ekohl commented on app/services/structured_fact_importer.rb
> +    facts.keep_if { |k, v| !v.nil? || (v.is_a?(String) && !v.empty?) }
Maybe `delete_if { |k, v| v.nil? || (v.is_a?(String) && v.empty?) }` is easier to read

2018-11-20 14:26 UTC, lzap requested changes
This needs a test.

2018-11-20 14:26 UTC, lzap commented on app/services/structured_fact_importer.rb
> +    facts.keep_if { |k, v| !v.nil? || (v.is_a?(String) && !v.empty?) }
Sure, can you rebase please?

2018-12-20 10:43 UTC, ares commented
modified the condition, rebased and added a test

2018-12-20 12:17 UTC, ekohl submitted a review, later dismissed

2018-12-20 12:36 UTC, lzap submitted a review, later dismissed

2018-12-20 12:37 UTC, lzap commented
```

Offenses:

app/helpers/operatingsystems_helper.rb:9:3: C: Metrics/CyclomaticComplexity: Cyclomatic complexity for icon is too high. [24/23]
  def icon(record, opts = {}) ...
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^

2229 files inspected, 1 offense detected
```

2018-12-20 13:33 UTC, ares commented
@lzap that's unrelated, being discussed at https://github.com/theforeman/foreman/pull/6356

2018-12-22 05:20 UTC, mmoll commented
ok to test

2018-12-22 12:46 UTC, mmoll approved these changes

2018-12-22 12:47 UTC, mmoll commented
GH-6355 already fixed the rubocop failure

2018-12-22 12:50 UTC, merged

2018-12-22 12:50 UTC, mmoll commented
merged, díky @ares!