Fixes #25487 - Fix subtotal in API response
theforeman/foreman pull request #6254
Opened 2018-11-16 16:44 UTC by johnpmitsch

When requesting an endpoint with a search parameter, the subtotal
shows the results returned, rather than responses found. i.e. even
if 200 results were found, if 20 are being returned because of
pagination, the subtotal will be 20.

This changes back to using `count`, which sends another SQL query
and returns the correct subtotal.

It looks like this was updated (with good intention) for performance reasons https://github.com/theforeman/foreman/pull/5993/files#r213566553

2018-11-16 16:45 UTC, johnpmitsch commented on app/controllers/api/v2/base_controller.rb
> +        @total ||= resource_scope.try(:count).to_i
This total isn't incorrect (afaict), should we use count here as well?

2018-11-16 16:46 UTC, johnpmitsch commented
credit to @iNecas and @mbacovsky for the investigation :mag:

2018-11-16 16:48 UTC, iNecas commented
It would be good to add some test to cover this behavior (I'm sure we would not hit this issue, if there was some testing for this before).

2018-11-16 20:26 UTC, johnpmitsch commented
@iNecas I added testing. I figured the best way to test the metadata is a real endpoint, so I added to the host controller tests. Let me know if there is a better way

2018-11-18 10:29 UTC, tbrisker requested changes
good catch! me-- for introducing this. A couple of minor comments inline.

2018-11-18 10:29 UTC, tbrisker commented on test/controllers/api/v2/hosts_controller_test.rb
> +        100.times { |_| FactoryBot.create(:host) }
you can use `FactoryBot.create_list` instead

2018-11-18 10:29 UTC, tbrisker commented on test/controllers/api/v2/hosts_controller_test.rb
> +      assert_equal hosts_response["subtotal"], ::Host.all.count
I don't think the  `::` is needed here

2018-11-18 10:29 UTC, tbrisker commented on app/controllers/api/v2/base_controller.rb
> +        @total ||= resource_scope.try(:count).to_i
I think here `size` should be safe and save one query possibly, but that's what tests are for

2018-11-19 15:49 UTC, johnpmitsch commented
@tbrisker thanks for the suggestions, I updated the tests to test for total too. I set up the hosts under "Empty org" so the subtotal and total are different for the test with the search parameter. I changed the metadata_total to use `size` again and it is still passing the tests :+1:

2018-11-26 14:26 UTC, johnpmitsch commented
[test foreman]

2018-11-29 13:57 UTC, johnpmitsch commented
@tbrisker does this approach look ok to you?

2018-11-29 16:36 UTC, iNecas submitted a review, later dismissed
Works for me

2018-12-02 15:13 UTC, tbrisker reviewed
sorry for dropping the ball here, just a couple of small inline comments

2018-12-02 15:13 UTC, tbrisker commented on test/controllers/api/v2/hosts_controller_test.rb
> +      assert_equal hosts_response["total"], Host.all.count
There is a hidden assumption here, that not all hosts are in `@empty_org` - perhaps assert that the subtotal and total are different?

2018-12-02 15:13 UTC, tbrisker commented on test/controllers/api/v2/hosts_controller_test.rb
> +        FactoryBot.create_list(:host, 100, organization: @empty_org)
instead of creating 100 entries, you can create a smaller list (say 10) and pass a smaller per_page parameter in the request (say 5)

2018-12-03 15:23 UTC, johnpmitsch commented
@tbrisker thanks, updated according to your suggestions

2018-12-03 15:32 UTC, tbrisker approved these changes
Thanks @johnpmitsch , lgtm!

2018-12-03 17:15 UTC, merged

2018-12-03 17:15 UTC, iNecas commented
Tests failures unrelated, Thanks @johnpmitsch and @tbrisker

2018-12-03 17:20 UTC, iNecas commented
Cherry-pick PR here https://github.com/theforeman/foreman/pull/6299