Fixes #25537 - Layout unwanted action calls
theforeman/foreman pull request #6269
Opened 2018-11-22 14:49 UTC by glekner

The Eventhandler for `popstate` is not working as intended.
the `changeActiveonBack` function was called even though there was no back click in the browser.
resulting in unneeded action calls.

also fixed dispatching an action for changing the activeMenu which is equal to the current one.

2018-11-25 13:50 UTC, ohadlevy commented
@sharvit @amirfefer can you review please?

2018-11-25 14:44 UTC, sharvit requested changes

2018-11-25 14:44 UTC, sharvit commented on webpack/assets/javascripts/react_app/components/Layout/__tests__/__snapshots__/Layout.test.js.snap
> +  activePath="/undefined/"
Is this a bug?

2018-11-25 14:44 UTC, sharvit commented on webpack/assets/javascripts/react_app/components/Layout/LayoutSelectors.js
> +export const selectIsLoading = state => selectLayout(state).isLoading;
Would be nice to add test to this new selector.

2018-11-25 15:03 UTC, glekner commented
applied @sharvit suggestions. also added a selector test helper from katello.

2018-11-25 15:47 UTC, sharvit approved these changes
LGTM! Thanks @glekner :+1:

2018-11-26 10:35 UTC, ohadlevy approved these changes

2018-11-26 10:35 UTC, merged