[WIP] Fixes #25548 - SearchBar bug on hosts page
theforeman/foreman pull request #6279
Opened 2018-11-26 10:49 UTC by Laviro

**Description of problem:**

Unable to search host in search box for all host

**Steps to Reproduce:**
1. Go on all hosts page
2. click on search box and type to search

**Actual results:**
As soon as we try to search, search box is gets disappear with error on browser console.

**Expected results:**
User should able to search from available hosts.

2018-11-26 15:48 UTC, ares commented
sorry, doesn't fix the problem on my setup :-(

2018-11-29 08:57 UTC, Laviro commented
@ares Thanks, I didn't have the plugins environment yet,
so I just tried to fix it on blind.
on `Forklift centos7-devel` machine with katello there was no error,
trying to set up `centos7-luna-devel`, as I heard from coworkers that it fails there,
and than try to debug it and fix the problem.

2018-11-29 14:11 UTC, Laviro commented
Finally ! @ares 
I succeeded to reproduce the bug on `vagrant@centos7-luna-devel`.
The problem was that the results was passed as an `Immutable array`,
and now when it is passed as `mutable` array, the bug is fixed.

@sharvit, @amirfefer Could you also take a look ?

2018-11-29 14:22 UTC, sharvit requested changes
Nice work @Laviro :+1:

2018-11-29 14:22 UTC, sharvit commented on webpack/assets/javascripts/react_app/components/AutoComplete/AutoCompleteSelectors.js
> +export const selectAutocomplete = state => state.autocomplete;
+1 for adding selectors.

Can you please add tests?

2018-11-29 14:22 UTC, sharvit commented on webpack/assets/javascripts/react_app/components/AutoComplete/AutoCompleteSelectors.js
> +export const selectAutocompleteResults = state => selectAutocomplete(state).results.asMutable();
Where do we actually break the `immutability`?
Can we change the consumer of the `results` array so it won't break the `immutability`?
If a 3rd party component breaks the `immutability`? If so can we pass the `results.asMutable()` only to the problematic component?

2018-11-29 14:45 UTC, boaz0 requested changes
No! Please don't do that.

You can read from the error message:
```
The push method cannot be invoked on an Immutable data structure
```

It seems that somewhere `push` is invoked on `results`! That's bad! The object is supposed to be immutable while `push` mutates the object.

I am against this :cry:

2018-11-29 14:47 UTC, ohadlevy submitted a review, later dismissed
:+1: to what others said, this seems like we didn't find the root cause to the issue.

2018-11-29 15:21 UTC, sharvit commented
@boaz1337 It seems that a 3rd party package do that and it is not apart of our source code.

If the 3rd party component changes the `results` array for its own inner usage and not in order to affect the state. I am fine with passing `asMutable` only to the relevant 3rd party property.

2018-11-29 16:05 UTC, sharvit commented
Code wise looks good to me! Thanks, @Laviro :+1: 

@ares can you verify please?

2018-11-29 16:42 UTC, amirfefer commented on webpack/assets/javascripts/react_app/components/AutoComplete/index.js
> +    const options = (results.asMutable && results.asMutable()) || results;
how about 
```js 
Immutable.isImmutable(results) ? results.asMutable() : results;
```
looks more clear to me

2018-11-29 17:02 UTC, boaz1337 commented
@sharvit what library/package and where?

Returning a mutable object might be OK but a comment explaining that is a must. :newspaper_roll: 

Thanks. :dango:

2018-11-29 18:01 UTC, sharvit commented
@boaz1337 I think it is the `TypeAheadSelect` from `patternfly-react`, @Laviro can you confirm?

I agree about the comment :+1:

2018-11-29 18:07 UTC, boaz1337 commented
@Laviro Sweet heaven is it because of [react-bootstrap-typeahead](https://github.com/ericgio/react-bootstrap-typeahead)? :cloud_with_lightning:

2018-11-29 18:29 UTC, Laviro commented
@boaz1337 yes, it happens while passing the Immutable array as results to the `react-bootstrap-typeahead`. While passing it as mutable everything works fine.
Not sure yet what causes it inside the `react-bootstrap-typeahead`.
Though this change really fix it.

2018-11-29 18:32 UTC, boaz1337 commented
All mighty! Can we open a ticket? Or maybe open a pull request?
As much I want this fixed as soon as possible I have a feeling fixing it on `react-bootstrap-typeahead` side.

Anyway, please write a comment explaining why you're doing the `asMutable` magic (explaining that react-bootstrap-typeahead is mutating it before displaying it in the menu or something similar).

2018-11-30 15:15 UTC, ares commented
Works great, fixes the issue for me. I think @boaz1337 last comment about adding a comment was not yet addressed, also linking upstream issue/PR that we've opened would be nice. Once I get ack from @boaz1337 I'm happy to merge, @ohadlevy won't be around so I'll have to dismiss his review :-)

2018-12-02 16:10 UTC, Laviro commented
@amirfefer updated, your request,
@boaz1337 added the comment, do you approve?
I'll open a PR to `react-bootstrap-typeahead` soon trying to fix this problem.

2018-12-02 16:55 UTC, boaz1337 commented
Do you know what version of `react-bootstrap-typeahead` this happens? I cannot reproduce it on `develop`.
Maybe it was fixed and all is needed is to update the package to have the newest version of that npm?

2018-12-03 11:10 UTC, amirfefer approved these changes
passing a mutable copied object from our store to a 3-rd party package seems fine to me.
Thanks @Laviro  works great :+1:

2018-12-03 12:09 UTC, Laviro commented
@boaz1337 it happens on host page, you can reproduce it with `luna`,
I think it happens when passing a massive array with options to `react-bootstrap-typeahead`,
maybe than they try to manipulate the options.

anyway on our side there are no `push` method invoked on the array, 
and when passing the array as mutable to  `react-bootstrap-typeahead` it works perfect.

2018-12-03 12:10 UTC, Laviro commented
[test upgrade]

2018-12-03 12:34 UTC, boaz1337 commented
@Laviro - thanks for the details.
Right now, my resources are low so I am trying to reproduce it on `develop`.
You're saying if I have many hosts and I run a search query then the problem will appear, right?

2018-12-03 13:54 UTC, Laviro commented
Yes @boaz1337, I doubled checked and pushed an immutable array of all countries as the default options,
and it happened again.

2018-12-04 08:19 UTC, Laviro commented
[test upgrade]

2018-12-04 10:28 UTC, boaz0 commented
It looks good to me, just one small thing: 

can you specify the version of react-bootstrap-typeahead?
or have a link to the issue on react-bootstrap-typeahead?

That's all.

2018-12-04 10:39 UTC, Laviro commented
thanks @boaz1337, patternfly is using `"react-bootstrap-typeahead": "^3.1.3",`
just opened an [issue](https://github.com/ericgio/react-bootstrap-typeahead/issues/398) in `react-bootstrap-typeahead`

2018-12-04 10:42 UTC, boaz0 approved these changes
LGTM

2018-12-04 12:42 UTC, sharvit approved these changes
LGTM! Thanks @Laviro :+1:

2018-12-04 14:48 UTC, ares approved these changes
Thanks @Laviro and all reviewers. @ohadlevy I'm merging since I know you'll be offline for few days. I believe the cause has been found and this is the best we can do for now in order to fix the issue.

2018-12-04 14:48 UTC, merged

2018-12-05 15:17 UTC, tbrisker commented
1.20 :cherries: - 01e416a68