Fixed #25485 - Release name required for debian
theforeman/foreman pull request #6329
Opened 2018-12-12 21:55 UTC by sbernhard

2018-12-13 08:48 UTC, tbrisker requested changes

2018-12-13 08:48 UTC, tbrisker commented on app/models/operatingsystem.rb
> +  validates :release_name, :presence => true, :if => Proc.new { |o| o.family == 'Debian' }
Shouldn't this be done in `app/models/operatinsystems/debian.rb`?

2018-12-13 09:25 UTC, sbernhard commented
Would be good but unfortunately, the "validates" in operatingsystem/debian.rb are not executed.

2018-12-13 13:27 UTC, tbrisker commented
@sbernhard - Ah, right, when we create an operating system we don't have the subclass set yet. 
However, i noticed `:set_family` callback is executed in `before_save` (which runs after validation), could there be a case in which the family isn't set yet when the validation runs? maybe we need to move that to `before_validate`?

2018-12-14 14:42 UTC, sbernhard commented
The test "release_name should be nil when lsbdistcodename isn't set on Debian" is broken (as expected). Does someone has a good idea how to proceed? What should be done, in case a debian-based system doesn't provide the lsbdistcodename (=release_name) during the fact import?

2018-12-23 13:55 UTC, tbrisker commented
@sbernhard I am not very familiar with the workings of debian systems, but is that a valid scenario (i.e. a debian not reporting distname in facts)? if not - than that test isn't valid and can be removed. if it is - we need to decide what we do in that case - use some sort of placeholder ("unknown"?), try to guess, fail the import?

2018-12-27 10:47 UTC, sbernhard commented
[test katello]

2018-12-27 13:21 UTC, sbernhard commented
Looks like the katello test are broken but don't know why and I don't think its because this PR. Any suggestions what to do?

2018-12-30 20:38 UTC, tbrisker commented
@sbernhard don't worry about the katello failure, it is unrelated. I assume from the latest commit that the dist name is always reported on all debians?

2018-12-30 21:34 UTC, sbernhard commented
Thanks @tbrisker for the information. 

It looks like that the release name should be always in the facts. Don't know why it shouldn't be there.

2018-12-31 08:45 UTC, tbrisker commented
@sbernhard i did a bit more research and turns out that this fact only works on debians if you have the `lsb-release` package installed (see https://blog.x-way.org/Linux/2012/02/14/Fix-empty-puppet-lsbdistcodename-on-Debian.html for example). So I think to make sure we don't break fact imports with this change we need to add some handling for it around https://github.com/theforeman/foreman/blob/develop/app/services/puppet_fact_parser.rb#L40 - perhaps set to 'unknown' in case it wasn't set before and isn't in the facts (so we don't update an existing one)

2019-01-07 18:57 UTC, sbernhard commented
> @sbernhard i did a bit more research and turns out that this fact only works on debians if you have the `lsb-release` package installed (see https://blog.x-way.org/Linux/2012/02/14/Fix-empty-puppet-lsbdistcodename-on-Debian.html for example). So I think to make sure we don't break fact imports with this change we need to add some handling for it around https://github.com/theforeman/foreman/blob/develop/app/services/puppet_fact_parser.rb#L40 - perhaps set to 'unknown' in case it wasn't set before and isn't in the facts (so we don't update an existing one)

Thank you very much for the help @tbrisker.

2019-01-07 23:11 UTC, sbernhard commented
> @sbernhard i did a bit more research and turns out that this fact only works on debians if you have the `lsb-release` package installed (see https://blog.x-way.org/Linux/2012/02/14/Fix-empty-puppet-lsbdistcodename-on-Debian.html for example). So I think to make sure we don't break fact imports with this change we need to add some handling for it around https://github.com/theforeman/foreman/blob/develop/app/services/puppet_fact_parser.rb#L40 - perhaps set to 'unknown' in case it wasn't set before and isn't in the facts (so we don't update an existing one)

Thank you very much for your help @tbrisker. Added one more test to represent the change.

2019-01-08 13:49 UTC, tbrisker commented
Thanks @sbernhard, one last request regarding this - if there are any debian OSes in the db already without release name this will make them invalid, can you add a migration updating them? Something along the lines of 
```ruby
OperatingSystem.where(type: 'Debian', release_name: [nil, '']).update_all(release_name: 'unknown')
```
should do it.

2019-01-08 22:49 UTC, jlsherrill commented
[test foreman]
[test katello]

2019-01-09 09:45 UTC, tbrisker approved these changes
Thanks @sbernhard !

2019-01-09 09:47 UTC, merged