Fixes #25648 - Delete filters as system admin
theforeman/foreman pull request #6330
Opened 2018-12-13 08:55 UTC by xprazak2

2018-12-13 09:33 UTC, san7ket submitted a review, later dismissed
As a system admin, I was able to delete the filter on role successfully

2018-12-18 15:56 UTC, ares requested changes

2018-12-18 15:56 UTC, ares commented on app/controllers/filters_controller.rb
> +                         Filter.authorized_as(User.current, current_permission)
as suggested on IRC, `Filter.authorized(current_permission)` would be nicer if it works

2018-12-20 12:54 UTC, xprazak2 commented
Changed, `Filter.authorized(current_permission)` worked for me.

2018-12-21 10:40 UTC, ares approved these changes

2018-12-21 10:40 UTC, ares commented
Thanks @xprazak2, merging!

2018-12-21 10:40 UTC, merged