Fixes #25810 - migrate react-bootstrap to patternfly-react
theforeman/foreman pull request #6394
Opened 2019-01-09 09:14 UTC by MariaAga

Refs #22001 #22232 #22006

2019-01-09 09:47 UTC, ohadlevy commented
[ok to test]

2019-01-14 16:22 UTC, amirfefer requested changes
Thanks @MariaAga ! 
The breadcrumbs bar doesn't render at all with this change, having this js error:
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite 
components) but got: undefined. You likely forgot to export your component from the file it's defined in, or
 you might have mixed up default and named imports.

Check the render method of `BreadcrumbSwitcher`.
```

Plus, the statistics page looks different now, from this:
![statistics-1](https://user-images.githubusercontent.com/11807069/51125339-136ac180-1829-11e9-9b07-e0e30fe9c54e.png)
To this:
![statistics-2](https://user-images.githubusercontent.com/11807069/51125349-18c80c00-1829-11e9-8d83-9d01a78fa523.png)

I like the new look though
but for next time, just upload some screenshots  if there's any change :)

2019-01-15 15:10 UTC, MariaAga commented
@amirfefer Did rebase, and couldn't reproduce this issue.

2019-01-20 12:18 UTC, ohadlevy commented
can we remove react-bootstrap from package.json now?

2019-01-20 12:22 UTC, ohadlevy submitted a review, later dismissed
when trying out the PR, I've noticed the following error in my browse logs:
```
react-dom.development.js:506 Warning: validateDOMNesting(...): <h3> cannot appear as a child of <h2>.
    in h3 (created by ChartBox)
    in h2 (created by CardTitle)
    in CardTitle (created by ChartBox)
    in div (created by CardHeading)
    in CardHeading (created by ChartBox)
    in div (created by Card)
    in Card (created by ChartBox)
    in ChartBox (created by StatisticsChartsList)
    in div (created by StatisticsChartsList)
    in StatisticsChartsList (created by Connect(StatisticsChartsList))
    in Connect(StatisticsChartsList) (created by I18nProviderWrapper(Connect(StatisticsChartsList)))
    in IntlProvider (created by I18nProviderWrapper(Connect(StatisticsChartsList)))
    in I18nProviderWrapper(Connect(StatisticsChartsList)) (created by StoreProvider(I18nProviderWrapper(Connect(StatisticsChartsList))))
    in Provider (created by StoreProvider(I18nProviderWrapper(Connect(StatisticsChartsList))))
    in StoreProvider(I18nProviderWrapper(Connect(StatisticsChartsList))) (created by DataProvider(StoreProvider(I18nProviderWrapper(Connect(StatisticsChartsList)))))
    in DataProvider(StoreProvider(I18nProviderWrapper(Connect(StatisticsChartsList))))
```

2019-01-21 14:34 UTC, MariaAga commented
@ohadlevy Removed the `Card.Title` and now its ok.
Design changed to:
![screenshot-localhost-5000-2019 01 21-16-31-50](https://user-images.githubusercontent.com/30431079/51480712-4fa6a080-1d9a-11e9-8c76-d62534a25045.png)

2019-01-21 14:37 UTC, ohadlevy commented
this looks wrong...? why not use the card title?

On Mon, Jan 21, 2019 at 4:34 PM MariaAga <notifications@github.com> wrote:

> @ohadlevy <https://github.com/ohadlevy> Removed the Card.Title and now
> its ok.
> Design changed to:
> [image: screenshot-localhost-5000-2019 01 21-16-31-50]
> <https://user-images.githubusercontent.com/30431079/51480712-4fa6a080-1d9a-11e9-8c76-d62534a25045.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/theforeman/foreman/pull/6394#issuecomment-456094121>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AABOx6QREIKfbbG69L4c5qR4UkcdGTBXks5vFc_bgaJpZM4Z3D3M>
> .
>

2019-01-22 09:47 UTC, MariaAga commented
Using the `Card.Title` makes that design,:
![screenshot-localhost-5000-2019 01 22-11-46-27](https://user-images.githubusercontent.com/30431079/51526589-60f3b980-1e3b-11e9-8318-693ba8cef06b.png)

Is it better?

2019-03-01 18:41 UTC, ohadlevy commented
@MariaAga can you rebase please?

2019-03-01 18:41 UTC, ohadlevy commented on app/models/report.rb
> -          source_count = Source.unscoped.joins(:logs).where("logs.report_id" => report_ids).delete_all
why is this part of the PR?

2019-03-07 13:59 UTC, MariaAga commented on app/models/report.rb
> -          source_count = Source.unscoped.joins(:logs).where("logs.report_id" => report_ids).delete_all
Removed. thanks

2019-03-21 14:47 UTC, waldenraines commented
[test foreman]
[test katello]

2019-03-28 22:25 UTC, waldenraines submitted a review, later dismissed
LGTM, @amirfefer @ohadlevy any other comments?

2019-04-05 12:36 UTC, mmoll commented
@MariaAga please rebase

2019-04-07 09:39 UTC, MariaAga commented
@mmoll, rebased thanks!

2019-04-07 11:27 UTC, mmoll commented
@amirfefer @ohadlevy anything missing here?

2019-04-07 11:28 UTC, mmoll commented
@MariaAga actually, I think the foreman test failure is related :broken_heart:

2019-04-07 12:15 UTC, MariaAga commented
@mmoll Thank you! I've change the statistics page test as it was looking for h3 titles instead of the new h2 titles

2019-04-07 12:19 UTC, Ron-Lavi submitted a review, later dismissed
Thanks @MariaAga, Looks great :+1: :trophy:

2019-04-07 13:55 UTC, ohadlevy commented
should we remove the entry from package.json then? @sharvit ?

2019-04-21 09:36 UTC, ohadlevy commented
bump on the package.json question please?

2019-04-28 20:49 UTC, mmoll commented
@MariaAga also, please rebase :)

2019-04-28 20:57 UTC, ohadlevy commented
also, I think it makes sense to add the cards-pf css class to the container to fit better https://www.patternfly.org/pattern-library/content-views/card-view

2019-04-29 08:00 UTC, sharvit commented
Thanks @MariaAga :+1: 

> should we remove the entry from package.json then? @sharvit ?

afaik we can remove it from `package.json` and `webpack.vendor.js`

2019-04-29 08:21 UTC, MariaAga commented
@ohadlevy, I don't think we should add this class as it causes this grey background:
![image](https://user-images.githubusercontent.com/30431079/56883873-a47c4600-6a70-11e9-8ae1-a3068e2d8bb6.png)
or this (when applying in the container of the container):
![image](https://user-images.githubusercontent.com/30431079/56883937-d8f00200-6a70-11e9-874a-611933d108a2.png)

2019-04-29 08:29 UTC, ohadlevy commented
@MariaAga - the grey background does look better than white on white, I do wonder whats the difference in our styles that make it look different to patternfly? IMHO we should have grey backgrounds with cards, for example in a similar screen (in this case openshift)
![image](https://user-images.githubusercontent.com/20167/56884318-11dca680-6a72-11e9-95ce-d19afa11e8b7.png)

2019-04-29 09:09 UTC, MariaAga commented
@ohadlevy  How about this? (or maybe this with more padding in the container)
![image](https://user-images.githubusercontent.com/30431079/56886383-97af2080-6a77-11e9-93ee-dddfbf1613a4.png)

2019-04-29 09:12 UTC, ohadlevy commented
> @ohadlevy How about this? (or maybe this with more padding in the container)

mind providing full page screenshot? regarding if its better, I would delegate to @theforeman/ui-ux designers?

2019-04-29 09:21 UTC, MariaAga commented
Sure!
![image](https://user-images.githubusercontent.com/30431079/56886805-7f8bd100-6a78-11e9-8e7e-79074eedf461.png)
![image](https://user-images.githubusercontent.com/30431079/56886869-af3ad900-6a78-11e9-8ea4-d8932536567f.png)

2019-05-02 09:30 UTC, ohadlevy commented
@MariaAga please remove the bootstrap-react npm from package.json ?

2019-05-02 09:54 UTC, MariaAga commented
Removed from package.json and webpack.vendor.js

2019-05-02 15:26 UTC, sharvit submitted a review, later dismissed
Thanks @MariaAga LGTM :+1:

2019-05-02 15:28 UTC, sharvit commented
@ekohl does it need a packaging PR?
`react-bootsrap` removed from core package.json but getting installed via `patternfly-react`?

2019-05-09 21:30 UTC, mmoll commented
@ekohl @ehelms @evgeni :point_up:

2019-05-16 17:47 UTC, mmoll approved these changes
RPMs should be fine, AFAICT.

2019-05-16 17:47 UTC, merged

2019-05-16 17:47 UTC, mmoll commented
merged, thanks @MariaAga!