Fixes #25818 - Show facts for single host API call
theforeman/foreman pull request #6398
Opened 2019-01-09 19:57 UTC by johnpmitsch

I could be missing the reason this isn't working as expected,
but for some hosts like virt-who hypervisors, I am not seeing
facts showing for GET /hosts/<id>. On other hosts, I see the
facts showing up. I'll provide more examples to illustrate this
point.

2019-01-09 20:07 UTC, johnpmitsch commented
I've had to test this out with https://github.com/Katello/katello/pull/7821 so the facts are reported correctly for virt-who hypervisors

I could be missing a reason `facts` is excluded from the rabl files, please explain if I am. I am seeing facts not show up for virt-who hypervisors.

i.e.
I have a virt-who hypervisor
Facts in console

```ruby
irb(main):021:0> Host.find(8).facts
=> {"hypervisor::type"=>"QEMU", "cpu::cpu_socket(s)"=>"1", "hypervisor::version"=>"2010001", "_timestamp"=>"2019-01-08 21:03:53 +0000", "hypervisor"=>nil, "cpu"=>nil}
```
But not in API, even the `facts` attribute itself is missing

```
[vagrant@coffee foreman{develop}]$ curl -g -k -u admin:changeme -H "Content-Type: application/json"  https://coffee.jomitsch.example.com/api/v2/hosts/8 | jq '.facts'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3162    0  3162    0     0  13165      0 --:--:-- --:--:-- --:--:-- 13230
null
```

For a normal Katello content host:

facts are in both API and console

```
irb(main):022:0> Host.find(3).facts
=> {"system::certificate_version"=>"3.2", "uname::sysname"=>"Linux", ... }

[vagrant@coffee foreman{develop}]$ curl -g -k -u admin:changeme -H "Content-Type: application/json"  https://coffee.jomitsch.example.com/api/v2/hosts/3 | jq '.facts'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10510    0 10510    0     0  39243      0 --:--:-- --:--:-- --:--:-- 39363
{
  "system::certificate_version": "3.2",
  "uname::sysname": "Linux",
  ...
}
```

2019-01-10 15:47 UTC, tbrisker requested changes
Is it possible the subscription facts are added by the subscription facet to the view? 
in general pulling all facts for a host can be very slow due to the size of the facts tables, in foreman core we don't show facts on the host show endpoint but only on `api/hosts/$id/facts` for this reason. 
If we want to show facts, i would hide it behind a toggle that defaults to not showing them as that can cause a significant degradation in api performance.

2019-01-10 15:47 UTC, tbrisker commented on app/views/api/v2/hosts/main.json.rabl
> +           :last_compile, :global_status, :global_status_label, :facts
this will add facts to the index as well, which will be *very* slow.

2019-01-10 16:17 UTC, johnpmitsch commented
@tbrisker thanks for explaining, it must be something we are doing in Katello that is showing facts for a content host, but not others. I'll dig into it more and see if changes can be made in Katello to show facts for virt-who hypervisors as well or rework the UI to use the `host/id/facts` endpoint since that will be more reliable.

If its ok, I'll keep this PR open until I figure something out just in case some foreman changes or more discussion is needed

2019-01-15 16:16 UTC, johnpmitsch commented
I'm closing this since it seems like we can work this out in Katello. Thanks for the help!

2019-01-15 16:16 UTC, closed without merging