Fixes #25098 - Validate compute resource taxonomy on NIC creation
theforeman/foreman pull request #6402
Opened 2019-01-10 11:41 UTC by bastilian

In cases where the compute resource is not in the same taxonomy as
the host, creating NICs is raising an error when trying to get to
the compute resource, which is out of scope, to ask for attributes
provided by it.

2019-01-14 07:43 UTC, bastilian commented
[test foreman,katello]

2019-01-14 07:44 UTC, bastilian commented
[test foreman][test katello]

2019-01-14 11:07 UTC, ares requested changes
The code looks good but it doesn't solve the issue in my case. It seems running nic validation triggeres the orchestration. But the orchestration code asks for compute attributes when checking whether compute resource gives back IP addresses.

Here's the trace

```
2019-01-14T12:00:13 [W|app|336d4705] Action failed
 | NoMethodError: undefined method `provided_attributes' for nil:NilClass
 | /home/ares/Projekty/Zdrojaky/foreman/app/models/concerns/orchestration/compute.rb:30:in `compute_provides?'
 | /home/ares/Projekty/Zdrojaky/foreman/app/models/nic/base.rb:182:in `compute_provides_ip?'
 | /home/ares/Projekty/Zdrojaky/foreman/app/services/nic_ip_required/base.rb:58:in `compute_provides_ip?'
 | /home/ares/Projekty/Zdrojaky/foreman/app/services/nic_ip_required/base.rb:20:in `required?'
 | /home/ares/Projekty/Zdrojaky/foreman/app/models/nic/base.rb:166:in `require_ip4_validation?'
 | /home/ares/Projekty/Zdrojaky/foreman/app/models/nic/base.rb:35:in `block in <class:Base>'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:426:in `instance_exec'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:426:in `block in make_lambda'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:178:in `block (2 levels) in halting_and_conditional'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:178:in `each'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:178:in `all?'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:178:in `block in halting_and_conditional'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:513:in `block in invoke_before'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:513:in `each'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:513:in `invoke_before'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:816:in `_run_validate_callbacks'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activemodel-5.2.1/lib/active_model/validations.rb:409:in `run_validations!'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activemodel-5.2.1/lib/active_model/validations/callbacks.rb:118:in `block in run_validations!'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:132:in `run_callbacks'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:816:in `_run_validation_callbacks'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activemodel-5.2.1/lib/active_model/validations/callbacks.rb:118:in `run_validations!'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activemodel-5.2.1/lib/active_model/validations.rb:339:in `valid?'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/validations.rb:67:in `valid?'
 | /home/ares/Projekty/Zdrojaky/foreman/app/models/concerns/orchestration.rb:86:in `valid?'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/autosave_association.rb:329:in `association_valid?'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/autosave_association.rb:316:in `block in validate_collection_association'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/autosave_association.rb:316:in `each'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/autosave_association.rb:316:in `each_with_index'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/autosave_association.rb:316:in `validate_collection_association'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/autosave_association.rb:220:in `block in define_autosave_validation_callbacks'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/autosave_association.rb:159:in `instance_eval'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/autosave_association.rb:159:in `block in define_non_cyclic_method'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:426:in `block in make_lambda'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:605:in `catch'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:605:in `block in default_terminator'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:199:in `block in halting'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:513:in `block in invoke_before'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:513:in `each'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:513:in `invoke_before'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:816:in `_run_validate_callbacks'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activemodel-5.2.1/lib/active_model/validations.rb:409:in `run_validations!'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activemodel-5.2.1/lib/active_model/validations/callbacks.rb:118:in `block in run_validations!'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:132:in `run_callbacks'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:816:in `_run_validation_callbacks'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activemodel-5.2.1/lib/active_model/validations/callbacks.rb:118:in `run_validations!'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activemodel-5.2.1/lib/active_model/validations.rb:339:in `valid?'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/validations.rb:67:in `valid?'
 | /home/ares/Projekty/Zdrojaky/foreman/app/models/concerns/orchestration.rb:86:in `valid?'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/validations.rb:84:in `perform_validations'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/validations.rb:46:in `save'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:310:in `block (2 levels) in save'
 | /home/ares/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/ [...]

2019-01-14 20:59 UTC, chris1984 commented
[test katello]

2019-01-21 17:50 UTC, chris1984 reviewed
@ares did you want me to kick off VMware regression tests against this pr or no?

2019-01-22 16:37 UTC, ares approved these changes
Thanks @bastilian, now it works as expected and improves the experience! Merging

2019-01-22 16:37 UTC, merged

2019-01-22 19:15 UTC, tbrisker commented
looks like this wasn't rebased on latest develop and now tests are failing with `ActiveRecord::RecordInvalid: Validation failed: Interfaces.compute resource is not defined for host's organization, Interfaces.compute resource is not defined for host's location` - e.g. http://ci.theforeman.org/job/test_develop/database=mysql,ruby=2.5,slave=fast/lastCompletedBuild/testReport/(root)/Api__V2__HostsControllerTest___host__id_power_status/test_0001_show_power_status_for_a_host/