fixes #25732 - select MIME type for reports
theforeman/foreman pull request #6423
Opened 2019-01-21 06:22 UTC by amitkarsale

Choose MIME type for report download.

2019-01-21 07:06 UTC, ohadlevy commented on app/models/report_template.rb
> +  def suggested_report_name(type)
can write (type = 'csv') in method signature

2019-01-21 07:09 UTC, ohadlevy commented on app/models/report_template.rb
> +    "#{name}-#{Date.today}.#{type}"
shouldnt this change the content html header? e.g. something like 'application/csv' or similar?

2019-01-21 08:16 UTC, ares commented
Note that if we use report_render macro, a format can be specified there, e.g. `report_render :yaml`. It would be nice if we pass the format into the renderer so that this macro could change format accordingly. For unknown formats such as txt, it would still default to csv but for yaml, it would already switch to yaml. Would that be feasible?

2019-01-23 14:21 UTC, ares requested changes
so two points we discussed online
1) report_render macro should look at the format and default to it, https://gist.github.com/ares/096c249fd7a1a74aebbf69ac39eaf00e
2) we need also API and hammer support for this new field
3) the format should support csv/yaml/txt, macro should keep defaulting to csv for unknown formats probably

2019-04-05 12:05 UTC, mmoll commented
@amitkarsale please rebase :)

2019-04-23 06:12 UTC, ares commented
The rebase didn't seem to work well. We discussed how mime-types should be implemented with a bigger team that focused on report templates recently and came to something slightly different.

We'd like to have formats defined in some constant. Each template could be assigned one or more available formats for rendering. Today we support json, yaml and csv as formats and we need to add plain text. Each format should define it's mime-type, file suffix and format constant passed to `render_report` macro. During generating, if the template has only one available format set, it will be automatically chosen, respective mime-type and suffix is used. If it has more, user can chose which format to use for the current rendering.

@amitkarsale would you be interested in updating the PR to this logic? We believe this would address all related RFEs.

2019-05-02 13:33 UTC, amitkarsale commented
@ares , sure would implement the logic. Can we close the PR would implement in a new PR.

2019-05-07 11:44 UTC, ares commented
sure, closing for now, thanks

2019-05-07 11:44 UTC, closed without merging