Fixes #25896 - syslog patter default is short
theforeman/foreman pull request #6428
Opened 2019-01-22 14:59 UTC by lzap

Just improving user experience, when logging to journald/syslog not
time/request id is needed as user can display or configure those fields
as needed. This was actually the purpose of `sys_pattern` configuration
option.

2019-01-22 15:02 UTC, ekohl commented
Nit: typo in the commit message

2019-01-24 04:03 UTC, chris1984 requested changes
Other than @ekohl comment about the typo looks good.

2019-01-28 14:13 UTC, lzap commented
Damn, rebased.

2019-01-28 14:59 UTC, chris1984 approved these changes
LGTM

2019-01-28 14:59 UTC, chris1984 commented
[test katello]

2019-01-29 07:28 UTC, lzap commented
All is good.

2019-01-29 14:32 UTC, chris1984 commented
[test foreman]

2019-01-29 18:27 UTC, tbrisker approved these changes
Thanks @lzap !

2019-01-29 18:27 UTC, merged