Fixes #25384 - expire count cache on switching taxonomy
theforeman/foreman pull request #6459
Opened 2019-02-04 08:08 UTC by amitkarsale

Expire hostgroup count cache on switching of taxonomies.

2019-02-05 14:06 UTC, tbrisker requested changes
The same problem will be present in any other pages that use the HostCounter service, please expire all of the caches in a generalized way

2019-02-27 09:40 UTC, amitkarsale commented
is it good to be merged?

2019-02-27 10:02 UTC, tbrisker commented
No, this is still only expiring only the hostgroup cache, there are multiple pages using the counter service that need to be all expired.

2019-04-04 14:02 UTC, amitkarsale commented
@tbrisker can you tell me what is failing here?

2019-04-05 12:05 UTC, mmoll commented
@amitkarsale please rebase :)

2019-08-21 08:53 UTC, tbrisker commented
ping @amitkarsale do you still intend to work on this? If so, this still requires changes as it will only expire the current controller's host count cache and not all controllers that have such cache.

2019-08-27 10:14 UTC, tbrisker commented
Closing for now due to inactivity, feel free to reopen if you wish to resume this work.

2019-08-27 10:14 UTC, closed without merging