Fixes #26055 - select bind on change just once
theforeman/foreman pull request #6483
Opened 2019-02-15 01:16 UTC by ezr-ondrej

Select is binding the change event handler multiple times.
It needs to be detached before component update to ensure single evocation.

2019-02-15 14:01 UTC, ares commented
@amirfefer or @sharvit could you please take a look?

2019-02-17 12:59 UTC, amirfefer requested changes
Thanks @ezr-ondrej  :+1: 
just one minor issue

2019-02-17 12:59 UTC, amirfefer commented on webpack/assets/javascripts/react_app/components/common/forms/Select.js
> +    $(this.select).off('change', onChange);
`componentWillUpdate` is deprecated, you can use `componentDidUpdate` instead

2019-02-17 17:05 UTC, ezr-ondrej commented
@amirfefer in that case, like this? :)

2019-02-26 11:55 UTC, ohadlevy commented
@amirfefer @sharvit ping?

2019-02-26 14:44 UTC, amirfefer approved these changes
Thanks @ezr-ondrej :+1: 
Works great

2019-02-26 14:46 UTC, ohadlevy approved these changes

2019-02-26 14:46 UTC, merged

2019-02-26 14:47 UTC, ohadlevy commented
thanks @ezr-ondrej