Fixes #26087 - Bruteforce attack cause reloading users sessions
theforeman/foreman pull request #6519
Opened 2019-02-28 07:55 UTC by dhlavac

Original session remains functional and attacking IP is blocked now.

2019-02-28 10:19 UTC, ares requested changes
It does not seem to solve this issue entirely. When I'm in that active session, when notification polling starts, it replies with

```
2019-02-28T11:17:15 [I|app|4c4afbee] Started GET "/notification_recipients" for 127.0.0.1 at 2019-02-28 11:17:15 +0100
2019-02-28T11:17:15 [I|app|4c4afbee] Processing by NotificationRecipientsController#index as JSON
2019-02-28T11:17:15 [W|app|4c4afbee] Brute-force attempt blocked from IP: 127.0.0.1
2019-02-28T11:17:15 [I|app|4c4afbee]   Rendering api/v2/errors/bruteforce_attempt.json.rabl within api/v2/layouts/error_layout
2019-02-28T11:17:15 [I|app|4c4afbee]   Rendered api/v2/errors/bruteforce_attempt.json.rabl within api/v2/layouts/error_layout (1.7ms)
2019-02-28T11:17:15 [I|app|4c4afbee] Filter chain halted as :authorize rendered or redirected
2019-02-28T11:17:15 [I|app|4c4afbee] Completed 401 Unauthorized in 10ms (Views: 8.6ms | ActiveRecord: 0.0ms)
```

which then triggers 
```
2019-02-28T11:17:15 [I|app|74fb8045] Started GET "/users/login" for ::1 at 2019-02-28 11:17:15 +0100
2019-02-28T11:17:15 [I|app|74fb8045] Processing by UsersController#login as HTML
2019-02-28T11:17:15 [D|sql|74fb8045]   User Exists (0.4ms)  SELECT  1 AS one FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 3], ["LIMIT", 1]]
2019-02-28T11:17:15 [D|sql|74fb8045]   ↳ app/controllers/users_controller.rb:181
2019-02-28T11:17:15 [I|app|74fb8045] Redirected to https://foreman.example.tst/domains
2019-02-28T11:17:15 [I|app|74fb8045] Filter chain halted as :verify_active_session rendered or redirected
2019-02-28T11:17:15 [I|app|74fb8045] Completed 302 Found in 6ms (ActiveRecord: 0.4ms)
```

and the whole page reloads with message `You have already logged in`

Also for changes like this, some tests would be good

2019-02-28 11:45 UTC, ares commented
I've looked at this a bit more and I think we should rather update the logic in brute force detection. If user currently logged in, we shouldn't consider the request as bruteforced. See https://github.com/theforeman/foreman/blob/develop/app/controllers/concerns/foreman/controller/bruteforce_protection.rb for the logic. Note that we can't use User.current there because authentication hasn't happened yet. But we could check session.

2019-03-07 09:14 UTC, ares requested changes
just one nit, otherwise makes sense

2019-03-07 09:14 UTC, ares commented on app/controllers/concerns/foreman/controller/bruteforce_protection.rb
>      limit > 0 && get_login_failures >= limit
perhaps moving the condition here would be slightly cleaner as it's the single definition of what is considered bruteforce attempt

`limit > 0 && get_login_failures >= limit && session[:user].nil?`

2019-03-15 16:23 UTC, dhlavac commented
@ares nit resolved :) About tests I am opened to any ideas because I didn't find way how to reproduce problem in test environment

2019-03-25 13:47 UTC, ares commented
[test foreman]

2019-03-25 13:47 UTC, ares submitted a review, later dismissed

2019-03-26 15:05 UTC, ares approved these changes
Thanks @dhlavac, merging!

2019-03-26 15:05 UTC, merged