Fixes #26215 - Autocomplete console warnings
theforeman/foreman pull request #6536
Opened 2019-03-04 15:08 UTC by Laviro

After `Patternfly-React` has updated `React-Bootstrap-Typeahead` version,
some console warnings were visible:

![selection_026](https://user-images.githubusercontent.com/26363699/53741913-1b95c380-3ea0-11e9-9540-bdf62595c227.png)

2019-03-04 15:23 UTC, Laviro commented
opened an issue to `React-Bootstrap-Typeahead`: [issue](https://github.com/ericgio/react-bootstrap-typeahead/issues/428) about:
- bodyContainer warning.
- Quieting the ID deprecation warning.

2019-03-04 22:19 UTC, Laviro commented
Will be fixed by https://github.com/patternfly/patternfly-react/pull/1493

2019-03-05 08:56 UTC, Laviro commented on package.json
> +    "react-bootstrap-typeahead": "3.4.1",
Will be removed when patternfly upgrades

2019-03-05 08:57 UTC, Laviro commented on webpack/assets/javascripts/react_app/components/AutoComplete/components/AutoCompleteMenu.js
> +    return null;
`emptyLabel` prop implementation has changed

2019-03-05 08:58 UTC, Laviro commented
@glekner could you check if this doesn't break your code? an ID is required now in `react-bootstrap-typeahead`

2019-03-05 09:13 UTC, Laviro commented
@theforeman/ui-ux could you have a look ?

2019-03-06 08:45 UTC, Laviro commented on app/helpers/search_bar_helper.rb
> +        id: search_bar_id
ID is required now

2019-03-06 08:48 UTC, Laviro commented on webpack/assets/javascripts/react_app/components/AutoComplete/index.js
> -  unableHTMLAutocomplete() {
got fixed on `react-bootstrap-typeahead` new version

2019-03-06 09:01 UTC, Laviro commented
Patternfly have merged the PR to upgrade `react-bootstrap-typeahead`, 
this PR is ready for review :)

2019-03-06 16:15 UTC, amirfefer requested changes
Thanks @Laviro :+1: 
Some minor issues

Have you tested it with #6500 and #6501 ?

2019-03-06 16:15 UTC, amirfefer commented on app/helpers/search_bar_helper.rb
> +    search_bar_id: 'tfm_search_bar'
using the term `tfm` here is a bit confusing with the object `tfm`

2019-03-06 16:15 UTC, amirfefer commented on app/helpers/search_bar_helper.rb
> +    search_bar_id: 'tfm_search_bar'
ditto

2019-03-15 15:44 UTC, ares commented
needs rebase now too

2019-03-18 10:22 UTC, ares commented
Test failures unrelated, @amirfefer is this ready from your point of view? Is there a packaging change needed because of patternfly-react bump?

2019-03-18 10:42 UTC, Laviro commented
@ares I am fine working with patternfly-react v2.29.17 if it is easier to merge.

2019-03-18 13:19 UTC, sharvit submitted a review, later dismissed
Thanks @Laviro LGTM

2019-03-18 13:22 UTC, ares commented
I defer to @ekohl re packaging bump, if he confirms I'm happy to merge.

2019-03-18 15:29 UTC, amirfefer submitted a review, later dismissed
Thanks @Laviro  LGTM :+1: 
test failure looks irrelevant

2019-03-19 14:21 UTC, Ron-Lavi commented
@ekohl would it be easier to stay with `patternfly-react` `v2.29.17` which works just fine for this PR,
instead of the packaging bump to `v2.30.6` ?

2019-03-19 17:27 UTC, ekohl submitted a review, later dismissed

2019-03-19 17:27 UTC, ekohl commented on package.json
> +    "patternfly-react": "^2.30.6",
https://github.com/theforeman/foreman-packaging/pull/3540 now updates to the latest (2.31.0) because that's allowed by `^2.30.6`

2019-03-19 17:51 UTC, ekohl commented
> @ekohl would it be easier to stay with `patternfly-react` `v2.29.17` which works just fine for this PR

We had 2.29.0 packaged. The difference between 2.29.17 and bumping to 2.31.0 as I did now is negligible. The scripts I use are aimed at using the latest version so if you had used `^2.29.17` I'd probably still have used `2.31.0`.

2019-03-20 08:09 UTC, ares commented
I suppose that's ack from packaging :-) if no one objects, I'll merge later today.

2019-03-20 09:13 UTC, Laviro commented
Awesome @ares @ekohl, thanks guys :)

2019-03-20 09:30 UTC, Laviro commented
Rebased, and everything is green :+1:

2019-03-20 14:36 UTC, ares approved these changes
Thanks @Laviro, @amirfefer and @ekohl, merging!

2019-03-20 15:55 UTC, merged