Fixes #26041 - Only validate MAC-address if subnet is set
theforeman/foreman pull request #6540
Opened 2019-03-05 17:16 UTC by UXabre

It should be possible to simply create a managed interface without a MAC address; this is especially useful when having tunnel adapters etc. for which no MAC address exists but a DNS-record is needed.

2019-03-12 10:19 UTC, timogoebel requested changes
Thanks, looks good and makes sense. Just one small nit with the tests.

2019-03-12 10:19 UTC, timogoebel commented on test/models/nics/base_test.rb
> +      refute nic.valid?, "Seems to be, unexpectedly valid... #{nic.errors.messages}"
you can use `refute_valid nic` here. That basically does the same.

2019-03-12 10:19 UTC, timogoebel commented on test/models/nics/base_test.rb
> +      assert nic.valid?, "Seems to be invalid... #{nic.errors.messages}"
`assert_valid nic`

2019-03-12 10:19 UTC, timogoebel commented on test/models/nics/base_test.rb
> +      assert nic.valid?, "Seems to be invalid... #{nic.errors.messages}"
`assert_valid nic`

2019-03-12 10:19 UTC, timogoebel commented on test/models/nics/base_test.rb
> +      refute nic.valid?, "Seems to be unexpectedly valid... #{nic.errors.messages}"
`refute_valid nic`

2019-03-12 10:19 UTC, timogoebel commented on test/models/nics/base_test.rb
> +      refute nic.valid?, "Seems to be unexpectedly valid... #{nic.errors.messages}"
`refute_valid nic`

2019-03-12 10:19 UTC, timogoebel commented on test/models/nics/base_test.rb
> +      assert nic.valid?, "Seems to be invalid... #{nic.errors.messages}"
`assert_valid nic`

2019-03-12 10:19 UTC, timogoebel commented on test/models/nics/base_test.rb
> +      assert nic.valid?, "Seems to be invalid... #{nic.errors.messages}"
`assert_valid nic`

2019-03-12 10:19 UTC, timogoebel commented on test/models/nics/base_test.rb
> +      assert nic.valid?, "Seems to be invalid... #{nic.errors.messages}"
`assert_valid nic`

2019-03-12 10:53 UTC, UXabre commented
I've made the changes as requested 🙂

2019-03-12 12:36 UTC, timogoebel approved these changes

2019-03-14 14:13 UTC, merged

2019-03-14 14:13 UTC, timogoebel commented
Thanks, @UXabre.