Fixes #26287 - Add a loader of global js files for plugins
theforeman/foreman pull request #6554
Opened 2019-03-10 14:05 UTC by amirfefer

For extendable react components and a global client routing, foreman needs a mechanism for loading  plugin's global js files.

For example, `Katello` would like to add some react content into `host show page` via Slot&Fill
katello just register his global fills file with
```rb
    Foreman::Plugin.register :katello do
     # content...
      register_global_file 'fills'
    end
```

and by that, foreman will load `katello:fills.js` globally.

2019-03-10 16:03 UTC, timogoebel commented on test/helpers/reactjs_helper_test.rb
> +      register_global_file 'some_global_file'
Can we name this `register_global_js_file` so it's more clear what this is used for?

2019-03-10 16:05 UTC, timogoebel commented
Just curious, do we have a corresponding katello PR to see how this is used in real life?

2019-03-10 16:11 UTC, amirfefer commented
@timogoebel not yet, this is needed for #6366 first

2019-03-12 11:31 UTC, amirfefer commented
@sharvit would you mind to review this?

2019-03-12 11:58 UTC, sharvit requested changes
Thanks @amirfefer, I agree this is needed and I like the implementation.

One thing that is missing for me is documentation for how it should be used.

2019-03-12 11:58 UTC, sharvit commented on app/registries/foreman/plugin/global_js.rb
> +        @global_js_files = file
Shouldn't it add to the array instead of replacing it?

2019-03-12 12:45 UTC, xprazak2 commented on app/helpers/reactjs_helper.rb
> +      if plugin.is_a?(Hash)
nit: maybe split this somehow?

2019-03-12 12:48 UTC, xprazak2 commented
Works as expected, registered file is added to the page. Nice work!
We will likely need the same for stylesheets...

2019-03-18 15:25 UTC, amirfefer commented
thanks @sharvit  and @xprazak2 , would you mind re-review?

2019-03-19 13:53 UTC, xprazak2 commented on test/helpers/reactjs_helper_test.rb
> +    res = webpacked_plugins_with_global_js()
Nit: you can omit the parens

@Hound, are you asleep?

2019-03-19 13:54 UTC, xprazak2 commented
@amirfefer, just one small nitpick, otherwise works as expected.

2019-03-19 15:00 UTC, amirfefer commented
done :)

2019-03-19 15:14 UTC, sharvit approved these changes
Thanks @amirfefer :+1:

2019-03-20 07:36 UTC, xprazak2 approved these changes

2019-03-20 08:59 UTC, amirfefer commented
@ares can we merge this?

2019-03-20 16:30 UTC, merged

2019-03-20 16:30 UTC, xprazak2 commented
Thanks!