Fixes #26475 - Password Strength snapshot changed
theforeman/foreman pull request #6623
Opened 2019-03-28 09:46 UTC by Laviro

`namespaceClassName="ReactPasswordStrength"` was added to the snapshot caused tests to fail.

2019-03-28 09:50 UTC, amirfefer requested changes
probably caused due to a version update ,would you mind to check if there is no any regression?

2019-03-28 09:54 UTC, Laviro commented
@amirfefer I saw no regression while using and testing it

![Selection_039](https://user-images.githubusercontent.com/26363699/55147901-ed7a6b00-514f-11e9-942f-bd8df6c870c8.png)

react-password-strength updated to `v2.4` a day ago:

![Selection_040](https://user-images.githubusercontent.com/26363699/55147962-03882b80-5150-11e9-85fa-fcc3b7ff8d7f.png)

Seem that this PR caused the snapshot change:

![Selection_041](https://user-images.githubusercontent.com/26363699/55148045-2ca8bc00-5150-11e9-99ad-9826667e91f6.png)

2019-03-28 09:56 UTC, amirfefer submitted a review, later dismissed
Thanks @Laviro  :+1:

2019-03-28 12:48 UTC, tbrisker reviewed
you should update `package.json` to match the correct version or the test would fail if people use the older version.

2019-03-28 12:59 UTC, Laviro commented
Thanks @tbrisker, updated

2019-03-31 07:36 UTC, timogoebel approved these changes

2019-03-31 07:38 UTC, timogoebel commented
@ekohl, @evgeni: Please ack, currently js tests in develop are failing without this.

2019-03-31 07:45 UTC, evgeni commented
I only see 2.3.1 in packaging and no PR to fix that? https://github.com/theforeman/foreman-packaging/tree/rpm/develop/packages/foreman/nodejs-react-password-strength

2019-03-31 07:59 UTC, sharvit approved these changes
Thanks @Laviro LGTM :+1: 
Can you please create a packaging PR?

2019-03-31 08:44 UTC, ohadlevy commented
packaging PR at https://github.com/theforeman/foreman-packaging/pull/3590

2019-03-31 08:54 UTC, sharvit approved these changes
We can merge it from my side :+1:

2019-03-31 10:23 UTC, ekohl approved these changes

2019-03-31 10:23 UTC, merged