Refs #26020 - improve report template API docs
theforeman/foreman pull request #6628
Opened 2019-03-30 14:33 UTC by ezr-ondrej

Improvement of API documentation for report templates commands.

Prerequisites for testing:
* Ideally hammer, as it is the main consumer for those docs.

Tests needed (anticipated impacts):
* Hammer cli
* /apidocs page

2019-03-30 14:39 UTC, timogoebel commented on app/controllers/api/v2/report_templates_controller.rb
> +        In case the report is not done generating, it will return empty response with http status 204 - NoContent.
Nit: `... an empty response ...`

2019-04-02 10:28 UTC, ares requested changes
one nit, then good to go in

2019-04-02 10:28 UTC, ares commented on app/controllers/api/v2/report_templates_controller.rb
> +        In case the report is not done generating, it will return an empty response with http status 204 - NoContent.
I'd change `In case the report is not done generating,` to `In case the report hasn't been generated yet,`

2019-04-05 11:09 UTC, ares approved these changes

2019-04-05 11:10 UTC, ares commented
Thanks @ezr-ondrej, merging!

2019-04-05 11:10 UTC, merged