[WIP] Fixes #26473,#4179,#22749,#26496 - fixes for broken GCE
theforeman/foreman pull request #6634
Opened 2019-04-01 09:19 UTC by kgaikwad

2019-04-03 19:09 UTC, ShimShtein requested changes
A couple of semantic changes, not too serious.

I am a bit concerned that args transformation methods like `new_vm` do not have any tests. It would be really awesome if we could make sure we are passing expected args to Fog (and GCE).

2019-04-03 19:09 UTC, ShimShtein commented on app/models/compute_resources/foreman/model/gce.rb
> +      if args[:associate_external_ip]&.is_a?(String)
Why not using `to_bool` here?
It would make the code more readable.

2019-04-03 19:09 UTC, ShimShtein commented on app/models/compute_resources/foreman/model/gce.rb
> +        args.except!(:associate_external_ip)
If you don't want `associate_external_ip` in `args`, you can use `delete` earlier:

``` ruby
if to_bool(args.delete(:associate_external_ip))
  args[:network_interfaces] = construct_network_interfaces(args[:network_interfaces])
end
```

Just watch for the case where you don't have `associate_external_ip` in `args`

2019-04-03 19:09 UTC, ShimShtein commented on app/models/compute_resources/foreman/model/gce.rb
> +      if args[:user_data].present?
You can use `delete` here:

``` ruby
user_data = args.delete(:user_data)
# ...
```

2019-04-03 19:09 UTC, ShimShtein commented on app/models/compute_resources/foreman/model/gce.rb
> +      vm = client.servers.create options.to_hash.deep_symbolize_keys.merge(server_optns.symbolize_keys)
Why do you need to `slice` options hash and then symbolize only part of keys and then merge the hash again?

2019-04-03 19:09 UTC, ShimShtein commented on app/models/concerns/fog_extensions/google/server.rb
> +        disks_arr.inject('') do |filter_string, d|
Maybe something like this:
``` ruby
disks_arr.map { |d| "(name = \"#{d[:source][/([^\/]+)$/]}\")" }.join(' OR ')
```

2019-04-04 07:54 UTC, kgaikwad commented on app/models/compute_resources/foreman/model/gce.rb
> +      vm = client.servers.create options.to_hash.deep_symbolize_keys.merge(server_optns.symbolize_keys)
@ShimShtein,

Before actual compute API request from `fog-google`, they processed `:network_inferfaces & :metadata` and then creates objects using `::Google::Apis::ComputeV1`. 
For which, I need all nested keys in symbolize format for these two.
 
For reference, please check below links - 
1. [Metadata key](https://github.com/fog/fog-google/blob/master/lib/fog/compute/google/models/server.rb#L502)
2. [Network interfaces](https://github.com/fog/fog-google/blob/master/lib/fog/compute/google/requests/insert_server.rb#L74)

2019-04-04 10:47 UTC, kgaikwad commented on app/models/compute_resources/foreman/model/gce.rb
> +      vm = client.servers.create options.to_hash.deep_symbolize_keys.merge(server_optns.symbolize_keys)
Note - I tried using `HashWithIndifferentAccess` but to initialize compute [classes](https://github.com/googleapis/google-api-ruby-client/blob/master/generated/google/apis/compute_v1/classes.rb),  most of initialize methods defined as `initialize(**args)` which results into error - `wrong number of arguments (given 1, expected 0)`. It expects keyword arguments only.

2019-04-04 12:15 UTC, ShimShtein submitted a review, later dismissed

2019-04-04 12:15 UTC, ShimShtein commented
ACK from me, @jyejare, if you could test it, it would be great.

2019-04-05 11:21 UTC, kgaikwad commented
@ShimShtein, 
I have dismissed your approval on PR as I done rebase. No any additional changes to PR.

2019-04-05 11:28 UTC, jyejare commented
Quick Testing has been performed with this PR, though I tested some of the commits separately.

Here are the findings:
-----------------------------
1. The GCE CR is being created
2. The zones are being loaded to GCE CR
3. Test Connection to GCE is successful.
4.  All the images including the depreciated images are loaded. (I can file an RFE/bug to include/exclude the depreciated images if its valid request)
5. Image with 'user_data' enabled is created
6. Image without 'user_data' (finish template) is created.
7. Username field has appeared for images and image can be saved with that username.
8. The user data template is resolved in VM(Sat Web-UI) when the user_data image is selected.
9. The external IP has been assigned to provisioned VM. (Both user-data and finish template)
10. The modified boot-disk(default disk) size is also updated in provisioned VM as requested.
11. Additional Disk has been attached to the provisioned VM if requested.
12. The user mentioned in 'User-Data' image is created in provisioned VM
13. The Finish template is resolved in VM(Sat Web-UI) when a non user_data image is selected.
14. Machine Types are loaded from GCE to be selected under the VM tab.
15. The 'Installed' status is displayed for finish and user data templates on provisioned VM.
16. Provisioned VM can be deleted from Foreman easily.
17. VMs provisioned and existing VMs are listed in GCE CR.
18. GCE VM can be Stopped and Start again successfully.

Some Notes:
--------------------
1. The testing has been performed with admin roles key, We are facing some issues for user creation and ssh while normal user role key. Will dig dipper into it later.
2. The testing has been done by deploying Foreman on GCE so that provisioned VM can send the call back to Foreman as it's in the same network.
3. Some scenarios that don't need a call back has also been tested from Local Development environment.

Raised/Yet-To-Raise Non-Blocker Issue:
----------------------------------------------------
1. https://projects.theforeman.org/issues/26442 : The deleted additinal disk from Foreman is being created in VM in GCE (Medium issue)
2. The double append of domain to VM - YET TO RAISE - need more detail as its reproducible only with user role key and not with admin role key (Medium issue)

Things Yet To Test (Secondary Things, not directly aligned with GCE):
------------------------------------------------------------------------------------------
1. Content access from GCE provisioned VM (Katello)
2. Ansible and Puppet integration with GCE VM
3. SSH Keys deployment of the user who provisioned the VM
4. Remote Execution on GCE VM
 .... and there could be more.

2019-04-08 07:19 UTC, xprazak2 commented
Looks ok code-wise.

2019-04-08 09:28 UTC, tbrisker approved these changes
Considering this is a great improvement over the current broken status and the amount of testing, I'm fine with merging this even if not all edge cases are completely handled. 
Thanks @kgaikwad, @ShimShtein, @jyejare and @xprazak2 !

2019-04-08 09:28 UTC, merged

2019-04-08 09:29 UTC, tbrisker commented
@kgaikwad can you please add this to the headline features for 1.22?