fixes #26647 - removes hidden_values from asset compile list
theforeman/foreman pull request #6695
Opened 2019-04-18 11:21 UTC by ohadlevy

its not required to compile it, as its already included in application.js

2019-04-18 12:06 UTC, tbrisker requested changes
while you're there, `lookup_keys` is also included in `application.js`

2019-04-18 12:30 UTC, ohadlevy commented
> while you're there, `lookup_keys` is also included in `application.js`

done.

2019-04-18 14:45 UTC, ohadlevy commented
test failures do not seems related.

2019-04-21 07:46 UTC, tbrisker approved these changes
Thanks @ohadlevy !

2019-04-21 07:46 UTC, merged