Fixes #26664 - adds OpenStack project domain
theforeman/foreman pull request #6706
Opened 2019-04-24 11:05 UTC by lzap

When creating new OpenStack CR against OSP v13 a permission denied (401)
error is returned. I have narrowed this down to the fact to missing flag
openstack_domain_id. When it's provided, the CR authenticates fine,
since it is mentioned as mandatory for V3 in
https://github.com/fog/fog-openstack this patch is going to add it.

The patch changes tenant not to be loaded from OpenStack because it's
chicken and egg problem - tenant presence makes for to think API V2 must
be used, however against V3 only openstacks it is no longer possible to
retrieve list of tenants anymore. It's now a free-form text field.

Two new fields (text) are added - project domain name and id. For
OpenStack I was testing with only id was required, however I am adding
also name and when set it is passed into fog.

I tested UI, API and hammer, a PR adding support to hammer is on the
way. I am going to propose this to 1.22 because essentially V3 OpenStack
CR is broken, however I think it was broken even before Fog upgrade.

2019-05-14 11:19 UTC, ares commented
@san7ket could you please test the patch? I can do the code review

2019-05-14 15:28 UTC, san7ket commented
@ares Yes sure , just one question, will upgrade be affected by this?

2019-05-14 15:47 UTC, ares commented
Not sure what you mean. People with openstack upgrading 10 -> 13 or people having working openstack in Foreman upgrading Foreman itself. It should affect users adding new compute resource, with this patch, they will need to manually enter tenant name, regardless of openstack version. For people having existing CR, the select field changes to text field but they don't have to do anything, the tenant is already saved in our db.

2019-05-14 15:55 UTC, san7ket commented
I meant the later, got my answer

2019-05-15 07:28 UTC, san7ket commented
I am testing this as a patch on 
foreman-1.22.0-0.5.RC1.el7sat.noarch

I am facing issues with selinux :( on UI error is 
```
Unable to save
Permission denied - connect(2) for 10.0.0.0:35357 (Errno::EACCES)
```
In audit.log
```
type=AVC msg=audit(1557902559.175:13013): avc:  denied  { name_connect } for  pid=9758 comm="diagnostic_con*" dest=35357 scontext=system_u:system_r:passenger_t:s0 tcontext=system_u:object_r:keystone_port_t:s0 tclass=tcp_socket permissive=0
type=SYSCALL msg=audit(1557902559.175:13013): arch=c000003e syscall=42 success=no exit=-13 a0=d a1=7f48a860df00 a2=10 a3=2 items=0 ppid=9591 pid=9758 auid=4294967295 uid=992 gid=990 euid=992 suid=992 fsuid=992 egid=990 sgid=990 fsgid=990 tty=(none) ses=4294967295 comm="diagnostic_con*" exe="/opt/rh/rh-ruby25/root/usr/bin/ruby" subj=system_u:system_r:passenger_t:s0 key=(null)
type=PROCTITLE msg=audit(1557902559.175:13013): proctitle=50617373656E676572205261636B4170703A202F7573722F73686172652F666F72656D616E
type=AVC msg=audit(1557902559.192:13014): avc:  denied  { name_connect } for  pid=9758 comm="diagnostic_con*" dest=35357 scontext=system_u:system_r:passenger_t:s0 tcontext=system_u:object_r:keystone_port_t:s0 tclass=tcp_socket permissive=0
type=SYSCALL msg=audit(1557902559.192:13014): arch=c000003e syscall=42 success=no exit=-13 a0=d a1=7f48a866f958 a2=10 a3=2 items=0 ppid=9591 pid=9758 auid=4294967295 uid=992 gid=990 euid=992 suid=992 fsuid=992 egid=990 sgid=990 fsgid=990 tty=(none) ses=4294967295 comm="diagnostic_con*" exe="/opt/rh/rh-ruby25/root/usr/bin/ruby" subj=system_u:system_r:passenger_t:s0 key=(null)
type=PROCTITLE msg=audit(1557902559.192:13014): proctitle=50617373656E676572205261636B4170703A202F7573722F73686172652F666F72656D616E
```

I put the box in permissive, and got it added. Is there a additional step here now ?

2019-05-15 07:32 UTC, lzap commented
Hey, if you run OpenStack on a different port than the standard one, you need to allow it in the policy. The SELinux boolean flag passenger_can_connect_openstack only allows standard ports.

2019-05-15 07:35 UTC, lzap commented
FYI this is how you add new port:

    semanage port -a -t foreman_osapi_compute_port_t -p tcp 35357

Or you can just allow all ports:

    setsebool passenger_can_connect_all on

2019-05-15 08:46 UTC, san7ket commented
Addition of CR - PASS
Listing VM's - PASS
Image Addition - PASS
Creation of VM - PASS
Provisioning VM - Issues , need more time to look into(Provisioning template not pulled and run)
Deletion VM - Issues, need more time (shows success in task, but backend VM still present)
Cloud-init - Issues, need more time (Not run clout-init log shows no tasks)

I think the later, issues are not related to this PR and first 3 tests are enough to test this PR.

2019-05-15 11:09 UTC, lzap commented
@san7ket great work, ping me on IRC if you need assistance for the other issues but we can merge this one @ares

2019-05-15 13:39 UTC, ares requested changes
Few suggestions. It would be much nicer to have selector if this is using v2 or v3 and update the form accordingly, but it's acceptable for now.

2019-05-15 13:39 UTC, ares commented on app/models/compute_resources/foreman/model/openstack.rb
> +        #:openstack_endpoint_type     => "publicURL"
should this be removed?

2019-05-15 13:39 UTC, ares commented on app/models/compute_resources/foreman/model/openstack.rb
> +        if tenant != ''
this would accept nil tenant, should it be `if tenant.present?`

2019-05-15 13:39 UTC, ares commented on app/models/compute_resources/foreman/model/openstack.rb
> +        h[:openstack_user_domain] = domain if domain != ''
if coming from API, all these values can be nil right? should we change it here and next 3 lines to `.present?`

2019-05-23 09:06 UTC, lzap commented
Rebased.

2019-06-24 13:26 UTC, lzap commented
@ares ping

2019-06-25 14:09 UTC, ares approved these changes
Thanks @lzap, merging!

2019-06-25 14:09 UTC, merged