[WIP] Fixes #25811 - replace multiple_selects by Patternfly's Dual List
theforeman/foreman pull request #6724
Opened 2019-04-30 12:21 UTC by Laviro

Replacing the old implementation of `multiple_selects` with Patternfly's Dual list,
and removing the `jquery.multi-select` dependency.

2019-05-01 03:49 UTC, Laviro commented
blocked by https://github.com/patternfly/patternfly-react/pull/1900

2019-05-02 09:21 UTC, ohadlevy commented on app/assets/javascripts/application.js
> -//= require jquery.multi-select
the actual file (app/assets/javascripts/jquery.multi-select.js) should also be removed.

2019-05-13 18:05 UTC, Laviro commented
[test foreman]

2019-05-13 18:45 UTC, mmoll commented
@Laviro you need to fix the Rubocop violation first :)

2019-05-14 09:37 UTC, ezr-ondrej commented on webpack/assets/javascripts/react_app/components/DualList/DualList.js
> +      <FormGroup id={id}>
The #6677 is merged, would it make sense to use it as a wrapper for the component?
I would love to see it usable from the rails helper.

2019-05-14 10:10 UTC, ezr-ondrej requested changes
I was thinking about generic components being connected and I believe it encourages to put data in the store by component hierarchy, rather than application domain. The store subtree would now looks like `{dualList: {host_organization_ids: ..., medium_operating_system_ids: ...}}`, what doesn't tells about the application domain too much and is not useful for rendering other parts of application.

Do you think it would make sense without connecting the component, to use inputs `name` attribute if it is standalone component in non react environment and handled the state in higher components (like forms), if needed (if react environment)?

2019-05-14 10:10 UTC, ezr-ondrej commented on webpack/assets/javascripts/react_app/components/DualList/index.js
> +const mapStateToProps = (state, { id }) => ({});
Why do we have a state in redux, if we are not using it to render the component?
I believe it resonates with my thought we do not need to connect the component, isn't it?

2019-05-15 09:43 UTC, Laviro commented on webpack/assets/javascripts/react_app/components/DualList/index.js
> +const mapStateToProps = (state, { id }) => ({});
still investigating it, but I believe the direction should be to connect it to redux,
and than other components on the page could get updated by changes of the Dual List.

2019-05-15 09:53 UTC, Laviro commented
Thanks @ezr-ondrej for your review,
the PR is still a draft though and I think connecting the component to redux
does make sense so other components could depend on the data that was selected by the DualList,

we can list all of the different Dual List reducers under the domain name, that's what you meant?

2019-05-15 17:42 UTC, ezr-ondrej commented
Well my point here is, that it is not the DualList alone who should get stored data, but rather let's say a host edit form of host with (id = 4), who is going to have dual list for selecting organizations and locations. That case should be IMHO reflected in redux something like `{hosts: { host_4: { organizations: ['RedHat'], locations: ['Brno', 'Prague'] }}`, but that is hard to achieve from DualList itself, but would be easy to achieve from the form component, whom would be passing `onChange` handler and just getting the value changes.

I know it's WIP, I was just peeking in the progress and sharing thoughts. I can't wait for seeing the component in action! :+1:

2019-05-27 07:01 UTC, ohadlevy commented on webpack/assets/javascripts/react_app/components/DualList/index.js
> +const mapStateToProps = (state, { id }) => ({});
I would say that by default (e.g. when using it as a rails form helper) it shouldnt be in redux, it should just mimic the input fields so the existing forms continue to work.

however, when using it inside a react page, then the HOC component would probably be connected with actions firing every time the user takes an action...?

2019-06-02 18:51 UTC, ohadlevy commented
whats the status of the PR? thanks.

2019-06-03 08:55 UTC, Laviro commented
Had to work on some other stuff,
I will continue to work on it and improve the feature with the community feedback.

2020-02-12 12:36 UTC, closed without merging

2020-02-13 10:55 UTC, xprazak2 commented
@stejskalleos I know you were looking into the related issue, so this might be relevant for you.