[WIP] Fixes #26676 - improve setting initialization
theforeman/foreman pull request #6737
Opened 2019-05-03 15:05 UTC by ares

reopening of https://github.com/theforeman/foreman/pull/6708 all info and reasons there, katello tests will be broken so I need to first find out why

2019-05-21 16:30 UTC, ezr-ondrej requested changes
I love optimizing the `Setting` load as it bugs me for some time.
Big :+1: for me!

I'm just bit worried about the class variable cache, wouldn't it be better to actually change the logic in ancestors to filter unchanged values prior to calling the `create`?
I know it is more work as we would need to change all ancestors, but the class variable seems to be one purposed for application start and is kept around in memory for whole application run, without being reused and if it would be used, it could cause problems as it keeps old values.

Something like this could maybe replace all ancestors `load_default_settings` methods instead?
```ruby
def self.load_default_settings
  return false unless table_exists?
  dbcache = Hash[Setting.where(:category => self.name).map { |s| [s.name, s] }]
  self.transaction do
    default_settings.compact.each do |s|
       val = s.update(:category => self.name).symbolize_keys
       dbcache.key?(val[:name]) ? create_existing(dbcache[val[:name]) : create!(s)
    end 
  end
  true
end
```

It would hit the load query in cases the Setting actually do not exists, but it is only for case the new setting was added and only once. I believe that would be ok, right?

2019-05-21 16:30 UTC, ezr-ondrej commented on app/models/setting.rb
> +      s.save if s.changed?
I believe `Rails` is doing exactly that (calling `changed?`) internally even on `update`, so I believe the deleting the default is enough here.

2019-05-21 16:30 UTC, ezr-ondrej commented on app/models/setting.rb
> +    Setting.table_exists? rescue return false
I believe the rescue is never going to be hitted now. I believe only `Setting.table_exists?` should be kept in this method, if you wouldn't want to use my suggestion above.

2019-07-13 20:12 UTC, ezr-ondrej commented
Any progress on this one?

2019-07-13 22:23 UTC, ares commented
Not in forseeable future :-(  I might get to it in late August when I'm travelling.

2019-07-14 23:30 UTC, ezr-ondrej commented
So you wouldn't get mad, if someone else would pick it up and try to push it? :stuck_out_tongue:
Purely hypotheticaly, of course: #6902

2019-07-15 08:10 UTC, ares commented
Such person would get in fact a beer from me :-) Thanks, closing this!

2019-07-15 08:10 UTC, closed without merging