Fixes #26754 - Change error when updating location fails
theforeman/foreman pull request #6742
Opened 2019-05-07 13:07 UTC by shiramax

2019-05-07 14:34 UTC, shiramax commented
@ShimShtein tests are failing because they expected for 404 error and not 422 - 
what do you think, should I change the code error to 404, or should I change all these failing tests?
thanks

2019-05-19 14:01 UTC, shiramax commented
[test katello]

2019-05-20 05:36 UTC, ShimShtein requested changes
The PR is good, found one use case that is not covered by it: `AssociationNotFound` [exception](https://github.com/theforeman/foreman/blob/7500537eefac12d1e58daa58c1efd346c6dc719c/app/controllers/api/base_controller.rb#L40) needs similar handling. Could you please change it?

2019-05-22 07:51 UTC, shiramax commented
[test foreman]

2019-05-22 07:52 UTC, shiramax commented
[test katello]

2019-05-23 11:26 UTC, shiramax commented
@ShimShtein can you please review? I believe the failing tests are unrelated

2019-05-28 08:52 UTC, shiramax commented
[test foreman]

2019-05-28 08:52 UTC, shiramax commented
[test katello]

2019-06-16 07:23 UTC, shiramax commented
[ test katello]

2019-06-16 07:23 UTC, shiramax commented
[test katello]

2019-06-16 08:37 UTC, shiramax commented
@ShimShtein can you please review again?

2019-06-24 07:25 UTC, ShimShtein commented
I have tried the following commands, but couldn't get unprocessible entity error code:

```
hammer host update --id 18 --location-id 200
hammer host update --id 18 --medium-id 200
```

2019-07-08 08:13 UTC, shiramax commented
@ShimShtein can you please review again?

2019-07-22 18:41 UTC, ShimShtein submitted a review, later dismissed
ACK from me.
@tbrisker, this PR changes responses in case of errors. Do we want to document this behaviour? Is this a good time to merge it?

2019-07-23 13:12 UTC, tbrisker requested changes
there's a couple of cases where i think the response should still be `:not_found`, see inline. let's wait with this to next week after branching, and add an upgrade warning in the manual since some users might need to adjust api scripts that check for specific responses.

2019-07-23 13:12 UTC, tbrisker commented on test/controllers/api/v2/hosts_controller_test.rb
> +      assert_response :unprocessable_entity
I think this should still be not_found?

2019-07-23 13:12 UTC, tbrisker commented on test/controllers/api/v2/config_reports_controller_test.rb
> +    assert_response :unprocessable_entity
I think this should still be not_found - the host exists, it just doesn't have reports

2019-07-23 13:12 UTC, tbrisker commented on test/controllers/api/v2/reports_controller_test.rb
> +    assert_response :unprocessable_entity
should also be not_found imho

2019-08-21 08:47 UTC, ShimShtein commented
@shiramax, ping?

2019-09-10 06:53 UTC, ShimShtein commented
ACK from me, as long as @tbrisker also approves

2019-09-10 07:04 UTC, tbrisker approved these changes
Please add an upgrade warning to the nightly manual.

2019-09-10 07:19 UTC, ShimShtein commented
@shiramax, please add a PR against [our site](https://github.com/theforeman/theforeman.org/blob/gh-pages/_includes/manuals/nightly/1.2_release_notes.md#upgrade-warnings) and reference it here. Then I will be comfortable merging this one.

2019-09-10 08:30 UTC, shiramax commented
@tbrisker , @ShimShtein 
thanks !
done: https://github.com/theforeman/theforeman.org/pull/1461

2019-09-10 11:20 UTC, merged

2019-09-10 11:20 UTC, tbrisker commented
Thanks @shiramax and @ShimShtein !