[WIP] Fixes #26010 - boot_order by orderable select
theforeman/foreman pull request #6768
Opened 2019-05-16 12:17 UTC by ezr-ondrej

Revival of #4400, with draggable multiselect.
![bootorder](https://user-images.githubusercontent.com/2884324/57852983-e33a2c00-77e4-11e9-8152-b2fc224c3290.gif)
Blocked by #6762 - the actual draggable multi select, which now needs to be reimplemented to bootstrap version.

Prerequisites  for testing:
* VMware cluster

Tests needed (anticipated impacts):
* Vmware host provisioning (mainly network based)

2019-11-20 16:05 UTC, ezr-ondrej commented
And we are up. I needed to add a small hack though :disappointed:

2019-11-20 20:12 UTC, ezr-ondrej commented
[test foreman][test katello]

2020-01-10 14:39 UTC, ares commented
This seems green and pending the review, could we prioritize the review here pls? or should we reassign?

2020-01-14 15:22 UTC, amirfefer requested changes
Thanks @ezr-ondrej :+1:

2020-01-14 15:22 UTC, amirfefer commented on webpack/assets/javascripts/react_app/components/common/forms/OrderableSelect/OrderableSelect.js
> +  const cls = props.className || '';
className is already `''` by default via `propType`

2020-01-14 15:22 UTC, amirfefer commented on webpack/assets/javascripts/react_app/components/common/forms/OrderableSelect/OrderableSelect.js
> +    .join(' ');
how about something more verbose? override props directly is an uncomon practice
```js
const classesWithoutFormControl = className && className
   .split(/\s+/)
   .filter(el => el !== 'form-control')
   .join(' ');
return (
 <TypeAheadSelect
   {...props}
   className={classesWithoutFormControl}
   {...}
 />

2020-01-14 15:45 UTC, ezr-ondrej commented on webpack/assets/javascripts/react_app/components/common/forms/OrderableSelect/OrderableSelect.js
> +    .join(' ');
yeah, looks much better, thanks :heart:

2020-01-14 16:18 UTC, ezr-ondrej commented
[test katello]

2020-01-15 11:33 UTC, amirfefer approved these changes
Works well :+1: 
Thanks @ezr-ondrej !

2020-01-15 11:33 UTC, merged

2020-01-15 12:42 UTC, ares commented
Thanks @ezr-ondrej and @amirfefer, this will make a lot of people happy! Setting also demo worthy with the hope, we'll see it on the next community demo :-)

2020-01-16 02:37 UTC, ezr-ondrej commented
> Thanks @ezr-ondrej and @amirfefer, this will make a lot of people happy! Setting also demo worthy with the hope, we'll see it on the next community demo :-)

I'm already on the agenda :upside_down_face: