Fixes #26812,#26814 - display correct vm_details in notifications
theforeman/foreman pull request #6780
Opened 2019-05-21 11:11 UTC by kgaikwad

Note that - state method is renamed to `status` in fog-google.

2019-06-10 12:55 UTC, tbrisker requested changes
Small comment inline, otherwise lgtm

2019-06-10 12:55 UTC, tbrisker commented on app/views/compute_resources_vms/show/_gce.html.erb
> +        <td><%= Time.parse(@vm.creation_timestamp).utc %></td>
Should this use `date_time_relative_value` helper for consistency with other time fields?

2019-06-10 23:52 UTC, ezr-ondrej submitted a review, later dismissed

2019-06-11 00:02 UTC, ezr-ondrej commented
LGTM :+1:

2019-06-11 16:20 UTC, kgaikwad commented
Thank you @tbrisker and @ezr-ondrej. I have updated PR with suggested changes.

2019-06-12 07:23 UTC, tbrisker approved these changes
Thanks @kgaikwad !

2019-06-12 07:24 UTC, merged

2019-06-12 07:26 UTC, tbrisker commented
1.22 - ec5d2f1eb a74dc7b17