Fixes #26869 - Add tooltip for IPv4 Subnet on NIC base form
theforeman/foreman pull request #6796
Opened 2019-05-24 16:26 UTC by wbclark

Fixes #26869 - Add tooltip for IPv4 Subnet on NIC base form

Adding a tooltip for IPv4 Subnet on NIC base form that will clarify that IPv4 Subnet with TFTP Capsule is required for PXE provisioning.

Subnet field was made optional with: https://projects.theforeman.org/issues/15133

We should have a note that says it is not optional when using PXE

RH bugzilla was opened at: https://bugzilla.redhat.com/show_bug.cgi?id=1712015

2019-05-24 16:34 UTC, chris1984 commented
ok to test

2019-05-24 16:35 UTC, chris1984 submitted a review, later dismissed
Thanks @wbclark , Approved pending jenkins

2019-05-24 17:43 UTC, chris1984 commented
@tbrisker can this get a merge please?

2019-05-24 19:07 UTC, tbrisker requested changes
Welcome to the Foreman repo @wbclark ! 
Please see my inline comment.

2019-05-24 19:07 UTC, tbrisker commented on app/views/nic/_base_form.html.erb
> +                :label_help => _("IPv4 Subnet with TFTP Capsule is required for PXE based provisioning.").html_safe,
This doesn't need to be marked as `html_safe` as it doesn't contain any HTML. Additionally, the correct term is smart proxy, not capsule.
```suggestion
                :label_help => _("IPv4 subnet with associated TFTP smart proxy is required for PXE based provisioning."),
```

2019-05-24 22:09 UTC, wbclark commented
@tbrisker, thank you for the warm welcome! I've made the requested changes. Have a great weekend

2019-05-26 06:09 UTC, tbrisker approved these changes
Thanks @wbclark and congrats on your first PR merge!

2019-05-26 06:09 UTC, merged