Fixes #27049 - Add onPopState HOC
theforeman/foreman pull request #6842
Opened 2019-06-13 14:01 UTC by glekner

New pages that are wrapped with `withRouter` can use this HOC to trigger a callback when the search query changes.

Also hijacking this PR to add missing `ReactApp` selectors

2019-06-17 17:07 UTC, glekner commented
@tbrisker can you review ?

2019-06-18 11:38 UTC, tbrisker commented
Please extract the unrelated changes to a separate PR and issue.
Could you explain a bit when is this needed?

2019-06-19 10:20 UTC, glekner commented
- removed unrelated changes . @tbrisker 

This is a lifecycle hook needed for browser navigation ( going back, forward ). it will trigger a callback when the query search changed, and only if the action was `POP`.

e.g.
User pressed on back button in page 2, so now we're in page 1 and we need a function to update the data with the new params. There is no Turbolinks anymore, we handle the history state.

2019-06-20 07:46 UTC, sharvit reviewed
Thanks @glekner :+1: 

I'm wondering since there is no usage for it yet, is it possible to demo it in the storybook?

2019-06-20 09:27 UTC, glekner commented
@sharvit the HOC assumes a component is wrapped `withRouter`, not sure if we should demonstrate in Storybook. the HOC is used in #6733

2019-06-23 07:57 UTC, sharvit commented
So is it possible to just add an `md` file to the storybook that explains about HOCs and about how to use them inside foreman?

I see those HOCs as a sort of super tool for developers to write routes easily and I afraid developers will have a hard time know they exist how to use them.

2019-06-24 17:10 UTC, sharvit commented
@glekner I would love to know your opinion about the new react hooks API

https://react-redux.js.org/next/api/hooks

2019-06-25 07:58 UTC, glekner commented
@sharvit @ohadlevy @tbrisker @amirfefer @ezr-ondrej  
I played with Redux hooks, and IMHO its not worth the switch.
Using a hook happens inside the component making it bound to redux, What happens if we want to stop using Redux?
Hooks are great for React but I just don't see it in Redux.

While testing those hooks I created `withRedux` which is basically a `connect()`
using `useSelector, useDispatch`.
it does helps make `index.js` files cleaner, and selectors easier to implement.
maybe we can create a better `connect()` but we have to make sure it doesn't hurt performance

-> [withRedux with example](https://github.com/glekner/foreman/commit/96b2ad12d006ce3f0686f0c622f116218c150214)

2019-06-25 10:56 UTC, sharvit commented
I tend to agree with you @glekner, I love the fact our components just render markup while the logic itself lives outside of the component so we just deliver the actions/data as props.

Therefore I prefer not to use hooks inside the components and I prefer to use them outside as your hooks.

I thought about an approach that keeps our current point of view but uses redux-hooks only in our `index.js` files as well:
```jsx
const ConnectedEditor = () => (
  <Editor
    diffViewType={useSelector(selectDiffType)}
    editorName={useSelector(selectEditorName)}
    errorText={useSelector(selectErrorText)}
    ...
    initializeEditor={useDispatch(initializeEditor)}
  />
);

export default ConnectedEditor;

```

2019-06-27 11:19 UTC, ohadlevy commented
@sharvit ack?

2019-06-27 12:01 UTC, sharvit commented
> @sharvit ack?

I'm waiting for:


> So is it possible to just add an `md` file to the storybook that explains about HOCs and about how to use them inside foreman?

2019-07-04 12:07 UTC, glekner commented
added `md` file

2019-07-04 12:34 UTC, sharvit requested changes
Thanks @glekner

2019-07-04 12:34 UTC, sharvit commented on webpack/stories/components/Markdown/Markdown.js
> +// import './Markdown.scss';
Leftover?

2019-07-04 13:30 UTC, glekner commented on webpack/stories/components/Markdown/Markdown.js
> +// import './Markdown.scss';
thanks, reverted the change

2019-07-04 14:04 UTC, sharvit approved these changes
Thanks @glekner

2019-07-04 14:32 UTC, ohadlevy approved these changes

2019-07-04 14:51 UTC, ohadlevy commented
test failures not related, thanks!

2019-07-04 14:51 UTC, merged