Fixes #10359 - API doc does mention org/loc in create/update
theforeman/foreman pull request #6892
Opened 2019-07-11 12:41 UTC by ofedoren

`/api/v2/organizations/[create | update]`
enpoints now mention the possibility to assing locations via `location_ids` param.

`/api/v2/locations/[create | update]`
enpoints now mention the possibility to assing organizations via `organization_ids` param.

2019-07-14 14:03 UTC, amirfefer requested changes
Thanks @ofedoren  :+1: 
Tested and API docs generated well.

Is there any reason to add a concern instead of altering the taxonomies controller?

2019-07-14 14:03 UTC, amirfefer commented on app/controllers/concerns/api/v2/taxonomies_controller_extension.rb
> +module Api::V2::TaxonomiesControllerExtension
how about changing this to be more informative? like `TaxonomiesControllerDocExtension` ?

2019-07-15 12:42 UTC, ofedoren commented
@amirfefer, the main reason to use a concern instead of altering the taxonomies controller is that organization/location controllers are [extended with taxonomies controller (which is a concern)](https://github.com/theforeman/foreman/blob/ae90b06ba5bb4d0e78f775ebf60833b75d2cd84e/app/controllers/api/v2/locations_controller.rb#L5). To update params for both Loc/Org controllers in more general way, the resource name is needed, because e.g. `LocationsController` needs to have `organization_ids` param. You cannot put the same code in `TaxonomiesController` concern because the resource is known after including `TaxonomiesController` concern in specific actual controller (e.g. `LocationsController`). And the only way to update a param group for each of actual controllers is to use `update_api` which must be used in a concern which will be then used in those controllers.

Also, I named this extension as `TaxonomiesControllerExtension` because there is a really small change and there is plenty of room for other doc or controller itself extensions which should not be in conflict (so there is no need to create a separate file for each small docs fix).

Anyway, any requests are welcome :D

2019-07-15 15:31 UTC, tbrisker commented
@ofedoren I did a little bit of experimenting and looks like you do have access to the resource name inside the param definitions even in the concern, although it is a bit hidden - `param_name` is evaluated to `:organization` when rendering the doc for the organization controller and to `:location` when rendering the doc for the location controller

2019-07-17 13:27 UTC, ofedoren commented
@tbrisker, thanks a lot! Updated accordingly your suggestion. Now it doesn't need to be updated via another concern.

2019-07-18 08:32 UTC, tbrisker approved these changes
Thanks @ofedoren !

2019-07-18 08:32 UTC, merged