Fixes #27347 - Fix User and Usergroup tests
theforeman/foreman pull request #6913
Opened 2019-07-19 13:21 UTC by adamruzicka

Looking into the issue it seems `audited_changes` is a hash with strings as keys, but the tests expect symbols as keys.

2019-07-19 13:41 UTC, adamruzicka commented
This seems to be a regression caused by `audited-4.9.0`, which was released yesterday (18.7.2019), pinning it to `4.8.0` fixes this issue as well.

2019-07-19 18:48 UTC, ezr-ondrej commented
Should we pin, or fix, then?

2019-07-19 19:05 UTC, mmoll commented
Personally I'd say: Fixing (and RPM updating) for develop, pinning for stable.

2019-07-21 07:08 UTC, tbrisker requested changes
As mentioned on the other PR, I'd rather we fix this after branching. Please open a new issue to upgrade to audited 4.9 so we can make sure there aren't other breaking changes post branching.

2019-08-28 08:55 UTC, tbrisker approved these changes
Pushed rebase to make sure the tests are still passing. will merge when green.

2019-08-28 10:50 UTC, tbrisker commented
This needs update to packaging and fix for katello - https://github.com/Katello/katello/blob/3329a4f0336f37db3bd026b93c96904b012391f1/test/models/activation_key_test.rb#L219 also needs updating

2019-08-28 11:08 UTC, tbrisker commented
https://github.com/Katello/katello/pull/8307 will fix this in katello

2019-08-28 12:02 UTC, tbrisker commented
https://github.com/theforeman/foreman-packaging/pull/4040 packaging for this

2019-08-28 12:45 UTC, tbrisker commented
[test katello]

2019-08-28 12:54 UTC, ekohl approved these changes

2019-08-28 13:51 UTC, merged

2019-08-28 13:52 UTC, tbrisker commented
Thanks @adamruzicka !