Fixes #27391 - spinner byte value initialization
theforeman/foreman pull request #6930
Opened 2019-07-25 08:58 UTC by ezr-ondrej

Fixes issue with byte spinner for libvirt and ovirt.

On form ajax load, the spinner is not initialized. This is far safer and it should not be a performance concern. I believe this should be backported and for 1.24 we should switch to React implementation.

It fixes the issue on edit form, not for host edit though, as #6258 disabled the initialization for disabled fields. So we see:
![uninitialized_spinner](https://user-images.githubusercontent.com/2884324/61860874-fd6e4580-aeca-11e9-8fba-1682ff872e47.png)
I would rather see the arrows, than this value, so I offer a revert for byte, but I would appreciate ACK

2019-07-25 11:08 UTC, ezr-ondrej commented
@shiramax could you ack this is better approach for now and we would prefer the correctly formatted field even if disabled (as it will revert yours #6258 for byte fields and show arrows again)?

2019-07-28 11:48 UTC, shiramax requested changes
I'm fine with the change, but it doesn't seem to be working on my setup, something to do with the tfm.numFields.initAll not working from the host_edit.jf file.
also, it means that will need to change https://bugzilla.redhat.com/show_bug.cgi?id=1517257 status. 

Also why are you changing this only for libvirt and ovirt? what about the other CR?

2019-07-30 09:01 UTC, ezr-ondrej commented
Other CR are not using the spinner for memory sizing, so it is not necessary elsewhere. But yeah, I agree, we would need to mark it on the BZ.

2019-08-09 06:50 UTC, ares commented
what is the status here? is it waiting on contributor? @ezr-ondrej were you able to reproduce the issue @shiramax reported?

2019-08-09 07:58 UTC, ezr-ondrej commented
I probably didn't quite understood what @shiramax  means it is not working. I have tried with ansible on, ansible off.. this seems to solve the issue for me :man_shrugging:
I would address the edit form separately, so I droped that commit.

2019-09-02 13:25 UTC, xprazak2 commented
I used libvirt and I have been having trouble reproducing this in a way it is described in redmine. When creating a new host, everything looks ok to me, both downstream and in develop:

![host-new](https://user-images.githubusercontent.com/2664090/64117266-00dfd100-cd95-11e9-94e5-80a11dbed763.png)

When editing host, downstream has units in GB as they should be, but the arrows are not disabled, so it is possible to change value even for disabled field:

![downstream-edit](https://user-images.githubusercontent.com/2664090/64117437-806da000-cd95-11e9-9e4f-816ecde8384d.png)

Develop does not have arrows nor the proper formatting:

![upstream-edit](https://user-images.githubusercontent.com/2664090/64117467-90857f80-cd95-11e9-935a-df7fb3fc2a64.png)

So it seems to me we need a fix for editing host...

2019-09-04 08:42 UTC, ares commented
As discussed, this is needed for 1.24 as the linked PR caused more severe regression. In fact it will restore another bug, arrows will be again clickable, but that is smaller evil until we reimplement spinners in react.

2019-09-05 10:33 UTC, xprazak2 commented
Right, so to sum it up:

1. These changes should make sure the value is always displayed in correct units
2. We do not mind if we have clickable arrows for disabled field (for now)

2019-09-05 10:42 UTC, xprazak2 commented
On host edit, I am getting:

![not-initialized](https://user-images.githubusercontent.com/2664090/64335077-535dff00-cfda-11e9-9c1e-3cd80fe8b104.png)

Without `byte_spinner` class on input (removed by #6258), initialization is not happening.

2019-09-05 11:02 UTC, ezr-ondrej commented
The former (create host) has been fixed by @xprazak2, so this is not as important. I would still say we need to reduce usage of inline javascript, so this still make sense.
Host form is different issue though. As mentioned, introduced in #6258.

2019-09-09 07:42 UTC, ares commented
before merging, it would be good to verify whether it's not resolved by https://github.com/theforeman/foreman/pull/6742

2019-09-09 11:43 UTC, tbrisker commented
This is resolved by #7023, closing this PR.

2019-09-09 11:43 UTC, closed without merging