Fixes #27556 - API errors as warning or higher
theforeman/foreman pull request #6968
Opened 2019-08-09 08:47 UTC by lzap

Many error messages were swalowed, this fixes it and files them as
"warning" level. Also small change - backtraces are now in debug level
by default which seems to me as a good improvement - many error states
repeats over and over again and can easily flood production logs. We do
have ERF error codes to find what exception was thrown in the codebase:

https://projects.theforeman.org/projects/foreman/wiki/ErrorCodes

2019-08-18 12:37 UTC, sharvit requested changes
Thanks @lzap

Can we add a test that the stack trace logged correctly?

2019-08-23 07:46 UTC, lzap commented
Are you sure you want me to add test for this? Tests are important I mean, however a missing log line is not a big deal and I would like us to spend our time on other things.

2019-08-23 07:49 UTC, lzap commented on app/controllers/api/base_controller.rb
> +    end
Covered in:

```
/home/lzap/work/foreman/test/controllers/application_controller_subclass_test.rb:
  243        ActiveRecord::MigrationContext.any_instance.stubs(:needs_migration?).returns(true)
  244        get :index
  245:       assert_response :service_unavailable
  246      end
  247    end
```
Including the method above.

2019-08-23 07:49 UTC, lzap commented on lib/foreman/logging.rb
>      end
And this method is covered in many tests, we do actually log during unit/integration testing into `log/test.log`.

2019-08-23 13:27 UTC, lzap commented
Please ping me on IRC if you insist on tests, I need this one to be merged soon (too many GH notifications problem).

2019-08-26 14:18 UTC, ezr-ondrej approved these changes
@sharvit, I agree it would be better to have tests, but I would be ok getting this in if it's tested manually as it's not really high prio and we are keeping the coverage, not lowering it...
What do you think?

2019-08-27 12:03 UTC, sharvit approved these changes
Thanks

2019-08-28 07:46 UTC, ezr-ondrej commented
Thanks @lzap :+1:

2019-08-28 07:46 UTC, merged