Fixes #27642 - Add helpers for deep keys transforms
theforeman/foreman pull request #6978
Opened 2019-08-16 13:47 UTC by xprazak2

extracted from https://github.com/theforeman/foreman_templates/pull/109/files#diff-375445b5a84cd461b8571395b5d4a75f

2019-08-18 11:48 UTC, sharvit requested changes
Thanks @xprazak2 LGTM, please fix the linting errors.

2019-08-19 07:21 UTC, xprazak2 commented
I fixed the errors.

2019-08-19 08:53 UTC, sharvit approved these changes

2019-08-27 10:18 UTC, tbrisker approved these changes
Thanks @xprazak2 and @sharvit !

2019-08-27 10:18 UTC, merged