Fixes #27004 - fix borken link to vm list
theforeman/foreman pull request #7011
Opened 2019-09-01 09:24 UTC by amirfefer

When viewing a VM on a compute resource, the breadcrumb link to navigate back to the list of VM's in the top left corner "Compute Resources Vms" does not take you back to the list. No action is taken

the switcher has been removed due to lack of vm list via API

2019-09-01 10:42 UTC, ohadlevy commented
thanks, that was always annoying to see

2019-09-01 13:17 UTC, amirfefer commented
tests failure seem unrelated

2019-09-02 06:42 UTC, tbrisker commented on app/views/compute_resources_vms/show.html.erb
> +    ],
Following our discussion yesterday, the breadcrumbs on this page should be:
Compute Resources -> <compute resource name> -> VMs -> <vm name>
which is the same as in the CR images page.
The vms index page should also include similar breadcrumbs.

2019-09-02 17:18 UTC, amirfefer commented
@tbrisker , @sharvit  - following to our discussion about `url_for` - https://github.com/theforeman/foreman/pull/7015

2019-09-03 11:34 UTC, apuntamb requested changes

2019-09-03 11:34 UTC, apuntamb commented on app/views/compute_resources_vms/show.html.erb
> +        url: url_for(compute_resource_vms_path(@compute_resource))
I think we can skip the use of `url_for` here too?

2019-09-06 09:24 UTC, timogoebel commented
Nit: The commit message contains a typo.

2019-09-09 11:30 UTC, amirfefer commented
Updated to:
![vmware-breadcrumbs](https://user-images.githubusercontent.com/11807069/64527281-2c6f3800-d30e-11e9-939c-788b96b3e80e.png)

commit message is fixed as well

2019-09-09 11:34 UTC, tbrisker commented on app/views/compute_resources_vms/show.html.erb
> +                  {
nitpick: looks like the indentation is off here and above

2019-09-09 11:37 UTC, tbrisker requested changes
Please also add the breadbrumb on the `compute_resource_vms/index.html.erb` page

2019-09-09 12:00 UTC, tbrisker approved these changes
tested, works well. Thanks @amirfefer !

2019-09-09 12:46 UTC, tbrisker commented
test failures unrelated.

2019-09-09 12:46 UTC, merged