Fixes #27907 - Add update_subnets_from_facts setting
theforeman/foreman pull request #7060
Opened 2019-09-23 13:57 UTC by treydock

Allow hostgroup updates from facts to be disabled via the
update_subnets_from_facts setting

2019-09-23 15:27 UTC, ekohl requested changes
The title also has subnets rather than hostgroup

2019-09-23 15:27 UTC, ekohl commented on test/models/host_test.rb
> +      Setting[:update_subnets_from_facts] = true
```suggestion
      Setting[:update_hostgroup_from_facts] = true
```

2019-09-23 15:27 UTC, ekohl commented on test/models/host_test.rb
> +      Setting[:update_subnets_from_facts] = false
```suggestion
      Setting[:update_hostgroup_from_facts] = false
```

2019-09-23 16:37 UTC, treydock commented on test/models/host_test.rb
> +      Setting[:update_subnets_from_facts] = false
Fixed copy+paste mistake

2019-09-23 16:37 UTC, treydock commented on test/models/host_test.rb
> +      Setting[:update_subnets_from_facts] = true
Fixed copy+paste mistake

2019-09-23 17:54 UTC, ekohl commented
I am wondering if we should generalize this to a setting `update_attributes_from_facts` (or similar) that's a list of things to import. Currently we have:
* `ignore_facts_for_operatingsystem`
* `ignore_facts_for_domain`
* `update_environment_from_facts`
* `update_subnets_from_facts`

This would add one more. It would also be a chance to unify the `ignore` and `update` behavior to a single one that's either positive or negative. Just not sure how well our UI works with settings that are lists.

2019-09-23 18:36 UTC, treydock commented
The UI seems okay for lists as that's used for `excluded_facts`, which is free form lists. I'm trying to test if my end goal of hostgroup not getting updated is possible via `excluded_facts`. I think it's actually the helper fact I have called `hostgroup_name` that's the issue but having issues testing that at the moment.

I think maybe a list of facts to not update on would be enough if `exclude_facts` doesn't do that already.  Right now my test environment isn't able to test any fact importing because I keep getting `nil` for the importer:

As side note I'd like to get this pushed into Satellite 6.6 once merged so figured making a backwards compatible change would make it easier to get this pulled in by Red Hat.

```
Error:
HostTest::import host and facts#test_0026_host hostgroup updated from facts:
NoMethodError: undefined method `new' for nil:NilClass
    app/models/host/base.rb:144:in `import_facts'
    app/models/host/managed.rb:329:in `import_facts'
    test/models/host_test.rb:823:in `block (2 levels) in <class:HostTest>'
```

2019-10-02 08:55 UTC, ares commented
@treydock thanks for your effort here. I'd like to check if you were able to solve the problem with `excluded_facts` and if not, if you'd be willing to do the bigger refactoring that was suggested by @ekohl or you wouldn't be able to get to it. That will allow us to decide how to proceed with this PR.

2019-10-02 13:03 UTC, treydock commented
I've had really inconsistent results when sending the facts `hostgroup` and `hostgroup_name` to Satellite 6.5.0. At first I think it was `hostgroup_name` that was reverting the Satellite picked hostgroup but now I'm unable to reproduce the behavior. I'm not convinced this pull request does what I thought it would do as I don't think doing `host.hostgroup = 'foo'` is actually going to work since `hostgroup` refers to an association. But it seems `host.hostgroup_name = 'foo'` does work.

2019-10-02 13:44 UTC, tbrisker commented
looks like I suggested unifying these settings already 3 years ago - https://projects.theforeman.org/issues/17625. Would be good to do that but i'd be fine with it being in a separate PR to this one.

2020-03-05 08:06 UTC, tbrisker commented
This was actually ready to merge, reopening. Sorry for the slow turnaround @treydock ! I'll merge this now and leave refactoring the settings to a separate issue.

2020-03-05 15:23 UTC, tbrisker approved these changes
Thanks @treydock and sorry again for the very long time it took me to get to this!

2020-03-05 15:24 UTC, merged