Fixes #27943 - oVirt instance type throw error on vm creation
theforeman/foreman pull request #7070
Opened 2019-09-30 13:10 UTC by bagasse

Align VM memory/cpus to templates/instance type ones (if no values found)

2019-10-03 12:19 UTC, bagasse commented
[test foreman]

2019-10-03 14:03 UTC, ezr-ondrej requested changes
It makes sense to me, but I would like to hear if it's what we want from @shiramax if possible :eyes: 
I have few thoughts and found one typo (probably) for code:
1. As a user I would like to at least see the value that's going to be filled in the `cores`/`memory` fields. Would that be posible?
1. How are we going to handle the `instance_type` being selected. Shouldn't we disable the fields dynamicaly by JS?

2019-10-03 14:03 UTC, ezr-ondrej commented on app/views/compute_resources_vms/form/ovirt/_base.html.erb
> +<% disable_field = !new_vm || (new_vm && @host.try(compute_attributes).try(instance_type)) %>
Typo?
```suggestion
<% disable_field = !new_vm || (new_vm && @host.try(:compute_attributes).try(:instance_type)) %>
```
Or:
```suggestion
<% disable_field = !new_vm || (new_vm && @host&.compute_attributes&.instance_type) %>
```

2019-10-03 14:03 UTC, ezr-ondrej commented on app/views/compute_resources_vms/form/ovirt/_base.html.erb
> +<%= counter_f f, :cores, :disabled => disable_field, :label => _('Cores per socket'), :label_size => 'col-md-2' %>
Above, we're checking if the `instance_type` has the field filled and overwriting only when it does. Shouldn't we disable only in such case then?

2019-10-03 14:03 UTC, ezr-ondrej commented on app/views/compute_resources_vms/form/ovirt/_base.html.erb
> +<%= counter_f f, :sockets, :disabled => disable_field, :label => _('Sockets'), :label_size => 'col-md-2' %>
This field is not being overwritten at all by `instance_type` is it correct to disable it?

2019-10-03 14:03 UTC, ezr-ondrej commented on app/models/compute_resources/foreman/model/ovirt.rb
> +        args[:memory] = instance_type_memory if instance_type_memory
Why we are assigning the values now? Isn't the values removal safer, if the values are going to be added by ovirt?

2019-10-03 14:19 UTC, bagasse commented on app/models/compute_resources/foreman/model/ovirt.rb
> +        args[:memory] = instance_type_memory if instance_type_memory
The previous implementation removed the values, but I think that if the value is not present (at least for memory) it set it to a default value (1GB) and set also max memory to 4x memory (4GB) and so we have an error when creating vm based on instance type (as attached to the redmine issue). For me it's a bug on the oVirt side, but as instance type is in deep maintenance mode I don't think they will make any change on it (and taking a look at java code is realy not easy for me) (I've a PR opened for months on the ansible-ovirt side without any comment or go/nogo)

2019-10-03 14:21 UTC, bagasse commented on app/views/compute_resources_vms/form/ovirt/_base.html.erb
> +<%= counter_f f, :sockets, :disabled => disable_field, :label => _('Sockets'), :label_size => 'col-md-2' %>
You are right, same for memory.

2019-10-03 15:00 UTC, bagasse commented on app/views/compute_resources_vms/form/ovirt/_base.html.erb
> +<%= counter_f f, :cores, :disabled => disable_field, :label => _('Cores per socket'), :label_size => 'col-md-2' %>
You are right, same for memory.

2019-10-03 15:24 UTC, bagasse commented on app/views/compute_resources_vms/form/ovirt/_base.html.erb
> +<%= counter_f f, :sockets, :disabled => disable_field, :label => _('Sockets'), :label_size => 'col-md-2' %>
Yes sockets are not supported by instance type in foreman for now, I will add it when https://github.com/fog/fog-ovirt/pull/75 will land.
I think that if user defined cores value in an instance type, he should also define sockets.

If you want, for now I can let this fields as it was before and manage field disableing more nicely in another PR when the fog-ovirt part will be merged.

2019-10-04 11:27 UTC, ezr-ondrej commented on app/models/compute_resources/foreman/model/ovirt.rb
> +        args[:memory] = instance_type_memory if instance_type_memory
Ok, I misunderstood the issue and though we define different value manually and deleting (omiting) it would make oVirt define it.

2019-10-04 11:29 UTC, ezr-ondrej commented on app/views/compute_resources_vms/form/ovirt/_base.html.erb
> +<%= counter_f f, :sockets, :disabled => disable_field, :label => _('Sockets'), :label_size => 'col-md-2' %>
yeah, it would make sense to me. as there is no value on instance_type, we should have a way to define it manually.

2019-10-04 11:35 UTC, bagasse commented on app/views/compute_resources_vms/form/ovirt/_base.html.erb
> +<%= counter_f f, :sockets, :disabled => disable_field, :label => _('Sockets'), :label_size => 'col-md-2' %>
Ok reverted all changes on this file and I will comeback to handle that in the same way at the same time when https://github.com/fog/fog-ovirt/pull/75 will land. Sorry for the noise.

2019-10-04 13:07 UTC, ezr-ondrej reviewed
I would be ok with current version, but User should be at least notified the values for cores/memory will possibly change (as in UI now user is able to fill in the values, but if he fills the `instance_type` as well, those are not going to be used).
Would be an warning message (`help_text`/`help_inline` for `instance_type` field) in the form a sufficient temporary solution?

2019-10-04 13:33 UTC, bagasse commented
For me it is, added message in the helper text.

2019-10-05 13:18 UTC, ezr-ondrej submitted a review, later dismissed
LGTM. @shiramax could you ack, that this is what we want?
Meaning overwrite the cores and memory by instance_type values?

2019-10-06 08:27 UTC, shiramax reviewed
Looks good to me! But I have some questions: 
1. Before the change, we didn't create the VM the right CPU and memory? 
2. what error message you expected to get now? because the error message in Redmine issue seems Ok to me.

2019-10-06 18:31 UTC, ezr-ondrej commented
> 1. Before the change, we didn't create the VM the right CPU and memory?
> 2. what error message you expected to get now? because the error message in Redmine issue seems Ok to me.

@shiramax I will try to answer, @bagasse please correct me if I'm mistaken :)

1. I would say we were not trying to override the manual values with the ones from `instance_type`. Not sure if that is correct or not, I would like to hear your opinion :)
2. With this change it shouldn't error out, as we will use the values from the `instance_type` if it's selected, not those filled manually.

2019-10-07 09:45 UTC, bagasse commented
@shiramax, @ezr-ondrej in the current implementation, the memory and cpus values are ignored by ovirt and oVirt use Instance type ones, in the UI all fields are disabled
![Screenshot from 2019-10-07 11-31-40](https://user-images.githubusercontent.com/2952632/66301163-e4383b00-e8f6-11e9-85cd-2ddc0743f460.png)
, on the background we remove these values as we use instance type values. but if values are missing, oVirt set default values for memory (1GB) and max_memory (4 x memory by default so 4GB) and try to validate instance type memory (eg 16GB) with vm max_memory (4GB) and we hit the error message attached to redmine issue. But when the error is printed, on the page reload, files are not disabled anymore (that's why I wanted to disable fields on page reload in some of iterations of this PR).
![Screenshot from 2019-10-07 11-32-04](https://user-images.githubusercontent.com/2952632/66301292-219cc880-e8f7-11e9-8f29-20c275b04422.png)

Because if this inconsistency, users can workaround the issue by passing "random' value to memory that will be passed to oVirt but oVirt will create VM with instance type values and will never use vm passed values but still try to validates these values (that why we have the error above)

2019-10-07 10:22 UTC, shiramax submitted a review, later dismissed
thanks for the explanation @bagasse :)

2019-10-07 10:31 UTC, ezr-ondrej commented
@bagasse can you please rebase on newest develo? It should be clean rebase, but the history is too diverge for the github doing it automatically.

2019-10-07 13:43 UTC, ezr-ondrej approved these changes
Thanks @bagasse and @shiramax  :+1:

2019-10-07 13:43 UTC, merged

2019-10-07 13:47 UTC, bagasse commented
@ezr-ondrej, @shiramax thank you for your time/reviews/patience ;)