Fixes #28070 - host param fallback parameter
theforeman/foreman pull request #7110
Opened 2019-10-16 10:02 UTC by lzap

This statement in our kickstart template does not work correctly:

    use_ntp = host_param_true?('use-ntp') || (is_fedora && os_major < 16) || (rhel_compatible && os_major <= 7

In order to avoid three liner, I am introducing a default value option, so it can be shortened to:

    use_ntp = host_param_true?('use-ntp', (is_fedora && os_major < 16) || (rhel_compatible && os_major <= 7))

2019-10-16 10:12 UTC, ekohl requested changes
I'm not 100% sure this makes sense and I don't see why the provided example doesn't work. I think the problem is really that it should be `< 7` instead of `<=`.

2019-10-16 10:12 UTC, ekohl commented on lib/foreman/renderer/scope/macros/host_template.rb
> +          def host_param_true?(name, default_value = nil)
Should the default be `false` to be 100% API compatible?

2019-10-16 10:12 UTC, ekohl commented on lib/foreman/renderer/scope/macros/host_template.rb
> +          def host_param_false?(name, default_value = nil)
I think the default should be `true` because now you're breaking the API.

2020-03-04 09:19 UTC, tbrisker commented
ping @lzap ?

2020-03-27 12:50 UTC, lzap commented
Good call, added a test for that.

2020-03-29 07:49 UTC, tbrisker commented on lib/foreman/renderer/scope/macros/host_template.rb
> +              default_value
This will now return `true` if the param doesn't exist, where before it would return `false`.

2020-03-29 07:50 UTC, tbrisker commented on test/unit/foreman/renderer/scope/macros/host_template_test.rb
> +      refute @scope.host_param_true?('true_param')
This should probably be 
```suggestion
      refute @scope.host_param_false?('true_param')
```

2020-04-02 12:43 UTC, lzap commented
Thanks, rebased.

2020-04-02 12:46 UTC, tbrisker commented on lib/foreman/renderer/scope/macros/host_template.rb
> +              default_value
This still needs fixing - the default value should be false in this function as well to maintain compatibility

2020-04-22 08:04 UTC, tbrisker commented
test failures related

2020-05-06 08:33 UTC, lzap commented
Rebased, thanks.

2020-05-06 14:02 UTC, tbrisker approved these changes
Thanks @lzap !

2020-05-06 14:02 UTC, merged

2021-01-29 10:08 UTC, ares commented
FYI this resulted in https://projects.theforeman.org/issues/28070, @ekohl comments were not addressed