Fixes #28270 - consume babel from @theforeman/env
theforeman/foreman pull request #7178
Opened 2019-11-14 16:49 UTC by sharvit

`@theforeman/env` hasn't deployed yet, based on https://github.com/theforeman/foreman-js/pull/62

2019-11-14 16:53 UTC, sharvit commented on package.json
> -    "@babel/core": "^7.7.0",
Probably we will need to keep `@babel/core` but I'm still investigating.

2019-11-18 12:41 UTC, xprazak2 commented
Packaging: https://github.com/theforeman/foreman-packaging/pull/4348

2019-11-18 16:20 UTC, amirfefer commented on package.json
> +    "@theforeman/env": "^3.1.0",
:heart:

2019-11-18 16:28 UTC, amirfefer submitted a review, later dismissed
Nice! works as expected!
Thanks @sharvit !

Why did you add the redux update commit?

2019-11-19 12:44 UTC, sharvit commented
> Why did you add the redux update commit?

Because I need to use `vendor` v3 while develop uses `vendor` v1, the redux commit updates the vendor to v2 so it makes sense using it.

2019-11-20 10:38 UTC, adamruzicka submitted a review, later dismissed
Seems to work nicely together with REX and tasks

2019-11-21 16:23 UTC, sharvit commented on package.json
> +    "@theforeman/babel": "^3.2.0",
Needs a packaging PR

2019-11-21 16:24 UTC, sharvit commented on package.json
> +    "babel-loader": "^8.0.0",
`babel-loader` needs packaging PR.
(it is in the scope of `webpack`, not `babel`, as it's a webpack plugin)

2019-11-21 16:42 UTC, sharvit commented
Updates about packaging: @evgeni @ekohl @ehelms @tbrisker 

The last effort migrating to `vendor` v3 blocked because we found out we need to do packaging for too many `babel-<something>` modules while we already have a solution for grouping them in one package to simplify the packaging process.

Therefore I created the `@theforeman/babel` module that contains all the `babel` modules and group them together.

To merge this PR, we need:
1. Update `@theforeman/vendor` in packaging to v3.2.0
2. Remove all the `babel` staff from packaging
3. Add `@theforeman/babel` to the packaging
4. Remove all the `babel` related things from packaging (**except `babel-loader`**)
5. Update the `babel-loader` in packaging to >=v8
(Did I forget something?)

I didn't want to do all those changes by myself because I am not that familiar with the packaging and I guess they should all be done in 1 PR. Can I get some help here from the packaging team?

2019-11-22 13:52 UTC, evgeni commented
This sounds sensible to me, but I'd like another ack from @ehelms or @ekohl.
We then basically end up with a big `@theforeman/babel` RPM that contains all the babel things and can carry on. Technically we don't need to remove the old babel stuff from packaging, but we should double-check that after merging these changes to plugins nothing more pulls that in.

2019-11-22 15:37 UTC, ekohl commented
I can only agree with what @evgeni said.

2019-11-27 09:24 UTC, sharvit commented
We decided to change the design around `babel` and split the configuration to `prod` and `dev`.
- `@theforeman/builder` -  contains the **`prod`** related `babel` modules and configs.
- `@theforeman/env` - contains the **`dev`** related `babel` modules and configs.

**So we should only `package` the builder module.**
The future plan is adding `webpack` modules to the `builder` so later we will just need to update the `builder` package.

2019-11-27 11:45 UTC, evgeni commented
Started builder packaging in https://github.com/theforeman/foreman-packaging/pull/4413

2019-11-27 12:42 UTC, evgeni commented
babel-loader: https://github.com/theforeman/foreman-packaging/pull/4416

2019-11-28 14:30 UTC, evgeni commented
so after building vendor 3.3.0, builder 3.3.0 and babel-loader 8.0.6, I get the following when trying to build foreman:

```
ERROR in ./webpack/assets/javascripts/bundle.js
Module build failed: Error: Cannot find module '@babel/core'
 babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/theforeman/tfm/root/usr/lib/node_modules/babel-loader/lib/index.js:10:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at loadLoader (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/loadLoader.js:18:17)
    at iteratePitchingLoaders (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/lib/NormalModule.js:275:15)
    at Compilation.buildModule (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/lib/Compilation.js:157:10)
    at moduleFactory.create (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/lib/Compilation.js:460:10)
    at factory (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:243:5)
    at applyPluginsAsyncWaterfall (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:94:13)
    at /opt/theforeman/tfm/root/usr/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:268:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:272:13)
    at resolver (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:69:10)
    at process.nextTick (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:196:7)
    at process._tickCallback (internal/process/next_tick.js:61:11)
error: Bad exit status from /var/tmp/rpm-tmp.P0dUQ2 (%build)
    Bad exit status from /var/tmp/rpm-tmp.P0dUQ2 (%build)
```

2019-11-28 15:23 UTC, evgeni commented
actually adding `@babel/core` to the buildroot gives me

```
ERROR in ./webpack/assets/javascripts/bundle.js
Module build failed: Error: /builddir/build/BUILD/foreman-1.25.0-develop/.babelrc.js: Error while loading config - Cannot find module '@theforeman/env/babel'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at Object.<anonymous> (/builddir/build/BUILD/foreman-1.25.0-develop/.babelrc.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at readConfigJS (/opt/theforeman/tfm/root/usr/lib/node_modules/@babel/core/lib/config/files/configuration.js:190:26)
    at cachedFunction (/opt/theforeman/tfm/root/usr/lib/node_modules/@babel/core/lib/config/caching.js:32:19)
    at readConfig (/opt/theforeman/tfm/root/usr/lib/node_modules/@babel/core/lib/config/files/configuration.js:162:44)
    at names.reduce (/opt/theforeman/tfm/root/usr/lib/node_modules/@babel/core/lib/config/files/configuration.js:128:20)
    at Array.reduce (<anonymous>)
    at loadOneConfig (/opt/theforeman/tfm/root/usr/lib/node_modules/@babel/core/lib/config/files/configuration.js:125:24)
    at findRelativeConfig (/opt/theforeman/tfm/root/usr/lib/node_modules/@babel/core/lib/config/files/configuration.js:100:16)
    at buildRootChain (/opt/theforeman/tfm/root/usr/lib/node_modules/@babel/core/lib/config/config-chain.js:113:39)
    at loadPrivatePartialConfig (/opt/theforeman/tfm/root/usr/lib/node_modules/@babel/core/lib/config/partial.js:85:55)
    at Object.loadPartialConfig (/opt/theforeman/tfm/root/usr/lib/node_modules/@babel/core/lib/config/partial.js:110:18)
    at Object.<anonymous> (/opt/theforeman/tfm/root/usr/lib/node_modules/babel-loader/lib/index.js:144:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/opt/theforeman/tfm/root/usr/lib/node_modules/babel-loader/lib/index.js:3:103)
    at _next (/opt/theforeman/tfm/root/usr/lib/node_modules/babel-loader/lib/index.js:5:194)
    at /opt/theforeman/tfm/root/usr/lib/node_modules/babel-loader/lib/index.js:5:364
    at new Promise (<anonymous>)
    at Object.<anonymous> (/opt/theforeman/tfm/root/usr/lib/node_modules/babel-loader/lib/index.js:5:97)
    at Object._loader (/opt/theforeman/tfm/root/usr/lib/node_modules/babel-loader/lib/index.js:224:18)
    at Object.loader (/opt/theforeman/tfm/root/usr/lib/node_modules/babel-loader/lib/index.js:60:18)
    at Object.<anonymous> (/opt/theforeman/tfm/root/usr/lib/node_modules/babel-loader/lib/index.js:55:12)
error: Bad exit status from /var/tmp/rpm-tmp.M5dlPM (%build)
    Bad exit status from /var/tmp/rpm-tmp.M5dlPM (%build)
```

2019-12-02 15:43 UTC, sharvit commented
> actually adding @babel/core to the buildroot gives me

It should work now :)
Can you please try again?

2019-12-02 15:55 UTC, evgeni commented
So I tried with bec5ad8f464b3fd4d6f53d291dc6dd0e4042b205 (that was the version that was using 3.3.1) and it seemed to be fine. I needed to build babel-loader, @babel/core and obviously vendor and builder. :+1: 

I tried clicking around in the UI and saw no obvious errors, also nothing in the Console log.

2019-12-02 16:06 UTC, evgeni commented
packaging PRs:

* foreman: https://github.com/theforeman/foreman-packaging/pull/4435
* builder: https://github.com/theforeman/foreman-packaging/pull/4413
* vendor: https://github.com/theforeman/foreman-packaging/pull/4417
* @babel/core: https://github.com/theforeman/foreman-packaging/pull/4425
* babel-loader: https://github.com/theforeman/foreman-packaging/pull/4416

2019-12-02 16:06 UTC, evgeni approved these changes
packaging: ACK

2019-12-02 16:33 UTC, sharvit commented
Thanks @evgeni :+1: 

The Travis errors are unrelated: https://projects.theforeman.org/issues/28391

2019-12-03 07:05 UTC, evgeni commented
@sharvit makes sense, cool.

can someone please ACK this from the JS/UX perspective please?

2019-12-03 08:51 UTC, Ron-Lavi approved these changes
Thanks @sharvit, tested LGTM :+1:

2019-12-03 10:20 UTC, amirfefer requested changes
Storybook is broken after the upgrade with this error:
```
ERROR in ./.storybook/config.js
Module build failed: Error: [BABEL] /home/afeferku/git/foreman/.storybook/config.js: Cannot find module
 '@theforeman/vendor-core' (While processing: 
"/home/afeferku/git/foreman/node_modules/@theforeman/env/babel/index.js")
```

EDIT: I was on an a previous version, after rebuilding it works well

2019-12-03 12:07 UTC, amirfefer approved these changes
foreman and storybook work well :+1: 
tested in develop and production 

Thanks @sharvit !

2019-12-03 12:10 UTC, merged

2019-12-03 12:11 UTC, sharvit commented
Thanks @amirfefer @laviro @evgeni @xprazak2 @adamruzicka :+1: