Fixes #28484 - Pass hostname to GCP API
theforeman/foreman pull request #7242
Opened 2019-12-11 14:37 UTC by eLvErDe

Needs an update from fog-google to use recent enought google-api-client but that should not be an issue if enable before, just no-oop.

I asked for a fog-google update here
https://github.com/fog/fog-google/issues/479

2019-12-11 14:40 UTC, eLvErDe commented
![gcp_custom_instance_hostname](https://user-images.githubusercontent.com/1586757/70630798-7842bd80-1c2c-11ea-935d-585a72bfe14c.png)

Here is how you can check in Google Cloud Console (network details of the instance)

2019-12-11 15:10 UTC, tbrisker commented
ok to test

2020-01-13 06:44 UTC, apuntamb requested changes
Adding inline comment.

2020-01-13 06:44 UTC, apuntamb commented on app/models/compute_resources/foreman/model/gce.rb
>        args[:name] = args[:name].parameterize if args[:name].present?
@eLvErDe Can we make this as:  
```ruby
if args[:name].present?
    args[:hostname] = args[:name]
    args[:name] = args[:name].parameterize
end

```
@kgaikwad what do you think?

2020-10-06 09:47 UTC, eLvErDe commented
Hello,

May I ask this to be re-opened ? Fog-google has been updated and thus, this minor patch will be sufficient to have the feature working if you just bump fog-google gem dependency version.

Best regards, Adam.

2020-10-06 09:50 UTC, tbrisker commented
@eLvErDe sure, I think you can reopen on your own, i'll reopen it for you though. Please rebase the pr on latest develop and update the fog-google minimum version to the new one.

2020-10-06 14:04 UTC, eLvErDe commented
@tbrisker Okay, I think this one is ready now. I still have some AWS work to do on another one....

2020-10-07 23:35 UTC, ezr-ondrej commented
Packaging PR: https://github.com/theforeman/foreman-packaging/pull/5871

2020-10-16 14:26 UTC, ezr-ondrej approved these changes
Good by me! :+1:
It will need a packinging ack though, but the packaging PR is in :+1:

2020-10-16 14:39 UTC, evgeni approved these changes
![tenor.gif](https://user-images.githubusercontent.com/94284/96272283-30b85b00-0fce-11eb-9966-a6d4e38fd323.gif)

2020-10-25 08:40 UTC, tbrisker commented
Thanks @eLvErDe and @ezr-ondrej ! Please update the foreman package requirements as repoclosure is currently failing: https://community.theforeman.org/t/foreman-nightly-rpm-pipeline-799-failed/21000/2

2020-10-25 08:40 UTC, merged

2020-10-25 08:51 UTC, evgeni commented
The repoclosure should ne unrelated to the requirements in the spec file. (Packaging release was broken for a few days, so it might be better tomorrow)

2020-10-25 08:52 UTC, evgeni commented
Oh, now that I've read the error, tomer is right