WIP - Fixes #28664 - API middleware redirect to login on 401
theforeman/foreman pull request #7337
Opened 2020-01-07 09:25 UTC by laviro

redirect to login whenever the error status is 401,
blocked by #7222 and #7186

To Do: add test.

2020-01-07 18:10 UTC, amirfefer requested changes
Thanks @laviro ! 
I think maybe this error handling should be managed by the API middleware and be defined inside an action, something like this?
```js
{
  type: API_OPERATIONS.GET,
  payload: {
    key: NOTIFICATION
    url,
    payload,
    errorHandling:  error  => {
      if (error.response.status === 401) visit('/users/login');
    } 
  }
```

2020-01-07 18:10 UTC, amirfefer commented on webpack/assets/javascripts/react_app/redux/API/APIRequest.js
> +    if (error.response.status === 401) {
Foreman may return with unauthorized status in some cases (afaik,  when admin permissions required) so these cases should be filtered out, or this error handling should be part of a specific action

2020-03-12 13:38 UTC, amirfefer commented
@laviro what's the status here?

2020-03-21 22:04 UTC, amirfefer commented
This comment is relevant for here 
https://github.com/theforeman/foreman/pull/7338/files#r391642824

2020-03-22 18:03 UTC, laviro commented
thanks @amirfefer ! updated with the `handleError` param as we discussed
to create a more generic handler for such cases.

2020-03-23 01:50 UTC, amirfefer requested changes
Thanks, @laviro  :+1:

2020-03-23 01:50 UTC, amirfefer commented on webpack/assets/javascripts/react_app/redux/API/APIRequest.js
> +    handleError(error);
could you please add a test for this?

2020-03-23 10:37 UTC, laviro commented on webpack/assets/javascripts/react_app/redux/API/APIRequest.js
> +    handleError(error);
thanks, added

2020-03-23 10:38 UTC, laviro commented
rebased and added a test

2020-03-23 11:33 UTC, laviro commented
added `handleSuccess` too

2020-03-30 07:12 UTC, laviro commented
ready for another review

2020-03-31 07:45 UTC, MariaAga commented
Great addition to the api! One question: @laviro Why is the request always calling the handle function? wouldn't it be better to only call it if it was defined and give it a `null` value?

2020-03-31 08:05 UTC, laviro commented
Thanks @MariaAga !
[setting those handlers initially to `noop`](https://github.com/theforeman/foreman/pull/7337/files#diff-958832b8df41edaad1c6dcf74e3ac31cR13) allow us to call them without checking

2020-04-02 10:18 UTC, laviro commented
@amirfefer @sharvit could you take a look? thanks

2020-04-07 14:49 UTC, MariaAga submitted a review, later dismissed

2020-04-16 16:23 UTC, laviro commented
Thanks @MariaAga,
@sharvit can you take a look?

2020-06-04 05:35 UTC, laviro commented
rebased, there are several PRs that are waiting on this,
@amirfefer @jeremylenz can you maybe take a final look? Thanks

2020-06-04 22:18 UTC, jeremylenz reviewed
Thanks @laviro !  Tested with Katello subscriptions page, works as expected.  Just one comment below

2020-06-04 22:18 UTC, jeremylenz commented on webpack/assets/javascripts/react_app/redux/API/APIRequest.js
>        type: SUCCESS,
Seems to me like the callbacks should get called after the actions (in other words, switch the order of the `handleSuccess` and `dispatch`.)  I wouldn't want a side effect to happen before I'm even notified of what caused the side effect.

2020-06-07 06:40 UTC, laviro commented
Thanks @jeremylenz ! makes sense, changed the order of the callbacks and the action dispatch

2020-06-08 14:13 UTC, jeremylenz approved these changes
Changes look good, thanks @laviro !

2020-06-08 17:12 UTC, laviro commented
@amirfefer can we merge this?

2020-06-09 15:44 UTC, amirfefer approved these changes
Thanks @laviro ! Great addition  :+1:

2020-06-09 15:45 UTC, merged

2020-06-09 18:50 UTC, johnpmitsch commented
This seems to be affecting Katello tests (since they have been updated to use foremanReact directly). It shouldn't in theory, as the imports seem to be fine and webpack handles it fine, but Jest seems to have a problem with the imports in this area of code. Historically, I also had to [remove internal usage of deprecated code](https://github.com/theforeman/foreman/commit/5d07be849b7498fc7a0a311b65600b5e246645b7#diff-25ebde132b3bd4206343cbd4254b9a93) from here as it was causing a very similar issue. 

Here is the message, notice the line numbers displayed don't actually exist. I'm not sure exactly what is happening. Does anyone have any ideas?

```
FAIL webpack/scenes/ContentViews/__tests__/contentViewPage.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'APIMiddleware' of undefined



      at Object.get [as APIMiddleware] (../foreman/webpack/assets/javascripts/react_app/redux/API/index.js:28:27)
      at Object.APIMiddleware (../foreman/webpack/assets/javascripts/react_app/redux/middlewares/index.js:9:17)
      at Object.<anonymous> (../foreman/webpack/assets/javascripts/react_app/redux/index.js:10:46)
      at Object.<anonymous> (../foreman/webpack/assets/javascripts/foreman_navigation.js:4:1)
      at Object.<anonymous> (../foreman/webpack/assets/javascripts/foreman_tools.js:12:1)
      at Object.<anonymous> (../foreman/webpack/assets/javascripts/react_app/common/helpers.js:4:1)
      at Object.<anonymous> (../foreman/webpack/assets/javascripts/react_app/redux/API/APIRequest.js:3:1)
      at Object.<anonymous> (../foreman/webpack/assets/javascripts/react_app/redux/API/APIMiddleware.js:2:1)
      at Object.<anonymous> (../foreman/webpack/assets/javascripts/react_app/redux/API/index.js:7:1)
      at Object.<anonymous> (webpack/test-utils/react-testing-lib-wrapper.js:7:1)
      at Object.<anonymous> (webpack/scenes/ContentViews/__tests__/contentViewPage.test.js:3:1)
```

This change is a workaround to the issue:
```diff
diff --git a/webpack/assets/javascripts/react_app/redux/API/APIRequest.js b/webpack/assets/javascripts/react_app/redux/API/APIRequest.js
index a97d885..f3c37cb 100644
--- a/webpack/assets/javascripts/react_app/redux/API/APIRequest.js
+++ b/webpack/assets/javascripts/react_app/redux/API/APIRequest.js
@@ -1,6 +1,7 @@
 import { API } from './';
 import { actionTypeGenerator } from './APIActionTypeGenerator';
-import { noop } from '../../common/helpers';
+//import { noop } from '../../common/helpers';
+const noop = () => {};
 
 export const get = async (
   {
```
also so does
```diff
diff --git a/webpack/assets/javascripts/react_app/common/helpers.js b/webpack/assets/javascripts/react_app/common/helpers.js
index b75fa0b..904c491 100644
--- a/webpack/assets/javascripts/react_app/common/helpers.js
+++ b/webpack/assets/javascripts/react_app/common/helpers.js
@@ -1,7 +1,8 @@
 import { snakeCase, camelCase, debounce } from 'lodash';
 import URI from 'urijs';
 import { translate as __ } from './I18n';
-import { foremanUrl } from '../../foreman_tools';
+//import { foremanUrl } from '../../foreman_tools';
+const foremanUrl = "http://localhost"
 
 /**
  * Our API returns non-ISO8601 dates
```
which leads me to believe jest is having trouble using  anything outside of `webpack/assets/javascripts`, in this case being `foreman_tools`

Unfortunately we can't stub at this level, we can only stub at Katello's entrypoint (APIMiddleware) and not further down the stack where foreman uses foreman_tools. It would be like trying to stub an internal function in an npm package rather than the external function used in the application itself.

I'm not sure the fix yet, but I'll keep looking and wanted to share my investigation so far. Please comment if you have any ideas!

2020-06-10 06:08 UTC, laviro commented
Thanks @johnpmitsch for bringing that up!
I opened https://github.com/theforeman/foreman/pull/7737 to run katello JS tests on travis so we could catch such problems before the PR is merged.

as for the jest issue I moved that `foremanUrl` method into the ReactApp
and than import it from `foreman_tools`

I wonder if we should also create an alias in tests for `foremanWebpack` than we will have access to all of the bundle.js code.

2020-06-10 08:53 UTC, laviro commented
Added the fix also in https://github.com/theforeman/foreman/pull/7739,
in case #7737 doesn't fed merge

2020-06-10 18:18 UTC, johnpmitsch commented
@laviro  It looks like there is actually a circular dependency here:

1. This is the entry point we import `APImiddleware` from:
https://github.com/theforeman/foreman/blob/59606795ec897811de785d655a1461fd42253293/webpack/assets/javascripts/react_app/redux/API/index.js#L7
2. Which imports `get` from `APIRequest`
https://github.com/theforeman/foreman/blob/59606795ec897811de785d655a1461fd42253293/webpack/assets/javascripts/react_app/redux/API/APIMiddleware.js#L2
3.  Which imports `noop` from `common/helpers`
https://github.com/theforeman/foreman/blob/59606795ec897811de785d655a1461fd42253293/webpack/assets/javascripts/react_app/redux/API/APIRequest.js#L3
4. Which imports `foremanUrl` from `foreman_tools`
https://github.com/theforeman/foreman/blob/59606795ec897811de785d655a1461fd42253293/webpack/assets/javascripts/react_app/common/helpers.js#L4
5. Which imports from `foreman_navigation`
https://github.com/theforeman/foreman/blob/59606795ec897811de785d655a1461fd42253293/webpack/assets/javascripts/foreman_tools.js#L12
6. Which imports from `react_app/redux`:
https://github.com/theforeman/foreman/blob/59606795ec897811de785d655a1461fd42253293/webpack/assets/javascripts/foreman_navigation.js#L4
7. Which imports `APIMiddleware` (what we were originally importing) but this time from `middlewares` instead of `API`.
https://github.com/theforeman/foreman/blob/59606795ec897811de785d655a1461fd42253293/webpack/assets/javascripts/react_app/redux/index.js#L8
8. This then calls the same `redux/API/index.js` file we originally called in step 1:
https://github.com/theforeman/foreman/blob/59606795ec897811de785d655a1461fd42253293/webpack/assets/javascripts/react_app/redux/middlewares/index.js#L1
9. Go to step 1

It seems the `redux/middlewares` export of `APIMiddleware` is there for convenience. We do use it in Katello, but can update it if it needs to be removed, I'm not sure how frequently it is used  in other plugins though. I think we will keep seeing this issue if not addressed though, perhaps it even could cause OOM issues or similar, so it's worth fixing permanently IMO.

As far as why we see this only in testing, my understanding is some build systems are better than others at fixing circular dependencies, the way webpack and jest are treating this could be different. This is about as far as my knowledge goes though, but a circular dependency does seem to be the cause of the issue.