Fixes #28725 - prevent image field from disabling on host form
theforeman/foreman pull request #7348
Opened 2020-01-13 07:36 UTC by kgaikwad

While creating a host using compute_profile, the image field under OS tab remain disabled & user won't be able to select image for provisioning. With this commit, it prevents this behavior on host form.

+ adding @shiramax and @apuntamb into the loop

2020-01-14 11:46 UTC, apuntamb approved these changes
It works for Azure compute resource. Tested with `compute profile` and `hostgroup + compute profile` and works fine for both. :)
Let's see what @shiramax  thinks.

2020-01-16 13:51 UTC, shiramax requested changes
@kgaikwad I've tested it, and it works fine, however, I'm not sure it's the best approach here, 
what causes the image to be disabled is that it's disabled in the compute profile, why shouldn't we remove this field from the compute profile?

2020-01-17 09:13 UTC, kgaikwad commented
@shiramax, 
> what causes the image to be disabled is that it's disabled in the compute profile, why shouldn't we remove this field from the compute profile?

Sorry, I didn't get how it is linked to image field from compute profile as this image field comes from compute_resource_vms partial.
In the issue description, it is mentioned that compute_profile selection causing this problem. But this is nothing to do with compute_profile selection. I am able to reproduce this issue without compute-profile selection.

2020-01-21 12:07 UTC, kgaikwad commented
Any updates?

Little more background -  On host form, added event listener for radio (i.e host_provision_method_image in case of image) change but this event won't get trigger when the value didn't get change after click.
That's why gave call to method i.e image_provision_method_selected explicitly.

2020-01-23 10:36 UTC, apuntamb commented
@kgaikwad  @shiramax  Would like to share my observations around the image field getting disabled apart from compute profiles scenario.
On host form -

| Step followed  | Observation |
| ------------------- | -----------------|
| Compute resource selected first time  | Image field **enabled** without selecting Arch/OS  |
| Compute resource selected next time  | Image field **disabled** without selecting Arch/OS |

The image field then continues to remain disabled after the second time.
Let me know if I missed out on any other step to be considered.

2020-01-23 14:13 UTC, shiramax approved these changes

2020-01-23 14:14 UTC, shiramax commented
Thanks, @kgaikwad and @apuntamb !

2020-01-23 14:14 UTC, merged