Fixes #28758 - Editor modal is shown empty
theforeman/foreman pull request #7358
Opened 2020-01-15 14:49 UTC by MariaAga

In report templates if you try to maximize the editor it only shows you its title and not its textarea, now it shows you the full modal that includes both

2020-01-15 15:54 UTC, amirfefer requested changes
Thanks @MariaAga !
It works, though I think the height is too small and doesn't give a fullscreen experience 

original:
![smaller](https://user-images.githubusercontent.com/11807069/72448583-ed6f5880-37bf-11ea-969a-c80823f7e8f5.png)

fullscreen:
![bigger](https://user-images.githubusercontent.com/11807069/72448611-f7915700-37bf-11ea-8c2c-cf51b19d0ede.png)

what do you think?

2020-01-15 16:03 UTC, MariaAga commented
@amirfefer It looks better but I couldn't achieve this height, what did you use?

2020-01-19 14:17 UTC, MariaAga commented
@amirfefer ping

2020-02-24 17:52 UTC, amirfefer reviewed
I added `height` to  `ace_editor_modal` class:
```css
.ace_editor_modal {
  width: 100% !important;
  height: 800vh !important;
}
```

2020-02-25 09:09 UTC, MariaAga commented
Added `height: 80vh !important;` as that's enough, and if the text is too long a scroll is added

2020-02-25 11:27 UTC, amirfefer approved these changes
Thanks @MariaAga  !

2020-02-25 11:28 UTC, merged