Fixes #28846 - PPC64 pxedir location
theforeman/foreman pull request #7381
Opened 2020-01-23 13:15 UTC by lzap

It looks like PXE images for Red Hat systems are stored in a different subdirectory than on Intel. Foreman then tries to find them under wrong URL which leads to 404 when provisioning PPC64 machines.

2020-01-26 12:12 UTC, tbrisker requested changes
just a small typo inline

2020-01-26 12:12 UTC, tbrisker commented on app/models/operatingsystems/coreos.rb
> +  def pxedir(architecture = nil)
```suggestion
  def pxedir(medium_provider = nil)
```

2020-02-10 12:38 UTC, lzap commented
Merged please squash on merge.

2020-02-10 13:28 UTC, tbrisker approved these changes
Thanks @lzap !

2020-02-10 13:28 UTC, merged