Fixes #28861 - SSH key cannot be added when FIPS enabled due to MD5
theforeman/foreman pull request #7391
Opened 2020-01-27 11:23 UTC by stejskalleos

**Description of problem:** 
When FIPS is enabled and customer will try to add SSH key for user, `500 internal server error` appear

**Steps to reproduce**
Steps to Reproduce:
(Enable FIPS)
1. Create new user
2. generate new key
3. Edit user -> SSH Keys -> Add SSH Keys
4. Fill new SSH key & Save

**Actual results:**
500 Internal server error

**Expected results:**
Key added

**Solution:**
Generate ssh key fingerprint with `SHA256`

2020-01-27 11:54 UTC, tbrisker commented
ok to test

2020-01-27 11:56 UTC, tbrisker commented
Please include an explanation of the fix in the commit message if needed, the original bug report can stay in the issue tracker.

2020-01-27 12:02 UTC, ekohl commented
In addition to what @tbrisker said, I'd suggest that the short summary describes the new situation. So `Use sha256 fingerprints for SSH keys`. If there's space, you can add `due to FIPS`. Then in the body you can describe that it uses MD5 in the default fingerprints which isn't allowed in FIPS.

2020-01-27 12:49 UTC, stejskalleos commented
Commit message & PR description updated.

2020-01-29 09:34 UTC, tbrisker requested changes

2020-01-29 09:34 UTC, tbrisker commented on db/migrate/20200127103144_ssh_keys_fingerprints_sha1.rb
> +    SshKey.all.each { |ssh_key| ssh_key.update(fingerprint: SSHKey.sha256_fingerprint(ssh_key.key)) }
You can use `update_column` to only modify the db without triggering callbacks.

2020-01-29 09:34 UTC, tbrisker commented on app/models/ssh_key.rb
> +  before_validation :generate_fingerprint, on: :create
This should still run on update as well, in case a user changes their key we need to update the fingerprint as well.

2020-01-29 15:37 UTC, adamruzicka commented
[test]

2020-01-29 15:40 UTC, adamruzicka commented
[test foreman]

2020-02-04 12:51 UTC, pondrejk approved these changes
checked on patched satellite on fips-enabled rhel7, the key is added to user without error

2020-02-05 09:33 UTC, tbrisker approved these changes
Thanks @stejskalleos !

2020-02-05 09:34 UTC, merged