Fixes #28866 - handle legacy content in router's fallback route
theforeman/foreman pull request #7394
Opened 2020-01-27 19:34 UTC by amirfefer

The fallback route in foreman's react-router handles all routes that aren't included in `/routes`
Currently, it triggers a full page reload (with an ugly hack to keep tracking location ) on every transition, which creates a performance drawback, plus the redux's store is destroyed and created from scratch - makes the store stateless across pages.

This PR demonstrates how we can render a react `Legacy` component which is responsible for fetching and running legacy content (HTML and scripts)

![»Hosts« (3)](https://user-images.githubusercontent.com/11807069/73206812-48079d80-414c-11ea-85ed-8eee2eac54f3.gif)

2020-02-02 18:32 UTC, amirfefer commented
### Test scenario
I've recorded a performance record with this scenario:
 Hosts Page (Starting Point) >> Compute Resouce >> VM1 >> Edit >> Cancel >> VM1 >> Edit 

#### Current
![noLegacyRoute](https://user-images.githubusercontent.com/11807069/73613031-33b71b00-45fa-11ea-985a-16866e98ab47.png)
[download recorded profile](https://github.com/theforeman/foreman/files/4144902/current.zip)

#### With Legacy Component
![withLegacyRoute](https://user-images.githubusercontent.com/11807069/73613113-0f0f7300-45fb-11ea-87da-423df740dd67.png)

[download recorded profile](https://github.com/theforeman/foreman/files/4144900/with-legacy-route.zip)

2020-02-06 11:15 UTC, amirfefer commented
All green :tada:

2020-02-24 16:30 UTC, jeremylenz requested changes
This is awesome @amirfefer, thanks!

When navigating between Foreman pages:
* :white_check_mark: Redux store is persisted
* :white_check_mark: Skeleton shows after debounce time
* :white_check_mark: Performance feels 1000% faster

When switching between Foreman and a plugin (for example, going from a Foreman page to a Katello page):
* :x: Redux store is not persisted;
* :x: looks like the full page is reloaded

When switching between two plugins (example: going from Foreman Tasks page to Subscriptions page)
* :x: Redux store is not persisted
* :white_check_mark: Nav bar is persisted

When navigating within plugins (for example, Subscriptions page to Red Hat Repositories page):
* :white_check_mark: Redux store is persisted, but
* :x: Skeleton is displayed indefinitely.  I can see the completed (200) document request in the dev tools, but it is not rendered to the DOM.
* :x: Console error: 
```
helpers.js:24 Uncaught (in promise) TypeError: Cannot read property 'outerHTML' of null
    at _callee$ (helpers.js:24)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at asyncGeneratorStep (bundle.js:30496)
    at _next (bundle.js:30498)
```

Also, whenever I switch pages using React Router (without a full page reload), the route in the URL bar changes but the page title doesn't change.  Do we use `react-helmet`?  maybe it would be useful here..

Again, nice work!  I'll save my nitpicks and code comments for the next review :yum:

2020-02-25 23:03 UTC, ezr-ondrej commented on webpack/assets/javascripts/react_app/common/MountingService.js
> +    ReactDOM.unmountComponentAtNode(node);
I believe the webcomponents rendering is going to solve unmountig for us, we should just switch to that globally instead.

2020-03-01 16:14 UTC, amirfefer commented
@jeremylenz Thanks for your review!
unfortunately, when switching between plugins a full page reload occurs due to some new js content in the head (same happens with turbolinks)

Issues within plugins are investigated now, probably the reason is multiple react-routers which  #6936  should handle.

2020-03-02 20:51 UTC, jeremylenz reviewed
Okay, added nitpicks etc. below.

2020-03-02 20:51 UTC, jeremylenz commented on webpack/assets/javascripts/foreman_navigation.js
> +        pushUrl(this.getAttribute('href'));
Why create the const and then not use it on lines 20 and 21?

2020-03-02 20:51 UTC, jeremylenz commented on webpack/assets/javascripts/react_app/components/BreadcrumbBar/BreadcrumbBarActions.js
> +export const initBreadcrumbsBar = () => ({ type: BREADCRUMB_BAR_INIT });
The component name is `BreadcrumbBar`.  Prefer renaming this to `initBreadcrumbBar` to remain consistent.

2020-03-02 20:51 UTC, jeremylenz commented on webpack/assets/javascripts/react_app/components/Legacy/BackList.js
> +// Add pathes (regex template) for triggering full page reload
patches? paths?

2020-03-02 20:51 UTC, jeremylenz commented on webpack/assets/javascripts/react_app/components/InnerHTML/index.js
> +  const dispatch = useDispatch();
I don't see anywhere in this file where `dispatch` is used.  No need to import / assign it

2020-03-02 20:51 UTC, jeremylenz commented on webpack/assets/javascripts/react_app/components/InnerHTML/index.js
> +  }, [html, dispatch]);
No need for `dispatch` here either

2020-03-02 20:51 UTC, jeremylenz commented on webpack/assets/javascripts/react_app/components/Legacy/helpers.js
> +const parsingDOM = html => {
`parseDOM` makes more sense to me as a name

2020-03-02 20:51 UTC, jeremylenz commented on webpack/assets/javascripts/react_app/common/MountingService.js
> +export function umountAllComponents() {
```suggestion
export function unmountAllComponents() {
```

2020-03-02 20:51 UTC, jeremylenz commented on webpack/assets/javascripts/react_app/components/Legacy/index.js
> +       an ajax call occours for getting new legacy content is invoked */
```suggestion
       an ajax call occurs for getting new legacy content */
```

2020-03-02 20:51 UTC, jeremylenz commented on webpack/assets/javascripts/react_app/components/Legacy/index.js
> +  }, [location]);
Why not add the other values to the dependency array?

2020-03-02 20:51 UTC, jeremylenz commented on webpack/assets/javascripts/react_app/components/Legacy/index.js
> +  // This was created for memorizing legacy content when the same location is requested
```suggestion
  // This was created for memoizing legacy content when the same location is requested
```

2020-03-02 20:51 UTC, jeremylenz commented on webpack/assets/javascripts/react_app/components/Legacy/index.js
> +  return !reload && referer && <DangerouslyInnerHTML html={content} />;
prefer a blank line here so I don't think the `return` is part of the `useEffect`

2020-03-02 20:51 UTC, jeremylenz commented on webpack/assets/javascripts/react_app/components/Legacy/index.js
> +    reload && window.location.assign(`${pathname}${search}`);
Prefer a single-line `if` statement here

2020-03-04 10:26 UTC, sharvit reviewed
Thanks @amirfefer, I started to review your pr a while ago and stopped because of my injury.
Those are my comments from 2 weeks ago so I am just putting them here and I will give it a full review soon.

2020-03-04 10:26 UTC, sharvit commented on package.json
> +    "dangerously-set-html-content": "^1.0.1",
Should move to the vendor

2020-03-04 10:26 UTC, sharvit commented on webpack/assets/javascripts/foreman_navigation.js
> +
Please remove this empty line

2020-03-04 10:26 UTC, sharvit commented on webpack/assets/javascripts/foreman_navigation.js
> +      }
Isn't `e.preventDefault();` suppose to be inside the `if`?

2020-03-04 10:26 UTC, sharvit commented on webpack/assets/javascripts/foreman_navigation.js
> +export const pushUrl = (url, queryParams) => {
Should we keep the `visit` method (line 37) as is or does it make sense changing it to something like:
```js
export const visit = url => pushUrl(url);
```

2020-03-04 10:26 UTC, sharvit commented on webpack/assets/javascripts/react_app/ReactApp/ReactAppReducer.js
> +  referer: null,
Can you put the `referer` before the `_currentHref`, it looks like the `referer` is private.

2020-03-04 10:26 UTC, sharvit commented on webpack/assets/javascripts/react_app/components/DelayedSkeleton/index.js
> +      <div id="loader">
Why use `id` instead of a `class`?
Notice it means you should not render the `DelayedSkeleton` component twice on the same page.

2020-03-04 10:26 UTC, sharvit commented on webpack/assets/javascripts/react_app/components/DelayedSkeleton/index.js
> +import React, { useState, useEffect } from 'react';
Shouldn't we name this file `DelayedSkeleton/DelayedSkeleton.js` based on our convention?
It always annoys me when I try to find a component lives in and `index.js` file.

2020-03-04 10:26 UTC, sharvit commented on webpack/assets/javascripts/react_app/components/DelayedSkeleton/index.js
> +export default DelayedSkeleton;
The export should be the last line of the file

2020-03-04 10:26 UTC, sharvit commented on webpack/assets/javascripts/react_app/components/InnerHTML/InnerHTML.test.js
> +  "<script>tfm.test() </script><div id='test'> <span> Hello World </span> </div> ";
Would it make sense to create `global.testInnerHtml = jest.fn()`;
And make sure the script actually calls it with the right params?

2020-03-04 10:26 UTC, sharvit commented on webpack/assets/javascripts/react_app/components/InnerHTML/__snapshots__/InnerHTML.test.js.snap
> +<Provider
Can you clean up the `Provider` from the snap?

2020-03-04 10:26 UTC, sharvit commented on webpack/assets/javascripts/react_app/components/DelayedSkeleton/index.js
> +import React, { useState, useEffect } from 'react';
Can you please add a story about the `DelayedSkeleton`?

2020-03-04 10:26 UTC, sharvit commented on webpack/assets/javascripts/react_app/components/InnerHTML/index.js
> +      } else divRef.current.appendChild(parsedHtml);
Can you please explain this logic here?
Not sure I understand the 2 different scenarios.

2020-03-04 10:26 UTC, sharvit commented on webpack/assets/javascripts/react_app/components/InnerHTML/index.js
> +    const newContent = () => {
Should we move it to https://github.com/theforeman/foreman/blob/develop/webpack/assets/javascripts/react_app/common/document.js ?

2020-03-04 10:26 UTC, sharvit commented on webpack/assets/javascripts/react_app/components/InnerHTML/index.js
> +const DangerouslyInnerHTML = ({ html }) => {
Should we add a story or some sort of doc for this component?

2020-03-04 10:26 UTC, sharvit commented on webpack/assets/javascripts/react_app/components/Legacy/BackList.js
> +const blackList = [/\/puppetclasses\/.+\/edit/];
As a plugin developer, shouldn't I suppose to be able to add items to this list?

2020-03-04 10:26 UTC, sharvit commented on webpack/assets/javascripts/react_app/routes/RouterSelector.js
> +export const SelectLastHistoryAction = state => state.router.action;
Can you please add a story to explain about the different selectors?

2020-05-20 08:25 UTC, tbrisker commented
Thanks @amirfefer ! feel free to reopen when you have time.

2020-05-20 08:25 UTC, closed without merging