Fixes #28935 - Add mutations for media
theforeman/foreman pull request #7415
Opened 2020-02-05 14:00 UTC by xprazak2

2020-02-06 17:04 UTC, kamils-iRonin commented on app/graphql/mutations/media/update.rb
> +
I think we need `id` here, maybe `Mutations::UpdateMutation` is a good place to define it?
```suggestion
argument :id, ID, required: true
```

2020-02-06 17:04 UTC, kamils-iRonin commented on test/graphql/mutations/media/update_mutation_test.rb
> +      let(:medium_id) { Foreman::GlobalId.for(medium_id) }
```suggestion
      let(:medium_id) { Foreman::GlobalId.for(medium) }
```

2020-02-06 17:04 UTC, kamils-iRonin commented on test/graphql/mutations/media/update_mutation_test.rb
> +        {
I think `id` is missing

```suggestion
        {
          id: medium_id,
```

2020-02-06 17:04 UTC, kamils-iRonin commented on test/graphql/mutations/media/update_mutation_test.rb
> +            $osFamily: String,
`OsFamilyEnum` is the correct type for `osFamily`

```suggestion
            $osFamily: OsFamilyEnum,
```

2020-02-20 09:33 UTC, shiramax commented on app/graphql/mutations/media/update.rb
> +
:+1:

2020-02-20 10:34 UTC, shiramax requested changes
Looks good to me!
can you please add more negative tests? 
- update a media without id 
- create media without all the required fields
- create media with  invalid valid os family
- create media with a name that is already exists
 
also, what about querying of getting index or show information of specific media.

2020-02-21 14:40 UTC, xprazak2 commented
I added more tests. We already have queries for [index and show](https://github.com/theforeman/foreman/blob/develop/app/graphql/types/query.rb#L86-L87)

2020-02-23 08:30 UTC, shiramax approved these changes

2020-02-23 08:38 UTC, shiramax commented
thanks @xprazak2 ! merging! also thanks @kamils-iRonin  for reviewing!

2020-02-23 08:39 UTC, merged