Fixes #28093 - Wrong host ownership in UserMailNotifications
theforeman/foreman pull request #7422
Opened 2020-02-07 10:56 UTC by emildragu

Wrong list of hosts in "Configuration Management Summary Report" when view_host permission
 is used with filter "owner = current_user"

2020-02-07 11:13 UTC, timogoebel commented on app/mailers/host_mailer.rb
> +    User.current = user
I think this should be done in a block, possibly via `User.as user do ... end` to make sure the user context is switched back.

2020-02-11 00:25 UTC, mmoll commented
ok to test

2020-03-12 14:28 UTC, tbrisker requested changes
Sorry for the slow response here! just a small suggested improvement inline, otherwise looks good to me!

2020-03-12 14:28 UTC, tbrisker commented on app/services/report_importer.rb
> +          Host.authorized_as(user, :view_hosts).find(host.id).present?
```suggestion
          Host.authorized(:view_hosts).find(host.id).present?
```

2020-03-12 14:28 UTC, tbrisker commented on app/mailers/host_mailer.rb
> +      Host::Managed.authorized_as(user, :view_hosts, Host)
Since you are in a user scope, you can use `authorized` instead of `authorized_as` here and below:
```suggestion
      Host::Managed.authorized(:view_hosts)
```

2020-03-25 12:49 UTC, tbrisker approved these changes
Thanks @emildragu ! I'll merge this now and push another PR to improve on it.

2020-03-25 12:49 UTC, merged

2020-03-25 12:51 UTC, tbrisker commented
for the record  - https://github.com/theforeman/foreman/pull/7543