Fixes #28974 - Add mutations for operating systems
theforeman/foreman pull request #7431
Opened 2020-02-11 11:41 UTC by xprazak2

2020-02-26 08:51 UTC, shiramax requested changes
please fix the tests

2020-03-05 07:31 UTC, xprazak2 commented
Tests are green now.

2020-03-09 11:59 UTC, shiramax approved these changes

2020-03-09 12:00 UTC, shiramax commented
thanks @xprazak2 !

2020-03-09 12:00 UTC, merged