Fixes #29292 - move pagination_options to the client
theforeman/foreman pull request #7497
Opened 2020-03-09 16:39 UTC by amirfefer

As it discussed here https://github.com/theforeman/foreman/pull/7139#discussion_r388370680, `pagination_options` can be computed directly in the client

2020-03-10 09:44 UTC, tbrisker requested changes
looks like test failures are related

2020-05-19 07:48 UTC, tbrisker requested changes
test failures are related, looks like we're testing that controllers include the pagination info - probably we need to drop or change these tests.

2020-05-26 14:22 UTC, sharvit requested changes
Thanks @amirfefer, nice addition

2020-05-26 14:22 UTC, sharvit commented on webpack/assets/javascripts/react_app/components/Pagination/PaginationHelper.js
> +export const usePaginationOptions = () => {
Shouldn't this file suppose to be called `PaginationHooks.js`?

2020-08-19 08:17 UTC, tbrisker commented
ping @amirfefer what's the status here?

2020-11-20 01:23 UTC, closed without merging

2020-11-23 15:14 UTC, tbrisker commented
I didn't want to loose this cleanup, opened https://github.com/theforeman/foreman/pull/8152 with fixes to the comments.