Fixes #28363 - remove validation no longer needed because we drop MySQL
theforeman/foreman pull request #7506
Opened 2020-03-11 13:54 UTC by shiramax

2020-03-11 14:55 UTC, tbrisker requested changes
test failures related

2020-03-12 13:47 UTC, tbrisker commented on test/models/shared/taxonomies_base_test.rb
> +
This is blocking tests from running

2020-03-16 07:42 UTC, tbrisker commented
test failure related

2020-03-16 10:51 UTC, tbrisker approved these changes
Thanks @shiramax !

2020-03-16 11:34 UTC, shiramax commented
[test katello]

2020-03-16 14:25 UTC, merged