Fixes #28182 - fixing broken search bar in facts
theforeman/foreman pull request #7554
Opened 2020-03-31 18:23 UTC by amirfefer

In Host -> Facts page the search bar contains `host = $fqdn`, and after cleaning it up and search for another query this happens:
![unspaced-search](https://user-images.githubusercontent.com/11807069/78061390-d9d29780-7395-11ea-8827-40ab0dac7fce.png)

it should also add a separator " and ":
![fixed-search](https://user-images.githubusercontent.com/11807069/78061414-e35bff80-7395-11ea-8c91-2e6efc1c610f.png)

2020-04-05 22:36 UTC, amirfefer commented
- [ ]  Fixing Tests failures

2020-04-05 22:51 UTC, ekohl reviewed
I ran into this bug last Friday so I can confirm it's annoying. However, I wonder if a separate parameter really the correct way. Shouldn't it check if `params[:search]` is not blank? The search may also be a complex expression. Some cases I can think of that might fail, but not sure if they will:

* `name = myfact or name = my_other_fact` should be `(name = myfact or name = my_other_fact) and ...`
* `name = myfact and  fqdn = host.example.com` will result in `name = myfact and  fqdn = host.example.com and fqdn = host.example.com` (note the double space)

It would be good to have test cases for this.

2020-04-15 12:20 UTC, ezr-ondrej requested changes
I believe Ewoud is right and we could simplify this.

2020-04-15 12:20 UTC, ezr-ondrej commented on app/controllers/application_controller.rb
>            params[:search] += query unless params[:search].include? query
As per Ewoud's suggestion, we can do this instead:
```suggestion
          unless params[:search].include? query
            params[:search] += ' and ' unless params[:search].blank?
            params[:search] += query
          end
```

2020-04-21 09:36 UTC, ezr-ondrej commented
@amirfefer ?

2020-05-10 17:22 UTC, amirfefer commented
Thanks @ezr-ondrej , @ekohl ! I've added also a test

2020-05-11 10:47 UTC, ekohl requested changes

2020-05-11 10:47 UTC, ekohl commented on app/controllers/fact_values_controller.rb
> +  end
This appears unused and also reversed the logic.

2020-05-11 13:25 UTC, tbrisker requested changes
Tested, seems to work properly. Just the left-over `has_search_param?` method needs cleaning.

2020-05-13 16:17 UTC, amirfefer commented
thanks @tbrisker , @ekohl !
updated

2020-05-13 16:44 UTC, ekohl approved these changes

2020-05-18 07:48 UTC, tbrisker approved these changes
Thanks @amirfefer !

2020-05-18 07:48 UTC, merged

2020-05-18 07:49 UTC, tbrisker commented
2.1 - 84d0f4967