Fixes #29402 - Add missing gov region for EC2
theforeman/foreman pull request #7585
Opened 2020-04-14 10:55 UTC by apuntamb

With the addition of a new gov region `us-gov-east-1` in AWS, Foreman EC2 doesn't support it due to the hardcoded `GOV_CLOUD_REGION` in the model. 
If the API calls work for gov cloud as well, for example here: `[#describe_regions](https://github.com/theforeman/foreman/blob/develop/app/models/compute_resources/foreman/model/ec2.rb#L82)` then we can remove setting the `self.url` explicitly with hardcoded region.
Still considering it WIP.

2020-05-13 10:54 UTC, shiramax requested changes

2020-05-13 10:54 UTC, shiramax commented on app/models/compute_resources/foreman/model/ec2.rb
> +    attr_accessor   :gov_cloud
I believe this line is not necessary

2020-05-14 07:37 UTC, apuntamb commented on app/models/compute_resources/foreman/model/ec2.rb
> +    attr_accessor   :gov_cloud
done.

2020-05-14 08:24 UTC, shiramax submitted a review, later dismissed

2020-05-18 15:36 UTC, shiramax approved these changes

2020-05-18 15:36 UTC, merged