Update debian.rb to support Ubuntu 20 legacy pxe
theforeman/foreman pull request #7608
Opened 2020-04-23 21:44 UTC by KoffeinKaio

Starting Ubuntu 20.04 LTS the PXE files (linux & initrd.gz) have moved from images to legacy-images
this PR adds an if contition to weather ubuntu major ver is over 20 and changes the pxe path

2020-04-24 08:30 UTC, ekohl requested changes
Could you squash your coommits and also use `Fixes #29612 - ` as a prefix? Our automation uses this and is particularly useful when we cherry pick. This looks like a good candidate for a stable branch.

Other than that it looks good.

2020-04-24 10:05 UTC, KoffeinKaio reviewed
commits squashed

2020-04-24 10:41 UTC, ekohl commented
ok to test

2020-04-24 10:42 UTC, ekohl approved these changes

2020-04-24 13:51 UTC, lzap approved these changes
I wonder if other Ubuntu clones does the same, We require user to set "Ubuntu" anyway for these, do we?

2020-04-24 22:36 UTC, ekohl commented
At least Debian Bullseye (current testing) doesn't: http://ftp.debian.org/debian/dists/bullseye/main/installer-amd64/current/

Katello failures appear unrelated.

@tbrisker looks like a good cherry pick candidate for 2.0 and 1.24.

2020-04-24 23:05 UTC, pmgration commented
Fix works for me using 1.24.2 :+1:

2020-04-25 19:36 UTC, hboetes commented
I just tested the patch and it fixes the problem.
Perhaps this can be written without code repetition with something like this pseudo code:
```
if $version >= 20
$newpath='legacy-'
else
$newpath=''
$url='dists/$release/main/installer-$arch/current/${newpath}images/netboot/' + guess_os + '-installer/$arch'
```

It would also be nice if theforeman would complain about a non-existing file.

2020-04-26 08:12 UTC, tbrisker approved these changes
Thanks @KoffeinKaio and congrats on your first PR in Foreman!

2020-04-26 08:12 UTC, merged

2020-04-26 08:15 UTC, tbrisker commented
cherry-picked to 2.0 as 1a7bd5f4e, 1.24 as c22657282e030b70b8a3c34ed74d2ad09a44c945