Fixes #29655 - Allow hosts for Rails in devel environment
theforeman/foreman pull request #7619
Opened 2020-04-29 15:24 UTC by johnpmitsch

This is to allow all hosts for Rails 6 new Host Authorization feature. https://www.fngtps.com/2019/rails6-blocked-host/

A more proper fix will happen for production and it can be used in the development environment when it is ready, but this is just to unblock things for now.

2020-04-29 15:28 UTC, jlsherrill commented
I think this makes sense to do for now as it unblock developers, is simple, and the production fix is quite a bit more of a complex solution

2020-04-30 11:57 UTC, ekohl commented on config/environments/development.rb
> +  config.hosts.clear
How about:
```suggestion
  config.hosts << SETTINGS[:fqdn]
```

2020-04-30 12:00 UTC, ekohl requested changes
Note that by default rails doesn't bind on 0.0.0.0, that's a thing that puppet-katello_devel does.

Allowing everything does IMHO mask the issue and I'm pretty sure we will need to deal with this before we ship. Stablization is next week so I'm guessing we must deal with the proper solution within days so I don't think we should merge a workaround.

2020-04-30 13:48 UTC, johnpmitsch commented
> Note that by default rails doesn't bind on 0.0.0.0, that's a thing that puppet-katello_devel does.
> 
> Allowing everything does IMHO mask the issue and I'm pretty sure we will need to deal with this before we ship. Stablization is next week so I'm guessing we must deal with the proper solution within days so I don't think we should merge a workaround.

I updated to `SETTINGS[:fqdn]`

I get that any Rails upgrade is a large effort and we can expect issues, but this is a pretty apparent one that prevents starting a server, which is affecting all developers and making it hard to use the latest dev environments. A small issue like this collectively costs us a lot of time as we all have to hunt down workarounds and can't spin up the latest dev environment from staging repos, so are using the outdated stable box and manually upgrading.

Its fine that this happens from time to time, but the priority should be getting things unblocked so developers can use the latest environment. This is a new feature in Rails 6 and considering it wasn't there in Rails 5, I don't see a huge impact in merging this devel-only fix for now.

2020-04-30 13:49 UTC, ekohl submitted a review, later dismissed
Untested, but :+1: if you can say it fixes it for you.

2020-04-30 13:50 UTC, ekohl commented
> I get that any Rails upgrade is a large effort and we can expect issues, but this is a pretty apparent one that prevents starting a server, which is affecting all developers and making it hard to use the latest dev environments.

Only the ones that are not on localhost. I guess the developers working on Rails 6 don't use that which is why it didn't surface.

2020-04-30 13:58 UTC, mmoll commented
@johnpmitsch please rebase :)

2020-04-30 14:01 UTC, johnpmitsch commented
> @johnpmitsch please rebase :)

Done!

2020-04-30 16:25 UTC, johnpmitsch commented
@ekohl @mmoll look good to merge?

2020-04-30 16:27 UTC, mmoll approved these changes

2020-04-30 16:27 UTC, merged

2020-04-30 16:28 UTC, mmoll commented
merged, thanks @johnpmitsch!

2020-05-05 12:19 UTC, lzap commented
I did not experience any changes for my case but would you mind opening a thread on discourse informing other devs if there are actions need to be taken? Thanks.

2020-05-05 13:17 UTC, johnpmitsch commented
> I did not experience any changes for my case but would you mind opening a thread on discourse informing other devs if there are actions need to be taken? Thanks.

@lzap This change was discussed [in this thread](https://community.theforeman.org/t/katello-devel-environment-is-broken-with-workaround/18490) and there shouldn't be any manual changes needed now with this fix. Is there anything in particular that you feel needs to be discussed?