Fix/28214 2
theforeman/foreman pull request #7684
Opened 2020-05-22 06:48 UTC by ares

2020-05-22 06:48 UTC, ares commented
please see the original discussion at https://github.com/theforeman/foreman/pull/7418, I was unable to reopen that one, assigning @tbrisker for the review

2020-08-02 15:00 UTC, tbrisker requested changes

2020-08-02 15:00 UTC, tbrisker commented on app/views/template_inputs/_form.html.erb
> +      <%= selectable_f f, :value_type, [[_('Plain'), 'plain'], [_("Search"), 'search'], [_('Date'), 'date']], {}, {'data-item': f.index || f.object.id, class: "select-value-type #{@template.locked? &
```suggestion
      <%= selectable_f f, :value_type, [[_('Plain'), 'plain'], [_("Search"), 'search'], [_('Date'), 'date']], {}, {'data-item': f.index || f.object.id, class: "select-value-type #{@template.locked? && 'without_select2'}", onchange: "tfm.templateInputs.inputValueOnchange(this)", disabled: @template.locked? } %>
```

2020-08-02 15:00 UTC, tbrisker commented on app/views/template_inputs/_form.html.erb
> +      <%= selectable_f f, :resource_type, Permission.resources_with_translations, {}, {wrapper_class: "#{hide_resource_type_input(f.object)} form-group #{@template.locked? && 'without_select2'} resou
```suggestion
      <%= selectable_f f, :resource_type, Permission.resources_with_translations, {}, {wrapper_class: "#{hide_resource_type_input(f.object)} form-group resource-type-#{f.index || f.object.id}", class: "#{@template.locked? && 'without_select2'}", disabled: @template.locked? } %>
```

2020-08-19 08:24 UTC, tbrisker commented
what's the status here @ares ?

2020-08-25 15:28 UTC, ares commented
my applogies, accepted your suggestions, hopefully that does not disqualify you from merging :-)

2020-10-27 09:32 UTC, ares commented
rebased to run tests again, simple patch to be merged

2020-10-27 10:38 UTC, tbrisker requested changes
Looks like you resolved the proposed changes but didn't apply them, maybe they got lost in the rebase?

2020-11-11 09:02 UTC, ares commented
sorry, commited both suggestions, not sure where it got lost

2020-11-11 13:24 UTC, tbrisker approved these changes
Thanks @ares ! tested, works as expected.

2020-11-11 13:26 UTC, merged

2020-11-11 13:26 UTC, tbrisker commented
and fixed the commit message on merge for you

2020-11-15 14:52 UTC, tbrisker commented
2.3 - 11ac0615d