Fixes #29901 - Lock default Job templates
theforeman/foreman pull request #7691
Opened 2020-05-25 08:44 UTC by stejskalleos

2020-05-27 12:49 UTC, ares requested changes
I think this PR can be closed and seeding fixed in all plugins that seed the templates, see the inline comment for more details

2020-05-27 12:49 UTC, ares commented on app/models/template.rb
>      handle_lock_on_import(options)
note that this line already contains the logic, the problem is the argument name

2020-05-27 12:49 UTC, ares commented on app/models/template.rb
> +    self.locked = options[:locked] unless options[:locked].nil?
the plugin should use `:lock`, not `:locked`, then it would be handled by the line below I believe

2020-05-28 08:40 UTC, stejskalleos commented
Plugin updates PR: https://github.com/oamg/foreman_leapp/pull/95 & https://github.com/theforeman/foreman_remote_execution/pull/500

2020-05-28 08:40 UTC, closed without merging