Fixes #29853 - Add DSL docs for OS
theforeman/foreman pull request #7730
Opened 2020-06-08 15:06 UTC by ofedoren

2020-06-10 13:25 UTC, shiramax requested changes

2020-06-10 13:25 UTC, shiramax commented on app/models/operatingsystem.rb
> +    property :media_url, Array, desc: 'URLs of associated media'
[6] pry(main)> Operatingsystem.first.media_url
NoMethodError: undefined method `media_url' for #<Redhat:0x00000000154cac38>

Is it possible that media_url doesn't exist?

2020-06-11 10:44 UTC, ofedoren commented on app/models/operatingsystem.rb
> +    property :media_url, Array, desc: 'URLs of associated media'
You're right. Probably this is a leftover, because I couldn't find this method to be defined anywhere...

2020-06-11 10:44 UTC, ofedoren commented
@shiramax, updated.

2020-06-11 10:54 UTC, shiramax approved these changes

2020-06-14 05:52 UTC, merged