Fixes #29851 - Add DSL docs for NIC
theforeman/foreman pull request #7732
Opened 2020-06-08 16:48 UTC by ofedoren

For the reviewer: I'm not quite sure what should be in the description for `link` property. Any advices?

2020-06-21 08:25 UTC, shiramax requested changes

2020-06-21 08:25 UTC, shiramax commented on app/models/nic/base.rb
> +      property :managed?, one_of: [true, false], desc: 'Returns true if the type is Nic::Managed, false otherwise'
'Returns True if external services such as DNS, DHCP and TFTP are configured for this interface'

2020-06-21 08:25 UTC, shiramax commented on app/models/nic/base.rb
> +      property :bond?, one_of: [true, false], desc: 'Returns true if the type is Nic::Bond, false otherwise'
'Returns true if the type of the interface is Bond, false otherwise'

2020-06-21 08:25 UTC, shiramax commented on app/models/nic/base.rb
> +      property :bridge?, one_of: [true, false], desc: 'Returns true if the type is Nic::Bridge, false otherwise'
'Returns true if the type of the interface is Bridge, false otherwise'

2020-06-21 08:25 UTC, shiramax commented on app/models/nic/base.rb
> +      property :bmc?, one_of: [true, false], desc: 'Returns true if the type is Nic::BMC, false otherwise'
the same..

2020-06-21 08:25 UTC, shiramax commented on app/models/nic/base.rb
> +      property :link, one_of: [true, false], desc: 'TODO: not sure'
I think: 
'Returns true if the Interface is up"

2020-06-22 11:00 UTC, ofedoren commented
Thanks, @shiramax! Updated.

2020-06-22 11:43 UTC, shiramax approved these changes

2020-06-22 11:44 UTC, merged