Fixes #29507 - Add puma-status for reporting
theforeman/foreman pull request #7735
Opened 2020-06-09 13:45 UTC by ehelms

Replaces https://github.com/theforeman/foreman/pull/7578 with additional commit to ensure puma is 4.3.5 or higher.

2020-06-09 13:45 UTC, ehelms commented
@tbrisker this would be nice to have in 2.1 for helping with debug

2020-06-09 13:54 UTC, tbrisker commented
tests are failing due to gemfile conflicts. Also, I assume this needs SELinux changes and packaging as well?

2020-06-09 15:44 UTC, ehelms commented
Packaging PR -- https://github.com/theforeman/foreman-packaging/pull/5031

I don't know if this requires SELinux changes, no issues were reported when testing. @lzap do you forsee any being needed?

2020-06-10 08:30 UTC, lzap commented
The only problem I can see is that the socket will have `tmp_t` (or similar) file label. If there's anything confined that needs to connect to it, it will require a rule to connect/read/write to `tmp_t`. Ideally this should have been a separate label.

But I believe `pumactl` runs unconfined (command line utility), so no issues there.

2020-06-13 00:22 UTC, sthirugn commented
Looks good, thank you for this PR.

2020-06-16 00:21 UTC, ehelms commented
Turns out I misread the puma repository structure and the 4.3.5 branch is missing the commit we need:

2020-09-16 08:34 UTC, ares commented
@ehelms this needs a rebase now, could you also please share an update about puma? There was some release already, so is this still blocked?

2020-09-21 13:13 UTC, ehelms commented
We never got a Puma 4 release with the needed security fix we implemented thus this has sat stagnant. A move to Puma 5 will enable this. Feel free to leave it open with that caveat or close it to be re-investigated at a later date.

2020-09-21 13:15 UTC, ekohl commented
Since https://projects.theforeman.org/issues/30490 `/run/foreman` should no longer be world readable so the security concern may no longer be valid.

2020-10-21 09:18 UTC, ezr-ondrej commented
@ehelms can we close this as Ewoud mentioned? I believe he's right and the concern is no longer valid.

2020-10-21 09:56 UTC, ekohl commented
> @ehelms can we close this as Ewoud mentioned? I believe he's right and the concern is no longer valid.

This is not what I meant this morning. I think that the blocker is no longer valid which means we can implement this. The feature itself is still valid.

2020-10-21 13:01 UTC, ehelms commented
Yep, this is valid and will be do-able with Puma 5 which we are actively working on.

2020-10-21 13:05 UTC, ekohl commented
> Yep, this is valid and will be do-able with Puma 5 which we are actively working on.

My argument was that the socket will live in `/run/foreman`. Currently that is mode 0700 so the security concern is no longer and issue so I don't see why we can't do this with Puma 4. With Puma 5 we can even better guarantee the security though.

2020-11-25 09:45 UTC, ekohl commented
ping @ehelms

2020-12-02 12:36 UTC, ekohl commented
https://github.com/theforeman/foreman/pull/8171 updates to Puma 5.1 which includes the fixes needed.

2020-12-02 21:55 UTC, ehelms commented
Intending to pick this up next sprint when I work on updating to Puma 5.1 across the board.

2021-02-17 09:46 UTC, ezr-ondrej commented
What is the plan for this PR? :)

2021-02-18 15:01 UTC, ehelms commented
Rebased and cleaned this up. Also opened  packaging PR to consume this https://github.com/theforeman/foreman/pull/7735

2021-02-18 15:07 UTC, ekohl commented
I think you meant to link https://github.com/theforeman/foreman-packaging/pull/6322. Is there also a related PR for Debian to maintain parity?

2021-02-18 16:32 UTC, ehelms commented
Deb link https://github.com/theforeman/foreman-packaging/pull/6323

2021-02-22 14:32 UTC, ekohl requested changes

2021-02-22 14:32 UTC, ekohl commented on config/puma/production.rb
> +state_permission 0640
Looks like Rubocop is unhappy here

2021-04-15 11:44 UTC, ekohl commented
Looks like @ares wrote a tutorial for this: https://community.theforeman.org/t/puma-status-monitoring-not-working-at-the-moment/23154

2021-04-15 14:29 UTC, ehelms commented
I updated the Rubocop issue and rebased. Also updates the packaging PRs:

 * https://github.com/theforeman/foreman-packaging/pull/6322
 * https://github.com/theforeman/foreman-packaging/pull/6323

2021-04-20 10:03 UTC, ekohl approved these changes
This change looks correct. Probably good to get packaging changes approved too before merging.

2021-04-26 17:27 UTC, evgeni commented
RPM changes are good, Debian I need to look at, but I see no hurdles.

2021-04-27 09:24 UTC, merged