Fixes #30110 - upgrade vendor to v4.7.0
theforeman/foreman pull request #7744
Opened 2020-06-11 14:20 UTC by sharvit

Packaging PR: https://github.com/theforeman/foreman-packaging/pull/5394

2020-06-16 13:28 UTC, tbrisker reviewed
This works with the related pr in foreman-js. let's get that released and packaged.

2020-06-16 14:56 UTC, sharvit commented
Thanks @tbrisker, updated to use v4.7.1

2020-06-16 14:58 UTC, tbrisker commented
@sharvit thanks, please update packaging pr as well

2020-06-21 16:17 UTC, tbrisker requested changes

2020-06-21 16:17 UTC, tbrisker commented on package.json
> -    "@babel/plugin-transform-modules-amd": "7.9.0",
Following our discussion on IRC, let's keep these pinning here as well to make sure npm doesn't try to be too clever (and also the `"babel-plugin-dynamic-import-node": "2.3.0"` below).

2020-06-21 16:17 UTC, tbrisker commented on package.json
> +    "@theforeman/vendor-dev": "^4.7.1",
We've just updated packaging to 4.8.0, let's update here as well.

2020-06-22 06:31 UTC, sharvit commented
It is using 4.8.0 now

2020-06-22 06:50 UTC, tbrisker commented on package.json
> -    "@babel/plugin-transform-modules-amd": "7.9.0",
Still needs addressing

2020-06-22 07:10 UTC, tbrisker approved these changes
Let's give it a try and see if it builds. Thanks @sharvit !

2020-06-22 07:10 UTC, merged