Fixes #29849 - Add DSL docs for hosts
theforeman/foreman pull request #7746
Opened 2020-06-15 12:48 UTC by ofedoren

Unfortunately, apipie-dsl doesn't have a way to merge concerns' docs into the main class. So, for now I suggest have documentation in separate classes with some kind of note for usage.

2020-06-21 09:42 UTC, shiramax requested changes

2020-06-21 09:42 UTC, shiramax commented on app/models/host/managed.rb
> +    property :architecture, String, desc: 'Returns a string representing the architecture of the host (e.g. "x86_64") or an empty string if no architecture is assigned (unmanaged host)'
It returns Architecture obj and not a string.

2020-06-21 09:42 UTC, shiramax commented on app/models/host/managed.rb
> +    property :interfaces, Array, desc: 'Returns an array of all host interfaces objects'
array_of: ['Nic::Managed']

2020-06-21 09:42 UTC, shiramax commented on app/models/host/managed.rb
> +    property :medium, String, desc: 'Returns installation medium\'s name associated with the host'
it returns Medium object.

2020-06-22 10:39 UTC, ofedoren commented
Thanks, @shiramax! Updated.

2020-06-22 11:44 UTC, shiramax commented
[test foreman]

2020-06-22 12:33 UTC, shiramax commented
@ofedoren I think the tests are related.

2020-06-22 14:56 UTC, ofedoren commented
@shiramax, thank you! I didn't notice one change that somehow migrated into this PR, should be fixed now.

2020-06-22 15:06 UTC, shiramax approved these changes

2020-06-22 15:06 UTC, merged

2020-06-22 15:07 UTC, shiramax commented
thanks @ofedoren !