Fixes #30185 - Change console files to be compatible to python3
theforeman/foreman pull request #7766
Opened 2020-06-22 13:21 UTC by shiramax

2020-06-22 13:54 UTC, ekohl commented
I wonder if we should put in the effort to unbundle [websockify](https://github.com/novnc/websockify) and use it as an external dependency.

2020-06-22 14:12 UTC, shiramax commented
@ekohl, do you know what's the reason to not do it in the first place?

2020-06-22 14:28 UTC, ekohl commented
Historical reasons I guess. That part of the codebase has been mostly untouched for years now and the vendoring is even older. When speaking to @ares in a related conversation he didn't even know it was an external project and assumed someone wrote it specifically for Foreman. I created https://projects.theforeman.org/issues/29539 and https://community.theforeman.org/t/consolidating-the-console/11215 spoke about the refactor even a step further.

In theory it would be:
* Check whether Websockify 0.8.0 is sufficient (which is in EPEL, Debian 10 and Ubuntu 18.04) or if we need 0.9.0 (https://bugzilla.redhat.com/show_bug.cgi?id=1628636 / https://bugzilla.redhat.com/show_bug.cgi?id=1816608)
* Modify the Foreman to search in $PATH (using `Foreman::Util::which`)
https://github.com/theforeman/foreman/blob/231761f7c62bd82e02a33ba184ccee102f9b9e57/lib/ws_proxy.rb#L67-L69
* Remove vendored code
* Change packaging to depend on python(3)-websockify
* Check whether SELinux is still happy (@lzap indicated this might be an issue and was willing to help)

Of course in practice you may find more things, but the general outline is pretty straight forward.

cdd8424fb4d31b390531cc1a1d74fb3820bae31a says it updated to 1.6.1 but this version doesn't exist. It may refer to 0.6.1 in which case 0.8.0 is actually an upgrade. In the past websockify lived in the noVNC repository but that also doesn't have a 1.6.1 version. Maybe @lzap remembers.

I probably don't have time for this, but I'll gladly help anyone who picks this up.

2020-06-22 21:56 UTC, shiramax commented
@ekohl I can have a look, should I drop this one?

2020-06-23 09:14 UTC, ekohl commented
@shiramax let's give it a try. If it doesn't work, we can circle back to this.

2020-07-14 10:56 UTC, shiramax commented
@ekohl I decided to re-open this issue, because I don't have time at the moment to unbundle websockify and I think it would be best to add this PR for now.
I do plan to check websockify unbundle, but I don't have the time at the moment, and I don't know when I will have the time.

2020-07-22 09:48 UTC, ekohl requested changes

2020-07-22 09:48 UTC, ekohl commented on extras/noVNC/websockify/websocketproxy.py
> +from .websocket import WebSocketRequestHandler, WebSocketServer, ssl
This does break if you execute this file directly:
```
$ ./extras/noVNC/websockify/websocketproxy.py --help
Traceback (most recent call last):
  File "./extras/noVNC/websockify/websocketproxy.py", line 20, in <module>
    from .websocket import WebSocketRequestHandler, WebSocketServer, ssl
ImportError: attempted relative import with no known parent package
```

However, we don't use that so we don't really care.

I would like to keep the patch small:
```suggestion
from . import websocket
```

Then you can revert the other changes in this file

2020-07-22 09:48 UTC, ekohl commented on extras/noVNC/websockify/__init__.py
> +from .websocketproxy import websockify_init
I'd prefer to keep the API the same and only change the bare minimum.
```suggestion
from .websocket import *
from .websocketproxy import *
```

2020-07-27 08:51 UTC, ekohl commented on extras/noVNC/websockify/__init__.py
> +from .websocketproxy import *
Mind keeping the line ending?

2020-07-27 09:44 UTC, shiramax commented on extras/noVNC/websockify/__init__.py
> +from .websocketproxy import *
done :)

2020-07-27 09:48 UTC, ekohl approved these changes
I don't think we need CI to complete since there's no coverage for this anyway. I manually verified it using `websockify.py --help` and that worked.

2020-07-27 09:48 UTC, merged