Fixes #30339 - isolate LookupKey tests
theforeman/foreman pull request #7808
Opened 2020-07-08 09:13 UTC by ezr-ondrej

Gets rid of the PuppetclassLookupKey dependency for testing a LookupKey.
Removes some tests as they are irrelevant to LookupKey itself.

2020-07-09 13:20 UTC, ezr-ondrej commented
[test foreman]

2020-07-29 08:39 UTC, kgaikwad requested changes
@ezr-ondrej, added two small inline comments.

2020-07-29 08:39 UTC, kgaikwad commented on test/models/lookup_key_test.rb
> +    test 'elemet separation' do
```suggestion
    test 'element separation' do
```
just a small typo

2020-07-29 08:39 UTC, kgaikwad commented on test/models/lookup_keys/puppetclass_lookup_key_test.rb
> +  test "default_value is only validated if omit is true" do
```suggestion
  test "default_value is only validated if omit is false" do
```
Please correct me if I am missing anything.

2020-07-29 11:38 UTC, ezr-ondrej commented
Right, thanks @kgaikwad ! I've accepted your suggestions :) :+1:

2020-07-29 15:12 UTC, kgaikwad approved these changes
Codewise looks good to me :+1: 
I guess failing katello test is irrelevant to pull-request changes.

@shiramax, do you have any additional comments?

2020-07-30 12:15 UTC, shiramax approved these changes
@ezr-ondrej looks good!

2020-07-30 12:16 UTC, shiramax commented
thanks @ezr-ondrej and @kgaikwad for the review :)

2020-07-30 12:16 UTC, merged