Fixes #30466 - trigger toasts from API middleware
theforeman/foreman pull request #7841
Opened 2020-07-21 18:09 UTC by laviro

2020-07-21 18:13 UTC, laviro commented on webpack/assets/javascripts/react_app/redux/API/APIRequest.js
> +
Added some spaces for readability

2020-07-21 18:14 UTC, laviro commented on webpack/assets/javascripts/react_app/redux/actions/toasts/index.js
> +  const key = toast.key || uuidV1();
it was one annoying `uuid` ( especially in tests )

2020-07-21 22:58 UTC, amirfefer requested changes
Thanks @laviro ! a great addition to our API stack  :+1: 
can you please extend `APIRequest`  test for including this new feature?

2020-07-21 22:58 UTC, amirfefer commented on webpack/assets/javascripts/react_app/redux/actions/common/forms.js
> +        successToast,
does it make sense to add an error toast?

2020-07-21 22:58 UTC, amirfefer commented on webpack/assets/javascripts/react_app/redux/API/APIActions.js
> + * @param { String } payload.successToast a succes toast will be triggered with this message after API success.
can you add these new props to our documentation?

2020-07-22 07:45 UTC, laviro commented
Thanks @amirfefer !
In the last commit:
- Added tests
- Added section to storybook
- Added also `errorToast` to `forms.js`
- Changed it into a function so the toast can contain info from the server, e.g:
```js
dispatch(
  get({
    key: MY_SPECIAL_KEY,
    url,
    toastError: error => `Oh no! Something went wrong while submiting the form, the server returned the following error: ${error}`,
    toastSuccess: response => `Yay! task: ${response.taskID} was successfully created.`
  })
);
```

2020-08-02 20:34 UTC, amirfefer approved these changes
Thanks @laviro ! 
works well

ready for merge after stabilization

2020-08-25 19:29 UTC, amirfefer commented
Merging, Thanks @laviro !

2020-08-25 19:29 UTC, merged