fixes #30499 - update latest versions of fedora, ruby and node
theforeman/foreman pull request #7855
Opened 2020-07-27 18:00 UTC by ohadlevy

Also removed a warning which is visible with ruby 2.7 / rails 6, by using
```
bundle exec rails app:update:bin
```

2020-07-27 18:03 UTC, ekohl reviewed
Can you elaborate on why spring is removed? No objection, but I'd like to understand.

2020-07-27 18:07 UTC, ohadlevy commented
> Can you elaborate on why spring is removed? No objection, but I'd like to understand.

Its the outcome of running ```bundle exec rails app:update:bin``` some more context at https://stackoverflow.com/questions/36538089/what-is-the-purpose-of-railsupdatebin-rake-task

2020-07-27 18:36 UTC, ohadlevy commented
is the test failure known? 
```
Expected {:name=>"_ForemanSelectedhosts", :value=>"%5B1%5D", :path=>"/", :domain=>"127.0.0.1", :expires=>nil, :secure=>false} to be empty. (Minitest::Assertion)
/home/jenkins/workspace/test_develop_pr_core/database/postgresql-integrations/ruby/2.5/slave/fast/test/integration/host_js_test.rb:401    
```

2020-07-27 22:56 UTC, ekohl commented
https://github.com/rails/rails/commit/a6c958b3a7d851d6609188dd4faa5f98fa23f381 suggests this should be moved to https://github.com/theforeman/foreman/blob/develop/config/boot.rb

2020-07-28 07:01 UTC, ohadlevy commented
thanks, updated.

2020-07-29 08:09 UTC, ohadlevy commented
[test katello]

2020-07-30 11:31 UTC, ekohl commented
> thanks, updated.

I don't see any changes to `config/boot.rb`.

2020-07-30 11:36 UTC, ohadlevy commented
> > thanks, updated.
> 
> I don't see any changes to `config/boot.rb`.

looking at the latest version of https://github.com/rails/rails/blob/6-0-stable/railties/lib/rails/generators/rails/app/templates/config/boot.rb.tt I dont think its actually needed anymore?

2020-07-30 11:47 UTC, ekohl commented
Odd, in master it is there: https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/config/boot.rb.tt

https://github.com/rails/rails/commit/a6c958b3a7d851d6609188dd4faa5f98fa23f381 doesn't appear to be in the 6.0 branch, nor any spring. The fact we have it here since 4b836b6295dd2e928ee452a514fef51432ce2b73 suggests we haven't been in line with upstream for ages. I'm not sure if removal is wise.

2020-07-30 12:02 UTC, ohadlevy commented
> Odd, in master it is there: https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/config/boot.rb.tt
> 
> [rails/rails@a6c958b](https://github.com/rails/rails/commit/a6c958b3a7d851d6609188dd4faa5f98fa23f381) doesn't appear to be in the 6.0 branch, nor any spring. The fact we have it here since [4b836b6](https://github.com/theforeman/foreman/commit/4b836b6295dd2e928ee452a514fef51432ce2b73) suggests we haven't been in line with upstream for ages. I'm not sure if removal is wise.

OK, I've added it back, the code from masters seems solid, so I wouldn't worry about that (one less task for 6.1?)

2020-07-30 12:07 UTC, ekohl commented on config/boot.rb
> +load File.expand_path("../bin/spring", __dir__)
```suggestion
begin
  load File.expand_path("../bin/spring", __dir__)
```

2020-07-30 12:10 UTC, ekohl submitted a review, later dismissed
@adamruzicka any concerns?

2020-07-30 12:56 UTC, ohadlevy commented
I've reverted the spring changes, retesting the container...

2020-07-30 13:24 UTC, ohadlevy commented
ok, reverting the spring change is breaking the containers all together:
```
bundler: failed to load command: bin/rails (bin/rails)
LoadError: cannot load such file -- bundler
  /home/foreman/bin/spring:8:in `require'
  /home/foreman/bin/spring:8:in `<top (required)>'
  bin/rails:3:in `load'
  bin/rails:3:in `<top (required)>'
foreman_app_1
```
I assume this can be reproduce with ruby 2.7 now?

2020-07-30 13:32 UTC, ekohl commented
You should not ship `bin/spring` in a container since it's development only. Spring itself is only listed in `bundler.d/development.rb`. We don't ship it our packages either. Then it doesn't exist and isn't loaded.

2020-07-30 13:41 UTC, ohadlevy commented
> You should not ship `bin/spring` in a container since it's development only. Spring itself is only listed in `bundler.d/development.rb`. We don't ship it our packages either. Then it doesn't exist and isn't loaded.

I would prefer not to delete files (and not follow rails for that matter), how about this?

2020-07-30 13:42 UTC, ekohl requested changes
You should really just drop `bin/spring` when building. That means it'll simply not load it. Probably around here:
https://github.com/theforeman/foreman/blob/c4c097fab09588a886da113e0c598120644f5d34/Dockerfile#L47-L49

2020-07-30 13:43 UTC, ohadlevy commented
ok, leave the patch or just it in the dockerfile?

2020-07-30 13:48 UTC, ohadlevy commented
@ekohl thanks, Ijust ended up reverting all of the spring changes and deleted it from the container.

how doesnt this break production env from source?

2020-07-30 14:04 UTC, ekohl commented
Normally the spring gem is unavailable because it's listed here:
https://github.com/theforeman/foreman/blob/c4c097fab09588a886da113e0c598120644f5d34/bundler.d/development.rb#L21

In our packages we simply remove the file `bundler.d/development.rb` so we know it's not present. This means `Spring` can never be loaded. All the scripts should gracefully fall back maybe the spring binstub isn't that graceful. Dropping the whole binstub feels appropriate since the gem isn't present either.

2020-07-30 14:36 UTC, ohadlevy commented
btw, the above fix doesnt work either, bin/rails still reference it...
```
bundler: failed to load command: bin/rails (bin/rails)
LoadError: cannot load such file -- bundler
  /home/foreman/bin/spring:8:in `require'
  /home/foreman/bin/spring:8:in `<top (required)>'
  bin/rails:3:in `load'
  bin/rails:3:in `<top (required)>'
```
feels like I should reintroduce my earlier patch?

2020-07-30 14:39 UTC, ohadlevy commented
sorry, PBKAC, I can confirm this patch works.

2020-07-30 14:45 UTC, ekohl approved these changes

2020-08-02 14:50 UTC, merged

2020-08-02 14:50 UTC, tbrisker commented
Thanks @ohadlevy and @ekohl !