Fixes #30288 - replace CPU/Cores/socket input to react comp
theforeman/foreman pull request #7865
Opened 2020-07-29 07:13 UTC by yifatmakias

2020-07-29 08:59 UTC, MariaAga requested changes
Thanks Yifat! Snapshots should be replaced and can you add tests for the warning and error states of the component?
Also I think there shouldn't be space between the warning and the cpu input, and instead there should be space between the warning and the next input, you can maybe add a class to the cpu input and add/remove margins

2020-07-29 08:59 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/CPUCoresInput/cpuCoresInput.scss
>  }
Can you use the colors from this file?
https://github.com/theforeman/foreman/blob/develop/webpack/assets/javascripts/react_app/common/colors.scss

2020-07-29 08:59 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/common/forms/NumericInput.js
> +      ClassName={inputClassName}
should be `className`

2020-07-29 08:59 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/CPUCoresInput/CPUCoresInput.js
> +        <Col className="col-md-4">
Should be `<Col md={2}>` (or 4)

2020-07-29 08:59 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/CPUCoresInput/CPUCoresInput.js
> +            onChange={v => handleChange(v)}
Can be just  `onChange={handleChange}`

2020-07-29 08:59 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/CPUCoresInput/CPUCoresInput.js
> +        <Col className="col-md-4">
Also I think for the warnings it makes sense to take the rest of the Row so can you change 4 to 10?

2020-07-29 09:58 UTC, yifatmakias commented
@MariaAga Thanks for the review.
I fixed the tests and all the comments.
I still need to add more tests and to fix the double space between the input to the alert message.

2020-08-02 20:53 UTC, amirfefer commented
foreman tests failures look related

2020-08-03 07:17 UTC, yifatmakias commented
@amirfefer Yes I know, I am working on fixing it.

2020-08-05 07:07 UTC, MariaAga submitted a review, later dismissed
Looks like the tests are working now :tada:

2020-08-05 07:07 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/CPUCoresInput/__tests__/CPUCoresInput.test.js
> +};
Can you merge this into 1 object? 
`fixtures ={ 'should..default...':{},  'should..warning...':{}, 'should..error...':{}}`

2020-08-05 12:47 UTC, yifatmakias commented
[test foreman]

2020-08-10 12:24 UTC, yifatmakias commented
[test katello]

2020-08-12 06:29 UTC, yifatmakias commented
This PR depends on other PR:
https://github.com/theforeman/foreman/pull/7896

2020-09-02 06:31 UTC, yifatmakias commented
[test katello]

2020-09-03 08:36 UTC, yifatmakias commented
[test katello]

2020-09-03 09:56 UTC, yifatmakias commented
[test katello]

2020-10-13 08:43 UTC, yifatmakias commented
[test katello]

2020-11-22 09:34 UTC, yifatmakias commented
[test katello]

2020-11-22 11:18 UTC, yifatmakias commented
[test katello]

2020-12-21 08:12 UTC, yifatmakias commented
[test katello]

2020-12-21 08:12 UTC, yifatmakias commented
[test foreman]

2021-01-27 12:07 UTC, xprazak2 approved these changes, later dismissed
Works well on libvirt, I haven't tested ovirt or vmware.

2021-02-25 13:24 UTC, shiramax requested changes
Thanks @yifatmakias 

I see some strange behavior here, every time I increase the socket, the cores also increase and vice versa, 
it shouldn't be like that, the cores and socket are completely different attributes.

2021-03-02 11:47 UTC, yifatmakias commented
@shiramax You are definitely right I will figure out the problem and fix this.
Thanks!

2021-04-06 07:31 UTC, yifatmakias commented
[test katello]

2021-04-08 11:18 UTC, ezr-ondrej approved these changes
This works and code looks good.
Thanks a lot, loving this :heart: :+1:

2021-04-08 11:19 UTC, ezr-ondrej commented
@MariaAga, @shiramax were your concerns addressed?

2021-04-08 11:21 UTC, shiramax approved these changes

2021-04-08 11:21 UTC, shiramax commented
@ezr-ondrej yes. thanks

2021-04-08 11:31 UTC, merged