Fixes #30620 - Fix CR creation from the API
theforeman/foreman pull request #7894
Opened 2020-08-11 10:13 UTC by shiramax

2020-08-11 10:27 UTC, ezr-ondrej approved these changes
I guess we could rather refactor the CRs to have the same way of doing this, but this is good fix to get in fast :+1:

2020-08-11 10:32 UTC, ezr-ondrej requested changes

2020-08-11 10:32 UTC, ezr-ondrej commented on app/controllers/api/v2/compute_resources_controller.rb
> +          if compute_resource_params["provider"] == "Ovirt"
Actually this should compare the `downcase`d version with 'ovirt', just to be sure.

2020-08-11 10:53 UTC, ezr-ondrej approved these changes
Great, thanks @shiramax :+1:
WWFJ.

2020-08-11 12:18 UTC, ezr-ondrej commented
I think I've already seen the katello errors, so I think we are fine, but I'd like to be sure.
@tbrisker do you know what's happening?

2020-08-12 07:28 UTC, tbrisker approved these changes
Perhaps we should refactor the conversion to uuid, but let's first fix this bug.

2020-08-12 07:29 UTC, merged

2020-08-12 07:30 UTC, tbrisker commented
2.2 - ba93142f0
2.1 - 8b2141b20