Refs #30029 - moved initialization of allowed tags
theforeman/foreman pull request #8010
Opened 2020-09-23 09:55 UTC by lzap

Telemetry was broken causing nil exception until Rails booted up and
initializer added some allowed tags. This fixes it. I have suspicion
that it broke some rake task too. Quick merge appreciated, sorry about
that.

2020-09-23 10:09 UTC, ezr-ondrej requested changes
In that case, the method is changing it's behaviour and I believe we should name it accordingly.

2020-09-23 10:09 UTC, ezr-ondrej commented on lib/foreman/telemetry.rb
>      def allowed_tags(labels)
```suggestion
    def add_allowed_tags(labels)
```

2020-09-23 15:31 UTC, lzap commented
Sure, updated the initializer as well.

2020-09-26 12:06 UTC, ezr-ondrej commented
[test foreman][test upgrade][test katello]

2020-09-26 12:08 UTC, ezr-ondrej approved these changes
LGTM :+1: 
WWFJ

2020-09-26 13:18 UTC, merged

2020-09-26 13:18 UTC, ezr-ondrej commented
Thanks @lzap