Fixes #30957 - Refactor External IPAM plugin Integration
theforeman/foreman pull request #8041
Opened 2020-10-02 11:46 UTC by grizzthedj

The External IPAM plugin(https://github.com/grizzthedj/smart_proxy_ipam) implementation has been refactored to separate the API from provider implementations, to increase stability, and make it easier to add new IPAM providers. 

As such, the data contract between Foreman and this plugin has been changed/simplified, and this patch addresses this. 

As an example, the `get_next_ip` method now returns `"100.55.55.3"` instead of `{"data": "100.55.55.3"}`. 

Netbox has also been added as a new IPAM provider, and is fully functional. This will be released in coming days as smart_proxy_ipam version 0.1.0.

2020-10-02 12:02 UTC, ekohl commented
> Netbox has also been added as a new IPAM provider, and is fully functional. This will be released in coming days as smart_proxy_ipam version 0.1.0.

I have been thinking about including it in smart-proxy core. At least the generic plugin, even if there is no provider. Providers can then be implemented in specific gems. This would be in line with the policy where all functionality that's in Foreman core is also in Smart Proxy core.

With the refactored base, I think we're much closer to being able to do that.

2020-10-07 08:44 UTC, ezr-ondrej commented
@lzap do you wanna take this?

2020-10-13 11:34 UTC, lzap requested changes
I missed this PR, sorry! Thanks for headsup @ezr-ondrej 

I think this is a change for the worse, root elements are good. Can you actually do the opposite? Review all API calls and make sure they include "data" element, strip it out in this class so callers don't need to know.

2020-10-13 11:34 UTC, lzap commented on app/models/subnet.rb
> +        errors.add :externalipam_group, _('Group not found in the configured External IPAM instance')
Just checking, no change except line order?

2020-10-13 11:34 UTC, lzap commented on lib/proxy_api/external_ipam.rb
> +    #     "2001:db8:abcd:12::1"  (IPv6)
This is actually good practice, having root element enables you to extend the API without breaking clients! I highly suggest the opposite - to review all calls to actually have a root element called "data" ;-)

I mentioned this in your smart proxy PR the other day.

2020-10-13 11:34 UTC, lzap commented on lib/proxy_api/external_ipam.rb
> +    #     {"error": "Group not found in External IPAM"}
Returning empty elements like arrays or hashes is also a good practice I would not be getting rid of. Exactly vice versa!

2020-10-13 11:34 UTC, lzap commented on lib/proxy_api/external_ipam.rb
> +      process(response)
This method should actually expect the "data" element and clean it out for caller. The code was better before.

2020-11-02 13:45 UTC, lzap submitted a review, later dismissed
This is okay, but the title is a bit misleading. This is nowhere near to "refactoring", this is a documentation update with some error handling improvements. Can you reword the title a bit?

2020-11-02 14:20 UTC, lzap approved these changes
All of this are documentation updates or slight changes in error handling. Can we merge this for 2.3 @tbrisker please?

2020-11-02 15:53 UTC, tbrisker commented
ok to test
Let's first merge it to nightly post-branching then consider pulling it into 2.3-stable

2020-11-02 15:55 UTC, tbrisker commented
[test foreman]

2020-11-02 16:25 UTC, lzap commented
I haven't realized we have branched already. To explain, @grizzthedj preferred this in 2.3 because of a big refactoring of the plugin which could be released in sync with 2.3. If we can do it, that would be great. Thanks!

2020-11-02 16:46 UTC, tbrisker commented
@lzap we are currently in the branching process so I'd rather not merge until we're done with it, afterward we can merge and cherry-pick to 2.3-stable. ping me in a day or two and we'll take care of it.

2020-11-06 08:06 UTC, merged

2020-11-06 08:06 UTC, lzap commented
Thank you, 2.3 was branched off, merged for 2.4.

2020-11-06 13:32 UTC, grizzthedj commented
@lzap Ideally I would like to get it in 2.3, this way people can start using the Netbox integration sooner.

2020-11-08 14:56 UTC, tbrisker commented
2.3 - cee4bf4b2ebbc9f29eefb834940ed18166e3668f