Fixes #31071 - expose created_at for report template
theforeman/foreman pull request #8075
Opened 2020-10-13 17:29 UTC by ranjan

Also, we can write macro like this

 def host_created_at(host)
      host&.created_at
 end

let me know which is better, unjail or writing a macro

2020-10-13 19:42 UTC, ofedoren requested changes
Thanks, @ranjan! But could you please also add a description of this into [properties](https://github.com/theforeman/foreman/blob/d2977968bd3fac08045d515d2dbbd5e506c62a92/app/models/host/managed.rb#L107) even though it's pretty straightforward?

2020-10-15 16:51 UTC, ranjan commented
> Thanks, @ranjan! But could you please also add a description of this into [properties](https://github.com/theforeman/foreman/blob/d2977968bd3fac08045d515d2dbbd5e506c62a92/app/models/host/managed.rb#L107) even though it's pretty straightforward?

Thanks @ofedoren, I didn't notice apipie doc. Update PR

2020-10-19 08:44 UTC, ofedoren approved these changes
LGTM, thanks, @ranjan!

2020-10-19 13:31 UTC, lzap approved these changes
Thank you.

2020-10-19 13:31 UTC, merged