Fixes #31081 - Global Registration - interface for REX
theforeman/foreman pull request #8107
Opened 2020-10-27 09:25 UTC by stejskalleos

With new parameter 'remote_execution_interface', users
can specify host's primary interface for remote execution.

**How to test**
* Host with multiple interfaces
* Run:
```
curl --user admin:changeme -X GET "https://foreman.example.com/register?remote_execution_interface=INTERFACE"
```

2020-10-28 15:57 UTC, ares requested changes
Not tested yet, however few comments related to the code and current test failures.

2020-10-28 15:57 UTC, ares commented on app/controllers/api/v2/registration_controller.rb
> +            remote_execution_interface
this should be called only if rex plugin is enabled, otherwise it fails (like in tests)

2020-10-28 15:57 UTC, ares commented on app/controllers/concerns/foreman/controller/registration.rb
> +    interfaces.each { |int| int.execution = int.identifier == params['remote_execution_interface'] }
pls add parenthesis

```
int.execution = (int.identifier == params['remote_execution_interface'])
```

to make it more readable

2020-10-28 15:57 UTC, ares commented on app/views/unattended/provisioning_templates/registration/global_registration.erb
> +       <%= "--data \"remote_execution_interface=#{@remote_execution_interface}\"" if @remote_execution_interface -%>
I'd use `@remote_execution_interface.present?`, same below, otherwise the data is added always, since the text field is empty string, which is truthy

2020-10-29 19:06 UTC, ares commented
Requires a rebase now, it will also require a rebase after #8104

2020-11-03 07:09 UTC, stejskalleos commented
I'm closing the issue, `remote_execution_interface` should be extended from the Remote Execution Plugin.

2020-11-03 07:09 UTC, closed without merging