Fixes #31363 - dual stack IPv4/6 network for PXE boot
theforeman/foreman pull request #8145
Opened 2020-11-21 15:15 UTC by ronnybremer

The template snippet kickstart_kernel_options has been modified to allow for PXE provisioning in a dual stack environment. In the past, the snippet would throw an error and the PXE operation would fail if both an IPv4 and IPv6 network are attached to the host to be provisioned.
This change will prefer IPv4 over IPv6 when both are configured and still allow for v4 only and v6 only operation.

2020-11-23 08:56 UTC, lzap requested changes
Hello, thanks for the patch however there was a ton of manual testing involved. I can only accept a change for this if there is a new test that renders with IPv4 host, IPv6 host and then dual-stack host. This could be challenging to implement if you are unfamiliar with our testing codebase, so I did this for you.

This patch can be replaced by this one that does what you suggest + adds those tests: https://github.com/theforeman/foreman/pull/8149

However even if we merge this, dualstack is icing on a thin ice - we don't test these real-world scenario. You can run into issues.

2020-11-23 09:09 UTC, ronnybremer commented
Hi Lukas, thank you for taking a look at this and converting it into a more sustainable version. You are right, I had no idea about the test scenarios involved but it makes a lot of sense.
Regarding the dual stack, all our systems are dual stacked so without that patch we cannot provision any host with both IPv4 and IPv6 addresses. You can only assign a v4 and v6 address to an interface in the host configuration if both networks are selected, and then the template breaks.

To get your right, I will close this PR as you combined it into #8149?

2020-11-23 13:57 UTC, lzap commented
> Regarding the dual stack, all our systems are dual stacked so without that patch we cannot provision any host with both IPv4 and IPv6 addresses. You can only assign a v4 and v6 address to an interface in the host configuration if both networks are selected, and then the template breaks.

I understand, but some things in Foreman are designed without dualstack in mind, for example MTU is defined on Subnet rather than NIC. Therefore if you attempt to create provisioning NIC with IPv4 and IPv6 subnets with different MTUs its a problem. Currently we error out in the provisioning template. Usually the priority is the question - which one should Foreman priorize? Which one should be used to actually do the provisioning?

We'd appreciate feedback and further testing on dual-stack.

> To get your right, I will close this PR as you combined it into #8149?

Yeah, I think I closed it for now. But subscribe and if the patch does not get through in here you may want to rebase on top of it and try again with a better solution.

@ekohl you are probably interested in this one.

2020-11-23 15:35 UTC, ronnybremer commented
> I understand, but some things in Foreman are designed without dualstack in mind, for example MTU is defined on Subnet rather than NIC. Therefore if you attempt to create provisioning NIC with IPv4 and IPv6 subnets with different MTUs its a problem. Currently we error out in the provisioning template. Usually the priority is the question - which one should Foreman priorize? Which one should be used to actually do the provisioning?

I got this from the comments I received so and yes, there probably will still be a few loose ends. Regarding priority, I think it is good to error out on different MTU sizes for v4 and v6 subnets, as this is a configuration mistake by the admin. To be honest, I like the option to configure the MUT on the subnet, as you want to make sure all your hosts are as identical as possible when it comes to MTU sizes on the same subnet. And since it's layer 2 the layer 3 protocol should not make any difference.

> We'd appreciate feedback and further testing on dual-stack.
I will continue to point out issues I find.

> Yeah, I think I closed it for now. But subscribe and if the patch does not get through in here you may want to rebase on top of it and try again with a better solution.

I will close this one tomorrow and keep an eye out for yours. Thank you!

2020-11-24 07:16 UTC, closed without merging

2020-11-24 11:37 UTC, ekohl commented
FYI: I do think this is a very good change (and I already had issues with the initial error implementation).

If MTUs differ then you can choose to pick one, let the OS handle it or error out if that particular case is detected. Error out sounds good but ideally this would actually show up prior to provisioning (on saving the form, setting build mode to true, etc).

2020-11-24 12:09 UTC, ronnybremer commented
Thank you Edwoud. I hope this will be a start to make Foreman more dual stack ready.