Fixes #29292 - move paginatin_options to the client
theforeman/foreman pull request #8152
Opened 2020-11-23 15:13 UTC by tbrisker

2020-11-23 15:15 UTC, tbrisker commented
Please squash on merge and see GH-7497 for previous comments.

2020-11-24 08:21 UTC, tbrisker commented
test failures are all intermittent and unrelated.

2020-11-30 11:37 UTC, amirfefer requested changes
Thanks @tbrisker , Tested and works well! 
Though katello needs an update as well - https://github.com/Katello/katello/blob/a046c3b1ce8ff2ef5cc1da6f35b8f0cd02bcbfce/webpack/components/Table/TableWrapper.js#L6

2020-11-30 12:31 UTC, tbrisker commented
Good find @amirfefer ! Opened https://github.com/Katello/katello/pull/9052 to fix it in katello. Next step might be to move it into the Pagination component itself so consumers don't need to care about it, but let's first get this change in.

2020-11-30 18:37 UTC, tbrisker commented on webpack/assets/javascripts/react_app/routes/Audits/AuditsPage/components/AuditsTable.js
> -import { usePaginationOptions } from '../../../../Root/Context/ForemanContext';
Just realized we don't actually need to pass this into the component, as it already defaults to it.

2020-12-01 12:58 UTC, tbrisker commented
@amirfefer can you take another look? We'll need to merge katello one right after this one. Looks like the reason it is needed in katello is that they use patternfly 4 pagination which expects the options in a bit different manner.

2020-12-02 18:02 UTC, amirfefer approved these changes
Thanks @tbrisker :+1: 
 works well

2020-12-02 18:03 UTC, merged