Fixes #31383 - Add report template for CVEs
theforeman/foreman pull request #8154
Opened 2020-11-24 15:39 UTC by xprazak2

A new report template that shows vulnerabilities
detected during an OVAL scan.

Needs https://github.com/theforeman/foreman_openscap/pull/458

2020-11-24 15:39 UTC, xprazak2 commented on app/views/unattended/report_templates/host_-_vulnerabilities.erb
> +- plugin: foreman_openscap
It would probably be good to constrain this by version.

2020-12-09 09:18 UTC, ares commented
works nicely, let's wait for the foreman_openscap release with the patches, but ready to merge afterwards

2021-04-22 13:58 UTC, ares commented
still works fine, note for me: before merge double check the macro name hasn't changed

2021-04-28 09:14 UTC, ares requested changes
few details

2021-04-28 09:14 UTC, ares commented on app/views/unattended/report_templates/host_-_vulnerabilities.erb
> +
please avoid empty lines, it would break the final CSV (or other format)

2021-04-28 09:14 UTC, ares commented on app/views/unattended/report_templates/host_-_vulnerabilities.erb
> +
here to, no new line please

2021-04-28 09:14 UTC, ares commented on app/views/unattended/report_templates/host_-_vulnerabilities.erb
> +<%- load_hosts(includes: [:cves]).each_record do |host| -%>
one of the stories asked for hosts filter, could you please also add it here? just define a new input of search type and use it in `load_hosts` macro as `search: input('Hosts filter')`

2021-04-30 09:59 UTC, xprazak2 commented
Updated, no longer blocked.

2021-05-03 14:41 UTC, ares approved these changes
Thanks @xprazak2, merging!

2021-05-03 14:41 UTC, merged

2021-05-05 08:34 UTC, ezr-ondrej commented
@xprazak2 would you mind demoing it? :)