Fixes #31440 - adding snippet_if_exists to nochroot block
theforeman/foreman pull request #8175
Opened 2020-12-03 13:43 UTC by domitea

Adding call of macro snippet_if_exists for better logging in nochroot block of kickstart_default template.

2020-12-03 15:46 UTC, lzap commented
Nice, can you add this after TTY change (the next two lines) so user actually see what's going on?

Also you need to regenerate snapshot template test fixtures after the change.

    RAILS_ENV=test bundle exec rake snapshots:generate

2020-12-04 08:50 UTC, domitea commented
@lzap Added line moved two lines below (after TTY change) and fixtures regenerated. Looks good for you?

2020-12-18 11:13 UTC, ares requested changes
one tiny thing, then good to merge I believe

2020-12-18 11:13 UTC, ares commented on app/views/unattended/provisioning_templates/provision/kickstart_default.erb
> +<%= snippet_if_exists(template_name + " custom postnochroot") %>
if you add `-` to `%>` it won't even affect the snapshot, it wouldn't be adding extra new line

2020-12-18 14:41 UTC, domitea commented
@ares PR updated

2021-01-08 10:08 UTC, ares approved these changes
Thanks @domitea, merging

2021-01-08 10:08 UTC, merged

2021-01-08 11:26 UTC, lzap commented
Sorry for the delay, I just started with post-break GH backlog.