Fixes #31595 - Timeseries Area chart in React
theforeman/foreman pull request #8237
Opened 2021-01-07 21:18 UTC by ezr-ondrej

Implements area chart, previously implemented by `flot_chart` in React.

2021-02-23 19:14 UTC, amirfefer requested changes
Thanks @ezr-ondre!j 👍 

I left a few comments, mostly nits.
Could you please add a storybook and some tests for this chart? there is no other use for this, and a story would be a great way to verify it.

2021-02-23 19:14 UTC, amirfefer commented on webpack/assets/javascripts/services/charts/AreaChartService.js
> +    throw new Error('xAxisDataLabel is missing for timeseries area graph');
wouldn't throwing a warning be safer?

2021-02-23 19:14 UTC, amirfefer commented on webpack/assets/javascripts/services/charts/AreaChartService.js
> +  } else if (config === 'timeseries' && !xAxisDataLabel) {
`xAxisDataLabel` has a default value, it can't be undefined, no?

2021-02-23 19:14 UTC, amirfefer commented on webpack/assets/javascripts/services/charts/AreaChartService.js
> +    );
how about make it a bit simpler? for increasing readability
Something like
```js
const datesInit = data[0].slice(1).map(epochSecs => new Date(epochSecs * 1000))
chartConfig.data.columns[0] = [xAxisDataLabel].concat(formatedDattes)
```

2021-02-23 19:14 UTC, amirfefer commented on webpack/assets/javascripts/services/charts/ChartService.consts.js
> +    pattern: ['#0088ce', '#ec7a08', '#3f9c35', '#005c66', '#f9d67a', '#703fec'],
good catch :)

2021-02-27 18:09 UTC, ezr-ondrej commented on webpack/assets/javascripts/services/charts/AreaChartService.js
> +  } else if (config === 'timeseries' && !xAxisDataLabel) {
we could get the undef from the caller, but it would be quite dumb from the caller, so we probably don't need to worry about that :thinking:

2021-02-27 18:54 UTC, ezr-ondrej commented
I've rebased, added test for the service and chart to the storybook.
The component just takes props, passes them to the service and push the result to C3, so I guess we don't need to test that :thinking:

2021-03-16 22:19 UTC, ezr-ondrej commented
[test upgrade]

2021-03-16 22:20 UTC, ezr-ondrej commented
[test katello]

2021-03-22 22:17 UTC, ezr-ondrej commented
Adding tag as demo worthy not to forget to demo the statistics plugin that uses this.

2021-05-05 18:15 UTC, amirfefer commented
[test foreman]

2021-05-05 19:59 UTC, amirfefer approved these changes
Thanks, @ezr-ondrej, tested on storybook and works well 👍 
Overall I think these PF3 charts are outdated and the `ChartService` helper adds a redundant complexity.  I'll raise this issue and the alternative PF4 charts (finally, a maintained [library](https://formidable.com/open-source/victory/) than c3) to the next UI group meeting.

2021-05-05 19:59 UTC, merged