Fixes: #31585 iPXE ping gateway and name server
theforeman/foreman pull request #8240
Opened 2021-01-08 14:53 UTC by jcpunk

Attempt to ping critical network resources. In theory when everything is working this should be transparent to the users. If not, this will clearly identify what went wrong.

2021-01-11 14:30 UTC, lzap commented
I am sorry I messed up. It must be either

    echo ${netX/gateway}

or

    show netX/gateway

The first print just the IP address, the second shows more networking info however setting name must be passed not variable with `${}` syntax. Can you fix this? Sorry about that, my bad.

2021-01-11 14:31 UTC, lzap requested changes
Other than that, looks great. For `ping` command keep it as is, that is correct.

2021-01-11 14:32 UTC, rplevka commented
Just for the record, here's the documentation of the `show` command usage:
https://ipxe.org/cmd/show

2021-01-11 14:42 UTC, jcpunk commented
I think I've got it sorted.

2021-01-13 09:45 UTC, lzap commented
Sorry, this is the last time. It only prints the IP without context, can we add little bit text around? Also when `ping` is not available, the error might be misleading. Here is my final suggestion:

```
echo Gateway: ${netX/gateway}
ping --count 1 ${netX/gateway} || echo Ping to gateway failed or ping command not available
echo DNS: ${netX/dns}
ping --count 1 ${netX/dns} || echo Ping to dns failed or ping command not available
```

2021-01-13 15:04 UTC, jcpunk commented
Makes sense to me, new patches pushed up.

2021-01-15 17:19 UTC, lzap approved these changes
Thanks for the patience, merging!

2021-01-15 17:21 UTC, lzap commented
For the record, redmine issue check was not executed all the rest is green. I don't have admin permissions to merge, so either @tbrisker can merge this on Sunday or I will retrigger tests on Monday. :-)

2021-01-15 17:32 UTC, lzap commented
Whatever, it's weekend and I am out for beer from tap! [test foreman] or was it [test core] not sure.

2021-01-17 09:39 UTC, tbrisker commented
Thanks @jcpunk and @lzap ! merging, not sure why the redmine check failed to run.

2021-01-17 09:39 UTC, merged