Fixes #31790 - update version for deprecation warning
theforeman/foreman pull request #8303
Opened 2021-02-02 14:41 UTC by upadhyeammit

Updating the version of deprecation warning to 2.5.

2021-02-02 14:43 UTC, upadhyeammit commented
@lzap I was checking original https://github.com/theforeman/foreman/pull/6465 and as per that we were suppose to remove deprecation block of code. As I see we are still having that code, I think we should update the version in deprecation warning?

2021-02-03 11:38 UTC, lzap commented
Please do this:

```diff
diff --git a/app/models/concerns/orchestration/dhcp.rb b/app/models/concerns/orchestration/dhcp.rb
index dd77081ef..34a3e9bb4 100644
--- a/app/models/concerns/orchestration/dhcp.rb
+++ b/app/models/concerns/orchestration/dhcp.rb
@@ -92,14 +92,7 @@ module Orchestration::DHCP
       # we no longer convert the boot server to IPv4 - smart proxy modules are required to do so if they don't support hostname
       bs
     else
-      begin
-        Foreman::Deprecation.deprecation_warning('1.25', "DHCP proxy does not report dhcp_filename_* capability and reverse DNS search in Foreman will be removed.")
-        ip = NicIpResolver.new(:nic => self).to_ip_address(bs) if bs.present?
-        return ip unless ip.nil?
-        failure _("Unable to determine the host's boot server. The DHCP smart proxy failed to provide this information and this subnet is not provided with TFTP services.")
-      rescue => e
-        failure _("failed to detect boot server: %s") % e, e
-      end
+      failure _("Unable to determine boot server. The DHCP smart proxy doesn't provide dhcp_filename capability or failed to provide this information.")
     end
   end
 ```

We should now error out if boot server can't be detected. @ekohl ?

2021-02-03 11:45 UTC, ekohl commented
Yes, 1.25 turned into 2.0. Since develop is now 2.5, that has long passed and it's safe to make it a hard error.

2021-02-03 14:23 UTC, upadhyeammit commented
@lzap changes pushed, request to check. Thank you!

2021-02-03 14:59 UTC, lzap approved these changes, later dismissed
The will do it, thanks.

2021-02-03 15:14 UTC, ekohl commented on app/models/concerns/orchestration/dhcp.rb
> +      failure _("Unable to determine boot server. The DHCP smart proxy doesn't provide dhcp_filename capability or failed to provide this information.")
I would consider moving this to just below `return unless tftp?` so the method becomes:
```ruby
return unless tftp?

unless subnet.dhcp.has_capability?(:DHCP, :dhcp_filename_hostname)
  failure ...
end

tftp.bootServer || URI.parse(subnet.tftp.url).host
```

For simplicity I left out the comments, but those can certainly help.

2021-02-04 11:23 UTC, ekohl commented on app/models/concerns/orchestration/dhcp.rb
>      # only smart proxies with V2 API are supported
Does this comment belong to `unless subnet.dhcp.has_capability?(:DHCP, :dhcp_filename_hostname)`?

2021-02-04 11:23 UTC, ekohl commented on app/models/concerns/orchestration/dhcp.rb
> +    # first try to ask our IPv4 TFTP server for its boot server
Does this comment help? I'm not sure it really clarifies things for anyone reading this to know that in the past we did a (IP ->) DNS -> IP conversion. Today it's just passing an entry to the Smart Proxy and the Smart Proxy is responsible for any conversion if needed. That's why we have the capability check.

2021-02-05 10:49 UTC, ekohl reviewed
Code wise :+1: but I'd rephrase the commit message to explain what the patch actually does.

2021-02-05 15:43 UTC, ekohl commented
I don't think this is really delegating it. We did that previously already but had a fallback. Also know that you don't have to fit it into a single line. https://chris.beams.io/posts/git-commit/#separate describes that you can actually write a body and I always encourage that when it makes sense.

So in this case I'd write something like:
```
Fixes #31790 - always delegate bootserver IP resolution to smart proxy

In 60c03b6a2e92c432ee66f2b27da634954c1b646c (reverse) DNS search for TFTP
server (bootServer) was delegated to the Smart Proxy if was supported, as
signaled via the dhcp_filename_hostname capability. At the same time, in
Foreman 2.0, the fallback support was deprecated. This drops the compatibility
code.
```

Context for code changes is important and really helps others understand them. It can also help yourself in the future when you do look back.

2021-02-09 15:39 UTC, lzap commented
Relevant errors, thanks @upadhyeammit for looking into this :-)

2021-02-25 09:46 UTC, lzap commented
Failures.

@ekohl I am just wondering, we have made the change for ISC DHCP ourselves, but I guess devs of other DHCP servers haven't noticed this. I am wondering if we should provide some sane default fallback mechanism for DHCP implementations which don't report none of the two capabilities.

2021-02-25 09:55 UTC, lzap commented on app/models/concerns/orchestration/dhcp.rb
>      end
I don't think this is correct, this is too strict.

I believe we should just file a warning into log if none of the `dhcp_filename_ipv4` and `dhcp_filename_hostname` are reported and that's it. We can't do anything about this and foreman should attempt to perform the orchestration. If it fails it's up to the DHCP owner to fix the component.

We can probably be verbose in the warning: _DHCP proxy does not report dhcp_filename_ipv4 or dhcp_filename_hostname capability. Foreman will pass boot server XXX as-is, the request might fail._

2021-03-19 14:41 UTC, lzap requested changes
Other than that I am good.

2021-03-19 14:41 UTC, lzap commented on app/models/concerns/orchestration/dhcp.rb
>      end
You have `XXX` in the string, store the bootserver (or TFTP Smart Proxy URL) in a variable and use it, then return it.

While you will be editing, can you add one more warning? When tftp.bootServer is nil, also warn:

"Using TFTP Smart Proxy hostname as the boot server name: #{boot_server}"

Thanks!

2021-03-30 17:39 UTC, lzap commented
You've suffered enough, the change you are looking for is:

```ruby
diff --git a/test/models/orchestration/dhcp_test.rb b/test/models/orchestration/dhcp_test.rb
index 6ba290965..e85ff864a 100644
--- a/test/models/orchestration/dhcp_test.rb
+++ b/test/models/orchestration/dhcp_test.rb
@@ -87,7 +87,7 @@ class DhcpOrchestrationTest < ActiveSupport::TestCase
   end

   test "provision interface DHCP records should contain default filename/next-server attributes for IPv4 tftp proxy" do
-    ProxyAPI::TFTP.any_instance.expects(:bootServer).returns('192.168.1.1')
+    ProxyAPI::TFTP.any_instance.expects(:bootServer).returns('192.168.1.1').twice
     subnet = FactoryBot.build(:subnet_ipv4, :dhcp, :tftp)
     h = as_admin do
       FactoryBot.create(:host, :with_dhcp_orchestration, :with_tftp_dual_stack_orchestration, :subnet => subnet)
@@ -98,7 +98,7 @@ class DhcpOrchestrationTest < ActiveSupport::TestCase
   end

   test "provision interface DHCP records should contain PXELinux BIOS filename/next-server attributes for IPv4 tftp proxy" do
-    ProxyAPI::TFTP.any_instance.expects(:bootServer).returns('192.168.1.1')
+    ProxyAPI::TFTP.any_instance.expects(:bootServer).returns('192.168.1.1').twice
     subnet = FactoryBot.build(:subnet_ipv4, :dhcp, :tftp)
     h = as_admin do
       FactoryBot.create(:host, :with_dhcp_orchestration, :with_tftp_dual_stack_orchestration, :subnet => subnet, :pxe_loader => 'PXELinux BIOS')
```

With that we are good, thanks for patience.

2021-04-22 07:53 UTC, upadhyeammit commented
@lzap request to review and maybe merge if we are good on this! thank you!

2021-04-22 08:27 UTC, lzap approved these changes
Thank you for the patience.

2021-04-22 08:27 UTC, merged