Fixes #32009 - removes flot_pie_chart
theforeman/foreman pull request #8366
Opened 2021-03-03 21:17 UTC by ezr-ondrej

This has been deprecated in 4ff6f0a1f0b8c6227f91e6b2bcd5c33e00b22a18 and
had a better solution in React for quite a long time now. We don't want
to support flot charts anymore and this one is first to go.

2021-03-08 14:52 UTC, tbrisker commented
[test katello] doesn't look related, but just to make sure

2021-03-08 15:07 UTC, tbrisker requested changes
missed one function, otherwise 💯

2021-03-08 15:07 UTC, tbrisker commented on app/assets/javascripts/charts.js
> -      search_on_click(event, item);
You can also drop this function

2021-03-08 21:27 UTC, ezr-ondrej commented on app/assets/javascripts/charts.js
> -      search_on_click(event, item);
Dropped :boom:

2021-03-09 11:44 UTC, tbrisker approved these changes
Good riddance, thanks @ezr-ondrej !

2021-03-09 11:44 UTC, merged