Fixes #32345 - Provide non-DB model methods for FactParser
theforeman/foreman pull request #8451
Opened 2021-04-19 10:52 UTC by ekohl

As a preparation for removel of the DB model methods, there should be an alternative for DB model methods (Architecture, Domain, Environment & Model) while also deprecating the DB model methods.

Currently it doesn't have the deprecations and no code has been modified to use the new methods, but it's to split off some part of https://github.com/theforeman/foreman/pull/8449 to make that PR smaller.

2021-04-19 10:59 UTC, ekohl commented on app/services/fact_parser.rb
> +  def hostgroup_name
@ofedoren suggested this in the related PR:
```suggestion
  def hostgroup_title
```

I'm not sure which is best, but it shouldn't be lost.

2021-04-19 13:55 UTC, ekohl commented on app/services/fact_parser.rb
> +    Domain.unscoped.where(:name => name).first_or_create if name.present?
Prior discussion: https://github.com/theforeman/foreman/pull/8449#discussion_r614895291

tl;dr: unscoped is a risk, but it was in the Puppet fact parser where I copied it from. [foreman_ansible](https://github.com/theforeman/foreman_ansible/blob/5eec05f645eae1b1cde9de2179f4cf5208873ae3/app/services/foreman_ansible/fact_parser.rb#L28-L32) doesn't use unscoped. There may be more out there.

2021-04-23 07:01 UTC, lzap requested changes
It should be really "title" because "name" is confusing.

Discovery does work with this change, no need to patch it. Other than that I am good.

2021-04-23 07:01 UTC, lzap commented on app/services/fact_parser.rb
> +    Domain.unscoped.where(:name => name).first_or_create if name.present?
Yes this is a long-standing issue (also for discovery). New hosts are even assigned organization and location via foreman_organization administer setting. I think the correct solution would be a boolean flag for each resource (domain, subnet) named "allow discovery of hosts via facts". Users would need to explicitly enable or disable those which are whitelisted.

2021-04-23 07:01 UTC, lzap commented on app/services/fact_parser.rb
> +    Environment.unscoped.where(:name => name).first_or_create
Nitpick: You can use new hash syntax.

2021-04-23 07:01 UTC, lzap commented on app/services/fact_parser.rb
> +  def hostgroup_name
Well title seems better fit for me.

2021-05-31 09:45 UTC, lzap commented
The Ansible patch is RTM, let me know once you want me to re-review this.

2021-09-01 01:23 UTC, closed without merging