Fixes #32264 - Fix bug in vmware disk size field input
theforeman/foreman pull request #8477
Opened 2021-04-28 11:24 UTC by yifatmakias

The library that was used in NumericInput react component created a bug in the vmware disk size field input.
So I replaced it to the library that was used before.

2021-04-28 13:10 UTC, yifatmakias commented
[test foreman]

2021-04-29 16:35 UTC, eLvErDe commented
Thanks a lot, this bug is annoying as hell !
Btw, am I the only one getting ActiveRecord::RecordNotFound when trying an ESX VM with 2.4.0 or did I missed another VMWare related PR ?

Thanks

2021-04-29 22:26 UTC, ezr-ondrej requested changes
It makes me sad :panda_face: to use two libraries for almost the same input :(
I'd rather make them more aligned. Can we just pass the parser from https://github.com/theforeman/foreman/blob/c03c4a44a8c7891aeb470a2fde3f486199299177/webpack/assets/javascripts/react_app/components/hosts/storage/vmware/controller/disk/index.js#L92 same as we do for `MemmoryAllocationInput`?

2021-04-29 22:26 UTC, ezr-ondrej commented on webpack/assets/javascripts/react_app/components/common/forms/NumericInput.js
> -  disabled,
Why are we removing `disabled` and `step`? Isn't this library support it?

2021-05-02 08:00 UTC, yifatmakias commented
@ezr-ondrej You are very right, I fixed it there is no use of two libraries anymore.

2021-05-02 19:20 UTC, ezr-ondrej approved these changes
Thanks @yifatmakias !
Great one liner for very annoying bug :+1:

2021-05-02 19:20 UTC, merged

2021-05-05 12:00 UTC, ezr-ondrej commented
CP 2.4: #8503