Fixes #32563 - iPXE bootstrapping fixed
theforeman/foreman pull request #8513
Opened 2021-05-07 08:29 UTC by lzap

Bootstrap script should be only returned when boostrap parameter is present regardless if host is found or not, because it can be actually found by a HTTP proxy REMOTE_IP fallback mechanism and bootstrap would be never returned.

Second problem is in global template handling, it should be only returned when host was not found but there wasn't mac argument provided.

More info at: https://community.theforeman.org/t/foreman-2-4-katello-4-ipxe-not-working/23398

2021-05-07 09:38 UTC, ekohl requested changes
> Bootstrap script should be only returned when boostrap parameter is present regardless if host is found or not, because it can be actually found by a HTTP proxy REMOTE_IP fallback mechanism and bootstrap would be never returned.

In that topic, I still think the reverse proxy is not properly recognized. I think if it is configured correctly, it won't be an issue. This change feels premature.

2021-05-07 09:38 UTC, ekohl commented on app/controllers/unattended_controller.rb
> +    # The host is not known and its not the bootstrap script
```suggestion
    # The host is not known and it's not the bootstrap script
```

2021-05-07 09:38 UTC, ekohl commented on app/controllers/unattended_controller.rb
> +    # Host not in build was found and its not bootstrap script
```suggestion
    # Host not in build was found and it's not bootstrap script
```

2021-05-07 09:38 UTC, ekohl commented on app/controllers/unattended_controller.rb
> +    if @host && !@host.build? && !params[:mac]
Why the `!params[:mac]` part?

2021-11-10 08:00 UTC, ares commented
Hello @lzap, given this is a draft for a long time we'd like to know if you have a plan to move this out of the draft in a foreseeable future. Given this was reopened 6 days ago, I assume you plan to get back to it.

If we don't get a reply in 2 weeks, we'll close the PR but it can always be reopened.

2021-11-25 08:03 UTC, tbrisker commented
2 weeks have passed, closing. Feel free to reopen when you get back to this.

2021-11-25 08:03 UTC, closed without merging

2021-11-27 07:28 UTC, itszakko commented
Hi, I'm currently being hit by this bug.

I'm currently using the workaround described in the forum thread and had to fork https://github.com/theforeman/puppet-foreman internally to do so, as we use Puppet to keep our boxes in continuous compliance.

```
# Trusted proxy settings
:trusted_proxies:
  - "127.0.0.0/8"
  - "::1"
  - "<%= @ipaddress %>"
```

If there's something I can do to help get this fixed proper so I can remove my internal hack, I'd love to help.

2022-03-03 15:29 UTC, lzap commented on app/controllers/unattended_controller.rb
> +    if @host && !@host.build? && !params[:mac]
That was a copy and paste error.

2022-03-03 15:29 UTC, lzap commented
Rebased.