Fixes #28221 - Adding passing of template scope for snippet rendering
theforeman/foreman pull request #8523
Opened 2021-05-13 07:55 UTC by domitea

In current implementation templates can be much complex by snippet.
Reusable pieces of template code that should be in the same scope like
their templates but they are not. This PR tries to solve that.

2021-05-14 09:43 UTC, ares submitted a review, later dismissed
it would be good to have a test for this

2021-05-14 10:08 UTC, lzap requested changes
The change does change context of all snippets which will fail to pass snapshot tests. We cannot do that.

What is the reasoning for the change?

2021-05-14 10:12 UTC, lzap commented
Ah I am reading the issue and the BZ now.

2021-05-14 11:02 UTC, lzap requested changes
Okay I was able to reproduce the problem.

The issue why your change breaks tests so much is that in shapthot tests we pass in also a scope and that completely shadows all other parameters if I am not mistaken. This can be seen on the first diff of the PXEGrub default local boot template:

```diff
 timeout=20


-fallback=1 2 3 4 5 6 7 8 9 10
-
-title Chainload Grub from /EFI/fedora or try next
-  rootnoverify (hd0,0)
-  chainloader /EFI/fedora/grubx64.efi
-
-title Chainload Grub from /EFI/redhat or try next
-  rootnoverify (hd0,0)
-  chainloader /EFI/redhat/grubx64.efi
-
-title Chainload Grub from /EFI/centos or try next
-  rootnoverify (hd0,0)
-  chainloader /EFI/centos/grubx64.efi
-
-title Chainload Grub from /EFI/debian or try next
-  rootnoverify (hd0,0)
-  chainloader /EFI/debian/grubx64.efi
-
-title Chainload Grub from /EFI/ubuntu or try next
-  rootnoverify (hd0,0)
-  chainloader /EFI/ubuntu/grubx64.efi
-
-title Chainload Grub from /EFI/sles or try next
-  rootnoverify (hd0,0)
-  chainloader /EFI/sles/grubx64.efi
-
-title Chainload Grub from /EFI/opensuse or try next
-  rootnoverify (hd0,0)
-  chainloader /EFI/opensuse/grubx64.efi
-
-title Chainload Grub from /EFI/Microsoft or try next
-  rootnoverify (hd0,0)
-  chainloader /EFI/Microsoft/grubx64.efi
-
-title Chainload Grub from /EFI/EFI or try next
-  rootnoverify (hd0,0)
-  chainloader /EFI/EFI/grubx64.efi
-
-title Chainload Grub from /EFI/local_chain_hd0 or try next
-  rootnoverify (hd0,0)
-  chainloader /EFI/local_chain_hd0/grubx64.efi
-
+title Update your PXEGrub local template to get EFI options
+  root (hd0,0)
+  chainloader +1
+
 title Chainload into bootloader on first disk
   root (hd0,0)
   chainloader +1
```

Looking at the source and snippet, variables are passed: `<%= snippet "pxegrub_chainload", variables: {paths: paths} %>` and this is now not evaluated properly.

Context of snippets is undefined, we have never thought about it because we treat snippets as "local", meaning they should not be context-dependant, all inputs should be passed in via "variables" argument. The solution to the problem that the customer has is probably to pass it explicitly:

   <%= snippet("mysnippet", variables: {kernel: @kernel, initrd: @initrd} %>

I am going to test this solution. However I think the proper fix is to get rid of this scope hack in bootdisk and solve this properly.

2021-05-14 11:57 UTC, lzap commented
Correction - my workaround suggestion does not work. The moment `snippet` macro is called, a new (provisioning) context is created. I'd expect the variables provided via argument to shadow ones from the context, but apparently it does not work like that.

Well, this is not great. I spent some time with this and I cannot figure out a good solution. We need to be able to keep the context and inject new variables for snippets. Please take another look.

2021-05-17 20:26 UTC, timogoebel commented
@kamils-iRonin: If I remember correctly, this approach won't work. Any ideas?

2021-05-18 14:17 UTC, kamils-iRonin reviewed
> We need to be able to keep the context and inject new variables for snippets.

Not sure if I got the problem. So, we need to keep the base scope variables and merge them with the snippet specific variables?

2021-05-18 14:17 UTC, kamils-iRonin commented on lib/foreman/renderer/scope/macros/snippet_rendering.rb
>                snippet_variables = variables.merge(options[:variables] || {})
```suggestion
              snippet_variables = variables_keys.index_with { |key| instance_variable_get("@#{key}") }
                                                .symbolize_keys
                                                .merge(variables)
                                                .merge(options[:variables] || {})
```

2021-06-03 08:19 UTC, domitea commented
I've updated the PR with the suggestion by @kamils-iRonin and I added the test. We'll see if goes green.

2021-06-04 08:18 UTC, ares reviewed
dismissing my stale review, I see @lzap is now reviewing, my request was fullfilled as I see the test

2021-06-14 15:00 UTC, ares commented
@lzap does this version work for you?

2021-06-16 08:32 UTC, lzap approved these changes
Yeah that works! Nice. Thank you.

2021-06-16 08:33 UTC, merged