Fixes #32618 - pin psych to 3.3
theforeman/foreman pull request #8532
Opened 2021-05-18 10:20 UTC by lzap

Psych 4.0 turns the default behavior to safely load YAML files, Ruby classes now must be explicitly allowed.

2021-05-18 10:35 UTC, lzap commented
I think the pin is the only reasonable solution for now. After I fix configuration loading:

```diff
diff --git a/Gemfile b/Gemfile
index f817f917e..9975d7954 100644
--- a/Gemfile
+++ b/Gemfile
@@ -1,9 +1,6 @@
 # foreman plugins import this file therefore __FILE__ cannot be used
 FOREMAN_GEMFILE = __FILE__ unless defined? FOREMAN_GEMFILE

-# pin YAML library before we even load YAML configuration
-gem 'psych', '~> 3.3'
-
 require_relative 'config/boot_settings'

 source 'https://rubygems.org'
diff --git a/lib/foreman/logging.rb b/lib/foreman/logging.rb
index 7f5d32fc4..ef802b376 100644
--- a/lib/foreman/logging.rb
+++ b/lib/foreman/logging.rb
@@ -124,7 +124,7 @@ module Foreman
       fail "Logging configuration 'config/logging.yaml' not present" unless File.exist?(config_file)
       overrides ||= {}
       overrides.deep_merge!(overrides[environment.to_sym]) if overrides.has_key?(environment.to_sym)
-      @config = YAML.load_file(config_file)
+      @config = YAML.load_file(config_file, permitted_classes: [Symbol])
       @config = @config[:default].deep_merge(@config[environment.to_sym]).deep_merge(overrides)
     end
```

Two more issues appear (Rails fixtures and rails_i18n):

```
I18n::InvalidLocaleData: can not load translations from /home/lzap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rails-i18n-6.0.0/lib/rails_i18n/../../rails/locale/af.yml: #<Psych::DisallowedClass: Tried to load unspecified class: Symbol>
/home/lzap/work/foreman/app/models/operatingsystem.rb:80:in `<class:Operatingsystem>'
/home/lzap/work/foreman/app/models/operatingsystem.rb:4:in `<top (required)>'
/home/lzap/work/foreman_hooks/lib/foreman_hooks/as_dependencies_hook.rb:4:in `load_missing_constant'
/home/lzap/work/foreman/config/initializers/apipie.rb:49:in `block in <top (required)>'
/home/lzap/work/foreman/config/initializers/apipie.rb:33:in `<top (required)>'
/home/lzap/work/foreman/config/initializers/0_print_time_spent.rb:38:in `block in load'
/home/lzap/work/foreman/config/initializers/0_print_time_spent.rb:17:in `benchmark'
/home/lzap/work/foreman/config/initializers/0_print_time_spent.rb:38:in `load'
/home/lzap/work/foreman/config/environment.rb:5:in `<top (required)>'
/home/lzap/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
/home/lzap/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'

Caused by:
Psych::DisallowedClass: Tried to load unspecified class: Symbol
(eval):2:in `symbol'
/home/lzap/work/foreman/app/models/operatingsystem.rb:80:in `<class:Operatingsystem>'
/home/lzap/work/foreman/app/models/operatingsystem.rb:4:in `<top (required)>'
/home/lzap/work/foreman_hooks/lib/foreman_hooks/as_dependencies_hook.rb:4:in `load_missing_constant'
/home/lzap/work/foreman/config/initializers/apipie.rb:49:in `block in <top (required)>'
/home/lzap/work/foreman/config/initializers/apipie.rb:33:in `<top (required)>'
/home/lzap/work/foreman/config/initializers/0_print_time_spent.rb:38:in `block in load'
/home/lzap/work/foreman/config/initializers/0_print_time_spent.rb:17:in `benchmark'
/home/lzap/work/foreman/config/initializers/0_print_time_spent.rb:38:in `load'
/home/lzap/work/foreman/config/environment.rb:5:in `<top (required)>'
/home/lzap/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
/home/lzap/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```

I think this change will affect many dependencies and we will have to wait for them to fix it.

2021-05-18 10:35 UTC, ekohl requested changes

2021-05-18 10:35 UTC, ekohl commented on Gemfile
> +gem 'psych', '~> 3.3'
I'd prefer to be explicit that we don't support version 4 but continue to accept all older versions. This is more flexible on the packaging side
```suggestion
gem 'psych', '< 4'
```

2021-05-18 10:41 UTC, lzap commented
Rebased, for the record the relevant patch is https://github.com/ruby/psych/pull/487

2021-05-18 10:52 UTC, lzap commented
For the record, there seems to be a bug in psych 4.0.0 which made our tests to fail. It will probably be fixed in a bit, so then we should be able to unpin it again: https://github.com/ruby/psych/issues/490

2021-05-18 10:52 UTC, lzap commented
For the record, there seems to be a bug in psych 4.0.0 which made our tests to fail. It will probably be fixed in a bit, so then we should be able to unpin it again: https://github.com/ruby/psych/issues/490

2021-05-18 11:32 UTC, ekohl approved these changes
Still, it feels safer to me to pin. Otherwise we risk shipping version 4 in stable branches on Debian. Let's unpin it only in develop.

2021-05-19 10:18 UTC, ezr-ondrej commented
Now katello fails, because we have the psych gem twice.
And it all seems weird to me, because I don't see the psych gem to be pulled in previous to your changes, as it is included in ruby, so I think we should have just use the ruby included version and we should be fine.

2021-05-19 10:20 UTC, ekohl commented
I think it would be better if Katello didn't specify it and only Foreman did.

I wonder if the test failure in Foreman is related.

2021-05-19 10:22 UTC, ezr-ondrej commented
> I wonder if the test failure in Foreman is related.

We've discussed it in the morning and we think it probably is, as it is a yaml report, so there is slight change (extra new line)

2021-05-19 10:25 UTC, ekohl commented
Yes, but pinning to a version < 4 sounds like it shouldn't affect things.

2021-05-19 13:08 UTC, ezr-ondrej commented
> Yes, but pinning to a version < 4 sounds like it shouldn't affect things.

I agree, I think it's related to https://github.com/theforeman/foreman/pull/8532#issuecomment-843961026

2021-05-19 14:13 UTC, ekohl commented
But in the foreman test (https://ci.theforeman.org/job/test_develop_pr_core/8152/) Katello isn't present so I wonder why that fails.

2021-05-19 14:32 UTC, ezr-ondrej commented
> But in the foreman test (https://ci.theforeman.org/job/test_develop_pr_core/8152/) Katello isn't present so I wonder why that fails.

Because we don't use psych in foreman - thus we use the ruby one, only katello includes it through some of it dependencies.

2021-05-19 14:40 UTC, ekohl commented
Ah, that's a nuance I missed. So why do we need to pin it in core then?

2021-05-20 06:15 UTC, lzap commented
So mystery solved (I guess). Katello CI job was adding psych gem into gemfile for unknown reason, it was not pinned. That's why we were seeing the failure on CI. @jlsherrill explained this: https://community.theforeman.org/t/psa-rubygem-psych-4-0-is-out-and-its-a-breaking-change/23604

However why I saw Foreman not booting locally on my Ruby 2.7 is not so clear for me. I somehow installed psych 4.0 I assume, after I uninstalled it I only see 3.1 now:

```
$ gem uninstall psych
Gem psych-3.1.0 cannot be uninstalled because it is a default gem
```

2021-05-20 14:38 UTC, ezr-ondrej commented
I'm closing this now as we should not require psych explicitly.
This was issue with our pipepline and rvm having the `psych` gem included by default instead of using the ruby implementation.
Fix for our pipeline was just: https://github.com/theforeman/jenkins-jobs/pull/69

2021-05-20 14:38 UTC, closed without merging