Fixes #32625 - Registration API & OS template
theforeman/foreman pull request #8549
Opened 2021-05-25 08:42 UTC by stejskalleos

Fixed issue when users could create registration command
with OS that doesn't have assigned `host_init_config` template

2021-05-25 11:59 UTC, timogoebel commented on app/controllers/api/v2/registration_commands_controller.rb
> +        if os_with_template?
Nit: I'd change this to use a guard clause.

```ruby
unless os_with_template?
  # render error message here
  return
end

# render normally
```

2021-05-25 11:59 UTC, timogoebel commented on app/controllers/api/v2/registration_commands_controller.rb
> +        os = Operatingsystem.authorized(:view_operatingsystems).find(registration_params[:operatingsystem_id])
Don't we have a helper for this? I think it's weird to do this kind of logic on a controller level.

2021-05-25 11:59 UTC, timogoebel commented on app/controllers/api/v2/registration_commands_controller.rb
> +          message = N_("Operating system doesn't have assigned 'host_init_config' template")
```suggestion
          message = N_("Operating system doesn't have a 'host_init_config' template assigned.")
```

2021-06-01 13:51 UTC, ares requested changes
looks mostly good, just one ask for a test, once fixed I'll do the testing, @timogoebel any more comments from your side or are you good with merging if it works?

2021-06-01 13:51 UTC, ares commented on app/models/operatingsystem.rb
> +  def has_default_template?(template_kind)
a test for this would be cool :-)

2021-06-01 13:56 UTC, timogoebel commented on app/controllers/api/v2/registration_commands_controller.rb
> +        param :operatingsystem_id, :number, desc: N_("ID of the Operating System to register the host in. Operating system must have assigned `host_init_config` template")
```suggestion
        param :operatingsystem_id, :number, desc: N_("ID of the Operating System to register the host in. Operating system must havea `host_init_config` template assigned.")
```

2021-06-01 13:57 UTC, timogoebel commented
> @timogoebel any more comments from your side

@ares: Just a tiny wording improvement suggestion, otherwise I'm good.

2021-06-07 08:53 UTC, stejskalleos commented
@ares @timogoebel - Rebased, updated & checks are green

2021-06-07 14:15 UTC, ares approved these changes
Thanks @stejskalleos and @timogoebel, I've tested and it works fine. I was surprised that it works fine without specifying the OS but that's OK for flows we get the OS from facts and shouldn't be mandatory.

Merging!

2021-06-07 14:15 UTC, merged