Fixes #32166 - Merging Ignored Interfaces to Excluded Facts
theforeman/foreman pull request #8560
Opened 2021-05-31 13:06 UTC by domitea

Foreman has two lists where "ignored" facts can be defined. The Ignored Interface Identifiers and Excluded Facts. Both of them actually do almost the same thing so it makes sense to merge them. 

PR contains also migration that takes values from ignored interfaces to excluded facts.
I've in plan to check plugins if the ignored interfaces are used and create PRs to reflect these change. In addition to that. I've added a warning message for Setting call and for Template call of this settings just in case if there are could be something missing from community.

2021-05-31 13:23 UTC, ekohl requested changes
I'm not sure this is a good idea. In Facter there's structured facts unless the fact filter starts to understand that structure as well.

Back in Facter < 3 you have facts as `ipaddress_$interface` but in Facter 3, there's a hash, so you end up with `facts['networking']['interfaces'][$interface]`. Having a list of interface patterns to ignore is actually very useful. A fact parser can use this information to filter out the right facts.

There is actually also a bug with this global matching where some facts are matched by accident. For example, `en*v*` also filters out the `environment` fact since it matches. I'm not sure if there's a Redmine for that though.

2021-05-31 13:23 UTC, ekohl commented on app/models/setting/provisioning.rb
> -      set('ignored_interface_identifiers', N_("Ignore interfaces that match these values during facts importing, you can use * wildcard to match names with indexes e.g. macvtap*"), IGNORED_INTERFACES
The constant `IGNORED_INTERFACES` is no unused. Should it be removed?

2021-05-31 13:23 UTC, ekohl commented on config/environments/development.rb
> +      Bullet.enable = false
This looks unrelated

2021-06-01 06:55 UTC, domitea commented
I understand your concern but I think it makes sense to have only one list of fact filtering. Information about interfaces are facts too so this attempt to remove inconsistency. To be honest, when I viewed the problem for the first time I through there is a another "magic parser and filter" only for the interfaces. Then @ares comes and said that it's only a another list of filters for fact parser. 

From my point of view, the `en*v*` problem isn't problem at all because Regex. Maybe, but maybe it will worth to create another list of "must have" facts that will bypass the filter even the regex in excluded facts includes them because sometimes is simpler to define what do you want instead you don't want. 

What so you think?

2021-06-01 07:26 UTC, lzap commented
I also do not think this is a good idea, but for a different reason. A do believe that the best user experience will bring us Common Fact Model: https://community.theforeman.org/t/rfc-common-fact-model/18900

In short, instead of filtering out facts, we want to have highly curated list of facts that we actually accept. We are speaking about dozen of facts at maximum, but these would be normalized across all facters (Ansible, Puppet, RHSM) in a way they do not fight each other. In some cases we could actually drop fact type completely and only present one consistent fact (e.g. memory size). All facts would be also stored in JSON as blobs so they could be still used per-host for parametrization (each type separately).

Then we can drop fact filtering altogether, there is no reason to keep it because storing a JSON in a blob is N operation. And here is my point - if we merge fact filter and NIC filter, then we could not drop the former because NIC filtering will still be useful. Our fact parsers will still be parsing NICs even after we introduce Common Fact Model.

So it is not a good step for the future. I am assuming that people do like my proposal, I know, it's bold :-)

2021-06-01 08:41 UTC, ekohl commented
> I understand your concern but I think it makes sense to have only one list of fact filtering. Information about interfaces are facts too so this attempt to remove inconsistency. To be honest, when I viewed the problem for the first time I through there is a another "magic parser and filter" only for the interfaces. Then @ares comes and said that it's only a another list of filters for fact parser.

Interfaces are special anyway since there is code in Foreman that updates the host interfaces from facts. That alone makes them special enough that a specific filter is valid IMHO.

At this point I don't think this is a path we should take and perhaps never should as long as the interface updating code exists in Foreman.

2021-06-04 08:51 UTC, ares commented
> Interfaces are special anyway since there is code in Foreman that updates the host interfaces from facts. That alone makes them special enough that a specific filter is valid IMHO.
> 
> At this point I don't think this is a path we should take and perhaps never should as long as the interface updating code exists in Foreman.

I think you're right. I think we can avoid some user confusion by providing a better help to the existing settings instead of combining them.

The `excluded_facts` means it skips all facts from being imported, meaning stored as raw data in the Foreman DB. The existing help for that says 

```
Exclude pattern for all types of imported facts (puppet, ansible, rhsm). Those facts won't be stored
in foreman's database. You can use * wildcard to match names with indexes e.g. ignore* will filter
out ignore, ignore123 as well as a::ignore or even a::ignore123::b
```

Which I think is good enough.

The `ignore_interace_identifiers` one is used after the facts are stored in the DB and we do further processing and update existing Foreman objects accordingly. The help says today 

```
Ignore interfaces that match these values during facts importing, you can use * wildcard 
to match names with indexes e.g. macvtap*
```

I think we should update it to something like

```
Skip creating or updating host network interfaces objects with identifiers matching these values from incoming facts.
You can use * wildcard to match identifiers with indexes e.g. macvtap*. The ignored interfaces raw facts
will be still stored in the DB, see the 'Exclude pattern' setting for more details.
```

If you all agree, I think this PR can just change to modify the setting description. As of today that would require a migration too, which hopefully changes soon.

2021-06-09 13:04 UTC, lzap commented
> If you all agree, I think this PR can just change to modify the setting description. As of today that would require a migration too, which hopefully changes soon.

I agree, let's do this. I understand the concern that this is confusing. Ideally at some point in the future:

1) Facts are stored in a blob/text and only few stored in tables separately
2) Foreman does not create interfaces, subnets, domains automatically but only via human-invervention

This is what I believe would deliver the best experience.

2021-06-10 12:00 UTC, domitea commented
@lzap, @ares PR updated, please take a look.

2021-06-10 14:30 UTC, lzap approved these changes
Works fine, thanks.

2021-06-10 14:31 UTC, lzap commented
@ekohl please merge once you confirm.

2021-06-11 08:00 UTC, ekohl approved these changes
LGTM. @ares since you also took a look, want to take a last one before merging?

2021-06-11 14:54 UTC, ares approved these changes
Thanks, merging!

2021-06-11 14:55 UTC, merged

2021-06-11 14:55 UTC, ares commented
I've updated the commit message as it was no longer accurate.

2021-06-16 08:38 UTC, lzap commented
We have missed the commit message which was not describing the actual commit, renamed the PR at least.

2021-10-20 09:57 UTC, ezr-ondrej commented on db/migrate/20210610134000_update_ignored_interfaces_setting_description.rb
> +end
We do not need migrations for description. I'll clean it up, but unfortunatelly it's already in release :)