Fixes #32536 - add valid error when using invalid status type
theforeman/foreman pull request #8561
Opened 2021-05-31 13:13 UTC by yifatmakias

when using "/api/hosts/:id/status/:type" where type is either "global, "configuration" or "build" any other type is now rendering a relevant error.

2021-05-31 13:41 UTC, ekohl reviewed
Looks good to me, but could you add a test to cover this as well?

2021-05-31 13:51 UTC, yifatmakias commented
> Looks good to me, but could you add a test to cover this as well?

@ekohl Yes sure, I will add and update the PR. Thanks!

2021-05-31 20:05 UTC, timogoebel requested changes

2021-05-31 20:05 UTC, timogoebel commented on app/controllers/api/v2/hosts_controller.rb
> +          when 'configuration', 'build'
Note, that plugins may add other statuses here. These must also continue to work.
There is a status registry API to check for available statuses.
This needs test coverage.

2021-06-01 08:30 UTC, timogoebel commented on test/controllers/api/v2/hosts_controller_test.rb
> +    assert JSON.parse(@response.body) == {"error" => "Status doesnt_exist does not exist."}
If this test fails, it's impossible to figure out why this happens.
```suggestion
    assert_equal ({"error" => "Status doesnt_exist does not exist."}, JSON.parse(@response.body))
```

2021-06-01 08:32 UTC, ekohl commented on test/controllers/api/v2/hosts_controller_test.rb
> +    get :get_status, params: { :id => @host.to_param, :type => 'doesnt_exist' }
Could you also assert the status code?

2021-06-01 09:54 UTC, timogoebel submitted a review, later dismissed
Untested, but looks good.

2021-06-01 09:56 UTC, ekohl requested changes

2021-06-01 09:56 UTC, ekohl commented on test/controllers/api/v2/hosts_controller_test.rb
> +    assert JSON.parse(@response.body) == {"error" => "Status doesnt_exist does not exist."}, JSON.parse(@response.body)
```suggestion
    assert_equal {"error" => "Status doesnt_exist does not exist."}, JSON.parse(@response.body)
```

2021-06-01 09:58 UTC, timogoebel commented on test/controllers/api/v2/hosts_controller_test.rb
> +    assert JSON.parse(@response.body) == {"error" => "Status doesnt_exist does not exist."}, JSON.parse(@response.body)
Oh yes, that's still missing.

2021-06-01 11:17 UTC, ekohl approved these changes

2021-06-01 12:29 UTC, merged

2021-06-14 10:02 UTC, ezr-ondrej commented
CP 2.5: #8591