refs #31663 Unassign OS from registration templates
theforeman/foreman pull request #8645
Opened 2021-07-07 09:27 UTC by stejskalleos

Operating systems cannot be assigned to registration templates,
so the migration file should also remove these associations.

How to reproduce the issue
* Checkout `2.4-stable` branch
* Assign OS to registration template
* Checkout `develop` branch
* Run `rails db:migrate` & then `rails db:seed`
```
ActiveRecord::RecordInvalid: 
Validation failed: Operatingsystems can't assign operating system to Registration template
```

From https://community.theforeman.org/t/foreman-update-2-5-1-foreman-rake-db-seed-fails/24242

2021-07-07 11:09 UTC, stejskalleos commented
@ares

2021-07-08 08:12 UTC, tbrisker requested changes
Issue [#31663](https://projects.theforeman.org/issues/31663) has already been released in 2.5.0. Please use a new redmine issue with `fixes` and mark it as related to 31663.

2021-07-08 08:20 UTC, tbrisker reviewed
What will happen to users who upgraded to 2.5.0 and ran this migration already?

2021-07-08 10:12 UTC, stejskalleos commented
> What will happen to users who upgraded to 2.5.0 and ran this migration already?

Well, this PR is fixing issue when users manually assigned OS to Global Registration template (**by default template has no OS**)

* If they assigned OS to GRT, they had same problem as some other users [0] and they had to fix it manually
* Other users (should be majority) run migration without problems

[0] https://community.theforeman.org/t/foreman-update-2-5-1-foreman-rake-db-seed-fails/24242

2021-07-14 16:09 UTC, tbrisker approved these changes
Thanks @stejskalleos , makes sense!

2021-07-14 16:09 UTC, merged

2021-07-14 16:10 UTC, tbrisker commented
2.5 - 7790fc852