Fixes #33038 - add bmc_available to host show API
theforeman/foreman pull request #8672
Opened 2021-07-15 18:11 UTC by amirfefer

This is needed for the new host details page to enable  BMC power actions

2021-07-16 08:38 UTC, ares requested changes
Tiny change requested, then good to be merged.

2021-07-16 08:38 UTC, ares commented on app/views/api/v2/hosts/main.json.rabl
> +  :last_compile, :global_status, :global_status_label, :uptime_seconds, :tags, :bmc_available?
Just a tiny ask, don't add an attribute with `?` in the name.

While it's Rails convention, the API shouldn't contain special charatcters, we typically don't do it for other flags, such as managed or build or enabled. Could you pleaes define an alias in the host model, something like `alias_method :bmc_available?, :bmc_available` and then use the version without question mark here?

2021-07-19 21:49 UTC, amirfefer commented
Thanks @ares , updated

2021-07-20 10:58 UTC, ares approved these changes
Thanks @amirfefer, works well, merging!

2021-07-20 10:59 UTC, merged