Fixes #33179 - Fix header in Enviroments page
theforeman/foreman pull request #8700
Opened 2021-07-29 11:38 UTC by yifatmakias

2021-07-29 12:25 UTC, ofedoren commented
@ezr-ondrej, shouldn't be that page extracted as part of Puppet removal?..

2021-07-29 12:27 UTC, ezr-ondrej commented
> @ezr-ondrej, shouldn't be that page extracted as part of Puppet removal?..

indeed, that's why the fix is directly against 2.5 branch :)

2021-07-29 13:46 UTC, ezr-ondrej approved these changes
Looks good to me.
@tbrisker ?

2021-07-29 14:58 UTC, tbrisker approved these changes
This doesn't seem like the correct fix and probably won't resolve the issue. The issue is that for generating the breadcrumb name, the mounter uses the BreadcrumbOption service to find the name:
https://github.com/theforeman/foreman/blob/f5a3dd2dedb569a0e6c5e8bb311c1da75906fc4f/app/helpers/layout_helper.rb#L76

Which in turn uses the menu manager to find the caption for the breadbrumb based on the controller name:

https://github.com/theforeman/foreman/blob/f5a3dd2dedb569a0e6c5e8bb311c1da75906fc4f/app/services/breadcrumbs_options.rb#L33

but when you have katello installed this is what is returned:
> Menu::Manager.get_resource_caption(:environments)
=> "Lifecycle Environments"

2021-07-29 14:58 UTC, tbrisker requested changes
oops, that should have been request changes, not approve :)

2021-07-29 15:17 UTC, tbrisker commented
And the reason it finds that is that katello actually registers the lifecycle environment menu item with the same key:

https://github.com/Katello/katello/blob/7db3ca848ae1577810b40a879bc0675254226528/lib/katello/plugin.rb#L66

2021-07-29 15:23 UTC, tbrisker commented
Alternatively, we could specify the breadcrumb explicitly like we do on the edit forms, by adding this to the view:
```
<%= breadcrumbs(:switchable => false,
                :items => [
                  { :caption => _('Puppet Environments'), :url => environments_path },
                ]) %>
```

2021-08-02 07:09 UTC, yifatmakias commented
> Alternatively, we could specify the breadcrumb explicitly like we do on the edit forms, by adding this to the view:
> 
> ```
> <%= breadcrumbs(:switchable => false,
>                 :items => [
>                   { :caption => _('Puppet Environments'), :url => environments_path },
>                 ]) %>
> ```

To which view? the welcome page? I am not sure I fully understand

2021-08-02 09:25 UTC, tbrisker commented
> > Alternatively, we could specify the breadcrumb explicitly like we do on the edit forms, by adding this to the view:
> > ```
> > <%= breadcrumbs(:switchable => false,
> >                 :items => [
> >                   { :caption => _('Puppet Environments'), :url => environments_path },
> >                 ]) %>
> > ```
> 
> To which view? the welcome page? I am not sure I fully understand

yes, if you add the `breadcrumbs` helper in the welcome.html.erb, it will override the default one which picks up the wrong name from the menu. Though I think that changing the menu item name in katello is a more correct solution to the issue.

Changing the titles from "Environments" to "Puppet Environments" still makes sense, but it won't resolve this issue and should be done in the puppet plugin rather than in the stable branch.

2021-08-02 12:48 UTC, tbrisker commented on app/views/environments/welcome.html.erb
> -<% content_for(:title, _("Enviroments")) %>
This is the page title, it should still remain - but changed to Puppet Environments as well

2021-08-02 13:04 UTC, tbrisker approved these changes
Thanks @yifatmakias ! please open a PR to foreman_puppet adding this change to the plugin as well.

2021-08-02 13:04 UTC, merged