Fixes #33514 - correct errorToast type
theforeman/foreman pull request #8783
Opened 2021-09-17 18:09 UTC by jeremylenz

When using API middleware's errorToast option, the action dispatched has a type 'error' which is incorrect. This results in a console warning:

```
Toast notification type 'error' is invalid. Please use one of the following types: success,danger,warning,info,default
```

It transforms the error to the 'danger' type, but still displays the warning. It should be 'danger' from the beginning to avoid the console warning.

2021-09-19 11:52 UTC, amirfefer requested changes
@jeremylenz, Thanks
Can you please update the failed snapshot?

2021-09-20 14:53 UTC, jeremylenz commented
@amirfefer Snapshot updated.  I don't think the other 2 failures are related..?

2021-09-20 14:58 UTC, amirfefer approved these changes
@jeremylenz, Thanks 👍 
yes, the other test failures aren't related

2021-09-20 14:58 UTC, merged

2021-11-18 13:09 UTC, ezr-ondrej commented
CP 3.0: 1d038e275