Fixes #33491 - fix host page kebab actions
theforeman/foreman pull request #8785
Opened 2021-09-19 15:35 UTC by amirfefer

The build action is blocked by https://github.com/theforeman/foreman/pull/8653

2021-09-28 12:54 UTC, ekohl commented
Needs a rebase now.

2021-10-06 18:13 UTC, amirfefer commented
- [ ] rebased
- [ ] remove the `build` option

2021-10-07 14:07 UTC, tbrisker requested changes
A few inline comments, most of them can be handled in follow-up PRs, but at least the message to display on delete should be corrected.

2021-10-07 14:07 UTC, tbrisker commented on webpack/assets/javascripts/react_app/components/HostDetails/ActionsBar/index.js
>      <DropdownSeparator key="separator" />,
This looks odd when there aren't any other items after it:
![image](https://user-images.githubusercontent.com/1540531/136395227-b454031e-fb6a-4439-bd8b-6b4aa7845d20.png)

2021-10-07 14:07 UTC, tbrisker commented on webpack/assets/javascripts/react_app/components/HostDetails/ActionsBar/index.js
> +      icon={<TrashIcon color="#c9190b" />}
Could this use some color variable from PF rather than hard-coded value?

2021-10-07 14:07 UTC, tbrisker commented on webpack/assets/javascripts/react_app/components/HostDetails/ActionsBar/index.js
> +      isDisabled={!canDestroy}
@MariSvirik will check if we should disable or hide if a user has no permissions, if we should hide instead we can do that in a follow up PR.

2021-10-07 14:07 UTC, tbrisker commented on webpack/assets/javascripts/react_app/components/HostDetails/ActionsBar/actions.js
> +  const errorToast = ({ message }) => message;
Not related to this, but looks like when the API errors the message is only the error code and no further details (the error message from the server does include a more detailed message):
![image](https://user-images.githubusercontent.com/1540531/136397097-b9a8e418-f252-49e7-82c8-c9d31ca6203f.png)

Additionally, looks like the error toast gets closed sometimes even without clicking the X button, though i didn't manage to figure out what triggers that.

2021-10-07 14:07 UTC, tbrisker commented on webpack/assets/javascripts/react_app/components/HostDetails/ActionsBar/index.js
> +  };
Can be done in a separate PR, but perhaps we could combine this with the `deleteHost` method and reuse it in the index page as well? (or at least encapsulate all the host delete logic in one place)

2021-10-07 14:07 UTC, tbrisker commented on webpack/assets/javascripts/react_app/components/HostDetails/ActionsBar/index.js
> +            'Are you sure you want to delete host %s ? It is irreversible, but VM and its disks will not be deleted. This behavior can be changed via global setting "Destroy associated VM on host del
The text might not be correct, if the setting has been changed the VM and disks will be deleted as well, and it might not be a VM at all. 
The full logic is here:
https://github.com/theforeman/foreman/blob/91c28da70a7bc5a96162ff2614eb1406ef0313ac/app/helpers/hosts_helper.rb#L278-L288

2021-10-08 12:33 UTC, MariSvirik commented on webpack/assets/javascripts/react_app/components/HostDetails/ActionsBar/actions.js
> +  const errorToast = ({ message }) => message;
If we have more informative text, let's use it instead of just having code 500.

There is probably an automatic timeout for the toast alert (8 seconds is recommended by [Patternfly](https://www.patternfly.org/v4/components/alert/design-guidelines))
Toast alerts should not disappear while the user is hovering over them.

2021-10-08 12:37 UTC, MariSvirik commented on webpack/assets/javascripts/react_app/components/HostDetails/ActionsBar/index.js
>      <DropdownSeparator key="separator" />,
@tbrisker Please, change the red icon to a black one. Based on PF4 guidelines we don't use red in dropdowns/buttons/icons. 
The only exception I can think of (where usage of the red Delete button is allowed) is inside the confirmation modal doing a very destructive action.

2021-10-10 17:24 UTC, amirfefer commented on webpack/assets/javascripts/react_app/components/HostDetails/ActionsBar/index.js
>      <DropdownSeparator key="separator" />,
Thanks, switched back to the default black color

2021-10-10 17:30 UTC, amirfefer commented on webpack/assets/javascripts/react_app/components/HostDetails/ActionsBar/actions.js
> +  const errorToast = ({ message }) => message;
This error message arrives from our API middleware, looks like the API middleware returns just the error status directly from  `axios`, but not the error object from the server, not in the scope of this PR.

@laviro can you please have a look at that?

2021-10-10 17:30 UTC, amirfefer commented on webpack/assets/javascripts/react_app/components/HostDetails/ActionsBar/index.js
> +  };
good idea 👍 
I merged these together for an easy re-use later

2021-10-10 17:34 UTC, amirfefer commented on webpack/assets/javascripts/react_app/components/HostDetails/ActionsBar/index.js
> +            'Are you sure you want to delete host %s ? It is irreversible, but VM and its disks will not be deleted. This behavior can be changed via global setting "Destroy associated VM on host del
Thanks, I've changed the logic a  bit, how about:
```
if (compute):
    "Are you sure you want to delete host <HOSTNAME> ? 
    It is irreversible, VM and its disks might be deleted according 
    to the global setting "Destroy associated VM on host delete"
else: 
    "Are you sure you want to delete host <HOSTNAME> ? This action is irreversible"
```

2021-10-11 07:08 UTC, tbrisker commented on webpack/assets/javascripts/react_app/components/HostDetails/ActionsBar/index.js
> +            'Are you sure you want to delete host %s ? It is irreversible, but VM and its disks will not be deleted. This behavior can be changed via global setting "Destroy associated VM on host del
The user might not have access to view the setting, so they won't know if the VM gets deleted or not/

2021-10-11 07:10 UTC, tbrisker commented on webpack/assets/javascripts/react_app/components/HostDetails/ActionsBar/actions.js
> +  const errorToast = ({ message }) => message;
I agree this is out of scope - just wanted to mention it since i noticed this when testing. Could you please open a separate issue for this so we don't forget to fix it?

2021-10-11 09:35 UTC, MariSvirik commented on webpack/assets/javascripts/react_app/components/HostDetails/ActionsBar/index.js
> +      isDisabled={!canDestroy}
- DISABLE 
Based on [console's guidelines](https://docs.google.com/document/d/1xEy7ieZUCe-R8FI0Lgk61b74npbPuD-PIRdixjsN5ac/edit#) we agreed with @tbrisker that the scenario fits the one described in the guidelines: 'User's org is entitled to the features/app but the user has just partial permissions. And we want them to have the ability to contact admin to change the permissions.'

2021-10-11 19:21 UTC, amirfefer commented on webpack/assets/javascripts/react_app/components/HostDetails/ActionsBar/index.js
> +            'Are you sure you want to delete host %s ? It is irreversible, but VM and its disks will not be deleted. This behavior can be changed via global setting "Destroy associated VM on host del
done :)
![Screen Shot 2021-10-11 at 22 19 21](https://user-images.githubusercontent.com/11807069/136844839-2e1718bf-de2d-493b-b8c0-df4cd18c0fbb.png)

2021-10-12 07:41 UTC, MariSvirik commented on webpack/assets/javascripts/react_app/components/HostDetails/ActionsBar/index.js
> +            'Are you sure you want to delete host %s ? It is irreversible, but VM and its disks will not be deleted. This behavior can be changed via global setting "Destroy associated VM on host del
@amirfefer can you just bold a hostname?

2021-10-12 07:48 UTC, tbrisker approved these changes
Thanks @amirfefer !

2021-10-12 07:48 UTC, merged

2021-10-12 07:50 UTC, tbrisker commented on webpack/assets/javascripts/react_app/components/HostDetails/ActionsBar/index.js
> +            'Are you sure you want to delete host %s ? It is irreversible, but VM and its disks will not be deleted. This behavior can be changed via global setting "Destroy associated VM on host del
Oops, just merged without noticing this comment. we can add it in a follow-up PR.

2021-10-12 13:38 UTC, amirfefer commented on webpack/assets/javascripts/react_app/components/HostDetails/ActionsBar/index.js
> +            'Are you sure you want to delete host %s ? It is irreversible, but VM and its disks will not be deleted. This behavior can be changed via global setting "Destroy associated VM on host del
PR for the rescue :) https://github.com/theforeman/foreman/pull/8837

2021-11-18 13:11 UTC, ezr-ondrej commented
CP 3.0: #8842