Fixes #33565 - speed-up kickstart on air gapped infra where repos are unreachable
theforeman/foreman pull request #8795
Opened 2021-09-24 14:45 UTC by pandrieux

speed-up kickstart on air gapped infra where repos are unreachable

on air gapped infra, installing subscription-manager won't be possible as-is since internet repo is unreachable.

I'm simply checking RPM is installed avoiding to wait for timeout.

2021-09-28 10:50 UTC, ekohl commented on app/views/unattended/provisioning_templates/snippet/redhat_register.erb
> +    if [ -z "$(rpm -qa subscription-manager)" ]; then
Should it instead use `rpm --query --quiet subscription-manager` and rely on the exit code?
```suggestion
    if ! rpm --query --quiet subscription-manager ; then
```

2021-09-28 12:30 UTC, ekohl commented
Could you squash both commits and use the right commit message format? Including `Fixes #33565` allows our automation to work.

2021-09-28 19:37 UTC, pandrieux commented
thanks you @ekohl , I think that is ok now.

2021-09-29 10:35 UTC, ekohl commented
ok to test

2021-09-29 10:35 UTC, ekohl approved these changes, later dismissed
I started CI, if that's green it can be merged.

2021-11-02 12:19 UTC, ekohl commented
My apologies, I forgot to check back. Now there's a merge conflict. Could you rebase this patch to resolve the conflict?

2022-05-18 10:15 UTC, ShimShtein commented
@pandrieux Can you please rebase the PR?

Also: I see there are other yum install commands in this file, or in other snippets that could be called. I suppose you will need to wrap them with a similar check too.

2022-07-26 15:36 UTC, pandrieux commented
@ShimShtein 
Sorry it took me some time as I was ooo for a while.
I just rebased the code.
I can't tell for the over yum install commands. In my env, I wrapped only this one.

2022-08-02 11:37 UTC, ShimShtein requested changes
Other yum commands are invoked in some specific cases. That's why you didn't see them manifesting in your setup.
For example the one [here](https://github.com/theforeman/foreman/blob/dfe4a66d6d0a0122c8ce69bc5f53abc7646e3339/app/views/unattended/provisioning_templates/snippet/redhat_register.erb#L127) will be invoked if you set `syspurpose*` parameters.
and others in this snippet would be manifested if content management (Katello) is enabled for this host.

I think we need to count in all these cases.

2022-08-04 09:51 UTC, pandrieux commented
I understand your point. 
I read the .erb, I'm adding wrapper for `subscription-manager-syspurpose` because it seems to be the same case.
I don't see any other invocation that require the wrapper. Once `subscription-manager*` is installed and registration is done, repositories will be available.

2022-08-07 08:56 UTC, ShimShtein approved these changes

2022-08-07 08:56 UTC, merged

2022-08-07 08:56 UTC, ShimShtein commented
Merged, thanks @pandrieux !