Fixes #33672 - drop unnecessary timestamps
theforeman/foreman pull request #8831
Opened 2021-10-11 09:48 UTC by lzap

I've reviewed `db/schema.rb` and found these. I do believe these are useless, let's see if it breaks any tests.

2021-10-11 10:42 UTC, ekohl requested changes
Why do you think these are not needed? At least for fact values I do use the last change time. It's even shown in the UI.

Also for settings we use `updated_at` here:
https://github.com/theforeman/foreman/blob/c89db7cdae5fc3569c7940e0c8d5e360efedfffc/app/services/setting_registry.rb#L146
That changed the memory usage from ~2 GB/worker to ~1.4 GB/worker (1fbcf6e45003d11637302c649bd13ef9fd5cf8f4).

I also don't see how dropping these helps. Is storage space a problem?

2021-10-13 08:59 UTC, ezr-ondrej commented on db/migrate/20211011093749_drop_unnecessary_timestamps.rb
> +        :taxonomies,
This one should probably keep the timestamps

2021-10-13 09:01 UTC, ezr-ondrej commented on db/migrate/20211011093749_drop_unnecessary_timestamps.rb
> +        :settings,
@ares and @ShimShtein are not sure about these.

2021-11-03 10:07 UTC, ares commented on db/migrate/20211011093749_drop_unnecessary_timestamps.rb
> +        :settings,
I looked in more details, we don't display this information anywhere and settings are audited, so I'm fine with dropping it for settings. However I disagree with FactValues, we use that in the Fact Values index page, the reported at column, which I think is useful. So either we need to drop this functionality (I don't prefer that) or we keep at least udpated_at for fact_values.

2021-11-03 10:10 UTC, ekohl commented on db/migrate/20211011093749_drop_unnecessary_timestamps.rb
> +        :settings,
As I said in https://github.com/theforeman/foreman/pull/8831#pullrequestreview-776080031, I think you'll break things by removing `updated_at` from settings.

2021-11-04 08:19 UTC, closed without merging