Fixes #33694 - upgrade prettier to v2
theforeman/foreman pull request #8843
Opened 2021-10-13 21:21 UTC by sharvit

Just upgrading prettier to v2 and running `npm run lint -- --fix`

- It is possible to reduce the diff by playing with the settings, for example setting `arrowParens` to `avoid` but I'm not sure if it is worth it, opinions?
  https://prettier.io/docs/en/options.html#arrow-function-parentheses

2021-10-13 23:04 UTC, sharvit commented on package.json
> +    "prettier": "2.4.1",
Seems like prettier recommend using `exact-same` version: https://prettier.io/docs/en/install.html

2021-10-14 08:48 UTC, tbrisker requested changes
I tried to look over the changes and think which ones are better and which aren't and commented inline on an example of each rule (i think). Would it be possible to upgrade the version and disable all the new rules first (or at least the ones causing most changes), and then open another PR for each rule to discuss separately if we want to implement it or not? That is how we did it with rubocop rules for the ruby code.

2021-10-14 08:48 UTC, tbrisker commented on script/npm_install_plugins.js
> +packageJsonDirs('pipe').forEach((pluginPath) => {
I'm not sure about this rule, looks like our current style is the opposite and it leads to quite a lot of changes. On the other hand I personally find it a bit more readable.

2021-10-14 08:48 UTC, tbrisker commented on script/plugin_webpack_directories.js
> +  var splitDirs = pluginDirs.toString().split('\n').reverse();
👍🏼 to longer lines before requiring a break (if this is the rule that changed here)

2021-10-14 08:48 UTC, tbrisker commented on webpack/assets/javascripts/foreman_hosts.js
> +  ).textContent;
👎🏼 to the rule that led to this change, looks much worse imho

2021-10-14 08:48 UTC, tbrisker commented on webpack/assets/javascripts/react_app/common/withReactRoutes.js
> +  (
not sure about this rule either, i think the previous version might be more readable?

2021-10-14 08:48 UTC, tbrisker commented on webpack/assets/javascripts/react_app/components/AuditsList/ExpansiveView.js
> +    const { comment, actionDisplayName, auditedChangesWithIdToLabel, details } =
This change is worse I think, it makes looking at the history more difficult if you want to figure out when a certain prop was added and why

2021-10-14 11:02 UTC, ekohl commented
Also a general note that we've also been cautious with Rubocop massive refactors. They make cherry picks harder and often patches need to be rebased to resolve conflicts.

2021-10-14 14:10 UTC, sharvit commented on script/npm_install_plugins.js
> +packageJsonDirs('pipe').forEach((pluginPath) => {
Yes, they changed the default value for https://prettier.io/docs/en/options.html#arrow-function-parentheses

2021-10-14 14:57 UTC, sharvit commented
> I tried to look over the changes and think which ones are better and which aren't and commented inline on an example of each rule (i think). Would it be possible to upgrade the version and disable all the new rules first (or at least the ones causing most changes), and then open another PR for each rule to discuss separately if we want to implement it or not? That is how we did it with rubocop rules for the ruby code.

The issue is, prettier is not customizable by design/philosophy because they believe in forcing the community opinion so you don't need to waste your time on discussions:

> “We want to free mental threads and end discussions around style. While sometimes fruitful, these discussions are for the most part wasteful.”
> "Even if Prettier does not format all code 100% the way you’d like, it’s worth the “sacrifice” given the unique benefits of Prettier"
- https://prettier.io/docs/en/option-philosophy.html
- https://prettier.io/docs/en/why-prettier.html

tbh I prefer the way the code looks with v1 but I don’t think we should use a project/version which is not maintained for the long term.
On the other side, I do like the approach of using whatever ever works and is agreed by the wider community so we don't need to think or discuss that.

2021-10-17 09:34 UTC, ekohl commented
https://github.com/theforeman/foreman/pull/8839#discussion_r730376166 is an example where a cherry pick is made harder because of coding style. I wonder if it would be better to disable prettier in stable branches just to avoid that. It wouldn't really solve things because many would no longer cleanly apply, but it'd reduce the pain a bit.

2021-11-03 10:00 UTC, ares commented
We decided to switch this to draft as the broader conversation on discourse is necessary first.

2021-11-03 15:21 UTC, sharvit commented
> We decided to switch this to draft as the broader conversation on discourse is necessary first.

Sounds good, I would like to bring this discussion again after the branching

2022-01-05 13:00 UTC, adamruzicka commented
Has the discussion already happened? Does anyone have a link to it?

2022-01-05 13:09 UTC, ekohl commented
AFAIK it hasn't.

2022-03-07 22:14 UTC, ezr-ondrej commented
Thanks @sharvit I believe this is opened for too long and won't get rebased.
I'm closing for now, but if @Ron-Lavi or @MariaAga feel like it, it would be worth revisiting ^_^

2022-03-07 22:14 UTC, closed without merging