Fixes #27024 - Adding audit cleanup duration and update rake task
theforeman/foreman pull request #8844
Opened 2021-10-14 10:35 UTC by domitea

Adding setting 'audit_period' to know how long saved audits user wants.
Also updating rake task for cleanup to reflect this setting

This is a complementary PR for https://github.com/theforeman/foreman-packaging/pull/7150

2021-10-18 08:12 UTC, ezr-ondrej commented
There is a rubocop failure, could you take a look into that? :)

2021-10-18 08:43 UTC, ezr-ondrej requested changes
We should document that we are leaving out `Template` audits.
I've tried to improve the texts a bit, but feel free to disregard it, or improve those improvements even bit more :)

2021-10-18 08:43 UTC, ezr-ondrej commented on lib/tasks/audits.rake
> +    audits = get_audits_without_templates
I don't see the old method (`get_audits`) used, can we remove that one?

2021-10-18 08:43 UTC, ezr-ondrej commented on lib/tasks/audits.rake
> +  If both is not defined, task ends without removing any audits.
```suggestion
  If both Setting and parameter are undefined, task finishes without cleaning any audits.
  Template audits are left uncleaned.
```

2021-10-18 08:43 UTC, ezr-ondrej commented on app/registries/foreman/settings.rb
> +      description: N_('Duration in days to preserve saved audits. When the audit reaches given time, it will be removed. Leave empty for disable this feature.'),
```suggestion
      description: N_('Duration in days to preserve audits for. Leave empty to disable the audits cleanup.'),
```

2021-10-19 16:56 UTC, ezr-ondrej reviewed
Works as expected :+1:
One more message improvement tho, it is not clear to me when I run the task manally, what should I do to continue using it, mentioning settings in the message is IMHO usefull.

2021-10-19 16:56 UTC, ezr-ondrej commented on lib/tasks/audits.rake
> +      puts "No days to keep is defined, exiting..."
We should let the users of the old task know where to set the required period.
```suggestion
      puts "The interval for keeping the Audits is not defined in the settings, exiting..."
```

2021-10-20 09:55 UTC, domitea commented on lib/tasks/audits.rake
> +      puts "No days to keep is defined, exiting..."
Good point!

2021-10-20 09:55 UTC, domitea commented
Thanks @ezr-ondrej for comments, PR updated.

2021-10-20 11:01 UTC, ezr-ondrej commented
[test katello]

2021-10-20 15:03 UTC, ezr-ondrej approved these changes
Thanks @domitea ! :+1:

2021-10-20 15:03 UTC, merged