Fixes #33697 - Registration - smart proxy features
theforeman/foreman pull request #8855
Opened 2021-10-19 06:46 UTC by stejskalleos

Registration through smart proxy works only if proxy
have enabled 'Templates' and 'Registration features'.

This fix proxy selection in UI form and generating command via API.

Related PR:
* https://github.com/theforeman/smart-proxy/pull/802

2021-10-19 07:29 UTC, ezr-ondrej requested changes

2021-10-19 07:29 UTC, ezr-ondrej commented on app/controllers/registration_commands_controller.rb
> +    with_templates.intersection(with_registration)
This can definitelly use the `with_features` scope :)
```
SmartProxy.with_features('Templates', 'Registration')
```

2021-10-19 07:29 UTC, ezr-ondrej commented on app/controllers/concerns/foreman/controller/registration_commands.rb
> +    template_f = Feature.find_by(name: 'Templates')
we have named scope `with_features` so you can simplify this by `SmartProxy.authorized.with_features('Templates', 'Registration').find`
That would make difficult to distinguish between proxy doesn't exists and proxy doesn't have the required features (doable, but harder).
Another way to simplify this would be `proxy_features = @smart_proxy.features.map(&:name)` and then `unless proxy_features.include?() && proxy_features.include?()`

2021-10-19 08:54 UTC, stejskalleos commented on app/controllers/registration_commands_controller.rb
> +    with_templates.intersection(with_registration)
You can't :)

I need to select proxies that have BOTH features. `SmartProxy.with_features('Templates', 'Registration')` will select all proxies that `Templates` OR `Registration` feature.

And I wasn't able find the way how to fix `with_features` to return proxies that have only both features.

2021-10-19 09:00 UTC, ekohl commented on app/controllers/registration_commands_controller.rb
> +    with_templates.intersection(with_registration)
I would still say that you can use `with_features('Templates', 'Registration')` and then in code go over the result and check if they have both features.

Another thing to consider is enhancing the Smart Proxy side. A Smart Proxy module can depend on another. So if registration always needs templates, declare it there. While it's removed in [this patch](https://github.com/theforeman/smart-proxy/commit/db33bc6780e28b5d694a1be6642e637aff59936f), it shows exactly how it can be done.

The result is that if templates is disabled, the registration feature will fail to start. Then the Registration feature is not recognized by Foreman which the installer will warn about.

It is still good to also enhance the Foreman side so I'm arguing for both. Big fan of defensive programming here ;)

2021-10-19 09:12 UTC, stejskalleos commented on app/controllers/registration_commands_controller.rb
> +    with_templates.intersection(with_registration)
+1 for the smart_proxy, I'll post the PR.

> I would still say that you can use with_features('Templates', 'Registration') and then in code go over the result and check if they have both features.

Sounds good, I'll update the PR.

2021-10-19 09:20 UTC, ekohl commented on app/controllers/registration_commands_controller.rb
> +    with_templates.intersection(with_registration)
Another idea you can check. Perhaps `SmartProxy.with_features('Templates').with_features('Registration')` gives you `AND` behavior.

2021-10-21 06:38 UTC, stejskalleos commented on app/controllers/registration_commands_controller.rb
> +    with_templates.intersection(with_registration)
> SmartProxy.with_features('Templates').with_features('Registration') gives you AND behavior.

That gives me empty array:

```
SELECT "smart_proxies".* FROM "smart_proxies" INNER JOIN "smart_proxy_features" ON "smart_proxy_features"."smart_proxy_id" = "smart_proxies"."id" INNER JOIN "features" ON "features"."id" = "smart_proxy_features"."feature_id" WHERE "features"."name" = 'Templates' AND "features"."name" = 'Registration' ORDER BY smart_proxies.name

=> []
```

Maybe I could add transaction for selecting the features, that would reduce number of queries

2021-10-21 07:34 UTC, adamruzicka commented on app/controllers/registration_commands_controller.rb
> +    with_templates.intersection(with_registration)
There might be a better way how to express this with activerecord or arel, but this seems to work
```
SmartProxy.joins("INNER JOIN smart_proxy_features AS spf1 ON smart_proxies.id = spf1.smart_proxy_id")
          .joins("INNER JOIN smart_proxy_features AS spf2 ON smart_proxies.id = spf2.smart_proxy_id")
          .joins("INNER JOIN features AS f1 ON f1.id = spf1.feature_id")
          .joins("INNER JOIN features AS f2 ON f2.id = spf2.feature_id")
          .where(f1: { name: "Ansible" }, f2: { name: "SSH" })
```

2021-10-21 10:52 UTC, stejskalleos commented on app/controllers/registration_commands_controller.rb
> +    with_templates.intersection(with_registration)
Question is how much is this readable ans easier to understand what's going on than the current version.
Users don't have much proxies in general, even if they had like 20 proxies, there won't be any performance problem.

2021-10-21 11:10 UTC, ekohl commented on app/controllers/registration_commands_controller.rb
> +    with_templates.intersection(with_registration)
I'm also leaning to 2 statements. You essentially want the intersection of `SmartProxy.with_features('Templates')` and `SmartProxy.with_features('Registration')`. Reading `SmartProxy.with_features('Templates') & SmartProxy.with_features('Registration')` is easier to follow than the complex join statements. (Note: I'm not sure my syntax exactly works, but you get the point).

2021-10-22 09:41 UTC, ezr-ondrej commented on app/controllers/registration_commands_controller.rb
> +    with_templates.intersection(with_registration)
Yeah, let us stay at the first version xD
Could you just use ` & ` instead of intersection? it is ruby 2.6 and we are still formally supporting 2.5.

2021-10-22 12:01 UTC, ekohl commented on app/controllers/registration_commands_controller.rb
> +    with_registration = Feature.find_by(name: 'Registration')&.smart_proxies.to_a
I think `SmartProxy.with_feature('Templates')` is easier to read. My reasoning is that you read from left to right and then it's clear you get SmartProxy instances that happen to have a feature.
```suggestion
    with_templates    = SmartProxy.with_features('Templates').to_a
    with_registration =  SmartProxy.with_features('Registration').to_a
```

2021-10-25 13:11 UTC, stejskalleos commented on app/controllers/registration_commands_controller.rb
> +    with_templates.intersection(with_registration)
Do we still support `2.5`? Because when I try `bundle install` on `develop` with `ruby-2.5.1` I got error:
```
globalid-0.5.1 requires ruby version >= 2.6.0, which is incompatible with the current version, ruby 2.5.1p57
```

2021-10-25 13:14 UTC, ekohl commented on app/controllers/registration_commands_controller.rb
> +    with_templates.intersection(with_registration)
Yes, Debian 10 uses Ruby 2.5 so that's still a target platform. There is a globalid-0.5.2 which does support Ruby 2.5 but 0.5.2 is >= 2.6. I wonder why it pulls in 0.5.1. Perhaps a lockfile?

2021-10-25 13:22 UTC, stejskalleos commented on app/controllers/registration_commands_controller.rb
> +    with_templates.intersection(with_registration)
> Perhaps a lockfile?

Ah, the classic one :) After removing a lockfile 2.5 works fine

2021-10-29 11:59 UTC, ekohl reviewed
The code looks sensible. Some minor phrasing suggestions. I'm not a native speaker either so I'm not sure what's best.

2021-10-29 11:59 UTC, ekohl commented on app/controllers/concerns/foreman/controller/registration_commands.rb
> +      message = N_("Proxy doesn't have enabled one of the following features: 'Registration', 'Templates'")
I'm not sure if lacks or misses is better, but this is shorter:
```suggestion
      message = N_("Proxy lacks one of the following features: 'Registration', 'Templates'")
```

2021-10-29 11:59 UTC, ekohl commented on app/controllers/api/v2/registration_commands_controller.rb
> +        param :smart_proxy_id, :number, desc: N_("ID of the Smart Proxy. Proxy must have enabled following features: 'Templates' and 'Registration'")
```suggestion
        param :smart_proxy_id, :number, desc: N_("ID of the Smart Proxy. This Proxy must have enabled both the 'Templates' and 'Registration' features")
```

2021-11-03 13:05 UTC, ezr-ondrej approved these changes
One nit, but overall looks ready to me :+1: 
I'd like to merge now as this I'd consider a bugfix.

2021-11-03 13:05 UTC, ezr-ondrej commented on test/controllers/registration_commands_controller_test.rb
> +      proxy = FactoryBot.create(:smart_proxy, features: features)
I'd love if we have additional proxies with only one feature and make sure those won't appear, but it's not crucial :)

2021-11-04 08:29 UTC, merged