Fixes #33757 - reports button link to new reports
theforeman/foreman pull request #8862
Opened 2021-10-21 07:38 UTC by lzap

Reports are changing to Host Reports:

https://community.theforeman.org/t/host-reports-plugin-in-foreman-3-1/25796

Let's advertise this on the old page and allow people to migrate to the new endpoint and format.

(Edit: Previously this patch was also about redirecting Reports button on the host detail page, but I changed my mind. We can do this via Deface if we decide it is too confusing to have two Reports button on the page.)

2021-10-21 10:42 UTC, ofedoren commented
If we're deprecating/changing things in core, could you please as part of this PR also add a warning on the Config Reports page? Just paste the following snippet to the `app/views/config_reports/index.html.erb`:
```erb
<% if defined?(ForemanHostReports) %>
  <%= alert class: 'alert-warning',
    header: _('This page is going to be removed'),
    text: "</br>".html_safe +
          _("Go to Monitor > Host Reports for up-to-date information.") +
          "</br>".html_safe +
          _("Please, read Upgrade notes to migrate to the new format.") %>
<% end %>
```
Of course, please modify the message to be more appropriate.

2021-10-21 13:15 UTC, lzap commented on app/views/config_reports/index.html.erb
> +<% end %>
Added. Question: should we only show this when the plugin is installed OR to all of users to advertise this feature a bit more?

2021-10-22 13:14 UTC, lzap commented
I have repurposed this patch. This is solely just a warning now. I think we can always show it, not just when Foreman Host Reports plugin is installed. This will help to spread the news more. We want users to migrate during or after upgrade to 3.1.

2021-10-25 07:50 UTC, Ron-Lavi commented
JS test error not related, being fixed in https://github.com/theforeman/foreman/pull/8863

2021-10-25 10:00 UTC, tbrisker requested changes
It would be good to add a link to somewhere explaining why this page will be removed and what will be replacing it and when, e.g. the discourse post on the subject.

2021-10-25 10:00 UTC, tbrisker commented on app/views/config_reports/index.html.erb
> +        _("Go to Monitor > Host Reports for up-to-date information.") +
Will this page be there if the plugin isn't installed?

2021-10-25 10:12 UTC, ofedoren commented on app/views/config_reports/index.html.erb
> +        _("Go to Monitor > Host Reports for up-to-date information.") +
No, and that's why I suggested to wrap it with:
```ruby
<% if defined?(ForemanHostReports) %>
...
<% end %>
```

2021-10-25 10:38 UTC, tbrisker commented on app/views/config_reports/index.html.erb
> +        _("Go to Monitor > Host Reports for up-to-date information.") +
We could just add the alert from the plugin using deface in that case, while deface is not a good permanent fix it could be the easiest for adding something that will only be there for a couple of versions.

2021-10-25 15:25 UTC, lzap commented on app/views/config_reports/index.html.erb
> +        _("Go to Monitor > Host Reports for up-to-date information.") +
Right, let me rephrase this completely.

2021-10-25 15:25 UTC, lzap commented
Yeah, I created a forum placeholder where I am going to put migration and installation instructions: https://community.theforeman.org/t/migrating-reports-to-the-new-format-in-foreman-3-1/25846

Rebased.

2021-10-26 12:38 UTC, lzap commented
Fixed the HTML link, this is now ready, @tbrisker can we hit 3.1RC1 with this one? This is zero risk, we can merge afterwards.

2021-10-26 14:43 UTC, ofedoren submitted a review, later dismissed
From my perspective this is OK now. The only thing is a weird commit.

2021-10-26 14:53 UTC, lzap commented
Damn! Fixed.

2021-10-27 06:04 UTC, tbrisker approved these changes
Thanks @lzap ! will fix commit message on merge (it still talks about the button...)

2021-10-27 06:05 UTC, merged