Fixes #33769 - Windows client installation type
theforeman/foreman pull request #8866
Opened 2021-10-22 12:23 UTC by ananace

This will currently only handle a single difference - Windows Server vs Windows.
Not things like Windows Server Standard vs Windows Server Core, or Windows vs Windows Education, etc.

As Windows has a rather ridiculous list of permutations in that regard I feel that keeping the difference down to Client vs Server is the more apt choice, as that's likely to be the most major difference.

2021-11-03 09:59 UTC, ShimShtein requested changes, later dismissed
Looks good, one nitpick though: could we prefix the fixtures with `puppet`, since we already have `ansible_facts_windows.json`

2021-11-04 08:16 UTC, lzap approved these changes
LGTM Thanks

2021-11-04 08:17 UTC, merged

2021-11-04 08:20 UTC, ShimShtein commented
@lzap, should we add the same logic also to ansible fact parser?

2021-11-04 08:21 UTC, lzap commented
I am not working on it, when it comes I will happily merge it :-)

2021-11-04 08:27 UTC, ShimShtein commented
@ananace, thanks for the PR. Can we please add the same logic also to [ansible fact parser](https://github.com/theforeman/foreman/blob/develop/app/services/foreman_ansible/operating_system_parser.rb)?

2021-11-04 09:56 UTC, ananace commented
Don't actually have any Windows machines using Ansible to test it in a real-world scenario with, but I guess I could write the same logic in there as well and hope it does the same thing?

2021-11-04 10:51 UTC, ShimShtein commented
I see we have at least sample json output in foreman repo. I suppose working against that file would be good enough, and in my opinion better than having the logic non-consistent between ansible and puppet.

2021-11-05 08:47 UTC, ananace commented
Having had a look at the Ansible fact fixture and the OS parsing code, I don't think the patch would make sense there.

On Puppet, the OS name was parsed based on the `os.name` fact, which was always "windows" regardless of it was a Windows Server or regular Windows install.

For Ansible it instead seems to derive the OS name by whitespace-stripping `ansible_os_name` or `ansible_distribution`, which would be "MicrosoftWindowsServer2019Datacenter" for the provided facts hash. So for a Windows 10 install I assume that the Ansible parser would - if using the same machine the Puppet facts were taken from - name the OS "Windows10Education"