Fixes #33773 - use correct fields for translations
theforeman/foreman pull request #8869
Opened 2021-10-25 10:55 UTC by upadhyeammit

2021-10-25 10:56 UTC, upadhyeammit commented
@tbrisker I have not updated the actual translations yet, after confirming changes are correct will do the update. Request to review, thank you!

2021-10-25 13:11 UTC, tbrisker requested changes
looks like the french version needs quite a lot more work, there's lots of mismatching keys there

2021-10-25 13:11 UTC, tbrisker commented on locale/de/foreman.po
> +msgstr "Fehler beim Importieren der Klasse %{kclass} for %{name}: existiert nicht in der Datenbank - wird ignoriert"
```suggestion
msgstr "Fehler beim Importieren der Klasse %{klass} for %{name}: existiert nicht in der Datenbank - wird ignoriert"
```

2021-10-25 13:11 UTC, tbrisker commented on locale/fr/foreman.po
> +msgstr "%<b> est utilisé par la ressource %{what} cachée"
```suggestion
msgstr "%{record} est utilisé par la ressource %{what} cachée"
```

2021-10-25 13:11 UTC, tbrisker commented on locale/fr/foreman.po
>  msgstr "Medium %%s non défini pour l'hôte '%{host}'"
```suggestion
msgstr "Medium %{os} non défini pour l'hôte '%{host}'"
```

2021-10-25 13:11 UTC, tbrisker commented on locale/fr/foreman.po
>  msgstr "%s utilisé"
this one also seems wrong. seems there are a lot of %s, %%s etc scattered around

2021-10-25 13:11 UTC, tbrisker commented on locale/fr/foreman.po
> +msgstr "Une erreur est survenue lors de la communication avec %%s : %{e}"
```suggestion
msgstr "Une erreur est survenue lors de la communication avec %{cr} : %{e}"
```

2021-10-25 13:11 UTC, tbrisker commented on locale/fr/foreman.po
> +msgstr "Impossible de créer l'entrée du domaine %%s : %{e}"
```suggestion
msgstr "Impossible de créer l'entrée du domaine %{name} : %{e}"
```

2021-10-25 13:11 UTC, tbrisker commented on locale/fr/foreman.po
> +msgstr "Architecture invalide '%%s' pour '%{os}'"
```suggestion
msgstr "Architecture invalide '%{arch}' pour '%{os}'"
```

2021-10-25 13:13 UTC, tbrisker commented
@upadhyeammit we probably need to correct the original translation in transifex and/or memsource so these fixes aren't overriden on the next pull

2021-10-29 16:44 UTC, upadhyeammit commented
The RH translation team is working on the fixes, hence I am closing the pr. Shall raise new pr once we have correct translations on transifex.

2021-10-29 16:44 UTC, closed without merging