Fixes #33791 - respect global settings precedence
theforeman/foreman pull request #8880
Opened 2021-10-27 12:01 UTC by ezr-ondrej

In the new registry we've forgot to force the global values precedence.
This forces the global values to be respected.

Lets fix nightlies

2021-10-27 12:16 UTC, ekohl reviewed
This makes me wonder if we need more integration tests. For example, one that retrieves the value from the API. Unit tests don't cover these kind of things

2021-10-27 12:16 UTC, ekohl commented on app/presenters/setting_presenter.rb
> +    readonly? ? SETTINGS[name.to_sym] : super
This does two lookups in `SETTINGS`. Can't we use `fetch()`?
```suggestion
    SETTINGS.fetch(name.to_sym) { super }
```

2021-10-27 12:19 UTC, ezr-ondrej commented on app/presenters/setting_presenter.rb
> +    readonly? ? SETTINGS[name.to_sym] : super
It does two only for the global settings, so it boils down to whether is `key?` more efficient then `fetch`, but I guess it's insignificant, so using yours ;)

2021-10-27 12:21 UTC, ezr-ondrej commented
> This makes me wonder if we need more integration tests. For example, one that retrieves the value from the API. Unit tests don't cover these kind of things

Well it depends, if then we test that the API uses the methods that we test by the unit tests then it actually does. I'm not against integration tests, but I'm against integration tests for everything.

This is weird funcionality tho, so the more tests for it the better :+1:

2021-10-27 12:25 UTC, ekohl commented
I now realize API was ambiguous. I meant the REST API. So more of an end-to-end test.

IMHO the challenge is to capture application behavior without blowing up the test suite execution time. That's a very fine line so I agree that we shouldn't have integration testing for everything.

2021-10-27 13:02 UTC, ekohl submitted a review, later dismissed
@tbrisker could you also take a look as well?

2021-10-27 13:06 UTC, ekohl requested changes
Btw, you opened a new issue but it's really a regression in a refactor. Can't we find that issue and Refs it? That would keep things consistent.

2021-10-27 13:06 UTC, ezr-ondrej commented
> I meant the REST API

Done :)

2021-10-27 13:08 UTC, ezr-ondrej commented
> Btw, you opened a new issue but it's really a regression in a refactor. Can't we find that issue and Refs it? That would keep things consistent.

Well, it was never implemented in the new DSL, so it's not clear which of the issues introduced it. The issue appeared when we switched to the DSL, but it's not where we introduced it...
I've connected the bug with the tracker for the DSL effort, isn't it enough?

2021-10-27 13:19 UTC, ekohl approved these changes
That works for me.

2021-10-27 14:55 UTC, tbrisker commented on app/presenters/setting_presenter.rb
> +    SETTINGS.fetch(name.to_sym) { super }
where does `super` go in this case? this class has no parent?

2021-10-27 15:31 UTC, ekohl commented on app/presenters/setting_presenter.rb
> +    SETTINGS.fetch(name.to_sym) { super }
There's `attribute :value` which probably does some magic with `ActiveModel`, but it's a good point.

2021-10-27 15:51 UTC, ezr-ondrej commented on app/presenters/setting_presenter.rb
> +    SETTINGS.fetch(name.to_sym) { super }
it includes ActiveModel::Attributes which defines the super method.
Do you think it would be more clear to call the attribute fetch ?

2021-10-27 17:39 UTC, ehelms commented
I can confirm this solved the nightly install breakage for me when running it.

2021-10-28 06:54 UTC, tbrisker commented on app/presenters/setting_presenter.rb
> +    SETTINGS.fetch(name.to_sym) { super }
Not crucial but i think that might be a bit clearer to read
```suggestion
    SETTINGS.fetch(name.to_sym, attribute(:value))
```

2021-10-28 06:57 UTC, tbrisker approved these changes
Merging now to unblock nightlies, we can followup with changing the fetch style in another pr.

2021-10-28 06:57 UTC, merged

2021-10-28 07:06 UTC, tbrisker commented on app/presenters/setting_presenter.rb
> +    SETTINGS.fetch(name.to_sym) { super }
opened https://github.com/theforeman/foreman/pull/8883 to propose this change, feel free to close it if you disagree

2021-11-03 16:41 UTC, ares commented
no need to CP, because 3.0 didn't use any setting defined through the DSL