Fixes #33882 - refresh host's global status after clearing a sub status
theforeman/foreman pull request #8909
Opened 2021-11-09 15:10 UTC by amirfefer

After clearing a failed status, the global should be refreshed as well, so the consistency keeps.

2021-11-09 16:40 UTC, ares requested changes
Please move this few lines above plus a functional test would be great. Then I'm happy to merge!

2021-11-09 16:40 UTC, ares commented on app/controllers/hosts_controller.rb
> +        @host.refresh_global_status!
this indeed fixes the issue, but it should happen regardless of the response type, so please move it after the `status.delete`

2021-11-09 17:01 UTC, amirfefer commented on app/controllers/hosts_controller.rb
> +        @host.refresh_global_status!
doesn't it impact only the new UI?

2021-11-09 19:29 UTC, amirfefer commented
Thanks @ares 👍
added a test

2021-11-10 10:03 UTC, ares commented on app/controllers/hosts_controller.rb
> +        @host.refresh_global_status!
It does, I couldn't find the place exactly where we render it on the old page. However it's a good idea to refresh the global status anyway (even when triggered from the old UI) as clearly this resulted in the state inconsistency when we check the host through API.

2021-11-10 20:32 UTC, amirfefer commented on webpack/assets/javascripts/react_app/components/HostDetails/Status/StatusActions.js
> +      handleSuccess: () => dispatch(getStatuses(hostName)),
After a successful status clearing, we need to pull the refreshed global status from the server so the user doesn't need  to refresh the entire page

2021-11-16 15:40 UTC, ares approved these changes
Nice, works well and fixes the issue of course. Thanks @amirfefer, merging!

2021-11-16 15:40 UTC, merged