Require Foreman::Gettext in initializers
theforeman/foreman pull request #8931
Opened 2021-11-18 12:34 UTC by stejskalleos

Fix deprecation warning the about initialization of auto-loaded constants

2021-11-18 12:39 UTC, ezr-ondrej requested changes

2021-11-18 12:39 UTC, ezr-ondrej commented on config/initializers/1_fast_gettext.rb
> +require "#{Rails.root}/lib/foreman/gettext/support"
can't we use the fact, that lib should be in the require path and make it bit more straight forward:
```suggestion
require 'foreman/gettext/all_domains'
require 'foreman/gettext/debug'
require 'foreman/gettext/support'
```
if that is not feasible, we should use [Pathname#join](https://ruby-doc.org/stdlib-1.9.3/libdoc/pathname/rdoc/Pathname.html#method-i-join)
`Rails.root.join('lib', 'foreman', ...)`

2021-11-18 13:42 UTC, ezr-ondrej commented on lib/foreman/gettext/debug.rb
> +    module Debug
Just a note: this is only needed with the classic loader, when we switch to zeitwerk, this shouldn't matter :)

2021-11-18 14:03 UTC, ezr-ondrej approved these changes
Nice and sraightforward :+1:

2021-11-18 14:03 UTC, merged

2021-11-19 08:13 UTC, lzap commented
For the record, fast_gettext can be extremely slow when you load all languages into memory, it takes several seconds. That is the reason why it was so hacky. Luckily, this patch did not seem to break this behavior:

Before the patch:

```
2021-11-19T09:11:46 [D|app|] Slow initializers:
2021-11-19T09:11:46 [D|app|]     238.44  ./config/initializers/foreman.rb
2021-11-19T09:11:46 [D|app|]     255.61  ./config/initializers/apipie.rb
```

After the patch:

```
2021-11-19T09:12:51 [D|app|] Slow initializers:
2021-11-19T09:12:51 [D|app|]     240.57  ./config/initializers/foreman.rb
2021-11-19T09:12:51 [D|app|]     255.05  ./config/initializers/apipie.rb
```