Loading constants in initializers/active_record_extensions.rb
theforeman/foreman pull request #8939
Opened 2021-11-22 13:17 UTC by stejskalleos

2021-11-22 16:09 UTC, tbrisker commented on config/initializers/active_record_extensions.rb
>  class ActiveRecord::Base
TBH, this initializer predates the introduction of ApplicationRecord in rails. Probably most if not all of the extensions actually belong there.

2021-11-23 11:22 UTC, ezr-ondrej requested changes
Apart of the requires, big :+1:
It's a nice cleanup :)

2021-11-23 11:22 UTC, ezr-ondrej commented on app/models/application_record.rb
> +require_relative 'concerns/parameterizable'
`concerns` subfolders are in a autoload path, so you should not need this, it should work by leaving it out to autoloader to load those. Being in autoload_path means they are roots and `concerns/host_mix` => `HostMix` is expected by autoloader.

I believe the previous require is here by mistake and can be removed while we are at it.

2021-11-23 14:33 UTC, ezr-ondrej approved these changes
Thank you @stejskalleos ! :+1:

2021-11-23 14:33 UTC, merged

2021-11-25 12:13 UTC, lzap commented
Why Hostmix was moved from `Host::Hostmix` into the root namespace? It broke foreman_setup for no reason. Just wondering if we could keep the namespace. Anyway, thanks for driving the change :-)

I fixed foreman_setup.

2021-11-25 12:24 UTC, ezr-ondrej commented
> Why Hostmix was moved from `Host::Hostmix` into the root namespace? It broke foreman_setup for no reason. Just wondering if we could keep the namespace. Anyway, thanks for driving the change :-)

I could have stayed in the namespace, but it was not too logical, as `Host` would suggest it's a Host extension, which it is not.
Tho sorry for disturbing plugins again, this one I've even checked, but didn't find any uses.