Fixes #33981 - fix the RHEL OS name parsing
theforeman/foreman pull request #8943
Opened 2021-11-23 14:03 UTC by ares

When the parser lived in the foreman_ansible plugin, it started to
prefer the lsb facts over the distribution one, which is correct
behavior. See
https://github.com/theforeman/foreman_ansible/commit/ba50f37a00fb55c9695b5ef0cb80987f8eb532f8
for more details.

However the Red Hat Enterprise Linux is reported as either
RedHatEnterprise for RHEL 8 or RedHatEnterpriseServer or
RedHatEnterpriseWorkstation for RHEL 7. When user has more fact sources
like RHSM or Puppet, the host flips between 2 operating systems. This
add the additional mapping of these extra values.

It also adds anonymized facts snapshots from RHEL 7 and RHEL 8 machines.

2021-11-23 14:04 UTC, ares commented
cc @xprazak2 and @ezr-ondrej

2021-11-23 16:31 UTC, ezr-ondrej approved these changes
I do not love this, but as a quick fix it's good enough.
We can do better when Dominik's refactoring gets in.

2021-11-23 16:33 UTC, ezr-ondrej requested changes

2021-11-23 16:33 UTC, ezr-ondrej commented on app/services/foreman_ansible/operating_system_parser.rb
> +          distribution = 'RedHat'
actually we have `distribution = RedHat` and later on we pick the same fact and do something else (add `_Workstation`)
Can't we join those two if statements?

2021-11-24 10:27 UTC, ezr-ondrej approved these changes
Thanks @ares! :+1:

2021-11-24 11:43 UTC, ezr-ondrej commented
Katello failure not related.

2021-11-24 11:45 UTC, merged

2021-12-11 16:17 UTC, ezr-ondrej commented
CP 3.1: 25d536f51