Puppet Environment in taxonomy ignore_types
theforeman/foreman pull request #8962
Opened 2021-12-02 08:45 UTC by stejskalleos

Fix for issue with `uninitialized constant Environment`.

Steps to reproduce the issue:
```ruby
organization = Organization.first
organization.update ignore_types: ['Environment']

organization.selected_ids # => Error with uninitialized constant Environment

```

2021-12-02 16:38 UTC, ezr-ondrej requested changes
I'm little bit worried that the migration won't do what we want it to do.
Environments won't work out of the box unfortunatelly, so I'd move that effort to the `foreman_puppet` Plugin.

2021-12-02 16:38 UTC, ezr-ondrej commented on db/migrate/20211202071418_environment_in_taxonomy_ignore_types.rb
> +        new_types = tax.ignore_types.map { |type| type == "Environment" ? "ForemanPuppet::Environment" : type }
This is little problematic, I believe we should do this migration in `foreman_puppet` as we will have to deal with:

https://github.com/theforeman/foreman/blob/b1f03b375e18c8da498ba0944b2565f53441833c/app/services/tax_host.rb#L32

which will cause `ids['foreman_puppet/environment_ids']` and that is meaningless.
above that, now we do not have `environment_ids` in `TaxHost::HASH_KEYS`

2021-12-06 11:33 UTC, ezr-ondrej approved these changes
Thank you @stejskalleos ! :+1:

2021-12-06 11:33 UTC, merged

2021-12-06 11:34 UTC, ezr-ondrej commented
CP 3.1: c10798b88

2022-01-24 14:09 UTC, ekohl commented
I think the issue mentioned was not relevant. This should have opened its own issue.