Fixes #34360 - prepare for Host Reports migration
theforeman/foreman pull request #9078
Opened 2022-02-01 11:49 UTC by lzap

Some of the core features are not possible to override from Host Reports. This patch adds some if statements until we drop legacy reports from core.

The patch also improves test fixtures and creates a script that allows uploading of reports for easier testing and development of reports. It will be soon removed but it will be very useful in the transition period if we encounter any bugs.

2022-02-01 11:51 UTC, lzap commented on app/controllers/hosts_controller.rb
> +        end
This would end up being ugly hack in the plugin, it is just a SQL optimalization.

2022-02-01 11:52 UTC, lzap commented on app/models/host/managed.rb
> +  end
Had to learn the hard way that it is not possible to override Ruby on Rails associations from plugins. At least it does not work for my case, not sure why.

2022-02-01 11:54 UTC, lzap commented on test/active_support_test_case_helper.rb
>    end
The patch reformats and corrects all our fixtures so they are actually valid payloads for the API call. Unfortunately, we use them in many tests where we actually build the call manually. Alternatively, I can change about 25 places in the codebase, but these tests will be deleted soon as well as this change.

2022-02-01 11:55 UTC, lzap commented on test/static_fixtures/reports/applied.json
>  }
These fixtures were actually invalid JSON, I fixed them and reformatted them all.

2022-02-01 11:55 UTC, lzap commented on script/reformat-fixtures
> +done
Helper script to reformat all fixtures. I find this very useful in foreman hosts plugin.

2022-02-01 17:53 UTC, ofedoren requested changes
Thanks, @lzap! LGTM, no objections so far except one:

When I navigate to Host index page and click on the Last report it will lead me to the `/hosts/hostname/config_reports/last`, it needs to redirect to the latest host report.

AFAIU we can try to update it via plugin, but since we put conditions here already, I guess we can do it here.

2022-02-01 17:53 UTC, ofedoren commented on .gitignore
> +script/send-fixture*.conf
Again, as with https://github.com/theforeman/smart_proxy_reports/pull/5#discussion_r725113553, I'd like to have an example for the config files.

2022-02-02 10:02 UTC, lzap commented on app/models/host/managed.rb
> +  end
@ezr-ondrej can you show me how to do this from plugin?

2022-02-02 10:02 UTC, lzap commented on app/controllers/hosts_controller.rb
> +        end
I can probably do this via filter. Let me look on this.

2022-02-02 10:04 UTC, lzap commented on .gitignore
> +script/send-fixture*.conf
Yeah this is what I do with many of my shell scripts to be able to override defaults. Looks like this is confusing and not really needed as there is an argument so let me remove this. Use arguments.

2022-02-02 10:10 UTC, lzap commented on app/controllers/hosts_controller.rb
> +        end
Actually not, an explicit method is needed.

2022-02-02 10:12 UTC, lzap commented on app/models/host/managed.rb
> +  end
Ondrej says it is very hacky to do from plugin so the agreement is to keep it this way.

2022-02-02 10:17 UTC, lzap commented on app/models/host/managed.rb
> +  end
There might be way actually to use default_scope in HostStatus. Let me test this.

2022-02-02 14:15 UTC, lzap commented on app/models/host/managed.rb
> +  end
I tried to implement this via default scope on HostReportStatus but unfortunately this does not work. That model does use STI so I cannot limit what other associations see. I think if statement is the only option if we don't want to do an ugly hack like in Puppet.

2022-02-02 14:17 UTC, lzap commented
So I just created an explicit load method that can be overriden from the plugin for the first case.

The second case is a temporary solution.

To test this, upload some reports using the shell script provided in this patch and try to open index and show pages of reports.

2022-02-02 15:24 UTC, ofedoren requested changes
@lzap, same issues:

 - On host index page try to search `report_failures = 1`:
![ScreenShot-1643815235826](https://user-images.githubusercontent.com/32508194/152183385-1a47e316-696d-4352-b8a8-143b7eec10ae.png)
 - On host index page try to click on the last report:
 
![ScreenShot-1643815472200](https://user-images.githubusercontent.com/32508194/152183630-7a81f96c-882d-44e5-92ca-f1e1b15e9a99.png)

2022-02-02 16:09 UTC, lzap commented
Not sure why it fails the query runs fine here:

```
[2] pry(main)> HostReport.where(:host_id => [1]).reorder('').group(:host_id).maximum(:id)
=> {}
```

The second problem - you click on what exactly?

2022-02-02 16:30 UTC, lzap commented
Okay fixed the SQL problem.

The link I can fix later I don't have time today anymore and I am not working for the rest of the week. Let's hit 3.2 with the core patch and I can fix the link from the plugin:

```ruby
    def last_report_column(record)
      time = record.last_report? ? date_time_relative_value(record.last_report) : ""
      link_to_if_authorized(time,
        hash_for_host_config_report_path(:host_id => record.to_param, :id => "last"),
        last_report_tooltip(record))
    end

    def last_report_tooltip(record)
      opts = { :rel => "twipsy" }
      date = record.last_report.nil? ? '' : date_time_absolute_value(record.last_report) + ", "
      if @last_report_ids[record.id]
        opts["data-original-title"] = date + _("view last report details")
      else
        opts.merge!(:disabled => true, :class => "disabled", :onclick => 'return false')
        opts["data-original-title"] = date + _("report already deleted") unless record.last_report.nil?
      end
      opts
    end
```

2022-02-02 18:01 UTC, ofedoren approved these changes
Thanks, @lzap, the search is fixed and I think we can fix the link from the plugin.

Tests are green, the changes are pretty safe and will be applied only if `host_reports` is installed.

2022-02-02 18:02 UTC, merged

2022-02-03 21:15 UTC, ezr-ondrej commented on app/models/host/managed.rb
> +  end
In retrospect, this should have been `Foreman::Plugin.installed?('....')`