Fixes #34375 - allow passing empty attributes for facets
theforeman/foreman pull request #9083
Opened 2022-02-02 12:43 UTC by ezr-ondrej

Facets were rejecting empty attributes to not create empty facet.
Tho we want to pass empty arrays to empty the related associations from facets.

Empty facet record is a trade off we are able to accept.

2022-02-10 14:15 UTC, ShimShtein requested changes
I am missing one test with an empty facet, but it looks good.

@ezr-ondrej , Can we add one?

2022-02-10 15:53 UTC, ShimShtein approved these changes
Looks good!

2022-02-10 15:54 UTC, merged

2022-02-10 15:54 UTC, ShimShtein commented
Merged, thanks @ezr-ondrej!

2022-02-10 15:56 UTC, ezr-ondrej commented
Not in 3.2 yet, should get cherry-picked to 3.2 and 3.1 :)

2022-02-17 21:51 UTC, ezr-ondrej commented
CP 3.2: 526b75afb