Fixes #34396 - job report tweaks
theforeman/foreman pull request #9093
Opened 2022-02-04 14:55 UTC by ares

This change adds few enhancements to the existing Job report. The report
is used with REX plugin, which has a button "Create Report" in job
detail page. Clicking that button takes user to the render report form
and fills in the job id input.

The enhancements:
1) rename the template to Job - Invocation Report to be more consistent
   with other report templates
2) Add missing `-` to closing `%>` erb tags to avoid empty lines in the
   output
3) don't fail on ended_at being nil, meaning on jobs that are still
   running, instead use empty value in such case

The follow up is necessary in the REX plugin so the setting default
value reflects the new name.

2022-02-04 15:00 UTC, adamruzicka commented on app/views/unattended/report_templates/job_-_invocation_report.erb
> +            'Finished': task.ended_at.nil? ? '' : format_time(task.ended_at),
Wouldn't it be more correct to use `nil` instead of an empty string?

2022-02-16 10:07 UTC, adamruzicka requested changes

2022-02-16 10:07 UTC, adamruzicka commented on app/views/unattended/report_templates/job_-_invocation_report.erb
> +            'Finished': task.ended_at.nil? ? '' : format_time(task.ended_at),
Also `#nil?` apparently is not allowed on Time jail

```
2022-02-16T10:58:24 [E|app|82beecb7] Error performing TemplateRenderJob (Job ID: 422e9b3c-bd74-428b-adb9-0770a4553f8c) from Dynflow(default) in 90.13ms: Safemode::NoMethodError (undefined method '#nil?' for Safemode::Jail (Time)):                                                
 82beecb7 | /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/safemode-1.3.6/lib/safemode/jail.rb:22:in `method_missing'                                                                                                                                                                       
 82beecb7 | Job - Invocation Report:66:in `block (2 levels) in bind'                                                                                                                                                                                                                  
 82beecb7 | /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.7/lib/active_record/relation/delegation.rb:87:in `each'                                                                                                                                                       
 82beecb7 | /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.7/lib/active_record/relation/delegation.rb:87:in `each'                                                                                                                                                       
 82beecb7 | /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/safemode-1.3.6/lib/safemode/jail.rb:31:in `method_missing'                                                                                                                                                                       
 82beecb7 | Job - Invocation Report:60:in `block in bind'                                                                                                                                                                                                                             
 82beecb7 | /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.7/lib/active_record/relation/batches/batch_enumerator.rb:64:in `block in each'                                                                                                                                
 82beecb7 | /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.7/lib/active_record/relation/batches.rb:238:in `block in in_batches'                                                                                                                                          
 82beecb7 | /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.7/lib/active_record/relation/batches.rb:222:in `loop'                                                                                                                                                         
 82beecb7 | /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.7/lib/active_record/relation/batches.rb:222:in `in_batches'                                                                                                                                                   
 82beecb7 | /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.7/lib/active_record/relation/batches/batch_enumerator.rb:64:in `each'                                                                                                                                         
 82beecb7 | /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.7/lib/active_record/relation/batches/batch_enumerator.rb:64:in `each'                                                                                                                                         
 82beecb7 | /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/safemode-1.3.6/lib/safemode/jail.rb:31:in `method_missing'                                                                                                                                                                       
 82beecb7 | Job - Invocation Report:59:in `bind'
```

2022-02-16 10:28 UTC, ares commented
Interesting, then https://github.com/svenfuchs/safemode/blob/master/lib/safemode/core_jails.rb#L43 probably does not work, however https://github.com/svenfuchs/safemode/blob/master/lib/safemode/core_jails.rb#L101 is present, so I'll use that. Also I agree re using nil instead. Should be ready for rereview now.

2022-02-16 11:20 UTC, adamruzicka requested changes

2022-02-16 11:20 UTC, adamruzicka commented on app/views/unattended/report_templates/job_-_invocation_report.erb
> +            'Finished': task.ended_at.blank? ? nil : format_time(task.ended_at),
Hmm, this didn't seem to help
```
2022-02-16T11:51:44 [E|app|7234de29] Error performing TemplateRenderJob (Job ID: aa228320-9d9d-4c68-92be-f79666f8bc7b) from Dynflow(default) in 232.96ms: Safemode::NoMethodError (undefined method '#blank?' for Safemode::Jail (Time)):                                             
 7234de29 | /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/safemode-1.3.6/lib/safemode/jail.rb:22:in `method_missing'                                                                                                                                                                       
 7234de29 | Job - Invocation Report:66:in `block (2 levels) in bind'                                                                                                                                                                                                                  
 7234de29 | /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.7/lib/active_record/relation/delegation.rb:87:in `each'                                                                                                                                                       
 7234de29 | /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.7/lib/active_record/relation/delegation.rb:87:in `each'                                                                                                                                                       
 7234de29 | /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/safemode-1.3.6/lib/safemode/jail.rb:31:in `method_missing'                                                                                                                                                                       
 7234de29 | Job - Invocation Report:60:in `block in bind'                                                                                                                                                                                                                             
 7234de29 | /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.7/lib/active_record/relation/batches/batch_enumerator.rb:64:in `block in each'                                                                                                                                
 7234de29 | /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.7/lib/active_record/relation/batches.rb:238:in `block in in_batches'                                                                                                                                          
 7234de29 | /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.7/lib/active_record/relation/batches.rb:222:in `loop'                                                                                                                                                         
 7234de29 | /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.7/lib/active_record/relation/batches.rb:222:in `in_batches'                                                                                                                                                   
 7234de29 | /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.7/lib/active_record/relation/batches/batch_enumerator.rb:64:in `each'                                                                                                                                         
 7234de29 | /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.7/lib/active_record/relation/batches/batch_enumerator.rb:64:in `each'                                                                                                                                         
 7234de29 | /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/safemode-1.3.6/lib/safemode/jail.rb:31:in `method_missing'                                                                                                                                                                       
 7234de29 | Job - Invocation Report:59:in `bind'
```

It looks like only `::Time` has a custom jail, however `task.ended_at` is a `ActiveSupport::TimeWithZone`, which does not inherit the same jail as `::Time`.

```
# In rails console
> task_jail = ForemanTasks::Task.first.to_jail.started_at.class
=> ActiveSupport::TimeWithZone

> Time.now.class
=> Time

> Time.now.to_jail.nil?
=> false

> Time.zone.now.class
=> ActiveSupport::TimeWithZone

> Time.zone.now.to_jail.nil?
Safemode::NoMethodError: undefined method '#nil?' for Safemode::Jail (Time)
from /home/aruzicka/.rvm/gems/ruby-2.7.0/gems/safemode-1.3.6/lib/safemode/jail.rb:22:in `method_missing'
```

It is ugly, but this seems to work
```suggestion
            'Finished': task.ended_at.respond_to?(:nil?) && task.ended_at.nil? ? nil : format_time(task.ended_at),
```

A proper alternative would be to introduce a jail for `ActiveSupport::TimeWithZone`

2022-02-16 11:24 UTC, adamruzicka commented on db/migrate/20220204155632_rename_job_report_template.rb
> +      ReportTemplate.unscoped.find_by(name: from)&.update_columns(:name => to)
To be honest I wasn't really paying attention what was going on when the migrations were run, but now I have two templates, one with the old name and one with the new one.

![image](https://user-images.githubusercontent.com/7326770/154255015-455b17a7-bf7a-40ad-9686-0a4d83c29c74.png)

2022-02-16 12:07 UTC, ofedoren commented on app/views/unattended/report_templates/job_-_invocation_report.erb
> +            'Finished': task.ended_at.blank? ? nil : format_time(task.ended_at),
https://github.com/theforeman/foreman/pull/9017 :)

2022-03-08 11:48 UTC, adamruzicka reviewed
Works well now.

Could we change the time format while we're touching this? Currently it omits leading zeroes for month and day, which is not strictly wrong, but definitely feels weird.

2022-03-08 11:48 UTC, adamruzicka commented on db/migrate/20220204155632_rename_job_report_template.rb
> +      ReportTemplate.unscoped.find_by(name: from)&.update_columns(:name => to)
Must have been caused by me switching branches.

2022-05-18 14:46 UTC, ares commented
@adamruzicka updated, the macro now keeps month and day as two digits, e.g. 05 for may.

2022-05-19 07:41 UTC, adamruzicka approved these changes
LGTM

2022-05-19 07:41 UTC, merged

2022-05-19 07:41 UTC, adamruzicka commented
Thank you @ares !