Fixes #34409 - Revert CentOS_Stream name
theforeman/foreman pull request #9096
Opened 2022-02-07 19:49 UTC by ekohl

In 16701e6bc97c716b7b316a0715285a6e6591e7b8 (and with a fixup in 7364916bd25512c2065892fab96c439648dbb6f1) Foreman started to identify CentOS Stream as CentOS_Stream. However, this is creating problems in upgrades because the description and title have been taken.

What Foreman 3.1 creates:

```
id | major |  name  | minor | nameindicator |         created_at         |         updated_at         | release_name |  type  |   description   | password_hash |      title
----+-------+--------+-------+---------------+----------------------------+----------------------------+--------------+--------+-----------------+---------------+-----------------
1 | 8     | CentOS |       |               | 2022-02-07 18:05:55.944924 | 2022-02-07 18:05:55.944924 |              | Redhat | CentOS Stream 8 | SHA256        | CentOS Stream 8
```

And Foreman Nightly:

```
id | major |     name      | minor | nameindicator |         created_at         |         updated_at         | release_name |  type  |   description   | password_hash |      title
----+-------+---------------+-------+---------------+----------------------------+----------------------------+--------------+--------+-----------------+---------------+-----------------
1 | 8     | CentOS_Stream |       |               | 2022-02-07 17:30:00.279439 | 2022-02-07 17:30:00.279439 |              | Redhat | CentOS Stream 8 | SHA256        | CentOS Stream 8
```

CentOS Linux 8 is End of Life and has been removed from the repositories. In order to minimize the risk for users it's safest to keep the name the same, especially now that Foreman 3.2 is about to branch. That means reverting the name change.

The various fact parser alignments should stay in. This is thus a manual revert instead of an automatic revert.

Related discussions:
* https://community.theforeman.org/t/katello-nightly-rpm-pipeline-1220-failed/27082/
* https://community.theforeman.org/t/luna-nightly-rpm-pipeline-332-failed/27195

2022-02-08 10:58 UTC, lzap requested changes
No, I don't want to further delay the final solution.

Let's fix what 3.1 created, it is obviously wrong. OS named "CentOS" and entitled "CentOS Stream" is incorrect, migrate that to OS named "CentOS_Stream" to fix the problem.

2022-02-08 11:02 UTC, ekohl commented
To be clear: are you writing the migration fixes?

2022-02-08 11:46 UTC, ekohl reviewed
I'll wait to see if tests pass. Then I may decide to split the commit into two. One for the unrelated fixes and one for the actual stream bits.

2022-02-08 11:46 UTC, ekohl commented on app/services/foreman_chef/fact_parser.rb
> +          os_name = 'CentOS'
Note that previously CentOS 7 was not normalized. This is IMHO also an unrelated fix.

2022-02-08 11:46 UTC, ekohl commented on app/services/foreman_salt/fact_parser.rb
> +      minor = match[:minor] || ""
I think this is a good improvement regardless of anything else and I now realize technically this refactor belongs in its own commit.

2022-02-08 12:02 UTC, lzap requested changes
This is hard no from me. And I am not sure what you are doing here, improving a revert patch?

> To be clear: are you writing the migration fixes?

I haven't neither authored or merged the patch. I did fix template association. I can work on migration later this week, should be pretty straightforward just a single query with where conditions (title/description).

Quite frankly, OS model is poorly implemented, I feel like name should have been a label (no  whitespace), we have the title for fancy names and that should no have any limitations or constraints. But that is a different discussion.

2022-02-08 12:16 UTC, ekohl commented
> I haven't neither authored or merged the patch. I did fix template association. I can work on migration later this week, should be pretty straightforward just a single query with where conditions (title/description).

To me this is a blocker for Foreman 3.2 and we are about to branch. As always with regressions, we can either revert of fix them. I'm not going to write a fix because I don't feel comfortable, so here I submitted the revert. If you're against this, it's up to you to provide a proper fix.

2022-02-08 13:21 UTC, lzap commented
Let me recap a bit. It was reported to us by our users in April 2021 that CentOS Stream does not work in Foreman. This was completely broken and I felt that CentOS is very important platform to work well so I immediately filed a patch which you didn't like, you presented weak arguments yet you blocked it and repelled me away from any further work: https://github.com/theforeman/foreman/pull/8456

> To me this is a blocker for Foreman 3.2 

Indeed, this was delivered late. We had a chance to deliver it earlier, but **you** didn't like it! Since then users were asking for the bug to be fixed, someone else did pick it up and it was eventually merged. Almost one year later, here we are with some solution in develop and a minor problem.

> we can either revert of fix them.

The latter is correct in this particular case, this isn't some tiny little thing that broke pipelines, this is an important feature that was delivered one year late. I am pretty sure it's not just me who think CentOS Stream should have been handled properly in 3.2.

Keep in mind that you were repeating again and again a weak argument that you would prefer "CentOS" name, in this context revert is not only bad for the project, it's politically inappropriate. I explained various reasons why "CentOS_Stream" OS name is better (actual name on centos.org, matches Katello creation, ability to differentiate the two OSes for the transition period) and all of these still stands. People are sometimes busy and revert is not a solution, if we are short of time it is unfortunate and this patch is a reason to delay the release.

Another important aspect of this is that our operating system model is designed poorly. This whole name/title/description uniqueness problem is nothing new. This was designed probably ten years ago and not by any participant of this conversation IIRC. Yet you are putting me into position that I am responsible for all of this. You demand a proper fix and present a deadline threat.

> If you're against this, it's up to you to provide a proper fix.

I find this so ludicrous that **you** say this.

2022-02-08 14:11 UTC, lzap commented
Here is the migration which I think should solve the problem: https://github.com/theforeman/foreman/pull/9098

2022-02-08 16:10 UTC, upadhyeammit commented
Looks like migration https://github.com/theforeman/foreman/pull/9098 should help to fix this issue. Including @ezr-ondrej to weigh in the decision, request to provide your thoughts on this.

2022-02-08 19:52 UTC, ezr-ondrej commented
I do not feel entitled to make the decision on this one. Though to share my opinion I feel like @lzap is correct that many users will continue using CentOS 8 regardless it being EOL and still need some way to distinguish between CentOS Linux 8 and CentOS Stream 8, I also found out an article that supports this feeling: https://www.helpnetsecurity.com/2021/09/01/support-centos-8/ (a company thinks they will profit from providing the expected support until the expected EOL).

So my stance is we should have a way to tell users which of the two they are using. Especially to support cases of users being in the middle of the process of migrating Linux to Stream which should be a valid scenario that foreman should support (ideally in 3.1).

@ekohl do I understand correctly that you disagree that there should be a distinguishing factor at all? Or are you just saying it should not be the name?

2022-02-09 12:34 UTC, ekohl commented
My immediate concern is, with my release hat on, that there's a regression. Since the original author left the project and I wasn't comfortable with writing a fix, I went with the revert method.

On a deeper level I still think the distinction of Stream should either be done completely or not at all. Doing it completely means abandoning the bare CentOS without the Linux/Stream indicator altogether and follow what the CentOS project prefers:
* CentOS Linux for a RHEL rebuild
* CentOS Stream as an upstream to RHEL
To me the hybrid is just creating more confusion.

But if the majority thinks it is a good idea then I won't stand in the way. I just want our nightly pipelines to pass reliably.

2022-02-14 16:02 UTC, ares commented
The alternative PR was merged, if we find problems with it we can revert and reopen this one, but for the moment I think it's OK to close. Please reopen/comment if I missed something. Thanks for looking into the issue!

2022-02-14 16:02 UTC, closed without merging

2022-02-15 11:12 UTC, ekohl commented
I've extracted the unrelated normalization to https://github.com/theforeman/foreman/pull/9105 which I think is also needed. Right now it may rely on case-insensitivity but IMHO that's always a bad idea if you can avoid it.