Refs #34511 - align pf4 design to breadcrumbs
theforeman/foreman pull request #9124
Opened 2022-03-02 01:31 UTC by amirfefer

Following https://github.com/theforeman/foreman/pull/9119#issuecomment-1050231133, this PR fixes the breadcrumbs styling and aligns it to PF4 design.

2022-03-02 16:08 UTC, MariaAga requested changes
Thanks! works well just needs a small adjustment

2022-03-02 16:08 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/BreadcrumbBar/BreadcrumbBar.scss
> +  margin: 0 0 24px;
Should be 16
>  `There should be 16px of padding both between the breadcrumb and the masthead, and between the breadcrumbs and anything that comes below.`

 https://www.patternfly.org/v4/components/breadcrumb/design-guidelines

2022-03-02 16:08 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/BreadcrumbBar/BreadcrumbBar.scss
> +    }
Unused class, should probably be removed from the other css as well

2022-03-08 21:58 UTC, amirfefer commented
@MariaAga Thanks, I fixed the css issue, and also added a test

2022-03-09 22:20 UTC, amirfefer commented
rebased

2022-03-14 13:14 UTC, MariaAga approved these changes
LGTM

2022-03-14 13:14 UTC, merged

2022-03-14 13:15 UTC, MariaAga commented
merged, thanks @amirfefer!