Fixes #35075 Out of sync translation of outofsync parameter
theforeman/foreman pull request #9270
Opened 2022-06-16 20:28 UTC by nlegaillart

Hi,

I may be wrong, but it seems that the en locale is not in sync with other languages.

In all locales the file `foreman.po` reads:

```
msgid "Duration in minutes after servers are classed as out of sync. You can override this on hosts by adding a parameter \"outofsync_interval\"." 
```

but in the `locale/en/foreman.po`, it reads:

```
msgid "Duration in minutes after servers are classed as out of sync. This setting is overridden by specific settings from config management tools (e.g. puppet_inteval, ansible_interval)." 
```

It seems also to be the case in the `app/registries/foreman/settings/general.rb` file.

Here is a tiny MR to fix that.

Regards,
--
Nicolas

2022-06-22 09:36 UTC, evgeni commented
ok to test

2022-06-22 09:49 UTC, evgeni requested changes
Yay, commit archeology!

The "You can override this on hosts…" was originally added in 330d63481f23bf1304eda460dcd7d9acc9d1492d.
Then, in c8236d240fbe4f962264bef391ebe86b708a6beb it was changed to "This setting is overridden by specific settings from config management tools…"
And looking at the discussion in the PR that introduced that change -- https://github.com/theforeman/foreman/pull/9037/files#r787798088 -- this was intentional.

So while I do agree that some translations (actually: cs_CZ de en_GB es fr it ja ko pt_BR ru zh_CN zh_TW) are out of date, the actual source code is correct and should not be changed.

@upadhyeammit how do we regenerate the other `.po` files to be in sync again?

2022-06-22 11:53 UTC, upadhyeammit commented
Its not required to modify the .po file, when we call the `make -C locale/ tx-update` it indeed calls the `extract-strings` which is responsible to update the `locale/foreman.pot` and `locale/every_langs/foreman.po` files. Below are the example outcomes,

~~~
$ grep -B 1 'outofsync_interval' locale/foreman.pot
"Duration in minutes after servers are classed as out of sync.You can override "
"this on hosts by adding a parameter `outofsync_interval`."

$ grep -B 1 'outofsync_interval' locale/es/foreman.po
msgid "Duration in minutes after servers are classed as out of sync.You can override this on hosts by adding a parameter `outofsync_interval`."
~~~

While checking this I also noticed we mistakenly deleted the space at the end of first sentence which is good to have?

2022-07-15 07:55 UTC, evgeni commented
Closing as not needed.

2022-07-15 07:55 UTC, closed without merging