Fixes #4007 - updating users email to be optional
theforeman/foreman pull request #9279
Opened 2022-06-27 15:07 UTC by nofaralfasi

Updating users' emails to be optional, except for when the email notifications are enabled (in this case the email is required).

2022-06-28 06:56 UTC, stejskalleos commented
ok to test

2022-06-28 07:22 UTC, stejskalleos requested changes
Tests needs to be updated:
```
ActiveRecord::RecordInvalid: Validation failed: Mail can't be blank
```

2022-06-28 15:40 UTC, ares commented on test/fixtures/users.yml
> +  mail_enabled: true
that should help, we should though perhaps clone some tests a capture the expected behavior when user has `mail_enabled: false`  too

2022-06-28 16:04 UTC, nofaralfasi commented on test/fixtures/users.yml
> +  mail_enabled: true
I agree. I will definitely add some tests for this case.

2022-07-06 09:53 UTC, nofaralfasi commented
[test foreman]

2022-07-07 09:02 UTC, stejskalleos commented
@nofaralfasi Can you rebase? The failing tests were fixed in https://github.com/theforeman/foreman/pull/9288

2022-07-10 12:18 UTC, Ron-Lavi submitted a review, later dismissed
Thanks @nofaralfasi !

2022-07-12 14:06 UTC, Ron-Lavi commented
@nofaralfasi can you rebase? tests should've been fixed in another PR

2022-07-12 14:06 UTC, Ron-Lavi commented
@stejskalleos any other comments?

2022-07-13 09:22 UTC, nofaralfasi commented
I did a rebase cause I thought that the tests were fixed, but I see now that that is not the case... (even more tests are failing now).

2022-07-13 10:57 UTC, ofedoren commented
> I did a rebase cause I thought that the tests were fixed, but I see now that that is not the case... (even more tests are failing now).

They were fixed :) But I bet some of the gems were updated and removed deprecated stuff. And since no one ever reads deprecation warnings the tests are broken again.

2022-07-21 08:20 UTC, nofaralfasi commented
> > I did a rebase cause I thought that the tests were fixed, but I see now that that is not the case... (even more tests are failing now).
> 
> They were fixed :) But I bet some of the gems were updated and removed deprecated stuff. And since no one ever reads deprecation warnings the tests are broken again.
> 
> UPD: Needs another rebase.

Thanks @ofedoren, in progress.

2022-07-25 11:47 UTC, stejskalleos approved these changes
:green_apple: **LGTM**
Tests are green, works as expected.

2022-07-25 11:47 UTC, merged

2022-07-25 11:47 UTC, stejskalleos commented
Thanks @nofaralfasi !