Fixes #35280 - Install katello-host-tools / -tracer during host registration
theforeman/foreman pull request #9321
Opened 2022-07-26 09:58 UTC by sbernhard

2022-08-02 11:39 UTC, stejskalleos requested changes

2022-08-02 11:39 UTC, stejskalleos commented on app/views/unattended/provisioning_templates/host_init_config/host_init_config_default.erb
> +<% if host_param_true?('redhat_install_host_tools', true) -%>
This should be `host_param_true?('redhat_install_host_tools')`

2022-08-02 11:39 UTC, stejskalleos commented on app/views/unattended/provisioning_templates/host_init_config/host_init_config_default.erb
> +<% if host_param_true?('redhat_install_host_tracer_tools', true) -%>
This should be `host_param_true?('redhat_install_host_tracer_tools')`

2022-08-02 11:39 UTC, stejskalleos commented on app/views/unattended/provisioning_templates/host_init_config/host_init_config_default.erb
> +<%= install_packages("katello-host-tools") -%>
Nit: `'` instead of `"`

2022-08-02 11:39 UTC, stejskalleos commented on app/views/unattended/provisioning_templates/host_init_config/host_init_config_default.erb
> +<%= install_packages("katello-host-tools-tracer") -%>
Nit: `'` instead of `"`

2022-08-02 11:52 UTC, sbernhard commented
Thanks @stejskalleos

2022-08-03 07:39 UTC, stejskalleos approved these changes
:green_apple: **LGTM**, thanks @sbernhard!

2022-08-03 07:40 UTC, merged