Fixes #35361 - Make columns on host index page selectable
theforeman/foreman pull request #9351
Opened 2022-08-11 14:01 UTC by ofedoren

Replaces #9319. @ShimShtein is that better?

 - tried to make it as much compatible with current usage of pagelets for columns, but without `key: :col_name` it won't be displayed if a user has preferences, thus plugins should be updated.
 - Deface solution seems to be not working anymore with these changes, thus plugins should be updated in favor of pagelets.

2022-08-18 14:26 UTC, ShimShtein requested changes

2022-08-18 14:26 UTC, ShimShtein commented on app/registries/pagelets/manager.rb
> +      def use_pagelet(mountpoint, opts)
I don't think we need to pass an open `opts` object. We are using only `:key` from it.
```suggestion
      def use_pagelet(mountpoint, key)
```

2022-08-18 14:26 UTC, ShimShtein commented on app/helpers/pagelets_helper.rb
> +    Pagelets::Filter.for(mountpoint, pagelets_for(mountpoint)).filter(filter_opts(opts)).each do |pagelet|
The `Filter` should be hidden inside the `Manager` class. I think it's implementation detail.
We can pass filter options as part of `pagelets_at` call in the manager:

```
def pagelets_at(key, mountpoint, opts={})
  handle_empty_keys_for key, mountpoint
  list = @pagelets[key][mountpoint]
  list = Filter.for(mountpoint, list).filter(opts[:filter]) if opts[:filter]
  list
```
and then pass the `:filter` as a parameter through `pagelets_for`

2022-08-18 14:26 UTC, ShimShtein commented on app/helpers/pagelets_helper.rb
> +          :attributes => attributes(col_opts, opts[:subject]),
This puts a lot of columns logic into a general method.

I think we should create two methods: `render_column_content_for` and `render_column_header_for` similar to `render_tab_content_for` and `render_tab_header_for`. Then we can utilize the fact that a pagelet can have more attributes than the ones defined in pagelet's class definition.
I would go with something like this:
```
def render_column_content_for(mountpoint, opts = {})
  pagelets_for(mountpoint).map do |pagelet|
      next unless pagelet.onlyif.call(opts[:subject], self)
      render_pagelet(pagelet, pagelet.opts.merge(opts))
  end.join
end
```

Now we can either move the `attributes` method into the `_selectable_column_*.erb` files, or add those methods to a separate helper.

2022-08-18 14:26 UTC, ShimShtein commented on app/registries/pagelets/filter.rb
> +      def registred_filters
I think we can skip the multiple filters, since the `Columns` filter is not limited to columns. I think it can work with any pagelet, especially if you define profile as first rate citizen.

2022-08-22 20:22 UTC, ofedoren commented
@ShimShtein, updated.

2022-08-25 10:30 UTC, ofedoren commented
Uhm... Can you please explain why did you return the columns in the view?..

2022-08-25 10:49 UTC, ShimShtein commented
I have returned the view columns as hidden to have an anchor for deface-based  extensions - this way the columns wouldn't disappear, but move to the end of the list, which sounds better than total removal.

@adamruzicka could you take a look before we merge?

I am OK with @ofedoren's work, and with the addition of the hidden anchor, I suppose it would be a good enough solution.

2022-08-25 13:25 UTC, adamruzicka approved these changes
There are nitpicks that could be had, but all in all it works well. As far as I'm concerned, this is good to go.

2022-08-25 13:26 UTC, ShimShtein approved these changes

2022-08-25 13:47 UTC, merged

2022-08-25 13:47 UTC, adamruzicka commented
Thank you @ofedoren & @ShimShtein !

2022-08-26 08:35 UTC, ares commented
@ofedoren please make sure to demo and document it as a headline feature of 3.4 :-)