Fixes #35388 - Drop unnecessary timestamps only if column exists
theforeman/foreman pull request #9360
Opened 2022-08-19 07:21 UTC by stejskalleos

Fix for the issue when :remove_column tries to remove
column that does not exists.

Note: we can't use `if_exists` or `if_not_exists`, they've been added in Rails 6.1 and we need to CP this PR into the 3.3-stable (Sat 6.12)

2022-08-19 08:05 UTC, stejskalleos commented
[test katello]

2022-08-19 08:23 UTC, ares approved these changes
Makes sense and looks good, we're yet debating the root cause.

We know some users were fighting similar issue and may have dropped the column from the DB. If that's the case, I'd be OK with extra level of robustness in this migration even though, majority of users won't hit it. If we confirm that theory, I'm happy to merge.

2022-08-22 09:02 UTC, ares commented
The reason for the error was because of migration renaming. If we'll need to rename the migration (to influence the order of execution with other migrations, we'll have to find another solution, perhaps based on this. But it should get merged as is atm.

2022-08-22 09:02 UTC, ares requested changes
this wouldn't solve the issue completely, so blocking for now

2022-08-30 12:43 UTC, closed without merging