Fixes #34997 - Fix expand/collapse all behavior in Details tab
theforeman/foreman pull request #9416
Opened 2022-09-08 14:35 UTC by jeremylenz

description to come

2022-09-19 11:44 UTC, MariaAga requested changes
Thanks for this fix! tested on foreman+plugins and it works well on untranslated foreman :)
needs to be changed so it will also work on translated foreman

2022-09-19 11:44 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/HostDetails/Tabs/Details/index.js
> +function cardExpansionReducer(state, action) {
Can this be an arrow function for consistency?

2022-09-19 11:44 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/HostDetails/Templates/CardItem/CardTemplate/index.js
> +  const cardId = cardIds?.find(id => id.includes(header));
This doesn't work well for a translated foreman, even if the id is translated it still doesnt always fit with the header unless its the same string exactly

2022-09-19 11:44 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/HostDetails/Tabs/Details/index.js
> +      throw new Error();
Can the error have some text, like `invalid card expansion type: ${type}`?

2022-09-19 11:44 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/HostDetails/Tabs/Details/index.js
> +      });
do we need this and `getInitialState`? they look very similar

2022-09-20 19:02 UTC, jeremylenz commented
thanks @MariaAga!

Turns out using the fill IDs simply isn't compatible with translation at all. So I reworked it to just use the card headers, and ended up simplifying things quite a bit. I also think I've addressed the other remaining comments. let me know..

2022-09-20 19:03 UTC, jeremylenz commented
I set my locale to German (hello Betriebssystem card!) and it seems to work fine now.

2022-09-22 19:42 UTC, MariaAga approved these changes
Thanks! everything works well now :)

2022-09-22 19:43 UTC, merged