Fixes #35520 - Unattended - Invalid remote_ip on production setup
theforeman/foreman pull request #9422
Opened 2022-09-13 11:43 UTC by stejskalleos

When rendering template through Smart Proxy in production setup, 'load_host_details' method is loading 'remote_ip' for the Smart Proxy, not for the provisioned host.

2022-09-13 12:38 UTC, Griffin-Sullivan commented
Confirmed the patch is working on 6.12.

2022-09-13 13:04 UTC, ekohl requested changes
Please don't do this. It's the wrong solution. You're opening up security holes. The proper solution is to document for users how to do it properly. We should finish up https://github.com/theforeman/foreman-documentation/pull/872.

2022-09-13 13:18 UTC, ekohl commented
I rebased it and opened https://github.com/theforeman/foreman-documentation/pull/1626.

@Griffin-Sullivan would you mind verifying that solution?

2022-09-13 14:22 UTC, ekohl commented
> You're opening up security holes.

To elaborate on this: the `X-Forwarded-For` header must be checked to come from a trusted source. Without this, anyone can spoof any IP. In https://projects.theforeman.org/issues/30779 we fixed that, but only in https://projects.theforeman.org/issues/34089 we added installer support for it. Today we still don't have any documentation for users.

2022-09-13 16:22 UTC, lzap commented
We have discussed this in the morning with Leos and we are aware of the security implications. That's why the proposal only limits this to the unattended controller and iPXE request, which is special - we cannot utilize tokens in this workflow.

I asked for this solution too, however, as @ares mentioned: the `trusted_hosts` setting check does not change a thing, an attacker can still spoof IP address against a proxy which will then forward it (in a "secure" way) to Foreman.

I am not against adding this as an extra layer of "protection", however, in that case I suggest also to update the setting description, and documentation: https://github.com/theforeman/foreman/blob/add9562faef4f61c4e3aeddd8be6ba7e8e9fc4d1/app/registries/foreman/settings/auth.rb#L35-L39

2022-09-14 14:01 UTC, ekohl commented
Via #9423 I've done some testing and I can see `request.forwarded_for` is set, but `request.remote_ip` is not set correctly. This gives me the impression that our whole `remote_ip` handling is broken. IMHO that's the bug to solve, not work around it like this. I'll continue diving into this after the next meeting.

2022-09-14 14:40 UTC, ekohl commented
Ok, disregard that. I had it misconfigured and it does work on my Foreman 3.3 setup. So I really don't see a reason why we should accept this patch.

> I asked about using `trusted_hosts` too, however, as @ares mentioned: the `trusted_hosts` setting check does not change a thing, an attacker can still spoof IP address against a proxy which will then forward it (in a "secure" way) to Foreman.

`trusted_hosts` is completely unrelated and has nothing to do with this.

`trusted_proxies` is a setting in `settings.yaml` for HTTP proxies. The Smart Proxy behaves like a HTTP Proxy in some cases (like templates) and sets `X-Forwarded-For`. Another implementation is Apache, which is used on content proxies. If you want correct logging of remote IPs, setting up `trusted_proxies` is required.

2022-09-14 15:33 UTC, ekohl commented
After checking with @Griffin-Sullivan I know where it went wrong. He used the incorrect IP address. I had also missed that the templates feature may be enabled on Foreman itself.

Consider a host `foreman.example.com` (`192.0.2.10`) with both foreman and foreman-proxy. The templates feature is enabled (which is default on Satellite). Then given a client (`192.0.2.42`) the HTTP requests flow like this:

Client -> Foreman Proxy -> Foreman

When the request reaches Foreman, the value of `X-Forwarded-For` is `192.0.2.42, 192.0.2.10`. This means Foreman's external IP must also be in the `trusted_proxies` setting. Once you do that, `remote_ip` is correct. On our hypothetical setup the solution is then:
```
foreman-installer --foreman-trusted-proxies 127.0.0.1/8 --foreman-trusted-proxies ::1 --foreman-trusted-proxies 192.0.2.10
```

The correct solution is in documentation or the installer (or both). No code change neede.

2022-09-14 15:33 UTC, closed without merging