Fixes #35837 - Allow non admin users update table preferences
theforeman/foreman pull request #9545
Opened 2022-12-08 16:22 UTC by pkoprda

Non admin user could not update existing table preferences (getting 403).

2023-02-06 15:38 UTC, ShimShtein commented
[test unit]

2023-02-07 10:06 UTC, ShimShtein requested changes

2023-02-07 10:06 UTC, ShimShtein commented on app/registries/foreman/access_permissions.rb
> +      :"api/v2/table_preferences" => [:show, :create, :edit, :update, :delete, :index],
```suggestion
      :"api/v2/table_preferences" => [:show, :create, :update, :destroy, :index],
```

The controller doesn't have `edit` and `delete` methods, but it does have `destroy` method

2023-02-21 16:06 UTC, ofedoren approved these changes
Thanks, @pkoprda and @adamruzicka, works for me. Any concerns, @ShimShtein ?

2023-02-23 15:52 UTC, ShimShtein approved these changes

2023-02-23 15:52 UTC, ShimShtein commented
Merged, thanks everyone!

2023-02-23 16:12 UTC, merged