Fixes #35845 - Searching hosts should be possible by all reported data
theforeman/foreman pull request #9548
Opened 2022-12-09 11:45 UTC by ares

When bios information was introduced in PR #9497, the searching was not added. This make all host reported data searchable.

2022-12-09 11:56 UTC, adamruzicka approved these changes
Nothing to add here, waiting for tests to pass

2022-12-09 14:42 UTC, ares commented
one libvirt test seems to be failing, that is unrelated

2022-12-14 15:09 UTC, stejskalleos requested changes
For me it doesn't work :/

I have a host created from the ansible facts.
These are facts from the ansible:
```
# Search facts by name  ~ bios
stream8.example.com | ansible_bios_date | 04/01/2014
stream8.example.com | ansible_bios_version | 1.16.1-2.fc37
stream8.example.com | ansible_bios_vendor | SeaBIOS
```

If I try to search on host page `reported.bios_vendor  = SeaBIOS` it just doesn't found anything.

Also I noticed one thing, some reported data (like domain) can be search by `reported  domain = example.com`, but your must be as `reported.bios* = search value`.

Why do we have some searches with dot and some without dot, is there a reason for it?

2022-12-16 15:05 UTC, ekohl commented
Perhaps this doesn't work because BIOS is a hash with (usually) 3 entries. Not actual fields themselves.

2023-01-09 13:24 UTC, adamruzicka commented
@stejskalleos does the host have the reported data facet? The search doesn't look at "raw" facts

2023-01-09 13:29 UTC, stejskalleos commented
> does the host have the reported data facet? The search doesn't look at "raw" facts

@adamruzicka How do I check that? The host was created from the Ansible facts, so I expected that the search would work with it.

2023-01-09 13:38 UTC, adamruzicka commented
Fire up the rails console, find the host and call `reported_data` on it or just look directly into the db.

2023-01-17 09:05 UTC, stejskalleos approved these changes
:green_apple: **LGTM**, works as expected.

Thanks @ares @adamruzicka !

2023-01-17 09:05 UTC, merged