Provide more information about host sub-statuses
theforeman/foreman pull request #9550
Opened 2022-12-09 17:43 UTC by ares

Added more info about how to add searching by custom statuses

2022-12-14 14:51 UTC, stejskalleos requested changes
Few nits, otherwise ok

2022-12-14 14:51 UTC, stejskalleos commented on developer_docs/how_to_create_a_plugin.asciidoc
> +on. The README contains a list of35806 it's current behaviour. To get started
Is this intentional?

2022-12-14 14:51 UTC, stejskalleos commented on developer_docs/how_to_create_a_plugin.asciidoc
> +such extension definition could look like
Missing `.` or `:`?

2022-12-14 14:51 UTC, stejskalleos commented on developer_docs/how_to_create_a_plugin.asciidoc
> +         scoped_search :relation => :execution_status_object, :on => :status,
Nit: Maybe would be worth to mention [scoped_search gem](https://github.com/wvanbergen/scoped_search), so users know where `scoped_search` method came from

2023-01-02 14:45 UTC, ares commented
thanks, replaced by https://github.com/theforeman/foreman/pull/9569 based on my fork, that PR resolves your comments

2023-01-02 14:45 UTC, closed without merging