Fixes #35917 - PXEGrub2 broken, linuxefi and initrdefi grub2 commands deprecated in RHEL8
theforeman/foreman pull request #9580
Opened 2023-01-11 03:16 UTC by zleite

2023-01-11 08:15 UTC, ekohl commented
@zleite thanks for this. If you use a single commit that has a message prefixed with `Fixes #35917 - ...` (like your PR title now) then it should automatically link it up in Redmine. Our automation works based on the git commits, not PR titles.

2023-03-15 07:46 UTC, stejskalleos requested changes

2023-03-15 07:46 UTC, stejskalleos commented on app/views/unattended/provisioning_templates/PXEGrub2/kickstart_default_pxegrub2.erb
> -  if (rhel_compatible && os_major < 7) || !@host.pxe_loader_efi?
We can't remove this, we still support provisioning of [RHEL6 until 30 Jun 2024](https://endoflife.date/rhel)

2023-03-15 07:46 UTC, stejskalleos commented on app/views/unattended/provisioning_templates/PXEGrub2/preseed_default_pxegrub2.erb
> +  linux <%= @kernel %> interface=auto url=<%= foreman_url('provision')%> ramdisk_size=10800 root=/dev/rd/0 rw auto BOOTIF=01-$net_default_mac <%= snippet("preseed_kernel_options").strip %>
Why is the `efi` suffix not needed anymore?
From the removed code above I can see that ubuntu >12  and debian >8 had to have `efi` suffix. What changed?

2023-06-16 01:23 UTC, closed without merging