Fixes #36084 - return early when sendmail_location file doesn't exist
theforeman/foreman pull request #9621
Opened 2023-02-12 14:34 UTC by Ron-Lavi

in case that delivery_method is "sendmail",
we should also check if the executable file exist. currently the mail can be seen as sent succesfully from the UI, although the executable to send it is missing

2023-02-12 19:32 UTC, Ron-Lavi commented
to make it work, and to have an existing sendmail_location,
you can follow the following installation instructions - e.g on fedora: https://tecadmin.net/install-sendmail-on-fedora/

2023-02-14 12:00 UTC, ekohl requested changes
> you can follow the following installation instructions - e.g on fedora: https://tecadmin.net/install-sendmail-on-fedora/

Note that sendmail is not something you really want. It may have been the only choice when it was written 40 years ago (yes, it's that old), but nowadays `/usr/bin/sendmail` is more of an interface. For example, postfix also provides it. On my Fedora:
```console
# dnf repoquery --whatprovides /usr/sbin/sendmail -q
esmtp-0:1.2-19.fc36.x86_64
exim-0:4.95-3.fc36.x86_64
exim-0:4.96-6.fc36.x86_64
opensmtpd-0:6.8.0p2-10.fc36.x86_64
opensmtpd-0:6.8.0p2-8.fc36.x86_64
postfix-2:3.6.4-1.fc36.x86_64
sendmail-0:8.17.1-5.fc36.x86_64
ssmtp-0:2.64-29.fc36.x86_64
```

Red Hat defaults to postfix because it's much more user friendly than sendmail.

2023-02-14 12:00 UTC, ekohl commented on app/controllers/users_controller.rb
> +      if (Setting[:delivery_method].to_s == "sendmail" && !File.exist?(Setting[:sendmail_location]))
Your solution does check if the file exists, but doesn't check if it's executable or some permission error (SELinux could deny access for example).

https://guides.rubyonrails.org/action_mailer_basics.html#example-action-mailer-configuration suggests there's an option `config.action_mailer.raise_delivery_errors = true` and I think that's what we're actually after here. It may also catch errors on the SMTP delivery so I'd appreciate it if you investigate that option.

2023-02-16 13:44 UTC, ekohl reviewed
I don't know if we always need to error out. That implies we may need to catch it where we call it and display an error. I was mostly talking about the test mail.

@adamruzicka did you also mention this was better in the latest mailer gem?

2023-02-16 13:44 UTC, Ron-Lavi commented
> It may have been the only choice when it was written 40 years ago (yes, it's that old), 

Well, seemed that it served well for so many years :)

>but nowadays /usr/bin/sendmail is more of an interface. For example, postfix also provides it. On my Fedora:
> `dnf repoquery --whatprovides /usr/sbin/sendmail -q`

Nice, `--whatprovides` command is super useful! TIL

@ekohl @adamruzicka looks like the `config.action_mailer.raise_delivery_errors = true` solved the issue.

2023-02-28 11:32 UTC, stejskalleos commented
[test katello]

2023-02-28 11:44 UTC, stejskalleos commented
:green_apple: **LGTM** Error is generated as expected.

Let's wait for Katello results, meanwhile @ekohl do you any other comments? If not we can merge

2023-02-28 12:11 UTC, ekohl commented
> Let's wait for Katello results, meanwhile @ekohl do you any other comments? If not we can merge

I still think that this is missing error handling. My biggest worry is that if an email is sent, but failed to deliver that an exception is raised. Then the controller which sends the email may display an error page (HTTP 500) while the primary action worked.

One way around that is to start using [`deliver_later`](https://api.rubyonrails.org/v7.0.4.2/classes/ActionMailer/MessageDelivery.html#method-i-deliver_later) (https://projects.theforeman.org/issues/36118).

I didn't test this, but I suppose one way to verify it would be:
* Configure audit entries to be mailed
* Make sure email can't be delivered (like setting sendmail to a location that doesn't exist)
* Edit a page that creates an audit entry

My theory would be that it shows an internal server error page.

Another would be user creation if welcome emails are enabled.

The `test_email` does have exception handling, so that should work just fine.

2023-03-01 13:54 UTC, Ron-Lavi commented
Alright then, I will update this PR with deliver_later.

2023-08-02 01:23 UTC, closed without merging