Fixes #35990 - fix search fact_values via API
theforeman/foreman pull request #9641
Opened 2023-03-05 09:39 UTC by nofaralfasi

fix the 500 error for searching fact_values via API

(cherry picked from commit 41e8e40e3561278489068593b7f95d2b1ed06d8b)

2023-03-05 11:38 UTC, ekohl requested changes
:+1: to cherry picking this, but you should keep the message as `Fixes` instead of `Refs`. Our automation will then correctly set the `Fixed in version` in Redmine.

2023-03-14 13:44 UTC, Ron-Lavi commented
Hey @nofaralfasi, thanks for the CP!
I tested it and still getting the same error as the issue indicates: 
`'Action failed' error (ActiveModel::MissingAttributeError): missing attribute: fact_name_id`

full logs: https://pastebin.com/CFNRtKys

2023-03-14 13:46 UTC, ekohl approved these changes
@Ron-Lavi how did you test that? The paths indicate a installation using packages and this PR isn't merged. I think @ehelms missed this one in 3.5.2.

2023-03-14 13:51 UTC, Ron-Lavi commented
interesting, I tried applying this patch on a production environment and got that error.

2023-03-14 13:54 UTC, ekohl commented
How did you patch? I'd expect that this works:
```sh
cd /usr/share/foreman
curl -L https://github.com/theforeman/foreman/pull/9641.patch | patch -p1
systemctl restart foreman
```

2023-03-14 17:11 UTC, Ron-Lavi approved these changes
> How did you patch? I'd expect that this works:
> 
> ```shell
> cd /usr/share/foreman
> curl -L https://github.com/theforeman/foreman/pull/9641.patch | patch -p1
> systemctl restart foreman
> ```

ACK, the restart was needed in this case (I assume it`s best practice always)
previously I could verify some patches on rails controllers / other Rails code without the restart
but seems needed for the API + hammer combination

thanks @nofaralfasi and @ekohl, merging!

2023-03-14 17:11 UTC, merged

2023-03-14 17:21 UTC, ekohl commented
> ACK, the restart was needed in this case (I assume it`s best practice always)
> previously I could verify some patches on rails controllers / other Rails code without the restart

AFAIK Auto-reload is a development thing only. You can probably remove all Ruby files from disk and the application will continue running with what's already in memory. Not sure how you could have patched things in packaged setups without reloads.

2023-03-14 19:05 UTC, Ron-Lavi commented
Replacing simple methods and helpers with a patch actually fixed an issue, I just needed to reload the page and things started working again, this is something pretty cool with Rails and I wish we could do the same with the bundled JS..

2023-03-14 23:33 UTC, ekohl commented
If that works in production then something is wrong. We shouldn't be hot reloading code. All code should be preloaded and then Puma should fork from the parent to avoid duplicating in memory.