Fixes #36190 - add issued date to applied report template
theforeman/foreman pull request #9649
Opened 2023-03-10 04:27 UTC by snagoor

This PR is dependent on https://github.com/Katello/katello/pull/10441

when Applied errata report template is generated, it would look as below

~~~
date,hostname,erratum_id,erratum_type,issued,status
2023-02-01 13:40:12 +0530,client.example.com,RHSA-2022:8900,security,2022-12-08,success
2023-02-01 13:40:19 +0530,client.example.com,RHSA-2022:4803,security,2022-05-30,success
2023-02-01 13:49:20 +0530,client.example.com,RHBA-2021:4789,bugfix,2021-11-23,success
~~~

2023-03-15 08:05 UTC, stejskalleos requested changes
This generates invalid report:
![report](https://user-images.githubusercontent.com/59385976/225245338-6317a651-43e5-40f9-a6a9-c69237c249b4.png)

CSV:
```csv
date,hostname,erratum_id,erratum_type,issued,status
2023-03-15 09:00:17 +0100,rhel8.example.com,RHSA-2022:6457,security,error,2023-03-15 08:49:11 +0100
2023-03-15 09:00:17 +0100,rhel8.example.com,RHSA-2022:7089,security,error,2023-03-15 08:49:11 +0100
2023-03-15 09:01:22 +0100,rhel8.example.com,RHSA-2022:6457,security,success,2023-03-15 08:49:11 +0100
```

2023-03-15 08:25 UTC, stejskalleos approved these changes
Ignore my previous comment, I had outdated `katello` gem.

:green_apple: **LGTM**, works as expected.

2023-03-15 08:26 UTC, merged

2023-03-15 08:26 UTC, stejskalleos commented
Thanks @snagoor

2023-03-28 12:04 UTC, MariaAga commented
Should this be cherry picked?