Fixes #36001 - create new modal for new personal access tokens
theforeman/foreman pull request #9665
Opened 2023-03-27 10:40 UTC by kmalyjur

2023-05-04 08:44 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/users/PersonalAccessTokens/PersonalAccessTokensSelectors.js
> +  selectAPIStatus(state, PERSONAL_ACCESS_TOKENS_REQUEST) === STATUS.PENDING ||
`PERSONAL_ACCESS_TOKENS_REQUEST` is not used in the submit, should be `PERSONAL_ACCESS_TOKEN_FORM_SUBMITTED`

2023-05-04 08:44 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/users/PersonalAccessTokens/PersonalAccessTokenModal.js
> +          <Button key="cancel" variant="link" onClick={handleModalToggle}>
Should also be disabled with `isSubmitting` as clicking on it will not cancel the submit

2023-05-04 08:53 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/users/PersonalAccessTokens/PersonalAccessTokenModal.js
> +  const validateTimeChange = newTime => {
not sure why, but when I enter time with only `hh:mm` there is a error in the time, but without text
![Screenshot from 2023-05-04 10-52-02](https://user-images.githubusercontent.com/30431079/236156922-e0b1865c-7b1f-4aa8-8ab8-485f45b27aa1.png)

2023-05-04 09:01 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/users/PersonalAccessTokens/PersonalAccessTokensSelectors.js
> +  selectAPIStatus(state, PERSONAL_ACCESS_TOKENS_REQUEST) === STATUS.RESOLVED;
If we use resolved here it means users cant create 2 access tokens without page refresh

2023-05-04 09:04 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/users/PersonalAccessTokens/PersonalAccessTokenModal.js
> +              handleSubmit();
I think the form shouldnt try to submit if there are name errors

2023-05-04 09:04 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/users/PersonalAccessTokens/PersonalAccessTokenModal.js
> +              onChange={v => setName(v)}
can be just `onChange=setName`

2023-05-04 09:09 UTC, MariaAga requested changes
Thanks for this refactor! left some comments:

2023-05-15 12:24 UTC, MariaAga commented
tested the usability a bit, there is weird behavior when users enter `12:00` to time and press Enter.
Also, after typing a name and selecting the `At` radio users can submit with an empty datetimepicker

2023-05-30 07:52 UTC, MariaAga requested changes
Almost there, just 2 small changes needed :)

2023-05-30 07:52 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/users/PersonalAccessTokens/PersonalAccessTokenModal.js
> +    setIsModalOpen(!isModalOpen);
Looks like this only is used when the code closes the modal, can it be renamed to `closeModal` and `setIsModalOpen(false)`?

2023-05-30 07:52 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/users/PersonalAccessTokens/PersonalAccessTokenModal.js
> +              aria-label="personal-token-name"
aria-labels should be human readable as its for visually impaired users who use screen readers. please fix also in other places in this pr.
https://www.aditus.io/aria/aria-label/

2023-05-31 08:33 UTC, kmalyjur commented on webpack/assets/javascripts/react_app/components/users/PersonalAccessTokens/PersonalAccessTokenModal.js
> +    setIsModalOpen(!isModalOpen);
I use it on line 145 when opening the modal, but it's definitely unnecessary, so I'm changing that, too.

2023-06-06 12:29 UTC, MariaAga approved these changes
LGTM!

2023-06-06 12:33 UTC, merged