[CP] 3.5.3 release and cherry-pick
theforeman/foreman pull request #9682
Opened 2023-04-12 20:36 UTC by ianballou

The single cherry-pick is from https://projects.theforeman.org/issues/35578

It looks like another PR was tacked onto that old issue. I believe I caught everything -- let me know if I didn't.

I've updated the CHANGELOG and the Foreman version.

2023-04-13 20:09 UTC, ekohl requested changes
The changelog looks incomplete. Did you not create it using `./extras/changelog`? In the release procedure this is part of `tag_project` and is normally not done in a PR. We just push it straight into the stable branch.

2023-04-13 22:23 UTC, ianballou commented
> The changelog looks incomplete. Did you not create it using `./extras/changelog`? In the release procedure this is part of `tag_project` and is normally not done in a PR. We just push it straight into the stable branch.

Ah okay, in Katello we create the changelog manually with tool_belt and update it in a PR. I'll remove the changelog entries.

2023-04-13 22:26 UTC, ianballou commented
@ekohl I'm guessing the version bump also happens later in the procedure? I removed all my commits and just left the cherry-pick.

2023-04-14 14:05 UTC, ekohl approved these changes
Thanks!

2023-04-14 14:05 UTC, merged