Fixes #36058 - Drop the socket facts chart
theforeman/foreman pull request #9695
Opened 2023-04-28 06:57 UTC by girijaasoni

Socket Facts chart wasn't rendered completely and there were feedbacks to consider dropping it. We added a community post to get more feedback on if the feature is needed
https://community.theforeman.org/t/socket-chart-feature-is-it-needed/33120
Feedback suggested to drop it. This PR is in reference for the same. Screenshots after dropping it is attached: 
![Screenshot from 2023-04-28 12-24-08](https://user-images.githubusercontent.com/115526987/235076837-2716b42d-1177-44e7-ae6b-df1294fa021b.png)

2023-04-30 09:50 UTC, Ron-Lavi submitted a review, later dismissed
Thanks @girijaasoni !
Looks great, tested and I see no issues with removing that action column,
also found no reference in the foreman org to the FactChart component,
but in the katello org, I found this funny [reference](https://github.com/Katello/katello/blob/master/webpack/components/extensions/about/index.js#L6) which I will rename in a different PR.

ACK from me 👍🏼

2023-05-04 14:05 UTC, stejskalleos requested changes
two things plus update the commit message with a description like in the PR.
Having a link there to the community would be nice too.

2023-05-04 14:05 UTC, stejskalleos commented on app/views/fact_values/index.html.erb
> -      <th class="col-md-1"><%= _('Actions') %></th>
Should we remove it, or keep it, even when the list is empty?
What if some plugins are extending this column? An unlikely scenario in this case, but you never know

2023-05-04 14:05 UTC, stejskalleos commented on app/views/fact_values/_fact.html.erb
> +
Nit: remove trailing line

2023-05-08 12:18 UTC, girijaasoni commented on app/views/fact_values/index.html.erb
> -      <th class="col-md-1"><%= _('Actions') %></th>
Only the view chart button is in the actions column code wise, IMHO we should remove it
@Ron-Lavi what do you think

2023-05-08 12:36 UTC, Ron-Lavi commented on app/views/fact_values/index.html.erb
> -      <th class="col-md-1"><%= _('Actions') %></th>
imho we can remove it as it will just stay empty and there's not seem to be any extensions to it.

2023-05-10 07:40 UTC, stejskalleos approved these changes
:green_apple: **LGTM**, works as expected

Thanks @girijaasoni !

2023-05-10 07:41 UTC, merged