Fixes #36502 - Update ipxe_global_default.erb to allow any port to register using fdi discovery image
theforeman/foreman pull request #9733
Opened 2023-06-12 19:05 UTC by jmott85

Adjusted BOOTIF=01-${mac} and added fdi.initnet=all which allows any network port to work with discovery.

To recreate: Boot a machine to fdi discovery image from iPXE using a network port that does not identify as net0.

Expected outcome: Discovery image updates Foreman server with machine information using the mac address of the port that established the connection.

Actual outcome: Discovery image fails while attempting to update Foreman server using the mac address of net0.

2023-07-03 08:27 UTC, stejskalleos commented
[ok to test]

2023-07-03 08:44 UTC, stejskalleos requested changes
Hi @jmott85,
I don't think this should be enabled by default, what about cases where users don't want to initialize all interfaces?

I think this should be customized by the config parameter, with default value `bootif`.

2023-07-31 18:36 UTC, jmott85 commented
> Hi @jmott85, I don't think this should be enabled by default, what about cases where users don't want to initialize all interfaces?
> 
> I think this should be customized by the config parameter, with default value `bootif`.

Please see latest commit.  I changed fdi.initnet to ${ifname} which uses the interface that iPXE booted from.

2023-09-20 06:52 UTC, stejskalleos commented
Hi, sorry for the late response, could you please rebase the commits over the latest `develop`, so it will trigger the CI over the latest changes?

2023-10-13 18:56 UTC, jmott85 commented
> Hi, sorry for the late response, could you please rebase the commits over the latest `develop`, so it will trigger the CI over the latest changes?

Merged with base and I also changed fdi.initnet to bootif instead of using an iPXE variable.  I found this option here: https://theforeman.org/plugins/foreman_discovery/18.0/index.html#3.1.5Discoveryimagekerneloptions

2024-01-19 11:36 UTC, ekohl commented
@jmott85 I'm reopening this because I think it's still a good change, but can you rebase on develop instead of merge? We'd like to see a single commit if possible.

2024-01-23 13:51 UTC, ekohl commented
@jmott85 you still only merged in the changes, but we'd like to see all changes squashed into a single commit. https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec is one example I found, though I'd recommend doing something like
```sh
git fetch origin
git rebase -i origin/develop
# Now change it to squash all changes
git push --force
```

2024-01-24 01:45 UTC, jmott85 commented
@ekohl Thanks for the assistance and apologies for the mess of commits.  I haven't tried squashing commits before and I still don't think I got it right.  Maybe it would be better to just close this issue and I can open a new one.

2024-01-29 17:32 UTC, ekohl commented
@jmott85 given how small the changes actually are, I think that would also be fine.

If you want to reset the changes, you can use this (assuming `origin` is the upstream repository, see https://community.theforeman.org/t/git-remote-fetch-pull-and-rebase/29949
```
git fetch origin
git reset --hard origin/develop
# make your changes
git push --force
```

2024-02-04 08:42 UTC, jmott85 commented
@ekohl, I think that got it into one commit now.  Please review.

2024-02-26 06:48 UTC, stejskalleos approved these changes
:green_apple: **LGTM**

Thanks @jmott85

2024-02-26 06:48 UTC, merged

2024-02-26 07:36 UTC, evgeni commented
@stejskalleos this breaks CI as the changes did not update the rendered snapshots :(

2024-02-26 07:47 UTC, evgeni commented
https://github.com/theforeman/foreman/pull/10070

2024-02-26 10:54 UTC, stejskalleos commented
Oh shoot, I thought it's failing due to the other problems. sorry, my bad