Fixes #36519 - Fix python-version on debian12
theforeman/foreman pull request #9741
Opened 2023-06-19 14:37 UTC by m-bucher

I kinda inverted the default to `python3` maybe more `python(2)`-using distributions need to mentioned, but one could argue that Python2 has been deprecated long enough now :stuck_out_tongue_winking_eye:

2023-06-19 14:49 UTC, ekohl requested changes

2023-06-19 14:49 UTC, ekohl commented on app/views/unattended/provisioning_templates/provision/preseed_default.erb
> +                   when (@host.operatingsystem.name == 'Debian' && os_major < 12) then 'python'
Looks like the package isn't available in bullseye either: https://packages.debian.org/buster/python does exist but https://packages.debian.org/bullseye/python doesn't.
```suggestion
                   when (@host.operatingsystem.name == 'Debian' && os_major < 11) then 'python'
```

2023-06-23 07:02 UTC, sbernhard approved these changes
LGTM

2023-06-27 10:20 UTC, ekohl approved these changes

2023-06-27 10:20 UTC, merged