[WIP] Fixes #36350 - Add line breaks to long bookmarks
theforeman/foreman pull request #9758
Opened 2023-06-28 08:38 UTC by kmalyjur

The dropdown was stretching with long names and it was overflowing the page too much:
![long-bookmark-name](https://github.com/theforeman/foreman/assets/78563507/fb77955e-ea2a-462f-988a-45ecf9123c99)

Now the dropdown shrinks and the words break if it is too long so that it is nicely visible:
![image](https://github.com/theforeman/foreman/assets/78563507/bd057639-97b2-435e-8a46-493893c9f8d3)

This is a quick resolution that could be redone in the future.

2023-06-28 11:29 UTC, ofedoren commented
Could we do it a bit differently? I mean, if there are multiple long names then they will just take a lot of vertical space. So nothing is changed, but the direction of wasted space.

Maybe we could try using ellipsis here? Just crop the line after few characters and put the rest into tooltip.

2023-06-28 12:38 UTC, ares commented
I think the ellipsis was used before we started with any bookmark changes and the user feedback was, that they need to see the whole bookmark name. Seeing just the beginning does not help too much. I think this is a good compromise, it's still readable (not extremely long line) and contains the whole name. Hoes does it look like, when there's 100 bookmarks like this (I think the reporting user had around 100 of them), is it scrollable? If so, I'm :+1:

2023-06-28 14:43 UTC, ofedoren commented
> Seeing just the beginning does not help too much. 

I agree, that's why I suggested tooltip with the rest (or the full name even). But since users want to deal with scrolling, who am I to be against that :no_mouth:

2023-07-03 13:53 UTC, kmalyjur commented
> How does it look like, when there's 100 bookmarks like this (I think the reporting user had around 100 of them), is it scrollable?

Yes, the page is scrollable when the dropdown is long.

However, after testing it more, I found this issue, so I'm now working on fixing it.
![image](https://github.com/theforeman/foreman/assets/78563507/fd247859-7e3e-443e-8c8d-04191498af57)

2023-07-20 09:27 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/PF4/Bookmarks/BookmarkItems.js
> +  const hasLongerName = bookmarks.some(bookmark => bookmark.name.length > 90);
Can you do this check also for `errorItem`?

2023-08-11 13:53 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/PF4/Bookmarks/BookmarkItems.js
> +    className={`bookmarks-dropdown-item ${errors > 90 ? 'expanded' : ''}`}
Should be `errors.length`

2023-08-11 13:54 UTC, MariaAga requested changes
Can you please change the class name `expanded` to something more specific to the bookmarks? just in case there would be another rule from somewhere for `expanded` classnames

2023-08-25 10:04 UTC, MariaAga approved these changes
Everything looks good, Thanks!

2023-08-25 10:04 UTC, merged