Fixes #36537 - Fix for setting search returning 500
theforeman/foreman pull request #9783
Opened 2023-07-28 12:09 UTC by girijaasoni

This is a temporary fix. The description column being removed in this PR "https://github.com/theforeman/foreman/blob/develop/db/migrate/20220124174632_drop_setting_fields.rb" caused the issue. As a temporary fix, we are removing the description search.

2023-08-01 06:12 UTC, stejskalleos commented
ok to test

2023-08-01 13:06 UTC, ekohl requested changes
Descriptions of commits matter and this is not a clear description. I'd also argue this is not a fix for https://projects.theforeman.org/issues/36537. In that case we use `Refs`.

I suspect this was introduced in de56ffb2806473db9dc0cfd1f13d38076c7e56ea.

So I'd suggest:

```
Refs #36537 - Drop description from setting search

The description is no longer a field so it can't be searched anymore. This is
not a real fix, but prevents internal server errors on the settings search.

Fixes: de56ffb28064 ("Fixes #34305 - stop creating settings in DB (#9050)")
```

And I wonder if the real fix isn't to add `:description` to the `delegate` statement.

2023-08-02 07:31 UTC, girijaasoni commented
> Descriptions of commits matter and this is not a clear description. I'd also argue this is not a fix for https://projects.theforeman.org/issues/36537. In that case we use `Refs`.
> 
> I suspect this was introduced in [de56ffb](https://github.com/theforeman/foreman/commit/de56ffb2806473db9dc0cfd1f13d38076c7e56ea).
> 
> So I'd suggest:
> 
> ```
> Refs #36537 - Drop description from setting search
> 
> The description is no longer a field so it can't be searched anymore. This is
> not a real fix, but prevents internal server errors on the settings search.
> 
> Fixes: de56ffb28064 ("Fixes #34305 - stop creating settings in DB (#9050)")
> ```
> 
> And I wonder if the real fix isn't to add `:description` to the `delegate` statement.

Thanks @ekohl :)

2023-08-03 10:44 UTC, stejskalleos commented
@girijaasoni Code looks good, but what @ekohl is suggesting in the previous comment is changing the commit message itself, not just the description of PR.
I mean it's not bad to have an updated PR description as well, but more important is the commit message, because later when you go over the commits and history of the repo (aka `git log`, `git blame`, ...) you don't see description of the PR, just the commit's description.

2023-08-04 08:46 UTC, girijaasoni commented
> @girijaasoni Code looks good, but what @ekohl is suggesting in the previous comment is changing the commit message itself, not just the description of PR. I mean it's not bad to have an updated PR description as well, but more important is the commit message, because later when you go over the commits and history of the repo (aka `git log`, `git blame`, ...) you don't see description of the PR, just the commit's description.

Thanks @stejskalleos , updated it :D

2023-08-07 10:54 UTC, stejskalleos commented
> Thanks @stejskalleos , updated it :D

Are you sure? Looks same to me: https://github.com/theforeman/foreman/pull/9783/commits/6dd4763a1954cb522f5e46ab05801d7067521fca

2023-08-07 12:18 UTC, stejskalleos commented
[test katello]

2023-08-07 12:53 UTC, stejskalleos approved these changes
Katello job is failing on `test/models/rpm_test.rb:50` ([link](https://github.com/Katello/katello/blob/master/test/models/rpm_test.rb#L47)), but looking at the test I don't think it's related to these changes.

@ekohl any other comments, I'm :green_apple: to merge

2023-08-08 10:12 UTC, ekohl approved these changes

2023-08-08 10:12 UTC, merged