Fixes #36734 - Hide double title on Register Host page
theforeman/foreman pull request #9830
Opened 2023-09-13 09:54 UTC by kmalyjur

![image](https://github.com/theforeman/foreman/assets/78563507/93a5e625-6f2d-4467-b624-24453fddb5ec)

Changed PageLayout so that breadcrumb, title, search bar and toolbar buttons work together even if some of the elements are missing.

2023-09-15 16:01 UTC, MariaAga requested changes

2023-09-15 16:01 UTC, MariaAga commented on webpack/assets/javascripts/react_app/routes/common/PageLayout/PageLayout.js
> +      <Text ouiaId="title" component="h1">
Can you keep it `breadcrumb_title`?

2023-09-18 10:58 UTC, MariaAga commented
@kmalyjur test failures look related

2023-09-19 10:13 UTC, kmalyjur commented
I added an additional `PageSection` for the title mainly because of the case when breadcrumb and search bar are present, and it also fixes the previous failures elegantly.

2023-09-19 11:02 UTC, MariaAga commented
can you please move the conditions to not show the page sections? so we wont end up with extra empty page sections that add space before the title.
Also, integration test failures are related.

2023-09-19 11:51 UTC, MariaAga approved these changes

2023-09-19 11:51 UTC, merged

2023-09-19 11:51 UTC, MariaAga commented
Thanks!