Fixes #36847 - Rename initrd for Debian
theforeman/foreman pull request #9870
Opened 2023-10-20 09:45 UTC by obol89

`initrd` in official Debian repositories has `.gz` extension, not `.img` as it is in the template currently.

2023-10-20 10:53 UTC, ekohl commented
ok to test

I've verified the URLs provided in https://projects.theforeman.org/issues/36847 so I think this is correct.

2023-10-20 11:11 UTC, ekohl approved these changes

2023-10-30 09:37 UTC, sbernhard submitted a review, later dismissed

2023-10-30 12:01 UTC, ekohl requested changes
Test failures are relevant: the snapshots need to be updated.

2023-12-05 13:39 UTC, sbernhard commented
Can you please update the snapshots @obol89 

It should only be about these 2 files. Should be easys to update them manually on disk without recording the snapshots completely:
-  https://github.com/theforeman/foreman/blob/develop/test/unit/foreman/renderer/snapshots/ProvisioningTemplate/iPXE/Preseed_default_iPXE.ubuntu4dhcp.snap.txt
-https://github.com/theforeman/foreman/blob/develop/test/unit/foreman/renderer/snapshots/ProvisioningTemplate/iPXE/Preseed_default_iPXE.debian4dhcp.snap.txt

2023-12-14 09:36 UTC, obol89 commented
> Can you please update the snapshots @obol89
> 
> It should only be about these 2 files. Should be easys to update them manually on disk without recording the snapshots completely:
> 
> https://github.com/theforeman/foreman/blob/develop/test/unit/foreman/renderer/snapshots/ProvisioningTemplate/iPXE/Preseed_default_iPXE.ubuntu4dhcp.snap.txt https://github.com/theforeman/foreman/blob/develop/test/unit/foreman/renderer/snapshots/ProvisioningTemplate/iPXE/Preseed_default_iPXE.debian4dhcp.snap.txt

I just updated the files. I'm not sure if I did it correctly from the merge request / github perspective, but please let me know if there is anything else to do.

2023-12-22 14:02 UTC, sbernhard approved these changes

2023-12-28 08:24 UTC, sbernhard commented
Ready to merge @ekohl ?

2024-01-02 16:00 UTC, ekohl requested changes
Checking versions:
* Debian 10: https://ftp.debian.org/debian/dists/buster/main/installer-amd64/current/images/netboot/debian-installer/amd64/
* Debian 11: https://ftp.debian.org/debian/dists/bullseye/main/installer-amd64/current/images/netboot/debian-installer/amd64/
* Debian 12: https://ftp.debian.org/debian/dists/bookworm/main/installer-amd64/current/images/netboot/debian-installer/amd64/

So all supported Debian versions have this.

It's also weird we have a line `initrd` below it which is correct. Looks like the specific line was introduced in 91de02799027ac36ab877737ef69c96b221ccb64. That came from https://github.com/theforeman/community-templates/commit/8deda37c0b0336357e0fe567a675910655619747. In https://github.com/theforeman/community-templates/pull/496 it is explicitly discussed, but I suppose nobody verified it for Debian.

2024-01-02 16:00 UTC, ekohl commented on test/unit/foreman/renderer/snapshots/ProvisioningTemplate/iPXE/Preseed_default_iPXE.debian4dhcp.snap.txt
> +kernel http://ftp.debian.org/debian/dists/wheezy/main/installer-amd64/current/images/netboot/debian-installer/amd64/linux initrd=initrd.gz interface=auto url=http://foreman.example.com/unattended/pro
We should really update our tests to have something newer than Wheezy, but that's outside the scope of this PR so I opened https://github.com/theforeman/foreman/pull/9972.

2024-01-02 16:00 UTC, ekohl commented on app/views/unattended/provisioning_templates/iPXE/preseed_default_ipxe.erb
> +kernel <%= kernel %> initrd=initrd.gz interface=auto url=<%= url %> ramdisk_size=10800 root=/dev/rd/0 rw auto <%= snippet("preseed_kernel_options", variables: {ipxe_net: true}).strip %>
Why doesn't this use the `initrd` variable that's defined on line 37? Shouldn't it be:
```suggestion
kernel <%= kernel %> initrd=<%= initrd %> interface=auto url=<%= url %> ramdisk_size=10800 root=/dev/rd/0 rw auto <%= snippet("preseed_kernel_options", variables: {ipxe_net: true}).strip %>
```

I'd expect it to then correctly use this code:
https://github.com/theforeman/foreman/blob/a1142ab9ef500e3206be1ff8a390431bc1b32de3/app/models/operatingsystems/debian.rb#L2

2024-01-02 16:00 UTC, ekohl commented on test/unit/foreman/renderer/snapshots/ProvisioningTemplate/iPXE/Preseed_default_iPXE.ubuntu4dhcp.snap.txt
> -kernel http://archive.ubuntu.com/ubuntu/dists/focal/main/installer-amd64/current/images/netboot/ubuntu-installer/amd64/linux initrd=initrd.img interface=auto url=http://foreman.example.com/unattended
Confusingly enough, this combination is never valid. For Focal you only have `legacy-images` and that directory only has `boot.img.gz`, not `initrd.*`.

2024-04-26 08:57 UTC, ekohl commented
I'm going to reopen this because I think it's still needed.

2024-05-10 12:33 UTC, sbernhard commented
[test]

2024-05-10 13:18 UTC, ekohl commented
I opened https://github.com/theforeman/foreman/pull/10156 with https://github.com/theforeman/foreman/pull/9870#discussion_r1439551408 and resolved the merge conflicts.

2024-08-17 01:50 UTC, closed without merging