Fixes #36858 - Table index page design changes
theforeman/foreman pull request #9873
Opened 2023-10-24 16:49 UTC by MariaAga

* Remove some padding between sections according to: https://www.sketch.com/s/7c65523b-3b2b-4fbd-b785-9d323dac6b95/a/52Ryg1P
* add isHoverable and isStriped to the table

![Screenshot from 2023-10-24 18-44-35](https://github.com/theforeman/foreman/assets/30431079/82e9db8e-013f-4719-a188-439d022df680)

2023-10-26 11:17 UTC, kmalyjur requested changes

2023-10-26 11:17 UTC, kmalyjur commented on webpack/assets/javascripts/react_app/components/PF4/TableIndexPage/TableIndexPage.scss
> +    padding-left: 0;
I think it's missing `padding-right`. Otherwise, everything looks good to me.

2023-10-30 12:37 UTC, MariaAga commented on webpack/assets/javascripts/react_app/components/PF4/TableIndexPage/TableIndexPage.scss
> +    padding-left: 0;
added, thanks!

2023-10-31 11:03 UTC, kmalyjur approved these changes

2023-10-31 11:35 UTC, ekohl approved these changes
I haven't tested this myself, but the changes look sensible and I'm trusting @kmalyjur's approval here.

2023-10-31 11:35 UTC, merged