Allow for deployment of puppet 8. Fixes #36939
theforeman/foreman pull request #9915
Opened 2023-11-23 02:25 UTC by trenta

Modified templates in unattended/provisioning_templates adding the option to deploy with puppet 8. \

2023-11-23 12:06 UTC, ekohl requested changes
Thanks for this. Small whitespace suggestions, but otherwise it looks good to me.

2023-11-23 12:06 UTC, ekohl commented on app/views/unattended/provisioning_templates/provision/kickstart_default.erb
> +<% if host_param_true?('enable-puppetlabs-repo') ||host_param_true?('enable-official-puppet8-repo') || host_param_true?('enable-official-puppet7-repo') || host_param_true?('enable-puppetlabs-puppet6-
```suggestion
<% if host_param_true?('enable-puppetlabs-repo') || host_param_true?('enable-official-puppet8-repo') || host_param_true?('enable-official-puppet7-repo') || host_param_true?('enable-puppetlabs-puppet6-repo')|| host_param_true?('enable-puppetlabs-puppet5-repo') -%>
```

2023-11-23 12:06 UTC, ekohl commented on app/views/unattended/provisioning_templates/user_data/autoyast_default_user_data.erb
> +<% if  host_param_true?('enable-official-puppet8-repo') || host_param_true?('enable-official-puppet7-repo') || host_param_true?('enable-puppetlabs-puppet6-repo') || host_param_true?('enable-puppetlab
```suggestion
<% if host_param_true?('enable-official-puppet8-repo') || host_param_true?('enable-official-puppet7-repo') || host_param_true?('enable-puppetlabs-puppet6-repo') || host_param_true?('enable-puppetlabs-puppet5-repo') -%>
```

2023-11-24 00:23 UTC, trenta commented
Do you need me to fix the white spaces or will the person doing the merge do it then?

2023-11-24 19:31 UTC, ekohl commented
Please fix up the commit. We had too many people who used the squash function wrong that we've disabled it.

2023-11-24 21:11 UTC, trenta commented
I get that. I'm probably one of those people. My git skills leave a lot to be desired. I've pushed the changes.

2023-11-25 12:04 UTC, ekohl approved these changes

2023-11-25 12:04 UTC, ekohl commented
ok to test

2023-11-26 13:10 UTC, merged